(function(b,a){a(["./kendo.core"],b);
})(function(){(function(){(function(a,l,m){var f=function(u){var o=this,p=f.formats,t,s,r,q,n;
if(arguments.length===1){u=o.resolveColor(u);
for(q=0;
q<p.length;
q++){t=p[q].re;
s=p[q].process;
r=t.exec(u);
if(r){n=s(r);
o.r=n[0];
o.g=n[1];
o.b=n[2];
}}}else{o.r=arguments[0];
o.g=arguments[1];
o.b=arguments[2];
}o.r=o.normalizeByte(o.r);
o.g=o.normalizeByte(o.g);
o.b=o.normalizeByte(o.b);
};
f.prototype={toHex:function(){var n=this,p=n.padDigit,q=n.r.toString(16),o=n.g.toString(16),i=n.b.toString(16);
return"#"+p(q)+p(o)+p(i);
},resolveColor:function(i){i=i||"black";
if(i.charAt(0)=="#"){i=i.substr(1,6);
}i=i.replace(/ /g,"");
i=i.toLowerCase();
i=f.namedColors[i]||i;
return i;
},normalizeByte:function(i){return(i<0||isNaN(i))?0:((i>255)?255:i);
},padDigit:function(i){return(i.length===1)?"0"+i:i;
},brightness:function(o){var i=this,n=Math.round;
i.r=n(i.normalizeByte(i.r*o));
i.g=n(i.normalizeByte(i.g*o));
i.b=n(i.normalizeByte(i.b*o));
return i;
},percBrightness:function(){var i=this;
return Math.sqrt(0.241*i.r*i.r+0.691*i.g*i.g+0.06800000000000001*i.b*i.b);
}};
f.formats=[{re:/^rgb\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/,process:function(i){return[m(i[1],10),m(i[2],10),m(i[3],10)];
}},{re:/^(\w{2})(\w{2})(\w{2})$/,process:function(i){return[m(i[1],16),m(i[2],16),m(i[3],16)];
}},{re:/^(\w{1})(\w{1})(\w{1})$/,process:function(i){return[m(i[1]+i[1],16),m(i[2]+i[2],16),m(i[3]+i[3],16)];
}}];
f.namedColors={aliceblue:"f0f8ff",antiquewhite:"faebd7",aqua:"00ffff",aquamarine:"7fffd4",azure:"f0ffff",beige:"f5f5dc",bisque:"ffe4c4",black:"000000",blanchedalmond:"ffebcd",blue:"0000ff",blueviolet:"8a2be2",brown:"a52a2a",burlywood:"deb887",cadetblue:"5f9ea0",chartreuse:"7fff00",chocolate:"d2691e",coral:"ff7f50",cornflowerblue:"6495ed",cornsilk:"fff8dc",crimson:"dc143c",cyan:"00ffff",darkblue:"00008b",darkcyan:"008b8b",darkgoldenrod:"b8860b",darkgray:"a9a9a9",darkgrey:"a9a9a9",darkgreen:"006400",darkkhaki:"bdb76b",darkmagenta:"8b008b",darkolivegreen:"556b2f",darkorange:"ff8c00",darkorchid:"9932cc",darkred:"8b0000",darksalmon:"e9967a",darkseagreen:"8fbc8f",darkslateblue:"483d8b",darkslategray:"2f4f4f",darkslategrey:"2f4f4f",darkturquoise:"00ced1",darkviolet:"9400d3",deeppink:"ff1493",deepskyblue:"00bfff",dimgray:"696969",dimgrey:"696969",dodgerblue:"1e90ff",firebrick:"b22222",floralwhite:"fffaf0",forestgreen:"228b22",fuchsia:"ff00ff",gainsboro:"dcdcdc",ghostwhite:"f8f8ff",gold:"ffd700",goldenrod:"daa520",gray:"808080",grey:"808080",green:"008000",greenyellow:"adff2f",honeydew:"f0fff0",hotpink:"ff69b4",indianred:"cd5c5c",indigo:"4b0082",ivory:"fffff0",khaki:"f0e68c",lavender:"e6e6fa",lavenderblush:"fff0f5",lawngreen:"7cfc00",lemonchiffon:"fffacd",lightblue:"add8e6",lightcoral:"f08080",lightcyan:"e0ffff",lightgoldenrodyellow:"fafad2",lightgray:"d3d3d3",lightgrey:"d3d3d3",lightgreen:"90ee90",lightpink:"ffb6c1",lightsalmon:"ffa07a",lightseagreen:"20b2aa",lightskyblue:"87cefa",lightslategray:"778899",lightslategrey:"778899",lightsteelblue:"b0c4de",lightyellow:"ffffe0",lime:"00ff00",limegreen:"32cd32",linen:"faf0e6",magenta:"ff00ff",maroon:"800000",mediumaquamarine:"66cdaa",mediumblue:"0000cd",mediumorchid:"ba55d3",mediumpurple:"9370d8",mediumseagreen:"3cb371",mediumslateblue:"7b68ee",mediumspringgreen:"00fa9a",mediumturquoise:"48d1cc",mediumvioletred:"c71585",midnightblue:"191970",mintcream:"f5fffa",mistyrose:"ffe4e1",moccasin:"ffe4b5",navajowhite:"ffdead",navy:"000080",oldlace:"fdf5e6",olive:"808000",olivedrab:"6b8e23",orange:"ffa500",orangered:"ff4500",orchid:"da70d6",palegoldenrod:"eee8aa",palegreen:"98fb98",paleturquoise:"afeeee",palevioletred:"d87093",papayawhip:"ffefd5",peachpuff:"ffdab9",peru:"cd853f",pink:"ffc0cb",plum:"dda0dd",powderblue:"b0e0e6",purple:"800080",red:"ff0000",rosybrown:"bc8f8f",royalblue:"4169e1",saddlebrown:"8b4513",salmon:"fa8072",sandybrown:"f4a460",seagreen:"2e8b57",seashell:"fff5ee",sienna:"a0522d",silver:"c0c0c0",skyblue:"87ceeb",slateblue:"6a5acd",slategray:"708090",slategrey:"708090",snow:"fffafa",springgreen:"00ff7f",steelblue:"4682b4",tan:"d2b48c",teal:"008080",thistle:"d8bfd8",tomato:"ff6347",turquoise:"40e0d0",violet:"ee82ee",wheat:"f5deb3",white:"ffffff",whitesmoke:"f5f5f5",yellow:"ffff00",yellowgreen:"9acd32"};
var j=["transparent"];
for(var h in f.namedColors){if(f.namedColors.hasOwnProperty(h)){j.push(h);
}}j=new RegExp("^("+j.join("|")+")(\\W|$)","i");
function k(i,o){var n,p;
if(i==null||i=="none"){return null;
}if(i instanceof c){return i;
}i=i.toLowerCase();
if((n=j.exec(i))){if(n[1]=="transparent"){i=new e(1,1,1,0);
}else{i=k(f.namedColors[n[1]],o);
}i.match=[n[1]];
return i;
}if((n=/^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})\b/i.exec(i))){p=new b(m(n[1],16),m(n[2],16),m(n[3],16),1);
}else{if((n=/^#?([0-9a-f])([0-9a-f])([0-9a-f])\b/i.exec(i))){p=new b(m(n[1]+n[1],16),m(n[2]+n[2],16),m(n[3]+n[3],16),1);
}else{if((n=/^rgb\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\)/.exec(i))){p=new b(m(n[1],10),m(n[2],10),m(n[3],10),1);
}else{if((n=/^rgba\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9.]+)\s*\)/.exec(i))){p=new b(m(n[1],10),m(n[2],10),m(n[3],10),l(n[4]));
}else{if((n=/^rgb\(\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*\)/.exec(i))){p=new e(l(n[1])/100,l(n[2])/100,l(n[3])/100,1);
}else{if((n=/^rgba\(\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9.]+)\s*\)/.exec(i))){p=new e(l(n[1])/100,l(n[2])/100,l(n[3])/100,l(n[4]));
}}}}}}if(p){p.match=n;
}else{if(!o){throw new Error("Cannot parse color: "+i);
}}return p;
}function g(i,p,o){if(!o){o="0";
}i=i.toString(16);
while(p>i.length){i="0"+i;
}return i;
}var c=kendo.Class.extend({toHSV:function(){return this;
},toRGB:function(){return this;
},toHex:function(){return this.toBytes().toHex();
},toBytes:function(){return this;
},toCss:function(){return"#"+this.toHex();
},toCssRgba:function(){var i=this.toBytes();
return"rgba("+i.r+", "+i.g+", "+i.b+", "+l((+this.a).toFixed(3))+")";
},toDisplay:function(){if(kendo.support.browser.msie&&kendo.support.browser.version<9){return this.toCss();
}return this.toCssRgba();
},equals:function(i){return i===this||i!==null&&this.toCssRgba()==k(i).toCssRgba();
},diff:function(n){if(n==null){return NaN;
}var i=this.toBytes();
n=n.toBytes();
return Math.sqrt(Math.pow((i.r-n.r)*0.3,2)+Math.pow((i.g-n.g)*0.59,2)+Math.pow((i.b-n.b)*0.11,2));
},clone:function(){var i=this.toBytes();
if(i===this){i=new b(i.r,i.g,i.b,i.a);
}return i;
}});
var e=c.extend({init:function(p,o,n,i){this.r=p;
this.g=o;
this.b=n;
this.a=i;
},toHSV:function(){var t,q,n,p,w,x;
var u=this.r,o=this.g,i=this.b;
t=Math.min(u,o,i);
q=Math.max(u,o,i);
x=q;
n=q-t;
if(n===0){return new d(0,0,x,this.a);
}if(q!==0){w=n/q;
if(u==q){p=(o-i)/n;
}else{if(o==q){p=2+(i-u)/n;
}else{p=4+(u-o)/n;
}}p*=60;
if(p<0){p+=360;
}}else{w=0;
p=-1;
}return new d(p,w,x,this.a);
},toBytes:function(){return new b(this.r*255,this.g*255,this.b*255,this.a);
}});
var b=e.extend({init:function(p,o,n,i){this.r=Math.round(p);
this.g=Math.round(o);
this.b=Math.round(n);
this.a=i;
},toRGB:function(){return new e(this.r/255,this.g/255,this.b/255,this.a);
},toHSV:function(){return this.toRGB().toHSV();
},toHex:function(){return g(this.r,2)+g(this.g,2)+g(this.b,2);
},toBytes:function(){return this;
}});
var d=c.extend({init:function(n,o,p,i){this.h=n;
this.s=o;
this.v=p;
this.a=i;
},toRGB:function(){var w=this.h,B=this.s,D=this.v;
var x,A,u,n,o,y,z,C;
if(B===0){A=u=n=D;
}else{w/=60;
x=Math.floor(w);
o=w-x;
y=D*(1-B);
z=D*(1-B*o);
C=D*(1-B*(1-o));
switch(x){case 0:A=D;
u=C;
n=y;
break;
case 1:A=z;
u=D;
n=y;
break;
case 2:A=y;
u=D;
n=C;
break;
case 3:A=y;
u=z;
n=D;
break;
case 4:A=C;
u=y;
n=D;
break;
default:A=D;
u=y;
n=z;
break;
}}return new e(A,u,n,this.a);
},toBytes:function(){return this.toRGB().toBytes();
}});
f.fromBytes=function(p,o,n,i){return new b(p,o,n,i!=null?i:1);
};
f.fromRGB=function(p,o,n,i){return new e(p,o,n,i!=null?i:1);
};
f.fromHSV=function(n,o,p,i){return new d(n,o,p,i!=null?i:1);
};
kendo.Color=f;
kendo.parseColor=k;
})(window.kendo.jQuery,parseFloat,parseInt);
})();
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
