(function(b,a){a([],b);
})(function(){(function(){(function(a,aO,aK){var W=aO.kendo=aO.kendo||{cultures:{}},C=a.extend,t=a.each,P=a.isArray,at=a.proxy,ae=a.noop,aa=Math,aE,T=aO.JSON||{},aD={},ap=/%/,E=/\{(\d+)(:[^\}]+)?\}/g,i=/(\d+(?:\.?)\d*)px\s*(\d+(?:\.?)\d*)px\s*(\d+(?:\.?)\d*)px\s*(\d+)?/i,ah=/^(\+|-?)\d+(\.?)\d*$/,F="function",aC="string",ag="number",ai="object",af="null",h="boolean",aL="undefined",L={},ay={},aB=[].slice,M=aO.Globalize;
W.version="2015.3.929";
function j(){}j.extend=function(aV){var aS=function(){},aU,aX=this,aW=aV&&aV.init?aV.init:function(){aX.apply(this,arguments);
},aT;
aS.prototype=aX.prototype;
aT=aW.fn=aW.prototype=new aS();
for(aU in aV){if(aV[aU]!=null&&aV[aU].constructor===Object){aT[aU]=C(true,{},aS.prototype[aU],aV[aU]);
}else{aT[aU]=aV[aU];
}}aT.constructor=aW;
aW.extend=aX.extend;
return aW;
};
j.prototype._initOptions=function(aS){this.options=q({},this.options,aS);
};
var R=W.isFunction=function(aS){return typeof aS==="function";
};
var ar=function(){this._defaultPrevented=true;
};
var Q=function(){return this._defaultPrevented===true;
};
var aj=j.extend({init:function(){this._events={};
},bind:function(aS,aW,a0){var a2=this,aY,aT=typeof aS===aC?[aS]:aS,aZ,a1,aV,aX=typeof aW===F,aU;
if(aW===aK){for(aY in aS){a2.bind(aY,aS[aY]);
}return a2;
}for(aY=0,aZ=aT.length;
aY<aZ;
aY++){aS=aT[aY];
aV=aX?aW:aW[aS];
if(aV){if(a0){a1=aV;
aV=function(){a2.unbind(aS,aV);
a1.apply(a2,arguments);
};
aV.original=a1;
}aU=a2._events[aS]=a2._events[aS]||[];
aU.push(aV);
}}return a2;
},one:function(aS,aT){return this.bind(aS,aT,true);
},first:function(aS,aW){var a0=this,aY,aT=typeof aS===aC?[aS]:aS,aZ,aV,aX=typeof aW===F,aU;
for(aY=0,aZ=aT.length;
aY<aZ;
aY++){aS=aT[aY];
aV=aX?aW:aW[aS];
if(aV){aU=a0._events[aS]=a0._events[aS]||[];
aU.unshift(aV);
}}return a0;
},trigger:function(aT,aS){var aX=this,aU=aX._events[aT],aV,aW;
if(aU){aS=aS||{};
aS.sender=aX;
aS._defaultPrevented=false;
aS.preventDefault=ar;
aS.isDefaultPrevented=Q;
aU=aU.slice();
for(aV=0,aW=aU.length;
aV<aW;
aV++){aU[aV].call(aX,aS);
}return aS._defaultPrevented===true;
}return false;
},unbind:function(aS,aU){var aW=this,aT=aW._events[aS],aV;
if(aS===aK){aW._events={};
}else{if(aT){if(aU){for(aV=aT.length-1;
aV>=0;
aV--){if(aT[aV]===aU||aT[aV].original===aU){aT.splice(aV,1);
}}}else{aW._events[aS]=[];
}}}return aW;
}});
function k(aT,aV){if(aV){return"'"+aT.split("'").join("\\'").split('\\"').join('\\\\\\"').replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\t/g,"\\t")+"'";
}else{var aS=aT.charAt(0),aU=aT.substring(1);
if(aS==="="){return"+("+aU+")+";
}else{if(aS===":"){return"+$kendoHtmlEncode("+aU+")+";
}else{return";"+aT+";$kendoOutput+=";
}}}}var g=/^\w+/,v=/\$\{([^}]*)\}/g,w=/\\\}/g,n=/__CURLY__/g,x=/\\#/g,az=/__SHARP__/g,aR=["","0","00","000","0000"];
aE={paramName:"data",useWithBlock:true,render:function(aW,aS){var aU,aV,aT="";
for(aU=0,aV=aS.length;
aU<aV;
aU++){aT+=aW(aS[aU]);
}return aT;
},compile:function(a1,aX){var a0=C({},this,aX),aY=a0.paramName,aS=aY.match(g)[0],a2=a0.useWithBlock,aV="var $kendoOutput, $kendoHtmlEncode = kendo.htmlEncode;",aU,aZ,aW;
if(R(a1)){return a1;
}aV+=a2?"with("+aY+"){":"";
aV+="$kendoOutput=";
aZ=a1.replace(w,"__CURLY__").replace(v,"#=$kendoHtmlEncode($1)#").replace(n,"}").replace(x,"__SHARP__").split("#");
for(aW=0;
aW<aZ.length;
aW++){aV+=k(aZ[aW],aW%2===0);
}aV+=a2?";}":";";
aV+="return $kendoOutput;";
aV=aV.replace(az,"#");
try{aU=new Function(aS,aV);
aU._slotCount=Math.floor(aZ.length/2);
return aU;
}catch(aT){throw new Error(W.format("Invalid template:'{0}' Generated code:'{1}'",a1,aV));
}}};
function al(aU,aS,aT){aU=aU+"";
aS=aS||2;
aT=aS-aU.length;
if(aT){return aR[aS].substring(0,aT)+aU;
}return aU;
}(function(){var aS=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,aT,aU,aV={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},aX,aZ={}.toString;
if(typeof Date.prototype.toJSON!==F){Date.prototype.toJSON=function(){var a0=this;
return isFinite(a0.valueOf())?al(a0.getUTCFullYear(),4)+"-"+al(a0.getUTCMonth()+1)+"-"+al(a0.getUTCDate())+"T"+al(a0.getUTCHours())+":"+al(a0.getUTCMinutes())+":"+al(a0.getUTCSeconds())+"Z":null;
};
String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf();
};
}function aW(a0){aS.lastIndex=0;
return aS.test(a0)?'"'+a0.replace(aS,function(a1){var a2=aV[a1];
return typeof a2===aC?a2:"\\u"+("0000"+a1.charCodeAt(0).toString(16)).slice(-4);
})+'"':'"'+a0+'"';
}function aY(a3,a0){var a1,a2,a8,a4,a5=aT,a6,a9=a0[a3],a7;
if(a9&&typeof a9===ai&&typeof a9.toJSON===F){a9=a9.toJSON(a3);
}if(typeof aX===F){a9=aX.call(a0,a3,a9);
}a7=typeof a9;
if(a7===aC){return aW(a9);
}else{if(a7===ag){return isFinite(a9)?String(a9):af;
}else{if(a7===h||a7===af){return String(a9);
}else{if(a7===ai){if(!a9){return af;
}aT+=aU;
a6=[];
if(aZ.apply(a9)==="[object Array]"){a4=a9.length;
for(a1=0;
a1<a4;
a1++){a6[a1]=aY(a1,a9)||af;
}a8=a6.length===0?"[]":aT?"[\n"+aT+a6.join(",\n"+aT)+"\n"+a5+"]":"["+a6.join(",")+"]";
aT=a5;
return a8;
}if(aX&&typeof aX===ai){a4=aX.length;
for(a1=0;
a1<a4;
a1++){if(typeof aX[a1]===aC){a2=aX[a1];
a8=aY(a2,a9);
if(a8){a6.push(aW(a2)+(aT?": ":":")+a8);
}}}}else{for(a2 in a9){if(Object.hasOwnProperty.call(a9,a2)){a8=aY(a2,a9);
if(a8){a6.push(aW(a2)+(aT?": ":":")+a8);
}}}}a8=a6.length===0?"{}":aT?"{\n"+aT+a6.join(",\n"+aT)+"\n"+a5+"}":"{"+a6.join(",")+"}";
aT=a5;
return a8;
}}}}}if(typeof T.stringify!==F){T.stringify=function(a3,a1,a2){var a0;
aT="";
aU="";
if(typeof a2===ag){for(a0=0;
a0<a2;
a0+=1){aU+=" ";
}}else{if(typeof a2===aC){aU=a2;
}}aX=a1;
if(a1&&typeof a1!==F&&(typeof a1!==ai||typeof a1.length!==ag)){throw new Error("JSON.stringify");
}return aY("",{"":a3});
};
}})();
(function(){var aU=/dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|HH|H|hh|h|mm|m|fff|ff|f|tt|ss|s|zzz|zz|z|"[^"]*"|'[^']*'/g,a8=/^(n|c|p|e)(\d*)$/i,a2=/(\\.)|(['][^']*[']?)|(["][^"]*["]?)/g,aT=/\,/g,aV="",a5=".",aS=",",a7="#",ba="0",a4="??",aW="en-US",a3={}.toString;
W.cultures["en-US"]={name:aW,numberFormat:{pattern:["-n"],decimals:2,",":",",".":".",groupSize:[3],percent:{pattern:["-n %","n %"],decimals:2,",":",",".":".",groupSize:[3],symbol:"%"},currency:{name:"US Dollar",abbr:"USD",pattern:["($n)","$n"],decimals:2,",":",",".":".",groupSize:[3],symbol:"$"}},calendars:{standard:{days:{names:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],namesAbbr:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],namesShort:["Su","Mo","Tu","We","Th","Fr","Sa"]},months:{names:["January","February","March","April","May","June","July","August","September","October","November","December"],namesAbbr:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},AM:["AM","am","AM"],PM:["PM","pm","PM"],patterns:{d:"M/d/yyyy",D:"dddd, MMMM dd, yyyy",F:"dddd, MMMM dd, yyyy h:mm:ss tt",g:"M/d/yyyy h:mm tt",G:"M/d/yyyy h:mm:ss tt",m:"MMMM dd",M:"MMMM dd",s:"yyyy'-'MM'-'ddTHH':'mm':'ss",t:"h:mm tt",T:"h:mm:ss tt",u:"yyyy'-'MM'-'dd HH':'mm':'ss'Z'",y:"MMMM, yyyy",Y:"MMMM, yyyy"},"/":"/",":":":",firstDay:0,twoDigitYearMax:2029}}};
function aY(bb){if(bb){if(bb.numberFormat){return bb;
}if(typeof bb===aC){var bc=W.cultures;
return bc[bb]||bc[bb.split("-")[0]]||null;
}return null;
}return null;
}function a1(bb){if(bb){bb=aY(bb);
}return bb||W.cultures.current;
}function aX(bb){bb.groupSizes=bb.groupSize;
bb.percent.groupSizes=bb.percent.groupSize;
bb.currency.groupSizes=bb.currency.groupSize;
}W.culture=function(bc){var bd=W.cultures,bb;
if(bc!==aK){bb=aY(bc)||bd[aW];
bb.calendar=bb.calendars.standard;
bd.current=bb;
if(M&&!M.load){aX(bb.numberFormat);
}}else{return bd.current;
}};
W.findCulture=aY;
W.getCulture=a1;
W.culture(aW);
function aZ(bd,bf,bc){bc=a1(bc);
var bb=bc.calendars.standard,be=bb.days,bg=bb.months;
bf=bb.patterns[bf]||bf;
return bf.replace(aU,function(bh){var bi;
var bj;
var bk;
if(bh==="d"){bj=bd.getDate();
}else{if(bh==="dd"){bj=al(bd.getDate());
}else{if(bh==="ddd"){bj=be.namesAbbr[bd.getDay()];
}else{if(bh==="dddd"){bj=be.names[bd.getDay()];
}else{if(bh==="M"){bj=bd.getMonth()+1;
}else{if(bh==="MM"){bj=al(bd.getMonth()+1);
}else{if(bh==="MMM"){bj=bg.namesAbbr[bd.getMonth()];
}else{if(bh==="MMMM"){bj=bg.names[bd.getMonth()];
}else{if(bh==="yy"){bj=al(bd.getFullYear()%100);
}else{if(bh==="yyyy"){bj=al(bd.getFullYear(),4);
}else{if(bh==="h"){bj=bd.getHours()%12||12;
}else{if(bh==="hh"){bj=al(bd.getHours()%12||12);
}else{if(bh==="H"){bj=bd.getHours();
}else{if(bh==="HH"){bj=al(bd.getHours());
}else{if(bh==="m"){bj=bd.getMinutes();
}else{if(bh==="mm"){bj=al(bd.getMinutes());
}else{if(bh==="s"){bj=bd.getSeconds();
}else{if(bh==="ss"){bj=al(bd.getSeconds());
}else{if(bh==="f"){bj=aa.floor(bd.getMilliseconds()/100);
}else{if(bh==="ff"){bj=bd.getMilliseconds();
if(bj>99){bj=aa.floor(bj/10);
}bj=al(bj);
}else{if(bh==="fff"){bj=al(bd.getMilliseconds(),3);
}else{if(bh==="tt"){bj=bd.getHours()<12?bb.AM[0]:bb.PM[0];
}else{if(bh==="zzz"){bi=bd.getTimezoneOffset();
bk=bi<0;
bj=aa.abs(bi/60).toString().split(".")[0];
bi=aa.abs(bi)-(bj*60);
bj=(bk?"+":"-")+al(bj);
bj+=":"+al(bi);
}else{if(bh==="zz"||bh==="z"){bj=bd.getTimezoneOffset()/60;
bk=bj<0;
bj=aa.abs(bj).toString().split(".")[0];
bj=(bk?"+":"-")+(bh==="zz"?al(bj):bj);
}}}}}}}}}}}}}}}}}}}}}}}}return bj!==aK?bj:bh.slice(1,bh.length-1);
});
}function a0(bA,bi,bc){bc=a1(bc);
var bB=bc.numberFormat,bn=bB.groupSize[0],bm=bB[aS],bf=bB[a5],bE=bB.decimals,bC=bB.pattern[0],by=[],bJ,bv,bw,be,bj,bz=bA<0,bt,bk,bu,bl,bF=aV,bK=aV,bs,bx,bb,bo,bp,bg,bG,bL,br,bq,bD,bd,bI,bH=-1,bh;
if(bA===aK){return aV;
}if(!isFinite(bA)){return bA;
}if(!bi){return bc.name.length?bA.toLocaleString():bA.toString();
}bj=a8.exec(bi);
if(bj){bi=bj[1].toLowerCase();
bv=bi==="c";
bw=bi==="p";
if(bv||bw){bB=bv?bB.currency:bB.percent;
bn=bB.groupSize[0];
bm=bB[aS];
bf=bB[a5];
bE=bB.decimals;
bJ=bB.symbol;
bC=bB.pattern[bz?0:1];
}be=bj[2];
if(be){bE=+be;
}if(bi==="e"){return be?bA.toExponential(bE):bA.toExponential();
}if(bw){bA*=100;
}bA=a6(bA,bE);
bz=bA<0;
bA=bA.split(a5);
bt=bA[0];
bk=bA[1];
if(bz){bt=bt.substring(1);
}bK=bt;
bu=bt.length;
if(bu>=bn){bK=aV;
for(bs=0;
bs<bu;
bs++){if(bs>0&&(bu-bs)%bn===0){bK+=bm;
}bK+=bt.charAt(bs);
}}if(bk){bK+=bf+bk;
}if(bi==="n"&&!bz){return bK;
}bA=aV;
for(bs=0,bx=bC.length;
bs<bx;
bs++){bb=bC.charAt(bs);
if(bb==="n"){bA+=bK;
}else{if(bb==="$"||bb==="%"){bA+=bJ;
}else{bA+=bb;
}}}return bA;
}if(bz){bA=-bA;
}if(bi.indexOf("'")>-1||bi.indexOf('"')>-1||bi.indexOf("\\")>-1){bi=bi.replace(a2,function(bN){var bO=bN.charAt(0).replace("\\",""),bM=bN.slice(1).replace(bO,"");
by.push(bM);
return a4;
});
}bi=bi.split(";");
if(bz&&bi[1]){bi=bi[1];
bp=true;
}else{if(bA===0){bi=bi[2]||bi[0];
if(bi.indexOf(a7)==-1&&bi.indexOf(ba)==-1){return bi;
}}else{bi=bi[0];
}}bD=bi.indexOf("%");
bd=bi.indexOf("$");
bw=bD!=-1;
bv=bd!=-1;
if(bw){bA*=100;
}if(bv&&bi[bd-1]==="\\"){bi=bi.split("\\").join("");
bv=false;
}if(bv||bw){bB=bv?bB.currency:bB.percent;
bn=bB.groupSize[0];
bm=bB[aS];
bf=bB[a5];
bE=bB.decimals;
bJ=bB.symbol;
}bo=bi.indexOf(aS)>-1;
if(bo){bi=bi.replace(aT,aV);
}bg=bi.indexOf(a5);
bx=bi.length;
if(bg!=-1){bk=bA.toString().split("e");
if(bk[1]){bk=a6(bA,Math.abs(bk[1]));
}else{bk=bk[0];
}bk=bk.split(a5)[1]||aV;
bL=bi.lastIndexOf(ba)-bg;
bG=bi.lastIndexOf(a7)-bg;
br=bL>-1;
bq=bG>-1;
bs=bk.length;
if(!br&&!bq){bi=bi.substring(0,bg)+bi.substring(bg+1);
bx=bi.length;
bg=-1;
bs=0;
}if(br&&bL>bG){bs=bL;
}else{if(bG>bL){if(bq&&bs>bG){bs=bG;
}else{if(br&&bs<bL){bs=bL;
}}}}if(bs>-1){bA=a6(bA,bs);
}}else{bA=a6(bA);
}bG=bi.indexOf(a7);
bI=bL=bi.indexOf(ba);
if(bG==-1&&bL!=-1){bH=bL;
}else{if(bG!=-1&&bL==-1){bH=bG;
}else{bH=bG>bL?bL:bG;
}}bG=bi.lastIndexOf(a7);
bL=bi.lastIndexOf(ba);
if(bG==-1&&bL!=-1){bh=bL;
}else{if(bG!=-1&&bL==-1){bh=bG;
}else{bh=bG>bL?bG:bL;
}}if(bH==bx){bh=bH;
}if(bH!=-1){bK=bA.toString().split(a5);
bt=bK[0];
bk=bK[1]||aV;
bu=bt.length;
bl=bk.length;
if(bz&&(bA*-1)>=0){bz=false;
}if(bo){if(bu===bn&&bu<bg-bI){bt=bm+bt;
}else{if(bu>bn){bK=aV;
for(bs=0;
bs<bu;
bs++){if(bs>0&&(bu-bs)%bn===0){bK+=bm;
}bK+=bt.charAt(bs);
}bt=bK;
}}}bA=bi.substring(0,bH);
if(bz&&!bp){bA+="-";
}for(bs=bH;
bs<bx;
bs++){bb=bi.charAt(bs);
if(bg==-1){if(bh-bs<bu){bA+=bt;
break;
}}else{if(bL!=-1&&bL<bs){bF=aV;
}if((bg-bs)<=bu&&bg-bs>-1){bA+=bt;
bs=bg;
}if(bg===bs){bA+=(bk?bf:aV)+bk;
bs+=bh-bg+1;
continue;
}}if(bb===ba){bA+=bb;
bF=bb;
}else{if(bb===a7){bA+=bF;
}}}if(bh>=bH){bA+=bi.substring(bh+1);
}if(bv||bw){bK=aV;
for(bs=0,bx=bA.length;
bs<bx;
bs++){bb=bA.charAt(bs);
bK+=(bb==="$"||bb==="%")?bJ:bb;
}bA=bK;
}bx=by.length;
if(bx){for(bs=0;
bs<bx;
bs++){bA=bA.replace(a4,by[bs]);
}}}return bA;
}var a6=function(bc,bb){bb=bb||0;
bc=bc.toString().split("e");
bc=Math.round(+(bc[0]+"e"+(bc[1]?(+bc[1]+bb):bb)));
bc=bc.toString().split("e");
bc=+(bc[0]+"e"+(bc[1]?(+bc[1]-bb):-bb));
return bc.toFixed(bb);
};
var a9=function(bd,bc,bb){if(bc){if(a3.call(bd)==="[object Date]"){return aZ(bd,bc,bb);
}else{if(typeof bd===ag){return a0(bd,bc,bb);
}}}return bd!==aK?bd:"";
};
if(M&&!M.load){a9=function(bd,bc,bb){if(a.isPlainObject(bb)){bb=bb.name;
}return M.format(bd,bc,bb);
};
}W.format=function(bb){var bc=arguments;
return bb.replace(E,function(be,bd,bf){var bg=bc[parseInt(bd,10)+1];
return a9(bg,bf?bf.substring(1):"");
});
};
W._extractFormat=function(bb){if(bb.slice(0,3)==="{0:"){bb=bb.slice(3,bb.length-1);
}return bb;
};
W._activeElement=function(){try{return document.activeElement;
}catch(bb){return document.documentElement.activeElement;
}};
W._round=a6;
W.toString=a9;
})();
(function(){var a1=/\u00A0/g,aV=/[eE][\-+]?[0-9]+/,a8=/[+|\-]\d{1,2}/,aX=/[+|\-]\d{1,2}:?\d{2}/,aT=/^\/Date\((.*?)\)\/$/,a4=/[+-]\d*/,aW=["G","g","d","F","D","y","m","T","t"],a2={2:/^\d{1,2}/,3:/^\d{1,3}/,4:/^\d{4}/},a3={}.toString;
function a5(bb,ba,a9){return !(bb>=ba&&bb<=a9);
}function aU(a9){return a9.charAt(0);
}function a0(a9){return a.map(a9,aU);
}function aS(a9,ba){if(!ba&&a9.getHours()===23){a9.setHours(a9.getHours()+2);
}}function aY(ba){var bb=0,bc=ba.length,a9=[];
for(;
bb<bc;
bb++){a9[bb]=(ba[bb]+"").toLowerCase();
}return a9;
}function aZ(a9){var ba={},bb;
for(bb in a9){ba[bb]=aY(a9[bb]);
}return ba;
}function a6(bE,bi,be){if(!bE){return null;
}var br=function(bI){var bH=0;
while(bi[bo]===bI){bH++;
bo++;
}if(bH>0){bo-=1;
}return bH;
},bk=function(bJ){var bI=a2[bJ]||new RegExp("^\\d{1,"+bJ+"}"),bH=bE.substr(bF,bJ).match(bI);
if(bH){bH=bH[0];
bF+=bH.length;
return parseInt(bH,10);
}return null;
},bj=function(bO,bJ){var bH=0,bI=bO.length,bM,bN,bL=0,bK=0,bP;
for(;
bH<bI;
bH++){bM=bO[bH];
bN=bM.length;
bP=bE.substr(bF,bN);
if(bJ){bP=bP.toLowerCase();
}if(bP==bM&&bN>bL){bL=bN;
bK=bH;
}}if(bL){bF+=bL;
return bK+1;
}return null;
},bc=function(){var bH=false;
if(bE.charAt(bF)===bi[bo]){bF++;
bH=true;
}return bH;
},ba=be.calendars.standard,bG=null,bx=null,bg=null,bm=null,bv=null,bB=null,bu=null,bo=0,bF=0,bq=false,bf=new Date(),bC=ba.twoDigitYearMax||2029,bh=bf.getFullYear(),bb,bd,bp,by,bA,bD,bt,a9,bz,bn,bw,bl,bs;
if(!bi){bi="d";
}by=ba.patterns[bi];
if(by){bi=by;
}bi=bi.split("");
bp=bi.length;
for(;
bo<bp;
bo++){bb=bi[bo];
if(bq){if(bb==="'"){bq=false;
}else{bc();
}}else{if(bb==="d"){bd=br("d");
if(!ba._lowerDays){ba._lowerDays=aZ(ba.days);
}if(bg!==null&&bd>2){continue;
}bg=bd<3?bk(2):bj(ba._lowerDays[bd==3?"namesAbbr":"names"],true);
if(bg===null||a5(bg,1,31)){return null;
}}else{if(bb==="M"){bd=br("M");
if(!ba._lowerMonths){ba._lowerMonths=aZ(ba.months);
}bx=bd<3?bk(2):bj(ba._lowerMonths[bd==3?"namesAbbr":"names"],true);
if(bx===null||a5(bx,1,12)){return null;
}bx-=1;
}else{if(bb==="y"){bd=br("y");
bG=bk(bd);
if(bG===null){return null;
}if(bd==2){if(typeof bC==="string"){bC=bh+parseInt(bC,10);
}bG=(bh-bh%100)+bG;
if(bG>bC){bG-=100;
}}}else{if(bb==="h"){br("h");
bm=bk(2);
if(bm==12){bm=0;
}if(bm===null||a5(bm,0,11)){return null;
}}else{if(bb==="H"){br("H");
bm=bk(2);
if(bm===null||a5(bm,0,23)){return null;
}}else{if(bb==="m"){br("m");
bv=bk(2);
if(bv===null||a5(bv,0,59)){return null;
}}else{if(bb==="s"){br("s");
bB=bk(2);
if(bB===null||a5(bB,0,59)){return null;
}}else{if(bb==="f"){bd=br("f");
bs=bE.substr(bF,bd).match(a2[3]);
bu=bk(bd);
if(bu!==null){bs=bs[0].length;
if(bs<3){bu*=Math.pow(10,(3-bs));
}if(bd>3){bu=parseInt(bu.toString().substring(0,3),10);
}}if(bu===null||a5(bu,0,999)){return null;
}}else{if(bb==="t"){bd=br("t");
a9=ba.AM;
bz=ba.PM;
if(bd===1){a9=a0(a9);
bz=a0(bz);
}bA=bj(bz);
if(!bA&&!bj(a9)){return null;
}}else{if(bb==="z"){bD=true;
bd=br("z");
if(bE.substr(bF,1)==="Z"){bc();
continue;
}bt=bE.substr(bF,6).match(bd>2?aX:a8);
if(!bt){return null;
}bt=bt[0].split(":");
bn=bt[0];
bw=bt[1];
if(!bw&&bn.length>3){bF=bn.length-2;
bw=bn.substring(bF);
bn=bn.substring(0,bF);
}bn=parseInt(bn,10);
if(a5(bn,-12,13)){return null;
}if(bd>2){bw=parseInt(bw,10);
if(isNaN(bw)||a5(bw,0,59)){return null;
}}}else{if(bb==="'"){bq=true;
bc();
}else{if(!bc()){return null;
}}}}}}}}}}}}}}bl=bm!==null||bv!==null||bB||null;
if(bG===null&&bx===null&&bg===null&&bl){bG=bh;
bx=bf.getMonth();
bg=bf.getDate();
}else{if(bG===null){bG=bh;
}if(bg===null){bg=1;
}}if(bA&&bm<12){bm+=12;
}if(bD){if(bn){bm+=-bn;
}if(bw){bv+=-bw;
}bE=new Date(Date.UTC(bG,bx,bg,bm,bv,bB,bu));
}else{bE=new Date(bG,bx,bg,bm,bv,bB,bu);
aS(bE,bm);
}if(bG<100){bE.setFullYear(bG);
}if(bE.getDate()!==bg&&bD===aK){return null;
}return bE;
}function a7(a9){var ba=a9.substr(0,1)==="-"?-1:1;
a9=a9.substring(1);
a9=(parseInt(a9.substr(0,2),10)*60)+parseInt(a9.substring(2),10);
return ba*a9;
}W.parseDate=function(bg,bb,a9){if(a3.call(bg)==="[object Date]"){return bg;
}var bc=0;
var ba=null;
var bd,be;
var bf;
if(bg&&bg.indexOf("/D")===0){ba=aT.exec(bg);
if(ba){ba=ba[1];
bf=a4.exec(ba.substring(1));
ba=new Date(parseInt(ba,10));
if(bf){bf=a7(bf[0]);
ba=W.timezone.apply(ba,0);
ba=W.timezone.convert(ba,0,-1*bf);
}return ba;
}}a9=W.getCulture(a9);
if(!bb){bb=[];
be=a9.calendar.patterns;
bd=aW.length;
for(;
bc<bd;
bc++){bb[bc]=be[aW[bc]];
}bc=0;
bb=["yyyy/MM/dd HH:mm:ss","yyyy/MM/dd HH:mm","yyyy/MM/dd","ddd MMM dd yyyy HH:mm:ss","yyyy-MM-ddTHH:mm:ss.fffffffzzz","yyyy-MM-ddTHH:mm:ss.fffzzz","yyyy-MM-ddTHH:mm:sszzz","yyyy-MM-ddTHH:mm:ss.fffffff","yyyy-MM-ddTHH:mm:ss.fff","yyyy-MM-ddTHH:mmzzz","yyyy-MM-ddTHH:mmzz","yyyy-MM-ddTHH:mm:ss","yyyy-MM-ddTHH:mm","yyyy-MM-dd HH:mm:ss","yyyy-MM-dd HH:mm","yyyy-MM-dd","HH:mm:ss","HH:mm"].concat(bb);
}bb=P(bb)?bb:[bb];
bd=bb.length;
for(;
bc<bd;
bc++){ba=a6(bg,bb[bc],a9);
if(ba){return ba;
}}return ba;
};
W.parseInt=function(bb,a9){var ba=W.parseFloat(bb,a9);
if(ba){ba=ba|0;
}return ba;
};
W.parseFloat=function(bj,a9,bb){if(!bj&&bj!==0){return null;
}if(typeof bj===ag){return bj;
}bj=bj.toString();
a9=W.getCulture(a9);
var be=a9.numberFormat,bg=be.percent,ba=be.currency,bi=ba.symbol,bh=bg.symbol,bd=bj.indexOf("-"),bf,bc;
if(aV.test(bj)){bj=parseFloat(bj.replace(be["."],"."));
if(isNaN(bj)){bj=null;
}return bj;
}if(bd>0){return null;
}else{bd=bd>-1;
}if(bj.indexOf(bi)>-1||(bb&&bb.toLowerCase().indexOf("c")>-1)){be=ba;
bf=be.pattern[0].replace("$",bi).split("n");
if(bj.indexOf(bf[0])>-1&&bj.indexOf(bf[1])>-1){bj=bj.replace(bf[0],"").replace(bf[1],"");
bd=true;
}}else{if(bj.indexOf(bh)>-1){bc=true;
be=bg;
bi=bh;
}}bj=bj.replace("-","").replace(bi,"").replace(a1," ").split(be[","].replace(a1," ")).join("").replace(be["."],".");
bj=parseFloat(bj);
if(isNaN(bj)){bj=null;
}else{if(bd){bj*=-1;
}}if(bj&&bc){bj/=100;
}return bj;
};
if(M&&!M.load){W.parseDate=function(bb,ba,a9){if(a3.call(bb)==="[object Date]"){return bb;
}return M.parseDate(bb,ba,a9);
};
W.parseFloat=function(ba,a9){if(typeof ba===ag){return ba;
}if(ba===aK||ba===null){return null;
}if(a.isPlainObject(a9)){a9=a9.name;
}ba=M.parseFloat(ba,a9);
return isNaN(ba)?null:ba;
};
}})();
function K(aT){var aV=aT.css(W.support.transitions.css+"box-shadow")||aT.css("box-shadow"),aU=aV?aV.match(i)||[0,0,0,0,0]:[0,0,0,0,0],aS=aa.max((+aU[3]),+(aU[4]||0));
return{left:(-aU[1])+aS,right:(+aU[1])+aS,bottom:(+aU[2])+aS};
}function aP(aU,aS){var aT=aD.browser,aX,aW=aU.css("direction")=="rtl";
if(!aU.parent().hasClass("k-animation-container")){var a0=K(aU),a1=aU[0].style.width,aV=aU[0].style.height,aZ=ap.test(a1),aY=ap.test(aV);
if(aT.opera){a0.left=a0.right=a0.bottom=5;
}aX=aZ||aY;
if(!aZ&&(!aS||(aS&&a1))){a1=aU.outerWidth();
}if(!aY&&(!aS||(aS&&aV))){aV=aU.outerHeight();
}aU.wrap(a("<div/>").addClass("k-animation-container").css({width:a1,height:aV,marginLeft:a0.left*(aW?1:-1),paddingLeft:a0.left,paddingRight:a0.right,paddingBottom:a0.bottom}));
if(aX){aU.css({width:"100%",height:"100%",boxSizing:"border-box",mozBoxSizing:"border-box",webkitBoxSizing:"border-box"});
}}else{var a2=aU.parent(".k-animation-container"),a3=a2[0].style;
if(a2.is(":hidden")){a2.show();
}aX=ap.test(a3.width)||ap.test(a3.height);
if(!aX){a2.css({width:aU.outerWidth(),height:aU.outerHeight(),boxSizing:"content-box",mozBoxSizing:"content-box",webkitBoxSizing:"content-box"});
}}if(aT.msie&&aa.floor(aT.version)<=7){aU.css({zoom:1});
aU.children(".k-menu").width(aU.width());
}return aU.parent();
}function q(aS){var aT=1,aU=arguments.length;
for(aT=1;
aT<aU;
aT++){r(aS,arguments[aT]);
}return aS;
}function r(aT,a2){var aX=W.data.ObservableArray,aW=W.data.LazyObservableArray,aS=W.data.DataSource,aV=W.data.HierarchicalDataSource,aY,a1,a0,aZ,aU;
for(aY in a2){a1=a2[aY];
a0=typeof a1;
if(a0===ai&&a1!==null){aZ=a1.constructor;
}else{aZ=null;
}if(aZ&&aZ!==Array&&aZ!==aX&&aZ!==aW&&aZ!==aS&&aZ!==aV){if(a1 instanceof Date){aT[aY]=new Date(a1.getTime());
}else{if(R(a1.clone)){aT[aY]=a1.clone();
}else{aU=aT[aY];
if(typeof(aU)===ai){aT[aY]=aU||{};
}else{aT[aY]={};
}r(aT[aY],a1);
}}}else{if(a0!==aL){aT[aY]=a1;
}}}return aT;
}function aG(aS,aV,aT){for(var aU in aV){if(aV.hasOwnProperty(aU)&&aV[aU].test(aS)){return aU;
}}return aT!==aK?aT:aS;
}function aJ(aS){return aS.replace(/([a-z][A-Z])/g,function(aT){return aT.charAt(0)+"-"+aT.charAt(1).toLowerCase();
});
}function aH(aS){return aS.replace(/\-(\w)/g,function(aU,aT){return aT.toUpperCase();
});
}function H(aT,aU){var aV={},aS;
if(document.defaultView&&document.defaultView.getComputedStyle){aS=document.defaultView.getComputedStyle(aT,"");
if(aU){a.each(aU,function(aW,aX){aV[aX]=aS.getPropertyValue(aX);
});
}}else{aS=aT.currentStyle;
if(aU){a.each(aU,function(aW,aX){aV[aX]=aS[aH(aX)];
});
}}if(!W.size(aV)){aV=aS;
}return aV;
}function S(aS){if(aS.className.indexOf("k-auto-scrollable")>-1){return true;
}var aT=H(aS,["overflow"]).overflow;
return aT=="auto"||aT=="scroll";
}function ax(aT,aW){var aS=aT instanceof a?aT[0]:aT;
var aU=aD.isRtl(aT);
var aX=aD.browser.webkit;
var aV=aD.browser.mozilla;
if(aW!==aK){if(aU&&aX){aS.scrollLeft=aS.scrollWidth-aS.clientWidth-aW;
}else{if(aU&&aV){aS.scrollLeft=-aW;
}else{aS.scrollLeft=aW;
}}}else{if(aU&&aX){return aS.scrollWidth-aS.clientWidth-aS.scrollLeft;
}else{return Math.abs(aS.scrollLeft);
}}}(function(){aD._scrollbar=aK;
aD.scrollbar=function(a1){if(!isNaN(aD._scrollbar)&&!a1){return aD._scrollbar;
}else{var a0=document.createElement("div"),a2;
a0.style.cssText="overflow:scroll;overflow-x:hidden;zoom:1;clear:both;display:block";
a0.innerHTML="&nbsp;";
document.body.appendChild(a0);
aD._scrollbar=a2=a0.offsetWidth-a0.scrollWidth;
document.body.removeChild(a0);
return a2;
}};
aD.isRtl=function(a0){return a(a0).closest(".k-rtl").length>0;
};
var aX=document.createElement("table");
try{aX.innerHTML="<tr><td></td></tr>";
aD.tbodyInnerHtml=true;
}catch(aT){aD.tbodyInnerHtml=false;
}aD.touch="ontouchstart" in aO;
aD.msPointers=aO.MSPointerEvent;
aD.pointers=aO.PointerEvent;
var aZ=aD.transitions=false,aY=aD.transforms=false,aU="HTMLElement" in aO?HTMLElement.prototype:[];
aD.hasHW3D=("WebKitCSSMatrix" in aO&&"m11" in new aO.WebKitCSSMatrix())||"MozPerspective" in document.documentElement.style||"msPerspective" in document.documentElement.style;
t(["Moz","webkit","O","ms"],function(){var a2=this.toString(),a0=typeof aX.style[a2+"Transition"]===aC;
if(a0||typeof aX.style[a2+"Transform"]===aC){var a1=a2.toLowerCase();
aY={css:(a1!="ms")?"-"+a1+"-":"",prefix:a2,event:(a1==="o"||a1==="webkit")?a1:""};
if(a0){aZ=aY;
aZ.event=aZ.event?aZ.event+"TransitionEnd":"transitionend";
}return false;
}});
aX=null;
aD.transforms=aY;
aD.transitions=aZ;
aD.devicePixelRatio=aO.devicePixelRatio===aK?1:aO.devicePixelRatio;
try{aD.screenWidth=aO.outerWidth||aO.screen?aO.screen.availWidth:aO.innerWidth;
aD.screenHeight=aO.outerHeight||aO.screen?aO.screen.availHeight:aO.innerHeight;
}catch(aT){aD.screenWidth=aO.screen.availWidth;
aD.screenHeight=aO.screen.availHeight;
}aD.detectOS=function(a9){var a7=false,a5,a4=[],a6=!/mobile safari/i.test(a9),a1={wp:/(Windows Phone(?: OS)?)\s(\d+)\.(\d+(\.\d+)?)/,fire:/(Silk)\/(\d+)\.(\d+(\.\d+)?)/,android:/(Android|Android.*(?:Opera|Firefox).*?\/)\s*(\d+)\.(\d+(\.\d+)?)/,iphone:/(iPhone|iPod).*OS\s+(\d+)[\._]([\d\._]+)/,ipad:/(iPad).*OS\s+(\d+)[\._]([\d_]+)/,meego:/(MeeGo).+NokiaBrowser\/(\d+)\.([\d\._]+)/,webos:/(webOS)\/(\d+)\.(\d+(\.\d+)?)/,blackberry:/(BlackBerry|BB10).*?Version\/(\d+)\.(\d+(\.\d+)?)/,playbook:/(PlayBook).*?Tablet\s*OS\s*(\d+)\.(\d+(\.\d+)?)/,windows:/(MSIE)\s+(\d+)\.(\d+(\.\d+)?)/,tizen:/(tizen).*?Version\/(\d+)\.(\d+(\.\d+)?)/i,sailfish:/(sailfish).*rv:(\d+)\.(\d+(\.\d+)?).*firefox/i,ffos:/(Mobile).*rv:(\d+)\.(\d+(\.\d+)?).*Firefox/},a8={ios:/^i(phone|pad|pod)$/i,android:/^android|fire$/i,blackberry:/^blackberry|playbook/i,windows:/windows/,wp:/wp/,flat:/sailfish|ffos|tizen/i,meego:/meego/},a3={tablet:/playbook|ipad|fire/i},a2={omini:/Opera\sMini/i,omobile:/Opera\sMobi/i,firefox:/Firefox|Fennec/i,mobilesafari:/version\/.*safari/i,ie:/MSIE|Windows\sPhone/i,chrome:/chrome|crios/i,webkit:/webkit/i};
for(var a0 in a1){if(a1.hasOwnProperty(a0)){a4=a9.match(a1[a0]);
if(a4){if(a0=="windows"&&"plugins" in navigator){return false;
}a7={};
a7.device=a0;
a7.tablet=aG(a0,a3,false);
a7.browser=aG(a9,a2,"default");
a7.name=aG(a0,a8);
a7[a7.name]=true;
a7.majorVersion=a4[2];
a7.minorVersion=a4[3].replace("_",".");
a5=a7.minorVersion.replace(".","").substr(0,2);
a7.flatVersion=a7.majorVersion+a5+(new Array(3-(a5.length<3?a5.length:2)).join("0"));
a7.cordova=typeof aO.PhoneGap!==aL||typeof aO.cordova!==aL;
a7.appMode=aO.navigator.standalone||(/file|local|wmapp/).test(aO.location.protocol)||a7.cordova;
if(a7.android&&(aD.devicePixelRatio<1.5&&a7.flatVersion<400||a6)&&(aD.screenWidth>800||aD.screenHeight>800)){a7.tablet=a0;
}break;
}}}return a7;
};
var aW=aD.mobileOS=aD.detectOS(navigator.userAgent);
aD.wpDevicePixelRatio=aW.wp?screen.width/320:0;
aD.kineticScrollNeeded=aW&&(aD.touch||aD.msPointers||aD.pointers);
aD.hasNativeScrolling=false;
if(aW.ios||(aW.android&&aW.majorVersion>2)||aW.wp){aD.hasNativeScrolling=aW;
}aD.mouseAndTouchPresent=aD.touch&&!(aD.mobileOS.ios||aD.mobileOS.android);
aD.detectBrowser=function(a4){var a1=false,a3=[],a2={edge:/(edge)[ \/]([\w.]+)/i,webkit:/(chrome)[ \/]([\w.]+)/i,safari:/(webkit)[ \/]([\w.]+)/i,opera:/(opera)(?:.*version|)[ \/]([\w.]+)/i,msie:/(msie\s|trident.*? rv:)([\w.]+)/i,mozilla:/(mozilla)(?:.*? rv:([\w.]+)|)/i};
for(var a0 in a2){if(a2.hasOwnProperty(a0)){a3=a4.match(a2[a0]);
if(a3){a1={};
a1[a0]=true;
a1[a3[1].toLowerCase().split(" ")[0].split("/")[0]]=true;
a1.version=parseInt(document.documentMode||a3[2],10);
break;
}}}return a1;
};
aD.browser=aD.detectBrowser(navigator.userAgent);
aD.zoomLevel=function(){try{var a0=aD.browser;
var a3=0;
var a1=document.documentElement;
if(a0.msie&&a0.version==11&&a1.scrollHeight>a1.clientHeight&&!aD.touch){a3=aD.scrollbar();
}return aD.touch?(a1.clientWidth/aO.innerWidth):a0.msie&&a0.version>=10?(((top||aO).document.documentElement.offsetWidth+a3)/(top||aO).innerWidth):1;
}catch(a2){return 1;
}};
aD.cssBorderSpacing=typeof document.documentElement.style.borderSpacing!="undefined"&&!(aD.browser.msie&&aD.browser.version<8);
(function(a0){var a1="",a2=a(document.documentElement),a3=parseInt(a0.version,10);
if(a0.msie){a1="ie";
}else{if(a0.mozilla){a1="ff";
}else{if(a0.safari){a1="safari";
}else{if(a0.webkit){a1="webkit";
}else{if(a0.opera){a1="opera";
}else{if(a0.edge){a1="edge";
}}}}}}if(a1){a1="k-"+a1+" k-"+a1+a3;
}if(aD.mobileOS){a1+=" k-mobile";
}a2.addClass(a1);
})(aD.browser);
aD.eventCapture=document.documentElement.addEventListener;
var aV=document.createElement("input");
aD.placeholder="placeholder" in aV;
aD.propertyChangeEvent="onpropertychange" in aV;
aD.input=(function(){var a4=["number","date","time","month","week","datetime","datetime-local"];
var a1=a4.length;
var a5="test";
var a2={};
var a0=0;
var a3;
for(;
a0<a1;
a0++){a3=a4[a0];
aV.setAttribute("type",a3);
aV.value=a5;
a2[a3.replace("-","")]=aV.type!=="text"&&aV.value!==a5;
}return a2;
})();
aV.style.cssText="float:left;";
aD.cssFloat=!!aV.style.cssFloat;
aV=null;
aD.stableSort=(function(){var a2=513;
var a1=[{index:0,field:"b"}];
for(var a0=1;
a0<a2;
a0++){a1.push({index:a0,field:"a"});
}a1.sort(function(a3,a4){return a3.field>a4.field?1:(a3.field<a4.field?-1:0);
});
return a1[0].index===1;
})();
aD.matchesSelector=aU.webkitMatchesSelector||aU.mozMatchesSelector||aU.msMatchesSelector||aU.oMatchesSelector||aU.matchesSelector||aU.matches||function(a2){var a1=document.querySelectorAll?(this.parentNode||document).querySelectorAll(a2)||[]:a(a2),a0=a1.length;
while(a0--){if(a1[a0]==this){return true;
}}return false;
};
aD.pushState=aO.history&&aO.history.pushState;
var aS=document.documentMode;
aD.hashChange=("onhashchange" in aO)&&!(aD.browser.msie&&(!aS||aS<=8));
aD.customElements=("registerElement" in aO.document);
})();
function aA(aT){var aU=0,aS;
for(aS in aT){if(aT.hasOwnProperty(aS)&&aS!="toJSON"){aU++;
}}return aU;
}function J(aS,aV,aT){if(!aV){aV="offset";
}var aU=aS[aV]();
if(aD.browser.msie&&(aD.pointers||aD.msPointers)&&!aT){aU.top-=(aO.pageYOffset-document.documentElement.scrollTop);
aU.left-=(aO.pageXOffset-document.documentElement.scrollLeft);
}return aU;
}var s={left:{reverse:"right"},right:{reverse:"left"},down:{reverse:"up"},up:{reverse:"down"},top:{reverse:"bottom"},bottom:{reverse:"top"},"in":{reverse:"out"},out:{reverse:"in"}};
function am(aT){var aS={};
t((typeof aT==="string"?aT.split(" "):aT),function(aU){aS[aU]=this;
});
return aS;
}function G(aS){return new W.effects.Element(aS);
}var u={};
a.extend(u,{enabled:true,Element:function(aS){this.element=a(aS);
},promise:function(aS,aT){if(!aS.is(":visible")){aS.css({display:aS.data("olddisplay")||"block"}).css("display");
}if(aT.hide){aS.data("olddisplay",aS.css("display")).hide();
}if(aT.init){aT.init();
}if(aT.completeCallback){aT.completeCallback(aS);
}aS.dequeue();
},disable:function(){this.enabled=false;
this.promise=this.promiseShim;
},enable:function(){this.enabled=true;
this.promise=this.animatedPromise;
}});
u.promiseShim=u.promise;
function aq(aU,aT,aV,aS){if(typeof aU===aC){if(R(aT)){aS=aT;
aT=400;
aV=false;
}if(R(aV)){aS=aV;
aV=false;
}if(typeof aT===h){aV=aT;
aT=400;
}aU={effects:aU,duration:aT,reverse:aV,complete:aS};
}return C({effects:{},duration:400,reverse:false,init:ae,teardown:ae,hide:false},aU,{completeCallback:aU.complete,complete:ae});
}function c(aU,aY,aT,aZ,aS){var aV=0,aX=aU.length,aW;
for(;
aV<aX;
aV++){aW=a(aU[aV]);
aW.queue(function(){u.promise(aW,aq(aY,aT,aZ,aS));
});
}return aU;
}function aI(aU,aT,aV,aS){if(aT){aT=aT.split(" ");
t(aT,function(aW,aX){aU.toggleClass(aX,aS);
});
}return aU;
}if(!("kendoAnimate" in a.fn)){C(a.fn,{kendoStop:function(aS,aT){return this.stop(aS,aT);
},kendoAnimate:function(aU,aT,aV,aS){return c(this,aU,aT,aV,aS);
},kendoAddClass:function(aS,aT){return W.toggleClass(this,aS,aT,true);
},kendoRemoveClass:function(aS,aT){return W.toggleClass(this,aS,aT,false);
},kendoToggleClass:function(aS,aT,aU){return W.toggleClass(this,aS,aT,aU);
}});
}var b=/&/g,Z=/</g,au=/"/g,f=/'/g,N=/>/g;
function O(aS){return(""+aS).replace(b,"&amp;").replace(Z,"&lt;").replace(N,"&gt;").replace(au,"&quot;").replace(f,"&#39;");
}var A=function(aS){return aS.target;
};
if(aD.touch){A=function(aS){var aT="originalEvent" in aS?aS.originalEvent.changedTouches:"changedTouches" in aS?aS.changedTouches:null;
return aT?document.elementFromPoint(aT[0].clientX,aT[0].clientY):aS.target;
};
t(["swipe","swipeLeft","swipeRight","swipeUp","swipeDown","doubleTap","tap"],function(aS,aT){a.fn[aT]=function(aU){return this.bind(aT,aU);
};
});
}if(aD.touch){if(!aD.mobileOS){aD.mousedown="mousedown touchstart";
aD.mouseup="mouseup touchend";
aD.mousemove="mousemove touchmove";
aD.mousecancel="mouseleave touchcancel";
aD.click="click";
aD.resize="resize";
}else{aD.mousedown="touchstart";
aD.mouseup="touchend";
aD.mousemove="touchmove";
aD.mousecancel="touchcancel";
aD.click="touchend";
aD.resize="orientationchange";
}}else{if(aD.pointers){aD.mousemove="pointermove";
aD.mousedown="pointerdown";
aD.mouseup="pointerup";
aD.mousecancel="pointercancel";
aD.click="pointerup";
aD.resize="orientationchange resize";
}else{if(aD.msPointers){aD.mousemove="MSPointerMove";
aD.mousedown="MSPointerDown";
aD.mouseup="MSPointerUp";
aD.mousecancel="MSPointerCancel";
aD.click="MSPointerUp";
aD.resize="orientationchange resize";
}else{aD.mousemove="mousemove";
aD.mousedown="mousedown";
aD.mouseup="mouseup";
aD.mousecancel="mouseleave";
aD.click="click";
aD.resize="resize";
}}}var aQ=function(aX,aY){var aZ=aY||"d",aU,aT,aV,aW,aS=1;
for(aT=0,aV=aX.length;
aT<aV;
aT++){aW=aX[aT];
if(aW!==""){aU=aW.indexOf("[");
if(aU!==0){if(aU==-1){aW="."+aW;
}else{aS++;
aW="."+aW.substring(0,aU)+" || {})"+aW.substring(aU);
}}aS++;
aZ+=aW+((aT<aV-1)?" || {})":")");
}}return new Array(aS).join("(")+aZ;
},Y=/^([a-z]+:)?\/\//i;
C(W,{widgets:[],_widgetRegisteredCallbacks:[],ui:W.ui||{},fx:W.fx||G,effects:W.effects||u,mobile:W.mobile||{},data:W.data||{},dataviz:W.dataviz||{},drawing:W.drawing||{},spreadsheet:{},keys:{INSERT:45,DELETE:46,BACKSPACE:8,TAB:9,ENTER:13,ESC:27,LEFT:37,UP:38,RIGHT:39,DOWN:40,END:35,HOME:36,SPACEBAR:32,PAGEUP:33,PAGEDOWN:34,F2:113,F10:121,F12:123,NUMPAD_PLUS:107,NUMPAD_MINUS:109,NUMPAD_DOT:110},support:W.support||aD,animate:W.animate||c,ns:"",attr:function(aS){return"data-"+W.ns+aS;
},getShadows:K,wrap:aP,deepExtend:q,getComputedStyles:H,webComponents:[],isScrollable:S,scrollLeft:ax,size:aA,toCamelCase:aH,toHyphens:aJ,getOffset:W.getOffset||J,parseEffects:W.parseEffects||am,toggleClass:W.toggleClass||aI,directions:W.directions||s,Observable:aj,Class:j,Template:aE,template:at(aE.compile,aE),render:at(aE.render,aE),stringify:at(T.stringify,T),eventTarget:A,htmlEncode:O,isLocalUrl:function(aS){return aS&&!Y.test(aS);
},expr:function(aS,aU,aT){aS=aS||"";
if(typeof aU==aC){aT=aU;
aU=false;
}aT=aT||"d";
if(aS&&aS.charAt(0)!=="["){aS="."+aS;
}if(aU){aS=aS.replace(/"([^.]*)\.([^"]*)"/g,'"$1_$DOT$_$2"');
aS=aS.replace(/'([^.]*)\.([^']*)'/g,"'$1_$DOT$_$2'");
aS=aQ(aS.split("."),aT);
aS=aS.replace(/_\$DOT\$_/g,".");
}else{aS=aT+aS;
}return aS;
},getter:function(aS,aU){var aT=aS+aU;
return L[aT]=L[aT]||new Function("d","return "+W.expr(aS,aU));
},setter:function(aS){return ay[aS]=ay[aS]||new Function("d,value",W.expr(aS)+"=value");
},accessor:function(aS){return{get:W.getter(aS),set:W.setter(aS)};
},guid:function(){var aT="",aS,aU;
for(aS=0;
aS<32;
aS++){aU=aa.random()*16|0;
if(aS==8||aS==12||aS==16||aS==20){aT+="-";
}aT+=(aS==12?4:(aS==16?(aU&3|8):aU)).toString(16);
}return aT;
},roleSelector:function(aS){return aS.replace(/(\S+)/g,"["+W.attr("role")+"=$1],").slice(0,-1);
},directiveSelector:function(aS){var aU=aS.split(" ");
if(aU){for(var aT=0;
aT<aU.length;
aT++){if(aU[aT]!="view"){aU[aT]=aU[aT].replace(/(\w*)(view|bar|strip|over)$/,"$1-$2");
}}}return aU.join(" ").replace(/(\S+)/g,"kendo-mobile-$1,").slice(0,-1);
},triggeredByInput:function(aS){return(/^(label|input|textarea|select)$/i).test(aS.target.tagName);
},onWidgetRegistered:function(aS){for(var aT=0,aU=W.widgets.length;
aT<aU;
aT++){aS(W.widgets[aT]);
}W._widgetRegisteredCallbacks.push(aS);
},logToConsole:function(aT){var aS=aO.console;
if(!W.suppressLog&&typeof(aS)!="undefined"&&aS.log){aS.log(aT);
}}});
var aN=aj.extend({init:function(aT,aU){var aV=this;
aV.element=W.jQuery(aT).handler(aV);
aV.angular("init",aU);
aj.fn.init.call(aV);
var aS=aU?aU.dataSource:null;
if(aS){aU=C({},aU,{dataSource:{}});
}aU=aV.options=C(true,{},aV.options,aU);
if(aS){aU.dataSource=aS;
}if(!aV.element.attr(W.attr("role"))){aV.element.attr(W.attr("role"),(aU.name||"").toLowerCase());
}aV.element.data("kendo"+aU.prefix+aU.name,aV);
aV.bind(aV.events,aU);
},events:[],options:{prefix:""},_hasBindingTarget:function(){return !!this.element[0].kendoBindingTarget;
},_tabindex:function(aV){aV=aV||this.wrapper;
var aS=this.element,aU="tabindex",aT=aV.attr(aU)||aS.attr(aU);
aS.removeAttr(aU);
aV.attr(aU,!isNaN(aT)?aT:0);
},setOptions:function(aS){this._setEvents(aS);
a.extend(this.options,aS);
},_setEvents:function(aV){var aW=this,aT=0,aU=aW.events.length,aS;
for(;
aT<aU;
aT++){aS=aW.events[aT];
if(aW.options[aS]&&aV[aS]){aW.unbind(aS,aW.options[aS]);
}}aW.bind(aW.events,aV);
},resize:function(aT){var aU=this.getSize(),aS=this._size;
if(aT||(aU.width>0||aU.height>0)&&(!aS||aU.width!==aS.width||aU.height!==aS.height)){this._size=aU;
this._resize(aU,aT);
this.trigger("resize",aU);
}},getSize:function(){return W.dimensions(this.element);
},size:function(aS){if(!aS){return this.getSize();
}else{this.setSize(aS);
}},setSize:a.noop,_resize:a.noop,destroy:function(){var aS=this;
aS.element.removeData("kendo"+aS.options.prefix+aS.options.name);
aS.element.removeData("handler");
aS.unbind();
},_destroy:function(){this.destroy();
},angular:function(){},_muteAngularRebind:function(aS){this._muteRebind=true;
aS.call(this);
this._muteRebind=false;
}});
var p=aN.extend({dataItems:function(){return this.dataSource.flatView();
},_angularItems:function(aS){var aT=this;
aT.angular(aS,function(){return{elements:aT.items(),data:a.map(aT.dataItems(),function(aU){return{dataItem:aU};
})};
});
}});
W.dimensions=function(aU,aS){var aT=aU[0];
if(aS){aU.css(aS);
}return{width:aT.offsetWidth,height:aT.offsetHeight};
};
W.notify=ae;
var aF=/template$/i,V=/^\s*(?:\{(?:.|\r\n|\n)*\}|\[(?:.|\r\n|\n)*\])\s*$/,U=/^\{(\d+)(:[^\}]+)?\}|^\[[A-Za-z_]*\]$/,o=/([A-Z])/g;
function an(aS,aT){var aU;
if(aT.indexOf("data")===0){aT=aT.substring(4);
aT=aT.charAt(0).toLowerCase()+aT.substring(1);
}aT=aT.replace(o,"-$1");
aU=aS.getAttribute("data-"+W.ns+aT);
if(aU===null){aU=aK;
}else{if(aU==="null"){aU=null;
}else{if(aU==="true"){aU=true;
}else{if(aU==="false"){aU=false;
}else{if(ah.test(aU)){aU=parseFloat(aU);
}else{if(V.test(aU)&&!U.test(aU)){aU=new Function("return ("+aU+")")();
}}}}}}return aU;
}function ao(aS,aU){var aV={},aT,aW;
for(aT in aU){aW=an(aS,aT);
if(aW!==aK){if(aF.test(aT)){aW=W.template(a("#"+aW).html());
}aV[aT]=aW;
}}return aV;
}W.initWidget=function(aU,a0,a3){var a1,aZ,a5,aW,aY,a2,a4,aT,aV,a7;
if(!a3){a3=W.ui.roles;
}else{if(a3.roles){a3=a3.roles;
}}aU=aU.nodeType?aU:aU[0];
a2=aU.getAttribute("data-"+W.ns+"role");
if(!a2){return;
}aV=a2.indexOf(".")===-1;
if(aV){a5=a3[a2];
}else{a5=W.getter(a2)(aO);
}var aS=a(aU).data(),a6=a5?"kendo"+a5.fn.options.prefix+a5.fn.options.name:"";
if(aV){a7=new RegExp("^kendo.*"+a2+"$","i");
}else{a7=new RegExp("^"+a6+"$","i");
}for(var aX in aS){if(aX.match(a7)){if(aX===a6){a1=aS[aX];
}else{return aS[aX];
}}}if(!a5){return;
}aT=an(aU,"dataSource");
a0=a.extend({},ao(aU,a5.fn.options),a0);
if(aT){if(typeof aT===aC){a0.dataSource=W.getter(aT)(aO);
}else{a0.dataSource=aT;
}}for(aW=0,aY=a5.fn.events.length;
aW<aY;
aW++){aZ=a5.fn.events[aW];
a4=an(aU,aZ);
if(a4!==aK){a0[aZ]=W.getter(a4)(aO);
}}if(!a1){a1=new a5(aU,a0);
}else{if(!a.isEmptyObject(a0)){a1.setOptions(a0);
}}return a1;
};
W.rolesFromNamespaces=function(aU){var aV=[],aS,aT;
if(!aU[0]){aU=[W.ui,W.dataviz.ui];
}for(aS=0,aT=aU.length;
aS<aT;
aS++){aV[aS]=aU[aS].roles;
}return C.apply(null,[{}].concat(aV.reverse()));
};
W.init=function(aS){var aT=W.rolesFromNamespaces(aB.call(arguments,1));
a(aS).find("[data-"+W.ns+"role]").addBack().each(function(){W.initWidget(this,{},aT);
});
};
W.destroy=function(aS){a(aS).find("[data-"+W.ns+"role]").addBack().each(function(){var aT=a(this).data();
for(var aU in aT){if(aU.indexOf("kendo")===0&&typeof aT[aU].destroy===F){aT[aU].destroy();
}}});
};
function m(aS,aT){return a.contains(aS,aT)?-1:1;
}function av(){var aS=a(this);
return(a.inArray(aS.attr("data-"+W.ns+"role"),["slider","rangeslider"])>-1)||aS.is(":visible");
}W.resize=function(aS,aT){var aU=a(aS).find("[data-"+W.ns+"role]").addBack().filter(av);
if(!aU.length){return;
}var aV=a.makeArray(aU);
aV.sort(m);
a.each(aV,function(){var aW=W.widgetInstance(a(this));
if(aW){aW.resize(aT);
}});
};
W.parseOptions=ao;
C(W.ui,{Widget:aN,DataBoundWidget:p,roles:{},progress:function(aT,aZ){var aX=aT.find(".k-loading-mask"),aY=W.support,aS=aY.browser,aV,aW,a0,aU;
if(aZ){if(!aX.length){aV=aY.isRtl(aT);
aW=aV?"right":"left";
aU=aT.scrollLeft();
a0=aS.webkit?(!aV?0:aT[0].scrollWidth-aT.width()-2*aU):0;
aX=a("<div class='k-loading-mask'><span class='k-loading-text'>Loading...</span><div class='k-loading-image'/><div class='k-loading-color'/></div>").width("100%").height("100%").css("top",aT.scrollTop()).css(aW,Math.abs(aU)+a0).prependTo(aT);
}}else{if(aX){aX.remove();
}}},plugin:function(aY,aX,aW){var aV=aY.fn.options.name,aS;
aX=aX||W.ui;
aW=aW||"";
aX[aV]=aY;
aX.roles[aV.toLowerCase()]=aY;
aS="getKendo"+aW+aV;
aV="kendo"+aW+aV;
var aZ={name:aV,widget:aY,prefix:aW||""};
W.widgets.push(aZ);
for(var aT=0,aU=W._widgetRegisteredCallbacks.length;
aT<aU;
aT++){W._widgetRegisteredCallbacks[aT](aZ);
}a.fn[aV]=function(a1){var a2=this,a0;
if(typeof a1===aC){a0=aB.call(arguments,1);
this.each(function(){var a5=a.data(this,aV),a3,a4;
if(!a5){throw new Error(W.format("Cannot call method '{0}' of {1} before it is initialized",a1,aV));
}a3=a5[a1];
if(typeof a3!==F){throw new Error(W.format("Cannot find method '{0}' of {1}",a1,aV));
}a4=a3.apply(a5,a0);
if(a4!==aK){a2=a4;
return false;
}});
}else{this.each(function(){return new aY(this,a1);
});
}return a2;
};
a.fn[aV].widget=aY;
a.fn[aS]=function(){return this.data(aV);
};
}});
var l={bind:function(){return this;
},nullObject:true,options:{}};
var ab=aN.extend({init:function(aS,aT){aN.fn.init.call(this,aS,aT);
this.element.autoApplyNS();
this.wrapper=this.element;
this.element.addClass("km-widget");
},destroy:function(){aN.fn.destroy.call(this);
this.element.kendoDestroy();
},options:{prefix:"Mobile"},events:[],view:function(){var aS=this.element.closest(W.roleSelector("view splitview modalview drawer"));
return W.widgetInstance(aS,W.mobile.ui)||l;
},viewHasNativeScrolling:function(){var aS=this.view();
return aS&&aS.options.useNativeScrolling;
},container:function(){var aS=this.element.closest(W.roleSelector("view layout modalview drawer splitview"));
return W.widgetInstance(aS.eq(0),W.mobile.ui)||l;
}});
C(W.mobile,{init:function(aS){W.init(aS,W.mobile.ui,W.ui,W.dataviz.ui);
},appLevelNativeScrolling:function(){return W.mobile.application&&W.mobile.application.options&&W.mobile.application.options.useNativeScrolling;
},roles:{},ui:{Widget:ab,DataBoundWidget:p.extend(ab.prototype),roles:{},plugin:function(aS){W.ui.plugin(aS,W.mobile.ui,"Mobile");
}}});
q(W.dataviz,{init:function(aS){W.init(aS,W.dataviz.ui);
},ui:{roles:{},themes:{},views:[],plugin:function(aS){W.ui.plugin(aS,W.dataviz.ui);
}},roles:{}});
W.touchScroller=function(aS,aT){if(!aT){aT={};
}aT.useNative=true;
return a(aS).map(function(aV,aU){aU=a(aU);
if(aD.kineticScrollNeeded&&W.mobile.ui.Scroller&&!aU.data("kendoMobileScroller")){aU.kendoMobileScroller(aT);
return aU.data("kendoMobileScroller");
}else{return false;
}})[0];
};
W.preventDefault=function(aS){aS.preventDefault();
};
W.widgetInstance=function(aS,aX){var aW=aS.data(W.ns+"role"),aZ=[],aT,aV;
if(aW){if(aW==="content"){aW="scroller";
}if(aX){if(aX[0]){for(aT=0,aV=aX.length;
aT<aV;
aT++){aZ.push(aX[aT].roles[aW]);
}}else{aZ.push(aX.roles[aW]);
}}else{aZ=[W.ui.roles[aW],W.dataviz.ui.roles[aW],W.mobile.ui.roles[aW]];
}if(aW.indexOf(".")>=0){aZ=[W.getter(aW)(aO)];
}for(aT=0,aV=aZ.length;
aT<aV;
aT++){var aY=aZ[aT];
if(aY){var aU=aS.data("kendo"+aY.fn.options.prefix+aY.fn.options.name);
if(aU){return aU;
}}}}};
W.onResize=function(aS){var aT=aS;
if(aD.mobileOS.android){aT=function(){setTimeout(aS,600);
};
}a(aO).on(aD.resize,aT);
return aT;
};
W.unbindResize=function(aS){a(aO).off(aD.resize,aS);
};
W.attrValue=function(aS,aT){return aS.data(W.ns+aT);
};
W.days={Sunday:0,Monday:1,Tuesday:2,Wednesday:3,Thursday:4,Friday:5,Saturday:6};
function D(aS,aT){var aU=aS.nodeName.toLowerCase();
return(/input|select|textarea|button|object/.test(aU)?!aS.disabled:"a"===aU?aS.href||aT:aT)&&aM(aS);
}function aM(aS){return a.expr.filters.visible(aS)&&!a(aS).parents().addBack().filter(function(){return a.css(this,"visibility")==="hidden";
}).length;
}a.extend(a.expr[":"],{kendoFocusable:function(aS){var aT=a.attr(aS,"tabindex");
return D(aS,!isNaN(aT)&&aT>-1);
}});
var ac=["mousedown","mousemove","mouseenter","mouseleave","mouseover","mouseout","mouseup","click"];
var B="label, input, [data-rel=external]";
var ad={setupMouseMute:function(){var aU=0,aV=ac.length,aS=document.documentElement;
if(ad.mouseTrap||!aD.eventCapture){return;
}ad.mouseTrap=true;
ad.bustClick=false;
ad.captureMouse=false;
var aT=function(aW){if(ad.captureMouse){if(aW.type==="click"){if(ad.bustClick&&!a(aW.target).is(B)){aW.preventDefault();
aW.stopPropagation();
}}else{aW.stopPropagation();
}}};
for(;
aU<aV;
aU++){aS.addEventListener(ac[aU],aT,true);
}},muteMouse:function(aS){ad.captureMouse=true;
if(aS.data.bustClick){ad.bustClick=true;
}clearTimeout(ad.mouseTrapTimeoutID);
},unMuteMouse:function(){clearTimeout(ad.mouseTrapTimeoutID);
ad.mouseTrapTimeoutID=setTimeout(function(){ad.captureMouse=false;
ad.bustClick=false;
},400);
}};
var y={down:"touchstart mousedown",move:"mousemove touchmove",up:"mouseup touchend touchcancel",cancel:"mouseleave touchcancel"};
if(aD.touch&&(aD.mobileOS.ios||aD.mobileOS.android)){y={down:"touchstart",move:"touchmove",up:"touchend touchcancel",cancel:"touchcancel"};
}else{if(aD.pointers){y={down:"pointerdown",move:"pointermove",up:"pointerup",cancel:"pointercancel pointerleave"};
}else{if(aD.msPointers){y={down:"MSPointerDown",move:"MSPointerMove",up:"MSPointerUp",cancel:"MSPointerCancel MSPointerLeave"};
}}}if(aD.msPointers&&!("onmspointerenter" in aO)){a.each({MSPointerEnter:"MSPointerOver",MSPointerLeave:"MSPointerOut"},function(aT,aS){a.event.special[aT]={delegateType:aS,bindType:aS,handle:function(aU){var aX,aY=this,aW=aU.relatedTarget,aV=aU.handleObj;
if(!aW||(aW!==aY&&!a.contains(aY,aW))){aU.type=aV.origType;
aX=aV.handler.apply(this,arguments);
aU.type=aS;
}return aX;
}};
});
}var I=function(aS){return(y[aS]||aS);
},z=/([^ ]+)/g;
W.applyEventMap=function(aS,aT){aS=aS.replace(z,I);
if(aT){aS=aS.replace(z,"$1."+aT);
}return aS;
};
var ak=a.fn.on;
function X(aT,aS){return new X.fn.init(aT,aS);
}C(true,X,a);
X.fn=X.prototype=new a();
X.fn.constructor=X;
X.fn.init=function(aT,aS){if(aS&&aS instanceof a&&!(aS instanceof X)){aS=X(aS);
}return a.fn.init.call(this,aT,aS,aw);
};
X.fn.init.prototype=X.fn;
var aw=X(document);
C(X.fn,{handler:function(aS){this.data("handler",aS);
return this;
},autoApplyNS:function(aS){this.data("kendoNS",aS||W.guid());
return this;
},on:function(){var aZ=this,aX=aZ.data("kendoNS");
if(arguments.length===1){return ak.call(aZ,arguments[0]);
}var aV=aZ,aS=aB.call(arguments);
if(typeof aS[aS.length-1]===aL){aS.pop();
}var aU=aS[aS.length-1],aW=W.applyEventMap(aS[0],aX);
if(aD.mouseAndTouchPresent&&aW.search(/mouse|click/)>-1&&this[0]!==document.documentElement){ad.setupMouseMute();
var aY=aS.length===2?null:aS[1],aT=aW.indexOf("click")>-1&&aW.indexOf("touchend")>-1;
ak.call(this,{touchstart:ad.muteMouse,touchend:ad.unMuteMouse},aY,{bustClick:aT});
}if(typeof aU===aC){aV=aZ.data("handler");
aU=aV[aU];
aS[aS.length-1]=function(a0){aU.call(aV,a0);
};
}aS[0]=aW;
ak.apply(aZ,aS);
return aZ;
},kendoDestroy:function(aS){aS=aS||this.data("kendoNS");
if(aS){this.off("."+aS);
}return this;
}});
W.jQuery=X;
W.eventMap=y;
W.timezone=(function(){var aY={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};
var aV={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};
function a1(bc,a9){var a5;
var ba;
var a8;
var a6=a9[3];
var a7=a9[4];
var bb=a9[5];
var a4=a9[8];
if(!a4){a9[8]=a4={};
}if(a4[bc]){return a4[bc];
}if(!isNaN(a7)){a5=new Date(Date.UTC(bc,aY[a6],a7,bb[0],bb[1],bb[2],0));
}else{if(a7.indexOf("last")===0){a5=new Date(Date.UTC(bc,aY[a6]+1,1,bb[0]-24,bb[1],bb[2],0));
ba=aV[a7.substr(4,3)];
a8=a5.getUTCDay();
a5.setUTCDate(a5.getUTCDate()+ba-a8-(ba>a8?7:0));
}else{if(a7.indexOf(">=")>=0){a5=new Date(Date.UTC(bc,aY[a6],a7.substr(5),bb[0],bb[1],bb[2],0));
ba=aV[a7.substr(0,3)];
a8=a5.getUTCDay();
a5.setUTCDate(a5.getUTCDate()+ba-a8+(ba<a8?7:0));
}}}return a4[bc]=a5;
}function aW(a8,a6,ba){a6=a6[ba];
if(!a6){var a7=ba.split(":");
var a4=0;
if(a7.length>1){a4=a7[0]*60+Number(a7[1]);
}return[-1000000,"max","-","Jan",1,[0,0,0],a4,"-"];
}var a9=new Date(a8).getUTCFullYear();
a6=jQuery.grep(a6,function(bc){var bb=bc[0];
var bd=bc[1];
return bb<=a9&&(bd>=a9||(bb==a9&&bd=="only")||bd=="max");
});
a6.push(a8);
a6.sort(function(bb,bc){if(typeof bb!="number"){bb=Number(a1(a9,bb));
}if(typeof bc!="number"){bc=Number(a1(a9,bc));
}return bb-bc;
});
var a5=a6[jQuery.inArray(a8,a6)-1]||a6[a6.length-1];
return isNaN(a5)?a5:null;
}function aX(a7,ba,a5){var a9=ba[a5];
if(typeof a9==="string"){a9=ba[a9];
}if(!a9){throw new Error('Timezone "'+a5+'" is either incorrect, or kendo.timezones.min.js is not included.');
}for(var a4=a9.length-1;
a4>=0;
a4--){var a6=a9[a4][3];
if(a6&&a7>a6){break;
}}var a8=a9[a4+1];
if(!a8){throw new Error('Timezone "'+a5+'" not found on '+a7+".");
}return a8;
}function a3(a6,a8,a4,a5){if(typeof a6!=ag){a6=Date.UTC(a6.getFullYear(),a6.getMonth(),a6.getDate(),a6.getHours(),a6.getMinutes(),a6.getSeconds(),a6.getMilliseconds());
}var a7=aX(a6,a8,a5);
return{zone:a7,rule:aW(a6,a4,a7[1])};
}function aZ(a7,a6){if(a6=="Etc/UTC"||a6=="Etc/GMT"){return 0;
}var a4=a3(a7,this.zones,this.rules,a6);
var a8=a4.zone;
var a5=a4.rule;
return W.parseFloat(a5?a8[0]-a5[6]:a8[0]);
}function aS(a8,a7){var a5=a3(a8,this.zones,this.rules,a7);
var a9=a5.zone;
var a6=a5.rule;
var a4=a9[2];
if(a4.indexOf("/")>=0){return a4.split("/")[a6&&+a6[6]?1:0];
}else{if(a4.indexOf("%s")>=0){return a4.replace("%s",(!a6||a6[7]=="-")?"":a6[7]);
}}return a4;
}function aU(a4,a6,a8){if(typeof a6==aC){a6=this.offset(a4,a6);
}if(typeof a8==aC){a8=this.offset(a4,a8);
}var a5=a4.getTimezoneOffset();
a4=new Date(a4.getTime()+(a6-a8)*60000);
var a7=a4.getTimezoneOffset();
return new Date(a4.getTime()+(a7-a5)*60000);
}function aT(a4,a5){return this.convert(a4,a4.getTimezoneOffset(),a5);
}function a0(a4,a5){return this.convert(a4,a5,a4.getTimezoneOffset());
}function a2(a4){return this.apply(new Date(a4),"Etc/UTC");
}return{zones:{},rules:{},offset:aZ,convert:aU,apply:aT,remove:a0,abbr:aS,toLocalDate:a2};
})();
W.date=(function(){var a3=60000,a2=86400000;
function aT(a9,ba){if(ba===0&&a9.getHours()===23){a9.setHours(a9.getHours()+2);
return true;
}return false;
}function a4(a9,ba,bb){var bc=a9.getHours();
bb=bb||1;
ba=((ba-a9.getDay())+(7*bb))%7;
a9.setDate(a9.getDate()+ba);
aT(a9,bc);
}function aU(a9,ba,bb){a9=new Date(a9);
a4(a9,ba,bb);
return a9;
}function aV(a9){return new Date(a9.getFullYear(),a9.getMonth(),1);
}function a1(a9){var bb=new Date(a9.getFullYear(),a9.getMonth()+1,0),ba=aV(a9),bc=Math.abs(bb.getTimezoneOffset()-ba.getTimezoneOffset());
if(bc){bb.setHours(ba.getHours()+(bc/60));
}return bb;
}function aW(a9){a9=new Date(a9.getFullYear(),a9.getMonth(),a9.getDate(),0,0,0);
aT(a9,0);
return a9;
}function a8(a9){return Date.UTC(a9.getFullYear(),a9.getMonth(),a9.getDate(),a9.getHours(),a9.getMinutes(),a9.getSeconds(),a9.getMilliseconds());
}function aX(a9){return a9.getTime()-aW(a9);
}function aZ(be,ba,a9){var bc=aX(ba),bb=aX(a9),bd;
if(!be||bc==bb){return true;
}if(ba>=a9){a9+=a2;
}bd=aX(be);
if(bc>bd){bd+=a2;
}if(bb<bc){bb+=a2;
}return bd>=bc&&bd<=bb;
}function aY(be,ba,a9){var bc=ba.getTime(),bb=a9.getTime(),bd;
if(bc>=bb){bb+=a2;
}bd=be.getTime();
return bd>=bc&&bd<=bb;
}function aS(a9,bb){var ba=a9.getHours();
a9=new Date(a9);
a5(a9,bb*a2);
aT(a9,ba);
return a9;
}function a5(a9,bc,bb){var bd=a9.getTimezoneOffset();
var ba;
a9.setTime(a9.getTime()+bc);
if(!bb){ba=a9.getTimezoneOffset()-bd;
a9.setTime(a9.getTime()+ba*a3);
}}function a6(){return aW(new Date());
}function a0(a9){return aW(a9).getTime()==a6().getTime();
}function a7(a9){var ba=new Date(1980,1,1,0,0,0);
if(a9){ba.setHours(a9.getHours(),a9.getMinutes(),a9.getSeconds(),a9.getMilliseconds());
}return ba;
}return{adjustDST:aT,dayOfWeek:aU,setDayOfWeek:a4,getDate:aW,isInDateRange:aY,isInTimeRange:aZ,isToday:a0,nextDay:function(a9){return aS(a9,1);
},previousDay:function(a9){return aS(a9,-1);
},toUtcTime:a8,MS_PER_DAY:a2,MS_PER_HOUR:60*a3,MS_PER_MINUTE:a3,setTime:a5,addDays:aS,today:a6,toInvariantTime:a7,firstDayOfMonth:aV,lastDayOfMonth:a1,getMilliseconds:aX};
})();
W.stripWhitespace=function(aT){if(document.createNodeIterator){var aV=document.createNodeIterator(aT,NodeFilter.SHOW_TEXT,function(aW){return aW.parentNode==aT?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;
},false);
while(aV.nextNode()){if(aV.referenceNode&&!aV.referenceNode.textContent.trim()){aV.referenceNode.parentNode.removeChild(aV.referenceNode);
}}}else{for(var aU=0;
aU<aT.childNodes.length;
aU++){var aS=aT.childNodes[aU];
if(aS.nodeType==3&&!/\S/.test(aS.nodeValue)){aT.removeChild(aS);
aU--;
}if(aS.nodeType==1){W.stripWhitespace(aS);
}}}};
var d=aO.requestAnimationFrame||aO.webkitRequestAnimationFrame||aO.mozRequestAnimationFrame||aO.oRequestAnimationFrame||aO.msRequestAnimationFrame||function(aS){setTimeout(aS,1000/60);
};
W.animationFrame=function(aS){d.call(aO,aS);
};
var e=[];
W.queueAnimation=function(aS){e[e.length]=aS;
if(e.length===1){W.runNextAnimation();
}};
W.runNextAnimation=function(){W.animationFrame(function(){if(e[0]){e.shift()();
if(e[0]){W.runNextAnimation();
}}});
};
W.parseQueryStringParams=function(aX){var aW=aX.split("?")[1]||"",aV={},aU=aW.split(/&|=/),aT=aU.length,aS=0;
for(;
aS<aT;
aS+=2){if(aU[aS]!==""){aV[decodeURIComponent(aU[aS])]=decodeURIComponent(aU[aS+1]);
}}return aV;
};
W.elementUnderCursor=function(aS){if(typeof aS.x.client!="undefined"){return document.elementFromPoint(aS.x.client,aS.y.client);
}};
W.wheelDeltaY=function(aV){var aU=aV.originalEvent,aT=aU.wheelDeltaY,aS;
if(aU.wheelDelta){if(aT===aK||aT){aS=aU.wheelDelta;
}}else{if(aU.detail&&aU.axis===aU.VERTICAL_AXIS){aS=(-aU.detail)*10;
}}return aS;
};
W.throttle=function(aT,aS){var aW;
var aU=0;
if(!aS||aS<=0){return aT;
}var aV=function(){var a0=this;
var aY=+new Date()-aU;
var aX=arguments;
function aZ(){aT.apply(a0,aX);
aU=+new Date();
}if(!aU){return aZ();
}if(aW){clearTimeout(aW);
}if(aY>aS){aZ();
}else{aW=setTimeout(aZ,aS-aY);
}};
aV.cancel=function(){clearTimeout(aW);
};
return aV;
};
W.caret=function(aT,a0,aU){var aX;
var aV=a0!==aK;
if(aU===aK){aU=a0;
}if(aT[0]){aT=aT[0];
}if(aV&&aT.disabled){return;
}try{if(aT.selectionStart!==aK){if(aV){aT.focus();
aT.setSelectionRange(a0,aU);
}else{a0=[aT.selectionStart,aT.selectionEnd];
}}else{if(document.selection){if(a(aT).is(":visible")){aT.focus();
}aX=aT.createTextRange();
if(aV){aX.collapse(true);
aX.moveStart("character",a0);
aX.moveEnd("character",aU-a0);
aX.select();
}else{var aW=aX.duplicate(),aZ,aY;
aX.moveToBookmark(document.selection.createRange().getBookmark());
aW.setEndPoint("EndToStart",aX);
aZ=aW.text.length;
aY=aZ+aX.text.length;
a0=[aZ,aY];
}}}}catch(aS){a0=[];
}return a0;
};
W.compileMobileDirective=function(aT,aU){var aS=aO.angular;
aT.attr("data-"+W.ns+"role",aT[0].tagName.toLowerCase().replace("kendo-mobile-","").replace("-",""));
aS.element(aT).injector().invoke(["$compile",function(aV){aV(aT)(aU);
if(!/^\$(digest|apply)$/.test(aU.$$phase)){aU.$digest();
}}]);
return W.widgetInstance(aT,W.mobile.ui);
};
W.antiForgeryTokens=function(){var aU={},aT=a("meta[name=csrf-token],meta[name=_csrf]").attr("content"),aS=a("meta[name=csrf-param],meta[name=_csrf_header]").attr("content");
a("input[name^='__RequestVerificationToken']").each(function(){aU[this.name]=this.value;
});
if(aS!==aK&&aT!==aK){aU[aS]=aT;
}return aU;
};
W.cycleForm=function(aU){var aS=aU.find("input, .k-widget").first();
var aV=aU.find("button, .k-button").last();
function aT(aW){var aX=W.widgetInstance(aW);
if(aX&&aX.focus){aX.focus();
}else{aW.focus();
}}aV.on("keydown",function(aW){if(aW.keyCode==W.keys.TAB&&!aW.shiftKey){aW.preventDefault();
aT(aS);
}});
aS.on("keydown",function(aW){if(aW.keyCode==W.keys.TAB&&aW.shiftKey){aW.preventDefault();
aT(aV);
}});
};
(function(){function aU(aY,aZ,a4,a3){var a0=a("<form>").attr({action:a4,method:"POST",target:a3});
var aX=W.antiForgeryTokens();
aX.fileName=aZ;
var a2=aY.split(";base64,");
aX.contentType=a2[0].replace("data:","");
aX.base64=a2[1];
for(var a1 in aX){if(aX.hasOwnProperty(a1)){a("<input>").attr({value:aX[a1],name:a1,type:"hidden"}).appendTo(a0);
}}a0.appendTo("body").submit().remove();
}var aT=document.createElement("a");
var aS="download" in aT;
function aV(a1,a2){var aZ=a1;
if(typeof a1=="string"){var a4=a1.split(";base64,");
var a0=a4[0];
var aY=atob(a4[1]);
var aX=new Uint8Array(aY.length);
for(var a3=0;
a3<aY.length;
a3++){aX[a3]=aY.charCodeAt(a3);
}aZ=new Blob([aX.buffer],{type:a0});
}navigator.msSaveBlob(aZ,a2);
}function aW(aX,aZ){if(aO.Blob&&aX instanceof Blob){aX=URL.createObjectURL(aX);
}aT.download=aZ;
aT.href=aX;
var aY=document.createEvent("MouseEvents");
aY.initMouseEvent("click",true,false,aO,0,0,0,0,0,false,false,false,false,0,null);
aT.dispatchEvent(aY);
}W.saveAs=function(aX){var aY=aU;
if(!aX.forceProxy){if(aS){aY=aW;
}else{if(navigator.msSaveBlob){aY=aV;
}}}aY(aX.dataURI,aX.fileName,aX.proxyURL,aX.proxyTarget);
};
})();
})($telerik.$,window);
})();
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
