(function(b,a){a(["./kendo.core"],b);
})(function(){(function(){(function(g){function h(){this.node=null;
}h.prototype={remove:function(){this.node.parentNode.removeChild(this.node);
this.attr={};
},attr:{},text:function(){return"";
}};
function j(){}j.prototype={nodeName:"#null",attr:{style:{}},children:[],remove:function(){}};
var i=new j();
function b(p,n,o){this.nodeName=p;
this.attr=n||{};
this.children=o||[];
}b.prototype=new h();
b.prototype.appendTo=function(q){var p=document.createElement(this.nodeName);
var n=this.children;
for(var o=0;
o<n.length;
o++){n[o].render(p,i);
}q.appendChild(p);
return p;
};
b.prototype.render=function(u,n){var t;
if(n.nodeName!==this.nodeName){n.remove();
t=this.appendTo(u);
}else{t=n.node;
var r;
var q=this.children;
var s=q.length;
var o=n.children;
var p=o.length;
if(Math.abs(p-s)>2){this.render({appendChild:function(v){u.replaceChild(v,n.node);
}},i);
return;
}for(r=0;
r<s;
r++){q[r].render(t,o[r]||i);
}for(r=s;
r<p;
r++){o[r].remove();
}}this.node=t;
this.syncAttributes(n.attr);
this.removeAttributes(n.attr);
};
b.prototype.syncAttributes=function(o){var n=this.attr;
for(var q in n){var r=n[q];
var p=o[q];
if(q==="style"){this.setStyle(r,p);
}else{if(r!==p){this.setAttribute(q,r,p);
}}}};
b.prototype.setStyle=function(q,n){var p=this.node;
var o;
if(n){for(o in q){if(q[o]!==n[o]){p.style[o]=q[o];
}}}else{for(o in q){p.style[o]=q[o];
}}};
b.prototype.removeStyle=function(n){var q=this.attr.style||{};
var p=this.node;
for(var o in n){if(q[o]===undefined){p.style[o]="";
}}};
b.prototype.removeAttributes=function(o){var n=this.attr;
for(var p in o){if(p==="style"){this.removeStyle(o.style);
}else{if(n[p]===undefined){this.removeAttribute(p);
}}}};
b.prototype.removeAttribute=function(n){var o=this.node;
if(n==="style"){o.style.cssText="";
}else{if(n==="className"){o.className="";
}else{o.removeAttribute(n);
}}};
b.prototype.setAttribute=function(n,p){var o=this.node;
if(o[n]!==undefined){o[n]=p;
}else{o.setAttribute(n,p);
}};
b.prototype.text=function(){var o="";
for(var n=0;
n<this.children.length;
++n){o+=this.children[n].text();
}return o;
};
function l(n){this.nodeValue=n;
}l.prototype=new h();
l.prototype.nodeName="#text";
l.prototype.render=function(p,n){var o;
if(n.nodeName!==this.nodeName){n.remove();
o=document.createTextNode(this.nodeValue);
p.appendChild(o);
}else{o=n.node;
if(this.nodeValue!==n.nodeValue){o.nodeValue=this.nodeValue;
}}this.node=o;
};
l.prototype.text=function(){return this.nodeValue;
};
function e(n){this.html=n;
}e.prototype={nodeName:"#html",attr:{},remove:function(){for(var n=0;
n<this.nodes.length;
n++){this.nodes[n].parentNode.removeChild(this.nodes[n]);
}},render:function(q,n){if(n.nodeName!==this.nodeName||n.html!==this.html){n.remove();
var p=q.lastChild;
f(q,this.html);
this.nodes=[];
for(var o=p?p.nextSibling:q.firstChild;
o;
o=o.nextSibling){this.nodes.push(o);
}}else{this.nodes=n.nodes.slice(0);
}}};
var d=document.createElement("div");
function f(o,n){d.innerHTML=n;
while(d.firstChild){o.appendChild(d.firstChild);
}}function c(n){return new e(n);
}function a(p,n,o){return new b(p,n,o);
}function k(n){return new l(n);
}function m(n){this.root=n;
this.children=[];
}m.prototype={html:c,element:a,text:k,render:function(o){var n=this.children;
var p;
var q;
for(p=0,q=o.length;
p<q;
p++){o[p].render(this.root,n[p]||i);
}for(p=q;
p<n.length;
p++){n[p].remove();
}this.children=o;
}};
g.dom={html:c,text:k,element:a,Tree:m,Node:h};
})(window.kendo);
})();
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
