(function(b,a){a(["./kendo.list","./kendo.mobile.scroller"],b);
})(function(){(function(){(function(a,y){var l=window.kendo,x=l.ui,r=x.Select,v=l.support,b=l._activeElement,o=l.data.ObservableObject,m=l.keys,n=".kendoDropDownList",h="disabled",q="readonly",f="change",j="k-state-focused",g="k-state-default",u="k-state-disabled",c="aria-disabled",d="aria-readonly",k="mouseenter"+n+" mouseleave"+n,w="tabindex",t="filter",s="accept",p=a.proxy;
var i=r.extend({init:function(A,D){var F=this;
var B=D&&D.index;
var C,E,z;
F.ns=n;
D=a.isArray(D)?{dataSource:D}:D;
r.fn.init.call(F,A,D);
D=F.options;
A=F.element.on("focus"+n,p(F._focusHandler,F));
F._focusInputHandler=a.proxy(F._focusInput,F);
F._inputTemplate();
F._reset();
F._prev="";
F._word="";
F.optionLabel=a();
F._wrapper();
F._tabindex();
F.wrapper.data(w,F.wrapper.attr(w));
F._span();
F._popup();
F._mobile();
F._dataSource();
F._ignoreCase();
F._filterHeader();
F._aria();
F._enable();
F._oldIndex=F.selectedIndex=-1;
if(B!==y){D.index=B;
}F._initialIndex=D.index;
F._optionLabel();
F._initList();
F._cascade();
if(D.autoBind){F.dataSource.fetch();
}else{if(F.selectedIndex===-1){E=D.text||"";
if(!E){C=D.optionLabel;
if(C&&D.index===0){E=C;
}else{if(F._isSelect){E=A.children(":selected").text();
}}}F._textAccessor(E);
}}z=a(F.element).parents("fieldset").is(":disabled");
if(z){F.enable(false);
}F.listView.bind("click",function(G){G.preventDefault();
});
l.notify(F);
},options:{name:"DropDownList",enabled:true,autoBind:true,index:0,text:null,value:null,delay:500,height:200,dataTextField:"",dataValueField:"",optionLabel:"",cascadeFrom:"",cascadeFromField:"",ignoreCase:true,animation:{},filter:"none",minLength:1,virtual:false,template:null,valueTemplate:null,optionLabelTemplate:null,groupTemplate:"#:data#",fixedGroupTemplate:"#:data#"},events:["open","close",f,"select","filtering","dataBinding","dataBound","cascade"],setOptions:function(z){r.fn.setOptions.call(this,z);
this.listView.setOptions(this._listOptions(z));
this._optionLabel();
this._inputTemplate();
this._accessors();
this._filterHeader();
this._enable();
this._aria();
if(!this.value()&&this.optionLabel[0]){this.select(0);
}},destroy:function(){var z=this;
z.wrapper.off(n);
z.element.off(n);
z._inputWrapper.off(n);
z._arrow.off();
z._arrow=null;
z.optionLabel.off();
r.fn.destroy.call(z);
},open:function(){var z=this;
if(z.popup.visible()){return;
}if(!z.listView.isBound()||z._state===s){z._open=true;
z._state="rebind";
if(z.filterInput){z.filterInput.val("");
z._prev="";
}z._filterSource();
}else{if(z._allowOpening()){z.popup.one("activate",z._focusInputHandler);
z.popup.open();
z._focusItem();
}}},_focusInput:function(){this._focusElement(this.filterInput);
},_allowOpening:function(){return this.optionLabel[0]||this.filterInput||this.dataSource.view().length;
},toggle:function(z){this._toggle(z,true);
},current:function(z){var A;
if(z===y){A=this.listView.focus();
if(!A&&this.selectedIndex===0&&this.optionLabel[0]){return this.optionLabel;
}return A;
}this._focus(z);
},dataItem:function(B){var D=this;
var z=null;
var A=!!D.optionLabel[0];
var C=D.options.optionLabel;
if(B===y){z=D.listView.selectedDataItems()[0];
}else{if(typeof B!=="number"){if(B.hasClass("k-list-optionlabel")){B=-1;
}else{B=a(D.items()).index(B);
}}else{if(A){B-=1;
}}z=D.dataSource.flatView()[B];
}if(!z&&A){z=a.isPlainObject(C)?new o(C):D._assignInstance(D._optionLabelText(),"");
}return z;
},refresh:function(){this.listView.refresh();
},text:function(C){var D=this;
var z,B;
var A=D.options.ignoreCase;
C=C===null?"":C;
if(C!==y){if(typeof C==="string"){B=A?C.toLowerCase():C;
D._select(function(E){E=D._text(E);
if(A){E=(E+"").toLowerCase();
}return E===B;
});
z=D.dataItem();
if(z){C=z;
}}D._textAccessor(C);
}else{return D._textAccessor();
}},value:function(B){var A=this;
var z=A.dataSource;
if(B===y){B=A._accessor()||A.listView.value()[0];
return B===y||B===null?"":B;
}if(B){A._initialIndex=null;
}if(A._request&&A.options.cascadeFrom&&A.listView.isBound()){if(A._valueSetter){z.unbind(f,A._valueSetter);
}A._valueSetter=p(function(){A.value(B);
},A);
z.one(f,A._valueSetter);
return;
}A.listView.value(B).done(function(){if(A.selectedIndex===-1&&A.text()){A.text("");
A._accessor("",-1);
}A._old=A._accessor();
A._oldIndex=A.selectedIndex;
});
A._fetchData();
},_optionLabel:function(){var C=this;
var A=C.options;
var z=A.optionLabel;
var B=A.optionLabelTemplate;
if(!z){C.optionLabel.off().remove();
C.optionLabel=a();
return;
}if(!B){B="#:";
if(typeof z==="string"){B+="data";
}else{B+=l.expr(A.dataTextField,"data");
}B+="#";
}if(typeof B!=="function"){B=l.template(B);
}C.optionLabelTemplate=B;
if(!C.optionLabel[0]){C.optionLabel=a('<div class="k-list-optionlabel"></div>').prependTo(C.list);
}C.optionLabel.html(B(z)).off().click(p(C._click,C)).on(k,C._toggleHover);
C.angular("compile",function(){return{elements:C.optionLabel};
});
},_optionLabelText:function(){var z=this.options.optionLabel;
return(typeof z==="string")?z:this._text(z);
},_listBound:function(){var G=this;
var D=G._initialIndex;
var F=G.options.optionLabel;
var B=G._state===t;
var z=G.dataSource.flatView();
var E=z.length;
var A;
var C;
var H;
G._angularItems("compile");
G._presetValue=false;
if(!G.options.virtual){C=G._height(B?(E||1):E);
G._calculateGroupPadding(C);
}G.popup.position();
if(G._isSelect){H=G.value();
if(E){if(F){F=G._option("",G._optionLabelText());
}}else{if(H){F=G._option(H,G.text());
}}G._options(z,F,H);
}G._makeUnselectable();
if(!B){if(G._open){G.toggle(G._allowOpening());
}G._open=false;
if(!G._fetch){if(E){if(!G.listView.value().length&&D>-1&&D!==null){G.select(D);
}G._initialIndex=null;
A=G.listView.selectedDataItems()[0];
if(A&&G.text()!==G._text(A)){G._selectValue(A);
}}else{if(G._textAccessor()!==G._optionLabelText()){G.listView.value("");
G._selectValue(null);
G._oldIndex=G.selectedIndex;
}}}}G._hideBusy();
G.trigger("dataBound");
},_listChange:function(){this._selectValue(this.listView.selectedDataItems()[0]);
if(this._presetValue||(this._old&&this._oldIndex===-1)){this._oldIndex=this.selectedIndex;
}},_focusHandler:function(){this.wrapper.focus();
},_focusinHandler:function(){this._inputWrapper.addClass(j);
this._prevent=false;
},_focusoutHandler:function(){var C=this;
var z=C._state===t;
var B=window.self!==window.top;
var A=C._focus();
if(!C._prevent){clearTimeout(C._typingTimeout);
if(z&&A&&!C.trigger("select",{item:A})){C._select(A,!C.dataSource.view().length);
}if(v.mobileOS.ios&&B){C._change();
}else{C._blur();
}C._inputWrapper.removeClass(j);
C._prevent=true;
C._open=false;
C.element.blur();
}},_wrapperMousedown:function(){this._prevent=!!this.filterInput;
},_wrapperClick:function(z){z.preventDefault();
this.popup.unbind("activate",this._focusInputHandler);
this._focused=this.wrapper;
this._toggle();
},_editable:function(C){var E=this;
var B=E.element;
var z=C.disable;
var D=C.readonly;
var F=E.wrapper.add(E.filterInput).off(n);
var A=E._inputWrapper.off(k);
if(!D&&!z){B.removeAttr(h).removeAttr(q);
A.addClass(g).removeClass(u).on(k,E._toggleHover);
F.attr(w,F.data(w)).attr(c,false).attr(d,false).on("keydown"+n,p(E._keydown,E)).on("focusin"+n,p(E._focusinHandler,E)).on("focusout"+n,p(E._focusoutHandler,E)).on("mousedown"+n,p(E._wrapperMousedown,E));
E.wrapper.on("click"+n,p(E._wrapperClick,E));
if(!E.filterInput){F.on("keypress"+n,p(E._keypress,E));
}}else{if(z){F.removeAttr(w);
A.addClass(u).removeClass(g);
}else{A.addClass(g).removeClass(u);
F.on("focusin"+n,p(E._focusinHandler,E)).on("focusout"+n,p(E._focusoutHandler,E));
}}B.attr(h,z).attr(q,D);
F.attr(c,z).attr(d,D);
},_option:function(A,z){return'<option value="'+A+'">'+z+"</option>";
},_keydown:function(A){var F=this;
var E=A.keyCode;
var z=A.altKey;
var C;
var B;
var D=F.popup.visible();
if(F.filterInput){C=F.filterInput[0]===b();
}if(E===m.LEFT){E=m.UP;
B=true;
}else{if(E===m.RIGHT){E=m.DOWN;
B=true;
}}if(B&&C){return;
}A.keyCode=E;
if(z&&E===m.UP){F._focusElement(F.wrapper);
}if(E===m.ENTER&&F._typingTimeout&&F.filterInput&&D){A.preventDefault();
return;
}B=F._move(A);
if(B){return;
}if(!D||!F.filterInput){if(E===m.HOME){B=true;
F._firstItem();
}else{if(E===m.END){B=true;
F._lastItem();
}}if(B){F._select(F._focus());
A.preventDefault();
}}if(!z&&!B&&F.filterInput){F._search();
}},_matchText:function(C,B){var D=this;
var A=D.options.ignoreCase;
var z=false;
C=C+"";
if(A){C=C.toLowerCase();
}if(C.indexOf(D._word)===0){if(D.optionLabel[0]){B+=1;
}D._select(B);
if(!D.popup.visible()){D._change();
}z=true;
}return z;
},_selectNext:function(A){var E=this;
var C=A;
var z=E.dataSource.flatView();
var B=z.length;
var D;
for(;
A<B;
A++){D=E._text(z[A]);
if(D&&E._matchText(D,A)&&!(E._word.length===1&&C===E.selectedIndex)){return true;
}}if(C>0&&C<B){A=0;
for(;
A<=C;
A++){D=E._text(z[A]);
if(D&&E._matchText(D,A)){return true;
}}}return false;
},_keypress:function(A){var D=this;
if(A.which===0||A.keyCode===l.keys.ENTER){return;
}var z=String.fromCharCode(A.charCode||A.keyCode);
var B=D.selectedIndex;
var C=D._word.length;
if(D.options.ignoreCase){z=z.toLowerCase();
}if(z===" "){A.preventDefault();
}if(!C){D._word=z;
}if(D._last===z&&C<=1&&B>-1){if(D._selectNext(B)){return;
}}if(C){D._word+=z;
}D._last=z;
D._search();
},_popupOpen:function(){var z=this.popup;
z.wrapper=l.wrap(z.element);
if(z.element.closest(".km-root")[0]){z.wrapper.addClass("km-popup km-widget");
this.wrapper.addClass("km-widget");
}},_popup:function(){r.fn._popup.call(this);
this.popup.one("open",p(this._popupOpen,this));
},_click:function(z){var A=z.item||a(z.currentTarget);
if(this.trigger("select",{item:A})){this.close();
return;
}this._userTriggered=true;
this._select(A);
this._focusElement(this.wrapper);
this._blur();
},_focusElement:function(B){var z=b();
var E=this.wrapper;
var C=this.filterInput;
var A=B===C?E:C;
var D=v.mobileOS&&(v.touch||v.MSPointers||v.pointers);
if(C&&C[0]===B[0]&&D){return;
}if(C&&A[0]===z){this._prevent=true;
this._focused=B.focus();
}},_filter:function(B){if(B){var A=this;
var z=A.options.ignoreCase;
if(z){B=B.toLowerCase();
}A._select(function(C){var D=A._text(C);
if(D!==y){D=(D+"");
if(z){D=D.toLowerCase();
}return D.indexOf(B)===0;
}});
}},_search:function(){var B=this;
var z=B.dataSource;
var A=B.selectedIndex;
clearTimeout(B._typingTimeout);
if(B.options.filter!=="none"){B._typingTimeout=setTimeout(function(){var C=B.filterInput.val();
if(B._prev!==C){B._prev=C;
B.search(C);
}B._typingTimeout=null;
},B.options.delay);
}else{B._typingTimeout=setTimeout(function(){B._word="";
},B.options.delay);
if(A===-1){A=0;
}if(!B.ul[0].firstChild){z.fetch().done(function(){if(z.data()[0]&&A>-1){B._selectNext(A);
}});
return;
}B._selectNext(A);
}},_get:function(z){var A,B,C;
var D=typeof z==="function";
var E=!D?a(z):a();
if(this.optionLabel[0]){if(typeof z==="number"){if(z>-1){z-=1;
}}else{if(E.hasClass("k-list-optionlabel")){z=-1;
}}}if(D){A=this.dataSource.flatView();
for(C=0;
C<A.length;
C++){if(z(A[C])){z=C;
B=true;
break;
}}if(!B){z=-1;
}}return z;
},_firstItem:function(){if(this.optionLabel[0]){this._focus(this.optionLabel);
}else{this.listView.focusFirst();
}},_lastItem:function(){this.optionLabel.removeClass("k-state-focused");
this.listView.focusLast();
},_nextItem:function(){if(this.optionLabel.hasClass("k-state-focused")){this.optionLabel.removeClass("k-state-focused");
this.listView.focusFirst();
}else{this.listView.focusNext();
}},_prevItem:function(){if(this.optionLabel.hasClass("k-state-focused")){return;
}this.listView.focusPrev();
if(!this.listView.focus()){this.optionLabel.addClass("k-state-focused");
}},_focusItem:function(){var B=this.listView;
var z=B.focus();
var A=B.select();
A=A[A.length-1];
if(A===y&&this.options.highlightFirst&&!z){A=0;
}if(A!==y){B.focus(A);
}else{if(this.options.optionLabel){this._focus(this.optionLabel);
this._select(this.optionLabel);
}else{B.scrollToIndex(0);
}}},_focus:function(z){var A=this.listView;
var B=this.optionLabel;
if(z===y){z=A.focus();
if(!z&&B.hasClass("k-state-focused")){z=B;
}return z;
}B.removeClass("k-state-focused");
z=this._get(z);
A.focus(z);
if(z===-1){B.addClass("k-state-focused");
}},_select:function(z,A){var B=this;
z=B._get(z);
B.listView.select(z);
if(!A&&B._state===t){B.listView.filter(false);
B._state=s;
}if(z===-1){B._selectValue(null);
}},_selectValue:function(z){var E=this;
var C=E.options.optionLabel;
var B=E.optionLabel;
var A=E.listView.select();
var F="";
var D="";
A=A[A.length-1];
if(A===y){A=-1;
}B.removeClass("k-state-focused k-state-selected");
if(z){D=z;
F=E._dataValue(z);
if(C){A+=1;
}}else{if(C){E._focus(B.addClass("k-state-selected"));
D=E._optionLabelText();
if(typeof C==="string"){F="";
}else{F=E._value(C);
}A=0;
}}E.selectedIndex=A;
if(F===null){F="";
}E._textAccessor(D);
E._accessor(F,A);
E._triggerCascade();
},_mobile:function(){var C=this,A=C.popup,z=v.mobileOS,B=A.element.parents(".km-root").eq(0);
if(B.length&&z){A.options.animation.open.effects=(z.android||z.meego)?"fadeIn":(z.ios||z.wp)?"slideIn:up":A.options.animation.open.effects;
}},_filterHeader:function(){var A;
var B=this.options;
var z=B.filter!=="none";
if(this.filterInput){this.filterInput.off(n).parent().remove();
this.filterInput=null;
}if(z){A='<span unselectable="on" class="k-icon k-i-search">select</span>';
this.filterInput=a('<input class="k-textbox"/>').attr({role:"listbox","aria-haspopup":true,"aria-expanded":false});
this.list.prepend(a('<span class="k-list-filter" />').append(this.filterInput.add(A)));
}},_span:function(){var B=this,C=B.wrapper,z="span.k-input",A;
A=C.find(z);
if(!A[0]){C.append('<span unselectable="on" class="k-dropdown-wrap k-state-default"><span unselectable="on" class="k-input">&nbsp;</span><span unselectable="on" class="k-select"><span unselectable="on" class="k-icon k-i-arrow-s">select</span></span></span>').append(B.element);
A=C.find(z);
}B.span=A;
B._inputWrapper=a(C[0].firstChild);
B._arrow=C.find(".k-icon");
},_wrapper:function(){var B=this,A=B.element,z=A[0],C;
C=A.parent();
if(!C.is("span.k-widget")){C=A.wrap("<span />").parent();
C[0].style.cssText=z.style.cssText;
C[0].title=z.title;
}A.hide();
B._focused=B.wrapper=C.addClass("k-widget k-dropdown k-header").addClass(z.className).css("display","").attr({unselectable:"on",role:"listbox","aria-haspopup":true,"aria-expanded":false});
},_clearSelection:function(z){this.select(z.value()?0:-1);
},_inputTemplate:function(){var A=this,z=A.options.valueTemplate;
if(!z){z=a.proxy(l.template("#:this._text(data)#",{useWithBlock:false}),A);
}else{z=l.template(z);
}A.valueTemplate=z;
},_textAccessor:function(F){var z=null;
var E=this.valueTemplate;
var C=this.options;
var B=C.optionLabel;
var D=this.span;
if(F!==y){if(a.isPlainObject(F)||F instanceof o){z=F;
}else{if(B&&this._optionLabelText()===F){z=B;
E=this.optionLabelTemplate;
}}if(!z){z=this._assignInstance(F,this._accessor());
}var A=function(){return{elements:D.get(),data:[{dataItem:z}]};
};
this.angular("cleanup",A);
D.html(E(z));
this.angular("compile",A);
}else{return D.text();
}},_preselect:function(A,z){if(!A&&!z){z=this._optionLabelText();
}this._accessor(A);
this._textAccessor(z);
this._old=this._accessor();
this._oldIndex=this.selectedIndex;
this.listView.setValue(A);
this._initialIndex=null;
this._presetValue=true;
},_assignInstance:function(B,C){var A=this.options.dataTextField;
var z={};
if(A){e(z,A.split("."),B);
e(z,this.options.dataValueField.split("."),C);
z=new o(z);
}else{z=B;
}return z;
}});
function e(C,A,E){var B=0,D=A.length-1,z;
for(;
B<D;
++B){z=A[B];
if(!(z in C)){C[z]={};
}C=C[z];
}C[A[D]]=E;
}x.plugin(i);
})(window.kendo.jQuery);
})();
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
