(function(b,a){a(["./kendo.datepicker","./kendo.numerictextbox","./kendo.validator","./kendo.binder"],b);
})(function(){(function(){(function(a,t){var o=window.kendo,s=o.ui,u=s.Widget,j=a.extend,q=o.support.browser.msie&&o.support.browser.version<9,m=o.isFunction,n=a.isPlainObject,l=a.inArray,p=/("|\%|'|\[|\]|\$|\.|\,|\:|\;|\+|\*|\&|\!|\#|\(|\)|<|>|\=|\?|\@|\^|\{|\}|\~|\/|\||`)/g,i='<div class="k-widget k-tooltip k-tooltip-validation" style="margin:0.5em"><span class="k-icon k-warning"> </span>#=message#<div class="k-callout k-callout-n"></div></div>',c="change";
var r=["url","email","number","date","boolean"];
function k(v){v=v!=null?v:"";
return v.type||a.type(v)||"string";
}function e(v){v.find(":input:not(:button, ["+o.attr("role")+"=upload], ["+o.attr("skip")+"], [type=file]), select").each(function(){var w=o.attr("bind"),x=this.getAttribute(w)||"",y=this.type==="checkbox"||this.type==="radio"?"checked:":"value:",z=this.name;
if(x.indexOf(y)===-1&&z){x+=(x.length?",":"")+y+z;
a(this).attr(w,x);
}});
}function f(z){var y=(z.model.fields||z.model)[z.field],C=k(y),D=y?y.validation:{},B,x=o.attr("type"),w=o.attr("bind"),A,v={name:z.field};
for(B in D){A=D[B];
if(l(B,r)>=0){v[x]=B;
}else{if(!m(A)){v[B]=n(A)?A.value||B:A;
}}v[o.attr(B+"-msg")]=A.message;
}if(l(C,r)>=0){v[x]=C;
}v[w]=(C==="boolean"?"checked:":"value:")+z.field;
return v;
}function d(x){var v,y,w,B,A,z;
if(x&&x.length){z=[];
for(v=0,y=x.length;
v<y;
v++){w=x[v];
A=w.text||w.value||w;
B=w.value==null?(w.text||w):w.value;
z[v]={text:A,value:B};
}}return z;
}var h={number:function(w,x){var v=f(x);
a('<input type="text"/>').attr(v).appendTo(w).kendoNumericTextBox({format:x.format});
a("<span "+o.attr("for")+'="'+x.field+'" class="k-invalid-msg"/>').hide().appendTo(w);
},date:function(w,y){var v=f(y),x=y.format;
if(x){x=o._extractFormat(x);
}v[o.attr("format")]=x;
a('<input type="text"/>').attr(v).appendTo(w).kendoDatePicker({format:y.format});
a("<span "+o.attr("for")+'="'+y.field+'" class="k-invalid-msg"/>').hide().appendTo(w);
},string:function(w,x){var v=f(x);
a('<input type="text" class="k-input k-textbox"/>').attr(v).appendTo(w);
},"boolean":function(w,x){var v=f(x);
a('<input type="checkbox" />').attr(v).appendTo(w);
},values:function(w,y){var v=f(y);
var x=o.stringify(d(y.values));
a("<select "+o.attr("text-field")+'="text"'+o.attr("value-field")+'="value"'+o.attr("source")+"='"+(x?x.replace(/\'/g,"&apos;"):x)+"'"+o.attr("role")+'="dropdownlist"/>').attr(v).appendTo(w);
a("<span "+o.attr("for")+'="'+y.field+'" class="k-invalid-msg"/>').hide().appendTo(w);
}};
function b(w,y){var z=w?(w.validation||{}):{},x,v;
for(x in z){v=z[x];
if(n(v)&&v.value){v=v.value;
}if(m(v)){y[x]=v;
}}}var g=u.extend({init:function(v,w){var x=this;
if(w.target){w.$angular=w.target.options.$angular;
}u.fn.init.call(x,v,w);
x._validateProxy=a.proxy(x._validate,x);
x.refresh();
},events:[c],options:{name:"Editable",editors:h,clearContainer:true,errorTemplate:i},editor:function(y,E){var F=this,x=F.options.editors,B=n(y),z=B?y.field:y,D=F.options.model||{},C=B&&y.values,G=C?"values":k(E),A=B&&y.editor,w=A?y.editor:x[G],v=F.element.find("["+o.attr("container-for")+"="+z.replace(p,"\\$1")+"]");
w=w?w:x.string;
if(A&&typeof y.editor==="string"){w=function(H){H.append(y.editor);
};
}v=v.length?v:F.element;
w(v,j(true,{},B?y:{field:z},{model:D}));
},_validate:function(x){var B=this,z,C=x.value,A=B._validationEventInProgress,D={},v=o.attr("bind"),y=x.field.replace(p,"\\$1"),w=new RegExp("(value|checked)\\s*:\\s*"+y+"\\s*(,|$)");
D[x.field]=x.value;
z=a(":input["+v+'*="'+y+'"]',B.element).filter("["+o.attr("validate")+"!='false']").filter(function(){return w.test(a(this).attr(v));
});
if(z.length>1){z=z.filter(function(){var E=a(this);
return !E.is(":radio")||E.val()==C;
});
}try{B._validationEventInProgress=true;
if(!B.validatable.validateInput(z)||(!A&&B.trigger(c,{values:D}))){x.preventDefault();
}}finally{B._validationEventInProgress=false;
}},end:function(){return this.validatable.validate();
},destroy:function(){var v=this;
v.angular("cleanup",function(){return{elements:v.element};
});
u.fn.destroy.call(v);
v.options.model.unbind("set",v._validateProxy);
o.unbind(v.element);
if(v.validatable){v.validatable.destroy();
}o.destroy(v.element);
v.element.removeData("kendoValidator");
},refresh:function(){var H=this,A,C,y=H.options.fields||[],v=H.options.clearContainer?H.element.empty():H.element,D=H.options.model||{},G={},w,B,x,E,F;
if(!a.isArray(y)){y=[y];
}for(A=0,C=y.length;
A<C;
A++){w=y[A];
B=n(w);
x=B?w.field:w;
E=(D.fields||D)[x];
b(E,G);
H.editor(w,E);
}if(H.options.target){H.angular("compile",function(){return{elements:v,data:v.map(function(){return{dataItem:D};
})};
});
}if(!C){F=D.fields||D;
for(x in F){b(F[x],G);
}}e(v);
if(H.validatable){H.validatable.destroy();
}o.bind(v,H.options.model);
H.options.model.unbind("set",H._validateProxy);
H.options.model.bind("set",H._validateProxy);
H.validatable=new o.ui.Validator(v,{validateOnBlur:false,errorTemplate:H.options.errorTemplate||t,rules:G});
var z=v.find(":kendoFocusable").eq(0).focus();
if(q){z.focus();
}}});
s.plugin(g);
})(window.kendo.jQuery);
})();
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
