(function(b,a){a(["./kendo.data","./kendo.popup","./kendo.window","./kendo.resizable","./kendo.gantt.list","./kendo.gantt.timeline","./kendo.grid","./kendo.pdf"],b);
})(function(){(function(){(function(a,ae){var G=window.kendo;
var X="matchMedia" in window;
var e=G.support.browser;
var J=G.support.mobileOS;
var L=G.Observable;
var ag=G.ui.Widget;
var j=G.data.DataSource;
var N=G.data.ObservableObject;
var M=G.data.ObservableArray;
var R=G.data.Query;
var D=a.isArray;
var C=a.inArray;
var E=G.isFunction;
var Q=a.proxy;
var t=a.extend;
var F=a.isPlainObject;
var I=a.map;
var H=G.keys;
var n=3;
var K=".kendoGantt";
var O="p0";
var Y="tabIndex";
var g="click";
var ah="width";
var W="string";
var p={down:{origin:"bottom left",position:"top left"},up:{origin:"top left",position:"bottom left"}};
var d="aria-activedescendant";
var b="gantt_active_cell";
var c="action-option-focused";
var q=".";
var Z="Are you sure you want to delete this task?";
var o="Are you sure you want to delete this dependency?";
var ac=G.template('<button class="#=styles.buttonToggle#"><span class="#=styles.iconToggle#">&nbps;</span></button>');
var f='<button class="#=styles.button# #=className#" #if (action) {#data-action="#=action#"#}#><span class="#=iconClass#"></span><span>#=text#</span></button>';
var h='<a class="#=className#" #=attr# href="\\#">#=text#</a>';
var af=G.template('<li class="#=styles.currentView# #=styles.viewButtonDefault#"><a href="\\#" class="#=styles.link#">&nbps;</a></li>');
var B=G.template('<ul class="#=styles.viewsWrapper#">#for(var view in views){#<li class="#=styles.viewButtonDefault# #=styles.viewButton#-#= view.toLowerCase() #" data-#=ns#name="#=view#"><a href="\\#" class="#=styles.link#">#=views[view].title#</a></li>#}#</ul>');
var aa=G.template('<div class="#=styles.popupWrapper#"><ul class="#=styles.popupList#" role="listbox">#for(var i = 0, l = actions.length; i < l; i++){#<li class="#=styles.item#" data-action="#=actions[i].data#" role="option">#=actions[i].text#</span>#}#</ul></div>');
var l=function(aj,ak){var ai={name:ak.field};
var al=ak.model.fields[ak.field].validation;
if(al&&F(al)&&al.message){ai[G.attr("dateCompare-msg")]=al.message;
}a('<input type="text" required '+G.attr("type")+'="date" '+G.attr("role")+'="datetimepicker" '+G.attr("bind")+'="value:'+ak.field+'" '+G.attr("validate")+"='true' />").attr(ai).appendTo(aj);
a("<span "+G.attr("for")+'="'+ak.field+'" class="k-invalid-msg"/>').hide().appendTo(aj);
};
var T=function(ai,aj){a('<a href="#" class="'+aj.styles.button+'">'+aj.messages.assignButton+"</a>").click(aj.click).appendTo(ai);
};
var z={wrapper:"k-widget k-gantt",rowHeight:"k-gantt-rowheight",listWrapper:"k-gantt-layout k-gantt-treelist",list:"k-gantt-treelist",timelineWrapper:"k-gantt-layout k-gantt-timeline",timeline:"k-gantt-timeline",splitBarWrapper:"k-splitbar k-state-default k-splitbar-horizontal k-splitbar-draggable-horizontal k-gantt-layout",splitBar:"k-splitbar",splitBarHover:"k-splitbar-horizontal-hover",popupWrapper:"k-list-container",popupList:"k-list k-reset",resizeHandle:"k-resize-handle",icon:"k-icon",item:"k-item",line:"k-line",buttonDelete:"k-gantt-delete",buttonCancel:"k-gantt-cancel",buttonSave:"k-gantt-update",buttonToggle:"k-gantt-toggle",primary:"k-primary",hovered:"k-state-hover",selected:"k-state-selected",focused:"k-state-focused",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",popup:{form:"k-popup-edit-form",editForm:"k-gantt-edit-form",formContainer:"k-edit-form-container",resourcesFormContainer:"k-resources-form-container",message:"k-popup-message",buttonsContainer:"k-edit-buttons k-state-default",button:"k-button",editField:"k-edit-field",editLabel:"k-edit-label",resourcesField:"k-gantt-resources"},toolbar:{headerWrapper:"k-floatwrap k-header k-gantt-toolbar",footerWrapper:"k-floatwrap k-header k-gantt-toolbar",toolbar:"k-gantt-toolbar",expanded:"k-state-expanded",views:"k-gantt-views",viewsWrapper:"k-reset k-header k-gantt-views",actions:"k-gantt-actions",button:"k-button k-button-icontext",buttonToggle:"k-button k-button-icon k-gantt-toggle",iconPlus:"k-icon k-i-plus",iconPdf:"k-icon k-i-pdf",iconToggle:"k-icon k-i-gantt-toggle",viewButtonDefault:"k-state-default",viewButton:"k-view",currentView:"k-current-view",link:"k-link",pdfButton:"k-gantt-pdf",appendButton:"k-gantt-create"}};
function V(ai){return"["+G.attr("uid")+(ai?"='"+ai+"']":"]");
}function ad(ai){delete ai.name;
delete ai.prefix;
delete ai.remove;
delete ai.edit;
delete ai.add;
delete ai.navigate;
return ai;
}function k(am){if(am.filter("[name=end], [name=start]").length){var al=am.attr("name");
var ao=G.widgetInstance(am,G.ui);
var aj={};
var ai=am;
var ak;
var an;
while(ai!==window&&!ak){ai=ai.parent();
ak=ai.data("kendoEditable");
}an=ak?ak.options.model:null;
if(!an){return true;
}aj.start=an.start;
aj.end=an.end;
aj[al]=ao?ao.value():G.parseDate(am.value());
return aj.start<=aj.end;
}return true;
}function u(am,ai){var an=am.parents("["+G.attr("role")+'="gantt"]');
var al=[];
var ak=U(an);
am.attr(Y,0);
if(ai){ak.each(function(ao,ap){al[ao]=a(ap).scrollTop();
});
}try{am[0].setActive();
}catch(aj){am[0].focus();
}if(ai){ak.each(function(ao,ap){a(ap).scrollTop(al[ao]);
});
}}function U(ai){return a(ai).parentsUntil("body").filter(function(al,ak){var aj=G.getComputedStyles(ak,["overflow"]);
return aj.overflow!="visible";
}).add(window);
}var m;
var ab=L.extend({init:function(ai,aj){L.fn.init.call(this);
this.element=ai;
this.options=t(true,{},this.options,aj);
this._popup();
},options:{direction:"down",navigatable:false},_current:function(ak){var aj=v.styles;
var ai=this.list.find(q+aj.focused);
var al=ai[ak]();
if(al.length){ai.removeClass(aj.focused).removeAttr("id");
al.addClass(aj.focused).attr("id",c);
this.list.find("ul").removeAttr(d).attr(d,c);
}},_popup:function(){var an=this;
var ak=v.styles;
var al="li"+q+ak.item;
var aj=q+ak.toolbar.appendButton;
var ai=this.options.messages.actions;
var am=this.options.navigatable;
this.list=a(aa({styles:ak,actions:[{data:"add",text:ai.addChild},{data:"insert-before",text:ai.insertBefore},{data:"insert-after",text:ai.insertAfter}]}));
this.element.append(this.list);
this.popup=new G.ui.Popup(this.list,t({anchor:this.element.find(aj),open:function(){an._adjustListWidth();
},animation:this.options.animation},p[this.options.direction]));
this.element.on(g+K,aj,function(ap){var aq=a(this);
var ao=aq.attr(G.attr("action"));
ap.preventDefault();
if(ao){an.trigger("command",{type:ao});
}else{an.popup.open();
if(am){an.list.find("li:first").addClass(ak.focused).attr("id",c).end().find("ul").attr({TABINDEX:0,"aria-activedescendant":c}).focus();
}}});
this.list.find(al).hover(function(){a(this).addClass(ak.hovered);
},function(){a(this).removeClass(ak.hovered);
}).end().on(g+K,al,function(){an.trigger("command",{type:a(this).attr(G.attr("action"))});
an.popup.close();
});
if(am){this.popup.bind("close",function(){an.list.find(al).removeClass(ak.focused).end().find("ul").attr(Y,0);
an.element.parents("["+G.attr("role")+'="gantt"]').find(q+ak.gridContent+" > table:first").focus();
});
this.list.find("ul").on("keydown"+K,function(ao){var ap=ao.keyCode;
switch(ap){case H.UP:ao.preventDefault();
an._current("prev");
break;
case H.DOWN:ao.preventDefault();
an._current("next");
break;
case H.ENTER:an.list.find(q+ak.focused).click();
break;
case H.ESC:ao.preventDefault();
an.popup.close();
break;
}});
}},_adjustListWidth:function(){var al=this.list;
var ak=v.styles;
var an=al[0].style.width;
var ao=this.element.find(q+ak.toolbar.appendButton);
var am=al.outerWidth();
var ai;
var aj;
if(!al.data(ah)&&an){return;
}ai=window.getComputedStyle?window.getComputedStyle(ao[0],null):0;
aj=ai?parseFloat(ai.width):ao.outerWidth();
if(ai&&(e.mozilla||e.msie)){aj+=parseFloat(ai.paddingLeft)+parseFloat(ai.paddingRight)+parseFloat(ai.borderLeftWidth)+parseFloat(ai.borderRightWidth);
}if(al.css("box-sizing")!=="border-box"){an=aj-(al.outerWidth()-al.width());
}else{an=aj;
}if(am>an){an=am;
}al.css({fontFamily:ao.css("font-family"),width:an}).data(ah,an);
},destroy:function(){clearTimeout(this._focusTimeout);
this.popup.destroy();
this.element.off(K);
this.list.off(K);
this.unbind();
}});
var i=function(aj,ai){return function(am){am=D(am)?{data:am}:am;
var al=am||{};
var ak=al.data;
al.data=ak;
if(!(al instanceof aj)&&al instanceof j){throw new Error("Incorrect DataSource type. Only "+ai+" instances are supported");
}return al instanceof aj?al:new aj(al);
};
};
var x=G.data.Model.define({id:"id",fields:{id:{type:"number"},predecessorId:{type:"number"},successorId:{type:"number"},type:{type:"number"}}});
var y=j.extend({init:function(ai){j.fn.init.call(this,t(true,{},{schema:{modelBase:x,model:x}},ai));
},successors:function(ai){return this._dependencies("predecessorId",ai);
},predecessors:function(ai){return this._dependencies("successorId",ai);
},dependencies:function(ai){var aj=this.predecessors(ai);
var ak=this.successors(ai);
aj.push.apply(aj,ak);
return aj;
},_dependencies:function(aj,al){var ai=this.view();
var ak={field:aj,operator:"eq",value:al};
ai=new R(ai).filter(ak).toArray();
return ai;
}});
y.create=i(y,"GanttDependencyDataSource");
var A=G.data.Model.define({duration:function(){var ai=this.end;
var aj=this.start;
return ai-aj;
},isMilestone:function(){return this.duration()===0;
},_offset:function(al){var ai=["start","end"];
var ak;
for(var aj=0;
aj<ai.length;
aj++){ak=new Date(this.get(ai[aj]).getTime()+al);
this.set(ai[aj],ak);
}},id:"id",fields:{id:{type:"number"},parentId:{type:"number",defaultValue:null,validation:{required:true}},orderId:{type:"number",validation:{required:true}},title:{type:"string",defaultValue:"New task"},start:{type:"date",validation:{required:true}},end:{type:"date",validation:{required:true,dateCompare:k,message:"End date should be after or equal to the start date"}},percentComplete:{type:"number",validation:{required:true,min:0,max:1,step:0.01}},summary:{type:"boolean"},expanded:{type:"boolean",defaultValue:true}}});
var w=j.extend({init:function(ai){j.fn.init.call(this,t(true,{},{schema:{modelBase:A,model:A}},ai));
},remove:function(ak){var aj=ak.get("parentId");
var ai=this.taskAllChildren(ak);
this._removeItems(ai);
ak=j.fn.remove.call(this,ak);
this._childRemoved(aj,ak.get("orderId"));
return ak;
},add:function(ai){if(!ai){return;
}ai=this._toGanttTask(ai);
return this.insert(this.taskSiblings(ai).length,ai);
},insert:function(ai,aj){if(!aj){return;
}aj=this._toGanttTask(aj);
aj.set("orderId",ai);
aj=j.fn.insert.call(this,ai,aj);
this._reorderSiblings(aj,this.taskSiblings(aj).length-1);
this._resolveSummaryFields(this.taskParent(aj));
return aj;
},taskChildren:function(al){var ai=this.view();
var aj={field:"parentId",operator:"eq",value:null};
var ak=this._sort||{field:"orderId",dir:"asc"};
var am;
if(!!al){am=al.get("id");
if(am===ae||am===null||am===""){return[];
}aj.value=am;
}ai=new R(ai).filter(aj).sort(ak).toArray();
return ai;
},taskAllChildren:function(ak){var aj=[];
var al=this;
var ai=function(am){var an=al.taskChildren(am);
aj.push.apply(aj,an);
I(an,ai);
};
if(!!ak){ai(ak);
}else{aj=this.view();
}return aj;
},taskSiblings:function(aj){if(!aj){return null;
}var ai=this.taskParent(aj);
return this.taskChildren(ai);
},taskParent:function(ai){if(!ai||ai.get("parentId")===null){return null;
}return this.get(ai.parentId);
},taskLevel:function(ak){var ai=0;
var aj=this.taskParent(ak);
while(aj!==null){ai+=1;
aj=this.taskParent(aj);
}return ai;
},taskTree:function(an){var ak=[];
var aj;
var ao=this.taskChildren(an);
for(var al=0,am=ao.length;
al<am;
al++){aj=ao[al];
ak.push(aj);
if(aj.get("expanded")){var ai=this.taskTree(aj);
ak.push.apply(ak,ai);
}}return ak;
},update:function(am,an){var ao=this;
var al;
var ak=function(au,at){var ap=ao.taskAllChildren(au);
for(var aq=0,ar=ap.length;
aq<ar;
aq++){ap[aq]._offset(at);
}};
var aj=function(ap){var aq=ap.field;
var ar=ap.sender;
switch(aq){case"start":ao._resolveSummaryStart(ao.taskParent(ar));
ak(ar,ar.get(aq).getTime()-al.getTime());
break;
case"end":ao._resolveSummaryEnd(ao.taskParent(ar));
break;
case"percentComplete":ao._resolveSummaryPercentComplete(ao.taskParent(ar));
break;
case"orderId":ao._reorderSiblings(ar,al);
break;
}};
if(an.parentId!==ae){al=am.get("parentId");
if(al!==an.parentId){am.set("parentId",an.parentId);
ao._childRemoved(al,am.get("orderId"));
am.set("orderId",ao.taskSiblings(am).length-1);
ao._resolveSummaryFields(ao.taskParent(am));
}delete an.parentId;
}am.bind("change",aj);
for(var ai in an){al=am.get(ai);
am.set(ai,an[ai]);
}am.unbind("change",aj);
},_resolveSummaryFields:function(ai){if(!ai){return;
}this._updateSummary(ai);
if(!this.taskChildren(ai).length){return;
}this._resolveSummaryStart(ai);
this._resolveSummaryEnd(ai);
this._resolveSummaryPercentComplete(ai);
},_resolveSummaryStart:function(aj){var ak=this;
var ai=function(aq){var al=ak.taskChildren(aq);
var ap=al[0].start.getTime();
var am;
for(var an=1,ao=al.length;
an<ao;
an++){am=al[an].start.getTime();
if(am<ap){ap=am;
}}return new Date(ap);
};
this._updateSummaryRecursive(aj,"start",ai);
},_resolveSummaryEnd:function(aj){var ak=this;
var ai=function(aq){var al=ak.taskChildren(aq);
var ap=al[0].end.getTime();
var am;
for(var an=1,ao=al.length;
an<ao;
an++){am=al[an].end.getTime();
if(am>ap){ap=am;
}}return new Date(ap);
};
this._updateSummaryRecursive(aj,"end",ai);
},_resolveSummaryPercentComplete:function(aj){var ak=this;
var ai=function(am){var al=ak.taskChildren(am);
var an=new R(al).aggregate([{field:"percentComplete",aggregate:"average"}]);
return an.percentComplete.average;
};
this._updateSummaryRecursive(aj,"percentComplete",ai);
},_updateSummaryRecursive:function(al,aj,ai){if(!al){return;
}var am=ai(al);
al.set(aj,am);
var ak=this.taskParent(al);
if(ak){this._updateSummaryRecursive(ak,aj,ai);
}},_childRemoved:function(an,ak){var am=an===null?null:this.get(an);
var ai=this.taskChildren(am);
for(var aj=ak,al=ai.length;
aj<al;
aj++){ai[aj].set("orderId",aj);
}this._resolveSummaryFields(am);
},_reorderSiblings:function(aq,am){var an=aq.get("orderId");
var ai=an>am;
var ap=ai?am:an;
var aj=ai?an:am;
var al=ai?ap:ap+1;
var ao=this.taskSiblings(aq);
aj=Math.min(aj,ao.length-1);
for(var ak=ap;
ak<=aj;
ak++){if(ao[ak]===aq){continue;
}ao[ak].set("orderId",al);
al+=1;
}},_updateSummary:function(aj){if(aj!==null){var ai=this.taskChildren(aj).length;
aj.set("summary",ai>0);
}},_toGanttTask:function(ai){if(!(ai instanceof A)){var aj=ai;
ai=this._createNewModel();
ai.accept(aj);
}return ai;
}});
w.create=i(w,"GanttDataSource");
t(true,G.data,{GanttDataSource:w,GanttTask:A,GanttDependencyDataSource:y,GanttDependency:x});
var s={desktop:{dateRange:l,resources:T}};
var r=G.Observable.extend({init:function(ai,aj){G.Observable.fn.init.call(this);
this.element=ai;
this.options=t(true,{},this.options,aj);
this.createButton=this.options.createButton;
},fields:function(aj,am){var ap=this;
var an=this.options;
var al=an.messages.editor;
var ao=an.resources;
var ak;
var ai=function(aq){aq.preventDefault();
ao.editor(ap.container.find(q+v.styles.popup.resourcesField),am);
};
if(an.editable.template){ak=a.map(am.fields,function(ar,aq){return{field:aq};
});
}else{ak=[{field:"title",title:al.title},{field:"start",title:al.start,editor:aj.dateRange},{field:"end",title:al.end,editor:aj.dateRange},{field:"percentComplete",title:al.percentComplete,format:O}];
if(am.get(ao.field)){ak.push({field:ao.field,title:al.resources,messages:al,editor:aj.resources,click:ai,styles:v.styles.popup});
}}return ak;
},_buildEditTemplate:function(ao,ak,ai){var ar=this.options.resources;
var au=this.options.editable.template;
var at=t({},G.Template,this.options.templateSettings);
var ap=at.paramName;
var aq=v.styles.popup;
var al="";
if(au){if(typeof au===W){au=window.unescape(au);
}al+=(G.template(au,at))(ao);
}else{for(var am=0,an=ak.length;
am<an;
am++){var aj=ak[am];
al+='<div class="'+aq.editLabel+'"><label for="'+aj.field+'">'+(aj.title||aj.field||"")+"</label></div>";
if(aj.field===ar.field){al+='<div class="'+aq.resourcesField+'" style="display:none"></div>';
}if((!ao.editable||ao.editable(aj.field))){ai.push(aj);
al+="<div "+G.attr("container-for")+'="'+aj.field+'" class="'+aq.editField+'"></div>';
}else{var av="#:";
if(aj.field){aj=G.expr(aj.field,ap);
av+=aj+"==null?'':"+aj;
}else{av+="''";
}av+="#";
av=G.template(av,at);
al+='<div class="'+aq.editField+'">'+av(ao)+"</div>";
}}}return al;
}});
var P=r.extend({destroy:function(){this.close();
this.unbind();
},editTask:function(ai){this.editable=this._createPopupEditor(ai);
},close:function(){var aj=this;
var ai=function(){if(aj.editable){aj.editable.destroy();
aj.editable=null;
aj.container=null;
}if(aj.popup){aj.popup.destroy();
aj.popup=null;
}};
if(this.editable&&this.container.is(":visible")){this.container.data("kendoWindow").bind("deactivate",ai).close();
}else{ai();
}},showDialog:function(am){var ai=am.buttons;
var ao=v.styles.popup;
var aj=G.format('<div class="{0}"><div class="{1}"><p class="{2}">{3}</p><div class="{4}">',ao.form,ao.formContainer,ao.message,am.text,ao.buttonsContainer);
for(var ak=0,al=ai.length;
ak<al;
ak++){aj+=this.createButton(ai[ak]);
}aj+="</div></div></div>";
var ap=this.element;
if(this.popup){this.popup.destroy();
}var an=this.popup=a(aj).appendTo(ap).eq(0).on("click",q+ao.button,function(ar){ar.preventDefault();
an.close();
var aq=a(ar.currentTarget).index();
ai[aq].click();
}).kendoWindow({modal:true,resizable:false,draggable:false,title:am.title,visible:false,close:function(){this.destroy();
ap.focus();
}}).getKendoWindow();
an.center().open();
},_createPopupEditor:function(ar){var at=this;
var ap={};
var ao=this.options.messages;
var am=v.styles;
var aq=am.popup;
var an=G.format('<div {0}="{1}" class="{2} {3}"><div class="{4}">',G.attr("uid"),ar.uid,aq.form,aq.editForm,aq.formContainer);
var al=this.fields(s.desktop,ar);
var aj=[];
an+=this._buildEditTemplate(ar,al,aj);
an+='<div class="'+aq.buttonsContainer+'">';
an+=this.createButton({name:"update",text:ao.save,className:v.styles.primary});
an+=this.createButton({name:"cancel",text:ao.cancel});
an+=this.createButton({name:"delete",text:ao.destroy});
an+="</div></div></div>";
var ai=this.container=a(an).appendTo(this.element).eq(0).kendoWindow(t({modal:true,resizable:false,draggable:true,title:ao.editor.editorTitle,visible:false,close:function(au){if(au.userTriggered){if(at.trigger("cancel",{container:ai,model:ar})){au.preventDefault();
}}}},ap));
var ak=ai.kendoEditable({fields:aj,model:ar,clearContainer:false,validateOnBlur:true,target:at.options.target}).data("kendoEditable");
G.cycleForm(ai);
if(!this.trigger("edit",{container:ai,model:ar})){ai.data("kendoWindow").center().open();
ai.on(g+K,q+am.buttonCancel,function(au){au.preventDefault();
au.stopPropagation();
at.trigger("cancel",{container:ai,model:ar});
});
ai.on(g+K,q+am.buttonSave,function(au){au.preventDefault();
au.stopPropagation();
var aw=at.fields(s.desktop,ar);
var az={};
var av;
for(var ax=0,ay=aw.length;
ax<ay;
ax++){av=aw[ax].field;
az[av]=ar.get(av);
}at.trigger("save",{container:ai,model:ar,updateInfo:az});
});
ai.on(g+K,q+am.buttonDelete,function(au){au.preventDefault();
au.stopPropagation();
at.trigger("remove",{container:ai,model:ar});
});
}else{at.trigger("cancel",{container:ai,model:ar});
}return ak;
}});
var S=ag.extend({init:function(ai,aj){ag.fn.init.call(this,ai,aj);
this.wrapper=this.element;
this.model=this.options.model;
this.resourcesField=this.options.resourcesField;
this.createButton=this.options.createButton;
this._initContainer();
this._attachHandlers();
},events:["save"],open:function(){this.window.center().open();
this.grid.resize(true);
},close:function(){this.window.bind("deactivate",Q(this.destroy,this)).close();
},destroy:function(){this._dettachHandlers();
this.grid.destroy();
this.grid=null;
this.window.destroy();
this.window=null;
ag.fn.destroy.call(this);
G.destroy(this.wrapper);
this.element=this.wrapper=null;
},_attachHandlers:function(){var aj=v.styles;
var ak=this.grid;
var ai=this._cancelProxy=Q(this._cancel,this);
this.container.on(g+K,q+aj.buttonCancel,this._cancelProxy);
this._saveProxy=Q(this._save,this);
this.container.on(g+K,q+aj.buttonSave,this._saveProxy);
this.window.bind("close",function(al){if(al.userTriggered){ai(al);
}});
ak.wrapper.on(g+K,"input[type='checkbox']",function(){var al=a(this);
var an=a(al).closest("tr");
var am=ak.dataSource.getByUid(an.attr(G.attr("uid")));
var ao=a(al).is(":checked")?1:"";
am.set("value",ao);
});
},_dettachHandlers:function(){this._cancelProxy=null;
this._saveProxy=null;
this.container.off(K);
this.grid.wrapper.off();
},_cancel:function(ai){ai.preventDefault();
this.close();
},_save:function(ai){ai.preventDefault();
this._updateModel();
if(!this.wrapper.is(q+v.styles.popup.resourcesField)){this.trigger("save",{container:this.wrapper,model:this.model});
}this.close();
},_initContainer:function(){var aj=v.styles.popup;
var ai=G.format('<div class="{0} {1}"><div class="{2} {3}"/></div>"',aj.form,aj.editForm,aj.formContainer,aj.resourcesFormContainer);
ai=a(ai);
this.container=ai.find(q+aj.resourcesFormContainer);
this.window=ai.kendoWindow({modal:true,resizable:false,draggable:true,visible:false,title:this.options.messages.resourcesEditorTitle}).data("kendoWindow");
this._resourceGrid();
this._createButtons();
},_resourceGrid:function(){var ak=this;
var aj=this.options.messages;
var ai=a('<div id="resources-grid"/>').appendTo(this.container);
this.grid=new G.ui.Grid(ai,{columns:[{field:"name",title:aj.resourcesHeader,template:"<label><input type='checkbox' value='#=name#'# if (value > 0 && value !== null) {#checked='checked'# } #/>#=name#</labe>"},{field:"value",title:aj.unitsHeader,template:function(al){var an=al.format;
var am=al.value!==null?al.value:"";
return an?G.toString(am,an):am;
}}],height:280,sortable:true,editable:true,filterable:true,dataSource:{data:ak.options.data,schema:{model:{id:"id",fields:{id:{from:"id"},name:{from:"name",type:"string",editable:false},value:{from:"value",type:"number",defaultValue:""},format:{from:"format",type:"string"}}}}},save:function(al){var am=!!al.values.value;
al.container.parent().find("input[type='checkbox']").prop("checked",am);
}});
},_createButtons:function(){var ai=this.options.buttons;
var aj='<div class="'+v.styles.popup.buttonsContainer+'">';
for(var ak=0,al=ai.length;
ak<al;
ak++){aj+=this.createButton(ai[ak]);
}aj+="</div>";
this.container.append(aj);
},_updateModel:function(){var al=[];
var am;
var ai=this.grid.dataSource.data();
for(var aj=0,ak=ai.length;
aj<ak;
aj++){am=ai[aj].get("value");
if(am!==null&&am>0){al.push(ai[aj]);
}}this.model[this.resourcesField]=al;
}});
var v=ag.extend({init:function(ai,aj){if(D(aj)){aj={dataSource:aj};
}m={append:{text:"Add Task",action:"add",className:v.styles.toolbar.appendButton,iconClass:v.styles.toolbar.iconPlus},pdf:{text:"Export to PDF",className:v.styles.toolbar.pdfButton,iconClass:v.styles.toolbar.iconPdf}};
ag.fn.init.call(this,ai,aj);
this._wrapper();
this._resources();
this._timeline();
this._toolbar();
this._footer();
this._adjustDimensions();
this._preventRefresh=true;
this.view(this.timeline._selectedViewName);
this._preventRefresh=false;
this._dataSource();
this._assignments();
this._dropDowns();
this._list();
this._dependencies();
this._resizable();
this._scrollable();
this._dataBind();
this._attachEvents();
this._createEditor();
G.notify(this);
},events:["dataBinding","dataBound","add","edit","remove","cancel","save","change","navigate","moveStart","move","moveEnd","resizeStart","resize","resizeEnd","columnResize"],options:{name:"Gantt",autoBind:true,navigatable:false,selectable:true,editable:true,resizable:false,columnResizeHandleWidth:n,columns:[],views:[],dataSource:{},dependencies:{},resources:{},assignments:{},taskTemplate:null,messages:{save:"Save",cancel:"Cancel",destroy:"Delete",deleteTaskConfirmation:Z,deleteDependencyConfirmation:o,deleteTaskWindowTitle:"Delete task",deleteDependencyWindowTitle:"Delete dependency",views:{day:"Day",week:"Week",month:"Month",year:"Year",start:"Start",end:"End"},actions:{append:"Add Task",addChild:"Add Child",insertBefore:"Add Above",insertAfter:"Add Below",pdf:"Export to PDF"},editor:{editorTitle:"Task",resourcesEditorTitle:"Resources",title:"Title",start:"Start",end:"End",percentComplete:"Complete",resources:"Resources",assignButton:"Assign",resourcesHeader:"Resources",unitsHeader:"Units"}},showWorkHours:true,showWorkDays:true,toolbar:null,workDayStart:new Date(1980,1,1,8,0,0),workDayEnd:new Date(1980,1,1,17,0,0),workWeekStart:1,workWeekEnd:5,hourSpan:1,snap:true,height:600,listWidth:"30%",rowHeight:null},select:function(aj){var ai=this.list;
if(!aj){return ai.select();
}ai.select(aj);
return;
},clearSelection:function(){this.list.clearSelection();
},destroy:function(){ag.fn.destroy.call(this);
if(this.dataSource){this.dataSource.unbind("change",this._refreshHandler);
this.dataSource.unbind("progress",this._progressHandler);
this.dataSource.unbind("error",this._errorHandler);
}if(this.dependencies){this.dependencies.unbind("change",this._dependencyRefreshHandler);
this.dependencies.unbind("error",this._dependencyErrorHandler);
}if(this.timeline){this.timeline.unbind();
this.timeline.destroy();
}if(this.list){this.list.unbind();
this.list.destroy();
}if(this.footerDropDown){this.footerDropDown.destroy();
}if(this.headerDropDown){this.headerDropDown.destroy();
}if(this._editor){this._editor.destroy();
}if(this._resizeDraggable){this._resizeDraggable.destroy();
}this.toolbar.off(K);
if(X){this._mediaQuery.removeListener(this._mediaQueryHandler);
this._mediaQuery=null;
}a(window).off("resize"+K,this._resizeHandler);
a(this.wrapper).off(K);
this.toolbar=null;
this.footer=null;
},_attachEvents:function(){this._resizeHandler=Q(this.resize,this,false);
a(window).on("resize"+K,this._resizeHandler);
},_wrapper:function(){var ai=v.styles;
var al=[ai.icon,ai.resizeHandle].join(" ");
var ak=this.options;
var aj=ak.height;
var am=ak.width;
this.wrapper=this.element.addClass(ai.wrapper).append("<div class='"+ai.listWrapper+"'><div></div></div>").append("<div class='"+ai.splitBarWrapper+"'><div class='"+al+"'></div></div>").append("<div class='"+ai.timelineWrapper+"'><div></div></div>");
this.wrapper.find(q+ai.list).width(ak.listWidth);
if(aj){this.wrapper.height(aj);
}if(am){this.wrapper.width(am);
}if(ak.rowHeight){this.wrapper.addClass(ai.rowHeight);
}},_toolbar:function(){var ap=this;
var al=v.styles;
var ax=q+al.toolbar.views+" > li";
var ao=q+al.toolbar.pdfButton;
var at=q+al.buttonToggle;
var ak=q+al.gridContent;
var av=a(q+al.list);
var aq=a(q+al.timeline);
var an=al.hovered;
var ai=this.options.toolbar;
var aj=a("<div class='"+al.toolbar.actions+"'>");
var au;
var aw;
var ar;
var am=function(ay){if(ay.matches){av.css({display:"none","max-width":0});
}else{av.css({display:"inline-block",width:"30%","max-width":"none"});
aq.css("display","inline-block");
ap.refresh();
aq.find(ak).scrollTop(ap.scrollTop);
}ap._resize();
};
if(!E(ai)){ai=(typeof ai===W?ai:this._actions(ai));
ai=Q(G.template(ai),this);
}ar=a(ac({styles:al.toolbar}));
aw=a(B({ns:G.ns,views:this.timeline.views,styles:al.toolbar}));
aj.append(ai({}));
au=a("<div class='"+al.toolbar.headerWrapper+"'>").append(ar).append(aw).append(aj);
if(aw.find("li").length>1){aw.prepend(af({styles:al.toolbar}));
}this.wrapper.prepend(au);
this.toolbar=au;
if(X){this._mediaQueryHandler=Q(am,this);
this._mediaQuery=window.matchMedia("(max-width: 480px)");
this._mediaQuery.addListener(this._mediaQueryHandler);
}au.on(g+K,ax,function(az){az.preventDefault();
var aA=ap.list;
var aB=a(this).attr(G.attr("name"));
var ay=aw.find(q+al.toolbar.currentView);
if(ay.is(":visible")){ay.parent().toggleClass(al.toolbar.expanded);
}if(aA.editable&&aA.editable.trigger("validate")){return;
}if(!ap.trigger("navigate",{view:aB})){ap.view(aB);
}}).on(g+K,ao,function(ay){ay.preventDefault();
ap.saveAsPDF();
}).on(g+K,at,function(ay){ay.preventDefault();
if(av.is(":visible")){av.css({display:"none",width:"0"});
aq.css({display:"inline-block",width:"100%"});
ap.refresh();
aq.find(ak).scrollTop(ap.scrollTop);
}else{aq.css({display:"none",width:0});
av.css({display:"inline-block",width:"100%","max-width":"none"}).find(ak).scrollTop(ap.scrollTop);
}ap._resize();
});
this.wrapper.find(q+al.toolbar.toolbar+" li").hover(function(){a(this).addClass(an);
},function(){a(this).removeClass(an);
});
},_actions:function(){var am=this.options;
var ai=am.toolbar;
var aj="";
if(!D(ai)){if(am.editable){ai=["append"];
}else{return aj;
}}for(var ak=0,al=ai.length;
ak<al;
ak++){aj+=this._createButton(ai[ak]);
}return aj;
},_footer:function(){if(!this.options.editable){return;
}var al=v.styles.toolbar;
var am=this.options.messages.actions;
var aj=a(G.template(f)(t(true,{styles:al},m.append,{text:am.append})));
var ai=a("<div class='"+al.actions+"'>").append(aj);
var ak=a("<div class='"+al.footerWrapper+"'>").append(ai);
this.wrapper.append(ak);
this.footer=ak;
},_createButton:function(aj){var an=aj.template||f;
var al=this.options.messages.actions;
var ak=typeof aj===W?aj:aj.name||aj.text;
var ai=m[ak]?m[ak].className:"k-gantt-"+(ak||"").replace(/\s/g,"");
var am={iconClass:"",action:"",text:ak,className:ai,styles:v.styles.toolbar};
if(!ak&&!(F(aj)&&aj.template)){throw new Error("Custom commands should have name specified");
}am=t(true,am,m[ak],{text:al[ak]});
if(F(aj)){if(aj.className&&C(am.className,aj.className.split(" "))<0){aj.className+=" "+am.className;
}am=t(true,am,aj);
}return G.template(an)(am);
},_adjustDimensions:function(){var ai=this.element;
var ak=v.styles;
var al=q+ak.list;
var ao=q+ak.timeline;
var am=q+ak.splitBar;
var ap=this.toolbar.outerHeight();
var aj=this.footer?this.footer.outerHeight():0;
var aq=ai.height();
var ar=ai.width();
var an=ai.find(am).outerWidth();
var at=ai.find(al).outerWidth();
ai.children([al,ao,am].join(",")).height(aq-(ap+aj)).end().children(ao).width(ar-(an+at));
if(ar<(at+an)){ai.find(al).width(ar-an);
}},_scrollTo:function(ao){var ap=this.timeline.view();
var al=this.list;
var aj=G.attr("uid");
var ak=typeof ao==="string"?ao:ao.closest("tr"+V()).attr(aj);
var ai;
var an;
var am=function(){if(an.length!==0){ai();
}};
if(ap.content.is(":visible")){an=ap.content.find(V(ak));
ai=function(){ap._scrollTo(an);
};
}else{an=al.content.find(V(ak));
ai=function(){an.get(0).scrollIntoView();
};
}am();
},_dropDowns:function(){var al=this;
var aj=q+v.styles.toolbar.actions;
var ai=this.options.messages.actions;
var am=this.timeline;
var ak=function(ao){var ax=ao.type;
var ar;
var an=al.dataSource;
var aw=an._createNewModel();
var au=al.dataItem(al.select());
var at=an.taskParent(au);
var aq=am.view()._timeSlots()[0];
var av=ax==="add"?au:at;
var ap=al.list.editable;
if(ap&&ap.trigger("validate")){return;
}aw.set("title","New task");
if(av){aw.set("parentId",av.get("id"));
aw.set("start",av.get("start"));
aw.set("end",av.get("end"));
}else{aw.set("start",aq.start);
aw.set("end",aq.end);
}if(ax!=="add"){ar=au.get("orderId");
ar=ax==="insert-before"?ar:ar+1;
}al._createTask(aw,ar);
};
if(!this.options.editable){return;
}this.footerDropDown=new ab(this.footer.children(aj).eq(0),{messages:{actions:ai},direction:"up",animation:{open:{effects:"slideIn:up"}},navigatable:al.options.navigatable});
this.headerDropDown=new ab(this.toolbar.children(aj).eq(0),{messages:{actions:ai},navigatable:al.options.navigatable});
this.footerDropDown.bind("command",ak);
this.headerDropDown.bind("command",ak);
},_list:function(){var ar=this;
var ao=ar.options.navigatable;
var al=v.styles;
var an=this.wrapper.find(q+al.list);
var ak=an.find("> div");
var at=this.wrapper.find(q+al.toolbar.actions+" > button");
var ap={columns:this.options.columns||[],dataSource:this.dataSource,selectable:this.options.selectable,editable:this.options.editable,resizable:this.options.resizable,columnResizeHandleWidth:this.options.columnResizeHandleWidth,listWidth:an.outerWidth(),resourcesField:this.resources.field,rowHeight:this.options.rowHeight};
var aj=ap.columns;
var ai;
var aq=function(){if(ao){ar._current(ar._cachedCurrent);
u(ar.list.content.find("table"),true);
}delete ar._cachedCurrent;
};
for(var am=0;
am<aj.length;
am++){ai=aj[am];
if(ai.field===this.resources.field&&typeof ai.editor!=="function"){ai.editor=Q(this._createResourceEditor,this);
}}this.list=new G.ui.GanttList(ak,ap);
this.list.bind("render",function(){ar._navigatable();
},true).bind("edit",function(au){ar._cachedCurrent=au.cell;
if(ar.trigger("edit",{task:au.model,container:au.cell})){au.preventDefault();
}}).bind("cancel",function(au){if(ar.trigger("cancel",{task:au.model,container:au.cell})){au.preventDefault();
}aq();
}).bind("update",function(au){ar._updateTask(au.task,au.updateInfo);
aq();
}).bind("change",function(){ar.trigger("change");
var au=ar.list.select();
if(au.length){at.removeAttr("data-action","add");
ar.timeline.select("[data-uid='"+au.attr("data-uid")+"']");
}else{at.attr("data-action","add");
ar.timeline.clearSelection();
}}).bind("columnResize",function(au){ar.trigger("columnResize",{column:au.column,oldWidth:au.oldWidth,newWidth:au.newWidth});
});
},_timeline:function(){var am=this;
var ak=v.styles;
var al=ad(t(true,{resourcesField:this.resources.field},this.options));
var aj=this.wrapper.find(q+ak.timeline+" > div");
var ai=q+ak.toolbar.currentView+" > "+q+ak.toolbar.link;
this.timeline=new G.ui.GanttTimeline(aj,al);
this.timeline.bind("navigate",function(an){var ap=an.view.replace(/\./g,"\\.").toLowerCase();
var ao=am.toolbar.find(q+ak.toolbar.views+" > li").removeClass(ak.selected).end().find(q+ak.toolbar.viewButton+"-"+ap).addClass(ak.selected).find(q+ak.toolbar.link).text();
am.toolbar.find(ai).text(ao);
am.refresh();
}).bind("moveStart",function(an){var ao=am.list.editable;
if(ao&&ao.trigger("validate")){an.preventDefault();
return;
}if(am.trigger("moveStart",{task:an.task})){an.preventDefault();
}}).bind("move",function(an){var aq=an.task;
var ap=an.start;
var ao=new Date(ap.getTime()+aq.duration());
if(am.trigger("move",{task:aq,start:ap,end:ao})){an.preventDefault();
}}).bind("moveEnd",function(an){var aq=an.task;
var ap=an.start;
var ao=new Date(ap.getTime()+aq.duration());
if(!am.trigger("moveEnd",{task:aq,start:ap,end:ao})){am._updateTask(am.dataSource.getByUid(aq.uid),{start:ap,end:ao});
}}).bind("resizeStart",function(an){var ao=am.list.editable;
if(ao&&ao.trigger("validate")){an.preventDefault();
return;
}if(am.trigger("resizeStart",{task:an.task})){an.preventDefault();
}}).bind("resize",function(an){if(am.trigger("resize",{task:an.task,start:an.start,end:an.end})){an.preventDefault();
}}).bind("resizeEnd",function(an){var ao=an.task;
var ap={};
if(an.resizeStart){ap.start=an.start;
}else{ap.end=an.end;
}if(!am.trigger("resizeEnd",{task:ao,start:an.start,end:an.end})){am._updateTask(am.dataSource.getByUid(ao.uid),ap);
}}).bind("percentResizeStart",function(an){var ao=am.list.editable;
if(ao&&ao.trigger("validate")){an.preventDefault();
}}).bind("percentResizeEnd",function(an){am._updateTask(am.dataSource.getByUid(an.task.uid),{percentComplete:an.percentComplete});
}).bind("dependencyDragStart",function(an){var ao=am.list.editable;
if(ao&&ao.trigger("validate")){an.preventDefault();
}}).bind("dependencyDragEnd",function(ao){var an=am.dependencies._createNewModel({type:ao.type,predecessorId:ao.predecessor.id,successorId:ao.successor.id});
am._createDependency(an);
}).bind("select",function(an){var ao=am.list.editable;
if(ao){ao.trigger("validate");
}am.select("[data-uid='"+an.uid+"']");
}).bind("editTask",function(an){var ao=am.list.editable;
if(ao&&ao.trigger("validate")){return;
}am.editTask(an.uid);
}).bind("clear",function(){am.clearSelection();
}).bind("removeTask",function(an){var ao=am.list.editable;
if(ao&&ao.trigger("validate")){return;
}am.removeTask(am.dataSource.getByUid(an.uid));
}).bind("removeDependency",function(an){var ao=am.list.editable;
if(ao&&ao.trigger("validate")){return;
}am.removeDependency(am.dependencies.getByUid(an.uid));
});
},_dataSource:function(){var aj=this.options;
var ai=aj.dataSource;
ai=D(ai)?{data:ai}:ai;
if(this.dataSource&&this._refreshHandler){this.dataSource.unbind("change",this._refreshHandler).unbind("progress",this._progressHandler).unbind("error",this._errorHandler);
}else{this._refreshHandler=Q(this.refresh,this);
this._progressHandler=Q(this._requestStart,this);
this._errorHandler=Q(this._error,this);
}this.dataSource=G.data.GanttDataSource.create(ai).bind("change",this._refreshHandler).bind("progress",this._progressHandler).bind("error",this._errorHandler);
},_dependencies:function(){var aj=this.options.dependencies||{};
var ai=D(aj)?{data:aj}:aj;
if(this.dependencies&&this._dependencyRefreshHandler){this.dependencies.unbind("change",this._dependencyRefreshHandler).unbind("error",this._dependencyErrorHandler);
}else{this._dependencyRefreshHandler=Q(this.refreshDependencies,this);
this._dependencyErrorHandler=Q(this._error,this);
}this.dependencies=G.data.GanttDependencyDataSource.create(ai).bind("change",this._dependencyRefreshHandler).bind("error",this._dependencyErrorHandler);
},_resources:function(){var aj=this.options.resources;
var ai=aj.dataSource||{};
this.resources={field:"resources",dataTextField:"name",dataColorField:"color",dataFormatField:"format"};
t(this.resources,aj);
this.resources.dataSource=G.data.DataSource.create(ai);
},_assignments:function(){var ai=this.options.assignments;
var aj=ai.dataSource||{};
if(this.assignments){this.assignments.dataSource.unbind("change",this._assignmentsRefreshHandler);
}else{this._assignmentsRefreshHandler=Q(this.refresh,this);
}this.assignments={dataTaskIdField:"taskId",dataResourceIdField:"resourceId",dataValueField:"value"};
t(this.assignments,ai);
this.assignments.dataSource=G.data.DataSource.create(aj);
this.assignments.dataSource.bind("change",this._assignmentsRefreshHandler);
},_createEditor:function(){var aj=this;
var ai=this._editor=new P(this.wrapper,t({},this.options,{target:this,resources:{field:this.resources.field,editor:Q(this._createResourceEditor,this)},createButton:Q(this._createPopupButton,this)}));
ai.bind("cancel",function(ak){var al=aj.dataSource.getByUid(ak.model.uid);
if(aj.trigger("cancel",{container:ak.container,task:al})){ak.preventDefault();
return;
}aj.cancelTask();
}).bind("edit",function(ak){var al=aj.dataSource.getByUid(ak.model.uid);
if(aj.trigger("edit",{container:ak.container,task:al})){ak.preventDefault();
}}).bind("save",function(ak){var al=aj.dataSource.getByUid(ak.model.uid);
aj.saveTask(al,ak.updateInfo);
}).bind("remove",function(ak){aj.removeTask(ak.model.uid);
});
},_createResourceEditor:function(ai,an){var ap=this;
var am=an instanceof N?an:an.model;
var ak=am.get("id");
var al=this.options.messages;
var ao=ap.resources.field;
var aj=this._resourceEditor=new S(ai,{resourcesField:ao,data:this._wrapResourceData(ak),model:am,messages:t({},al.editor),buttons:[{name:"update",text:al.save,className:v.styles.primary},{name:"cancel",text:al.cancel}],createButton:Q(this._createPopupButton,this),save:function(aq){ap._updateAssignments(aq.model.get("id"),aq.model.get(ao));
}});
aj.open();
},_createPopupButton:function(ai){var aj=ai.name||ai.text;
var ak={className:v.styles.popup.button+" k-gantt-"+(aj||"").replace(/\s/g,""),text:aj,attr:""};
if(!aj&&!(F(ai)&&ai.template)){throw new Error("Custom commands should have name specified");
}if(F(ai)){if(ai.className){ai.className+=" "+ak.className;
}ak=t(true,ak,ai);
}return G.template(h)(ak);
},view:function(ai){return this.timeline.view(ai);
},dataItem:function(ak){if(!ak){return null;
}var aj=this.list;
var ai=aj.content.find(ak);
return aj._modelFromElement(ai);
},setDataSource:function(ai){this.options.dataSource=ai;
this._dataSource();
this.list._setDataSource(this.dataSource);
if(this.options.autoBind){ai.fetch();
}},setDependenciesDataSource:function(ai){this.options.dependencies=ai;
this._dependencies();
if(this.options.autoBind){ai.fetch();
}},items:function(){return this.wrapper.children(".k-task");
},_updateAssignments:function(an,au){var ak=this.assignments.dataSource;
var av=this.assignments.dataTaskIdField;
var at=this.assignments.dataResourceIdField;
var al=false;
var aj=new R(ak.view()).filter({field:av,operator:"eq",value:an}).toArray();
var ai;
var ar;
var aw;
while(aj.length){ai=aj[0];
for(var am=0,ap=au.length;
am<ap;
am++){ar=au[am];
if(ai.get(at)===ar.get("id")){aw=au[am].get("value");
this._updateAssignment(ai,aw);
au.splice(am,1);
al=true;
break;
}}if(!al){this._removeAssignment(ai);
}al=false;
aj.shift();
}for(var ao=0,aq=au.length;
ao<aq;
ao++){ar=au[ao];
this._createAssignment(ar,an);
}ak.sync();
},cancelTask:function(){var aj=this._editor;
var ai=aj.container;
if(ai){aj.close();
}},editTask:function(ak){var ai=typeof ak==="string"?this.dataSource.getByUid(ak):ak;
if(!ai){return;
}var aj=this.dataSource._createNewModel(ai.toJSON());
aj.uid=ai.uid;
this.cancelTask();
this._editTask(aj);
},_editTask:function(ai){this._editor.editTask(ai);
},saveTask:function(al,am){var ak=this._editor;
var ai=ak.container;
var aj=ak.editable;
if(ai&&aj&&aj.end()){this._updateTask(al,am);
}},_updateTask:function(aj,ak){var ai=this.resources.field;
if(!this.trigger("save",{task:aj,values:ak})){this._preventRefresh=true;
this.dataSource.update(aj,ak);
if(ak[ai]){this._updateAssignments(aj.get("id"),ak[ai]);
}this._syncDataSource();
}},_updateAssignment:function(ai,ak){var aj=this.assignments.dataValueField;
ai.set(aj,ak);
},removeTask:function(ak){var aj=this;
var ai=typeof ak==="string"?this.dataSource.getByUid(ak):ak;
if(!ai){return;
}this._taskConfirm(function(al){if(!al){aj._removeTask(ai);
}},ai);
},_createTask:function(ak,aj){if(!this.trigger("add",{task:ak,dependency:null})){var ai=this.dataSource;
this._preventRefresh=true;
if(aj===ae){ai.add(ak);
}else{ai.insert(aj,ak);
}this._scrollToUid=ak.uid;
this._syncDataSource();
}},_createDependency:function(ai){if(!this.trigger("add",{task:null,dependency:ai})){this._preventDependencyRefresh=true;
this.dependencies.add(ai);
this._preventDependencyRefresh=false;
this.dependencies.sync();
}},_createAssignment:function(am,al){var aj=this.assignments;
var ak=aj.dataSource;
var ap=aj.dataTaskIdField;
var an=aj.dataResourceIdField;
var ao=aj.dataValueField;
var ai=ak._createNewModel();
ai[ap]=al;
ai[an]=am.get("id");
ai[ao]=am.get("value");
ak.add(ai);
},removeDependency:function(ak){var aj=this;
var ai=typeof ak==="string"?this.dependencies.getByUid(ak):ak;
if(!ai){return;
}this._dependencyConfirm(function(al){if(!al){aj._removeDependency(ai);
}},ai);
},_removeTaskDependencies:function(al,ai){this._preventDependencyRefresh=true;
for(var aj=0,ak=ai.length;
aj<ak;
aj++){this.dependencies.remove(ai[aj]);
}this._preventDependencyRefresh=false;
this.dependencies.sync();
},_removeTaskAssignments:function(an){var aj=this.assignments.dataSource;
var ai=aj.view();
var ak={field:this.assignments.dataTaskIdField,operator:"eq",value:an.get("id")};
ai=new R(ai).filter(ak).toArray();
this._preventRefresh=true;
for(var al=0,am=ai.length;
al<am;
al++){aj.remove(ai[al]);
}this._preventRefresh=false;
aj.sync();
},_removeTask:function(aj){var ai=this.dependencies.dependencies(aj.id);
if(!this.trigger("remove",{task:aj,dependencies:ai})){this._removeTaskDependencies(aj,ai);
this._removeTaskAssignments(aj);
this._preventRefresh=true;
if(this.dataSource.remove(aj)){this._syncDataSource();
}this._preventRefresh=false;
}},_removeDependency:function(ai){if(!this.trigger("remove",{task:null,dependencies:[ai]})){if(this.dependencies.remove(ai)){this.dependencies.sync();
}}},_removeAssignment:function(ai){this.assignments.dataSource.remove(ai);
},_taskConfirm:function(ai,ak){var aj=this.options.messages;
this._confirm(ai,{model:ak,text:aj.deleteTaskConfirmation,title:aj.deleteTaskWindowTitle});
},_dependencyConfirm:function(ai,aj){var ak=this.options.messages;
this._confirm(ai,{model:aj,text:ak.deleteDependencyConfirmation,title:ak.deleteDependencyWindowTitle});
},_confirm:function(aj,am){var ak=this.options.editable;
var al;
var ai;
if(ak===true||ak.confirmation!==false){al=this.options.messages;
ai=[{name:"delete",text:al.destroy,className:v.styles.primary,click:function(){aj();
}},{name:"cancel",text:al.cancel,click:function(){aj(true);
}}];
this.showDialog(t(true,{},am,{buttons:ai}));
}else{aj();
}},showDialog:function(ai){this._editor.showDialog(ai);
},refresh:function(){if(this._preventRefresh||this.list.editable){return;
}this._progress(false);
var al=this.dataSource;
var an=al.taskTree();
var am=this._scrollToUid;
var ak;
var aj;
var ai=-1;
if(this.current){aj=this.current.closest("tr").attr(G.attr("uid"));
ai=this.current.index();
}if(this.trigger("dataBinding")){return;
}if(this.resources.dataSource.data().length!==0){this._assignResources(an);
}if(this._editor){this._editor.close();
}this.clearSelection();
this.list._render(an);
this.timeline._render(an);
this.timeline._renderDependencies(this.dependencies.view());
if(am){this._scrollTo(am);
this.select(V(am));
}if((am||aj)&&ai>=0){ak=this.list.content.find("tr"+V((am||aj))+" > td:eq("+ai+")");
this._current(ak);
}this._scrollToUid=null;
this.trigger("dataBound");
},refreshDependencies:function(){if(this._preventDependencyRefresh){return;
}if(this.trigger("dataBinding")){return;
}this.timeline._renderDependencies(this.dependencies.view());
this.trigger("dataBound");
},_assignResources:function(ap){var ao=this.resources;
var ak=this.assignments;
var al=function(){var ar=ak.dataSource.view();
var at={field:ak.dataTaskIdField};
ar=new R(ar).group(at).toArray();
return ar;
};
var aj=al();
var ai=function(av,ar){var aw=av.get("id");
G.setter(ao.field)(av,new M([]));
for(var at=0,au=aj.length;
at<au;
at++){if(aj[at].value===aw){ar(av,aj[at].items);
}}};
var aq=function(aA,au){for(var av=0,aw=au.length;
av<aw;
av++){var at=au[av];
var ax=ao.dataSource.get(at.get(ak.dataResourceIdField));
var az=at.get(ak.dataValueField);
var ay=at.get(ak.dataResourceIdField);
var aB=ax.get(ao.dataFormatField)||O;
var ar=G.toString(az,aB);
aA[ao.field].push(new N({id:ay,name:ax.get(ao.dataTextField),color:ax.get(ao.dataColorField),value:az,formatedValue:ar}));
}};
for(var am=0,an=ap.length;
am<an;
am++){ai(ap[am],aq);
}},_wrapResourceData:function(ak){var aq=this;
var ao=[];
var am;
var an=this.resources.dataSource.view();
var ai=this.assignments.dataSource.view();
var ap=new R(ai).filter({field:aq.assignments.dataTaskIdField,operator:"eq",value:ak}).toArray();
var ar=function(at){var au=null;
new R(ap).filter({field:aq.assignments.dataResourceIdField,operator:"eq",value:at}).select(function(av){au+=av.get(aq.assignments.dataValueField);
});
return au;
};
for(var aj=0,al=an.length;
aj<al;
aj++){am=an[aj];
ao.push({id:am.get("id"),name:am.get(aq.resources.dataTextField),format:am.get(aq.resources.dataFormatField)||O,value:ar(am.id)});
}return ao;
},_syncDataSource:function(){this._preventRefresh=false;
this._requestStart();
this.dataSource.sync();
},_requestStart:function(){this._progress(true);
},_error:function(){this._progress(false);
},_progress:function(ai){G.ui.progress(this.element,ai);
},_resizable:function(){var ak=this;
var aq=this.wrapper;
var aj=v.styles;
var ai=q+aj.gridContent;
var ap=aq.find(q+aj.list);
var an=aq.find(q+aj.timeline);
var ao;
var am;
var al;
this._resizeDraggable=aq.find(q+aj.splitBar).height(ap.height()).hover(function(){a(this).addClass(aj.splitBarHover);
},function(){a(this).removeClass(aj.splitBarHover);
}).end().kendoResizable({orientation:"horizontal",handle:q+aj.splitBar,start:function(){ao=ap.width();
am=an.width();
al=an.find(ai).scrollLeft();
},resize:function(at){var ar=at.x.initialDelta;
if(G.support.isRtl(aq)){ar*=-1;
}if(ao+ar<0||am-ar<0){return;
}ap.width(ao+ar);
an.width(am-ar);
an.find(ai).scrollLeft(al+ar);
ak.timeline.view()._renderCurrentTime();
}}).data("kendoResizable");
},_scrollable:function(){var al=this;
var aj=v.styles;
var ai=q+aj.gridContent;
var ak=q+aj.gridHeaderWrap;
var an=this.timeline.element.find(ak);
var am=this.timeline.element.find(ai);
var ap=this.list.element.find(ak);
var ao=this.list.element.find(ai);
if(J){ao.css("overflow-y","auto");
}am.on("scroll",function(){al.scrollTop=this.scrollTop;
an.scrollLeft(this.scrollLeft);
ao.scrollTop(this.scrollTop);
});
ao.on("scroll",function(){al.scrollTop=this.scrollTop;
ap.scrollLeft(this.scrollLeft);
am.scrollTop(this.scrollTop);
}).on("DOMMouseScroll"+K+" mousewheel"+K,function(ar){var at=am.scrollTop();
var aq=G.wheelDeltaY(ar);
if(aq){ar.preventDefault();
a(ar.currentTarget).one("wheel"+K,false);
am.scrollTop(at+(-aq));
}});
},_navigatable:function(){var ax=this;
var au=this.options.navigatable;
var am=this.options.editable;
var ap=this.list.header.find("table");
var ak=this.list.content.find("table");
var ao=v.styles;
var aq=G.support.isRtl(this.wrapper);
var ay=this.timeline.element.find(q+ao.gridContent);
var aw=ap.add(ak);
var ai=V();
var aj;
var an={collapse:false,expand:true};
var av=function(aA){var aB=ax.timeline.view()._timeSlots()[0].offsetWidth;
ay.scrollLeft(ay.scrollLeft()+(aA?-aB:aB));
};
var at=function(aB){var aC=ax.current.parent("tr"+V());
var aA=ax.current.index();
var aD=aC[aB]();
if(ax.select().length!==0){ax.clearSelection();
}if(aD.length!==0){ax._current(aD.children("td:eq("+aA+")"));
ax._scrollTo(ax.current);
}else{if(ax.current.is("td")&&aB=="prev"){u(ap);
}else{if(ax.current.is("th")&&aB=="next"){u(ak);
}}}};
var ar=function(aA){var aB=ax.current[aA]();
if(aB.length!==0){ax._current(aB);
aj=ax.current.index();
}};
var az=function(aB){var aA=ax.dataItem(ax.current);
if(aA.summary&&aA.expanded!==aB){aA.set("expanded",aB);
}};
var al=function(){if(!ax.options.editable||ax.list.editable){return;
}var aA=ax.select();
var aB=G.attr("uid");
if(aA.length){ax.removeTask(aA.attr(aB));
}};
a(this.wrapper).on("mousedown"+K,"tr"+ai+", div"+ai+":not("+q+ao.line+")",function(aC){var aB=a(aC.currentTarget);
var aD=a(aC.target).is(":button,a,:input,a>.k-icon,textarea,span.k-icon,span.k-link,.k-input,.k-multiselect-wrap");
var aA;
if(aC.ctrlKey){return;
}if(au){if(aB.is("tr")){aA=a(aC.target).closest("td");
}else{aA=ax.list.content.find("tr"+V(aB.attr(G.attr("uid")))+" > td:first");
}ax._current(aA);
}if((au||am)&&!aD){ax._focusTimeout=setTimeout(function(){u(ax.list.content.find("table"),true);
},2);
}});
if(au!==true){ak.on("keydown"+K,function(aA){if(aA.keyCode==H.DELETE){al();
}});
return;
}aw.on("focus"+K,function(){var aC=this===ak.get(0)?"td":"th";
var aB=ax.select();
var aA=ax.current||a((aB.length?aB:this)).find(aC+":eq("+(aj||0)+")");
ax._current(aA);
}).on("blur"+K,function(){ax._current();
if(this==ap){a(this).attr(Y,-1);
}}).on("keydown"+K,function(aA){var aC=aA.keyCode;
var aB;
if(!ax.current){return;
}aB=ax.current.is("td");
switch(aC){case H.RIGHT:aA.preventDefault();
if(aA.altKey){av();
}else{if(aA.ctrlKey){az(aq?an.collapse:an.expand);
}else{ar(aq?"prev":"next");
}}break;
case H.LEFT:aA.preventDefault();
if(aA.altKey){av(true);
}else{if(aA.ctrlKey){az(aq?an.expand:an.collapse);
}else{ar(aq?"next":"prev");
}}break;
case H.UP:aA.preventDefault();
at("prev");
break;
case H.DOWN:aA.preventDefault();
at("next");
break;
case H.SPACEBAR:aA.preventDefault();
if(aB){ax.select(ax.current.closest("tr"));
}break;
case H.ENTER:aA.preventDefault();
if(aB){if(ax.options.editable){ax._cachedCurrent=ax.current;
ax.list._startEditHandler(ax.current);
a(this).one("keyup",function(aD){aD.stopPropagation();
});
}}else{ax.current.children("a.k-link").click();
}break;
case H.ESC:aA.stopPropagation();
break;
case H.DELETE:if(aB){al();
}break;
default:if(aC>=49&&aC<=57){ax.view(ax.timeline._viewByIndex(aC-49));
}break;
}});
},_current:function(aj){var ak=v.styles;
var ai;
if(this.current&&this.current.length){this.current.removeClass(ak.focused).removeAttr("id");
}if(aj&&aj.length){this.current=aj.addClass(ak.focused).attr("id",b);
ai=a(G._activeElement());
if(ai.is("table")&&this.wrapper.find(ai).length>0){ai.removeAttr(d).attr(d,b);
}}else{this.current=null;
}},_dataBind:function(){var aj=this;
if(aj.options.autoBind){this._preventRefresh=true;
this._preventDependencyRefresh=true;
var ai=a.map([this.dataSource,this.dependencies,this.resources.dataSource,this.assignments.dataSource],function(ak){return ak.fetch();
});
a.when.apply(null,ai).done(function(){aj._preventRefresh=false;
aj._preventDependencyRefresh=false;
aj.refresh();
});
}},_resize:function(){this._adjustDimensions();
this.timeline.view()._adjustHeight();
this.timeline.view()._renderCurrentTime();
this.list._adjustHeight();
}});
if(G.PDFMixin){G.PDFMixin.extend(v.fn);
v.fn._drawPDF=function(){var aj="."+z.list;
var ak=this.wrapper.find(aj).width();
var ai=this.wrapper.clone();
ai.find(aj).css("width",ak);
return this._drawPDFShadow({content:ai});
};
}G.ui.plugin(v);
t(true,v,{styles:z});
})(window.kendo.jQuery);
})();
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
