(function(b,a){a(["./kendo.core","./kendo.color","./kendo.drawing"],b);
})(function(){(function(){(function(al,M,ai){var x=al.kendo;
var q=!!al.Uint8Array;
var J="\n";
var ah=0;
var b=(function(){var ao="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
return{decode:function(aB){var ay=aB.replace(/[^A-Za-z0-9\+\/\=]/g,""),ax=0,az=ay.length,aA=[];
while(ax<az){var at=ao.indexOf(ay.charAt(ax++));
var au=ao.indexOf(ay.charAt(ax++));
var av=ao.indexOf(ay.charAt(ax++));
var aw=ao.indexOf(ay.charAt(ax++));
var ap=(at<<2)|(au>>>4);
var aq=((au&15)<<4)|(av>>>2);
var ar=((av&3)<<6)|aw;
aA.push(ap);
if(av!=64){aA.push(aq);
}if(aw!=64){aA.push(ar);
}}return aA;
},encode:function(ap){var ay=0,az=ap.length;
var aA="";
while(ay<az){var aq=ap[ay++];
var ar=ap[ay++];
var at=ap[ay++];
var au=aq>>>2;
var av=((aq&3)<<4)|(ar>>>4);
var aw=((ar&15)<<2)|(at>>>6);
var ax=at&63;
if(ay-az==2){aw=ax=64;
}else{if(ay-az==1){ax=64;
}}aA+=ao.charAt(au)+ao.charAt(av)+ao.charAt(aw)+ao.charAt(ax);
}return aA;
}};
}());
var L={a0:[2383.94,3370.39],a1:[1683.78,2383.94],a2:[1190.55,1683.78],a3:[841.89,1190.55],a4:[595.28,841.89],a5:[419.53,595.28],a6:[297.64,419.53],a7:[209.76,297.64],a8:[147.4,209.76],a9:[104.88,147.4],a10:[73.7,104.88],b0:[2834.65,4008.19],b1:[2004.09,2834.65],b2:[1417.32,2004.09],b3:[1000.63,1417.32],b4:[708.66,1000.63],b5:[498.9,708.66],b6:[354.33,498.9],b7:[249.45,354.33],b8:[175.75,249.45],b9:[124.72,175.75],b10:[87.87000000000001,124.72],c0:[2599.37,3676.54],c1:[1836.85,2599.37],c2:[1298.27,1836.85],c3:[918.43,1298.27],c4:[649.13,918.43],c5:[459.21,649.13],c6:[323.15,459.21],c7:[229.61,323.15],c8:[161.57,229.61],c9:[113.39,161.57],c10:[79.37000000000001,113.39],executive:[521.86,756],folio:[612,936],legal:[612,1008],letter:[612,792],tabloid:[792,1224]};
function F(){var ao=0,aq=c();
function ap(){for(var ar=0;
ar<arguments.length;
++ar){var au=arguments[ar];
if(au===ai){throw new Error("Cannot output undefined to PDF");
}else{if(au instanceof ae){au.beforeRender(ap);
au.render(ap);
}else{if(u(au)){af(au,ap);
}else{if(v(au)){ag(au,ap);
}else{if(typeof au=="number"){if(isNaN(au)){throw new Error("Cannot output NaN to PDF");
}var at=au.toFixed(7);
if(at.indexOf(".")>=0){at=at.replace(/\.?0+$/,"");
}if(at=="-0"){at="0";
}aq.writeString(at);
}else{if(/string|boolean/.test(typeof au)){aq.writeString(au+"");
}else{if(typeof au.get=="function"){aq.write(au.get());
}else{if(typeof au=="object"){if(!au){aq.writeString("null");
}else{ap(new P(au));
}}}}}}}}}}}ap.writeData=function(ar){aq.write(ar);
};
ap.withIndent=function(ar){++ao;
ar(ap);
--ao;
};
ap.indent=function(){ap(J,K("",ao*2,"  "));
ap.apply(null,arguments);
};
ap.offset=function(){return aq.offset();
};
ap.toString=function(){throw new Error("FIX CALLER");
};
ap.get=function(){return aq.get();
};
ap.stream=function(){return aq;
};
return ap;
}function am(ar,ap){var ao=ar.beforeRender;
var aq=ar.render;
ar.beforeRender=function(){};
ar.render=function(at){at(ap," 0 R");
};
ar.renderFull=function(at){ar._offset=at.offset();
at(ap," 0 obj ");
ao.call(ar,at);
aq.call(ar,at);
at(" endobj");
};
}function p(ao){var aq=ao("paperSize",L.a4);
if(!aq){return{};
}if(typeof aq=="string"){aq=L[aq.toLowerCase()];
if(aq==null){throw new Error("Unknown paper size");
}}aq[0]=aj(aq[0]);
aq[1]=aj(aq[1]);
if(ao("landscape",false)){aq=[Math.max(aq[0],aq[1]),Math.min(aq[0],aq[1])];
}var ap=ao("margin");
if(ap){if(typeof ap=="string"||typeof ap=="number"){ap=aj(ap,0);
ap={left:ap,top:ap,right:ap,bottom:ap};
}else{ap={left:aj(ap.left,0),top:aj(ap.top,0),right:aj(ap.right,0),bottom:aj(ap.bottom,0)};
}if(ao("addMargin")){aq[0]+=ap.left+ap.right;
aq[1]+=ap.top+ap.bottom;
}}return{paperSize:aq,margin:ap};
}function Q(at){var aw=this;
var au=F();
var aq=0;
var ar=[];
function ap(ay,ax){return(at&&at[ay]!=null)?at[ay]:ax;
}aw.getOption=ap;
aw.attach=function(ax){if(ar.indexOf(ax)<0){am(ax,++aq);
ar.push(ax);
}return ax;
};
aw.pages=[];
aw.FONTS={};
aw.IMAGES={};
aw.GRAD_COL_FUNCTIONS={};
aw.GRAD_OPC_FUNCTIONS={};
aw.GRAD_COL={};
aw.GRAD_OPC={};
var ao=aw.attach(new O());
var av=aw.attach(new X());
ao.setPages(av);
aw.addPage=function(aB){var aD=p(function(aH,aG){return(aB&&aB[aH]!=null)?aB[aH]:aG;
});
var aE=aD.paperSize;
var aA=aD.margin;
var az=aE[0];
var ay=aE[1];
if(aA){az-=aA.left+aA.right;
ay-=aA.top+aA.bottom;
}var ax=new aa(F(),null,true);
var aF={Contents:aw.attach(ax),Parent:av,MediaBox:[0,0,aE[0],aE[1]]};
var aC=new W(aw,aF);
aC._content=ax;
av.addPage(aw.attach(aC));
aC.transform(1,0,0,-1,0,aE[1]);
if(aA){aC.translate(aA.left,aA.top);
aC.rect(0,0,az,ay);
aC.clip();
}aw.pages.push(aC);
return aC;
};
aw.render=function(){var ax;
au("%PDF-1.4",J,"%\xc2\xc1\xda\xcf\xce",J,J);
for(ax=0;
ax<ar.length;
++ax){ar[ax].renderFull(au);
au(J,J);
}var ay=au.offset();
au("xref",J,0," ",ar.length+1,J);
au("0000000000 65535 f ",J);
for(ax=0;
ax<ar.length;
++ax){au(an(ar[ax]._offset,10)," 00000 n ",J);
}au(J);
au("trailer",J);
au(new P({Size:ar.length+1,Root:ao,Info:new P({Producer:new ab(ap("producer","Kendo UI PDF Generator")),Title:new ab(ap("title","")),Author:new ab(ap("author","")),Subject:new ab(ap("subject","")),Keywords:new ab(ap("keywords","")),Creator:new ab(ap("creator","Kendo UI PDF Generator")),CreationDate:ap("date",new Date())})}),J,J);
au("startxref",J,ay,J);
au("%%EOF",J);
return au.stream().offset(0);
};
}var l={"Times-Roman":true,"Times-Bold":true,"Times-Italic":true,"Times-BoldItalic":true,Helvetica:true,"Helvetica-Bold":true,"Helvetica-Oblique":true,"Helvetica-BoldOblique":true,Courier:true,"Courier-Bold":true,"Courier-Oblique":true,"Courier-BoldOblique":true,Symbol:true,ZapfDingbats:true};
function y(ar,ao){function ap(){if(al.console){if(al.console.error){al.console.error("Cannot load URL: %s",ar);
}else{al.console.log("Cannot load URL: %s",ar);
}}ao(null);
}var aq=new XMLHttpRequest();
aq.open("GET",ar,true);
if(q){aq.responseType="arraybuffer";
}aq.onload=function(){if(aq.status==200||aq.status==304){if(q){ao(new Uint8Array(aq.response));
}else{ao(new VBArray(aq.responseBody).toArray());
}}else{ap();
}};
aq.onerror=ap;
aq.send(null);
}function z(aq,ao){var ap=l[aq];
if(ap){ao(ap);
}else{y(aq,function(ar){if(ar==null){throw new Error("Cannot load font from "+aq);
}else{var at=new x.pdf.TTFFont(ar);
l[aq]=at;
ao(at);
}});
}}var s={};
function B(aw,au){var av=s[aw],at,ar;
if(av){au(av);
}else{av=new Image();
if(!(/^data:/i.test(aw))){av.crossOrigin="Anonymous";
}if(q&&!(/^data:/i.test(aw))){var ax=new XMLHttpRequest();
ax.onload=function(){ar=ax.response;
at=URL.createObjectURL(ar);
ao(at);
};
ax.onerror=ap;
ax.open("GET",aw,true);
ax.responseType="blob";
ax.send();
}else{ao(aw);
}}function ao(ay){av.src=ay;
if(av.complete&&!x.support.browser.msie){aq();
}else{av.onload=aq;
av.onerror=ap;
}}function ap(){au(s[aw]="TAINTED");
}function aq(){if(ar&&/^image\/jpe?g$/i.test(ar.type)){var aI=new FileReader();
aI.onload=function(){av=new T(av.width,av.height,c(new Uint8Array(this.result)));
URL.revokeObjectURL(at);
au(s[aw]=av);
};
aI.readAsArrayBuffer(ar);
return;
}var aA=document.createElement("canvas");
aA.width=av.width;
aA.height=av.height;
var aB=aA.getContext("2d");
aB.drawImage(av,0,0);
var aG;
try{aG=aB.getImageData(0,0,av.width,av.height);
}catch(aD){return ap();
}finally{if(at){URL.revokeObjectURL(at);
}}var aE=false,aJ=c(),az=c();
var aH=aG.data;
var aF=0;
while(aF<aH.length){aJ.writeByte(aH[aF++]);
aJ.writeByte(aH[aF++]);
aJ.writeByte(aH[aF++]);
var ay=aH[aF++];
if(ay<255){aE=true;
}az.writeByte(ay);
}if(aE){av=new Y(av.width,av.height,aJ,az);
}else{var aC=aA.toDataURL("image/jpeg");
aC=aC.substr(aC.indexOf(";base64,")+8);
var aK=c();
aK.writeBase64(aC);
aK.offset(0);
av=new T(av.width,av.height,aK);
}au(s[aw]=av);
}}function G(ao){return function(at,ap){var ar=at.length,aq=ar;
if(ar===0){return ap();
}while(aq-->0){ao(at[aq],function(){if(--ar===0){ap();
}});
}};
}var A=G(z);
var C=G(B);
Q.prototype={loadFonts:A,loadImages:C,getFont:function(ap){var ao=this.FONTS[ap];
if(!ao){ao=l[ap];
if(!ao){throw new Error("Font "+ap+" has not been loaded");
}if(ao===true){ao=this.attach(new Z(ap));
}else{ao=this.attach(new R(this,ao));
}this.FONTS[ap]=ao;
}return ao;
},getImage:function(ap){var ao=this.IMAGES[ap];
if(!ao){ao=s[ap];
if(!ao){throw new Error("Image "+ap+" has not been loaded");
}if(ao==="TAINTED"){return null;
}ao=this.IMAGES[ap]=this.attach(ao.asStream(this));
}return ao;
},getOpacityGS:function(at,ap){var ar=M(at).toFixed(3);
at=M(ar);
ar+=ap?"S":"F";
var ao=this._opacityGSCache||(this._opacityGSCache={});
var aq=ao[ar];
if(!aq){var au={Type:a("ExtGState")};
if(ap){au.CA=at;
}else{au.ca=at;
}aq=this.attach(new P(au));
aq._resourceName=a("GS"+(++ah));
ao[ar]=aq;
}return aq;
},dict:function(ao){return new P(ao);
},name:function(ao){return a(ao);
},stream:function(ap,ao){return new aa(ao,ap);
}};
function K(aq,ap,ao){while(aq.length<ap){aq=ao+aq;
}return aq;
}function an(ap,ao){return K(ap+"",ao,"0");
}function r(ap,ao){return Object.prototype.hasOwnProperty.call(ap,ao);
}var u=Array.isArray||function(ao){return ao instanceof Array;
};
function v(ao){return ao instanceof Date;
}function af(ao,ap){ap("[");
if(ao.length>0){ap.withIndent(function(){for(var aq=0;
aq<ao.length;
++aq){if(aq>0&&aq%8===0){ap.indent(ao[aq]);
}else{ap(" ",ao[aq]);
}}});
}ap(" ]");
}function ag(ao,ap){ap("(D:",an(ao.getUTCFullYear(),4),an(ao.getUTCMonth()+1,2),an(ao.getUTCDate(),2),an(ao.getUTCHours(),2),an(ao.getUTCMinutes(),2),an(ao.getUTCSeconds(),2),"Z)");
}function H(ao){return ao*(72/25.4);
}function i(ao){return H(ao*10);
}function t(ao){return ao*72;
}function aj(ar,ao){if(typeof ar=="number"){return ar;
}if(typeof ar=="string"){var ap;
ap=/^\s*([0-9.]+)\s*(mm|cm|in|pt)\s*$/.exec(ar);
if(ap){var aq=M(ap[1]);
if(!isNaN(aq)){if(ap[2]=="pt"){return aq;
}return{mm:H,cm:i,"in":t}[ap[2]](aq);
}}}if(ao!=null){return ao;
}throw new Error("Can't parse unit: "+ar);
}function ae(){}ae.prototype.beforeRender=function(){};
function j(ap,ar,ao){if(!ao){ao=ae;
}ap.prototype=new ao();
for(var aq in ar){if(r(ar,aq)){ap.prototype[aq]=ar[aq];
}}return ap;
}var ab=j(function ab(ao){this.value=ao;
},{render:function(aq){var ar="",ao=this.escape();
for(var ap=0;
ap<ao.length;
++ap){ar+=String.fromCharCode(ao.charCodeAt(ap)&255);
}aq("(",ar,")");
},escape:function(){return this.value.replace(/([\(\)\\])/g,"\\$1");
},toString:function(){return this.value;
}});
var S=j(function S(ao){this.value=ao;
},{render:function(ap){ap("<");
for(var ao=0;
ao<this.value.length;
++ao){ap(an(this.value.charCodeAt(ao).toString(16),4));
}ap(">");
}},ab);
var U=j(function U(ao){this.name=ao;
},{render:function(ao){ao("/"+this.escape());
},escape:function(){return this.name.replace(/[^\x21-\x7E]/g,function(ao){return"#"+an(ao.charCodeAt(0).toString(16),2);
});
},toString:function(){return this.name;
}});
var V={};
U.get=a;
function a(ao){if(r(V,ao)){return V[ao];
}return(V[ao]=new U(ao));
}var P=j(function P(ao){this.props=ao;
},{render:function(ap){var aq=this.props,ao=true;
ap("<<");
ap.withIndent(function(){for(var ar in aq){if(r(aq,ar)&&!/^_/.test(ar)){ao=false;
ap.indent(a(ar)," ",aq[ar]);
}}});
if(!ao){ap.indent();
}ap(">>");
}});
var aa=j(function aa(ap,aq,ao){if(typeof ap=="string"){var ar=c();
ar.write(ap);
ap=ar;
}this.data=ap;
this.props=aq||{};
this.compress=ao;
},{render:function(ap){var ao=this.data.get(),aq=this.props;
if(this.compress&&al.pako&&typeof al.pako.deflate=="function"){if(!aq.Filter){aq.Filter=[];
}else{if(!(aq.Filter instanceof Array)){aq.Filter=[aq.Filter];
}}aq.Filter.unshift(a("FlateDecode"));
ao=al.pako.deflate(ao);
}aq.Length=ao.length;
ap(new P(aq)," stream",J);
ap.writeData(ao);
ap(J,"endstream");
}});
var O=j(function O(ao){ao=this.props=ao||{};
ao.Type=a("Catalog");
},{setPages:function(ao){this.props.Pages=ao;
}},P);
var X=j(function X(){this.props={Type:a("Pages"),Kids:[],Count:0};
},{addPage:function(ao){this.props.Kids.push(ao);
this.props.Count++;
}},P);
function T(aq,ap,ao){this.asStream=function(){var ar=new aa(ao,{Type:a("XObject"),Subtype:a("Image"),Width:aq,Height:ap,BitsPerComponent:8,ColorSpace:a("DeviceRGB"),Filter:a("DCTDecode")});
ar._resourceName=a("I"+(++ah));
return ar;
};
}function Y(ar,ap,aq,ao){this.asStream=function(au){var at=new aa(ao,{Type:a("XObject"),Subtype:a("Image"),Width:ar,Height:ap,BitsPerComponent:8,ColorSpace:a("DeviceGray")},true);
var av=new aa(aq,{Type:a("XObject"),Subtype:a("Image"),Width:ar,Height:ap,BitsPerComponent:8,ColorSpace:a("DeviceRGB"),SMask:au.attach(at)},true);
av._resourceName=a("I"+(++ah));
return av;
};
}var Z=j(function Z(ao){this.props={Type:a("Font"),Subtype:a("Type1"),BaseFont:a(ao)};
this._resourceName=a("F"+(++ah));
},{encodeText:function(ao){return new ab(ao+"");
}},P);
var R=j(function R(aq,ao,ar){ar=this.props=ar||{};
ar.Type=a("Font");
ar.Subtype=a("Type0");
ar.Encoding=a("Identity-H");
this._pdf=aq;
this._font=ao;
this._sub=ao.makeSubset();
this._resourceName=a("F"+(++ah));
var ap=ao.head;
this.name=ao.psName;
var at=this.scale=ao.scale;
this.bbox=[ap.xMin*at,ap.yMin*at,ap.xMax*at,ap.yMax*at];
this.italicAngle=ao.post.italicAngle;
this.ascent=ao.ascent*at;
this.descent=ao.descent*at;
this.lineGap=ao.lineGap*at;
this.capHeight=ao.os2.capHeight||this.ascent;
this.xHeight=ao.os2.xHeight||0;
this.stemV=0;
this.familyClass=(ao.os2.familyClass||0)>>8;
this.isSerif=this.familyClass>=1&&this.familyClass<=7;
this.isScript=this.familyClass==10;
this.flags=((ao.post.isFixedPitch?1:0)|(this.isSerif?1<<1:0)|(this.isScript?1<<3:0)|(this.italicAngle!==0?1<<6:0)|(1<<5));
},{encodeText:function(ao){return new S(this._sub.encodeText(ao+""));
},getTextWidth:function(ap,at){var au=0,ao=this._font.cmap.getUnicodeEntry().codeMap;
for(var ar=0;
ar<at.length;
++ar){var aq=ao[at.charCodeAt(ar)];
au+=this._font.widthOfGlyph(aq||0);
}return au*ap/1000;
},beforeRender:function(){var az=this;
var aA=az._sub;
var aq=aA.render();
var aw=new aa(c(aq),{Length1:aq.length},true);
var at=az._pdf.attach(new P({Type:a("FontDescriptor"),FontName:a(az._sub.psName),FontBBox:az.bbox,Flags:az.flags,StemV:az.stemV,ItalicAngle:az.italicAngle,Ascent:az.ascent,Descent:az.descent,CapHeight:az.capHeight,XHeight:az.xHeight,FontFile2:az._pdf.attach(aw)}));
var ap=aA.ncid2ogid;
var av=aA.firstChar;
var ax=aA.lastChar;
var ao=[];
(function ay(aF,aD){if(aF<=ax){var aE=ap[aF];
if(aE==null){ay(aF+1);
}else{if(!aD){ao.push(aF,aD=[]);
}aD.push(az._font.widthOfGlyph(aE));
ay(aF+1,aD);
}}})(av);
var ar=new P({Type:a("Font"),Subtype:a("CIDFontType2"),BaseFont:a(az._sub.psName),CIDSystemInfo:new P({Registry:new ab("Adobe"),Ordering:new ab("Identity"),Supplement:0}),FontDescriptor:at,FirstChar:av,LastChar:ax,DW:Math.round(az._font.widthOfGlyph(0)),W:ao,CIDToGIDMap:az._pdf.attach(az._makeCidToGidMap())});
var au=az.props;
au.BaseFont=a(az._sub.psName);
au.DescendantFonts=[az._pdf.attach(ar)];
var aB=new ac(av,ax,aA.subset);
var aC=new aa(F(),null,true);
aC.data(aB);
au.ToUnicode=az._pdf.attach(aC);
},_makeCidToGidMap:function(){return new aa(c(this._sub.cidToGidMap()),null,true);
}},P);
var ac=j(function ad(ao,ap,aq){this.firstChar=ao;
this.lastChar=ap;
this.map=aq;
},{render:function(ao){ao.indent("/CIDInit /ProcSet findresource begin");
ao.indent("12 dict begin");
ao.indent("begincmap");
ao.indent("/CIDSystemInfo <<");
ao.indent("  /Registry (Adobe)");
ao.indent("  /Ordering (UCS)");
ao.indent("  /Supplement 0");
ao.indent(">> def");
ao.indent("/CMapName /Adobe-Identity-UCS def");
ao.indent("/CMapType 2 def");
ao.indent("1 begincodespacerange");
ao.indent("  <0000><ffff>");
ao.indent("endcodespacerange");
var ap=this;
ao.indent(ap.lastChar-ap.firstChar+1," beginbfchar");
ao.withIndent(function(){for(var aq=ap.firstChar;
aq<=ap.lastChar;
++aq){var ar=ap.map[aq];
ao.indent("<",an(aq.toString(16),4),">","<",an(ar.toString(16),4),">");
}});
ao.indent("endbfchar");
ao.indent("endcmap");
ao.indent("CMapName currentdict /CMap defineresource pop");
ao.indent("end");
ao.indent("end");
}});
function E(ao){return ao.map(function(ap){return u(ap)?E(ap):typeof ap=="number"?(Math.round(ap*1000)/1000).toFixed(3):ap;
}).join(" ");
}function e(av,aw,ar,ao,ax,at,ap){var au=E([aw,ar,ao,ax,at,ap]);
var aq=av.GRAD_COL_FUNCTIONS[au];
if(!aq){aq=av.GRAD_COL_FUNCTIONS[au]=av.attach(new P({FunctionType:2,Domain:[0,1],Range:[0,1,0,1,0,1],N:1,C0:[aw,ar,ao],C1:[ax,at,ap]}));
}return aq;
}function h(at,ao,ap){var ar=E([ao,ap]);
var aq=at.GRAD_OPC_FUNCTIONS[ar];
if(!aq){aq=at.GRAD_OPC_FUNCTIONS[ar]=at.attach(new P({FunctionType:2,Domain:[0,1],Range:[0,1],N:1,C0:[ao],C1:[ap]}));
}return aq;
}function D(ay,aB){var au=false;
var ax=[];
var ap=[];
var aw=[];
var at=[];
var av,az,aq,aA,ar;
for(av=1;
av<aB.length;
++av){az=aB[av-1];
aq=aB[av];
aA=az.color;
ar=aq.color;
ap.push(e(ay,aA.r,aA.g,aA.b,ar.r,ar.g,ar.b));
if(aA.a<1||ar.a<1){au=true;
}aw.push(aq.offset);
at.push(0,1);
}if(au){for(av=1;
av<aB.length;
++av){az=aB[av-1];
aq=aB[av];
aA=az.color;
ar=aq.color;
ax.push(h(ay,aA.a,ar.a));
}}aw.pop();
return{hasAlpha:au,colors:ao(ap),opacities:au?ao(ax):null};
function ao(aC){if(aC.length==1){return aC[0];
}return{FunctionType:3,Functions:aC,Domain:[0,1],Bounds:aw,Encode:at};
}}function d(av,au,ax,aq,ar,ap){var aw,at;
if(!ap){var ao=[au].concat(aq);
ax.forEach(function(ay){ao.push(ay.offset,ay.color.r,ay.color.g,ay.color.b);
});
at=E(ao);
aw=av.GRAD_COL[at];
}if(!aw){aw=new P({Type:a("Shading"),ShadingType:au?3:2,ColorSpace:a("DeviceRGB"),Coords:aq,Domain:[0,1],Function:ar,Extend:[true,true]});
av.attach(aw);
aw._resourceName="S"+(++ah);
if(at){av.GRAD_COL[at]=aw;
}}return aw;
}function g(aw,au,ax,aq,ar,ap){var av,at;
if(!ap){var ao=[au].concat(aq);
ax.forEach(function(ay){ao.push(ay.offset,ay.color.a);
});
at=E(ao);
av=aw.GRAD_OPC[at];
}if(!av){av=new P({Type:a("ExtGState"),AIS:false,CA:1,ca:1,SMask:{Type:a("Mask"),S:a("Luminosity"),G:aw.attach(new aa("/a0 gs /s0 sh",{Type:a("XObject"),Subtype:a("Form"),FormType:1,BBox:(ap?[ap.left,ap.top+ap.height,ap.left+ap.width,ap.top]:[0,1,1,0]),Group:{Type:a("Group"),S:a("Transparency"),CS:a("DeviceGray"),I:true},Resources:{ExtGState:{a0:{CA:1,ca:1}},Shading:{s0:{ColorSpace:a("DeviceGray"),Coords:aq,Domain:[0,1],ShadingType:au?3:2,Function:ar,Extend:[true,true]}}}}))}});
aw.attach(av);
av._resourceName="O"+(++ah);
if(at){aw.GRAD_OPC[at]=av;
}}return av;
}function f(av,ar,ao){var at=ar.type=="radial";
var aq=D(av,ar.stops);
var ap=at?[ar.start.x,ar.start.y,ar.start.r,ar.end.x,ar.end.y,ar.end.r]:[ar.start.x,ar.start.y,ar.end.x,ar.end.y];
var aw=d(av,at,ar.stops,ap,aq.colors,ar.userSpace&&ao);
var au=aq.hasAlpha?g(av,at,ar.stops,ap,aq.opacities,ar.userSpace&&ao):null;
return{hasAlpha:aq.hasAlpha,shading:aw,opacity:au};
}var W=j(function W(ao,ap){this._pdf=ao;
this._rcount=0;
this._textMode=false;
this._fontResources={};
this._gsResources={};
this._xResources={};
this._patResources={};
this._shResources={};
this._opacity=1;
this._matrix=[1,0,0,1,0,0];
this._annotations=[];
this._font=null;
this._fontSize=null;
this._contextStack=[];
ap=this.props=ap||{};
ap.Type=a("Page");
ap.ProcSet=[a("PDF"),a("Text"),a("ImageB"),a("ImageC"),a("ImageI")];
ap.Resources=new P({Font:new P(this._fontResources),ExtGState:new P(this._gsResources),XObject:new P(this._xResources),Pattern:new P(this._patResources),Shading:new P(this._shResources)});
ap.Annots=this._annotations;
},{_out:function(){this._content.data.apply(null,arguments);
},transform:function(ao,ap,aq,ar,at,au){if(!w(arguments)){this._matrix=I(arguments,this._matrix);
this._out(ao," ",ap," ",aq," ",ar," ",at," ",au," cm");
this._out(J);
}},translate:function(ao,ap){this.transform(1,0,0,1,ao,ap);
},scale:function(ao,ap){this.transform(ao,0,0,ap,0,0);
},rotate:function(ao){var ap=Math.cos(ao),aq=Math.sin(ao);
this.transform(ap,aq,-aq,ap,0,0);
},beginText:function(){this._textMode=true;
this._out("BT",J);
},endText:function(){this._textMode=false;
this._out("ET",J);
},_requireTextMode:function(){if(!this._textMode){throw new Error("Text mode required; call page.beginText() first");
}},_requireFont:function(){if(!this._font){throw new Error("No font selected; call page.setFont() first");
}},setFont:function(ao,ap){this._requireTextMode();
if(ao==null){ao=this._font;
}else{if(!(ao instanceof R)){ao=this._pdf.getFont(ao);
}}if(ap==null){ap=this._fontSize;
}this._fontResources[ao._resourceName]=ao;
this._font=ao;
this._fontSize=ap;
this._out(ao._resourceName," ",ap," Tf",J);
},setTextLeading:function(ao){this._requireTextMode();
this._out(ao," TL",J);
},setTextRenderingMode:function(ao){this._requireTextMode();
this._out(ao," Tr",J);
},showText:function(ar,ap){this._requireFont();
if(ar.length>1&&ap&&this._font instanceof R){var ao=this._font.getTextWidth(this._fontSize,ar);
var aq=ap/ao*100;
this._out(aq," Tz ");
}this._out(this._font.encodeText(ar)," Tj",J);
},showTextNL:function(ao){this._requireFont();
this._out(this._font.encodeText(ao)," '",J);
},addLink:function(ar,ao){var ap=this._toPage({x:ao.left,y:ao.bottom});
var aq=this._toPage({x:ao.right,y:ao.top});
this._annotations.push(new P({Type:a("Annot"),Subtype:a("Link"),Rect:[ap.x,ap.y,aq.x,aq.y],Border:[0,0,0],A:new P({Type:a("Action"),S:a("URI"),URI:new ab(ar)})}));
},setStrokeColor:function(aq,ap,ao){this._out(aq," ",ap," ",ao," RG",J);
},setOpacity:function(ao){this.setFillOpacity(ao);
this.setStrokeOpacity(ao);
this._opacity*=ao;
},setStrokeOpacity:function(ap){if(ap<1){var ao=this._pdf.getOpacityGS(this._opacity*ap,true);
this._gsResources[ao._resourceName]=ao;
this._out(ao._resourceName," gs",J);
}},setFillColor:function(aq,ap,ao){this._out(aq," ",ap," ",ao," rg",J);
},setFillOpacity:function(ap){if(ap<1){var ao=this._pdf.getOpacityGS(this._opacity*ap,false);
this._gsResources[ao._resourceName]=ao;
this._out(ao._resourceName," gs",J);
}},gradient:function(aq,ao){this.save();
this.rect(ao.left,ao.top,ao.width,ao.height);
this.clip();
if(!aq.userSpace){this.transform(ao.width,0,0,ao.height,ao.left,ao.top);
}var ap=f(this._pdf,aq,ao);
var at=ap.shading._resourceName,ar;
this._shResources[at]=ap.shading;
if(ap.hasAlpha){ar=ap.opacity._resourceName;
this._gsResources[ar]=ap.opacity;
this._out("/"+ar+" gs ");
}this._out("/"+at+" sh",J);
this.restore();
},setDashPattern:function(ao,ap){this._out(ao," ",ap," d",J);
},setLineWidth:function(ao){this._out(ao," w",J);
},setLineCap:function(ao){this._out(ao," J",J);
},setLineJoin:function(ao){this._out(ao," j",J);
},setMitterLimit:function(ao){this._out(ao," M",J);
},save:function(){this._contextStack.push(this._context());
this._out("q",J);
},restore:function(){this._out("Q",J);
this._context(this._contextStack.pop());
},moveTo:function(ao,ap){this._out(ao," ",ap," m",J);
},lineTo:function(ao,ap){this._out(ao," ",ap," l",J);
},bezier:function(ao,ar,ap,at,aq,au){this._out(ao," ",ar," ",ap," ",at," ",aq," ",au," c",J);
},bezier1:function(ao,aq,ap,ar){this._out(ao," ",aq," ",ap," ",ar," y",J);
},bezier2:function(ao,aq,ap,ar){this._out(ao," ",aq," ",ap," ",ar," v",J);
},close:function(){this._out("h",J);
},rect:function(aq,ar,ap,ao){this._out(aq," ",ar," ",ap," ",ao," re",J);
},ellipse:function(au,av,ar,at){function ao(aw){return au+aw;
}function ap(aw){return av+aw;
}var aq=0.5522847498307936;
this.moveTo(ao(0),ap(at));
this.bezier(ao(ar*aq),ap(at),ao(ar),ap(at*aq),ao(ar),ap(0));
this.bezier(ao(ar),ap(-at*aq),ao(ar*aq),ap(-at),ao(0),ap(-at));
this.bezier(ao(-ar*aq),ap(-at),ao(-ar),ap(-at*aq),ao(-ar),ap(0));
this.bezier(ao(-ar),ap(at*aq),ao(-ar*aq),ap(at),ao(0),ap(at));
},circle:function(ap,aq,ao){this.ellipse(ap,aq,ao,ao);
},stroke:function(){this._out("S",J);
},nop:function(){this._out("n",J);
},clip:function(){this._out("W n",J);
},clipStroke:function(){this._out("W S",J);
},closeStroke:function(){this._out("s",J);
},fill:function(){this._out("f",J);
},fillStroke:function(){this._out("B",J);
},drawImage:function(ap){var ao=this._pdf.getImage(ap);
if(ao){this._xResources[ao._resourceName]=ao;
this._out(ao._resourceName," Do",J);
}},comment:function(ap){var ao=this;
ap.split(/\r?\n/g).forEach(function(aq){ao._out("% ",aq,J);
});
},_context:function(ao){if(ao!=null){this._opacity=ao.opacity;
this._matrix=ao.matrix;
}else{return{opacity:this._opacity,matrix:this._matrix};
}},_toPage:function(aw){var av=this._matrix;
var ao=av[0],ap=av[1],aq=av[2],ar=av[3],at=av[4],au=av[5];
return{x:ao*aw.x+aq*aw.y+at,y:ap*aw.x+ar*aw.y+au};
}},P);
function c(ao){var au=0,at=0;
if(ao==null){ao=q?new Uint8Array(256):[];
}else{at=ao.length;
}var ap=q?function(aQ){if(aQ>=ao.length){var aR=new Uint8Array(Math.max(aQ+256,ao.length*2));
aR.set(ao,0);
ao=aR;
}}:function(){};
var ar=q?function(){return new Uint8Array(ao.buffer,0,at);
}:function(){return ao;
};
var aH=q?function(aQ){if(typeof aQ=="string"){return aP(aQ);
}var aR=aQ.length;
ap(au+aR);
ao.set(aQ,au);
au+=aR;
if(au>at){at=au;
}}:function(aQ){if(typeof aQ=="string"){return aP(aQ);
}for(var aR=0;
aR<aQ.length;
++aR){aI(aQ[aR]);
}};
var aE=q?function(aR,aQ){if(ao.buffer.slice){return new Uint8Array(ao.buffer.slice(aR,aR+aQ));
}else{var aS=new Uint8Array(aQ);
aS.set(new Uint8Array(ao.buffer,aR,aQ));
return aS;
}}:function(aR,aQ){return ao.slice(aR,aR+aQ);
};
function aq(){return au>=at;
}function aw(){return au<at?ao[au++]:0;
}function aI(aQ){ap(au);
ao[au++]=aQ&255;
if(au>at){at=au;
}}function aB(){return(aw()<<8)|aw();
}function aN(aQ){aI(aQ>>8);
aI(aQ);
}function aC(){var aQ=aB();
return aQ>=32768?aQ-65536:aQ;
}function aO(aQ){aN(aQ<0?aQ+65536:aQ);
}function az(){return(aB()*65536)+aB();
}function aL(aQ){aN((aQ>>>16)&65535);
aN(aQ&65535);
}function aA(){var aQ=az();
return aQ>=2147483648?aQ-4294967296:aQ;
}function aM(aQ){aL(aQ<0?aQ+4294967296:aQ);
}function ax(){return az()/65536;
}function aJ(aQ){aL(Math.round(aQ*65536));
}function ay(){return aA()/65536;
}function aK(aQ){aM(Math.round(aQ*65536));
}function av(aQ){return aG(aQ,aw);
}function aD(aQ){return String.fromCharCode.apply(String,av(aQ));
}function aP(aR){for(var aQ=0;
aQ<aR.length;
++aQ){aI(aR.charCodeAt(aQ));
}}function aG(aR,aS){for(var aT=new Array(aR),aQ=0;
aQ<aR;
++aQ){aT[aQ]=aS();
}return aT;
}var aF={eof:aq,readByte:aw,writeByte:aI,readShort:aB,writeShort:aN,readLong:az,writeLong:aL,readFixed:ax,writeFixed:aJ,readShort_:aC,writeShort_:aO,readLong_:aA,writeLong_:aM,readFixed_:ay,writeFixed_:aK,read:av,write:aH,readString:aD,writeString:aP,times:aG,get:ar,slice:aE,offset:function(aQ){if(aQ!=null){au=aQ;
return aF;
}return au;
},skip:function(aQ){au+=aQ;
},toString:function(){throw new Error("FIX CALLER.  BinaryStream is no longer convertible to string!");
},length:function(){return at;
},saveExcursion:function(aQ){var aR=au;
try{return aQ();
}finally{au=aR;
}},writeBase64:function(aQ){if(al.atob){aP(al.atob(aQ));
}else{aH(b.decode(aQ));
}},base64:function(){return b.encode(ar());
}};
return aF;
}function ak(ao){return ao.replace(/^\s*(['"])(.*)\1\s*$/,"$2");
}function N(ao){var ar=/^\s*((normal|italic)\s+)?((normal|small-caps)\s+)?((normal|bold|\d+)\s+)?(([0-9.]+)(px|pt))(\/(([0-9.]+)(px|pt)|normal))?\s+(.*?)\s*$/i;
var aq=ar.exec(ao);
if(!aq){return{fontSize:12,fontFamily:"sans-serif"};
}var ap=aq[8]?parseInt(aq[8],10):12;
return{italic:aq[2]&&aq[2].toLowerCase()=="italic",variant:aq[4],bold:aq[6]&&/bold|700/i.test(aq[6]),fontSize:ap,lineHeight:aq[12]?aq[12]=="normal"?ap:parseInt(aq[12],10):null,fontFamily:aq[14].split(/\s*,\s*/g).map(ak)};
}function o(at){function aq(av){if(at.bold){av+="|bold";
}if(at.italic){av+="|italic";
}return av.toLowerCase();
}var ao=at.fontFamily;
var ar,au;
if(ao instanceof Array){for(var ap=0;
ap<ao.length;
++ap){ar=aq(ao[ap]);
au=m[ar];
if(au){break;
}}}else{au=m[ao.toLowerCase()];
}while(typeof au=="function"){au=au();
}if(!au){au="Times-Roman";
}return au;
}var m={serif:"Times-Roman","serif|bold":"Times-Bold","serif|italic":"Times-Italic","serif|bold|italic":"Times-BoldItalic","sans-serif":"Helvetica","sans-serif|bold":"Helvetica-Bold","sans-serif|italic":"Helvetica-Oblique","sans-serif|bold|italic":"Helvetica-BoldOblique",monospace:"Courier","monospace|bold":"Courier-Bold","monospace|italic":"Courier-Oblique","monospace|bold|italic":"Courier-BoldOblique",zapfdingbats:"ZapfDingbats","zapfdingbats|bold":"ZapfDingbats","zapfdingbats|italic":"ZapfDingbats","zapfdingbats|bold|italic":"ZapfDingbats"};
function n(ao,ap){ao=ao.toLowerCase();
m[ao]=function(){return m[ap];
};
m[ao+"|bold"]=function(){return m[ap+"|bold"];
};
m[ao+"|italic"]=function(){return m[ap+"|italic"];
};
m[ao+"|bold|italic"]=function(){return m[ap+"|bold|italic"];
};
}n("Times New Roman","serif");
n("Courier New","monospace");
n("Arial","sans-serif");
n("Helvetica","sans-serif");
n("Verdana","sans-serif");
n("Tahoma","sans-serif");
n("Georgia","sans-serif");
n("Monaco","monospace");
n("Andale Mono","monospace");
function k(ap,aq){if(arguments.length==1){for(var ao in ap){if(r(ap,ao)){k(ao,ap[ao]);
}}}else{ap=ap.toLowerCase();
m[ap]=aq;
switch(ap){case"dejavu sans":m["sans-serif"]=aq;
break;
case"dejavu sans|bold":m["sans-serif|bold"]=aq;
break;
case"dejavu sans|italic":m["sans-serif|italic"]=aq;
break;
case"dejavu sans|bold|italic":m["sans-serif|bold|italic"]=aq;
break;
case"dejavu serif":m.serif=aq;
break;
case"dejavu serif|bold":m["serif|bold"]=aq;
break;
case"dejavu serif|italic":m["serif|italic"]=aq;
break;
case"dejavu serif|bold|italic":m["serif|bold|italic"]=aq;
break;
case"dejavu mono":m.monospace=aq;
break;
case"dejavu mono|bold":m["monospace|bold"]=aq;
break;
case"dejavu mono|italic":m["monospace|italic"]=aq;
break;
case"dejavu mono|bold|italic":m["monospace|bold|italic"]=aq;
break;
}}}x.pdf={Document:Q,BinaryStream:c,defineFont:k,parseFontDef:N,getFontURL:o,loadFonts:A,loadImages:C,getPaperOptions:p,TEXT_RENDERING_MODE:{fill:0,stroke:1,fillAndStroke:2,invisible:3,fillAndClip:4,strokeAndClip:5,fillStrokeClip:6,clip:7}};
function I(ao,ar){var ap=ao[0],at=ao[1],av=ao[2],ax=ao[3],az=ao[4],aB=ao[5];
var aq=ar[0],au=ar[1],aw=ar[2],ay=ar[3],aA=ar[4],aC=ar[5];
return[ap*aq+at*aw,ap*au+at*ay,av*aq+ax*aw,av*au+ax*ay,az*aq+aB*aw+aA,az*au+aB*ay+aC];
}function w(ao){return ao[0]===1&&ao[1]===0&&ao[2]===0&&ao[3]===1&&ao[4]===0&&ao[5]===0;
}})(window,parseFloat);
})();
(function(){(function(u){function f(w,v){return Object.prototype.hasOwnProperty.call(w,v);
}function q(v){return Object.keys(v).sort(function(w,x){return w-x;
}).map(parseFloat);
}var o=u.kendo.pdf;
var a=o.BinaryStream;
function d(v){this.raw=v;
this.scalerType=v.readLong();
this.tableCount=v.readShort();
this.searchRange=v.readShort();
this.entrySelector=v.readShort();
this.rangeShift=v.readShort();
var y=this.tables={};
for(var x=0;
x<this.tableCount;
++x){var w={tag:v.readString(4),checksum:v.readLong(),offset:v.readLong(),length:v.readLong()};
y[w.tag]=w;
}}d.prototype={readTable:function(x,v){var w=this.tables[x];
if(!w){throw new Error("Table "+x+" not found in directory");
}return(this[x]=w.table=new v(this,w));
},render:function(I){var G=Object.keys(I).length;
var z=Math.pow(2,Math.floor(Math.log(G)/Math.LN2));
var D=z*16;
var x=Math.floor(Math.log(z)/Math.LN2);
var C=G*16-D;
var B=a();
B.writeLong(this.scalerType);
B.writeShort(G);
B.writeShort(D);
B.writeShort(x);
B.writeShort(C);
var w=G*16;
var A=B.offset()+w;
var y=null;
var H=a();
for(var J in I){if(f(I,J)){var F=I[J];
B.writeString(J);
B.writeLong(this.checksum(F));
B.writeLong(A);
B.writeLong(F.length);
H.write(F);
if(J=="head"){y=A;
}A+=F.length;
while(A%4){H.writeByte(0);
A++;
}}}B.write(H.get());
var E=this.checksum(B.get());
var v=2981146554-E;
B.offset(y+8);
B.writeLong(v);
return B.get();
},checksum:function(v){v=a(v);
var w=0;
while(!v.eof()){w+=v.readLong();
}return w&4294967295;
}};
function c(x){function v(z,y){this.definition=y;
this.length=y.length;
this.offset=y.offset;
this.file=z;
this.rawData=z.raw;
this.parse(z.raw);
}v.prototype.raw=function(){return this.rawData.slice(this.offset,this.length);
};
for(var w in x){if(f(x,w)){v[w]=v.prototype[w]=x[w];
}}return v;
}var g=c({parse:function(v){v.offset(this.offset);
this.version=v.readLong();
this.revision=v.readLong();
this.checkSumAdjustment=v.readLong();
this.magicNumber=v.readLong();
this.flags=v.readShort();
this.unitsPerEm=v.readShort();
this.created=v.read(8);
this.modified=v.read(8);
this.xMin=v.readShort_();
this.yMin=v.readShort_();
this.xMax=v.readShort_();
this.yMax=v.readShort_();
this.macStyle=v.readShort();
this.lowestRecPPEM=v.readShort();
this.fontDirectionHint=v.readShort_();
this.indexToLocFormat=v.readShort_();
this.glyphDataFormat=v.readShort_();
},render:function(v){var w=a();
w.writeLong(this.version);
w.writeLong(this.revision);
w.writeLong(0);
w.writeLong(this.magicNumber);
w.writeShort(this.flags);
w.writeShort(this.unitsPerEm);
w.write(this.created);
w.write(this.modified);
w.writeShort_(this.xMin);
w.writeShort_(this.yMin);
w.writeShort_(this.xMax);
w.writeShort_(this.yMax);
w.writeShort(this.macStyle);
w.writeShort(this.lowestRecPPEM);
w.writeShort_(this.fontDirectionHint);
w.writeShort_(v);
w.writeShort_(this.glyphDataFormat);
return w.get();
}});
var j=c({parse:function(v){v.offset(this.offset);
var w=this.file.head.indexToLocFormat;
if(w===0){this.offsets=v.times(this.length/2,function(){return 2*v.readShort();
});
}else{this.offsets=v.times(this.length/4,v.readLong);
}},offsetOf:function(v){return this.offsets[v];
},lengthOf:function(v){return this.offsets[v+1]-this.offsets[v];
},render:function(x){var y=a();
var w=x[x.length-1]>65535;
for(var v=0;
v<x.length;
++v){if(w){y.writeLong(x[v]);
}else{y.writeShort(x[v]/2);
}}return{format:w?1:0,table:y.get()};
}});
var h=c({parse:function(v){v.offset(this.offset);
this.version=v.readLong();
this.ascent=v.readShort_();
this.descent=v.readShort_();
this.lineGap=v.readShort_();
this.advanceWidthMax=v.readShort();
this.minLeftSideBearing=v.readShort_();
this.minRightSideBearing=v.readShort_();
this.xMaxExtent=v.readShort_();
this.caretSlopeRise=v.readShort_();
this.caretSlopeRun=v.readShort_();
this.caretOffset=v.readShort_();
v.skip(4*2);
this.metricDataFormat=v.readShort_();
this.numOfLongHorMetrics=v.readShort();
},render:function(v){var w=a();
w.writeLong(this.version);
w.writeShort_(this.ascent);
w.writeShort_(this.descent);
w.writeShort_(this.lineGap);
w.writeShort(this.advanceWidthMax);
w.writeShort_(this.minLeftSideBearing);
w.writeShort_(this.minRightSideBearing);
w.writeShort_(this.xMaxExtent);
w.writeShort_(this.caretSlopeRise);
w.writeShort_(this.caretSlopeRun);
w.writeShort_(this.caretOffset);
w.write([0,0,0,0,0,0,0,0]);
w.writeShort_(this.metricDataFormat);
w.writeShort(v.length);
return w.get();
}});
var k=c({parse:function(v){v.offset(this.offset);
this.version=v.readLong();
this.numGlyphs=v.readShort();
this.maxPoints=v.readShort();
this.maxContours=v.readShort();
this.maxComponentPoints=v.readShort();
this.maxComponentContours=v.readShort();
this.maxZones=v.readShort();
this.maxTwilightPoints=v.readShort();
this.maxStorage=v.readShort();
this.maxFunctionDefs=v.readShort();
this.maxInstructionDefs=v.readShort();
this.maxStackElements=v.readShort();
this.maxSizeOfInstructions=v.readShort();
this.maxComponentElements=v.readShort();
this.maxComponentDepth=v.readShort();
},render:function(v){var w=a();
w.writeLong(this.version);
w.writeShort(v.length);
w.writeShort(this.maxPoints);
w.writeShort(this.maxContours);
w.writeShort(this.maxComponentPoints);
w.writeShort(this.maxComponentContours);
w.writeShort(this.maxZones);
w.writeShort(this.maxTwilightPoints);
w.writeShort(this.maxStorage);
w.writeShort(this.maxFunctionDefs);
w.writeShort(this.maxInstructionDefs);
w.writeShort(this.maxStackElements);
w.writeShort(this.maxSizeOfInstructions);
w.writeShort(this.maxComponentElements);
w.writeShort(this.maxComponentDepth);
return w.get();
}});
var i=c({parse:function(v){v.offset(this.offset);
var w=this.file,x=w.hhea;
this.metrics=v.times(x.numOfLongHorMetrics,function(){return{advance:v.readShort(),lsb:v.readShort_()};
});
var y=w.maxp.numGlyphs-w.hhea.numOfLongHorMetrics;
this.leftSideBearings=v.times(y,v.readShort_);
},forGlyph:function(v){var w=this.metrics;
var x=w.length;
if(v<x){return w[v];
}return{advance:w[x-1].advance,lsb:this.leftSideBearings[v-x]};
},render:function(v){var y=a();
for(var w=0;
w<v.length;
++w){var x=this.forGlyph(v[w]);
y.writeShort(x.advance);
y.writeShort_(x.lsb);
}return y.get();
}});
var e=(function(){function y(C){this.raw=C;
}y.prototype={compound:false,render:function(){return this.raw.get();
}};
var v=1;
var z=8;
var x=32;
var B=64;
var A=128;
function w(C){this.raw=C;
var E=this.glyphIds=[];
var F=this.idOffsets=[];
while(true){var D=C.readShort();
F.push(C.offset());
E.push(C.readShort());
if(!(D&x)){break;
}C.skip(D&v?4:2);
if(D&A){C.skip(8);
}else{if(D&B){C.skip(4);
}else{if(D&z){C.skip(2);
}}}}}w.prototype={compound:true,render:function(E){var F=a(this.raw.get());
for(var C=0;
C<this.glyphIds.length;
++C){var D=this.glyphIds[C];
F.offset(this.idOffsets[C]);
F.writeShort(E[D]);
}return F.get();
}};
return c({parse:function(){this.cache={};
},glyphFor:function(F){var C=this.cache;
if(f(C,F)){return C[F];
}var H=this.file.loca;
var G=H.lengthOf(F);
if(G===0){return(C[F]=null);
}var D=this.rawData;
var J=this.offset+H.offsetOf(F);
var K=a(D.slice(J,G));
var I=K.readShort_();
var M=K.readShort_();
var O=K.readShort_();
var L=K.readShort_();
var N=K.readShort_();
var E=C[F]=I==-1?new w(K):new y(K);
E.numberOfContours=I;
E.xMin=M;
E.yMin=O;
E.xMax=L;
E.yMax=N;
return E;
},render:function(D,I,H){var J=a(),G=[];
for(var E=0;
E<I.length;
++E){var F=I[E];
var C=D[F];
G.push(J.offset());
if(C){J.write(C.render(H));
}}G.push(J.offset());
return{table:J.get(),offsets:G};
}});
}());
var l=(function(){function v(x,w){this.text=x;
this.length=x.length;
this.platformID=w.platformID;
this.platformSpecificID=w.platformSpecificID;
this.languageID=w.languageID;
this.nameID=w.nameID;
}return c({parse:function(x){x.offset(this.offset);
x.readShort();
var w=x.readShort();
var B=this.offset+x.readShort();
var z=x.times(w,function(){return{platformID:x.readShort(),platformSpecificID:x.readShort(),languageID:x.readShort(),nameID:x.readShort(),length:x.readShort(),offset:x.readShort()+B};
});
var C=this.strings={};
for(var y=0;
y<z.length;
++y){var A=z[y];
x.offset(A.offset);
var D=x.readString(A.length);
if(!C[A.nameID]){C[A.nameID]=[];
}C[A.nameID].push(new v(D,A));
}this.postscriptEntry=C[6][0];
this.postscriptName=this.postscriptEntry.text.replace(/[^\x20-\x7F]/g,"");
},render:function(A){var D=this.strings;
var C=0;
for(var w in D){if(f(D,w)){C+=D[w].length;
}}var z=a();
var E=a();
z.writeShort(0);
z.writeShort(C);
z.writeShort(6+12*C);
for(w in D){if(f(D,w)){var y=w==6?[new v(A,this.postscriptEntry)]:D[w];
for(var x=0;
x<y.length;
++x){var B=y[x];
z.writeShort(B.platformID);
z.writeShort(B.platformSpecificID);
z.writeShort(B.languageID);
z.writeShort(B.nameID);
z.writeShort(B.length);
z.writeShort(E.offset());
E.writeString(B.text);
}}}z.write(E.get());
return z.get();
}});
})();
var p=(function(){var v=".notdef .null nonmarkingreturn space exclam quotedbl numbersign dollar percent ampersand quotesingle parenleft parenright asterisk plus comma hyphen period slash zero one two three four five six seven eight nine colon semicolon less equal greater question at A B C D E F G H I J K L M N O P Q R S T U V W X Y Z bracketleft backslash bracketright asciicircum underscore grave a b c d e f g h i j k l m n o p q r s t u v w x y z braceleft bar braceright asciitilde Adieresis Aring Ccedilla Eacute Ntilde Odieresis Udieresis aacute agrave acircumflex adieresis atilde aring ccedilla eacute egrave ecircumflex edieresis iacute igrave icircumflex idieresis ntilde oacute ograve ocircumflex odieresis otilde uacute ugrave ucircumflex udieresis dagger degree cent sterling section bullet paragraph germandbls registered copyright trademark acute dieresis notequal AE Oslash infinity plusminus lessequal greaterequal yen mu partialdiff summation product pi integral ordfeminine ordmasculine Omega ae oslash questiondown exclamdown logicalnot radical florin approxequal Delta guillemotleft guillemotright ellipsis nonbreakingspace Agrave Atilde Otilde OE oe endash emdash quotedblleft quotedblright quoteleft quoteright divide lozenge ydieresis Ydieresis fraction currency guilsinglleft guilsinglright fi fl daggerdbl periodcentered quotesinglbase quotedblbase perthousand Acircumflex Ecircumflex Aacute Edieresis Egrave Iacute Icircumflex Idieresis Igrave Oacute Ocircumflex apple Ograve Uacute Ucircumflex Ugrave dotlessi circumflex tilde macron breve dotaccent ring cedilla hungarumlaut ogonek caron Lslash lslash Scaron scaron Zcaron zcaron brokenbar Eth eth Yacute yacute Thorn thorn minus multiply onesuperior twosuperior threesuperior onehalf onequarter threequarters franc Gbreve gbreve Idotaccent Scedilla scedilla Cacute cacute Ccaron ccaron dcroat".split(/\s+/g);
return c({parse:function(w){w.offset(this.offset);
this.format=w.readLong();
this.italicAngle=w.readFixed_();
this.underlinePosition=w.readShort_();
this.underlineThickness=w.readShort_();
this.isFixedPitch=w.readLong();
this.minMemType42=w.readLong();
this.maxMemType42=w.readLong();
this.minMemType1=w.readLong();
this.maxMemType1=w.readLong();
var y;
switch(this.format){case 65536:case 196608:break;
case 131072:y=w.readShort();
this.glyphNameIndex=w.times(y,w.readShort);
this.names=[];
var x=this.offset+this.length;
while(w.offset()<x){this.names.push(w.readString(w.readByte()));
}break;
case 151552:y=w.readShort();
this.offsets=w.read(y);
break;
case 262144:this.map=w.times(this.file.maxp.numGlyphs,w.readShort);
break;
}},glyphFor:function(w){switch(this.format){case 65536:return v[w]||".notdef";
case 131072:var x=this.glyphNameIndex[w];
if(x<v.length){return v[x];
}return this.names[x-v.length]||".notdef";
case 151552:case 196608:return".notdef";
case 262144:return this.map[w]||65535;
}},render:function(A){if(this.format==196608){return this.raw();
}var B=a(this.rawData.slice(this.offset,32));
B.writeLong(131072);
B.offset(32);
var z=[];
var D=[];
for(var w=0;
w<A.length;
++w){var x=A[w];
var C=this.glyphFor(x);
var y=v.indexOf(C);
if(y>=0){z.push(y);
}else{z.push(v.length+D.length);
D.push(C);
}}B.writeShort(A.length);
for(w=0;
w<z.length;
++w){B.writeShort(z[w]);
}for(w=0;
w<D.length;
++w){B.writeByte(D[w].length);
B.writeString(D[w]);
}return B.get();
}});
})();
var b=(function(){function v(x,y){var z=this;
z.platformID=x.readShort();
z.platformSpecificID=x.readShort();
z.offset=y+x.readLong();
x.saveExcursion(function(){x.offset(z.offset);
z.format=x.readShort();
z.length=x.readShort();
z.language=x.readShort();
z.isUnicode=(z.platformID==3&&z.platformSpecificID==1&&z.format==4)||(z.platformID===0&&z.format==4);
z.codeMap={};
switch(z.format){case 0:for(var G=0;
G<256;
++G){z.codeMap[G]=x.readByte();
}break;
case 4:var K=x.readShort()/2;
x.skip(6);
var D=x.times(K,x.readShort);
x.skip(2);
var M=x.times(K,x.readShort);
var H=x.times(K,x.readShort_);
var I=x.times(K,x.readShort);
var B=(z.length+z.offset-x.offset())/2;
var F=x.times(B,x.readShort);
for(G=0;
G<K;
++G){var L=M[G],C=D[G];
for(var A=L;
A<=C;
++A){var E;
if(I[G]===0){E=A+H[G];
}else{var J=I[G]/2-(K-G)+(A-L);
E=F[J]||0;
if(E!==0){E+=H[G];
}}z.codeMap[A]=E&65535;
}}}});
}function w(K,M){var y=q(K);
var U=[];
var D=[];
var J=null;
var B=null;
function L(W){return M[K[W]];
}for(var H=0;
H<y.length;
++H){var x=y[H];
var F=L(x);
var z=F-x;
if(J==null||z!==B){if(J){D.push(J);
}U.push(x);
B=z;
}J=x;
}if(J){D.push(J);
}D.push(65535);
U.push(65535);
var R=U.length;
var S=R*2;
var Q=2*Math.pow(2,Math.floor(Math.log(R)/Math.LN2));
var E=Math.log(Q/2)/Math.LN2;
var P=S-Q;
var A=[];
var O=[];
var G=[];
for(H=0;
H<R;
++H){var T=U[H];
var C=D[H];
if(T==65535){A.push(0);
O.push(0);
break;
}var V=L(T);
if(T-V>=32768){A.push(0);
O.push(2*(G.length+R-H));
for(var I=T;
I<=C;
++I){G.push(L(I));
}}else{A.push(V-T);
O.push(0);
}}var N=a();
N.writeShort(3);
N.writeShort(1);
N.writeLong(12);
N.writeShort(4);
N.writeShort(16+R*8+G.length*2);
N.writeShort(0);
N.writeShort(S);
N.writeShort(Q);
N.writeShort(E);
N.writeShort(P);
D.forEach(N.writeShort);
N.writeShort(0);
U.forEach(N.writeShort);
A.forEach(N.writeShort_);
O.forEach(N.writeShort);
G.forEach(N.writeShort);
return N.get();
}return c({parse:function(x){var z=this;
var y=z.offset;
x.offset(y);
z.version=x.readShort();
var A=x.readShort();
z.unicodeEntry=null;
z.tables=x.times(A,function(){var B=new v(x,y);
if(B.isUnicode){z.unicodeEntry=B;
}return B;
});
},render:function(x,y){var z=a();
z.writeShort(0);
z.writeShort(1);
z.write(w(x,y));
return z.get();
},getUnicodeEntry:function(){if(!this.unicodeEntry){throw new Error("Font doesn't have an Unicode encoding");
}return this.unicodeEntry;
}});
})();
var n=c({parse:function(v){v.offset(this.offset);
this.version=v.readShort();
this.averageCharWidth=v.readShort_();
this.weightClass=v.readShort();
this.widthClass=v.readShort();
this.type=v.readShort();
this.ySubscriptXSize=v.readShort_();
this.ySubscriptYSize=v.readShort_();
this.ySubscriptXOffset=v.readShort_();
this.ySubscriptYOffset=v.readShort_();
this.ySuperscriptXSize=v.readShort_();
this.ySuperscriptYSize=v.readShort_();
this.ySuperscriptXOffset=v.readShort_();
this.ySuperscriptYOffset=v.readShort_();
this.yStrikeoutSize=v.readShort_();
this.yStrikeoutPosition=v.readShort_();
this.familyClass=v.readShort_();
this.panose=v.times(10,v.readByte);
this.charRange=v.times(4,v.readLong);
this.vendorID=v.readString(4);
this.selection=v.readShort();
this.firstCharIndex=v.readShort();
this.lastCharIndex=v.readShort();
if(this.version>0){this.ascent=v.readShort_();
this.descent=v.readShort_();
this.lineGap=v.readShort_();
this.winAscent=v.readShort();
this.winDescent=v.readShort();
this.codePageRange=v.times(2,v.readLong);
if(this.version>1){this.xHeight=v.readShort();
this.capHeight=v.readShort();
this.defaultChar=v.readShort();
this.breakChar=v.readShort();
this.maxContext=v.readShort();
}}},render:function(){return this.raw();
}});
var s=100000;
function m(){var x="",w=s+"";
for(var v=0;
v<w.length;
++v){x+=String.fromCharCode(w.charCodeAt(v)-48+65);
}++s;
return x;
}function r(v){this.font=v;
this.subset={};
this.unicodes={};
this.ogid2ngid={0:0};
this.ngid2ogid={0:0};
this.ncid2ogid={};
this.next=this.firstChar=1;
this.nextGid=1;
this.psName=m()+"+"+this.font.psName;
}r.prototype={use:function(v){var w;
if(typeof v=="string"){var A="";
for(var x=0;
x<v.length;
++x){w=this.use(v.charCodeAt(x));
A+=String.fromCharCode(w);
}return A;
}w=this.unicodes[v];
if(!w){w=this.next++;
this.subset[w]=v;
this.unicodes[v]=w;
var z=this.font.cmap.getUnicodeEntry().codeMap[v];
if(z){this.ncid2ogid[w]=z;
if(this.ogid2ngid[z]==null){var y=this.nextGid++;
this.ogid2ngid[z]=y;
this.ngid2ogid[y]=z;
}}}return w;
},encodeText:function(v){return this.use(v);
},glyphIds:function(){return q(this.ogid2ngid);
},glyphsFor:function(w,z){if(!z){z={};
}for(var x=0;
x<w.length;
++x){var y=w[x];
if(!z[y]){var v=z[y]=this.font.glyf.glyphFor(y);
if(v&&v.compound){this.glyphsFor(v.glyphIds,z);
}}}return z;
},render:function(){var x=this.glyphsFor(this.glyphIds());
for(var B in x){if(f(x,B)){B=parseInt(B,10);
if(this.ogid2ngid[B]==null){var z=this.nextGid++;
this.ogid2ngid[B]=z;
this.ngid2ogid[z]=B;
}}}var A=q(this.ngid2ogid);
var C=A.map(function(E){return this.ngid2ogid[E];
},this);
var v=this.font;
var w=v.glyf.render(x,C,this.ogid2ngid);
var y=v.loca.render(w.offsets);
this.lastChar=this.next-1;
var D={cmap:b.render(this.ncid2ogid,this.ogid2ngid),glyf:w.table,loca:y.table,hmtx:v.hmtx.render(C),hhea:v.hhea.render(C),maxp:v.maxp.render(C),post:v.post.render(C),name:v.name.render(this.psName),head:v.head.render(y.format),"OS/2":v.os2.render()};
return this.font.directory.render(D);
},cidToGidMap:function(){var z=a(),w=0;
for(var v=this.firstChar;
v<this.next;
++v){while(w<v){z.writeShort(0);
w++;
}var y=this.ncid2ogid[v];
if(y){var x=this.ogid2ngid[y];
z.writeShort(x);
}else{z.writeShort(0);
}w++;
}return z.get();
}};
function t(A,x){var B=this;
var v=B.contents=a(A);
if(v.readString(4)=="ttcf"){if(!x){throw new Error("Must specify a name for TTC files");
}v.readLong();
var y=v.readLong();
for(var w=0;
w<y;
++w){var z=v.readLong();
v.saveExcursion(function(){v.offset(z);
B.parse();
});
if(B.psName==x){return;
}}throw new Error("Font "+x+" not found in collection");
}else{v.offset(0);
B.parse();
}}t.prototype={parse:function(){var v=this.directory=new d(this.contents);
this.head=v.readTable("head",g);
this.loca=v.readTable("loca",j);
this.hhea=v.readTable("hhea",h);
this.maxp=v.readTable("maxp",k);
this.hmtx=v.readTable("hmtx",i);
this.glyf=v.readTable("glyf",e);
this.name=v.readTable("name",l);
this.post=v.readTable("post",p);
this.cmap=v.readTable("cmap",b);
this.os2=v.readTable("OS/2",n);
this.psName=this.name.postscriptName;
this.ascent=this.os2.ascent||this.hhea.ascent;
this.descent=this.os2.descent||this.hhea.descent;
this.lineGap=this.os2.lineGap||this.hhea.lineGap;
this.scale=1000/this.head.unitsPerEm;
},widthOfGlyph:function(v){return this.hmtx.forGlyph(v).advance*this.scale;
},makeSubset:function(){return new r(this);
}};
o.TTFFont=t;
})(window);
})();
(function(){(function(p,a){var j=p.drawing;
var o=p.geometry;
var D=p.pdf.TEXT_RENDERING_MODE;
var c={dash:[4],dashDot:[4,2,1,2],dot:[1,2],longDash:[8,2],longDashDot:[8,2,1,2],longDashDotDot:[8,2,1,2,1,2],solid:[]};
var q={butt:0,round:1,square:2};
var r={miter:0,round:1,bevel:2};
function x(L,G){var J=[],M=[],O=L.options;
function K(R,P,Q){if(!Q){Q=O;
}if(Q.pdf&&Q.pdf[R]!=null){return Q.pdf[R];
}return P;
}var N=K("multiPage");
L.traverse(function(P){d({Image:function(Q){if(M.indexOf(Q.src())<0){M.push(Q.src());
}},Text:function(Q){var R=p.pdf.parseFontDef(Q.options.font);
var S=p.pdf.getFontURL(R);
if(J.indexOf(S)<0){J.push(S);
}}},P);
});
function I(){if(--H>0){return;
}var Q=new (p.pdf.Document)({producer:K("producer"),title:K("title"),author:K("author"),subject:K("subject"),keywords:K("keywords"),creator:K("creator"),date:K("date")});
function P(T){var U=T.options;
var Z=v(T);
var S=Z.bbox;
T=Z.root;
var X=K("paperSize",K("paperSize","auto"),U),R=false;
if(X=="auto"){if(S){var Y=S.getSize();
X=[Y.width,Y.height];
R=true;
var V=S.getOrigin();
Z=new j.Group();
Z.transform(new o.Matrix(1,0,0,1,-V.x,-V.y));
Z.append(T);
T=Z;
}else{X="A4";
}}var W;
W=Q.addPage({paperSize:X,margin:K("margin",K("margin"),U),addMargin:R,landscape:K("landscape",K("landscape",false),U)});
g(T,W,Q);
}if(N){L.children.forEach(P);
}else{P(L);
}G(Q.render(),Q);
}var H=2;
p.pdf.loadFonts(J,I);
p.pdf.loadImages(M,I);
}function F(H,G){x(H,function(I){G("data:application/pdf;base64,"+I.base64());
});
}function E(H,G){x(H,function(I){G(new Blob([I.get()],{type:"application/pdf"}));
});
}function y(I,H,J,G){if(window.Blob&&!p.support.browser.safari){E(I,function(K){p.saveAs({dataURI:K,fileName:H});
if(G){G(K);
}});
}else{F(I,function(K){p.saveAs({dataURI:K,fileName:H,proxyURL:J});
if(G){G(K);
}});
}}function d(I,G){var H=I[G.nodeType];
if(H){return H.call.apply(H,arguments);
}return G;
}function g(G,J,K){if(G.options._pdfDebug){J.comment("BEGIN: "+G.options._pdfDebug);
}var L=G.transform();
var I=G.opacity();
J.save();
if(I!=null&&I<1){J.setOpacity(I);
}B(G,J,K);
A(G,J,K);
z(G,J,K);
if(L){var H=L.matrix();
J.transform(H.a,H.b,H.c,H.d,H.e,H.f);
}d({Path:l,MultiPath:k,Circle:f,Arc:e,Text:m,Image:i,Group:h},G,J,K);
J.restore();
if(G.options._pdfDebug){J.comment("END: "+G.options._pdfDebug);
}}function B(I,M){var N=I.stroke&&I.stroke();
if(!N){return;
}var G=N.color;
if(G){G=w(G);
if(G==null){return;
}M.setStrokeColor(G.r,G.g,G.b);
if(G.a!=1){M.setStrokeOpacity(G.a);
}}var O=N.width;
if(O!=null){if(O===0){return;
}M.setLineWidth(O);
}var H=N.dashType;
if(H){M.setDashPattern(c[H],0);
}var J=N.lineCap;
if(J){M.setLineCap(q[J]);
}var K=N.lineJoin;
if(K){M.setLineJoin(r[K]);
}var L=N.opacity;
if(L!=null){M.setStrokeOpacity(L);
}}function A(H,K){var I=H.fill&&H.fill();
if(!I){return;
}if(I instanceof j.Gradient){return;
}var G=I.color;
if(G){G=w(G);
if(G==null){return;
}K.setFillColor(G.r,G.g,G.b);
if(G.a!=1){K.setFillOpacity(G.a);
}}var J=I.opacity;
if(J!=null){K.setFillOpacity(J);
}}function z(H,I,J){var G=H.clip();
if(G){b(G,I,J);
I.clip();
}}function C(G){return(G&&(G instanceof j.Gradient||(G.color&&!/^(none|transparent)$/i.test(G.color)&&(G.width==null||G.width>0)&&(G.opacity==null||G.opacity>0))));
}function u(H,M,N,Q){var J=H.fill();
if(J instanceof j.Gradient){if(Q){M.clipStroke();
}else{M.clip();
}var L=J instanceof j.RadialGradient;
var P,I;
if(L){P={x:J.center().x,y:J.center().y,r:0};
I={x:J.center().x,y:J.center().y,r:J.radius()};
}else{P={x:J.start().x,y:J.start().y};
I={x:J.end().x,y:J.end().y};
}var K={type:L?"radial":"linear",start:P,end:I,userSpace:J.userSpace(),stops:J.stops.elements().map(function(U){var T=U.offset();
if(/%$/.test(T)){T=parseFloat(T)/100;
}else{T=parseFloat(T);
}var S=w(U.color());
S.a*=U.opacity();
return{offset:T,color:S};
})};
var G=H.rawBBox();
var R=G.topLeft(),O=G.getSize();
G={left:R.x,top:R.y,width:O.width,height:O.height};
M.gradient(K,G);
return true;
}}function t(G,H,I){if(C(G.fill())&&C(G.stroke())){if(!u(G,H,I,true)){H.fillStroke();
}}else{if(C(G.fill())){if(!u(G,H,I,false)){H.fill();
}}else{if(C(G.stroke())){H.stroke();
}else{H.nop();
}}}}function s(K,J){var L=K.segments;
if(L.length==4&&K.options.closed){var G=[];
for(var H=0;
H<L.length;
++H){if(L[H].controlIn()){return false;
}G[H]=L[H].anchor();
}var I=(G[0].y==G[1].y&&G[1].x==G[2].x&&G[2].y==G[3].y&&G[3].x==G[0].x)||(G[0].x==G[1].x&&G[1].y==G[2].y&&G[2].x==G[3].x&&G[3].y==G[0].y);
if(I){J.rect(G[0].x,G[0].y,G[2].x-G[0].x,G[2].y-G[0].y);
return true;
}}}function b(I,K,L){var P=I.segments;
if(P.length===0){return;
}if(!s(I,K,L)){for(var M,J=0;
J<P.length;
++J){var O=P[J];
var G=O.anchor();
if(!M){K.moveTo(G.x,G.y);
}else{var N=M.controlOut();
var H=O.controlIn();
if(N&&H){K.bezier(N.x,N.y,H.x,H.y,G.x,G.y);
}else{K.lineTo(G.x,G.y);
}}M=O;
}if(I.options.closed){K.close();
}}}function l(G,H,I){b(G,H,I);
t(G,H,I);
}function k(G,I,K){var J=G.paths;
for(var H=0;
H<J.length;
++H){b(J[H],I,K);
}t(G,I,K);
}function f(G,I,J){var H=G.geometry();
I.circle(H.center.x,H.center.y,H.radius);
t(G,I,J);
}function e(G,I,J){var K=G.geometry().curvePoints();
I.moveTo(K[0].x,K[0].y);
for(var H=1;
H<K.length;
){I.bezier(K[H].x,K[H++].y,K[H].x,K[H++].y,K[H].x,K[H++].y);
}t(G,I,J);
}function m(G,I){var K=p.pdf.parseFontDef(G.options.font);
var J=G._position;
var H;
if(G.fill()&&G.stroke()){H=D.fillAndStroke;
}else{if(G.fill()){H=D.fill;
}else{if(G.stroke()){H=D.stroke;
}}}I.transform(1,0,0,-1,J.x,J.y+K.fontSize);
I.beginText();
I.setFont(p.pdf.getFontURL(K),K.fontSize);
I.setTextRenderingMode(H);
I.showText(G.content(),G._pdfRect?G._pdfRect.width():null);
I.endText();
}function h(H,J,K){if(H._pdfLink){J.addLink(H._pdfLink.url,H._pdfLink);
}var G=H.children;
for(var I=0;
I<G.length;
++I){g(G[I],J,K);
}}function i(G,H){var L=G.src();
if(!L){return;
}var I=G.rect();
var K=I.getOrigin();
var J=I.getSize();
H.transform(J.width,0,0,-J.height,K.x,K.y+J.height);
H.drawImage(L);
}function n(H,J){var G=a.Deferred();
for(var I in J){H.options.set("pdf."+I,J[I]);
}j.pdf.toDataURL(H,G.resolve);
return G.promise();
}function w(H){var G=p.parseColor(H,true);
return G?G.toRGB():null;
}function v(O){var I=false;
var L=o.Matrix.unit();
var J=null;
var H;
do{H=false;
O=M(O);
}while(O&&H);
return{root:O,bbox:J};
function G(R){H=true;
return R;
}function P(R){return(R.visible()&&R.opacity()>0&&(C(R.fill())||C(R.stroke())));
}function N(R){var S=[];
for(var U=0;
U<R.length;
++U){var T=M(R[U]);
if(T!=null){S.push(T);
}}return S;
}function Q(V,S){var T=I;
var U=L;
if(V.transform()){L=L.multiplyCopy(V.transform().matrix());
}var R=V.clip();
if(R){R=R.bbox();
if(R){R=R.bbox(L);
I=I?o.Rect.intersect(I,R):R;
}}try{return S();
}finally{I=T;
L=U;
}}function K(S){if(I==null){return false;
}var R=S.rawBBox().bbox(L);
if(I&&R){R=o.Rect.intersect(R,I);
}return R;
}function M(R){return Q(R,function(){if(!(R instanceof j.Group||R instanceof j.MultiPath)){var S=K(R);
if(!S){return G(null);
}J=J?o.Rect.union(J,S):S;
}return d({Path:function(T){if(T.segments.length===0||!P(T)){return G(null);
}return T;
},MultiPath:function(U){if(!P(U)){return G(null);
}var T=new j.MultiPath(U.options);
T.paths=N(U.paths);
if(T.paths.length===0){return G(null);
}return T;
},Circle:function(T){if(!P(T)){return G(null);
}return T;
},Arc:function(T){if(!P(T)){return G(null);
}return T;
},Text:function(T){if(!/\S/.test(T.content())||!P(T)){return G(null);
}return T;
},Image:function(T){if(!(T.visible()&&T.opacity()>0)){return G(null);
}return T;
},Group:function(U){var T=new j.Group(U.options);
T.children=N(U.children);
T._pdfLink=U._pdfLink;
if(U!==O&&T.children.length===0&&!U._pdfLink){return G(null);
}return T;
}},R);
});
}}p.deepExtend(j,{exportPDF:n,pdf:{toDataURL:F,toBlob:E,saveAs:y,toStream:x}});
})(window.kendo,window.kendo.jQuery);
})();
(function(){(function(b,a){b.PDFMixin={extend:function(c){c.events.push("pdfExport");
c.options.pdf=this.options;
c.saveAsPDF=this.saveAsPDF;
c._drawPDF=this._drawPDF;
c._drawPDFShadow=this._drawPDFShadow;
},options:{fileName:"Export.pdf",proxyURL:"",paperSize:"auto",allPages:false,landscape:false,margin:null,title:null,author:null,subject:null,keywords:null,creator:"Kendo UI PDF Generator",date:null},saveAsPDF:function(){var e=new a.Deferred();
var f=e.promise();
var c={promise:f};
if(this.trigger("pdfExport",c)){return;
}var d=this.options.pdf;
d.multiPage=d.allPages;
this._drawPDF(e).then(function(g){return b.drawing.exportPDF(g,d);
}).done(function(g){b.saveAs({dataURI:g,fileName:d.fileName,proxyURL:d.proxyURL,forceProxy:d.forceProxy,proxyTarget:d.proxyTarget});
e.resolve();
}).fail(function(g){e.reject(g);
});
return f;
},_drawPDF:function(c){var d=new a.Deferred();
b.drawing.drawDOM(this.wrapper).done(function(f){var e={page:f,pageNumber:1,progress:1,totalPages:1};
c.notify(e);
d.resolve(e.page);
}).fail(function(e){d.reject(e);
});
return d;
},_drawPDFShadow:function(d){d=d||{};
var f=this.wrapper;
var e=a("<div class='k-pdf-export-shadow'>");
if(d.width){e.css({width:d.width,overflow:"visible"});
}f.before(e);
e.append(d.content||f.clone(true,true));
var c=a.Deferred();
setTimeout(function(){var g=b.drawing.drawDOM(e);
g.always(function(){e.remove();
}).then(function(){c.resolve.apply(c,arguments);
}).fail(function(){c.reject.apply(c,arguments);
}).progress(function(){c.progress.apply(c,arguments);
});
},15);
return c.promise();
}};
})(kendo,window.kendo.jQuery);
})();
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
