(function(b,a){a(["./kendo.core"],b);
})(function(){(function(){(function(a,J){var t=window.kendo,I=t.ui,L=I.Widget,F=t.support,r=t.getOffset,y="open",k="close",n="deactivate",c="activate",j="center",u="left",C="right",G="top",i="bottom",b="absolute",s="hidden",h="body",v="location",A="position",K="visible",p="effects",d="k-state-active",e="k-state-border",f=/k-state-border-(\w+)/,g=".k-picker-wrap, .k-dropdown-wrap, .k-link",w="down",o=a(document.documentElement),M=a(window),D="scroll",B="resize scroll",m=F.transitions.css,H=m+"transform",q=a.extend,x=".kendoPopup",E=["font-size","font-family","font-stretch","font-style","font-weight","line-height"];
function l(N,O){return N===O||a.contains(N,O);
}var z=L.extend({init:function(N,O){var Q=this,P;
O=O||{};
if(O.isRtl){O.origin=O.origin||i+" "+C;
O.position=O.position||G+" "+C;
}L.fn.init.call(Q,N,O);
N=Q.element;
O=Q.options;
Q.collisions=O.collision?O.collision.split(" "):[];
Q.downEvent=t.applyEventMap(w,t.guid());
if(Q.collisions.length===1){Q.collisions.push(Q.collisions[0]);
}P=a(Q.options.anchor).closest(".k-popup,.k-group").filter(":not([class^=km-])");
O.appendTo=a(a(O.appendTo)[0]||P[0]||h);
Q.element.hide().addClass("k-popup k-group k-reset").toggleClass("k-rtl",!!O.isRtl).css({position:b}).appendTo(O.appendTo).on("mouseenter"+x,function(){Q._hovered=true;
}).on("mouseleave"+x,function(){Q._hovered=false;
});
Q.wrapper=a();
if(O.animation===false){O.animation={open:{effects:{}},close:{hide:true,effects:{}}};
}q(O.animation.open,{complete:function(){Q.wrapper.css({overflow:K});
Q._activated=true;
Q._trigger(c);
}});
q(O.animation.close,{complete:function(){Q._animationClose();
}});
Q._mousedownProxy=function(R){Q._mousedown(R);
};
Q._resizeProxy=function(R){Q._resize(R);
};
if(O.toggleTarget){a(O.toggleTarget).on(O.toggleEvent+x,a.proxy(Q.toggle,Q));
}},events:[y,c,k,n],options:{name:"Popup",toggleEvent:"click",origin:i+" "+u,position:G+" "+u,anchor:h,appendTo:null,collision:"flip fit",viewport:window,copyAnchorStyles:true,autosize:false,modal:false,adjustSize:{width:0,height:0},animation:{open:{effects:"slideIn:down",transition:true,duration:200},close:{duration:100,hide:true}}},_animationClose:function(){var S=this,R=S.options;
S.wrapper.hide();
var Q=S.wrapper.data(v),N=a(R.anchor),P,O;
if(Q){S.wrapper.css(Q);
}if(R.anchor!=h){P=((N.attr("class")||"").match(f)||["","down"])[1];
O=e+"-"+P;
N.removeClass(O).children(g).removeClass(d).removeClass(O);
S.element.removeClass(e+"-"+t.directions[P].reverse);
}S._closing=false;
S._trigger(n);
},destroy:function(){var Q=this,O=Q.options,N=Q.element.off(x),P;
L.fn.destroy.call(Q);
if(O.toggleTarget){a(O.toggleTarget).off(x);
}if(!O.modal){o.unbind(Q.downEvent,Q._mousedownProxy);
Q._toggleResize(false);
}t.destroy(Q.element.children());
N.removeData();
if(O.appendTo[0]===document.body){P=N.parent(".k-animation-container");
if(P[0]){P.remove();
}else{N.remove();
}}},open:function(X,Y){var V=this,S={isFixed:!isNaN(parseInt(Y,10)),x:X,y:Y},R=V.element,U=V.options,Q="down",O,W,N=a(U.anchor),T=R[0]&&R.hasClass("km-widget");
if(!V.visible()){if(U.copyAnchorStyles){if(T&&E[0]=="font-size"){E.shift();
}R.css(t.getComputedStyles(N[0],E));
}if(R.data("animating")||V._trigger(y)){return;
}V._activated=false;
if(!U.modal){o.unbind(V.downEvent,V._mousedownProxy).bind(V.downEvent,V._mousedownProxy);
if(!(F.mobileOS.ios||F.mobileOS.android)){V._toggleResize(false);
V._toggleResize(true);
}}V.wrapper=W=t.wrap(R,U.autosize).css({overflow:s,display:"block",position:b});
if(F.mobileOS.android){W.css(H,"translatez(0)");
}W.css(A);
if(a(U.appendTo)[0]==document.body){W.css(G,"-10000px");
}O=q(true,{},U.animation.open);
V.flipped=V._position(S);
O.effects=t.parseEffects(O.effects,V.flipped);
Q=O.effects.slideIn?O.effects.slideIn.direction:Q;
if(U.anchor!=h){var P=e+"-"+Q;
R.addClass(e+"-"+t.directions[Q].reverse);
N.addClass(P).children(g).addClass(d).addClass(P);
}R.data(p,O.effects).kendoStop(true).kendoAnimate(O);
}},position:function(){if(this.visible()){this._position();
}},toggle:function(){var N=this;
N[N.visible()?k:y]();
},visible:function(){return this.element.is(":"+K);
},close:function(R){var S=this,Q=S.options,T,N,P,O;
if(S.visible()){T=(S.wrapper[0]?S.wrapper:t.wrap(S.element).hide());
S._toggleResize(false);
if(S._closing||S._trigger(k)){S._toggleResize(true);
return;
}S.element.find(".k-popup").each(function(){var V=a(this),U=V.data("kendoPopup");
if(U){U.close(R);
}});
o.unbind(S.downEvent,S._mousedownProxy);
if(R){N={hide:true,effects:{}};
}else{N=q(true,{},Q.animation.close);
P=S.element.data(p);
O=N.effects;
if(!O&&!t.size(O)&&P&&t.size(P)){N.effects=P;
N.reverse=true;
}S._closing=true;
}S.element.kendoStop(true);
T.css({overflow:s});
S.element.kendoAnimate(N);
}},_trigger:function(N){return this.trigger(N,{type:N});
},_resize:function(N){var O=this;
if(N.type==="resize"){clearTimeout(O._resizeTimeout);
O._resizeTimeout=setTimeout(function(){O._position();
O._resizeTimeout=null;
},50);
}else{if(!O._hovered||(O._activated&&O.element.hasClass("k-list-container"))){O.close();
}}},_toggleResize:function(O){var N=O?"on":"off";
this._scrollableParents()[N](D,this._resizeProxy);
M[N](B,this._resizeProxy);
},_mousedown:function(P){var U=this,O=U.element[0],R=U.options,N=a(R.anchor)[0],V=R.toggleTarget,T=t.eventTarget(P),S=a(T).closest(".k-popup"),Q=S.parent().parent(".km-shim").length;
S=S[0];
if(!Q&&S&&S!==U.element[0]){return;
}if(a(P.target).closest("a").data("rel")==="popover"){return;
}if(!l(O,T)&&!l(N,T)&&!(V&&l(a(V)[0],T))){U.close();
}},_fit:function(O,P,Q){var N=0;
if(O+P>Q){N=Q-(O+P);
}if(O<0){N=-O;
}return N;
},_flip:function(P,T,N,U,Q,S,O){var R=0;
O=O||T;
if(S!==Q&&S!==j&&Q!==j){if(P+O>U){R+=-(N+T);
}if(P+R<0){R+=N+T;
}}return R;
},_scrollableParents:function(){return a(this.options.anchor).parentsUntil("body").filter(function(O,N){return t.isScrollable(N);
});
},_position:function(T){var ai=this,S=ai.element,an=ai.wrapper,ab=ai.options,aj=a(ab.viewport),al=aj.offset(),O=a(ab.anchor),ac=ab.origin.toLowerCase().split(" "),ag=ab.position.toLowerCase().split(" "),Q=ai.collisions,ap=F.zoomLevel(),ah,ad,ae,ao=10002,W=!!((aj[0]==window)&&window.innerWidth&&(ap<=1.02)),V=0,R=document.documentElement,X,am,ak;
am=W?window.innerWidth:aj.width();
ak=W?window.innerHeight:aj.height();
if(W&&R.scrollHeight-R.clientHeight>0){am-=t.support.scrollbar();
}ah=O.parents().filter(an.siblings());
if(ah[0]){ae=Math.max(Number(ah.css("zIndex")),0);
if(ae){ao=ae+10;
}else{ad=O.parentsUntil(ah);
for(X=ad.length;
V<X;
V++){ae=Number(a(ad[V]).css("zIndex"));
if(ae&&ao<ae){ao=ae+10;
}}}}an.css("zIndex",ao);
if(T&&T.isFixed){an.css({left:T.x,top:T.y});
}else{an.css(ai._align(ac,ag));
}var af=r(an,A,O[0]===an.offsetParent()[0]),Z=r(an),P=O.offsetParent().parent(".k-animation-container,.k-popup,.k-group");
if(P.length){af=r(an,A,true);
Z=r(an);
}if(aj[0]===window){Z.top-=(window.pageYOffset||document.documentElement.scrollTop||0);
Z.left-=(window.pageXOffset||document.documentElement.scrollLeft||0);
}else{Z.top-=al.top;
Z.left-=al.left;
}if(!ai.wrapper.data(v)){an.data(v,q({},af));
}var aa=q({},Z),Y=q({},af),N=ab.adjustSize;
if(Q[0]==="fit"){Y.top+=ai._fit(aa.top,an.outerHeight()+N.height,ak/ap);
}if(Q[1]==="fit"){Y.left+=ai._fit(aa.left,an.outerWidth()+N.width,am/ap);
}var U=q({},Y);
if(Q[0]==="flip"){Y.top+=ai._flip(aa.top,S.outerHeight(),O.outerHeight(),ak/ap,ac[0],ag[0],an.outerHeight());
}if(Q[1]==="flip"){Y.left+=ai._flip(aa.left,S.outerWidth(),O.outerWidth(),am/ap,ac[1],ag[1],an.outerWidth());
}S.css(A,b);
an.css(Y);
return(Y.left!=U.left||Y.top!=U.top);
},_align:function(Y,Z){var ab=this,T=ab.wrapper,N=a(ab.options.anchor),ad=Y[0],V=Y[1],ae=Z[0],W=Z[1],P=r(N),R=a(ab.options.appendTo),S,af=T.outerWidth(),U=T.outerHeight(),Q=N.outerWidth(),O=N.outerHeight(),ac=P.top,X=P.left,aa=Math.round;
if(R[0]!=document.body){S=r(R);
ac-=S.top;
X-=S.left;
}if(ad===i){ac+=O;
}if(ad===j){ac+=aa(O/2);
}if(ae===i){ac-=U;
}if(ae===j){ac-=aa(U/2);
}if(V===C){X+=Q;
}if(V===j){X+=aa(Q/2);
}if(W===C){X-=af;
}if(W===j){X-=aa(af/2);
}return{top:ac,left:X};
}});
I.plugin(z);
})(window.kendo.jQuery);
})();
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
