(function(b,a){a(["./kendo.core","./kendo.draganddrop"],b);
})(function(){(function(){(function(a,l){var e=window.kendo,k=e.ui,n=k.Widget,f=a.proxy,d=e.isFunction,b=a.extend,c="horizontal",m="vertical",j="start",h="resize",i="resizeend";
var g=n.extend({init:function(o,p){var q=this;
n.fn.init.call(q,o,p);
q.orientation=q.options.orientation.toLowerCase()!=m?c:m;
q._positionMouse=q.orientation==c?"x":"y";
q._position=q.orientation==c?"left":"top";
q._sizingDom=q.orientation==c?"outerWidth":"outerHeight";
q.draggable=new k.Draggable(o,{distance:1,filter:p.handle,drag:f(q._resize,q),dragcancel:f(q._cancel,q),dragstart:f(q._start,q),dragend:f(q._stop,q)});
q.userEvents=q.draggable.userEvents;
},events:[h,i,j],options:{name:"Resizable",orientation:c},resize:function(){},_max:function(o){var r=this,p=r.hint?r.hint[r._sizingDom]():0,q=r.options.max;
return d(q)?q(o):q!==l?(r._initialElementPosition+q)-p:q;
},_min:function(o){var q=this,p=q.options.min;
return d(p)?p(o):p!==l?q._initialElementPosition+p:p;
},_start:function(o){var r=this,q=r.options.hint,p=a(o.currentTarget);
r._initialElementPosition=p.position()[r._position];
r._initialMousePosition=o[r._positionMouse].startLocation;
if(q){r.hint=d(q)?a(q(p)):q;
r.hint.css({position:"absolute"}).css(r._position,r._initialElementPosition).appendTo(r.element);
}r.trigger(j,o);
r._maxPosition=r._max(o);
r._minPosition=r._min(o);
a(document.body).css("cursor",p.css("cursor"));
},_resize:function(p){var t=this,q=t._maxPosition,r=t._minPosition,o=t._initialElementPosition+(p[t._positionMouse].location-t._initialMousePosition),s;
s=r!==l?Math.max(r,o):o;
t.position=s=q!==l?Math.min(q,s):s;
if(t.hint){t.hint.toggleClass(t.options.invalidClass||"",s==q||s==r).css(t._position,s);
}t.resizing=true;
t.trigger(h,b(p,{position:s}));
},_stop:function(o){var p=this;
if(p.hint){p.hint.remove();
}p.resizing=false;
p.trigger(i,b(o,{position:p.position}));
a(document.body).css("cursor","");
},_cancel:function(o){var p=this;
if(p.hint){p.position=l;
p.hint.css(p._position,p._initialElementPosition);
p._stop(o);
}},destroy:function(){var o=this;
n.fn.destroy.call(o);
if(o.draggable){o.draggable.destroy();
}},press:function(p){if(!p){return;
}var o=p.position(),q=this;
q.userEvents.press(o.left,o.top,p[0]);
q.targetPosition=o;
q.target=p;
},move:function(p){var s=this,q=s._position,r=s.targetPosition,o=s.position;
if(o===l){o=r[q];
}r[q]=o+p;
s.userEvents.move(r.left,r.top);
},end:function(){this.userEvents.end();
this.target=this.position=l;
}});
e.ui.plugin(g);
})(window.kendo.jQuery);
})();
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
