(function(b,a){a(["./kendo.data"],b);
})(function(){(function(){(function(a,P){var v=window.kendo,O=v.ui,w=v.keys,z=a.map,j=a.each,N=a.trim,n=a.extend,L=v.template,S=O.Widget,m=/^(a|div)$/i,D=".kendoTabStrip",u="img",s="href",E="prev",I="show",y="k-link",x="k-last",d="click",l="error",k=":empty",t="k-image",o="k-first",H="select",b="activate",e="k-content",g="contentUrl",A="mouseenter",B="mouseleave",f="contentLoad",i="k-state-disabled",h="k-state-default",c="k-state-active",p="k-state-focused",r="k-state-hover",J="k-tab-on-top",C=".k-item:not(."+i+")",q=".k-tabstrip-items > "+C+":not(."+c+")",M={content:L("<div class='k-content'#= contentAttributes(data) # role='tabpanel'>#= content(item) #</div>"),itemWrapper:L("<#= tag(item) # class='k-link'#= contentUrl(item) ##= textAttributes(item) #>#= image(item) ##= sprite(item) ##= text(item) #</#= tag(item) #>"),item:L("<li class='#= wrapperCssClass(group, item) #' role='tab' #=item.active ? \"aria-selected='true'\" : ''#>#= itemWrapper(data) #</li>"),image:L("<img class='k-image' alt='' src='#= imageUrl #' />"),sprite:L("<span class='k-sprite #= spriteCssClass #'></span>"),empty:L("")},F={wrapperCssClass:function(T,V){var W="k-item",U=V.index;
if(V.enabled===false){W+=" k-state-disabled";
}else{W+=" k-state-default";
}if(U===0){W+=" k-first";
}if(U==T.length-1){W+=" k-last";
}return W;
},textAttributes:function(T){return T.url?" href='"+T.url+"'":"";
},text:function(T){return T.encoded===false?T.text:v.htmlEncode(T.text);
},tag:function(T){return T.url?"a":"span";
},contentAttributes:function(T){return T.active!==true?" style='display:none' aria-hidden='true' aria-expanded='false'":"";
},content:function(T){return T.content?T.content:T.contentUrl?"":"&nbsp;";
},contentUrl:function(T){return T.contentUrl?v.attr("content-url")+'="'+T.contentUrl+'"':"";
}};
function R(T){T.children(u).addClass(t);
T.children("a").addClass(y).children(u).addClass(t);
T.filter(":not([disabled]):not([class*=k-state-disabled])").addClass(h);
T.filter("li[disabled]").addClass(i).removeAttr("disabled");
T.filter(":not([class*=k-state])").children("a").filter(":focus").parent().addClass(c+" "+J);
T.attr("role","tab");
T.filter("."+c).attr("aria-selected",true);
T.each(function(){var U=a(this);
if(!U.children("."+y).length){U.contents().filter(function(){return(!this.nodeName.match(m)&&!(this.nodeType==3&&!N(this.nodeValue)));
}).wrapAll("<span class='"+y+"'/>");
}});
}function Q(T){var U=T.children(".k-item");
U.filter(".k-first:not(:first-child)").removeClass(o);
U.filter(".k-last:not(:last-child)").removeClass(x);
U.filter(":first-child").addClass(o);
U.filter(":last-child").addClass(x);
}function G(T,U){return"<span class='k-button k-button-icon k-button-bare k-tabstrip-"+T+"' unselectable='on'><span class='k-icon "+U+"'></span></span>";
}var K=S.extend({init:function(U,V){var X=this;
S.fn.init.call(X,U,V);
X._animations(X.options);
V=X.options;
X._wrapper();
X._isRtl=v.support.isRtl(X.wrapper);
X._tabindex();
X._updateClasses();
X._dataSource();
if(V.dataSource){X.dataSource.fetch();
}X._tabPosition();
X._scrollable();
if(X.options.contentUrls){X.wrapper.find(".k-tabstrip-items > .k-item").each(function(Y,Z){a(Z).find(">."+y).data(g,X.options.contentUrls[Y]);
});
}X.wrapper.on(A+D+" "+B+D,q,X._toggleHover).on("focus"+D,a.proxy(X._active,X)).on("blur"+D,function(){X._current(null);
});
X._keyDownProxy=a.proxy(X._keydown,X);
if(V.navigatable){X.wrapper.on("keydown"+D,X._keyDownProxy);
}X.wrapper.children(".k-tabstrip-items").on(d+D,".k-state-disabled .k-link",false).on(d+D," > "+C,function(Y){var ab=X.wrapper[0];
if(ab!==document.activeElement){var aa=v.support.browser.msie;
if(aa){try{ab.setActive();
}catch(Z){ab.focus();
}}else{ab.focus();
}}if(X._click(a(Y.currentTarget))){Y.preventDefault();
}});
var W=X.tabGroup.children("li."+c),T=X.contentHolder(W.index());
if(W[0]&&T.length>0&&T[0].childNodes.length===0){X.activateTab(W.eq(0));
}X.element.attr("role","tablist");
if(X.element[0].id){X._ariaId=X.element[0].id+"_ts_active";
}v.notify(X);
},_active:function(){var T=this.tabGroup.children().filter("."+c);
T=T[0]?T:this._endItem("first");
if(T[0]){this._current(T);
}},_endItem:function(T){return this.tabGroup.children(C)[T]();
},_item:function(V,T){var U;
if(T===E){U="last";
}else{U="first";
}if(!V){return this._endItem(U);
}V=V[T]();
if(!V[0]){V=this._endItem(U);
}if(V.hasClass(i)){V=this._item(V,T);
}return V;
},_current:function(T){var W=this,U=W._focused,V=W._ariaId;
if(T===P){return U;
}if(U){if(U[0].id===V){U.removeAttr("id");
}U.removeClass(p);
}if(T){if(!T.hasClass(c)){T.addClass(p);
}W.element.removeAttr("aria-activedescendant");
V=T[0].id||V;
if(V){T.attr("id",V);
W.element.attr("aria-activedescendant",V);
}}W._focused=T;
},_keydown:function(V){var Y=this,W=V.keyCode,U=Y._current(),X=Y._isRtl,T;
if(V.target!=V.currentTarget){return;
}if(W==w.DOWN||W==w.RIGHT){T=X?E:"next";
}else{if(W==w.UP||W==w.LEFT){T=X?"next":E;
}else{if(W==w.ENTER||W==w.SPACEBAR){Y._click(U);
V.preventDefault();
}else{if(W==w.HOME){Y._click(Y._endItem("first"));
V.preventDefault();
return;
}else{if(W==w.END){Y._click(Y._endItem("last"));
V.preventDefault();
return;
}}}}}if(T){Y._click(Y._item(U,T));
V.preventDefault();
}},_dataSource:function(){var T=this;
if(T.dataSource&&T._refreshHandler){T.dataSource.unbind("change",T._refreshHandler);
}else{T._refreshHandler=a.proxy(T.refresh,T);
}T.dataSource=v.data.DataSource.create(T.options.dataSource).bind("change",T._refreshHandler);
},setDataSource:function(T){var U=this;
U.options.dataSource=T;
U._dataSource();
U.dataSource.fetch();
},_animations:function(T){if(T&&("animation" in T)&&!T.animation){T.animation={open:{effects:{}},close:{effects:{}}};
}},refresh:function(W){var af=this,aa=af.options,ae=v.getter(aa.dataTextField),U=v.getter(aa.dataContentField),V=v.getter(aa.dataContentUrlField),Y=v.getter(aa.dataImageUrlField),ag=v.getter(aa.dataUrlField),ab=v.getter(aa.dataSpriteCssClass),X,ad=[],ac,T,ah=af.dataSource.view(),Z;
W=W||{};
T=W.action;
if(T){ah=W.items;
}for(X=0,Z=ah.length;
X<Z;
X++){ac={text:ae(ah[X])};
if(aa.dataContentField){ac.content=U(ah[X]);
}if(aa.dataContentUrlField){ac.contentUrl=V(ah[X]);
}if(aa.dataUrlField){ac.url=ag(ah[X]);
}if(aa.dataImageUrlField){ac.imageUrl=Y(ah[X]);
}if(aa.dataSpriteCssClass){ac.spriteCssClass=ab(ah[X]);
}ad[X]=ac;
}if(W.action=="add"){if(W.index<af.tabGroup.children().length){af.insertBefore(ad,af.tabGroup.children().eq(W.index));
}else{af.append(ad);
}}else{if(W.action=="remove"){for(X=0;
X<ah.length;
X++){af.remove(W.index);
}}else{if(W.action=="itemchange"){X=af.dataSource.view().indexOf(ah[0]);
if(W.field===aa.dataTextField){af.tabGroup.children().eq(X).find(".k-link").text(ah[0].get(W.field));
}}else{af.trigger("dataBinding");
af.remove("li");
af.append(ad);
af.trigger("dataBound");
}}}},value:function(U){var T=this;
if(U!==P){if(U!=T.value()){T.tabGroup.children().each(function(){if(a.trim(a(this).text())==U){T.select(this);
}});
}}else{return T.select().text();
}},items:function(){return this.tabGroup[0].children;
},setOptions:function(U){var V=this,T=V.options.animation;
V._animations(U);
U.animation=n(true,T,U.animation);
if(U.navigatable){V.wrapper.on("keydown"+D,V._keyDownProxy);
}else{V.wrapper.off("keydown"+D,V._keyDownProxy);
}S.fn.setOptions.call(V,U);
},events:[H,b,I,l,f,"change","dataBinding","dataBound"],options:{name:"TabStrip",dataTextField:"",dataContentField:"",dataImageUrlField:"",dataUrlField:"",dataSpriteCssClass:"",dataContentUrlField:"",tabPosition:"top",animation:{open:{effects:"expand:vertical fadeIn",duration:200},close:{duration:200}},collapsible:false,navigatable:true,contentUrls:false,scrollable:{distance:200}},destroy:function(){var T=this;
S.fn.destroy.call(T);
if(T._refreshHandler){T.dataSource.unbind("change",T._refreshHandler);
}T.wrapper.off(D);
T.wrapper.children(".k-tabstrip-items").off(D);
if(T._scrollableModeActive){T._scrollPrevButton.off().remove();
T._scrollNextButton.off().remove();
}T.scrollWrap.children(".k-tabstrip").unwrap();
v.destroy(T.wrapper);
},select:function(T){var U=this;
if(arguments.length===0){return U.tabGroup.children("li."+c);
}if(!isNaN(T)){T=U.tabGroup.children().get(T);
}T=U.tabGroup.find(T);
a(T).each(function(V,W){W=a(W);
if(!W.hasClass(c)&&!U.trigger(H,{item:W[0],contentElement:U.contentHolder(W.index())[0]})){U.activateTab(W);
}});
return U;
},enable:function(T,U){this._toggleDisabled(T,U!==false);
return this;
},disable:function(T){this._toggleDisabled(T,false);
return this;
},reload:function(T){T=this.tabGroup.find(T);
var U=this;
T.each(function(){var X=a(this),W=X.find("."+y).data(g),V=U.contentHolder(X.index());
if(W){U.ajaxRequest(X,V,null,W);
}});
return U;
},append:function(U){var V=this,T=V._create(U);
j(T.tabs,function(X){var W=T.contents[X];
V.tabGroup.append(this);
if(V.options.tabPosition=="bottom"){V.tabGroup.before(W);
}else{if(V._scrollableModeActive){V._scrollPrevButton.before(W);
}else{V.wrapper.append(W);
}}V.angular("compile",function(){return{elements:[W]};
});
});
Q(V.tabGroup);
V._updateContentElements();
V.resize(true);
return V;
},insertBefore:function(W,V){V=this.tabGroup.find(V);
var X=this,T=X._create(W),U=a(X.contentElement(V.index()));
j(T.tabs,function(Z){var Y=T.contents[Z];
V.before(this);
U.before(Y);
X.angular("compile",function(){return{elements:[Y]};
});
});
Q(X.tabGroup);
X._updateContentElements();
X.resize(true);
return X;
},insertAfter:function(W,V){V=this.tabGroup.find(V);
var X=this,T=X._create(W),U=a(X.contentElement(V.index()));
j(T.tabs,function(Z){var Y=T.contents[Z];
V.after(this);
U.after(Y);
X.angular("compile",function(){return{elements:[Y]};
});
});
Q(X.tabGroup);
X._updateContentElements();
X.resize(true);
return X;
},remove:function(U){var V=this;
var W=typeof U;
var T;
if(W==="string"){U=V.tabGroup.find(U);
}else{if(W==="number"){U=V.tabGroup.children().eq(U);
}}T=U.map(function(){var X=V.contentElement(a(this).index());
v.destroy(X);
return X;
});
U.remove();
T.remove();
V._updateContentElements();
V.resize(true);
return V;
},_create:function(W){var V=a.isPlainObject(W),Y=this,X,U,T;
if(V||a.isArray(W)){W=a.isArray(W)?W:[W];
X=z(W,function(aa,Z){return a(K.renderItem({group:Y.tabGroup,item:n(aa,{index:Z})}));
});
U=z(W,function(aa,Z){if(typeof aa.content=="string"||aa.contentUrl){return a(K.renderContent({item:n(aa,{index:Z})}));
}});
}else{if(typeof W=="string"&&W[0]!="<"){X=Y.element.find(W);
}else{X=a(W);
}U=a();
X.each(function(){T=a("<div class='"+e+"'/>");
if(/k-tabstrip-items/.test(this.parentNode.className)){var Z=parseInt(this.getAttribute("aria-controls").replace(/^.*-/,""),10)-1;
T=a(Y.contentElement(Z));
}U=U.add(T);
});
R(X);
}return{tabs:X,contents:U};
},_toggleDisabled:function(T,U){T=this.tabGroup.find(T);
T.each(function(){a(this).toggleClass(h,U).toggleClass(i,!U);
});
},_updateClasses:function(){var W=this,V,T,U;
W.wrapper.addClass("k-widget k-header k-tabstrip");
W.tabGroup=W.wrapper.children("ul").addClass("k-tabstrip-items k-reset");
if(!W.tabGroup[0]){W.tabGroup=a("<ul class='k-tabstrip-items k-reset'/>").appendTo(W.wrapper);
}V=W.tabGroup.find("li").addClass("k-item");
if(V.length){T=V.filter("."+c).index();
U=T>=0?T:P;
W.tabGroup.contents().filter(function(){return(this.nodeType==3&&!N(this.nodeValue));
}).remove();
}if(T>=0){V.eq(T).addClass(J);
}W.contentElements=W.wrapper.children("div");
W.contentElements.addClass(e).eq(U).addClass(c).css({display:"block"});
if(V.length){R(V);
Q(W.tabGroup);
W._updateContentElements();
}},_updateContentElements:function(){var X=this,U=X.options.contentUrls||[],V=X.tabGroup.find(".k-item"),W=(X.element.attr("id")||v.guid())+"-",T=X.wrapper.children("div");
if(T.length&&(V.length>T.length)){T.each(function(aa){var Y=parseInt(this.id.replace(W,""),10),ab=V.filter("[aria-controls="+W+Y+"]"),Z=W+(aa+1);
ab.data("aria",Z);
this.setAttribute("id",Z);
});
V.each(function(){var Y=a(this);
this.setAttribute("aria-controls",Y.data("aria"));
Y.removeData("aria");
});
}else{V.each(function(aa){var Y=T.eq(aa),Z=W+(aa+1);
this.setAttribute("aria-controls",Z);
if(!Y.length&&U[aa]){a("<div class='"+e+"'/>").appendTo(X.wrapper).attr("id",Z);
}else{Y.attr("id",Z);
if(!a(this).children(".k-loading")[0]&&!U[aa]){a("<span class='k-loading k-complete'/>").prependTo(this);
}}Y.attr("role","tabpanel");
Y.filter(":not(."+c+")").attr("aria-hidden",true).attr("aria-expanded",false);
Y.filter("."+c).attr("aria-expanded",true);
});
}X.contentElements=X.contentAnimators=X.wrapper.children("div");
X.tabsHeight=X.tabGroup.outerHeight()+parseInt(X.wrapper.css("border-top-width"),10)+parseInt(X.wrapper.css("border-bottom-width"),10);
if(v.kineticScrollNeeded&&v.mobile.ui.Scroller){v.touchScroller(X.contentElements);
X.contentElements=X.contentElements.children(".km-scroll-container");
}},_wrapper:function(){var T=this;
if(T.element.is("ul")){T.wrapper=T.element.wrapAll("<div />").parent();
}else{T.wrapper=T.element;
}T.scrollWrap=T.wrapper.parent(".k-tabstrip-wrapper");
if(!T.scrollWrap[0]){T.scrollWrap=T.wrapper.wrapAll("<div class='k-tabstrip-wrapper' />").parent();
}},_tabPosition:function(){var U=this,T=U.options.tabPosition;
U.wrapper.addClass("k-floatwrap k-tabstrip-"+T);
if(T=="bottom"){U.tabGroup.appendTo(U.wrapper);
}U.resize(true);
},_setContentElementsDimensions:function(){var aa=this,Z=aa.options.tabPosition;
if(Z=="left"||Z=="right"){var U=aa.wrapper.children(".k-content"),T=U.filter(":visible"),W="margin-"+Z,Y=aa.tabGroup,V=Y.outerWidth();
var X=Math.ceil(Y.height())-parseInt(T.css("padding-top"),10)-parseInt(T.css("padding-bottom"),10)-parseInt(T.css("border-top-width"),10)-parseInt(T.css("border-bottom-width"),10);
setTimeout(function(){U.css(W,V).css("min-height",X);
});
}},_resize:function(){this._setContentElementsDimensions();
this._scrollable();
},_sizeScrollWrap:function(T){if(T.is(":visible")){var V=this.options.tabPosition;
var U=Math.floor(T.outerHeight(true))+(V==="left"||V==="right"?2:this.tabsHeight);
this.scrollWrap.css("height",U).css("height");
}},_toggleHover:function(T){a(T.currentTarget).toggleClass(r,T.type==A);
},_click:function(X){var aa=this,Y=X.find("."+y),V=Y.attr(s),T=aa.options.collapsible,U=aa.contentHolder(X.index()),Z,W;
if(X.closest(".k-widget")[0]!=aa.wrapper[0]){return;
}if(X.is("."+i+(!T?",."+c:""))){return true;
}W=Y.data(g)||(V&&(V.charAt(V.length-1)=="#"||V.indexOf("#"+aa.element[0].id+"-")!=-1));
Z=!V||W;
if(aa.tabGroup.children("[data-animating]").length){return Z;
}if(aa.trigger(H,{item:X[0],contentElement:U[0]})){return true;
}if(Z===false){return;
}if(T&&X.is("."+c)){aa.deactivateTab(X);
return true;
}if(aa.activateTab(X)){Z=true;
}return Z;
},_scrollable:function(){var X=this,T=X.options,Y,W,V,U;
if(X._scrollableAllowed()){X.wrapper.addClass("k-tabstrip-scrollable");
Y=X.wrapper[0].offsetWidth;
W=X.tabGroup[0].scrollWidth;
if(W>Y&&!X._scrollableModeActive){X._nowScrollingTabs=false;
X._isRtl=v.support.isRtl(X.element);
X.wrapper.append(G("prev","k-i-arrow-w")+G("next","k-i-arrow-e"));
V=X._scrollPrevButton=X.wrapper.children(".k-tabstrip-prev");
U=X._scrollNextButton=X.wrapper.children(".k-tabstrip-next");
X.tabGroup.css({marginLeft:V.outerWidth()+9,marginRight:U.outerWidth()+12});
V.on("mousedown"+D,function(){X._nowScrollingTabs=true;
X._scrollTabsByDelta(T.scrollable.distance*(X._isRtl?1:-1));
});
U.on("mousedown"+D,function(){X._nowScrollingTabs=true;
X._scrollTabsByDelta(T.scrollable.distance*(X._isRtl?-1:1));
});
V.add(U).on("mouseup"+D,function(){X._nowScrollingTabs=false;
});
X._scrollableModeActive=true;
X._toggleScrollButtons();
}else{if(X._scrollableModeActive&&W<=Y){X._scrollableModeActive=false;
X.wrapper.removeClass("k-tabstrip-scrollable");
X._scrollPrevButton.off().remove();
X._scrollNextButton.off().remove();
X.tabGroup.css({marginLeft:"",marginRight:""});
}else{if(!X._scrollableModeActive){X.wrapper.removeClass("k-tabstrip-scrollable");
}else{X._toggleScrollButtons();
}}}}},_scrollableAllowed:function(){var T=this.options;
return T.scrollable&&!isNaN(T.scrollable.distance)&&(T.tabPosition=="top"||T.tabPosition=="bottom");
},_scrollTabsToItem:function(U){var ab=this,Y=ab.tabGroup,T=Y.scrollLeft(),X=U.outerWidth(),V=ab._isRtl?U.position().left:U.position().left-Y.children().first().position().left,aa=Y[0].offsetWidth,Z=Math.ceil(parseFloat(Y.css("padding-left"))),W;
if(ab._isRtl){if(V<0){W=T+V-(aa-T)-Z;
}else{if(V+X>aa){W=T+V-X+Z*2;
}}}else{if(T+aa<V+X){W=V+X-aa+Z*2;
}else{if(T>V){W=V-Z;
}}}Y.finish().animate({scrollLeft:W},"fast","linear",function(){ab._toggleScrollButtons();
});
},_scrollTabsByDelta:function(T){var W=this;
var V=W.tabGroup;
var U=V.scrollLeft();
V.finish().animate({scrollLeft:U+T},"fast","linear",function(){if(W._nowScrollingTabs){W._scrollTabsByDelta(T);
}else{W._toggleScrollButtons();
}});
},_toggleScrollButtons:function(){var U=this,V=U.tabGroup,T=V.scrollLeft();
U._scrollPrevButton.toggle(U._isRtl?T<V[0].scrollWidth-V[0].offsetWidth-1:T!==0);
U._scrollNextButton.toggle(U._isRtl?T!==0:T<V[0].scrollWidth-V[0].offsetWidth-1);
},deactivateTab:function(X){var Y=this,U=Y.options.animation,T=U.open,V=n({},U.close),W=V&&"effects" in V;
X=Y.tabGroup.find(X);
V=n(W?V:n({reverse:true},T),{hide:true});
if(v.size(T.effects)){X.kendoAddClass(h,{duration:T.duration});
X.kendoRemoveClass(c,{duration:T.duration});
}else{X.addClass(h);
X.removeClass(c);
}X.removeAttr("aria-selected");
Y.contentAnimators.filter("."+c).kendoStop(true,true).kendoAnimate(V).removeClass(c).attr("aria-hidden",true);
},activateTab:function(ab){if(this.tabGroup.children("[data-animating]").length){return;
}ab=this.tabGroup.find(ab);
var ah=this,U=ah.options.animation,T=U.open,V=n({},U.close),Z=V&&"effects" in V,ad=ab.parent().children(),ae=ad.filter("."+c),ac=ad.index(ab);
V=n(Z?V:n({reverse:true},T),{hide:true});
if(v.size(T.effects)){ae.kendoRemoveClass(c,{duration:V.duration});
ab.kendoRemoveClass(r,{duration:V.duration});
}else{ae.removeClass(c);
ab.removeClass(r);
}var W=ah.contentAnimators;
if(ah.inRequest){ah.xhr.abort();
ah.inRequest=false;
}if(W.length===0){ah.tabGroup.find("."+J).removeClass(J);
ab.addClass(J).css("z-index");
ab.addClass(c);
ah._current(ab);
ah.trigger("change");
if(ah._scrollableModeActive){ah._scrollTabsToItem(ab);
}return false;
}var ai=W.filter("."+c),Y=ah.contentHolder(ac),X=Y.closest(".k-content");
ah.tabsHeight=ah.tabGroup.outerHeight()+parseInt(ah.wrapper.css("border-top-width"),10)+parseInt(ah.wrapper.css("border-bottom-width"),10);
ah._sizeScrollWrap(ai);
if(Y.length===0){ai.removeClass(c).attr("aria-hidden",true).kendoStop(true,true).kendoAnimate(V);
return false;
}ab.attr("data-animating",true);
var aa=(ab.children("."+y).data(g)||false)&&Y.is(k),ag=function(){ah.tabGroup.find("."+J).removeClass(J);
ab.addClass(J).css("z-index");
if(v.size(T.effects)){ae.kendoAddClass(h,{duration:T.duration});
ab.kendoAddClass(c,{duration:T.duration});
}else{ae.addClass(h);
ab.addClass(c);
}ae.removeAttr("aria-selected");
ab.attr("aria-selected",true);
ah._current(ab);
ah._sizeScrollWrap(X);
X.addClass(c).removeAttr("aria-hidden").kendoStop(true,true).attr("aria-expanded",true).kendoAnimate(n({init:function(){ah.trigger(I,{item:ab[0],contentElement:Y[0]});
v.resize(Y);
}},T,{complete:function(){ab.removeAttr("data-animating");
ah.trigger(b,{item:ab[0],contentElement:Y[0]});
v.resize(Y);
ah.scrollWrap.css("height","").css("height");
}}));
},af=function(){if(!aa){ag();
ah.trigger("change");
}else{ab.removeAttr("data-animating");
ah.ajaxRequest(ab,Y,function(){ab.attr("data-animating",true);
ag();
ah.trigger("change");
});
}if(ah._scrollableModeActive){ah._scrollTabsToItem(ab);
}};
ai.removeClass(c);
ai.attr("aria-hidden",true);
ai.attr("aria-expanded",false);
if(ai.length){ai.kendoStop(true,true).kendoAnimate(n({complete:af},V));
}else{af();
}return true;
},contentElement:function(W){if(isNaN(W-0)){return P;
}var T=this.contentElements&&this.contentElements[0]&&!v.kineticScrollNeeded?this.contentElements:this.contentAnimators;
W=T&&W<0?T.length+W:W;
var V=new RegExp("-"+(W+1)+"$");
if(T){for(var U=0,X=T.length;
U<X;
U++){if(V.test(T.eq(U).closest(".k-content")[0].id)){return T[U];
}}}return P;
},contentHolder:function(U){var T=a(this.contentElement(U)),V=T.children(".km-scroll-container");
return v.support.touch&&V[0]?V:T;
},ajaxRequest:function(W,U,T,ae){W=this.tabGroup.find(W);
var ad=this,af=a.ajaxSettings.xhr,aa=W.find("."+y),V={},Z=W.width()/2,Y=false,ac=W.find(".k-loading").removeClass("k-complete");
if(!ac[0]){ac=a("<span class='k-loading'/>").prependTo(W);
}var X=Z*2-ac.width();
var ab=function(){ac.animate({marginLeft:(parseInt(ac.css("marginLeft"),10)||0)<Z?X:0},500,ab);
};
if(v.support.browser.msie&&v.support.browser.version<10){setTimeout(ab,40);
}ae=ae||aa.data(g)||aa.attr(s);
ad.inRequest=true;
ad.xhr=a.ajax({type:"GET",cache:false,url:ae,dataType:"html",data:V,xhr:function(){var ag=this,ai=af(),ah=ag.progressUpload?"progressUpload":ag.progress?"progress":false;
if(ai){a.each([ai,ai.upload],function(){if(this.addEventListener){this.addEventListener("progress",function(aj){if(ah){ag[ah](aj);
}},false);
}});
}ag.noProgress=!(window.XMLHttpRequest&&("upload" in new XMLHttpRequest()));
return ai;
},progress:function(ag){if(ag.lengthComputable){var ah=parseInt((ag.loaded/ag.total*100),10)+"%";
ac.stop(true).addClass("k-progress").css({width:ah,marginLeft:0});
}},error:function(ah,ag){if(ad.trigger("error",{xhr:ah,status:ag})){this.complete();
}},stopProgress:function(){clearInterval(Y);
ac.stop(true).addClass("k-progress")[0].style.cssText="";
},complete:function(ag){ad.inRequest=false;
if(this.noProgress){setTimeout(this.stopProgress,500);
}else{this.stopProgress();
}if(ag.statusText=="abort"){ac.remove();
}},success:function(ai){ac.addClass("k-complete");
try{var ah=this,ak=10;
if(ah.noProgress){ac.width(ak+"%");
Y=setInterval(function(){ah.progress({lengthComputable:true,loaded:Math.min(ak,100),total:100});
ak+=10;
},40);
}ad.angular("cleanup",function(){return{elements:U.get()};
});
v.destroy(U);
U.html(ai);
}catch(aj){var ag=window.console;
if(ag&&ag.error){ag.error(aj.name+": "+aj.message+" in "+ae);
}this.error(this.xhr,"error");
}if(T){T.call(ad,U);
}ad.angular("compile",function(){return{elements:U.get()};
});
ad.trigger(f,{item:W[0],contentElement:U[0]});
}});
}});
n(K,{renderItem:function(V){V=n({tabStrip:{},group:{}},V);
var T=M.empty,U=V.item;
return M.item(n(V,{image:U.imageUrl?M.image:T,sprite:U.spriteCssClass?M.sprite:T,itemWrapper:M.itemWrapper},F));
},renderContent:function(T){return M.content(n(T,F));
}});
v.ui.plugin(K);
})(window.kendo.jQuery);
})();
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
