(function(b,a){a(["./kendo.draganddrop"],b);
})(function(){(function(){(function(a,V){var u=window.kendo,X=u.ui.Widget,k=u.ui.Draggable,s=a.isPlainObject,c=u._activeElement,M=a.proxy,p=a.extend,m=a.each,S=u.template,d="body",T,I=".kendoWindow",A=".k-window",D=".k-window-title",E=D+"bar",B=".k-window-content",C=".k-resize-handle",x=".k-overlay",t="k-content-frame",F="k-loading",w="k-state-hover",v="k-state-focused",G="k-window-maximized",W=":visible",q="hidden",g="cursor",J="open",b="activate",h="deactivate",e="close",N="refresh",P="resize",Q="resizeEnd",l="dragstart",j="dragend",n="error",K="overflow",ab="zIndex",H=".k-window-actions .k-i-minimize,.k-window-actions .k-i-maximize",y=".k-i-pin",z=".k-i-unpin",L=y+","+z,U=".k-window-titlebar .k-window-action",O=".k-window-titlebar .k-i-refresh",r=u.isLocalUrl;
function i(ac){return(typeof ac!="undefined");
}function f(ae,ad,ac){return Math.max(Math.min(parseInt(ae,10),ac===Infinity?ac:parseInt(ac,10)),parseInt(ad,10));
}function R(ac,ad){return function(){var ag=this,ah=ag.wrapper,af=ah[0].style,ae=ag.options;
if(ae.isMaximized||ae.isMinimized){return ag;
}ag.restoreOptions={width:af.width,height:af.height};
ah.children(C).hide().end().children(E).find(H).parent().hide().eq(0).before(T.action({name:"Restore"}));
ad.call(ag);
if(ac=="maximize"){ag.wrapper.children(E).find(L).parent().hide();
}else{ag.wrapper.children(E).find(L).parent().show();
}return ag;
};
}function o(){return !this.type||this.type.toLowerCase().indexOf("script")>=0;
}var Y=X.extend({init:function(ae,ai){var al=this,ao,ah={},am,ad,aj,ag=false,ac,an,ak=ai&&ai.actions&&!ai.actions.length,af;
X.fn.init.call(al,ae,ai);
ai=al.options;
aj=ai.position;
ae=al.element;
ac=ai.content;
if(ak){ai.actions=[];
}al.appendTo=a(ai.appendTo);
al._animations();
if(ac&&!s(ac)){ac=ai.content={url:ac};
}ae.find("script").filter(o).remove();
if(!ae.parent().is(al.appendTo)&&(aj.top===V||aj.left===V)){if(ae.is(W)){ah=ae.offset();
ag=true;
}else{am=ae.css("visibility");
ad=ae.css("display");
ae.css({visibility:q,display:""});
ah=ae.offset();
ae.css({visibility:am,display:ad});
}if(aj.top===V){aj.top=ah.top;
}if(aj.left===V){aj.left=ah.left;
}}if(!i(ai.visible)||ai.visible===null){ai.visible=ae.is(W);
}ao=al.wrapper=ae.closest(A);
if(!ae.is(".k-content")||!ao[0]){ae.addClass("k-window-content k-content");
al._createWindow(ae,ai);
ao=al.wrapper=ae.closest(A);
al._dimensions();
}al._position();
if(ai.pinned){al.pin(true);
}if(ac){al.refresh(ac);
}if(ai.visible){al.toFront();
}an=ao.children(B);
al._tabindex(an);
if(ai.visible&&ai.modal){al._overlay(ao.is(W)).css({opacity:0.5});
}ao.on("mouseenter"+I,U,M(al._buttonEnter,al)).on("mouseleave"+I,U,M(al._buttonLeave,al)).on("click"+I,"> "+U,M(al._windowActionHandler,al));
an.on("keydown"+I,M(al._keydown,al)).on("focus"+I,M(al._focus,al)).on("blur"+I,M(al._blur,al));
this._resizable();
this._draggable();
af=ae.attr("id");
if(af){af=af+"_wnd_title";
ao.children(E).children(D).attr("id",af);
an.attr({role:"dialog","aria-labelledby":af});
}ao.add(ao.children(".k-resize-handle,"+E)).on("mousedown"+I,M(al.toFront,al));
al.touchScroller=u.touchScroller(ae);
al._resizeHandler=M(al._onDocumentResize,al);
al._marker=u.guid().substring(0,8);
a(window).on("resize"+I+al._marker,al._resizeHandler);
if(ai.visible){al.trigger(J);
al.trigger(b);
}u.notify(al);
},_buttonEnter:function(ac){a(ac.currentTarget).addClass(w);
},_buttonLeave:function(ac){a(ac.currentTarget).removeClass(w);
},_focus:function(){this.wrapper.addClass(v);
},_blur:function(){this.wrapper.removeClass(v);
},_dimensions:function(){var aj=this.wrapper;
var ag=this.options;
var ai=ag.width;
var ad=ag.height;
var af=ag.maxHeight;
var ac=["minWidth","minHeight","maxWidth","maxHeight"];
this.title(ag.title);
for(var ae=0;
ae<ac.length;
ae++){var ah=ag[ac[ae]];
if(ah&&ah!=Infinity){aj.css(ac[ae],ah);
}}if(af&&af!=Infinity){this.element.css("maxHeight",af);
}if(ai){if(ai.toString().indexOf("%")>0){aj.width(ai);
}else{aj.width(f(ai,ag.minWidth,ag.maxWidth));
}}if(ad){if(ad.toString().indexOf("%")>0){aj.height(ad);
}else{aj.height(f(ad,ag.minHeight,ag.maxHeight));
}}if(!ag.visible){aj.hide();
}},_position:function(){var ad=this.wrapper,ac=this.options.position;
if(ac.top===0){ac.top=ac.top.toString();
}if(ac.left===0){ac.left=ac.left.toString();
}ad.css({top:ac.top||"",left:ac.left||""});
},_animations:function(){var ac=this.options;
if(ac.animation===false){ac.animation={open:{effects:{}},close:{hide:true,effects:{}}};
}},_resize:function(){u.resize(this.element.children());
},_resizable:function(){var ac=this.options.resizable;
var ad=this.wrapper;
if(this.resizing){ad.off("dblclick"+I).children(C).remove();
this.resizing.destroy();
this.resizing=null;
}if(ac){ad.on("dblclick"+I,E,M(function(ae){if(!a(ae.target).closest(".k-window-action").length){this.toggleMaximization();
}},this));
m("n e s w se sw ne nw".split(" "),function(af,ae){ad.append(T.resizeHandle(ae));
});
this.resizing=new aa(this);
}ad=null;
},_draggable:function(){var ac=this.options.draggable;
if(this.dragging){this.dragging.destroy();
this.dragging=null;
}if(ac){this.dragging=new Z(this,ac.dragHandle||E);
}},_actions:function(){var ac=this.options.actions;
var ae=this.wrapper.children(E);
var ad=ae.find(".k-window-actions");
ac=a.map(ac,function(af){return{name:af};
});
ad.html(u.render(T.action,ac));
},setOptions:function(ac){X.fn.setOptions.call(this,ac);
var ad=this.options.scrollable!==false;
this.restore();
this._animations();
this._dimensions();
this._position();
this._resizable();
this._draggable();
this._actions();
if(typeof ac.modal!=="undefined"){this._overlay(ac.modal);
}this.element.css(K,ad?"":"hidden");
},events:[J,b,h,e,N,P,Q,l,j,n],options:{name:"Window",animation:{open:{effects:{zoom:{direction:"in"},fade:{direction:"in"}},duration:350},close:{effects:{zoom:{direction:"out",properties:{scale:0.7}},fade:{direction:"out"}},duration:350,hide:true}},title:"",actions:["Close"],autoFocus:true,modal:false,resizable:true,draggable:true,minWidth:90,minHeight:50,maxWidth:Infinity,maxHeight:Infinity,pinned:false,scrollable:true,position:{},content:null,visible:null,height:null,width:null,appendTo:"body"},_closable:function(){return a.inArray("close",a.map(this.options.actions,function(ac){return ac.toLowerCase();
}))>-1;
},_keydown:function(ad){var an=this,am=an.options,ai=u.keys,ah=ad.keyCode,ap=an.wrapper,al,af,ac=10,ag=an.options.isMaximized,ak,aj,ao,ae;
if(ad.target!=ad.currentTarget||an._closing){return;
}if(ah==ai.ESC&&an._closable()){an._close(false);
}if(am.draggable&&!ad.ctrlKey&&!ag){al=u.getOffset(ap);
if(ah==ai.UP){af=ap.css("top",al.top-ac);
}else{if(ah==ai.DOWN){af=ap.css("top",al.top+ac);
}else{if(ah==ai.LEFT){af=ap.css("left",al.left-ac);
}else{if(ah==ai.RIGHT){af=ap.css("left",al.left+ac);
}}}}}if(am.resizable&&ad.ctrlKey&&!ag){if(ah==ai.UP){af=true;
aj=ap.height()-ac;
}else{if(ah==ai.DOWN){af=true;
aj=ap.height()+ac;
}}if(ah==ai.LEFT){af=true;
ak=ap.width()-ac;
}else{if(ah==ai.RIGHT){af=true;
ak=ap.width()+ac;
}}if(af){ao=f(ak,am.minWidth,am.maxWidth);
ae=f(aj,am.minHeight,am.maxHeight);
if(!isNaN(ao)){ap.width(ao);
an.options.width=ao+"px";
}if(!isNaN(ae)){ap.height(ae);
an.options.height=ae+"px";
}an.resize();
}}if(af){ad.preventDefault();
}},_overlay:function(ad){var ac=this.appendTo.children(x),ae=this.wrapper;
if(!ac.length){ac=a("<div class='k-overlay' />");
}ac.insertBefore(ae[0]).toggle(ad).css(ab,parseInt(ae.css(ab),10)-1);
return ac;
},_actionForIcon:function(ac){var ad=/\bk-i-\w+\b/.exec(ac[0].className)[0];
return{"k-i-close":"_close","k-i-maximize":"maximize","k-i-minimize":"minimize","k-i-restore":"restore","k-i-refresh":"refresh","k-i-pin":"pin","k-i-unpin":"unpin"}[ad];
},_windowActionHandler:function(ad){if(this._closing){return;
}var ae=a(ad.target).closest(".k-window-action").find(".k-icon");
var ac=this._actionForIcon(ae);
if(ac){ad.preventDefault();
this[ac]();
return false;
}},_modals:function(){var ac=this;
var ad=a(A).filter(function(){var ae=a(this);
var af=ac._object(ae);
var ag=af&&af.options;
return ag&&ag.modal&&ag.visible&&ag.appendTo===ac.options.appendTo&&ae.is(W);
}).sort(function(ae,af){return +a(ae).css("zIndex")-+a(af).css("zIndex");
});
ac=null;
return ad;
},_object:function(ad){var ac=ad.children(B);
var ae=u.widgetInstance(ac);
if(ae instanceof Y){return ae;
}return V;
},center:function(){var ai=this,af=ai.options.position,aj=ai.wrapper,ac=a(window),ah=0,ag=0,ae,ad;
if(ai.options.isMaximized){return ai;
}if(!ai.options.pinned){ah=ac.scrollTop();
ag=ac.scrollLeft();
}ad=ag+Math.max(0,(ac.width()-aj.width())/2);
ae=ah+Math.max(0,(ac.height()-aj.height()-parseInt(aj.css("paddingTop"),10))/2);
aj.css({left:ad,top:ae});
af.top=ae;
af.left=ad;
return ai;
},title:function(ad){var ae=this,ai=ae.wrapper,ac=ae.options,ag=ai.children(E),af=ag.children(D),ah;
if(!arguments.length){return af.text();
}if(ad===false){ai.addClass("k-window-titleless");
ag.remove();
}else{if(!ag.length){ai.prepend(T.titlebar(ac));
ae._actions();
ag=ai.children(E);
}else{af.html(ad);
}ah=ag.outerHeight();
ai.css("padding-top",ah);
ag.css("margin-top",-ah);
}ae.options.title=ad;
return ae;
},content:function(ae,ad){var ac=this.wrapper.children(B),af=ac.children(".km-scroll-container");
ac=af[0]?af:ac;
if(!i(ae)){return ac.html();
}this.angular("cleanup",function(){return{elements:ac.children()};
});
u.destroy(this.element.children());
ac.empty().html(ae);
this.angular("compile",function(){var ag=[];
for(var ah=ac.length;
--ah>=0;
){ag.push({dataItem:ad});
}return{elements:ac.children(),data:ag};
});
return this;
},open:function(){var ai=this,aj=ai.wrapper,ae=ai.options,ah=ae.animation.open,ac=aj.children(B),af,ad=a(document);
if(!ai.trigger(J)){if(ai._closing){aj.kendoStop(true,true);
}ai._closing=false;
ai.toFront();
if(ae.autoFocus){ai.element.focus();
}ae.visible=true;
if(ae.modal){af=ai._overlay(false);
af.kendoStop(true,true);
if(ah.duration&&u.effects.Fade){var ag=u.fx(af).fadeIn();
ag.duration(ah.duration||0);
ag.endValue(0.5);
ag.play();
}else{af.css("opacity",0.5);
}af.show();
}if(!aj.is(W)){ac.css(K,q);
aj.show().kendoStop().kendoAnimate({effects:ah.effects,duration:ah.duration,complete:M(this._activate,this)});
}}if(ae.isMaximized){ai._documentScrollTop=ad.scrollTop();
ai._documentScrollLeft=ad.scrollLeft();
a("html, body").css(K,q);
}return ai;
},_activate:function(){var ac=this.options.scrollable!==false;
if(this.options.autoFocus){this.element.focus();
}this.element.css(K,ac?"":"hidden");
this.trigger(b);
},_removeOverlay:function(ai){var ae=this._modals();
var af=this.options;
var ad=af.modal&&!ae.length;
var ag=af.modal?this._overlay(true):a(V);
var ac=af.animation.close;
if(ad){if(!ai&&ac.duration&&u.effects.Fade){var ah=u.fx(ag).fadeOut();
ah.duration(ac.duration||0);
ah.startValue(0.5);
ah.play();
}else{this._overlay(false).remove();
}}else{if(ae.length){this._object(ae.last())._overlay(true);
}}},_close:function(ag){var ah=this,ai=ah.wrapper,ae=ah.options,af=ae.animation.open,ad=ae.animation.close,ac=a(document);
if(ai.is(W)&&!ah.trigger(e,{userTriggered:!ag})){if(ah._closing){return;
}ah._closing=true;
ae.visible=false;
a(A).each(function(al,ak){var aj=a(ak).children(B);
if(ak!=ai&&aj.find("> ."+t).length>0){aj.children(x).remove();
}});
this._removeOverlay();
ai.kendoStop().kendoAnimate({effects:ad.effects||af.effects,reverse:ad.reverse===true,duration:ad.duration,complete:M(this._deactivate,this)});
}if(ah.options.isMaximized){a("html, body").css(K,"");
if(ah._documentScrollTop&&ah._documentScrollTop>0){ac.scrollTop(ah._documentScrollTop);
}if(ah._documentScrollLeft&&ah._documentScrollLeft>0){ac.scrollLeft(ah._documentScrollLeft);
}}},_deactivate:function(){var ad=this;
ad.wrapper.hide().css("opacity","");
ad.trigger(h);
if(ad.options.modal){var ac=ad._object(ad._modals().last());
if(ac){ac.toFront();
}}},close:function(){this._close(true);
return this;
},_actionable:function(ac){return a(ac).is(U+","+U+" .k-icon,:input,a");
},_shouldFocus:function(ae){var ac=c(),ad=this.element;
return this.options.autoFocus&&!a(ac).is(ad)&&!this._actionable(ae)&&(!ad.find(ac).length||!ad.find(ae).length);
},toFront:function(ad){var ah=this,aj=ah.wrapper,ac=aj[0],ak=+aj.css(ab),ae=ak,ag=(ad&&ad.target)||null;
a(A).each(function(an,am){var ao=a(am),ap=ao.css(ab),al=ao.children(B);
if(!isNaN(ap)){ak=Math.max(+ap,ak);
}if(am!=ac&&al.find("> ."+t).length>0){al.append(T.overlay);
}});
if(!aj[0].style.zIndex||ae<ak){aj.css(ab,ak+2);
}ah.element.find("> .k-overlay").remove();
if(ah._shouldFocus(ag)){ah.element.focus();
var af=a(window).scrollTop(),ai=parseInt(aj.position().top,10);
if(ai>0&&ai<af){if(af>0){a(window).scrollTop(ai);
}else{aj.css("top",af);
}}}aj=null;
return ah;
},toggleMaximization:function(){if(this._closing){return this;
}return this[this.options.isMaximized?"restore":"maximize"]();
},restore:function(){var ag=this;
var ae=ag.options;
var ad=ae.minHeight;
var af=ag.restoreOptions;
var ac=a(document);
if(!ae.isMaximized&&!ae.isMinimized){return ag;
}if(ad&&ad!=Infinity){ag.wrapper.css("min-height",ad);
}ag.wrapper.css({position:ae.pinned?"fixed":"absolute",left:af.left,top:af.top,width:af.width,height:af.height}).removeClass(G).find(".k-window-content,.k-resize-handle").show().end().find(".k-window-titlebar .k-i-restore").parent().remove().end().end().find(H).parent().show().end().end().find(L).parent().show();
ag.options.width=af.width;
ag.options.height=af.height;
a("html, body").css(K,"");
if(this._documentScrollTop&&this._documentScrollTop>0){ac.scrollTop(this._documentScrollTop);
}if(this._documentScrollLeft&&this._documentScrollLeft>0){ac.scrollLeft(this._documentScrollLeft);
}ae.isMaximized=ae.isMinimized=false;
ag.resize();
return ag;
},maximize:R("maximize",function(){var ae=this,af=ae.wrapper,ad=af.position(),ac=a(document);
p(ae.restoreOptions,{left:ad.left,top:ad.top});
af.css({left:0,top:0,position:"fixed"}).addClass(G);
this._documentScrollTop=ac.scrollTop();
this._documentScrollLeft=ac.scrollLeft();
a("html, body").css(K,q);
ae.options.isMaximized=true;
ae._onDocumentResize();
}),minimize:R("minimize",function(){var ac=this;
ac.wrapper.css({height:"",minHeight:""});
ac.element.hide();
ac.options.isMinimized=true;
}),pin:function(ac){var ae=this,ag=a(window),ah=ae.wrapper,af=parseInt(ah.css("top"),10),ad=parseInt(ah.css("left"),10);
if(ac||!ae.options.pinned&&!ae.options.isMaximized){ah.css({position:"fixed",top:af-ag.scrollTop(),left:ad-ag.scrollLeft()});
ah.children(E).find(y).addClass("k-i-unpin").removeClass("k-i-pin");
ae.options.pinned=true;
}},unpin:function(){var ad=this,af=a(window),ag=ad.wrapper,ae=parseInt(ag.css("top"),10),ac=parseInt(ag.css("left"),10);
if(ad.options.pinned&&!ad.options.isMaximized){ag.css({position:"",top:ae+af.scrollTop(),left:ac+af.scrollLeft()});
ag.children(E).find(z).addClass("k-i-pin").removeClass("k-i-unpin");
ad.options.pinned=false;
}},_onDocumentResize:function(){var ad=this,ag=ad.wrapper,af=a(window),ah=u.support.zoomLevel(),ae,ac;
if(!ad.options.isMaximized){return;
}ae=af.width()/ah;
ac=af.height()/ah-parseInt(ag.css("padding-top"),10);
ag.css({width:ae,height:ac});
ad.options.width=ae;
ad.options.height=ac;
ad.resize();
},refresh:function(af){var ah=this,ae=ah.options,ac=a(ah.element),ad,ag,ai;
if(!s(af)){af={url:af};
}af=p({},ae.content,af);
ag=i(ae.iframe)?ae.iframe:af.iframe;
ai=af.url;
if(ai){if(!i(ag)){ag=!r(ai);
}if(!ag){ah._ajaxRequest(af);
}else{ad=ac.find("."+t)[0];
if(ad){ad.src=ai||ad.src;
}else{ac.html(T.contentFrame(p({},ae,{content:af})));
}ac.find("."+t).unbind("load"+I).on("load"+I,M(this._triggerRefresh,this));
}}else{if(af.template){ah.content(S(af.template)({}));
}ah.trigger(N);
}ac.toggleClass("k-window-iframecontent",!!ag);
return ah;
},_triggerRefresh:function(){this.trigger(N);
},_ajaxComplete:function(){clearTimeout(this._loadingIconTimeout);
this.wrapper.find(O).removeClass(F);
},_ajaxError:function(ad,ac){this.trigger(n,{status:ac,xhr:ad});
},_ajaxSuccess:function(ac){return function(ad){var ae=ad;
if(ac){ae=S(ac)(ad||{});
}this.content(ae,ad);
this.element.prop("scrollTop",0);
this.trigger(N);
};
},_showLoading:function(){this.wrapper.find(O).addClass(F);
},_ajaxRequest:function(ac){this._loadingIconTimeout=setTimeout(M(this._showLoading,this),100);
a.ajax(p({type:"GET",dataType:"html",cache:false,error:M(this._ajaxError,this),complete:M(this._ajaxComplete,this),success:M(this._ajaxSuccess(ac.template),this)},ac));
},_destroy:function(){if(this.resizing){this.resizing.destroy();
}if(this.dragging){this.dragging.destroy();
}this.wrapper.off(I).children(B).off(I).end().find(".k-resize-handle,.k-window-titlebar").off(I);
a(window).off("resize"+I+this._marker);
clearTimeout(this._loadingIconTimeout);
X.fn.destroy.call(this);
this.unbind(V);
u.destroy(this.wrapper);
this._removeOverlay(true);
},destroy:function(){this._destroy();
this.wrapper.empty().remove();
this.wrapper=this.appendTo=this.element=a();
},_createWindow:function(){var ac=this.element,af=this.options,ad,ag,ae=u.support.isRtl(ac);
if(af.scrollable===false){ac.attr("style","overflow:hidden;");
}ag=a(T.wrapper(af));
ad=ac.find("iframe:not(.k-content)").map(function(){var ah=this.getAttribute("src");
this.src="";
return ah;
});
ag.toggleClass("k-rtl",ae).appendTo(this.appendTo).append(ac).find("iframe:not(.k-content)").each(function(ah){this.src=ad[ah];
});
ag.find(".k-window-title").css(ae?"left":"right",ag.find(".k-window-actions").outerWidth()+10);
ac.css("visibility","").show();
ac.find("[data-role=editor]").each(function(){var ah=a(this).data("kendoEditor");
if(ah){ah.refresh();
}});
ag=ac=null;
}});
T={wrapper:S("<div class='k-widget k-window' />"),action:S("<a role='button' href='\\#' class='k-window-action k-link'><span role='presentation' class='k-icon k-i-#= name.toLowerCase() #'>#= name #</span></a>"),titlebar:S("<div class='k-window-titlebar k-header'>&nbsp;<span class='k-window-title'>#= title #</span><div class='k-window-actions' /></div>"),overlay:"<div class='k-overlay' />",contentFrame:S("<iframe frameborder='0' title='#= title #' class='"+t+"' src='#= content.url #'>This page requires frames in order to show content</iframe>"),resizeHandle:S("<div class='k-resize-handle k-resize-#= data #'></div>")};
function aa(ad){var ac=this;
ac.owner=ad;
ac._draggable=new k(ad.wrapper,{filter:">"+C,group:ad.wrapper.id+"-resizing",dragstart:M(ac.dragstart,ac),drag:M(ac.drag,ac),dragend:M(ac.dragend,ac)});
ac._draggable.userEvents.bind("press",M(ac.addOverlay,ac));
ac._draggable.userEvents.bind("release",M(ac.removeOverlay,ac));
}aa.prototype={addOverlay:function(){this.owner.wrapper.append(T.overlay);
},removeOverlay:function(){this.owner.wrapper.find(x).remove();
},dragstart:function(ac){var ad=this;
var ae=ad.owner;
var af=ae.wrapper;
ad.elementPadding=parseInt(af.css("padding-top"),10);
ad.initialPosition=u.getOffset(af,"position");
ad.resizeDirection=ac.currentTarget.prop("className").replace("k-resize-handle k-resize-","");
ad.initialSize={width:af.width(),height:af.height()};
ad.containerOffset=u.getOffset(ae.appendTo,"position");
af.children(C).not(ac.currentTarget).hide();
a(d).css(g,ac.currentTarget.css(g));
},drag:function(ae){var ak=this,an=ak.owner,ao=an.wrapper,aj=an.options,ad=ak.resizeDirection,ac=ak.containerOffset,af=ak.initialPosition,ag=ak.initialSize,ai,ah,al,am,ap=Math.max(ae.x.location,ac.left),aq=Math.max(ae.y.location,ac.top);
if(ad.indexOf("e")>=0){ai=ap-af.left;
ao.width(f(ai,aj.minWidth,aj.maxWidth));
}else{if(ad.indexOf("w")>=0){am=af.left+ag.width;
ai=f(am-ap,aj.minWidth,aj.maxWidth);
ao.css({left:am-ai-ac.left,width:ai});
}}if(ad.indexOf("s")>=0){ah=aq-af.top-ak.elementPadding;
ao.height(f(ah,aj.minHeight,aj.maxHeight));
}else{if(ad.indexOf("n")>=0){al=af.top+ag.height;
ah=f(al-aq,aj.minHeight,aj.maxHeight);
ao.css({top:al-ah-ac.top,height:ah});
}}if(ai){an.options.width=ai+"px";
}if(ah){an.options.height=ah+"px";
}an.resize();
},dragend:function(ac){var ad=this,ae=ad.owner,af=ae.wrapper;
af.children(C).not(ac.currentTarget).show();
a(d).css(g,"");
if(ae.touchScroller){ae.touchScroller.reset();
}if(ac.keyCode==27){af.css(ad.initialPosition).css(ad.initialSize);
}ae.trigger(Q);
return false;
},destroy:function(){if(this._draggable){this._draggable.destroy();
}this._draggable=this.owner=null;
}};
function Z(ae,ac){var ad=this;
ad.owner=ae;
ad._draggable=new k(ae.wrapper,{filter:ac,group:ae.wrapper.id+"-moving",dragstart:M(ad.dragstart,ad),drag:M(ad.drag,ad),dragend:M(ad.dragend,ad),dragcancel:M(ad.dragcancel,ad)});
ad._draggable.userEvents.stopPropagation=false;
}Z.prototype={dragstart:function(ae){var ag=this.owner,af=ag.element,ac=af.find(".k-window-actions"),ad=u.getOffset(ag.appendTo);
ag.trigger(l);
ag.initialWindowPosition=u.getOffset(ag.wrapper,"position");
ag.startPosition={left:ae.x.client-ag.initialWindowPosition.left,top:ae.y.client-ag.initialWindowPosition.top};
if(ac.length>0){ag.minLeftPosition=ac.outerWidth()+parseInt(ac.css("right"),10)-af.outerWidth();
}else{ag.minLeftPosition=20-af.outerWidth();
}ag.minLeftPosition-=ad.left;
ag.minTopPosition=-ad.top;
ag.wrapper.append(T.overlay).children(C).hide();
a(d).css(g,ae.currentTarget.css(g));
},drag:function(ad){var ah=this.owner,ag=ah.options.position,af=Math.max(ad.y.client-ah.startPosition.top,ah.minTopPosition),ae=Math.max(ad.x.client-ah.startPosition.left,ah.minLeftPosition),ac={left:ae,top:af};
a(ah.wrapper).css(ac);
ag.top=af;
ag.left=ae;
},_finishDrag:function(){var ac=this.owner;
ac.wrapper.children(C).toggle(!ac.options.isMinimized).end().find(x).remove();
a(d).css(g,"");
},dragcancel:function(ac){this._finishDrag();
ac.currentTarget.closest(A).css(this.owner.initialWindowPosition);
},dragend:function(){this._finishDrag();
this.owner.trigger(j);
return false;
},destroy:function(){if(this._draggable){this._draggable.destroy();
}this._draggable=this.owner=null;
}};
u.ui.plugin(Y);
})(window.kendo.jQuery);
})();
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b){b();
});
