Type.registerNamespace("Telerik.Web.UI");
(function(b,a){b.FileExplorerHelper={extractExtensionFromDataItem:function(c){return this.parseExtension(c.Extension,c.Name);
},parseExtension:function(d,e){var c=d;
if(!c){c=(e&&e.indexOf(".")>0)?e:"";
}return c.substr(c.lastIndexOf(".")+1).toLowerCase();
},stripExtension:function(d){var c=new RegExp(String.format("\\.{0}$",d.get_extension()));
return d.get_name().replace(c,"");
},extractPathFromDataItem:function(c,d){return c.Path||this.buildPathFromName(c.Name,d);
},extractPathFromExplorerItem:function(d,c){return d.get_path()||this.buildPathFromName(d.get_name(),c);
},buildPathFromName:function(d,c){var f=c.get_pathSeparator();
var e=c.get_currentDirectory();
if(e&&e.charAt(e.length-1)!=f.charAt(0)){e+=f;
}e+=d;
return e;
},webImageRegExp:/^png$|^gif$|^bmp$|^jpg$|^jpeg$|^tiff$|^ico$|^webp$/i,isWebImage:function(c){return c&&this.webImageRegExp.test(c.replace(".",""));
},getThumbnailCSSExtension:function(c){var e=this.isFolderItem(c);
var d=e?"folder":this.extractExtensionFromDataItem(c);
return this.isWebImage(d)?"rfeImageView":d;
},hideContextMenu:function(c){if(c&&c._shown){c.hide();
}},isFolderItem:function(c){return(typeof(c.Length)==="undefined"||c.Length==null);
},canDelete:function(c){return(c&b.FileExplorerItemPermissions.Delete)!=0;
},canUpload:function(c){return(c&b.FileExplorerItemPermissions.Upload)!=0;
}};
a.extend({registerjQueryEvents:function(c,d){a.each(d,function(f,e){c.prototype["add_"+e]=function(g){a(this).on(e,g);
};
c.prototype["remove_"+e]=function(g){a(this).off(e,g);
};
});
}});
})(Telerik.Web.UI,$telerik.$);
Type.registerNamespace("Telerik.Web.UI.FileExplorer");
(function(b,a){b.FileExplorer.IFileListView=function(c){};
b.FileExplorer.IFileListView.prototype={bindToServerData:function(d,c){},dataBind:function(){},get_id:function(){},get_dataSource:function(){},set_dataSource:function(c){},get_pageIndex:function(){},set_pageIndex:function(d,c){},get_pageSize:function(){},set_pageSize:function(c){},get_pageCount:function(){},get_itemsCount:function(){},get_items:function(){},get_name:function(){},selectItemsByName_Fast:function(c){},selectItemByName:function(c){},get_selectedItems:function(){},selectDefaultItem:function(){},clearSelection:function(){},getItemByName:function(c){},getItemByPath:function(c){},get_element:function(){},get_container:function(){},focusPagerControl:function(){},attachEventHandlers:function(c){},filter:function(c){},show:function(){},hide:function(){},getScroll:function(){},scrollTo:function(){},add_sort:function(c){},remove_sort:function(c){},add_page:function(c){},remove_page:function(c){},add_open:function(c){},remove_open:function(c){},add_itemSelect:function(c){},remove_itemSelect:function(c){},add_contextMenu:function(c){},remove_contextMenu:function(c){},add_hideContextMenu:function(c){},remove_hideContextMenu:function(c){},add_itemDragStart:function(c){},remove_itemDragStart:function(c){},add_itemDragging:function(c){},remove_itemDragging:function(c){},add_itemDrop:function(c){},remove_itemDrop:function(c){},add_itemDropComplete:function(c){},remove_itemDropComplete:function(c){}};
b.FileExplorer.IFileListView.registerInterface("Telerik.Web.UI.FileExplorer.IFileListView");
b.FileExplorer.ClientBindableFileListView=function(c){this.control=c;
this._name="";
};
b.FileExplorer.ClientBindableFileListView.prototype={bindToServerData:function(d,c){if(!d||!d.data){return;
}this._isBindingFlag=true;
this.control.set_virtualItemCount(d.count);
this.control.set_dataSource(d.data);
if(!isNaN(c)){this.set_currentPageIndex(c,true);
}this.dataBind();
this._updatePageControl(d.count);
this._isBindingFlag=false;
},dataBind:function(){return this.control.dataBind();
},get_dataSource:function(){return this.control.get_dataSource();
},set_dataSource:function(c){this.control.set_dataSource(c);
},get_pageSize:function(){return this.control.get_pageSize();
},set_pageSize:function(c){this.control.set_pageSize(c);
},get_pageCount:function(){return this.control.get_pageCount();
},get_itemsCount:function(){return this.control.get_virtualItemCount();
},get_currentPageIndex:function(){return this.control.get_currentPageIndex();
},set_currentPageIndex:function(d,c){this.control.set_currentPageIndex(d,c);
},get_name:function(){return this._name;
},selectItemByName:function(d){var c=this.getItemIndexByName(d);
if(c!=-1){this._selectIndex(c);
}},clearSelection:function(){this.control.clearSelectedItems();
},getItemByName:function(c){return this.getItemBy(c,"Name");
},getItemByPath:function(c){return this.getItemBy(c,"Path");
},getItemBy:function(h,g){var c=this.get_dataSource();
if(c){for(var e=0,f=c.length;
e<f;
e++){var d=c[e];
if(d[g]==h){return d;
}}}return null;
},getItemIndexByName:function(f){var c=this.get_dataSource();
if(c){for(var d=0,e=c.length;
d<e;
d++){if(c[d].Name==f){return d;
}}}return -1;
},show:function(){this.get_element().style.display="";
},hide:function(){this.get_element().style.display="none";
},raiseEvent:function(d,c){a(this).trigger(d,[c]);
},_focus:function(c){b.FileExplorer.FileList.prototype._focus(c);
},_filterItem:function(e,d){var f=e.Name.toLowerCase();
var c=e.Extension?e.Extension.toLowerCase():false;
return(f==".."&&!c)||f.indexOf(this.filterKeyWord)!=-1||(c&&c.indexOf(this.filterKeyWord)!=-1);
},_storeUnfilteredData:function(c){this._dataCache=Array.clone(c);
},_updatePageControl:function(c){},_selectIndex:function(c){this.control.selectItem(c);
}};
a.registerjQueryEvents(b.FileExplorer.ClientBindableFileListView,["sort","page","open","itemSelect","contextMenu","hideContextMenu","itemDragStart","itemDragging","itemDrop","itemDropComplete"]);
b.FileExplorer.ClientBindableFileListView.registerClass("Telerik.Web.UI.FileExplorer.ClientBindableFileListView");
})(Telerik.Web.UI,$telerik.$);
Type.registerNamespace("Telerik.Web.UI.FileExplorer");
(function(c,a,b){b.FileList=function(d){b.FileList.initializeBase(this);
this.options=a.extend({grid:null,listView:null,contextMenu:null,container:null,fileExplorer:null},d||{});
this._folderCache={};
this._selectedFiles=[];
this._forceServerFilteringFlags={};
this.fileListViewsMap={};
this._sortExpression="";
this._attachEventHandlers();
this.helpers=Telerik.Web.UI.FileExplorerHelper;
};
b.FileList.prototype={dataBind:function(){if(a.isArray(this.get_dataSource())){this._listControl.dataBind();
}},bindToServerData:function(e,d){this._currentServerData=e;
if(e&&e.data&&!isNaN(e.count)){this._listControl.bindToServerData(e,d);
}},bindToData:function(d){this.set_dataSource(d);
this.dataBind();
},get_dataSource:function(){return this._listControl.get_dataSource();
},set_dataSource:function(d){this._listControl.set_dataSource(d);
},get_pageSize:function(){return this._listControl.get_pageSize();
},set_pageSize:function(d){this._listControl.set_pageSize(d);
},get_control:function(){return this._listControl;
},get_allowMultiSelect:function(){return this._listControl.get_allowMultiSelect();
},get_view:function(){return this._listControl;
},get_contextMenu:function(){return this.options.contextMenu;
},get_fileExplorer:function(){return this.options.fileExplorer;
},get_element:function(){return this._listControl.get_element();
},get_items:function(){return this._listControl.get_items();
},get_selectedItems:function(){return this._listControl.get_selectedItems();
},get_selectedItemsDataAndElement:function(){return this._listControl.get_selectedItemsDataAndElement();
},getSelectedFiles:function(){return this.get_selectedItems();
},get_selectedItem:function(){var d=this.get_selectedItems();
return d.length>0?d[0]:null;
},get_filterTextBox:function(d){return a("input.rfeFilterTxt",(d||this.get_view()).get_container()).get(0);
},fileListViews:[],activeFileListView:null,registerFileListView:function(d){if(!d||!d.get_name){return;
}if(!this.fileListViewsMap[d.get_name()]){this.fileListViews.push(d);
}this.fileListViewsMap[d.get_name()]=d;
this._attachViewEvents(d);
d.hide();
},chooseFileListView:function(e){var d=this.getFileListViewByName(e);
if(d&&d!=this._listControl){d.show();
if(this._listControl){this._listControl.hide();
d.bindToServerData(this._currentServerData,this._listControl.get_pageIndex());
a(this.get_filterTextBox(d)).val(this._filterKeyWord||"");
}this._listControl=d;
}},getFileListViewByName:function(d){return this.fileListViewsMap[d];
},selectFile:function(d){var e=d.Name||(d.get_name()?d.get_name():null);
if(e){this.selectFileByName(e);
}},selectFileByName:function(d){this._clearStoredSelection();
this._listControl.selectItemByName(d);
},selectFileList:function(d){this._listControl.selectItemsByName_Fast(d);
},selectDefaultFile:function(){this._clearStoredSelection();
return this._listControl.selectDefaultItem();
},clearSelection:function(){this._listControl.clearSelection();
},findFileByName:function(d){return this._listControl.getItemByName(d);
},findFileByPath:function(d){return this._listControl.getItemByPath(d);
},get_grid:function(){return this.options.grid;
},get_listView:function(){return this.options.listView;
},open:function(e){var d=c.FileExplorerItem.isInstanceOfType(e)?e:this._toFileItem(e);
this.options.fileExplorer.open(d);
},focus:function(){this._focus(this._listControl.get_element());
},focusPagerControl:function(){this._listControl.focusPagerControl();
},attachEventHandlers:function(d){if(d){this._attachEventHandlers();
}else{this._detachEventHandlers();
}},raiseCommand:function(d){this.raiseEvent("command",d);
},raiseEvent:function(f,d){var e=this.get_events().getHandler(f);
if(e){e(this,d||Sys.EventArgs.Empty);
}},showFolderFileList:function(e){if(this._currentFolder!=e){var d=this._retrieveFromCache(e);
if(d){this.clearFilter();
this._clearPageState();
this._currentFolder=e;
this._applyServerData(d,e);
}else{this.refreshFileList(e);
}}},refreshFileList:function(d){this._storeSelectedFiles(d);
this.clearFilter();
this._clearPageState();
this._currentFolder=d;
this._getServerDataCallback();
},sort:function(d){this._storeSelectedFiles(this._currentFolder);
this.clearFilter();
this._sortExpression=d||"";
this._getServerDataCallback();
},showPageContent:function(e,d){this._storeSelectedFiles(this._currentFolder);
this._startIndex=e||0;
this._pageSize=d||this.get_pageSize();
this._getServerDataCallback();
},filterList:function(d){this._filterListWithEvent(d);
},doFiltering:function(d){if(this._shouldForceServerFiltering()){this._forceServerFiltering();
this.serverFilter(d);
}else{this.clientFilter(d);
}},serverFilter:function(d){this._setFilterKeyword(d);
this._clearPageState();
this._getServerDataCallback();
},clientFilter:function(f){this._setFilterKeyword(f);
var d=this._retrieveOriginalFilterData();
if(d){var e=this._filterItems(d.data);
this.bindToServerData(this._toServerDataFormat(e));
}},clearFilter:function(){this._filterKeyWord="";
a(this.get_filterTextBox()).val("");
},clearFolderCache:function(d){this._clearFolderCache(d);
},dispose:function(){this.attachEventHandlers(false);
},_chooseListControl:function(){if(this.options.grid){return new b.GridFileList(this.options.grid);
}else{if(this.options.listView){return new b.ListViewFileList(this.options.listView);
}else{return null;
}}},_focus:function(d){Telerik.Web.UI.RadFileExplorer.prototype._focus(d);
},_toFileItem:function(d){if(!d){return null;
}var e=d.Name;
var f=d.Length;
return $create(Telerik.Web.UI.FileExplorerItem,{type:(this.helpers.isFolderItem(d)?Telerik.Web.UI.FileExplorerItemType.Directory:Telerik.Web.UI.FileExplorerItemType.File),permissions:d.Permissions,name:e,path:this.helpers.extractPathFromDataItem(d,this.options.fileExplorer),extension:this.helpers.extractExtensionFromDataItem(d),size:f,url:d.Url});
},_storeSelectedFiles:function(f){if(this._currentFolder==f){var g=this.get_selectedItems();
if(g.length>=this._selectedFiles.length){this._clearStoredSelection();
for(var d=0,e=g.length;
d<e;
d++){this._selectedFiles.push(g[d].Name);
}}this._viewScroll=this.get_view().getScroll();
}else{this._clearStoredSelection();
this._viewScroll=0;
}},_restoreSelectedFiles:function(){if(this._selectedFiles===null){this._selectedFiles=[];
return;
}this.clearSelection();
this.selectFileList(this._selectedFiles);
this.get_view().scrollTo(this._viewScroll);
},_clearStoredSelection:function(){this._selectedFiles=[];
},_setFilterKeyword:function(d){this._filterKeyWord=d.toLowerCase();
},_retrieveOriginalFilterData:function(){var d=this._retrieveFromCache();
if(!d){d=this._toServerDataFormat(this.get_items());
this._cacheFilesData(d);
}return d;
},_clearPageState:function(){this._pageSize=this._startIndex=null;
this._listControl.set_pageIndex(0,true);
},_getServerDataCallback:function(){this.raiseEvent("callback");
var g=this._currentFolder;
var f=Sys.Serialization.JavaScriptSerializer.serialize({path:g||this.options.fileExplorer.get_currentDirectory(),sortExpression:this._sortExpression||"",startIndex:this._startIndex||0,maxRowNumber:this._pageSize||this.get_pageSize(),filterKeyWord:this._filterKeyWord||""});
var d=Function.createDelegate(this,this._onCallbackResponse);
var e=Function.createDelegate(this,this._onErrorCallback);
WebForm_DoCallback(this.options.fileExplorer._uniqueId,f,d,g,e,true);
},_onCallbackResponse:function(e,d){this.raiseEvent("callbackComplete");
if(!e){return;
}var f=Sys.Serialization.JavaScriptSerializer.deserialize(e);
if(f&&f.data){this._fixMissingPath(f.data);
}if(!this._filterKeyWord){this._cacheFilesData(f);
}this.clearSelection();
this._applyServerData(f,d);
this._restoreSelectedFiles();
},_applyServerData:function(e,d){this.bindToServerData(e);
this.raiseEvent("folderLoaded",new b.FilePathEventArgs(d));
},_onErrorCallback:function(){alert("Callback has failed");
},_toServerDataFormat:function(d){return{count:d.length,data:d};
},_fixMissingPath:function(d){for(var e=0,f=d.length;
e<f;
e++){if(!d.Path){d.Path=this.helpers.buildPathFromName(d.Name,this.options.fileExplorer);
}}},_filterItems:function(d){return a.grep(d,a.proxy(this._filterItem,this));
},_filterItem:function(e,d){var f=e.Name.toLowerCase();
return(f==".."&&!e.Extension)||f.indexOf(this._filterKeyWord)!=-1;
},_raiseFilterEvent:function(d){this.raiseEvent("filter",d);
return d;
},_cacheFilesData:function(d,e){this._folderCache[this._buildCacheKey(e)]=d;
},_retrieveFromCache:function(d){return this._folderCache[this._buildCacheKey(d)];
},_clearFoldersCache:function(d){for(var e=0;
e<d.length;
e++){this._clearFolderCache(d[e].Path);
}},_clearFolderCache:function(d){this._cacheFilesData(null,d);
},_buildCacheKey:function(d){return(d||this._currentFolder)+"***"+this._sortExpression;
},_shouldForceServerFiltering:function(){return this._listControl.get_pageCount()>1||this._forceServerFilteringFlags[this._currentFolder];
},_forceServerFiltering:function(){this._forceServerFilteringFlags[this._currentFolder]=true;
},_filterListWithEvent:function(f,d){var e=this._raiseFilterEvent(new c.FileExplorerFilterEventArgs(f,d||null));
f=e.get_text();
if(!e.get_cancel()){this.doFiltering(f);
}},_attachEventHandlers:function(){this._emptySpaceContextHandler=Function.createDelegate(this,this._emptySpaceContextMenu);
$addHandler(this.options.fileExplorer.get_gridPane().getContentElement(),"contextmenu",this._emptySpaceContextHandler);
if(this.options.contextMenu){this.options.contextMenu.add_itemClicking(Function.createDelegate(this,this._onMenuItemClick));
this.options.contextMenu.add_hidden(Function.createDelegate(this,this._onMenuClose));
}},_detachEventHandlers:function(){this._listControl.attachEventHandlers(false);
},_attachViewEvents:function(e){var d=this.get_filterTextBox(e);
if(d){$telerik.addHandler(d,"keydown",function(f){if(f.keyCode==13){$telerik.cancelRawEvent(f.rawEvent);
}},true);
$telerik.addHandler(d,"keyup",Function.createDelegate(this,this._keyUpFilterTextBox),true);
}e.attachEventHandlers(true);
e.add_sort(Function.createDelegate(this,this._onSort));
e.add_page(Function.createDelegate(this,this._onPaging));
e.add_open(Function.createDelegate(this,this._onOpen));
e.add_itemSelect(Function.createDelegate(this,this._onSelectItem));
e.add_contextMenu(Function.createDelegate(this,this._onItemContextMenu));
e.add_hideContextMenu(Function.createDelegate(this,this._onHideContextMenu));
e.add_itemDragStart(Function.createDelegate(this,this._onItemDragStart));
e.add_itemDragging(Function.createDelegate(this,this._onItemDragging));
e.add_itemDrop(Function.createDelegate(this,this._onItemDrop));
e.add_itemDropComplete(Function.createDelegate(this,this._onItemDropComplete));
},_onSort:function(e,d){this.sort(d.get_sortExpression());
},_onPaging:function(e,d){this.showPageContent(d.get_startIndex(),d.get_pageSize());
},_onOpen:function(e,d){this.open(d||this.get_selectedItem());
},_onSelectItem:function(e,d){this.raiseEvent("itemSelect",new b.FileListItemEventArgs(this._toFileItem(d)));
},_onItemDragStart:function(e,d){var f=d.get_item();
d.set_cancel(!!f&&f.Name==="..");
if(this.options.contextMenu){this.options.contextMenu.hide();
}},_onItemDragging:function(f,d){var g=this.options.fileExplorer;
if(g._enableCopy){var e=d.get_domEvent().ctrlKey;
var h=Sys.UI.DomElement.containsCssClass(g.get_element(),g._copyCursorClassName);
if(e!=h){g._updateCopyCursor(e);
}}g._scrollTreeViewOnDrag(d.get_domEvent());
},_onItemDrop:function(g,d){var h=this.options.fileExplorer;
if(h._enableCopy){h._updateCopyCursor(false);
}var e=h._currentTreeNode||this._tryExtractNodeFromDomElement(d.get_targetElement());
if(e){if(!h._isNodeADirectory(e)){e=e.get_parent();
}var n=h._enableCopy&&d.get_domEvent().ctrlKey;
var l={isCopying:n,srcFolder:h.get_currentDirectory(),dstFolder:e.get_value()};
if(l.srcFolder==l.dstFolder){d.set_cancel(true);
}else{l.items=[];
var k=n?"copy":"move";
var f=d.get_items();
for(var m=0,r=f.length;
m<r;
m++){var p=f[m];
var j=this._toFileItem(p);
var o=j.isDirectory()?"D":"F";
var q=new Telerik.Web.UI.FileExplorerEventArgs(j,l.dstFolder);
h.raiseEvent(k,q);
if(!q.get_cancel()){Array.add(l.items,o+j.get_path());
}}h._gridRowDroppedParams=l;
}this._clearFolderCache(l.srcFolder);
this._clearFolderCache(l.dstFolder);
}else{d.set_cancel(true);
}},_onItemDropComplete:function(f,e){var g=this.options.fileExplorer;
var i=g._gridRowDroppedParams;
if(i){var d=i.isCopying?"CallbackFnCopy_":"GridDrag_";
d+=i.dstFolder+"***"+i.items.join("***");
var h=i.dstFolder+"***"+this._sortExpression;
g._folderCache[h]=null;
g._gridRowDroppedParams=null;
g._postbackTreeAjaxPanel(d);
}},_keyUpFilterTextBox:function(d){$telerik.cancelRawEvent(d.rawEvent);
var e=this.get_filterTextBox().value;
if(!this.options.fileExplorer.get_enableFilteringOnEnter()||d.keyCode==13||e==""){$telerik.cancelRawEvent(d.rawEvent);
this._filterListWithEvent(e,d.rawEvent);
return false;
}},_tryExtractNodeFromDomElement:function(d){var e=a(d).parents(".rtLI:first").get(0);
if(e){return e._item;
}return null;
},_emptySpaceContextMenu:function(d){var f=this.options.contextMenu;
var e=this.options.fileExplorer;
if(!f||!e._enabled){return;
}var g=this._toFileItem(this._lastContextMenuItem||this.get_selectedItem());
if(!g||g.get_name()===".."){g=e._getCurrentFolderItem();
}var h=e._setContextMenuItemsState(f,g.get_permissions(),!(this._lastContextMenuItem||this.get_selectedItem()));
if(h){f.show(d);
}return $telerik.cancelRawEvent(d);
},_onMenuItemClick:function(i,d){var g=this.options.fileExplorer;
var j=d.get_item().get_value();
var f=this._getContextMenuSelectedItem();
switch(j){case"Rename":if(f&&f.get_name()===".."){return;
}var h=g._allowFileExtensionRename?f.get_name():c.FileExplorerHelper.stripExtension(f);
var e=Function.createCallback(Function.createDelegate(g,function(l,m){if(l){this._renameItem(m,l);
}}),f);
g._showPromptDialog(e,{title:"Rename",value:h,inputValidator:g._validateFileNameInputDelegate,timeout:10});
break;
case"Delete":this._deleteSelectedItems();
break;
case"Open":this.open(f);
break;
case"NewFolder":g.createNewDirectory(this._currentFolder);
break;
case"Upload":g._showUploadWindow();
break;
case"Copy":g._copy("grid");
break;
case"Paste":var k=f;
if(k==null||!k.isDirectory()){k=g._getCurrentFolderItem();
}g._paste(k);
break;
}},_deleteSelectedItems:function(){this.options.fileExplorer.deleteSelectedItems();
},_onItemContextMenu:function(e,d){this._lastContextMenuItem=d;
},_onHideContextMenu:function(e,d){this.options.fileExplorer._hideContextMenus(new Sys.UI.DomEvent(d),false,"");
},_onMenuClose:function(){this._lastContextMenuItem=null;
},_getContextMenuSelectedItem:function(){var d=this._toFileItem(this._getContextMenuSelectedDataItem());
if(!d||d.get_name()===".."){d=this.options.fileExplorer._getCurrentFolderItem();
}return d;
},_getContextMenuSelectedDataItem:function(){return this._lastContextMenuItem||this.get_selectedItem();
}};
a.registerControlProperties(b.FileList,{allowPaging:false});
a.registerControlEvents(b.FileList,["command","filter","folderLoaded","itemSelect","callback","callbackComplete"]);
b.FileList.registerClass("Telerik.Web.UI.FileExplorer.FileList",Sys.Component);
})(Telerik.Web.UI,$telerik.$,Telerik.Web.UI.FileExplorer);
Type.registerNamespace("Telerik.Web.UI.FileExplorer");
(function(c,a,b){b.FileListSortEventArgs=function(d){b.FileListSortEventArgs.initializeBase(this);
this.set_sortExpression(d);
};
a.registerControlProperties(b.FileListSortEventArgs,{sortExpression:""});
b.FileListSortEventArgs.registerClass("Telerik.Web.UI.FileExplorer.FileListSortEventArgs",Sys.EventArgs);
b.FileListPageEventArgs=function(e,d){b.FileListPageEventArgs.initializeBase(this);
this.set_startIndex(e);
this.set_pageSize(d);
};
a.registerControlProperties(b.FileListPageEventArgs,{startIndex:0,pageSize:0});
b.FileListPageEventArgs.registerClass("Telerik.Web.UI.FileExplorer.FileListPageEventArgs",Sys.EventArgs);
b.FileListItemEventArgs=function(d){b.FileListItemEventArgs.initializeBase(this);
this.set_item(d);
};
a.registerControlProperties(b.FileListItemEventArgs,{item:""});
b.FileListItemEventArgs.registerClass("Telerik.Web.UI.FileExplorer.FileListItemEventArgs",Sys.EventArgs);
b.FileListItemCancelableEventArgs=function(d){b.FileListItemCancelableEventArgs.initializeBase(this);
this.set_item(d);
};
a.registerControlProperties(b.FileListItemCancelableEventArgs,{item:""});
b.FileListItemCancelableEventArgs.registerClass("Telerik.Web.UI.FileExplorer.FileListItemCancelableEventArgs",Sys.CancelEventArgs);
b.FileListItemsCancelableEventArgs=function(f,e,d){b.FileListItemsCancelableEventArgs.initializeBase(this);
this.set_items(f);
this.set_domEvent(e);
this.set_targetElement(d);
};
a.registerControlProperties(b.FileListItemsCancelableEventArgs,{items:[],domEvent:null,targetElement:null});
b.FileListItemsCancelableEventArgs.registerClass("Telerik.Web.UI.FileExplorer.FileListItemsCancelableEventArgs",Sys.CancelEventArgs);
b.FilePathEventArgs=function(d){b.FilePathEventArgs.initializeBase(this);
this.set_path(d);
};
a.registerControlProperties(b.FilePathEventArgs,{path:""});
b.FilePathEventArgs.registerClass("Telerik.Web.UI.FileExplorer.FilePathEventArgs",Sys.EventArgs);
})(Telerik.Web.UI,$telerik.$,Telerik.Web.UI.FileExplorer);
Type.registerNamespace("Telerik.Web.UI.FileExplorer");
(function(c,a,b){b.GridFileList=function(d,e){this.options=a.extend({contextMenu:null},e||{});
b.GridFileList.initializeBase(this,[d.get_masterTableView()]);
this.grid=d;
this.helpers=Telerik.Web.UI.FileExplorerHelper;
};
b.GridFileList.prototype={get_id:function(){return this.grid.get_id();
},get_name:function(){return"grid";
},get_items:function(){return this._extractDataItemFromItemsArray(this.grid.get_masterTableView().get_dataItems());
},get_selectedItems:function(){return this._extractDataItemFromItemsArray(this.grid.get_selectedItems());
},get_selectedItemsDataAndElement:function(){var d=this.grid.get_selectedItems();
return a.map(d,function(e){var f={get_element:function(){return e.get_element();
}};
return a.extend(e.get_dataItem(),f);
});
},get_element:function(){return this.grid.get_element();
},get_container:function(){return this.get_element();
},set_pageIndex:function(e,g){var d=this.suppressPageEvent;
this.suppressPageEvent=!!g;
var f=e+1;
this.grid.get_masterTableView().page(f);
this.suppressPageEvent=d;
},get_pageIndex:function(){return this.grid.get_masterTableView().get_currentPageIndex();
},get_allowMultiSelect:function(){return this.grid.get_allowMultiRowSelection();
},focusPagerControl:function(){var d=$get("RadSliderDrag_"+this.grid.get_masterTableView()._data.sliderClientID,this.grid.get_element());
this._focus(d);
},selectDefaultItem:function(){var j=this.grid.MasterTableView;
var e=j.get_dataItems();
var k=e[0];
var d=j.get_selectedItems()[0];
var g=j.get_selectedItems().length>0;
if(g&&d._owner.CurrentPageIndex!=j.CurrentPageIndex){g=false;
var h=e.length;
for(var f=0;
f<h;
f++){if(e[f].get_selected()){g=true;
break;
}}}if(!g&&k){this.grid.MasterTableView.selectItem(k.get_element());
}return k;
},selectItemsByName_Fast:function(j){if(!j){return;
}var d=this.grid.get_masterTableView().get_dataItems();
var e=this._createHashTableFromDataItems(d,"Name");
var l=this.grid.get_masterTableView();
for(var f=0,k=j.length;
f<k;
f++){var h=j[f];
var g=e[h];
if(g){l.selectItem(g.get_element(),true);
}}},getScroll:function(){var d=this.control.get_element().parentNode;
return d?d.scrollTop:0;
},scrollTo:function(d){var e=this.control.get_element().parentNode;
if(e){e.scrollTop=d;
}},attachEventHandlers:function(d){if(!d){return;
}this.grid.add_rowContextMenu(Function.createDelegate(this,this._onGridRowContextMenu));
this.grid.add_command(Function.createDelegate(this,this._onGridCommand));
this.grid.add_rowDblClick(Function.createDelegate(this,this._onRowDblClick));
this.grid.add_rowDataBound(Function.createDelegate(this,this._onRowDataBound));
this.grid.add_rowSelected(Function.createDelegate(this,this._onSelectItem));
this.grid.add_rowDragStarted(Function.createDelegate(this,this._onItemDragStart));
this.grid.add_rowDragging(Function.createDelegate(this,this._onItemDragging));
this.grid.add_rowDropping(Function.createDelegate(this,this._onItemDrop));
this.grid.add_keyPress(Function.createDelegate(this,this._onGridKeyPress));
},_selectIndex:function(e,g){this.control.selectItem(e);
if(!g){var d=this.control.get_dataItems()[e],f=d.get_element();
Telerik.Web.UI.Grid.ScrollIntoView(f);
}},_updatePageControl:function(d){this.grid.repaint();
},_extractDataItemFromItemsArray:function(d){return a.map(d,function(e){return e.get_dataItem();
});
},_createHashTableFromDataItems:function(d,j){var e={};
for(var f=0,k=d.length;
f<k;
f++){var g=d[f];
var h=g.get_dataItem();
if(h){e[h[j]]=g;
}}return e;
},_onGridRowContextMenu:function(e,d){var f=d.get_itemIndexHierarchical();
var h=e.get_masterTableView();
var g=h.get_dataItems()[f];
this.raiseEvent("contextMenu",g.get_dataItem());
},_onGridCommand:function(e,d){d.set_cancel(true);
switch(d.get_commandName()){case"Sort":this.raiseEvent("sort",new b.FileListSortEventArgs(e.get_masterTableView().get_sortExpressions().toString()));
break;
case"RowDroppedHtml":this.raiseEvent("itemDropComplete");
break;
case"Page":if(this._isBindingFlag){break;
}var h=e.get_masterTableView();
var f=h.get_pageSize();
var g=e.get_masterTableView().get_currentPageIndex()*f;
if(!this.suppressPageEvent){this.raiseEvent("page",new b.FileListPageEventArgs(g,f));
}break;
}},_onRowDblClick:function(e,d){this._raiseOpen(this._getEventArgsItem(d));
},_onRowDataBound:function(m,d){var k=d.get_dataItem();
var o=this.helpers.isFolderItem(k);
var p=k.Name;
var r=o?"&nbsp;":k.Length;
var j="rfeFileExtension "+(o?"folder":this.helpers.extractExtensionFromDataItem(k));
var s=d.get_item("Name").get_element();
var h=m.get_masterTableView().get_columns();
for(var n=0,q=s.cells.length;
n<q;
n++){var g=h[n].get_uniqueName();
var f=s.cells[n];
f.setAttribute("unselectable","on");
switch(g){case"Name":var l=document.createElement("div");
l.className=j;
l.innerHTML=p.replace(/&/g,"&amp;");
l.setAttribute("unselectable","on");
f.innerHTML="";
f.appendChild(l);
break;
case"Size":f.innerHTML=r;
break;
default:var e=k.Attributes[g];
f.innerHTML=e?e:"&nbsp;";
break;
}}},_onSelectItem:function(g,d){var f=d.get_domEvent();
if(f.type=="mousedown"&&f.button==Sys.UI.MouseButton.leftButton&&!f.shiftKey){return;
}var e=this._getEventArgsItem(d);
if(e){this.raiseEvent("itemSelect",e);
}},_onItemDragStart:function(e,d){var f=this._getEventArgsItem(d);
var g=new b.FileListItemCancelableEventArgs(f);
this.raiseEvent("itemDragStart",g);
d.set_cancel(g.get_cancel());
},_onItemDragging:function(e,d){this.raiseEvent("itemDragging",d);
},_onItemDrop:function(f,d){var g=this._extractDataItemFromItemsArray(d.get_draggedItems());
var e=d.get_domEvent();
var h=d.get_destinationHtmlElement();
this.raiseEvent("itemDrop",new b.FileListItemsCancelableEventArgs(g,e,h));
},_onGridKeyPress:function(f,e){var g=e.get_keyCode();
var d=e.get_domEvent();
var h=d.target?d.target.className:d.srcElement.className;
if(g==13){if(h!="rfeFilterTxt"){this._raiseOpen();
}return $telerik.cancelRawEvent(d.rawEvent);
}},_raiseOpen:function(d){this.raiseEvent("open",d);
},_getEventArgsItem:function(d){return d.get_gridDataItem().get_dataItem();
}};
b.GridFileList.registerClass("Telerik.Web.UI.FileExplorer.GridFileList",b.ClientBindableFileListView,b.IFileListView);
})(Telerik.Web.UI,$telerik.$,Telerik.Web.UI.FileExplorer);
Type.registerNamespace("Telerik.Web.UI.FileExplorer");
(function(c,a,b,g){var d=$telerik.getComputedStyle;
b.ListViewFileList=function(h){b.ListViewFileList.initializeBase(this,[h]);
this.listViewContainer=this.control.get_element().parentNode;
this.container=this.listViewContainer.parentNode;
this.paneElement=this._getContainingPaneElement();
this.pageSlider=this._findPageSlider();
this.applyPageInfoTemplate("Page <span class='rfeCurrentPage'>#= page #</span>/<span class='rfeTotalPages'>#= pages #</span>; Items <span class='rfeStartItem'>#= start #</span>-<span class='rfeEndItem'>#= end #</span>/<span class='rfeTotalItems'>#= itemsCount #</span>");
if(this.pageSlider){var i=this._getPageInfoContainer();
if(i.length==0){this._getPageControlContainer().append("<div class='rfePageControl rfePageInfo'>");
}}this.listViewContainer.setAttribute("tabIndex",0);
this.specialKeys={};
this.itemsElements=this.control.get_element().parentNode.getElementsByTagName("li");
};
b.ListViewFileList.prototype={get_id:function(){return this.control.get_id();
},get_name:function(){return"thumbnails";
},get_items:function(){return this.get_dataSource();
},get_selectedItems:function(){var h=this.control.get_dataSource();
return a.map(this.control.get_selectedIndexes(),function(i){return h[i];
});
},get_selectedItemsDataAndElement:function(){var i=this.itemsElements;
var h=this.control.get_dataSource();
return a.map(this.control.get_selectedIndexes(),function(j){var k={get_element:function(){return i[j];
}};
return a.extend(h[j],k);
});
},dataBind:function(){var h=this.getScroll();
b.ListViewFileList.callBaseMethod(this,"dataBind");
this._calculateListViewHeight();
this.scrollTo(h);
},selectItemsByName_Fast:function(m){var o=[];
var h=this._createHashTableFromItems(this.get_items(),"Name");
for(var j=0,n=m.length;
j<n;
j++){var l=m[j];
var k=h[l];
if(k){o.push(k.__itemIndex);
}}this.control.set_selectedIndexes(o);
this.dataBind();
},get_element:function(){return this.listViewContainer;
},get_container:function(){return this.container;
},get_boundContainer:function(){return $get(this.control.get_clientSettings().DataBinding.ItemPlaceHolderID);
},set_pageIndex:function(i,j){if(!this.pageSlider){return;
}var h=this.suppressPageEvent;
this.suppressPageEvent=!!j;
this.pageSlider.set_value(i);
this.suppressPageEvent=h;
},get_pageIndex:function(){return this.pageSlider?this.pageSlider.get_value():0;
},get_allowMultiSelect:function(){return this.control.get_allowMultiItemSelection();
},get_pageInfo:function(){var j=this.control.get_pageSize();
var i=this.get_pageIndex();
var k=i*j;
var h=this.get_itemsCount();
return{page:i+1,pages:this.get_pageCount(),start:h==0?0:k+1,end:Math.min(k+j,h),itemsCount:h};
},compilePageInfo:function(){return this.pageInfoTemplate(this.get_pageInfo());
},set_currentPageIndex:function(h,i){this.control.set_currentPageIndex(h,i);
this.set_pageIndex(h,i);
},selectDefaultItem:function(){this._selectSingleIndex(0);
},selectRange:function(i,h){this._selectRange(i,h);
this.control.set_selectedIndexes(this.control.get_selectedIndexes().sort());
},getScroll:function(){var h=this._getListElement();
return h?h.scrollTop:0;
},scrollTo:function(i){var h=this._getListElement();
if(h){h.scrollTop=i;
}},navigate:function(h){var i=this._getNewItemIndexByDirection(h);
if(i!=-1){this._selectSingleIndex(i);
}},show:function(){this.container.style.display="";
},hide:function(){this.container.style.display="none";
},attachEventHandlers:function(i){if(!i){return this.detachEventHandlers();
}var h="#"+this.control.get_clientSettings().DataBinding.ItemPlaceHolderID+" li a";
a(this.listViewContainer).on("dblclick",h,a.proxy(this._onDblClick,this)).on("mousedown",h,a.proxy(this._onDragPrepare,this)).on("click",h,a.proxy(this._handleMultiSelect,this));
if($telerik.isTouchDevice&&a.fn.nodoubletapzoom){a(this.listViewContainer).nodoubletapzoom();
}a(this.listViewContainer).on("mousedown",a.proxy(this._onContainerClick,this)).on("keydown",a.proxy(this._onKeyDown,this)).on("keyup",a.proxy(this._onKeyUp,this)).on("focus",a.proxy(function(){this._isFocused=true;
},this)).on("blur",a.proxy(function(){this._isFocused=false;
},this));
this.control.add_command(Function.createDelegate(this,this._onCommand));
this.control.add_itemDragStarted(Function.createDelegate(this,this._onDragStart));
this.control.add_itemDragging(Function.createDelegate(this,this._onDragging));
this.control.add_itemDropping(Function.createDelegate(this,this._onDrop));
this.control.add_itemSelected(Function.createDelegate(this,this._onItemSelect));
if(this.pageSlider){this.pageSlider.add_valueChanged(Function.createDelegate(this,this._onPageChanged));
}},detachEventHandlers:function(){},focusPagerControl:function(){if(!this.pageSlider){return;
}var h=this.pageSlider.get_dragHandles()[0];
this._focus(h);
},updatePageInfo:function(){this._getPageInfoContainer().html(this.compilePageInfo());
},applyPageInfoTemplate:function(h){this.pageInfoTemplate=Telerik.Web.UI.Template.compile(h);
},_hoveredCssClass:"rfeHoveredLink",_createHashTableFromItems:function(h,m){var j={};
for(var k=0,n=h.length;
k<n;
k++){var l=h[k];
l.__itemIndex=k;
if(l){j[l[m]]=l;
}}return j;
},_findPageSlider:function(){var h=a(this.container).find(".RadSlider.rfePageControl").prop("id");
if(h){return $find(h);
}},_hasFilter:function(){return a(this.container).find(".rfeFilterContainer").length>0;
},_selectIndex:function(h,j){this.control.selectItem(h);
if(!j){var i=this._findNodeByIndex(h).parent()[0];
$telerik.scrollIntoView(i);
}},_selectSingleIndex:function(h,i){this.control.clearSelectedItems();
this._selectIndex(h,i);
},_updatePageControl:function(h){if(this.pageSlider){this.pageSlider.set_maximumValue(Math.max(this.get_pageCount()-1,0));
this.updatePageInfo();
}this._calculateListViewHeight();
this._resetKeyboardFlags();
},_calculateListViewHeight:function(){var i=this._getListElement();
if(i){i.style.height="";
var j=i.offsetHeight;
var h=parseInt(this.paneElement.style.height,10)-a(this.container).find(".rfePageControlContainer").height()-a(this.container).find(".rfeFilterContainer").height()-$telerik.getPaddingBox(i).vertical-$telerik.getMarginBox(i).vertical;
i.style.height=h+"px";
i.style.overflowY=h<j?"scroll":"auto";
}},_getContainingPaneElement:function(){return this.container.parentNode;
},_getListElement:function(){return $get(this.control.get_clientSettings().DataBinding.ItemPlaceHolderID);
},_getSelectedItemElements:function(){var h=this.control.get_selectedIndexes();
return a(this._getListElement()).find("li").filter(function(j,k){return Array.contains(h,j);
});
},_getPageControlContainer:function(){return a(this.container).find(".rfePageControlContainer");
},_getPageInfoContainer:function(){return this._getPageControlContainer().find(".rfePageInfo");
},_createDraggableElement:function(){this._dragContainer=a(this.control._itemDrag._draggedItem).addClass("RadFileExplorer").css({visibility:"hidden"});
this._dragContainer.find("ul").css({height:"auto"});
this._dragContainer.find("li.rlvI").addClass("rfeFileDrag").append(this._createFileCountElement());
},_createFileCountElement:function(){var i=this.get_selectedItems().length;
if(i>1){var h=a("<span>").text(i).css({width:this._calculateFileCountWidth(i)+"px"});
return a("<span>").addClass("rfeFileCount").append(h);
}else{return a();
}},_calculateFileCountWidth:function(h){return(h+"").length*6;
},_calculateItemsPerRow:function(){var j=this._getItemWidth();
var i=this.get_boundContainer();
var h=e(f(d(i,"width")),i.clientWidth,i.offsetWidth);
return Math.floor(h/j);
},_getItemWidth:function(){return $telerik.getOuterSize(this.get_boundContainer().getElementsByTagName("li")[0]).width;
},_attachWaitForDraggingEvent:function(h){this._waitForDraggingDelegate=a.proxy(this._waitForDragging,this);
a(document).on("mousemove",{startPos:{x:h.pageX,y:h.pageY}},this._waitForDraggingDelegate);
},_showDraggableElement:function(){this._dragContainer.css({visibility:""});
},_getItemByIndex:function(h){return this.get_items()[h];
},_getNewItemIndexByDirection:function(h){var n=this.get_items().length;
if(n<=0){return -1;
}var j=n-1;
var m=this.control.get_selectedIndexes();
var i=isNaN(this._currentSelectPosition)?(m.length?m[0]:-1):this._currentSelectPosition;
var k=isNaN(this._currentSelectPosition)?(m.length?m[m.length-1]:-1):this._currentSelectPosition;
var l=h=="home"?0:h=="end"?j:h=="left"?i-1:h=="right"?k+1:h=="up"?i-this._calculateItemsPerRow():h=="down"?k+this._calculateItemsPerRow():i;
return Math.max(Math.min(l,j),0);
},_resetKeyboardFlags:function(){delete this._currentSelectPosition;
delete this._shiftSelectWaypoint;
},_onCommand:function(i,h){h.set_cancel(true);
},_handleMultiSelect:function(h){var i=$telerik.$(h.currentTarget).data("index");
var j=this.control.get_selectedIndexes();
h.preventDefault();
if(h.shiftKey&&j.length){if(h.ctrlKey){return this._handleShiftSelect(Math.min(j[0],i),Math.max(j[j.length-1],i));
}else{return this._handleShiftSelect(this._lastSelectedIndex,i);
}}else{if(!h.ctrlKey&&(j.length>1||j[0]!==i)){this.control.clearSelectedItems();
}if(!Array.contains(j,i)){this._lastSelectedIndex=i;
}if(h.ctrlKey){this.control.toggleSelection(i);
}else{this.control.selectItem(i);
}}this._focus(this.get_element());
},_handleShiftSelect:function(i,h){this.control.clearSelectedItems();
this._selectRange(h,i);
},_selectRange:function(j,h){var i=Math.min(j,h);
var k=Math.max(j,h);
do{this.control.selectItem(i);
}while(i++<k);
},_onPageChanged:function(k,h){var i=h.get_newValue();
var j=this.control.get_pageSize();
this.updatePageInfo();
if(!this.suppressPageEvent){this.raiseEvent("page",new b.FileListPageEventArgs(i*j,j));
}},_onItemSelect:function(j,h){var i=this._getItemByIndex(h.get_itemIndex());
if(i){this.raiseEvent("itemSelect",i);
}},_onDragPrepare:function(h){h.stopImmediatePropagation();
var i=a(h.currentTarget).data("index");
if(h.which==3){this._onContextMenu(h);
}else{this._onHideContextMenu(h);
Telerik.Web.UI.RadListView.HandleDrag(h.originalEvent,this.control.get_id(),i);
}if(!Array.contains(this.control.get_selectedIndexes(),i)){this._handleMultiSelect(h);
}},_onDragStart:function(j,h){var i=new b.FileListItemCancelableEventArgs(this._getItemByIndex(h.get_itemIndex()));
this.raiseEvent("itemDragStart",i);
h.set_cancel(i.get_cancel());
if(!i.get_cancel()){a(document).one("mousemove",a.proxy(this._onCreateDraggable,this));
}},_onCreateDraggable:function(h){this._createDraggableElement();
this._attachWaitForDraggingEvent(h);
},_onDragging:function(i,h){this.raiseEvent("itemDragging",h);
},_waitForDragging:function(h){var j=h.data.startPos;
var i={x:h.pageX,y:h.pageY};
if(i.x!=j.x||i.y!=j.y){this._showDraggableElement();
this._offWaiting();
}},_offWaiting:function(){this._draggedItems=this.get_selectedItems();
a(document).off("mousemove",this._waitForDraggingDelegate);
delete this._waitForDragging;
},_onDrop:function(j,h){var i=new b.FileListItemsCancelableEventArgs(this._draggedItems,h.get_domEvent());
this.raiseEvent("itemDrop",i);
if(!i.get_cancel()){this.raiseEvent("itemDropComplete");
}delete this._draggedItems;
},_onContextMenu:function(h){var i=this._getItemFromjEvent(h);
this.raiseEvent("contextMenu",i);
},_onHideContextMenu:function(h){this.raiseEvent("hideContextMenu",h.originalEvent);
},_onDblClick:function(h){this._raiseOpen(this._getItemFromjEvent(h));
},_onKeyDown:function(i){if(i.shiftKey){this._handleShiftKeySelect(i);
}else{if(i.ctrlKey){this._handleCtrlKeySelect(i);
}else{if(i.keyCode==Sys.UI.Key.enter){var j=this.get_selectedItems();
if(j.length){this._raiseOpen(j[0]);
}}else{var h=this._getDirectionByKeyCode(i.keyCode);
if(h){this.navigate(h);
}}}}i.preventDefault();
},_onKeyUp:function(h){if(!(h.shiftKey||h.ctrlKey)&&(this._shiftSelectWaypoint||this._currentSelectPosition)){this._resetKeyboardFlags();
}},_ctrlSelectWaypoint:g,_handleCtrlKeySelect:function(i){var j=i.keyCode;
if(j==Sys.UI.Key.space){var k=this._getMarkedPosition();
this.control.toggleSelection(k);
if(Array.contains(this.control.get_selectedIndexes(),k)){this._shiftSelectWaypoint=k;
}this._currentSelectPosition=k;
}else{var h=this._getDirectionByKeyCode(j);
if(h){var l=this._getNewItemIndexByDirection(h);
this._currentSelectPosition=l;
}}this._markCurrentSelectPosition();
},_markCurrentSelectPosition:function(){var h=a(this._getListElement());
h.find("li a."+this._hoveredCssClass).removeClass(this._hoveredCssClass);
this._findNodeByIndex(this._currentSelectPosition).addClass(this._hoveredCssClass);
},_findNodeByIndex:function(h,i){i=i||a(this._getListElement());
return i.find("li a[data-index='"+h+"']");
},_getMarkedPosition:function(){return a(this._getListElement()).find("li a."+this._hoveredCssClass).data("index");
},_currentSelectPosition:g,_shiftSelectWaypoint:g,_handleShiftKeySelect:function(i){var j=i.keyCode;
this._ensureWaypoint();
var h=this._getDirectionByKeyCode(j);
if(h){var k=this._getNewItemIndexByDirection(h);
this._currentSelectPosition=k;
if(i.ctrlKey){this.selectRange(this._shiftSelectWaypoint,this._currentSelectPosition);
}else{this._handleShiftSelect(this._shiftSelectWaypoint,this._currentSelectPosition);
}}},_ensureWaypoint:function(){if(!this._shiftSelectWaypoint){this._shiftSelectWaypoint=this.control.get_selectedIndexes()[0];
}},_onContainerClick:function(h){if(this._isFocused&&this.control.get_selectedIndexes().length>0){this.clearSelection();
}},_raiseOpen:function(h){this.raiseEvent("open",h);
},_getItemFromjEvent:function(h){var i=a(h.currentTarget).data("index");
return this._getItemByIndex(i);
},_getDirectionByKeyCode:function(h){var i=Sys.UI.Key;
return i.up==h?"up":i.down==h?"down":i.left==h?"left":i.right==h?"right":i.home==h?"home":i.end==h?"end":"";
}};
b.ListViewFileList.registerClass("Telerik.Web.UI.FileExplorer.ListViewFileList",b.ClientBindableFileListView,b.IFileListView);
a.fn.nodoubletapzoom=function(){a(this).bind("touchstart",function h(j){var m=j.timeStamp;
var l=a(this).data("lastTouch")||m;
var i=m-l;
var k=j.originalEvent.touches.length;
a(this).data("lastTouch",m);
if(!i||i>500||k>1){return;
}j.preventDefault();
a(j.target).trigger("dblclick");
});
};
function f(h){return parseInt(h,10);
}function e(){var j=Number.MAX_VALUE;
for(var h=0;
h<arguments.length;
h++){var k=arguments[h];
if(!isNaN(k)&&k<j){j=k;
}}return j;
}})(Telerik.Web.UI,$telerik.$,Telerik.Web.UI.FileExplorer);
Type.registerNamespace("Telerik.Web.UI.FileExplorer");
(function(){$telerik.toFileExplorer=function(h){return h;
};
$telerik.findFileExplorer=$find;
var a=$telerik.$;
var b=Telerik.Web.UI;
var f=b.FileExplorerHelper;
var c=f.canDelete;
var d=f.canUpload;
Telerik.Web.UI.RadFileExplorer=function(h){Telerik.Web.UI.RadFileExplorer.initializeBase(this,[h]);
this._localization={};
this._initialGridData={};
this._uniqueId="";
this._selectedFile=null;
this._pathSeparator="/";
this._gridPageSize=10;
this._enableCopy=false;
this._explorerMode=Telerik.Web.UI.FileExplorerMode.Default;
this._allowFileExtensionRename=true;
this._initialGridPageIndex=0;
this._overwriteExistingFiles=false;
this._selectedFileListItem=null;
this._folderCache=[];
this._gridContextHandler=null;
this._actionsManager=null;
this._currentDirectoryInputID="";
this._postbackArgumentInputID="";
this._treeId="";
this._commandArgumentInputID="";
this._copiedPaths=[];
this._copyCursorClassName="rfeCopyCursor";
this._bindingGridFlag=false;
this._isPaging=false;
this._filterKeyWord=null;
this._btnUpload=null;
this._enabled=true;
this._droppedFilesTypes=[];
this._dropEventTarget=null;
this._dropZoneOverlayElement=null;
this._droppedFilesTotalCount=0;
this._uploadedFilesCount=0;
this._btnCancelUpload=null;
this._btnCancelUploadID="btnCancelUpload";
this._uploadProgressLabel=null;
this._uploadProgressLabelID="lblDropUploadProgress";
this._dropUploadInfoPanel=null;
this._dropUploadInfoPanelID="dropUploadInfoPanel";
this._currentUploadRow=null;
this._isDropUploadCancelled=false;
this._shortCutManager=null;
this._keyDownDelegate=null;
this._htmlElKeyDownDelegate=null;
this._lastFocusedElement=null;
this._shouldShowGridContextMenu=true;
this._fileList=null;
this._fileNameInvalidCharacters=[92,47,58,42,63,34,60,62,124];
this.fileNameInvalidText="File names cannot contain any of the following characters";
};
Telerik.Web.UI.RadFileExplorer.prototype={initialize:function(){Telerik.Web.UI.RadFileExplorer.callBaseMethod(this,"initialize");
if((this.get_grid()&&this._explorerMode==b.FileExplorerMode.Default)||(this.get_listView()&&this._explorerMode==b.FileExplorerMode.Thumbnails)){this._fileList=new b.FileExplorer.FileList({grid:this.get_grid(),listView:this.get_listView(),contextMenu:this.get_gridContextMenu(),container:this.get_gridPane().getContentElement(),fileExplorer:this});
if(this.get_grid()){this._fileList.registerFileListView(new b.FileExplorer.GridFileList(this.get_grid()));
}if(this.get_listView()){this._fileList.registerFileListView(new b.FileExplorer.ListViewFileList(this.get_listView()));
}this._fileList.chooseFileListView(this._getFileListViewNameByExplorerMode());
}if(this.get_asyncUpload()){var h=this._getControlClientID(this._btnCancelUploadID);
this._btnCancelUpload=$find(h);
var j=this._getControlClientID(this._uploadProgressLabelID);
this._uploadProgressLabel=$get(j);
var i=this._getControlClientID(this._dropUploadInfoPanelID);
this._dropUploadInfoPanel=$get(i);
}this.raiseEvent("init",Sys.EventArgs.Empty);
this.attachEventHandlers();
this.initializeControl();
this.raiseEvent("load",Sys.EventArgs.Empty);
},_getControlClientID:function(h){return this.get_id()+"_"+h;
},initializeControl:function(){if(this._fileList){var j=parseInt(this._initialGridPageIndex,10);
this._fileList.bindToServerData(this._initialGridData,j);
this._fileList._currentFolder=this.get_currentDirectory();
}if(this._selectedFile){this._selectInitialFile();
var l=this.get_tree();
if(l){this._scrollFolderIntoView(l.get_selectedNode());
}}var k=this.get_toolbar();
if(k!=null){var i={redoAction:Function.createDelegate(this,this._executeBackForward),undoAction:Function.createDelegate(this,this._executeBackForward)};
this._actionsManager=$create(Telerik.Web.UI.ActionsManager,null,i);
this._updateToolbar();
this._updateBackForward(this.get_currentDirectory());
}if($telerik.isFirefox){this._addFirefoxFormAutoComplete();
}if(!$telerik.isIE&&!$telerik.isOpera){this._copyCursorClassName+="CSS3";
}if(this._currentDirectoryInputID){var h=$get(this._currentDirectoryInputID);
if(h){h.setAttribute("autocomplete","off");
}}this._fixWindowLocalization();
this.set_commandArgument("");
this._disableTreeMultiSelectInTouch();
this._setRightToLeft();
if(this._renderMode===Telerik.Web.UI.RenderMode.Lite){this._updateSplitterHeight();
}},_updateSplitterHeight:function(){var j=$telerik.getContentSize(this.get_element()).height;
var l=0;
if(this._toolbar){var p=this._toolbar.get_element();
var m=parseFloat($telerik.$(p).css("height"));
var o=parseFloat($telerik.$(p).css("paddingTop"));
var n=parseFloat($telerik.$(p).css("paddingBottom"));
l=m+o+n;
}var h=$get(this.get_addressBox());
var i=0;
if(h){i=parseFloat($telerik.$(h).css("height"));
}var k=j-l-i;
if(k!==j){this.get_tree().get_element().style.height=k+"px";
this.get_fileList().get_element().style.height=k+"px";
this._resizeSplitterDelegate=Function.createDelegate(this,this._resizeSplitter);
this.get_splitter().add_load(this._resizeSplitterDelegate);
this._splitterHeight=k;
}},_resizeSplitter:function(){this.get_splitter().set_height(this._splitterHeight);
},attachEventHandlers:function(){this._attachAjaxPanelHandlers();
if(this.get_tree()){this._attachTreeHandlers();
}if(this._fileList){this._attachFileListHandlers();
}if(this.get_toolbar()){this.get_toolbar().add_buttonClicked(Function.createDelegate(this,this.toolbarClicked));
}var h=this.get_asyncUpload();
this._btnUpload=$get(this.get_id()+"_btnUpload");
if(h!=null){this._attachAsyncUploadHandlers();
if(this._btnUpload!=null){this._onBtnUploadClickDelegate=Function.createDelegate(this,this._onBtnUploadClick);
$telerik.$(this._btnUpload).click(this._onBtnUploadClickDelegate);
}if(this._fileExplorerHasFileList()){this._dropZoneOverlayElement=this._getDropZoneOverlayElement();
this._attachDragAndDropZoneHandlers();
}this._btnCancelUpload.add_clicked(Function.createDelegate(this,this._onCancelUploadButtonClicked));
}this._validateFileNameInputDelegate=Function.createDelegate(this,this._validateFileNameInput);
this._registerShortcuts();
this.raiseEvent("eventHandlersAttached",Sys.EventArgs.Empty);
},_fileExplorerHasFileList:function(){return this._explorerMode!==b.FileExplorerMode.FileTree&&this.get_fileList();
},_getDropZoneOverlayElement:function(){var i=this.get_gridPane().get_element();
var h=i.getElementsByTagName("div");
var j=h[h.length-1];
return j;
},_attachDragAndDropZoneHandlers:function(){var j=this,h=j.get_grid(),k=a(".rfeThumbnailsContainer",j.get_element()).get(0),i=this._dropZoneOverlayElement;
j._onDropZoneDragEnterDelegate=Function.createDelegate(j,j._onDropZoneDragEnter);
if(h){this._gridElement=h.get_element();
$telerik.addHandler(this._gridElement,"dragenter",j._onDropZoneDragEnterDelegate);
}if(k){j._thumbnailsContainer=k;
$telerik.addHandler(k,"dragenter",j._onDropZoneDragEnterDelegate);
}this._onDropZoneDragLeaveDelegate=Function.createDelegate(this,this._onDropZoneDragLeave);
$telerik.addHandler(i,"dragleave",this._onDropZoneDragLeaveDelegate);
this._onDropZoneDropDelegate=Function.createDelegate(this,this._onDropZoneDrop);
$telerik.addHandler(i,"drop",this._onDropZoneDropDelegate);
},_detachDragAndDropZoneHandlers:function(){var j=this,h=j._grdiElement,k=j._thumbnailsContainer,i=this._dropZoneOverlayElement;
if(h){$telerik.removeHandler(h,"dragenter",j._onDropZoneDragEnterDelegate);
}if(k){$telerik.removeHandler(k,"dragenter",j._onDropZoneDragEnterDelegate);
}if(i){$telerik.removeHandler(i,"dragleave",this._onDropZoneDragLeaveDelegate);
$telerik.removeHandler(i,"drop",this._onDropZoneDropDelegate);
}},_onDropZoneDragEnter:function(){this._dropZoneOverlayElement.style.display="block";
},_onDropZoneDragLeave:function(){this._dropZoneOverlayElement.style.display="none";
},_onDropZoneDrop:function(){this._dropZoneOverlayElement.style.display="none";
},dispose:function(){if(this.get_asyncUpload()!==null&&this._fileExplorerHasFileList()){this._detachDragAndDropZoneHandlers();
this._dropZoneOverlayElement=null;
}this._folderCache=null;
if(this._btnUpload!=null){$telerik.$(this._btnUpload).unbind("click");
this._btnUpload=null;
}var h=this.get_gridPane().getContentElement();
if(this._gridContextHandler&&h&&h._events){$removeHandler(h,"contextmenu",this._gridContextHandler);
this._gridContextHandler=null;
}this._attachShortcutHandlers(false);
Telerik.Web.UI.RadFileExplorer.callBaseMethod(this,"dispose");
},get_tree:function(){return $find(this._treeId==null?"":this._treeId);
},set_tree:function(h){if(h&&h.get_id){this._treeId=h.get_id();
}},get_fileList:function(){return this._fileList;
},set_fileList:function(h){this._fileList=h;
},clearFolderCache:function(){this._folderCache=[];
},filter:function(h){if(this._fileList){this._fileList.filterList(h);
}},copy:function(j){var i=b.FileExplorerControls;
var h=j==i.Tree?"tree":j==i.FileList?"grid":null;
if(h){this._copy(h);
}},paste:function(h){if(h&&h.isDirectory()&&this._copiedPaths.length>0){this._paste(h);
}},rename:function(h,i){if(h&&i){this._renameItem(h,i);
}},copyItems:function(h){this.clearCopyItems();
this.copyMoreItems(h);
},copyMoreItems:function(j){for(var h=0,k=j.length;
h<k;
h++){this._addItemToCopiedPaths(j[h]);
}},clearCopyItems:function(){this._copiedPaths=[];
},createItemFromPath:function(h){return this._createItemFromPath(h);
},addFileNameInvalidChar:function(i){var h=i.charCodeAt();
this._fileNameInvalidCharacters.push(h);
},removeFileNameInvalidChar:function(j){var h=j.charCodeAt();
var i=a.inArray(h,this._fileNameInvalidCharacters);
if(i!=-1){this._fileNameInvalidCharacters.splice(i,1);
}},get_overwriteExistingFiles:function(){return this._overwriteExistingFiles;
},set_overwriteExistingFiles:function(h){this._overwriteExistingFiles=h;
this._getChildElement("chkOverwrite").checked=h;
},_fixWindowLocalization:function(){if(Telerik.Web.UI.RadWindowUtils&&Telerik.Web.UI.RadWindowUtils.Localization){var h=this.get_localization();
Telerik.Web.UI.RadWindowUtils.Localization.OK=h.OK;
Telerik.Web.UI.RadWindowUtils.Localization.Cancel=h.Cancel;
}},_addFirefoxFormAutoComplete:function(){var h=this.get_element();
while(h!=null&&h.tagName.toLowerCase()!="form"){h=h.parentNode;
}if(h!=null){h.setAttribute("autocomplete","off");
}},_setRightToLeft:function(){var h=null;
var i=this.get_element();
if(i){h=$telerik.isRightToLeft(i);
}this._isRightToLeft=h;
if(h){Sys.UI.DomElement.addCssClass(i,"rfeRtl");
}},_postbackTreeAjaxPanel:function(h){if(this._postbackArgumentInputID){var j=$get(this._postbackArgumentInputID);
j.value=h;
}var k=this.get_postbackButton();
if(k){var i=$get(k);
i.click();
}},_onAjaxRequestStart:function(j,h){var i=h.get_postBackElement();
if(i&&(i.id==this.get_postbackButton()||(this.get_tree()&&i.id==this.get_tree().get_id()))){this._showLoadingPanel(this.get_treePane().get_id());
this.raiseEvent("ajaxRequestStart",Sys.EventArgs.Empty);
var k=this.get_tree();
this._treeId=k!=null?k.get_id():null;
h.get_request().isRFE=this.get_id();
}},_onAjaxResponseEnd:function(o,h){var m=h.get_response();
if(!m){return;
}var r=m.get_webRequest();
if(r&&r.isRFE&&r.isRFE==this.get_id()){this._hideLoadingPanel(this.get_treePane().get_id());
h.get_response().get_webRequest().isRFE=null;
if(this._treeId!=null){this._attachTreeHandlers();
this._disableTreeMultiSelectInTouch();
}var i=this.get_currentDirectory();
if(this._currentDirectory&&this._currentDirectory!=i){this._currentDirectory=null;
var k=this._createItemFromPath(i);
var j=new Telerik.Web.UI.FileExplorerEventArgs(k,"");
this.raiseEvent("folderChange",j);
}this._refreshFileList(i);
var p=this.get_tree();
if(p){var q=p.get_element();
q.setAttribute("tabindex","0");
if($telerik.isIE7||$telerik.isIE6){q.setAttribute("tabIndex","0");
}q.style.outlineStyle="none";
}this._attachFocusHandlers(false);
var l=this._lastFocusedElement;
if(l){l=this._lastFocusedElement=$get(l.id);
var n=this;
window.setTimeout(function(){n._focus(l);
},0);
}this.raiseEvent("ajaxRequestEnd",Sys.EventArgs.Empty);
}},_attachAjaxPanelHandlers:function(){Sys.WebForms.PageRequestManager.getInstance().add_beginRequest(Function.createDelegate(this,this._onAjaxRequestStart));
Sys.WebForms.PageRequestManager.getInstance().add_endRequest(Function.createDelegate(this,this._onAjaxResponseEnd));
},_attachFileListHandlers:function(){this._fileList.add_filter(Function.createDelegate(this,function(i,h){this.raiseEvent("filter",h);
}));
this._fileList.add_itemSelect(Function.createDelegate(this,function(i,h){this._updateToolbar(null,null,h.get_item().get_permissions());
this.raise_itemSelected(h.get_item());
}));
this._fileList.add_callback(Function.createDelegate(this,function(i,h){var j=this.get_gridPane().get_id();
this._hideLoadingPanel(j);
this._showLoadingPanel(j);
}));
this._fileList.add_callbackComplete(Function.createDelegate(this,function(i,h){var j=this.get_gridPane().get_id();
this._hideLoadingPanel(j);
}));
this._fileList.add_folderLoaded(Function.createDelegate(this,function(i,h){var j=this._getCurrentFolderItem();
this.raiseEvent("folderLoaded",new Telerik.Web.UI.FileExplorerEventArgs(j,""));
}));
},_showFolderFileList:function(h){if(this.get_currentDirectory()==h){return;
}this.set_currentDirectory(h);
if(this._fileList){this._fileList.showFolderFileList(h);
}},_refreshFileList:function(h){this.set_currentDirectory(h);
if(this._fileList){this._fileList.refreshFileList(h);
}},loadFolder:function(k,h){if(!k){return;
}if(h==null){h=true;
}if(this.get_currentDirectory()==k&&h){return;
}var j=this._createItemFromPath(k);
var i=new Telerik.Web.UI.FileExplorerEventArgs(j,"");
this.raiseEvent("folderChange",i);
if(i.get_cancel()){return;
}this.set_currentDirectory(k,h);
this._postbackTreeAjaxPanel("LoadFolder_"+k);
},toolbarClicked:function(j,h){var i=h.get_item().get_value();
this._fireCommand(i);
},_fireCommand:function(h){switch(h){case"Back":this._back();
break;
case"Forward":this._forward();
break;
case"Refresh":this.refresh();
break;
case"NewFolder":this.createNewDirectory();
break;
case"Delete":this.deleteSelectedItems();
break;
case"Upload":this._showUploadWindow();
break;
case"Open":this.open();
break;
case"GridView":this._fileList.chooseFileListView("grid");
this._selectedFileListItem=null;
break;
case"ThumbnailsView":this._fileList.chooseFileListView("thumbnails");
this._selectedFileListItem=null;
break;
}},_addItemToCopiedPaths:function(h){Array.add(this._copiedPaths,h);
},_copy:function(h,n){var q=this.get_tree();
if(q){this._focus(q.get_element());
}this._copiedPaths=[];
if(n){this._addItemToCopiedPaths(n);
}else{if(h=="grid"){if(this._fileList){this._fileList.focus();
var o=this.get_selectedItems();
for(var k=0;
k<o.length;
k++){this._addItemToCopiedPaths(o[k]);
}}}else{if(h=="tree"){if(q){var p=q.get_selectedNodes();
for(var m=0;
m<p.length;
m++){var l=this._createItemFromTreeViewNode(p[m]);
this._addItemToCopiedPaths(l);
}}}}}},_paste:function(l){if(this._copiedPaths.length==0||!l.isDirectory()){return;
}var j=new Telerik.Web.UI.FileExplorerCopyEventArgs(this._copiedPaths,l.get_path());
this.raiseEvent("copy",j);
if(!j.get_cancel()&&j._items.length>0){var h=l.get_path();
for(var k=0;
k<j._items.length;
k++){var m=j._items[k].isDirectory()?"D":"F";
h+="***"+m+j._items[k].get_path();
}if(this._fileList){this._fileList.clearFolderCache(l.get_path());
}this._postbackTreeAjaxPanel("CallbackFnCopy_"+h);
}},_gridOpenFolder:function(i){var j=this.get_tree();
if(j!=null){var h=j.findNodeByValue(i);
if(h){h.select();
h.expand();
this._showFolderFileList(i);
this.set_currentDirectory(i);
this._focusFileListAfterCallback();
}}},_isOpenExtension:function(h){return(h=="docx"||h=="doc"||h=="xlsx"||h=="xls"||h=="zip");
},open:function(h){if(!this._enabled){return;
}if(!h){h=this.get_selectedItem();
}if(h){if(!h.isDirectory()||(h.isDirectory()&&h.get_path()!=this.get_currentDirectory())){if(this.raiseFileItemCancelEvent(h,"fileOpen")){return false;
}}if(h.isDirectory()){if(this.raiseFileItemCancelEvent(h,"folderChange")){return false;
}this._gridOpenFolder(h.get_path());
}else{if(this.get_enableOpenFile()){var j=h.get_url();
if(this._isOpenExtension(h.get_extension())){window.location.href=j;
}else{var i=this.get_windowManager();
window.setTimeout(function(){var k=i.open(j,null);
k.set_title(h.get_name());
k.set_modal(false);
},10);
}}}}},deleteSelectedItems:function(i){var h=this.get_selectedItems();
if(h&&h.length>0){this.deleteItem(h,i);
}},deleteItem:function(j,l){if((typeof(l)=="undefined")||(l!=false)){var h=function(m){if(m){this._deleteItem(j);
}};
var k=this.get_windowManager();
var i=this._getDialogDimentions();
k.radconfirm(this.get_localization()["ConfirmDelete"],Function.createDelegate(this,h),i.width,i.height,null,this.get_localization()["Delete"]);
}else{this._deleteItem(j);
}},_deleteItem:function(m){if(!Array.isInstanceOfType(m)){m=[m];
}var h="";
for(var k=0,n=m.length;
k<n;
k++){var l=m[k];
if(!l.get_path){l=this._createItemFromPath(l);
}if(l&&l.get_name()===".."){continue;
}if(l&&l.get_path){var j=new Telerik.Web.UI.FileExplorerEventArgs(l,"");
this.raiseEvent("delete",j);
if(j.get_cancel()){continue;
}h+=l.get_path()+"***";
if(l.isDirectory()&&this._fileList){this._fileList.clearFolderCache(l.get_path());
}}}if(h.length>0){this._currentDirectory=this.get_currentDirectory();
this._postbackTreeAjaxPanel("CallbackFnDelete_"+h);
}},_createFolder:function(l,k){var j=this._createItemFromPath(l);
var h=new Telerik.Web.UI.FileExplorerEventArgs(j,k);
this.raiseEvent("createNewFolder",h);
if(h.get_cancel()){return false;
}var i=l+"***"+k;
this._postbackTreeAjaxPanel("CallbackFnCreate_"+i);
},createNewDirectory:function(j,i){if(!j){j=this.get_currentDirectory();
}if(!i){var h=Function.createCallback(Function.createDelegate(this,function(k,l){if(k){this._createFolder(l,k);
}}),j);
this._showPromptDialog(h,{title:"CreateNewFolder",value:this.get_newFolderDefaultValue(),inputValidator:this._validateFileNameInputDelegate,timeout:10});
}else{this._createFolder(j,i);
}},refresh:function(i){var h=this._fileList;
if(i&&h){this._fileList.selectFileList(a.makeArray(i));
}this.loadFolder(this.get_currentDirectory(),false);
},_showUploadWindow:function(){var h=this._getChildElement("uploadContainer");
var i=this.get_windowManager();
window.setTimeout(function(){i.open(null,i.get_id()+"fileExplorerUpload",h);
h.style.overflow="";
h.style.height="auto";
h.style.width="auto";
h.style.position="";
},10);
},_updateToolbar:function(j,h,i){if(!this._enabled||this.get_toolbar()==null){return;
}if(typeof(i)=="undefined"||i==null){i=this.get_currentPermissions();
}this._setToolbarButtonEnabledState("Back",this._actionsManager&&this._actionsManager.canUndo());
this._setToolbarButtonEnabledState("Forward",this._actionsManager&&this._actionsManager.canRedo());
this._setToolbarButtonEnabledState("Open",true);
this._setToolbarButtonEnabledState("Refresh",true);
this._setToolbarButtonEnabledState("NewFolder",d(i));
this._setToolbarButtonEnabledState("Upload",d(i));
this._setToolbarButtonEnabledState("Delete",c(i));
if(this._fileList){this._setToolbarButtonEnabledState("GridView",!!this._fileList.getFileListViewByName("grid"));
this._setToolbarButtonEnabledState("ThumbnailsView",!!this._fileList.getFileListViewByName("thumbnails"));
}},_setToolbarButtonEnabledState:function(h,i){var j=this.get_toolbar();
if(j!=null){j.get_items().forEach(function(k){if(k.get_value()==h||h=="all"){k.set_enabled(i);
}});
}},_attachTreeHandlers:function(){var h=this.get_tree();
if(h!=null){h.add_nodeClicked(Function.createDelegate(this,this._onTreeNodeClicked));
h.add_nodeDoubleClick(Function.createDelegate(this,this._onTreeNodeDoubleClick));
h.add_contextMenuShowing(Function.createDelegate(this,this._onTreeContextMenuShowing));
h.add_contextMenuItemClicked(Function.createDelegate(this,this._onTreeContextMenuItemClicked));
h.add_nodeDropping(Function.createDelegate(this,this._onTreeNodeDropping));
h.add_nodeDragging(Function.createDelegate(this,this._onTreeNodeDragging));
h.add_mouseOver(Function.createDelegate(this,this._onTreeMouseOver));
h.add_mouseOut(Function.createDelegate(this,this._onTreeMouseOut));
h.add_nodeEditing(Function.createDelegate(this,this._onTreeNodeEditing));
h.add_keyPressing(Function.createDelegate(this,this._onTreeKeyPressing));
h.add_nodePopulated(Function.createDelegate(this,this._onTreeNodePopulated));
}},_isOverElement:function(h,i){while(h){if(h.id==i){return h;
}h=h.parentNode;
}return null;
},_onTreeNodePopulated:function(j,h){if(this._explorerMode==Telerik.Web.UI.FileExplorerMode.FileTree){var i=this._createItemFromTreeViewNode(h.get_node());
this.raiseEvent("folderLoaded",new Telerik.Web.UI.FileExplorerEventArgs(i,""));
}},_onTreeKeyPressing:function(j,h){var i=h.get_domEvent();
if(i&&i.keyCode==13){h.set_cancel(true);
$telerik.cancelRawEvent(i);
this._onTreeNodeDoubleClick(j,h);
}},_onTreeNodeDragging:function(j,h){this._checkCopyCursor(j,h);
var i=h.get_domEvent();
this._scrollTreeViewOnDrag(i);
},_onTreeNodeEditing:function(n,h){this._treeKeyDownDelegate=null;
var l=h.get_node();
if(l){var k=h.get_newText(),i=this._createItemFromTreeViewNode(l),j=new Telerik.Web.UI.FileExplorerEventArgs(i,k);
this.raiseEvent("move",j,true);
if(j.get_cancel()){h.set_cancel(j.get_cancel());
}else{var m=l.get_parent();
if(m&&m.get_value){if(this._fileList){this._fileList.clearFolderCache(m.get_value());
}}}}},_onTreeMouseOver:function(i,h){this._currentTreeNode=h.get_node();
},_onTreeMouseOut:function(i,h){this._currentTreeNode=null;
},_onTreeNodeDropping:function(v,h){if(this._enableCopy){this._updateCopyCursor(false);
}var r=this._enableCopy&&h.get_domEvent().ctrlKey;
var n=r?"copy":"move";
var x=h.get_sourceNodes();
var m=h.get_destNode();
if(!m){var l=h.get_htmlElement();
if(!l){return;
}var p=this.get_grid();
var o=p!=null?this._isOverElement(l,p.get_id()):null;
if(o){h.set_htmlElement(o);
}else{h.set_cancel(true);
}}else{if(this._isNodeADirectory(m)){var t=m.get_value();
for(var q=0;
q<x.length;
q++){var s=this._createItemFromTreeViewNode(x[q]);
var j=new Telerik.Web.UI.FileExplorerEventArgs(s,t);
this.raiseEvent(n,j);
if(j.get_cancel()){h.set_cancel(true);
}}}else{h.set_cancel(true);
}}if(!h.get_cancel()){if(!r){for(var k=0;
k<x.length;
k++){var w=x[k];
var u=w.get_parent();
if(u&&u.get_value){if(this._fileList){this._fileList.clearFolderCache(u.get_value());
}}if(this._fileList&&this._isNodeADirectory(m)){this._fileList.clearFolderCache(w.get_value());
}}}this.set_commandArgument(n);
}},_onTreeContextMenuShowing:function(k,h){var j=h.get_node();
var i=this._createItemFromTreeViewNode(j);
var l=this._setContextMenuItemsState(h.get_menu(),i.get_permissions());
if(!l){h.set_cancel(true);
$telerik.cancelRawEvent(h.get_domEvent());
}},_onTreeContextMenuItemClicked:function(p,h){var q=h.get_node();
var k=h.get_menuItem().get_value();
switch(k){case"Rename":q.startEdit();
var l=q.get_inputElement();
if(!this._allowFileExtensionRename){var j=this._createItemFromTreeViewNode(q);
if(!j.isDirectory()){l.value=b.FileExplorerHelper.stripExtension(j);
}}this._attachFileNameValidator(l);
var r=p.get_childListElement();
this._treeKeyDownDelegate=Function.createDelegate(this,this._treeKeyDown);
if(r){$telerik.addHandler(r,"keydown",this._treeKeyDownDelegate,true);
}break;
case"NewFolder":if(!this._isNodeADirectory(q)){q=q.get_parent();
}var m=q.get_value();
this.createNewDirectory(m);
break;
case"Delete":var i=this._createItemFromTreeViewNode(q);
this.deleteItem(i);
break;
case"Upload":this._showUploadWindow();
break;
case"Copy":var o=null;
if(!q.get_selected()){o=this._createItemFromTreeViewNode(q);
}this._copy("tree",o);
break;
case"Paste":var n=this._createItemFromTreeViewNode(q);
this._paste(n);
break;
}},_onTreeNodeDoubleClick:function(k,h){var j=h.get_node();
var i=this._createItemFromTreeViewNode(j);
this.open(i);
},_onTreeNodeClicked:function(m,h){if(!this._enabled){return;
}var l=h.get_node();
var k=this._createItemFromTreeViewNode(l);
var j=m.get_multipleSelect()&&h.get_domEvent()&&(h.get_domEvent().ctrlKey||h.get_domEvent().shiftKey);
if(k.isDirectory()&&!j){var i=new Telerik.Web.UI.FileExplorerEventArgs(k,"");
this.raiseEvent("folderChange",i);
if(i.get_cancel()){return;
}l.expand();
this._showFolderFileList(k.get_path());
return true;
}return this.raise_itemSelected(k);
},_attachAsyncUploadHandlers:function(){var h=this.get_asyncUpload();
if(h!=null){h.add_filesUploaded(Function.createDelegate(this,this._onAsyncUploadFilesUploaded));
h.add_fileUploading(Function.createDelegate(this,this._onAsyncUploadFilesUploading));
h.add_fileUploaded(Function.createDelegate(this,this._onAsyncUploadFileUploaded));
h.add_validationFailed(Function.createDelegate(this,this._onAsyncUploadValidationFailed));
h.add_fileDropped(Function.createDelegate(this,this._onAsyncUploadFileDropped));
h.add_filesSelected(Function.createDelegate(this,this._onAsyncFilesSelected));
}},_onBtnUploadClick:function(){if(!this._btnUpload.control.get_enabled()){return false;
}var i=this.get_windowManager();
if(i){var h=i.getActiveWindow();
if(h){h.close("SenderIsBtnUpload");
this._uploadFilesViaAsyncUpload();
}}return false;
},_uploadFilesViaAsyncUpload:function(){var h=this.get_asyncUpload();
if(h!=null){var k=h.getUploadedFiles();
if(k.length>0){var i=this._fileList;
if(i){if(k.length==1||!i.get_allowMultiSelect()){var j=function(l){l.selectFileByName(k[k.length-1]);
l._selectedFiles=null;
l.remove_folderLoaded(j);
};
i.add_folderLoaded(j);
}}this.refresh(k);
}h.deleteAllFileInputs();
}},_onAsyncUploadFilesUploaded:function(){if(this._droppedFilesCanBeUploadedInFileExplorer()){this._uploadFilesViaAsyncUpload();
this._finalizeFileDrop();
}if(this._btnUpload!=null){this._btnUpload.control.set_enabled(true);
}},_droppedFilesCanBeUploadedInFileExplorer:function(){return this._isFileDroppedInFileExplorerDropZone(this._dropEventTarget)&&this._isDropUploadCancelled===false;
},_finalizeFileDrop:function(){this._hideFilesDroppedLoadingPanel();
this._clearDragAndDropHelperFields();
this._displayUploadedFileCountAndTotalFileCount();
},_isFileDroppedInFileExplorerDropZone:function(h){var i=this.get_gridPane().get_element();
return i===h||$telerik.isDescendant(i,h);
},_hideFilesDroppedLoadingPanel:function(){this._hideLoadingPanel(this.get_id());
this._dropUploadInfoPanel.style.display="none";
},_clearDragAndDropHelperFields:function(){this._droppedFilesTotalCount=0;
this._uploadedFilesCount=0;
this._dropEventTarget=null;
this._droppedFilesTypes.length=0;
},_displayUploadedFileCountAndTotalFileCount:function(k,j){var i="";
k=typeof k!=="undefined"?k:0;
j=typeof j!=="undefined"?j:0;
if(j>0){var h=Math.round(k/j*1000)/10;
i="Total Progress "+h+"% ("+k+") Total "+j;
}this._uploadProgressLabel.innerHTML=i;
},_onAsyncUploadFilesUploading:function(j,h){var i=this._pullNextDroppedFileType();
if(i===""||this._isDropUploadCancelled===true){h.set_cancel(true);
if(this._isThisLastUploadingFile()){this._finalizeFileDrop();
}}this._currentUploadRow=h.get_row();
if(this._btnUpload!=null){this._btnUpload.control.set_enabled(false);
}},_pullNextDroppedFileType:function g(){return this._droppedFilesTypes.shift();
},_isThisLastUploadingFile:function(){return this._droppedFilesTypes.length===0&&this._isDropUploadCancelled===false;
},_onAsyncUploadValidationFailed:function(i,h){this._showUploadValidationFailedAlert(h.get_fileName());
this._pullNextDroppedFileType();
if(this._allDroppedFilesAreInvalid()){this._removeDroppedFiles();
this._finalizeFileDrop();
}},_showUploadValidationFailedAlert:function(h){var i=this.get_localization();
alert(h+"\n\n"+i.InvalidFileSize+"\n"+i.InvalidFileExtension);
},_allDroppedFilesAreInvalid:function(){var h=this.get_asyncUpload();
return h.getInvalidFiles().length+1===this._droppedFilesTotalCount;
},_onAsyncUploadFileDropped:function(i,h){this._droppedFilesTypes.push(h.get_file().type);
this._dropEventTarget=h.get_originalDropEvent().currentTarget;
},_onAsyncFilesSelected:function(j,h){var i=h.get_dropArgs();
if(i&&this._isFileDroppedInFileExplorerDropZone(i.target)){this._raiseFilesDroppingEvent(h);
if(!h.get_cancel()){this._showFilesDroppedLoadingPanel();
this._droppedFilesTotalCount=h.get_count();
this._displayUploadedFileCountAndTotalFileCount(0,h.get_count());
}this._isDropUploadCancelled=false;
}},_raiseFilesDroppingEvent:function(h){var i=this._createFileDroppingEventArgs(h);
this.raiseEvent("filesDropping",i);
h.set_cancel(i.get_cancel());
},_showFilesDroppedLoadingPanel:function(){this._showLoadingPanel(this.get_id());
this._dropUploadInfoPanel.style.display="block";
},_createFileDroppingEventArgs:function(h){return a.extend({get_count:function(){return h.get_count();
},get_dropArgs:function(){return h.get_dropArgs();
}},new Sys.CancelEventArgs());
},_onCancelUploadButtonClicked:function(){if(this._droppedFilesTotalCount>0){this._cancelFilesUpload();
}},_cancelFilesUpload:function(){this._isDropUploadCancelled=true;
this._cancelCurrentFileUpload();
this._removeDroppedFiles();
this._finalizeFileDrop();
},_cancelCurrentFileUpload:function(){var h=this.get_asyncUpload();
var i=this._currentUploadRow;
if(i){h._uploadModule.cancel(i);
}},_removeDroppedFiles:function(){this.get_asyncUpload().deleteAllFileInputs();
},_onAsyncUploadFileUploaded:function(){var h=++this._uploadedFilesCount;
this._displayUploadedFileCountAndTotalFileCount(h,this._droppedFilesTotalCount);
},_getGridDataItemPath:function(h){if(!h){return null;
}var i=h.Path;
if(!i){i=this.get_currentDirectory();
if(i&&i.charAt(i.length-1)!=this.get_pathSeparator().charAt(0)){i+=this.get_pathSeparator();
}i+=h.Name;
}return i;
},_setContextMenuItemsState:function(l,m,j){if(l==null||l.get_items().get_count()==0){return false;
}var h=0;
var k=l.get_items();
var i=this._copiedPaths.length>0;
k.forEach(function(n){var o=true;
switch(n.get_value()){case"Upload":case"NewFolder":o=d(m);
break;
case"Delete":o=c(m);
o=o&&(j!=true);
break;
case"Rename":o=d(m)&&c(m);
o=o&&(j!=true);
break;
case"Copy":o=(j!=true);
break;
case"Paste":o=d(m);
o=o&&i;
break;
}if(!o){h++;
}n.set_enabled(o);
});
return true;
},_renameItem:function(i,j){var h=new Telerik.Web.UI.FileExplorerEventArgs(i,j,true);
this.raiseEvent("move",h);
if(h.get_cancel()){return false;
}var k=b.FileExplorerHelper.extractPathFromExplorerItem(i,this);
this._postbackTreeAjaxPanel("CallbackFnRenameItem_"+k+"***"+j);
},_isNodeADirectory:function(i){if(this._explorerMode==Telerik.Web.UI.FileExplorerMode.Default){return true;
}else{var h=i.get_attributes();
return !h.getAttribute("Length");
}},_updateCopyCursor:function(h){if(h){Sys.UI.DomElement.addCssClass(this.get_element(),this._copyCursorClassName);
}else{Sys.UI.DomElement.removeCssClass(this.get_element(),this._copyCursorClassName);
}},_checkCopyCursor:function(k,h){if(this._enableCopy){var i=h.get_domEvent().ctrlKey;
var j=Sys.UI.DomElement.containsCssClass(this.get_element(),this._copyCursorClassName);
if(i!=j){this._updateCopyCursor(i);
}}},_probeTreeForScrolling:function(h){var k={x:0,y:0};
var i=$telerik.isTouchDevice?$telerik.getTouchEventLocation(h):{x:h.clientX,y:h.clientY};
var l=this.get_treePane();
var j=$telerik.getBounds(l.getContentElement());
if(i.y<j.y+20){k.y=-1;
}else{if(i.y>j.y+j.height-20){k.y=1;
}}if(i.x<j.x+20){k.x=-1;
}else{if(i.x>j.x+j.width-20){k.x=1;
}}return k;
},_scrollTreeViewOnDrag:function(h){var j=this.get_treePane();
var i=this._probeTreeForScrolling(h);
if(i!=0){j.setScrollPos(j.getScrollPos().left+i.x*5,j.getScrollPos().top+i.y*5);
}},_lightweightDialogDimentions:{height:155,heightSilk:155,heightGlow:155,heightBootstrap:215,heightBlackMetroTouch:215,heightMetroTouch:215},_classicDialogDimentions:{height:330,heightSilk:195,heightGlow:195,heightBootstrap:195,heightBlackMetroTouch:215,heightMetroTouch:215},_getDialogDimensions:function(){if(this._renderMode===Telerik.Web.UI.RenderMode.Lite){return this._lightweightDialogDimentions;
}else{return this._classicDialogDimentions;
}},_getDialogDimentions:function(j){var i=this._getDialogDimensions();
var k={width:330,height:i.height,uploadItemHeight:29};
var h=this.get_windowManager().get_skin();
switch(h){case"Silk":case"Glow":case"Bootstrap":k.height=i["height"+h];
break;
case"BlackMetroTouch":case"MetroTouch":k.width=400;
k.height=i["height"+h];
k.uploadItemHeight=41;
break;
default:break;
}return k;
},_showPromptDialog:function(h,m){var j=this.get_localization();
var i=this._getDialogDimentions();
var l=a.extend({width:i.width,height:i.height,title:"",message:"",value:"",timeout:false,inputValidator:null},m||{});
l.title=j[l.title]||l.title;
l.message=j[l.message]||l.message||l.title;
var k=this.get_windowManager();
if(l.timeout===false){var n=k.radprompt(l.message,h,l.width,l.height,null,l.title,l.value);
return this._attachPromptDialogValidator(n,l.inputValidator);
}else{setTimeout(Function.createDelegate(this,function(){var o=k.radprompt(l.message,h,l.width,l.height,null,l.title,l.value);
this._attachPromptDialogValidator(o,l.inputValidator);
}),l.timeout);
}},_attachPromptDialogValidator:function(j,i){if(i){var h=j.get_popupElement().getElementsByTagName("input")[0];
$telerik.addHandler(h,"keypress",i,true);
}return j;
},_attachFileNameValidator:function(h){$telerik.addHandler(h,"keypress",this._validateFileNameInputDelegate,true);
},_getCurrentFolderItem:function(){var h=this._createItemFromPath(this.get_currentDirectory());
return h;
},_createItemFromPath:function(j){var h=null;
var k=this.get_tree();
if(k!=null){var i=k.findNodeByValue(j);
h=this._createItemFromTreeViewNode(i);
}if(h==null&&this._fileList){h=this._findItemByPath(j);
}return h;
},_validateFileNameInput:function(h){if(this._shouldPreventFileNameInput(h)){$telerik.cancelRawEvent(h);
this._alertWrongFileNameInput(h.target);
}},_shouldPreventFileNameInput:function(h){var j=this._fileNameInvalidCharacters;
var i=h.charCode||h.keyCode;
return a.inArray(i,j)>-1;
},_alertWrongFileNameInput:function(h){var i=this.get_tooltipControl();
i.set_targetControl(h);
i.set_text(this.fileNameInvalidText+":<br />"+this._getInvalidCharsToString());
setTimeout(function(){i.show();
},100);
},_getInvalidCharsToString:function(){var j=this._fileNameInvalidCharacters;
var h=[];
for(var k=0;
k<j.length;
k++){h.push(String.fromCharCode(j[k]));
}return h.join(" ");
},getFileExplorerItemFromGridDataItem:function(j){var h=j.get_dataItem();
var k=this._getGridDataItemPath(h);
var i=this._findItemByPath(k);
return i;
},getFileExplorerItemFromNode:function(h){return this._createItemFromTreeViewNode(h);
},_createItemFromTreeViewNode:function(m){if(!m){return null;
}var h=m.get_attributes();
var l=h.getAttribute("Name");
var q=h.getAttribute("Length");
if(q){q=parseInt(q,10);
}var o=h.getAttribute("Path");
var p=parseInt(h.getAttribute("Permissions"),10);
var s=h.getAttribute("Url");
var i=b.FileExplorerHelper.parseExtension(h.getAttribute("Extension"),l);
var r=q==null?Telerik.Web.UI.FileExplorerItemType.Directory:Telerik.Web.UI.FileExplorerItemType.File;
if(r==Telerik.Web.UI.FileExplorerItemType.File&&!o){var n=m.get_parent();
if(n){o=n.get_value();
if(o&&o.charAt(o.length-1)!=this.get_pathSeparator().charAt(0)){o+=this.get_pathSeparator();
}o+=l;
}}var k={type:r,permissions:p,name:l,path:o,size:q,url:s,extension:i};
var j=$create(Telerik.Web.UI.FileExplorerItem,k,null,null,null);
return j;
},_hideLoadingPanel:function(h){if(h==null){return;
}var i=this.get_ajaxLoadingPanel();
if(i){i.hide(h);
}},_showLoadingPanel:function(h){if(h==null){return;
}var i=this.get_ajaxLoadingPanel();
if(i){i.show(h);
}},_scrollFolderIntoView:function(h){if(!h){return;
}var k=this.get_treePane();
var j=k.getScrollPos();
var i=this._getNodeOffset(h);
if(this._shouldScrollTreePaneVertical(i)){j.top=this._calculateNewScrollValue(i,"top");
}if(this._shouldScrollTreePaneHorizontal(i)){j.left=this._calculateNewScrollValue(i,"left");
}if(j!=k.getScrollPos()){k.setScrollPos(j.left,j.top);
}},_calculateNewScrollValue:function(j,h){var i=h=="top"?"Height":"Width";
var l=this.get_treePane().getContentElement();
var k=l["scroll"+i]-l["client"+i];
var m=h=="top"?Math.ceil(l["client"+i]/2):0;
return Math.max(Math.min(j[h]-m,k),0);
},_shouldScrollTreePaneVertical:function(h){var i=this.get_treePane();
return(h.top>i.getContentElement().clientHeight)||(h.top<0);
},_shouldScrollTreePaneHorizontal:function(j){var k=this.get_treePane();
var h=k.getContentElement();
var i=0.45;
if(j.left>0){return j.left>i*h.clientWidth;
}return true;
},_getNodeOffset:function(h){var k=this.get_treePane();
var j=a(k.getContentElement()).position();
var i=a(h.get_element()).position();
return{top:i.top-j.top,left:i.left-j.left};
},_disableTreeMultiSelectInTouch:function(){if($telerik.isTouchDevice&&this._explorerMode==Telerik.Web.UI.FileExplorerMode.FileTree&&this.get_tree()){this.get_tree().set_multipleSelect(false);
}},_findItemByPath:function(i){var h=this._fileList.findFileByPath(i);
return h?this._fileList._toFileItem(h):null;
},get_selectedItems:function(){var l=[];
var m=this._fileList;
var s=this.get_tree();
if(m!=null){var p=m.get_selectedItems();
if(p&&p.length>0){for(var n=0,r=p.length;
n<r;
n++){var h=p[n];
var k=m._toFileItem(h);
if(k){Array.add(l,k);
}}}}if(s!=null&&l.length==0){var t=s.get_selectedNodes();
for(var q=0;
q<t.length;
q++){var o=this._createItemFromTreeViewNode(t[q]);
Array.add(l,o);
}}return l;
},get_selectedItem:function(){return this.get_selectedItems()[0];
},_selectInitialFile:function(){if(this._selectedFile){if(this._fileList){this._fileList.selectFileByName(this._selectedFile);
}else{if(this.get_tree()){var h=this.get_tree().findNodeByValue(b.FileExplorerHelper.buildPathFromName(this._selectedFile,this));
if(h){h.set_selected(true);
}}}}this._selectedFile=null;
},_getFileListViewNameByExplorerMode:function(){switch(this._explorerMode){case b.FileExplorerMode.Default:return"grid";
case b.FileExplorerMode.Thumbnails:return"thumbnails";
default:return null;
}},_back:function(){var h=this._actionsManager.get_currentAction();
if(h==this.get_currentDirectory()){this._actionsManager.shiftPointerLeft();
}this._actionsManager.undo();
},_forward:function(){var h=this._actionsManager.get_nextAction();
if(h==this.get_currentDirectory()){this._actionsManager.shiftPointerRight();
}this._actionsManager.redo();
},_updateBackForward:function(h){this._actionsManager.addAction(h);
},_executeBackForward:function(j,h){var i=h.get_action();
this.loadFolder(i,false);
},_getCurrentDirectoryElement:function(){var i=this._currentDirectoryInputID;
var h=i?$get(i):null;
return h;
},get_currentDirectory:function(){var h=this._getCurrentDirectoryElement();
return h?h.value:"";
},set_currentDirectory:function(n,h){if((null!=this._actionsManager)&&(n!=this.get_currentDirectory())&&(false!=h)){this._updateBackForward(n);
}var i=this._getCurrentDirectoryElement();
if(i){i.value=n;
}var m=this.get_tree();
var j=m.findNodeByValue(n);
if(j){j.select();
this._scrollFolderIntoView(j);
}var l=this.get_addressBox();
if(l){var k=$get(l);
if(k){k.value=n;
}}this._updateToolbar();
},get_currentPermissions:function(i){var h=this._createItemFromPath(i||this.get_currentDirectory());
return h?h.get_permissions():null;
},raise_itemSelected:function(h){var i=new Telerik.Web.UI.FileExplorerEventArgs(h,"");
this.raiseEvent("itemSelected",i);
return !i.get_cancel();
},raiseFileItemCancelEvent:function(j,i){var h=new b.FileExplorerEventArgs(j,"");
this.raiseEvent(i,h);
return h.get_cancel();
},get_localization:function(){return this._localization;
},get_pathSeparator:function(){return this._pathSeparator;
},_getCommandArgumentInput:function(){var i=this._commandArgumentInputID;
var h=i?$get(i):null;
return h;
},set_commandArgument:function(i){var h=this._getCommandArgumentInput();
if(h){h.value=i;
}},get_commandArgument:function(){var h=this._getCommandArgumentInput();
return h?h.value:null;
},_registerShortcuts:function(){if(this.get_shortcuts()){this._attachShortcutHandlers(true);
}var h=this;
setTimeout(function(){var i=h.get_element();
var k=false;
i.setAttribute("tabindex","0");
if($telerik.isIE7||$telerik.isIE6){i.setAttribute("tabIndex","0");
k=true;
}var n=h.get_tree();
if(n){var o=n.get_element();
o.setAttribute("tabindex","0");
if(k){o.setAttribute("tabIndex","0");
}o.style.outlineStyle="none";
}var m=h.get_toolbar();
if(m){m.get_element().setAttribute("tabindex","0");
if(k){m.get_element().setAttribute("tabIndex","0");
}}var j=h.get_gridPane();
if(j){j.getContentElement().setAttribute("tabindex","-1");
var l=h.get_splitter().getSplitBarByIndex(0);
if(l){a("input.rspCollapseBarCollapse",l.get_element()).attr(k?"tabIndex":"tabindex","-1");
}}},0);
},_focusFileListAfterCallback:function(){if(this._fileList){var h=this._fileList.get_element();
if(this._lastFocusedElement.id==h.id){this._lastFocusedElement=h;
this._fileList.focus();
}}},_focus:function(h){try{if(h.setActive){h.setActive();
}else{if(h.focus){h.focus();
}}return true;
}catch(i){return false;
}},_attachShortcutHandlers:function(h){if(h){this._keyDownDelegate=Function.createDelegate(this,this._keyDown);
$addHandler(this.get_element(),"keydown",this._keyDownDelegate);
this._htmlElKeyDownDelegate=Function.createDelegate(this,this._htmlElKeyDown);
$addHandler(document.documentElement,"keydown",this._htmlElKeyDownDelegate);
this._attachFocusHandlers(true);
this._windowCloseDelegate=Function.createDelegate(this,this._onWindowClose);
this.get_windowManager().add_close(this._windowCloseDelegate);
}else{if(this._keyDownDelegate){$removeHandler(this.get_element(),"keydown",this._keyDownDelegate);
this._keyDownDelegate=null;
}if(this._htmlElKeyDownDelegate){$removeHandler(document.documentElement,"keydown",this._htmlElKeyDownDelegate);
this._htmlElKeyDownDelegate=null;
}}},_attachFocusHandlers:function(j){var k=this.get_tree();
var h=this._fileList;
if(k){this._treeElement=k.get_element();
$addHandler(this._treeElement,"focus",Function.createDelegate(this,function(l){this._lastFocusedElement=this._treeElement;
}));
this._treeClickDelegate=Function.createDelegate(this,this._treeClick);
k.add_nodeClicked(this._treeClickDelegate);
}if(h){var i=h.get_element();
if(j){this._lastFocusedElement=i;
}if(this._onFocusDelegate){$telerik.removeHandler(this._lastFocusedElement||i,"focus",this._onFocusDelegate);
}this._onFocusDelegate=Function.createDelegate(this,function(l){this._lastFocusedElement=this._fileList.get_element();
});
$telerik.addHandler(i,"focus",this._onFocusDelegate);
}},_keyDown:function(i){if(!this._enabled){return;
}var k=this.get_shortcuts();
if(!this._shortCutManager){this._shortCutManager=new b.ShortCutManager(k);
}var n=i.target?i.target.className:i.srcElement.className;
if(i.rawEvent.keyCode==46&&n=="rfeFilterTxt"){return;
}var l=this._shortCutManager.isShortCutHit(i.rawEvent);
if(!l){return;
}var p=this.get_tree();
var m=l.get_name();
if(p&&m=="FocusTreeView"){var q=p.get_element();
this._focus(q);
this._lastFocusedElement=q;
}else{if(this._fileList&&m=="FocusGrid"){this._fileList.focus();
this._lastFocusedElement=this._fileList.get_control().get_element();
}else{if(this.get_addressBox()&&m=="FocusAddressBar"){var o=$get(this.get_addressBox());
if(this._focus(o)){o.select();
}}else{if(this._fileList&&m=="FocusGridPagingSlider"){this._fileList.focusPagerControl();
}else{if(this.get_toolbar()&&m=="FocusToolBar"){this._focus(this.get_toolbar().get_element());
}else{if(m=="ContextMenu"){var j=i.target?i.target:i.srcElement;
if(this._isFileListAnEventTarget(j)){this._showFileListContextMenu();
}if(j.className.indexOf("RadTreeView")!=-1){this._showTreeContextMenu(p);
}}else{var h=m.indexOf("UploadFile")!=-1?"Upload":m;
if((h=="Upload"&&!d(this.get_currentPermissions()))||(h=="Delete"&&!c(this._getSelectedItemPermissions()))){return;
}this._fireCommand(h);
}}}}}}if(m!="FocusFileExplorer"&&k.indexOf(m)!=-1){$telerik.cancelRawEvent(i.rawEvent);
return false;
}},_isFileListAnEventTarget:function(h){var i=h.className;
return i.indexOf("RadGrid")!==-1||i.indexOf("rfeListViewContainer")!==-1;
},_htmlElKeyDown:function(h){if(!this._shortCutManager){this._shortCutManager=new b.ShortCutManager(this.get_shortcuts());
}if(h.keyCode==27){this._hideContextMenus(h,true,"e");
}var j=this._shortCutManager.isShortCutHit(h);
if(!j){return;
}var k=j.get_name();
if(k=="FocusFileExplorer"){var i=this.get_element();
this._focus(i);
this._lastFocusedElement=i;
}else{if(k=="ContextMenu"){this._hideContextMenus(h,false,j.get_shortCutString().toLowerCase());
}}},_hideContextMenus:function(h,j,k){var l=false;
var i=this.get_gridContextMenu();
if(i&&i._shown){i.hide();
l=true;
k=k.replace(/\s*/gi,"");
this._shouldShowGridContextMenu=(k=="context"||k=="shift+f10")?j:true;
}var m=this.get_tree();
if(m){var n=m.get_contextMenus()[0];
if(n&&n._shown){n.hide();
this._lastFocusedElement=m.get_element();
l=true;
}}if(l){this._focus(this._lastFocusedElement);
$telerik.cancelRawEvent(h.rawEvent);
return false;
}},_treeKeyDown:function(h){if(h.keyCode==27){var j=this.get_tree();
this._lastFocusedElement=j.get_element();
if($telerik.isIE){var i=this;
window.setTimeout(function(){i._focus(i._lastFocusedElement);
},100);
}else{this._focus(this._lastFocusedElement);
}if(this._treeKeyDownDelegate){var k=j.get_childListElement();
if(k){$removeHandler(k,"keydown",this._treeKeyDownDelegate);
this._treeKeyDownDelegate=null;
}}}},_onWindowClose:function(i,h){if(h.get_argument()!="SenderIsBtnUpload"&&this.get_asyncUpload()!=null){this.get_asyncUpload().deleteAllFileInputs();
}var j=this;
window.setTimeout(function(){if(j._lastFocusedElement){j._focus(j._lastFocusedElement);
}},0);
},_treeClick:function(i,h){this._lastFocusedElement=i.get_element();
this._focus(this._lastFocusedElement);
},_showFileListContextMenu:function(){var h=this._fileList;
if(h.get_items().length===0){return;
}this._selectedFileListItem=this._getSelectedFileListItem();
var i=h.get_contextMenu();
var j=this._setContextMenuItemsState(i,this.get_currentPermissions(this._selectedFileListItem.Path));
if(j&&i){this._showContextMenuAtItem(i,this._selectedFileListItem);
}},_getSelectedFileListItem:function(){var h=this._fileList;
if(h.get_selectedItemsDataAndElement().length===0){h.selectDefaultFile();
}return h.get_selectedItemsDataAndElement()[0];
},_showContextMenuAtItem:function(i,j){var h=$telerik.getBounds(j.get_element());
i.showAt(h.x+60,h.y+h.height,null);
i.get_items().getItem(0).focus();
},_showTreeContextMenu:function(l){var m=l.get_contextMenus()[0];
var j=l.get_selectedNode();
l._contextMenuNode=j;
var i=this._createItemFromTreeViewNode(j);
var k=this._setContextMenuItemsState(m,i.get_permissions());
if(k&&m){var h=$telerik.getBounds(j.get_element());
m.showAt(h.x+60,h.y+20,null);
m.get_items().getItem(0).focus();
}},_getSelectedItemPermissions:function(){return this.get_currentPermissions(this.get_selectedItem().get_path());
}};
a.registerControlProperties(b.RadFileExplorer,{allowPaging:false,enableOpenFile:true,enableFilteringOnEnter:false,addressBox:"",postbackButton:null,windowManager:null,gridPane:null,treePane:null,ajaxLoadingPanel:null,gridContextMenu:null,grid:null,listView:null,splitter:null,toolbar:null,tooltipControl:null,asyncUpload:null,newFolderDefaultValue:"NewFolder",shortcuts:null});
a.registerControlEvents(b.RadFileExplorer,["itemSelected","folderLoaded","fileOpen","folderChange","init","load","eventHandlersAttached","createNewFolder","delete","move","copy","ajaxRequestStart","ajaxRequestEnd","filter","filesDropping"]);
Telerik.Web.UI.RadFileExplorer.registerClass("Telerik.Web.UI.RadFileExplorer",Telerik.Web.UI.RadWebControl);
var e=function(i,h){b[i]=function(){var j=Array.prototype.slice.call(arguments);
b[i].initializeBase(this,j);
};
b[i].registerClass("Telerik.Web.UI."+i,h);
};
Telerik.Web.UI.FileExplorerEventArgs=function(i,j,h){Telerik.Web.UI.FileExplorerEventArgs.initializeBase(this);
this._item=i;
this._newPath=j;
this._isRename=!!h;
};
Telerik.Web.UI.FileExplorerEventArgs.prototype={get_path:function(){return this._item.get_path();
},get_newPath:function(){return this._newPath;
},get_item:function(){return this._item;
},get_isRename:function(){return this._isRename;
}};
Telerik.Web.UI.FileExplorerEventArgs.registerClass("Telerik.Web.UI.FileExplorerEventArgs",Sys.CancelEventArgs);
e("RadFileExplorerEventArgs",Telerik.Web.UI.FileExplorerEventArgs);
Telerik.Web.UI.FileExplorerCopyEventArgs=function(h,i){Telerik.Web.UI.FileExplorerCopyEventArgs.initializeBase(this);
this._items=h;
this._newPath=i;
};
Telerik.Web.UI.FileExplorerCopyEventArgs.prototype={get_newPath:function(){return this._newPath;
},get_items:function(){return this._items;
},get_item:function(){return this._items.length>0?this._items[0]:null;
},get_path:function(){return this._items.length>0?this._items[0].get_path():null;
}};
Telerik.Web.UI.FileExplorerCopyEventArgs.registerClass("Telerik.Web.UI.FileExplorerCopyEventArgs",Sys.CancelEventArgs);
e("RadFileExplorerCopyEventArgs",Telerik.Web.UI.FileExplorerCopyEventArgs);
Telerik.Web.UI.FileExplorerFilterEventArgs=function(i,h){Telerik.Web.UI.FileExplorerFilterEventArgs.initializeBase(this);
this._text=i;
this._domEvent=h;
};
Telerik.Web.UI.FileExplorerFilterEventArgs.prototype={get_text:function(){return this._text;
},set_text:function(h){this._text=h;
},get_domEvent:function(){return this._domEvent;
}};
Telerik.Web.UI.FileExplorerFilterEventArgs.registerClass("Telerik.Web.UI.FileExplorerFilterEventArgs",Sys.CancelEventArgs);
e("RadFileExplorerFilterEventArgs",Telerik.Web.UI.FileExplorerFilterEventArgs);
a.registerEnum(b,"FileExplorerItemType",{File:0,Directory:1});
a.registerEnum(b,"FileExplorerItemPermissions",{Read:1,Upload:2,Delete:4});
a.registerEnum(b,"FileExplorerMode",{Default:1,FileTree:2,Thumbnails:3});
a.registerEnum(b,"FileExplorerControls",{Tree:1,FileList:2});
Telerik.Web.UI.FileExplorerItem=function(){Telerik.Web.UI.FileExplorerItem.initializeBase(this);
this._url="";
};
Telerik.Web.UI.FileExplorerItem.prototype={get_url:function(){return this._url?this._url:this._path;
},set_url:function(h){this._url=h;
},isDirectory:function(){return this._type==Telerik.Web.UI.FileExplorerItemType.Directory;
}};
a.registerControlProperties(b.FileExplorerItem,{size:"",extension:"",path:"",name:"",permissions:Telerik.Web.UI.FileExplorerItemPermissions.Read,type:Telerik.Web.UI.FileExplorerItemType.File});
Telerik.Web.UI.FileExplorerItem.registerClass("Telerik.Web.UI.FileExplorerItem",Sys.Component);
})();
