(function(a,b,l){var g=window.kendo,e=g.dataviz.map,h="load",f="initialize",j="MissingRadClientDataSource";
var i="markerAdd",k="popupInit";
var c=e.layers.MarkerLayer.fn._addOne;
e.layers.MarkerLayer.fn._addOne=function(m){var n=c.call(this,m);
this.map.trigger(i,{marker:n});
return n;
};
var d=g.ui.Tooltip.fn._initPopup;
g.ui.Tooltip.fn._initPopup=function(){d.call(this);
this.trigger(k);
};
b.RadMap=function(m){var n=this;
b.RadMap.initializeBase(n,[m]);
n._initialized=false;
n._options={};
n._element=m;
n.kendoWidget=null;
};
b.RadMap.prototype={initialize:function(){var n=this;
if(n._initialized){return;
}try{n._initialize();
}catch(m){if(m&&m.message==j){if(!n._appLoadAdded){n._appLoadAdded=true;
Sys.Application.add_load(function(){n._initialize();
});
}}else{throw m;
}}},_initialize:function(){var m=this;
if(!m._options){return;
}b.RadMap.callBaseMethod(m,"initialize");
m._initializeLayers();
m._riseInitializeEvent();
m._moveClientStateFieldAfterElement();
m.kendoWidget=a(m._element).kendoMap(m._options).data("kendo-map");
m._initializeKendoWidget();
m.raiseEvent(h);
m.updateClientState();
m._initialized=true;
},_initializeLayers:function(){var q=this,o=q._options.layers;
if(o){for(var m=0,p=o.length;
m<p;
m++){var n=o[m];
q._initializeLayerDataSource(n);
}}},_initializeLayerDataSource:function(o){var n=o.clientDataSourceID;
if(n){var m=$find(n);
if(m&&(m instanceof b.RadClientDataSource)){o.dataSource=m._kendoDataSource;
}else{if(m===null){throw new Error(j);
}}}},_riseInitializeEvent:function(){var n=this,m=new b.RadMapInitializeEventArgs(n._options);
n.raiseEvent(f,m);
n._options=m.get_options();
},_moveClientStateFieldAfterElement:function(){var m=this;
a("#"+m._clientStateFieldID).insertAfter(m._element);
},_initializeKendoWidget:function(){var m=this;
m._bindToWidgetEvents();
m._initializeMarkersTooltips();
},_bindToWidgetEvents:function(){var m=this;
m.kendoWidget.bind("reset",function(n){m.updateClientState();
}).bind("panEnd",function(n){m.updateClientState();
}).bind(i,function(n){m._bindToTooltipPopupInit(n.marker.tooltip);
});
},_initializeMarkersTooltips:function(){var o=this,n=o.kendoWidget.markers?o.kendoWidget.markers.items||[]:[];
for(var m=0;
m<n.length;
m++){o._bindToTooltipPopupInit(n[m].tooltip);
}},_bindToTooltipPopupInit:function(n){if(!n){return;
}var m=this.get_skin();
n.bind(k,function(o){o.sender.popup.element.addClass("RadMap RadMap_"+m);
});
},dispose:function(){var m=this;
if(m.kendoWidget){m.kendoWidget.destroy();
}delete m.kendoWidget;
delete m._options;
b.RadMap.callBaseMethod(m,"dispose");
},repaint:function(){this.kendoWidget.resize();
},get_kendoWidget:function(){return this.kendoWidget;
},saveClientState:function(){var o=this,m=o.kendoWidget.center(),p=o.kendoWidget.zoom(),n='{"zoom":'+p+',"centerLatitude":'+m.lat+',"centerLongitude":'+m.lng+"}";
return n;
}};
b.RadMap.registerClass("Telerik.Web.UI.RadMap",b.RadWebControl);
a.registerControlProperties(b.RadMap,{skin:""});
a.registerControlEvents(b.RadMap,[f,h]);
b.RadMapInitializeEventArgs=function(m){this._options=m;
};
b.RadMapInitializeEventArgs.prototype={get_options:function(){return this._options;
},set_options:function(m){this._options=m;
}};
b.RadMapInitializeEventArgs.registerClass("Telerik.Web.UI.RadMapInitializeEventArgs",Sys.EventArgs);
})($telerik.$,Telerik.Web.UI);
