(function(){Type.registerNamespace("Telerik.Web.UI");
var a=Telerik.Web.UI;
Telerik.Web.UI.GridMobileEditView=function(b){this._editIndexHierarhical=null;
this._ownerId=null;
a.GridMobileEditView.initializeBase(this,[b]);
};
a.GridMobileEditView.prototype={initialize:function(){a.GridMobileEditView.callBaseMethod(this,"initialize");
},dispose:function(){a.GridMobileEditView.callBaseMethod(this,"dispose");
},get_owner:function(){if(!this._owner){this._owner=$find(this._ownerId);
}return this._owner;
},onInit:function(){this.changed();
},applyChanges:function(){if(this._editIndexHierarhical){this.get_owner().fireCommand("Update",this._editIndexHierarhical);
}else{this.get_owner().fireCommand("PerformInsert","");
}},show:function(){a.GridMobileEditView.callBaseMethod(this,"show");
},close:function(){if(this._editIndexHierarhical){this.get_owner().fireCommand("CancelUpdate",this._editIndexHierarhical);
}else{this.get_owner().fireCommand("CancelInsert","");
}}};
a.GridMobileEditView.registerClass("Telerik.Web.UI.GridMobileEditView",Telerik.Web.UI.GridMobileView);
})();
