(function(a,b){var i=a.noop,c=a.extend,k=a.proxy,f=a.merge,g=function(r,t){if(t&&t.filter){var s=t.filter,q=r.filter;
q.logic=s.logic||q.logic;
if(s.filters){f(q.filters,s.filters);
}}},h=function(q,r){if(r&&r.sort){f(q.sort,r.sort);
}},e={0:"jsonp",1:"xml"},n="requesting",m="requestSucceeded",l="requestFailed",o="string",j="null",p;
var d=function(q){(function(){var s={};
a.extend(q,{bind:function(u,t){a.each(u,function(v,w){r(v,w,t);
});
},trigger:function(){var t=Array.prototype.slice.call(arguments),u=t.shift();
a(s).trigger(u,t);
},disposeEvents:function(){a(s).off();
}});
function r(u,v,t){a(s).on(u,k(v,t));
}})();
};
Type.registerNamespace("Telerik.Web.UI");
b.RadODataDataSource=function(){b.RadODataDataSource.initializeBase(this);
this._models={};
this._url="";
this._filtering=false;
this._sorting=false;
this._paging=false;
this._enableDataCaching=false;
};
b.RadODataDataSource.prototype={initialize:function(){b.RadODataDataSource.callBaseMethod(this,"initialize");
this._initializeModels();
},dispose:function(){b.RadODataDataSource.callBaseMethod(this,"dispose");
var r=this._models;
for(var q in r){r[q].dispose();
}},fetch:function(r,s){if(r){var q=this._models[r];
if(!q){alert("No Data Model with name "+r+" was found");
}else{q.get_query().execute(s);
}}},get_options:function(q){var r,u=this.get_transport(),t=this,s=this.getPagerByModel(q),v=e[u.Read.DataType];
r={dataType:v,url:u.Read.Url,data:{filter:t.getFiltersByModel(q),sort:t.getSortsByModel(q),select:t.getSelectionByModel(q),config:{paging:t._paging,sorting:t._sorting,filtering:t._filtering,caching:t._enableDataCaching,json:v==="jsonp"}}};
c(r.data,s);
return r;
},getFiltersByModel:function(q){return this._getFieldByModel(q,"filters");
},_getFieldByModel:function(t,q,r){if(!r){r=this["get_"+q]();
}for(var s=0;
s<r.length;
s++){if(r[s].modelID==t){return r[s];
}}},getSortsByModel:function(q){var r=this._getFieldByModel(q,"sorts");
if(r){return r.sorts;
}},getSelectionByModel:function(r){var t=this._schema;
for(var q=0;
q<t.length;
q++){var s=t[q];
if(s.ModelID==r){if(s.Fields.length>0){return s.Fields;
}else{return p;
}}}},getPagerByModel:function(r){var t=this._schema;
for(var q=0;
q<t.length;
q++){var s=t[q];
if(s.ModelID==r){return{skip:s.PageIndex*s.PageSize,take:s.PageSize,page:s.PageIndex,pageSize:s.PageSize};
}}},get_model:function(q){return this._models[q];
},_initializeModels:function(){var v=this._schema,s=this._models;
for(var q=0;
q<v.length;
q++){var t=v[q],r=t.ModelID,u=this.get_options(r);
s[r]=new b.RadODataDataSource.Model(t,u);
this._attachHandlersForModel(s[r]);
}},_attachHandlersForModel:function(q){var r=this;
q.bind({requesting:r._onRequesting,requestSucceeded:r._onRequestSucceeded,requestFailed:r._onRequestFailed},r);
},_onRequesting:function(r,q){a.raiseControlEvent(this,"requesting",q);
},_onRequestSucceeded:function(s,r){var q={data:r.data,count:r.count,modelName:r.modelName,context:r.context};
a.raiseControlEvent(this,"requestSucceeded",q);
},_onRequestFailed:function(r,q){a.raiseControlEvent(this,"requestFailed",q);
}};
a.registerControlProperties(b.RadODataDataSource,{filters:[],sorts:[],schema:null,transport:null});
a.registerControlEvents(b.RadODataDataSource,[n,m,l]);
b.RadODataDataSource.Model=function(q,r){d(this);
this._id=q.ModelID;
this._fields=q.Fields;
this._options=r;
this._options.url=this._initUrl(r.url,q.Set);
this._events={};
this._query=new b.RadODataDataSource.Query(this);
var s=this;
this._query.bind({requesting:function(u,t){t.modelName=s._id;
s.trigger(n,t);
},requestSucceeded:function(u,t){t.modelName=s._id;
s.trigger(m,t);
},requestFailed:function(v,u){var t={statusCode:u.status,message:u.statusText,modelName:s._id};
s.trigger(l,t);
}});
};
b.RadODataDataSource.Model.prototype={_initUrl:function(r,q){if(r[r.length-1]!=="/"){r=r+"/";
}return r+q;
},nextPage:function(){var q=this._options.data,r=++q.page;
this.set_pageIndex(r);
},previousPage:function(){var q=this._options.data,r=--q.page;
this.set_pageIndex(r);
},dispose:function(){this.disposeEvents();
this.get_query().dispose();
},get_filterExpressions:function(){return this._options.data.filter;
},set_filterExpressions:function(r){var q=this._options.data;
q.filter=q.filter||{filters:[]};
this._setFilterOrSort(q.filter.filters,r);
},get_sortExpressions:function(){return this._options.data.sort;
},set_sortExpressions:function(q){this._setFilterOrSort(this._options.data.sort,q);
},_setFilterOrSort:function(s,r){if(a.type(r)==="array"){for(var q=0;
q<r.length;
q++){s.push(r[q]);
}}else{s.push(r);
}},get_query:function(){return this._query;
},get_options:function(){return this._options;
},get_pageIndex:function(){return this._options.data.page;
},get_pageSize:function(){return this._options.data.take;
},set_pageIndex:function(r){var q=this._options.data;
q.skip=r*q.take;
q.page=r;
this._query.execute(this._options);
},set_pageSize:function(r){var q=this._options.data;
q.pageSize=r;
q.take=r;
q.skip=q.page*r;
},get_totalCount:function(q){var s=this._options,r=new b.RadODataDataSource.DataCountQuery(s.url,s.dataType,q);
r._fetch();
}};
(function(){var s={eq:"eq",neq:"ne",gt:"gt",gte:"ge",lt:"lt",lte:"le",contains:"substringof",endswith:"endswith",startswith:"startswith"};
var r={pageSize:i,page:i,filter:function(x,w){if(w){x.$filter=u(w);
}},sort:function(x,w){if(w){x.$orderby=a.map(w,function(z){var y=z.field.replace(/\./g,"/");
if(z.dir==="desc"){y+=" desc";
}return y;
}).join(",");
}},skip:function(w,x){if(x){w.$skip=x;
}},take:function(w,x){if(x){w.$top=x;
}},select:function(w,x){if(x){w.$select=v(x);
}}};
function v(y){var x=[];
for(var w=0;
w<y.length;
w++){x[w]=y[w].FieldName;
}return x.join(",");
}function u(x){var E=[],C=x.logic||"and",A,B,w,F,z,D,G,y=x.filters;
for(A=0,B=y.length;
A<B;
A++){x=y[A];
w=x.field;
G=x.value;
D=x.operator;
if(x.filters){x=u(x);
}else{w=w.replace(/\./g,"/");
x=s[D];
if(x&&G!==p){G=t(G,D);
F=a.type(G);
if(F===o&&!G.startsWith("guid")||F===j){if(G&&G!==j){z="'{1}'";
G=G.replace(/'/g,"''");
}else{G=j;
z="{1}";
}}else{if(F==="date"){z="datetime'{1:yyyy-MM-ddTHH:mm:ss}'";
}else{z="{1}";
}}if(x.length>3){if(x!=="substringof"){z="{0}({2},"+z+")";
}else{z="{0}("+z+",{2})";
}}else{z="{2} {0} "+z;
}x=String.format(z,x,G,w);
}}E.push(x);
}x=E.join(" "+C+" ");
if(E.length>1){x="("+x+")";
}return x;
}function q(w){return w=="contains"||w=="endswith"||w=="startswith";
}function t(w,y){var x,z=typeof w;
if(q(y)){return w+="";
}if(z===o&&w.match(/\D/gi)&&Date.parse(w)){return new Date(w);
}if(z===o&&w.match(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)){return"guid'"+w+"'";
}x=parseFloat(w);
return x?x:w;
}b.RadODataDataSource.Parsers={OData:{jsonp:{data:function(w){var x=w.value?w.value:w.d.results||w.d;
if(a.type(x)!=="array"){x=a.makeArray(x);
}return x;
},total:function(w){var x=w.d?w.d.__count:w["odata.count"];
return parseInt(x,10);
}},xml:{data:function(x){var w=a(a.parseXML(x)||x),z=[],y=this;
w.find("entry").each(function(D,B){var C={},A=a(B).children("content").children(":first");
y._populateProperties(C,A);
z.push(C);
});
return z;
},total:function(x){var w=a(a.parseXML(x)||x);
return w.find("entry").length;
},_populateProperties:function(y,w){var x=this;
w.children().each(function(z,B){var A=B.localName||B.baseName;
if(B.childNodes.length<=1){y[A]=B.textContent||B.text;
}else{y[A]={};
x._populateProperties(y[A],a(B));
}});
}}}};
b.RadODataDataSource.DataCountQuery=function(y,x,w){this._url=y+"/$count";
this._dataType=x;
this._success=w.success;
this._fail=w.fail;
this._initializeQuery();
};
b.RadODataDataSource.DataCountQuery.prototype={_initializeQuery:function(){var x=this,w={cache:true,url:x._url,success:x._success,error:x._fail};
if(this._dataType=="jsonp"){w=c(true,w,{dataType:x._dataType,jsonp:"$callback",data:{$format:"json"}});
}else{w=c(true,w,{dataType:"text"});
}this._options=w;
},_fetch:function(){a.ajax(this._options);
}};
b.RadODataDataSource.Query=function(w,x){d(this);
this._model=w;
this._options=x||w.get_options();
var y=this._options.dataType;
if(this._options.data.config.caching){this._cache=new b.RadODataDataSource.DataCache(this);
}this._parser=b.RadODataDataSource.Parsers.OData[y];
};
b.RadODataDataSource.Query.prototype={_parameterMap:function(x,z){var y,w;
x=x||{};
y=this._params(x);
for(w in x){if(r[w]){r[w](y,x[w]);
}else{y[w]=x[w];
}}return y;
},_params:function(x){var w=x.config;
var y={};
if(w.json){y.$format="json";
}if(w.paging){y.$inlinecount="allpages";
}return y;
},_onSuccess:function(x,y){var z=this._parser,w=y?y.context:{};
var A={data:z.data(x),count:z.total(x),context:w};
if(this._cache){this._cache.add(A,y);
}this.trigger(m,A);
},_onFail:function(w){this.trigger(l,w);
},_send:function(w){var x=c(true,{},w);
delete x.data.config;
a.ajax(x);
},dispose:function(){if(this._cache){this._cache.clear();
this._cache=null;
}this.disposeEvents();
},setup:function(w){if(w.dataType=="jsonp"){w.jsonp="$callback";
}w.cache=true;
var x=c({},w.data),y=this;
w.data=this._parameterMap(x);
w.success=function(z){y._onSuccess(z,w);
};
w.error=k(this._onFail,this);
return w;
},_mergeData:function(w,x){if(x!=p){w.page=x.page||w.page;
w.pageSize=x.pageSize||w.pageSize;
w.skip=w.page*w.pageSize;
w.take=w.pageSize;
g(w,x);
h(w,x);
}},execute:function(y){var A=c(true,{},this._options),z=A.data;
z.filter=A.data.filter||{filters:[]};
z.sort=A.data.sort||[];
if(y!=p){this._mergeData(z,y);
}var w={options:A,set_filterExpressions:function(C){z.filter.filters.push(C);
},set_sortExpressions:function(C){z.sort.push(C);
},set_pageIndex:function(C){z.skip=C*z.take;
z.page=C;
},set_pageSize:function(C){z.take=C;
z.skip=z.page*C;
}};
this.trigger(n,w);
A=this.setup(A);
if(this._cache){var x=this._cache.get(A);
if(x&&x.data){var B={data:x.data,count:x.count};
this.trigger(m,B);
return;
}}this._send(A);
}};
b.RadODataDataSource.DataCache=function(w){this._owner=w;
this._data={};
this._counts={};
};
b.RadODataDataSource.DataCache.prototype={add:function(y,A){var x=y.data,w=y.count,z=this._buildCacheKey(A);
if(typeof(x)==="object"&&(x.length)){this._data[z]=x;
this._counts[z]=w;
}},get:function(x){var w=this._buildCacheKey(x);
return{data:this._data[w],count:this._counts[w]};
},clear:function(){this._data={};
this._counts={};
},_buildCacheKey:function(y){var w=y.data,A=y.url,x=w.$filter?w.$filter.replace(/\s+/gim,""):"",z=w.$orderby?w.$orderby.replace(/\s+/gim,""):"";
return encodeURIComponent([A,w.$skip,w.$top,w.$select,x,z].join("-"));
}};
})();
b.RadODataDataSource.registerClass("Telerik.Web.UI.RadODataDataSource",Sys.Component);
})($telerik.$,Telerik.Web.UI);
