(function(a,b,c){if(!b.RadPanelItem.Views){b.RadPanelItem.Views={};
}b.RadPanelItem.Views.Lite=function(d){this._owner=d;
};
b.RadPanelItem.Views.Lite.prototype={get_textElement:function(){var d=this._owner.get_linkElement();
if(d){return a(d).find("span.rpText").get(0)||null;
}else{return null;
}},get_linkElement:function(){if(!this._owner._linkElement){this._owner._linkElement=$telerik.getFirstChildByTagName(this._owner.get_element(),"a",0)||$telerik.getFirstChildByTagName(this._owner.get_element(),"span",0);
}return this._owner._linkElement;
},get_headerElement:function(){if(!this._owner._headerElement){this._owner._headerElement=a(this._owner.get_element()).children("a.rpLink, span.rpLink, div.rpHeaderTemplate").get(0);
}return this._owner._headerElement;
},_onExpandHandleMouseOver:function(d){if(!this._owner.get_isEnabled()){return true;
}a(this._owner.get_expandHandleElement()).addClass("rpHovered");
if(this._owner._shouldNavigate()){a(this._owner.get_headerElement()).addClass("rpHovered");
}return true;
},_onExpandHandleMouseOut:function(d){if(!this._owner.get_isEnabled()){return true;
}var f=a(this._owner.get_expandHandleElement());
if(f.hasClass("rpHovered")){f.removeClass("rpHovered");
}return true;
},_render:function(d){d[d.length]="<li class='"+this._owner._determineCssClass()+"'>";
this._owner._renderLink(d);
if(this._owner.get_imageUrl()){this._owner._renderImage(d);
}d[d.length]="<span class='rpText'>";
d[d.length]=this._owner.get_text();
d[d.length]="</span>";
d[d.length]="<span class='rpExpandHandle'></span>";
var e=this._owner.get_navigateUrl();
if(e){d[d.length]="</a>";
}else{d[d.length]="</span>";
}this._owner._renderChildList(d);
d[d.length]="</li>";
},_renderLink:function(e){if(this._owner._isSeparator){return;
}var d="#";
var f=this._owner.get_navigateUrl();
if(f){d=f;
e[e.length]='<a href="';
e[e.length]=d;
e[e.length]='" ';
}else{e[e.length]="<span ";
}var g=this._owner.get_target();
if(g){e[e.length]='target="';
e[e.length]=g;
e[e.length]='" ';
}if(this._owner.get_enabled()){e[e.length]='class="rpLink"';
}else{e[e.length]='class="rpLink rpDisabled"';
}e[e.length]=">";
return e;
}};
})($telerik.$,Telerik.Web.UI);
