Type.registerNamespace("Telerik.Web");
(function(){$telerik.toRating=function(d){return d;
};
$telerik.findRating=$find;
var a=Telerik.Web.UI;
var b=function(e,d){a[e]=function(){var f=Array.prototype.slice.call(arguments);
a[e].initializeBase(this,f);
};
a[e].registerClass("Telerik.Web.UI."+e,d);
};
a.RatingPrecision=function(){};
a.RatingPrecision.prototype={Item:0,Half:1,Exact:2};
a.RatingPrecision.registerEnum("Telerik.Web.UI.RatingPrecision");
a.RatingSelectionMode=function(){};
a.RatingSelectionMode.prototype={Single:0,Continuous:1};
a.RatingSelectionMode.registerEnum("Telerik.Web.UI.RatingSelectionMode");
a.RatingRatingEventArgs=function(d){a.RatingRatingEventArgs.initializeBase(this);
this._newValue=d;
};
a.RatingRatingEventArgs.prototype={get_newValue:function(){return this._newValue;
}};
a.RatingRatingEventArgs.registerClass("Telerik.Web.UI.RatingRatingEventArgs",Sys.CancelEventArgs);
b("RadRatingRatingEventArgs",Telerik.Web.UI.RatingRatingEventArgs);
a.RatingRatedEventArgs=function(d){a.RatingRatedEventArgs.initializeBase(this);
this._oldValue=d;
};
a.RatingRatedEventArgs.prototype={get_oldValue:function(){return this._oldValue;
}};
a.RatingRatedEventArgs.registerClass("Telerik.Web.UI.RatingRatedEventArgs",Sys.EventArgs);
b("RadRatingRatedEventArgs",Telerik.Web.UI.RatingRatedEventArgs);
a.RadRating=function(d){a.RadRating.initializeBase(this,[d]);
this._itemCount=5;
this._value=0;
this._doubleValue="0";
this._selectionMode=a.RatingSelectionMode.Continuous;
this._precision=a.RatingPrecision.Item;
this._orientation=a.Orientation.Horizontal;
this._isDirectionReversed=false;
this._enableToolTips=true;
this._autoPostBack=false;
this._readOnly=false;
this._enabled=true;
this._uniqueID=null;
this._preInitializeComplete=false;
this._ulWrapper=null;
this._items=[];
this._itemData=[];
this._definedItems=false;
this._itemWidth="";
this._itemHeight="";
this._documentMouseMoveDelegate=null;
this._selectedItemCssClass="rrtSelected";
this._hoveredItemCssClass="rrtOver";
this._clearSelectedStateOnHover=false;
};
a.RadRating.prototype={initialize:function(){if(!this._preInitializeComplete){a.RadRating._preInitialize(this.get_id(),this._orientation);
}a.RadRating.callBaseMethod(this,"initialize");
$telerik.$(".tm",this.get_element()).remove().contents().insertBefore(this.get_element());
var f=this._ulWrapper=$telerik.getFirstChildByTagName(this.get_element(),"ul",0);
this._decorateListWrapper();
this._createItemData();
if(!this._readOnly&&this._enabled){var d=this._getMainEventHandlers();
$addHandlers(f,d,this);
}$addHandler(f,"click",this._cancelEvent);
this._synchronizeUIWithValue(this._value,true);
this.get_element().value=this._doubleValue;
var e=this;
setTimeout(function(){e._requestItemsHoverImages();
},0);
this.raiseEvent("load");
if(!this.canRepaint()){this.add_parentShown(this.get_element());
}},dispose:function(){this._attachDocumentHandlers(false);
this._createPartElements(false);
this._storeStartCoords(false);
this._spanSize=null;
this._hoveredItem=null;
$clearHandlers(this._ulWrapper);
this._ulWrapper=null;
this._items=null;
this._itemData=[];
a.RadRating.callBaseMethod(this,"dispose");
},repaint:function(){a.RadRating._preInitialize(this.get_id(),this._orientation);
var d=this._value;
this._clearSelection(d);
this._synchronizeUIWithValue(d);
},_decorateListWrapper:function(){if($telerik.isMobileSafari){$telerik.$(this._ulWrapper).addClass("_Telerik_MobileSafari");
}},_getMainEventHandlers:function(){return $telerik.isTouchDevice?{mouseup:this._mouseUpTouchDevice}:{mouseover:this._mouseOver,mouseup:this._mouseUp,mouseout:this._mouseOut};
},_createItemData:function(){var j=this._isDirectionReversed,h,q;
var m=this._items=$telerik.getChildrenByTagName(this._ulWrapper,"li");
if(j){var r=[];
for(h=(m.length-1);
h>=0;
h--){r[r.length]=m[h];
}m=this._items=r;
}var o=0;
var n=0;
var k=this._itemData;
var e=this._definedItems=(k&&k.length>0);
for(h=0,q=m.length;
h<q;
h++){var d;
if(!e){d={value:(h+1)};
}else{d=k[h];
var v={};
var s={};
if(!d.imageUrl){d.imageUrl="";
}else{v.url="url("+d.imageUrl+")";
}if(!d.selectedImageUrl){d.selectedImageUrl=d.imageUrl;
}if(d.selectedImageUrl){s.url="url("+d.selectedImageUrl+")";
}if(d.imageUrl||d.selectedImageUrl){o++;
}var f=d.hoveredImageUrl;
var g=d.hoveredSelectedImageUrl;
if(f||g){d.hoveredImageUrl=f?f:g;
d.hoveredSelectedImageUrl=g?g:f;
n++;
}else{d.hoveredImageUrl=d.selectedImageUrl;
d.hoveredSelectedImageUrl=d.selectedImageUrl;
}if(d.hoveredImageUrl){v.hoveredUrl="url("+d.hoveredImageUrl+")";
}if(d.hoveredSelectedImageUrl){s.hoveredUrl="url("+d.hoveredSelectedImageUrl+")";
}d.item=(j?s:v);
d.itemSpan=(j?v:s);
}d.index=h;
d.itemElement=m[h];
k[h]=d;
}if(e&&n==0&&o>0){this._clearSelectedStateOnHover=true;
}var p=this._itemWidth;
var u=(""!=p);
p=parseInt(p,10)+"px";
var l=this._itemHeight;
var t=(""!=l);
l=parseInt(l,10)+"px";
if(a.Orientation.Horizontal==this._orientation){if(u){m.itemSpanWidth=j?p:"0px";
m.itemSpanSelectedWidth=j?"0px":p;
if(t){m.itemPartsStaticSize=l;
}}}else{if(t){m.itemSpanHeight=j?l:"0px";
m.itemSpanSelectedHeight=j?"0px":l;
if(u){m.itemPartsStaticSize=p;
}}}},_requestItemsHoverImages:function(){var h=this._itemData;
for(var g=0,j=h.length;
g<j;
g++){var d=h[g];
var f=d.hoveredImageUrl;
if(f!=d.selectedImageUrl){this._requestImage(f);
var e=d.hoveredSelectedImageUrl;
if(e!=f){this._requestImage(e);
}}}},_requestImage:function(d){var e=document.createElement("img");
e.setAttribute("src",d);
e.setAttribute("alt","");
e.setAttribute("class","rrtHiddenImages");
this.get_element().appendChild(e);
},_getItem:function(d){for(var e=0;
e<3&&d!==this._ulWrapper;
e++,d=d.parentNode){if("li"==d.tagName.toLowerCase()){return d;
}}return null;
},_getItemA:function(e){var d=e.getElementsByTagName("a");
if(d&&d.length>0){return d[0];
}return null;
},_getItemSpan:function(d){var e=d.getElementsByTagName("span");
if(e&&e.length>0){return e[0];
}return null;
},_getItemData:function(f){var g=this._itemData;
for(var e=0,h=g.length;
e<h;
e++){var d=g[e];
if(d.itemElement===f){return d;
}}},_getItemValue:function(e,d){var f=this._getItemData(e).value;
if(a.RatingPrecision.Item!=this._precision){f-=1;
f+=this._getFraction(e,d);
}if(!isNaN(f)){return f;
}return 0;
},_getItemByValue:function(h){h=Math.ceil(h);
var f=this._itemData;
for(var e=0,g=f.length;
e<g;
e++){var d=f[e];
if(d.value===h){return d.itemElement;
}}},_getItemIndexByValue:function(h){h=Math.ceil(h);
var f=this._itemData;
for(var e=0,g=f.length;
e<g;
e++){var d=f[e];
if(d.value===h){return d.index;
}}},_getItemIndex:function(e){var d=this._getItemData(e).index;
if(!isNaN(d)){return d;
}return -1;
},_getFraction:function(f,d){if(!f){return;
}var e=0;
var l=(a.Orientation.Horizontal==this._orientation?"width":"height");
var g=$telerik.getSize(this._getItemA(f))[l];
var h=this._overPartItem;
var i=this._overPartItemComplement;
if(d&&h&&i){var k=$telerik.getSize(h)[l];
var j=$telerik.getSize(i)[l];
e=Math.max(k,j);
if(0==e&&Sys.UI.DomElement.containsCssClass(f,this._hoveredItemCssClass)){return 1;
}}else{e=$telerik.getSize(this._getItemSpan(f))[l];
if(this._isDirectionReversed){e=g-e;
}}return this._calculateFraction(e,g);
},_calculateFraction:function(d,e){return c(d/e);
},_markContinuousHovered:function(d){if(this._selectionMode!=a.RatingSelectionMode.Continuous){return;
}var g=this._items;
for(var e=0,h=g.length;
e<h;
e++){var f=g[e];
if(d===f){break;
}this._markItemHovered(f);
}},_markItemHovered:function(g){Sys.UI.DomElement.addCssClass(g,this._hoveredItemCssClass);
var f=this._getItemData(g);
var i=f.itemSpan;
if(i&&i.hoveredUrl){var h=this._getItemSpan(g);
h.style.backgroundImage=i.hoveredUrl;
}var e=f.item;
if(e&&e.hoveredUrl){var d=this._getItemA(g);
d.style.backgroundImage=e.hoveredUrl;
}},_clearOverState:function(d){var g=(a.RatingSelectionMode.Continuous==this._selectionMode);
var j=this._items;
var e=d?this._getItemIndex(d):null;
for(var f=(j.length-1);
f>=0;
f--){var h=j[f];
if(g&&e!=null&&(e>this._getItemIndex(h))){return;
}this._clearItemOverState(h);
}},_clearItemOverState:function(g){Sys.UI.DomElement.removeCssClass(g,this._hoveredItemCssClass);
var f=this._getItemData(g);
var i=f.itemSpan;
if(i&&i.url){var h=this._getItemSpan(g);
h.style.backgroundImage=i.url;
}var e=f.item;
if(e&&e.url){var d=this._getItemA(g);
d.style.backgroundImage=e.url;
}},_markContinuousSelected:function(d){var g=this._items;
var j=g.itemSpanSelectedWidth;
var h=g.itemSpanSelectedHeight;
this._markItemSelected(d,j,h);
if(a.RatingSelectionMode.Continuous!=this._selectionMode){return;
}for(var e=0,k=g.length;
e<k;
e++){var f=g[e];
if(d===f){break;
}this._markItemSelected(f,j,h);
}},_markItemSelected:function(d,f,e){Sys.UI.DomElement.addCssClass(d,this._selectedItemCssClass);
this._setItemSize(d,f,e);
},_clearSelection:function(n){var e=(a.RatingSelectionMode.Continuous==this._selectionMode);
var h=this._items;
var k=h.itemSpanWidth;
var j=h.itemSpanHeight;
var m=this._getItemIndexByValue(n);
var l=this._getItemIndexByValue(this._value);
for(var d=l;
d>=0;
d--){var f=h[d];
if(l==d){this._clearPart(f);
}var g=this._getItemIndex(f);
if(m!=null&&((e&&m>g)||(m==g))){return;
}this._clearItemSelectedState(f,k,j);
}},_clearItemSelectedState:function(d,f,e){Sys.UI.DomElement.removeCssClass(d,this._selectedItemCssClass);
this._setItemSize(d,f,e);
},_setItemSize:function(d,f,e){var g=this._getItemSpan(d);
if(f){g.style.width=f;
}if(e){g.style.height=e;
}},_clearPart:function(d,e){var g=this._getItemSpan(d);
if(!g){return;
}var f=e?(e.toString()+"px"):"";
g.style[a.Orientation.Horizontal==this._orientation?"width":"height"]=f;
},_updateHoveredItem:function(h){this._mouseOut(h,true);
var j=this._hoveredItem;
var p=this._overPartItem;
var q=this._overPartItemComplement;
if(!j||!p||!q){return;
}var n=$telerik.getDocumentRelativeCursorPosition(h)[this._locationProperty];
var v=n-this._ulLocation;
v=Math.min(this._maxMousePosition,Math.max(0,v));
v%=this._itemOuterSize;
v-=this._positionOffset;
this._clearItemOverState(j);
var o=this._getOverPartsSize(v,j);
var u=o.partSize;
var s=o.partComplementSize;
var w=this._sizeProperty;
var f=parseInt(p.style[w],10);
if(isNaN(f)||f<1){p.style[w]="1px";
}var d=parseInt(q.style[w],10);
if(isNaN(f)||d<1){q.style[w]="1px";
}var i=(a.Orientation.Horizontal==this._orientation);
if(this._isDirectionReversed){var m=this._marginProperty;
var l=this._itemSize;
var x=this._spanSize;
var t=l-u-(i?0:x);
p.style[m]=t.toString()+"px";
var r=l-s-(i?0:(x+t+u));
q.style[m]=r.toString()+"px";
}else{if(!i){p.style.marginTop=(-s).toString()+"px";
}}p.style[w]=u.toString()+"px";
q.style[w]=s.toString()+"px";
this._updateHoveredItemPartsImages(j);
if(this._enableToolTips){var g=this._getItemData(j);
if(!g.tooltip){var k=this._getItemA(j);
k.title=this._getItemValue(j,true);
}}},_updateHoveredItemPartsImages:function(g){var e=this._isDirectionReversed?"right bottom":"left top";
var f=this._getItemData(g);
var j=f.itemSpan;
var i=this._overPartItem.style;
if(j&&j.hoveredUrl){i.backgroundImage=j.hoveredUrl;
i.backgroundPosition=e;
}else{if(i.backgroundPosition){this._clearBackgroundPosition(i);
}}var d=f.item;
var h=this._overPartItemComplement.style;
if(d&&d.hoveredUrl){h.backgroundImage=d.hoveredUrl;
h.backgroundPosition=e;
}else{if(h.backgroundPosition){this._clearBackgroundPosition(h);
}}},_clearBackgroundPosition:function(d){if(d.removeAttribute){d.removeAttribute("backgroundPosition");
}else{d.removeProperty("backgroundPosition");
}},_getOverPartsSize:function(m,i){var g=this.get_renderMode()==a.RenderMode.Lite;
var h=this._isDirectionReversed;
var j=this._itemSize;
var e=this._itemHalfSize;
var n=this._precision;
var f=(a.RatingPrecision.Half==n);
var l=0;
var k=0;
if(((a.RatingPrecision.Exact==n)&&(m<0||m>=j))||(f&&((!h&&m>e)||(h&&m<=e)))){if((!h&&m>=0)||(h&&m<j)){this._markItemHovered(i);
}}else{var p=this._spanSize;
if(h){if(g){var d=j-p;
if(m>d){if(f){k=e;
}else{k=j-m;
}}else{if(f){l=e;
}else{k=p;
l=j-m;
}}}else{if(m>p){k=f?e:(j-m);
if(f&&(p>e)){l=e;
k=(j-p);
}}else{l=f?e:(j-m);
k=j-p;
}}}else{if((m>p)||(f&&(p<e))){l=p;
k=f?e:m;
}else{l=f?e:m;
}}}var o={partSize:((l<0)?0:l),partComplementSize:((k<0)?0:k)};
return o;
},_createPartElements:function(i){var e=this._overPartItem;
var f=this._overPartItemComplement;
if(i){if(!e){e=document.createElement("span");
e.className="rrtPart";
f=document.createElement("span");
f.className="rrtPartComplement";
var g=this._items.itemPartsStaticSize;
if(g){var h=(a.Orientation.Horizontal==this._orientation)?"height":"width";
e.style[h]=g;
f.style[h]=g;
var d="-"+g;
e.style.marginTop=d;
f.style.marginTop=d;
}this._overPartItem=e;
this._overPartItemComplement=f;
}}else{if(e&&f){e.parentNode.removeChild(e);
this._overPartItem=null;
f.parentNode.removeChild(f);
this._overPartItemComplement=null;
}}},_storeStartCoords:function(i){if(i){var e=(a.Orientation.Horizontal==this._orientation);
var f=this._items[0];
var d=this._getItemA(f);
var j=this._ulWrapper;
var g=this._locationProperty=e?"left":"top";
var h=this._sizeProperty=e?"width":"height";
this._marginProperty=e?"marginLeft":"marginTop";
this._ulLocation=$telerik.getLocation(j)[e?"x":"y"]+($telerik.getMarginBox(j)[g]+$telerik.getBorderBox(j)[g]+$telerik.getPaddingBox(j)[g]);
this._itemOuterSize=$telerik.getOuterSize(f)[h];
this._itemSize=$telerik.getSize(d)[h];
this._itemHalfSize=parseFloat(this._itemSize/2,10);
this._positionOffset=$telerik.getMarginBox(d)[g]+$telerik.getBorderBox(d)[g];
this._maxMousePosition=(this._itemOuterSize*this._itemCount)-1;
}else{this._locationProperty=null;
this._sizeProperty=null;
this._marginProperty=null;
this._ulLocation=null;
this._itemOuterSize=null;
this._itemSize=null;
this._itemHalfSize=null;
this._positionOffset=null;
this._maxMousePosition=null;
}},_attachDocumentHandlers:function(d){if(true==d){this._documentMouseMoveDelegate=Function.createDelegate(this,this._updateHoveredItem);
$telerik.addExternalHandler(document,"mousemove",this._documentMouseMoveDelegate);
}else{if(this._documentMouseMoveDelegate){$telerik.removeExternalHandler(document,"mousemove",this._documentMouseMoveDelegate);
this._documentMouseMoveDelegate=null;
}}},_getFractionSize:function(l,t){var o=this._overPartItem;
var p=this._overPartItemComplement;
if(!(o&&p)&&typeof(t)=="undefined"){return 0;
}var j=this.get_renderMode()==a.RenderMode.Lite;
var k=this._isDirectionReversed&&!j;
var i=(a.Orientation.Horizontal==this._orientation);
var s=(i?"width":"height");
var m=this._items;
var n=$telerik.getSize(this._getItemA(l?l:m[0]))[s];
var f=0;
if(o&&p){var r=$telerik.getSize(o)[s];
var q=$telerik.getSize(p)[s];
f=(r>q)?r:q;
if(0==f&&Sys.UI.DomElement.containsCssClass(l,this._hoveredItemCssClass)){f=n;
}if(k){f=n-f;
}}else{if(t!=null){var e=t-Math.floor(t);
if(e>0){if(k){e=1-e;
}f=Math.round(n*e);
}else{f=(-1);
}}}var h=(k&&f==n)||(!k&&f==0);
var g=(k&&f==0)||(!k&&f==n);
var d=i?(""!=this._itemWidth):(""!=this._itemHeight);
if((!d&&g)||h){f=(-1);
if(h){this._clearItemSelectedState(l,m.itemSpanWidth,m.itemSpanHeight);
}}f=(f<0)?"":f.toString()+"px";
return f;
},_mouseOver:function(d){var f=this._getItem(d.target||d.srcElement);
if(!f){this._hoveredItem=null;
return;
}var h=this._hoveredItem;
if(h&&h===f){return;
}this._clearOverState(f);
if(this._clearSelectedStateOnHover){this._clearSelection();
}this._markContinuousHovered(f);
if(a.RatingPrecision.Item!=this._precision){this._mouseOverPrecise(f,d);
}else{this._markItemHovered(f);
}if(this._enableToolTips){var g=this._getItemA(f);
var i=this._getItemData(f).tooltip;
g.title=i?i:this._getItemValue(f);
}},_mouseOverPrecise:function(g,d){this._createPartElements(true);
this._hoveredItem=g;
var i=(a.Orientation.Horizontal==this._orientation);
var m=(i?"width":"height");
var h=this._getItemSpan(g);
if(h){this._spanSize=$telerik.getSize(h)[m];
}var k=this._overPartItem;
var l=this._overPartItemComplement;
var j=this._isDirectionReversed;
k.style[m]="0px";
l.style[m]="0px";
if(!i&&!j){l.style.marginTop=(-this._spanSize).toString()+"px";
}var f=this._getItemA(g);
f.appendChild(j?k:l);
f.appendChild(j?l:k);
if(!this._itemOuterSize){this._storeStartCoords(true);
}if(!this._documentMouseMoveDelegate){this._attachDocumentHandlers(true);
}this._updateHoveredItem(d);
},_mouseUp:function(d){var m=this._getItem(d.target||d.srcElement);
if(!m){return;
}var g=(a.RatingPrecision.Item!=this._precision);
var j=this._overPartItem;
var k=this._overPartItemComplement;
if(g&&(!j||!this._overPartItemComplement)){return;
}var i=this._value;
var h=this._getItemValue(m,true);
var l=new a.RatingRatingEventArgs(h);
this.raiseEvent("rating",l);
if(l.get_cancel()){return;
}if(i!=h){this._clearSelection(h);
this._markContinuousSelected(m);
if(g){var o=this._getItemSpan(m);
var p=this._getFractionSize(m,h);
var f=(a.Orientation.Horizontal==this._orientation);
var n=f?"width":"height";
j.style[n]="1px";
k.style[n]="1px";
o.style[n]=p;
this._spanSize=$telerik.getSize(o)[n];
if(!f&&!this._isDirectionReversed){p=(p!="")?("-"+p):"";
k.style.marginTop=p;
}this._updateHoveredItem(d);
}}this._setValue(h);
this.raiseEvent("rated",new a.RatingRatedEventArgs(i));
if(this._autoPostBack){this._raiseServerEvent();
}},_mouseUpTouchDevice:function(g){var p=this._getItem(g.target||g.srcElement);
if(!p){return;
}var q=this._getItemA(p);
var i=this._precision!=a.RatingPrecision.Item;
var l={left:g.rawEvent.pageX,top:g.rawEvent.pageY};
var j=$telerik.getLocation(p);
j={left:j.x,top:j.y};
var d=a.Orientation.Horizontal==this._orientation?"left":"top";
var s=a.Orientation.Horizontal==this._orientation?"width":"height";
var k=$telerik.getSize(p)[s]-2*($telerik.getMarginBox(q)[d]+$telerik.getBorderBox(q)[d]);
var h=0,r=0;
if(i){r=l[d]-j[d];
var f=this._isDirectionReversed?k-r:r;
h=this._calculateFraction(f,k);
r=this._calculateFractionSize(k,r);
}var n=this._value;
var m=this._calculateItemValue(p,h);
var o=new a.RatingRatingEventArgs(m);
this.raiseEvent("rating",o);
if(o.get_cancel()){return;
}if(n!=m){this._clearSelection(m);
this._markContinuousSelected(p);
if(i){var t=this._getItemSpan(p);
t.style[s]=r+"px";
this._spanSize=r;
}}this._setValue(m);
this.raiseEvent("rated",new a.RatingRatedEventArgs(n));
if(this._autoPostBack){this._raiseServerEvent();
}},_calculateItemValue:function(e,d){var f=this._getItemData(e).value;
var g=f-1;
switch(this._precision){case a.RatingPrecision.Item:return f;
case a.RatingPrecision.Half:return d>0.5?f:f-0.5;
case a.RatingPrecision.Exact:return g+d;
default:throw"impossible";
}},_calculateFractionSize:function(e,f){var d=parseInt(e/2,10);
var g=this._isDirectionReversed?[d,0]:[e,d];
switch(this._precision){case a.RatingPrecision.Item:return 0;
case a.RatingPrecision.Half:return f>d?g[0]:g[1];
case a.RatingPrecision.Exact:return f;
default:throw"impossible";
}},_mouseOut:function(d,g){var f=$telerik.isMouseOverElementEx(this._ulWrapper,d);
if(f){if(!g&&a.RatingPrecision.Item!=this._precision){this._hoveredItem=null;
}return $telerik.cancelRawEvent(d);
}this._attachDocumentHandlers(false);
this._createPartElements(false);
this._storeStartCoords(false);
this._spanSize=null;
this._hoveredItem=null;
this._clearOverState();
if(this._clearSelectedStateOnHover){this._synchronizeUIWithValue(this._value);
}},_cancelEvent:function(d){if(!d){return false;
}if(d.preventDefault){d.preventDefault();
}d.returnValue=false;
return false;
},_raiseServerEvent:function(){setTimeout(Function.createDelegate(this,function(){__doPostBack(this._uniqueID);
}),0);
},add_load:function(d){this.get_events().addHandler("load",d);
},remove_load:function(d){this.get_events().removeHandler("load",d);
},add_rating:function(d){this.get_events().addHandler("rating",d);
},remove_rating:function(d){this.get_events().removeHandler("rating",d);
},add_rated:function(d){this.get_events().addHandler("rated",d);
},remove_rated:function(d){this.get_events().removeHandler("rated",d);
},get_itemCount:function(){return this._itemCount;
},get_value:function(){return this._value;
},set_value:function(g){var e=this._value;
var d=this.get_isInitialized();
if(d){g=this._fixValuePrecision(g);
var f=new a.RatingRatingEventArgs(g);
this.raiseEvent("rating",f);
if(f.get_cancel()){return;
}if(g!=e){this._clearSelection(g);
this._synchronizeUIWithValue(g);
}}this._setValue(g);
if(d){this.raiseEvent("rated",new a.RatingRatedEventArgs(e));
if(this._autoPostBack){this._raiseServerEvent();
}}},_setValue:function(d){this._value=d;
this._doubleValue=d.toString();
this.get_element().value=this._doubleValue;
this.updateClientState();
},_synchronizeUIWithValue:function(h,g){var d=this._getItemByValue(h);
if(d){if(!g){this._markContinuousSelected(d);
}if(h!=parseInt(h,10)){var e=this._getItemSpan(d);
var f=this._getFractionSize(d,h);
e.style[a.Orientation.Horizontal==this._orientation?"width":"height"]=f;
}}},_fixValuePrecision:function(e){if(!this._definedItems){var d=this._items;
if(e<0){e=0;
}else{if(e>d.length){e=d.length;
}}}return c(e);
},get_selectionMode:function(){return this._selectionMode;
},set_selectionMode:function(d){this._selectionMode=d;
},get_precision:function(){return this._precision;
},set_precision:function(d){this._precision=d;
},get_orientation:function(){return this._orientation;
},set_orientation:function(d){this._orientation=d;
},get_isDirectionReversed:function(){return this._isDirectionReversed;
},set_isDirectionReversed:function(d){this._isDirectionReversed=d;
},get_enableToolTips:function(){return this._enableToolTips;
},set_enableToolTips:function(d){this._enableToolTips=d;
},get_readOnly:function(){return this._readOnly;
},set_readOnly:function(d){if(this.get_isInitialized()&&d!=this._readOnly){this._enableRatingControl(!d);
}this._readOnly=d;
this.updateClientState();
},get_enabled:function(){return this._enabled;
},set_enabled:function(d){if(this.get_isInitialized()&&d!=this._enabled){this._enableRatingControl(d);
}this._enabled=d;
},get_itemData:function(){return this._itemData;
},set_itemData:function(d){this._itemData=d;
},_enableRatingControl:function(h){var j=this._ulWrapper;
$clearHandlers(j);
this._attachDocumentHandlers(false);
if(h){$addHandlers(j,{mouseover:this._mouseOver,mouseup:this._mouseUp,mouseout:this._mouseOut},this);
}else{this._clearOverState();
if(this._enableToolTips){var e=this.get_value();
var d=this._ulWrapper.getElementsByTagName("a");
for(var f=0,g=d.length;
f<g;
f++){d[f].title=e;
}}}$addHandler(j,"click",this._cancelEvent);
},saveClientState:function(){var g=["readOnly"];
var h={value:this._doubleValue};
for(var d=0,e=g.length;
d<e;
d++){var f=g[d];
h[f]=this["get_"+f]();
}return Sys.Serialization.JavaScriptSerializer.serialize(h);
}};
a.RadRating._preInitialize=function(h,o){var g=$get(h);
if(!g||($telerik.getInvisibleParent(g)!=null)){return;
}var l=g.getElementsByTagName("li");
if(l&&l.length>0){var j=l[0];
var k=a.RadRating._getElementBox(j);
var p=a.RadRating._getElementBox($telerik.getChildrenByTagName(g,"ul")[0]);
var d=$telerik.getChildrenByTagName(j,"a")[0];
var n=$telerik.getOuterSize(d);
n.width+=k.horizontal;
n.height+=k.vertical;
var m=l.length;
var i=(0==o);
var f=p.horizontal+(i?(m*n.width):n.width);
var e=p.vertical+(i?n.height:(m*n.height));
if(parseInt(g.style.width,10)!=f||parseInt(g.style.height,10)!=e){$telerik.setContentSize(g,{width:f,height:e});
}}};
a.RadRating._getElementBox=function(f){var e={horizontal:0,vertical:0};
if(f){var d=$telerik.getBorderBox(f);
var h=$telerik.getPaddingBox(f);
var g=$telerik.getMarginBox(f);
e.horizontal=d.horizontal+h.horizontal+g.horizontal;
e.vertical=d.vertical+h.vertical+g.vertical;
}return e;
};
a.RadRating.registerClass("Telerik.Web.UI.RadRating",a.RadWebControl);
function c(d){return Math.round(d*10)/10;
}})();
