(function(a,d){Type.registerNamespace("Telerik.Web.UI.Dialogs");
var b=Telerik.Web.UI;
var c=b.Dialogs;
c.MobileDialogTitleBar=function(e){c.MobileDialogTitleBar.initializeBase(this,[e]);
this._cssClass="";
this._buttonCssClass="";
this._iconCssClass="";
};
c.MobileDialogTitleBar.prototype={initialize:function(){var e=this;
c.MobileDialogTitleBar.callBaseMethod(e,"initialize");
var f=window.localization;
if(f){e.set_title(f.Title);
}e.attachEventHandlers();
},attachEventHandlers:function(){var g=this;
var f=g.get_okButton();
var e=g.get_cancelButton();
g._okDelegate=Function.createDelegate(g,g._okHandler);
g._cancelDelegate=Function.createDelegate(g,g._cancelHandler);
f.onEvent("click",g._okDelegate);
e.onEvent("click",g._cancelDelegate);
},detachEventHandlers:function(){var g=this;
var f=g.get_okButton();
var e=g.get_cancelButton();
f.offEvent("click",g._okDelegate);
e.offEvent("click",g._cancelDelegate);
g._okDelegate=d;
g._cancelDelegate=d;
},get_okButton:function(){return this._getChildByClass(this._buttonCssClass+"OK");
},get_cancelButton:function(){return this._getChildByClass(this._buttonCssClass+"Cancel");
},get_title:function(){return this._title;
},set_title:function(e){this._title=e;
this._setTitleContent(e);
},dispose:function(){this.detachEventHandlers();
c.MobileDialogTitleBar.callBaseMethod(this,"dispose");
},_okHandler:function(){this.raiseEvent("ok");
},_cancelHandler:function(){this.raiseEvent("cancel");
},_setTitleContent:function(f){var e=a(this.get_element()).find("h6");
e.html(f);
},_getChildByClass:function(e){return a(this.get_element()).find("."+e);
}};
c.MobileDialogTitleBar.registerClass("Telerik.Web.UI.Dialogs.MobileDialogTitleBar",b.RadWebControl);
a.registerControlEvents(c.MobileDialogTitleBar,["cancel","ok"]);
})($telerik.$);
