Type.registerNamespace("Telerik.Web.UI");
$telerik.findDataForm=$find;
$telerik.toDataForm=function(a){return a;
};
(function(a,c){var b=Telerik.Web.UI;
b.RadDataForm=function(d){var e=["command","dataFormCreated","dataFormCreating","dataFormDestroying","setValues","getValues"];
this._initializeEvents(e);
b.RadDataForm.initializeBase(this,[d]);
this._uniqueID=null;
this._virtualItemCount=0;
this._currentPageIndex=0;
this._isItemInserted=false;
this._clientDataSourceID="";
this._clientDataSource=null;
this._clientDataKeyNames=[];
this._View=null;
this._Edit=null;
this._Insert=null;
this._currentDataKeyValue;
};
b.RadDataForm.prototype={initialize:function(){b.RadDataForm.callBaseMethod(this,"initialize");
this.raise_dataFormCreating(new Sys.EventArgs());
this._View=$telerik.findElement(this.get_element(),"View");
this._Edit=$telerik.findElement(this.get_element(),"Edit");
if(this._Edit){this._Edit.style.display="none";
}this._Insert=$telerik.findElement(this.get_element(),"Insert");
if(this._Insert){this._Insert.style.display="none";
}this._initializeAutoDataBind();
this.raise_dataFormCreated(new Sys.EventArgs());
},_initializeAutoDataBind:function(){var d=this;
if(d._clientDataSourceID){d._onCommandDelegate=Function.createDelegate(d,d._onCommand);
d.add_command(this._onCommandDelegate);
d._clientDataSource=$find(d._clientDataSourceID);
if(d._clientDataSource){d._bindClientDataSource();
}else{Sys.Application.add_load(function(){d._clientDataSource=$find(d._clientDataSourceID);
d._bindClientDataSource();
});
}}},_bindClientDataSource:function(){var e=this;
var d=e._clientDataSource;
d.set_allowPaging(true);
if(1!=d.get_pageSize()){d.set_pageSize(1);
}if(e.get_currentPageIndex()!=d.get_currentPageIndex()){d.set_currentPageIndex(e.get_currentPageIndex());
}d.fetch(function(f){var g=f.get_data();
e.set_virtualItemCount(e._clientDataSource._kendoDataSource.total());
e.set_currentPageIndex(e._clientDataSource.get_currentPageIndex());
e.set_dataSource(g);
e.dataBind(true);
});
},_updateClientDataSourceChanges:function(g){var h=this;
var f=h._clientDataSource;
var e=f.get_dataSourceObject().options.autoSync;
f.get_dataSourceObject().options.autoSync=false;
var d;
if(g=="PerformInsert"){d=new Sys.CancelEventArgs();
d.get_commandName=function(){return"PerformInsert";
};
d._dataItem={};
d.get_dataItem=function(){return this["_dataItem"];
};
d.set_dataItem=function(i){this["_dataItem"]=i;
};
this.raise_getValues(d);
if(!d.get_cancel()){f.insert(0,d.get_dataItem());
}}else{if(g=="Update"){d=new Sys.CancelEventArgs();
d.get_commandName=function(){return"Update";
};
d._dataItem={};
d.get_dataItem=function(){return this["_dataItem"];
};
d.set_dataItem=function(i){this["_dataItem"]=i;
};
d._dataKey="";
d.get_dataKey=function(){return this["_dataKey"];
};
d.set_dataKey=function(i){this["_dataKey"]=i;
};
d.set_dataKey(this._currentDataKeyValue);
this.raise_getValues(d);
if(!d.get_cancel()){f.update(d.get_dataItem(),d.get_dataKey());
}}else{if(g=="Delete"&&this._currentDataKeyValue){f.remove(this._currentDataKeyValue);
}}}f.sync();
f.get_dataSourceObject().options.autoSync=e;
},_prepareDataItem:function(g,d){var f={};
for(var e in d){f[g.getColumnByUniqueName(e).get_dataField()]=d[e];
}return f;
},_initializeEvents:function(d){if(d){var h=this;
for(var e=0,f=d.length;
e<f;
e++){var g=d[e];
h["add_"+g]=(function(i){return function(j){this.get_events().addHandler(i,j);
};
}(g));
h["remove_"+g]=(function(i){return function(j){this.get_events().removeHandler(i,j);
};
}(g));
h["raise_"+g]=(function(i){return function(j){this.raiseEvent(i,j);
};
}(g));
}}},_onCommand:function(f,d){var e=d.get_commandName();
if(!d.get_cancel()){if(e=="PerformInsert"||e=="Update"||e=="Delete"){this._updateClientDataSourceChanges(e);
}if(e=="InitInsert"){this._Insert.style.display="";
this._View.style.display="none";
}else{if(e=="CancelInsert"||e=="PerformInsert"){this._Insert.style.display="none";
this._View.style.display="";
}else{if(e=="Edit"){this._Edit.style.display="";
this._View.style.display="none";
}else{if(e=="Cancel"||e=="Update"){this._Edit.style.display="none";
this._View.style.display="";
}}}}this._bindClientDataSource();
d.set_cancel(true);
}},dataBind:function(d){var e=this._dataSource[0];
if(this._clientDataKeyNames.length>0){this._currentDataKeyValue=(this._dataSource[0])[this._clientDataKeyNames[0]];
}this.raise_setValues(e);
},get_dataSource:function(){return this._dataSource;
},set_dataSource:function(d){this._dataSource=d;
},get_clientDataSourceID:function(){return this._clientDataSourceID;
},get_currentPageIndex:function(){return this._currentPageIndex;
},set_currentPageIndex:function(d){if(d>=0&&this._currentPageIndex!=d){this._currentPageIndex=d;
this.updateClientState();
}},page:function(d,e){var f=this.get_currentPageIndex();
switch(d){case"Next":f++;
break;
case"Prev":f--;
break;
case"First":f=0;
break;
case"Last":f=(this._virtualItemCount||1)-1;
break;
default:f=d=parseInt(d,10);
break;
}if(isNaN(f)||f<0||(this._clientDataSource&&f>((this._virtualItemCount||1)-1))){return false;
}if(f!==this._currentPageIndex){this.set_currentPageIndex(f);
if(!e){this.fireCommand("Page",d);
}}return true;
},get_virtualItemCount:function(){return this._virtualItemCount;
},set_virtualItemCount:function(d){if(d>=0&&d!==this._virtualItemCount){this._virtualItemCount=+d;
this.updateClientState();
}},fireCommand:function(f,e){var d=new Sys.CancelEventArgs();
this._buildEventArgs(d,{commandName:f,commandArgument:e});
this.raise_command(d);
if(d.get_cancel()){return false;
}if(!(this._clientDataSource)){this._executePostBackEvent(String.format("FireCommand:{0}|;{1}|;",f,e));
}},dispose:function(){this.raise_dataFormDestroying(new Sys.EventArgs());
b.RadDataForm.callBaseMethod(this,"dispose");
},rebind:function(){this.fireCommand("Rebind","");
},editItem:function(d){this.fireCommand("Edit",d||null);
},updateItem:function(d){this.fireCommand("Update",d||null);
},deleteItem:function(d){this.fireCommand("Delete",d||null);
},cancelUpdate:function(d){this.fireCommand("Cancel",d||null);
},showInsertItem:function(d){if(typeof(d)=="undefined"||d==""||d==b.RadDataFormInsertItemPosition.None){d=b.RadDataFormInsertItemPosition.LastItem;
}this.fireCommand("InitInsert",d);
},insertItem:function(){this.fireCommand("PerformInsert","");
},cancelInsert:function(){this.fireCommand("CancelInsert","");
},get_uniqueID:function(){return this.UniqueID;
},get_skin:function(){return this.Skin;
},_buildEventArgs:function(d,e){for(var g in e){var f=g;
var h=e[g];
if(f.indexOf("et_")>0){d[f]=h;
continue;
}d["_"+f]=h;
d["get_"+f]=(function(i){return function(){return this["_"+i];
};
}(f));
}return d;
}};
b.RadDataForm.registerClass("Telerik.Web.UI.RadDataForm",b.RadWebControl);
b.RadDataFormInsertItemPosition=function(){};
b.RadDataFormInsertItemPosition.prototype={None:0,FirstItem:1,LastItem:2};
b.RadDataFormInsertItemPosition.registerEnum("Telerik.Web.UI.RadDataFormInsertItemPosition",false);
})($telerik.$);
