(function(){var a=$telerik.$;
var d=Telerik.Web.UI;
var e=d.Scheduler;
var c=d.RadScheduler.prototype;
var b=d.SchedulerAppointment.prototype;
function g(){if(!this._isSchedulerContentRendered()){return;
}this._appLoadContextMenuCallback=Function.createDelegate(this,this._appLoadContextMenus);
Sys.Application.add_load(this._appLoadContextMenuCallback);
this.add_timeSlotContextMenu(i);
this.add_appointmentContextMenu(h);
if($telerik.isTouchDevice){this._addPreventClosing(this.get_appointmentContextMenus());
this._addPreventClosing(this.get_timeSlotContextMenus());
}}function f(){if(!this._isSchedulerContentRendered()){return;
}this.remove_timeSlotContextMenu(i);
this.remove_appointmentContextMenu(h);
this._removeAppointmentContextMenuHandlers();
this._removeTimeSlotContextMenuHandlers();
}function i(k,j){k._showTimeSlotContextMenu(j.get_domEvent(),j.get_targetSlot(),j.get_startSlot(),j.get_endSlot());
}function h(k,j){k._contextMenuAppointment=j.get_appointment();
j.get_appointment().showContextMenu(j.get_domEvent());
}d.RadScheduler._plugins.push({onInitialize:g,onDispose:f});
e.ContextMenuCommands={Edit:"CommandEdit",Delete:"CommandDelete",AddApt:"CommandAddAppointment",AddAptRecurring:"CommandAddRecurringAppointment",ShowFullTime:"CommandShow24Hours",GoToToday:"CommandGoToToday"};
c._appLoadContextMenus=function(){Sys.Application.remove_load(this._appLoadContextMenuCallback);
this._addAppointmentContextMenuHandlers();
this._addTimeSlotContextMenuHandlers();
};
c._addTimeSlotContextMenuHandlers=function(){this._timeSlotContextMenuHandlersAdded=true;
this._timeSlotContextMenuItemClickingDelegate=Function.createDelegate(this,this._timeSlotContextMenuItemClickingHandler);
this._timeSlotContextMenuItemClickedDelegate=Function.createDelegate(this,this._timeSlotContextMenuItemClickedHandler);
var k=this.get_timeSlotContextMenus();
for(var l=0;
l<k.length;
l++){var j=k[l];
if(j){j.add_itemClicking(this._timeSlotContextMenuItemClickingDelegate);
j.add_itemClicked(this._timeSlotContextMenuItemClickedDelegate);
}}};
c._timeSlotContextMenuItemClickingHandler=function(p,j){this._preventCtxMenuClosing=false;
var l=j.get_item();
var m=l.get_value();
var k=a.raiseCancellableControlEvent(this,"timeSlotContextMenuItemClicking",{slot:this._contextMenuTimeSlot,startSlot:this._contextMenuStartTimeSlot,endSlot:this._contextMenuEndTimeSlot,item:l});
j.set_cancel(k);
if(k){return;
}if(m===e.ContextMenuCommands.AddApt||m===e.ContextMenuCommands.AddAptRecurring){var o=this._raiseAppointmentInsertingFromContextMenu();
if(o){return;
}}if(this.get_shouldPostbackOnTimeSlotContextMenuItemClick()&&!this._renderingManager){this._handleServerSideTimeSlotContextMenuItemClick(l);
}else{var n=this._getTimeSlotMenuItemClickHandlers()[m];
if(n){n();
}}};
c._raiseAppointmentInsertingFromContextMenu=function(){var k=this._contextMenuTimeSlot;
var j=new d.SchedulerAppointmentInsertingEventArgs(k.get_startTime(),k.get_isAllDay(),k);
this._raiseAppointmentInserting(j);
return j.get_cancel();
};
c._getTimeSlotMenuItemClickHandlers=function(){var j=this;
if(!this._timeSlotClickHandlers){this._timeSlotClickHandlers={};
this._timeSlotClickHandlers[e.ContextMenuCommands.AddApt]=function(){var l=j.get_selectedSlots();
var m;
var k;
if(l.length>0){m=l[0];
k=l[l.length-1];
}if(m&&k){j.showInlineInsertForm(m,k);
}else{j.showInlineInsertForm(j._contextMenuTimeSlot);
}};
this._timeSlotClickHandlers[e.ContextMenuCommands.AddAptRecurring]=function(){var m=(j.get_selectedSlots().length>0)?j.get_selectedSlots()[0]:j._contextMenuTimeSlot;
var l=j.get_durationOfSelectedArea();
var k;
if(l){k=j._createAppointmentFromTimeSlotAndDuration(m,l);
}else{k=j._createAppointmentFromTimeSlot(m);
}if(j._renderingManager){k.set_recurrenceState(d.RecurrenceState.Master);
k.set_recurrenceRule(j._createDefaultRecurrenceRule(k));
}j._showAdvancedInsertForm(k,true,m);
};
this._timeSlotClickHandlers[e.ContextMenuCommands.ShowFullTime]=function(){if(j._renderingManager){j.set_showFullTime(!j.get_showFullTime());
}else{j.postback({Command:"SwitchFullTime"});
}};
this._timeSlotClickHandlers[e.ContextMenuCommands.GoToToday]=function(){var k={stopPropagation:function(){},preventDefault:function(){}};
j._onTodayClick(k);
};
}return this._timeSlotClickHandlers;
};
c._createDefaultRecurrenceRule=function(j){var m=[d.RecurrenceDay.Sunday,d.RecurrenceDay.Monday,d.RecurrenceDay.Tuesday,d.RecurrenceDay.Wednesday,d.RecurrenceDay.Thursday,d.RecurrenceDay.Friday,d.RecurrenceDay.Saturday];
var k=new d.RecurrencePattern();
k.set_frequency(d.RecurrenceFrequency.Weekly);
k.set_interval(1);
k.set_daysOfWeekMask(m[j.get_start().getDay()]);
var l=new d.RecurrenceRange();
l.set_start(j.get_start());
l.set_eventDuration(j.get_duration());
return d.RecurrenceRule.fromPatternAndRange(k,l).toString();
};
c._handleServerSideTimeSlotContextMenuItemClick=function(j){var m=this;
var q=this._contextMenuTimeSlot.get_index();
var k=q;
var n=m.get_selectedSlots().length;
if(n>0){q=m.get_selectedSlots()[0].get_index();
k=m.get_selectedSlots()[n-1].get_index();
}var p=this._contextMenuTimeSlot.get_domElement().offsetWidth;
var o=this._contextMenuTimeSlot.get_domElement().offsetHeight;
var l={command:"ContextMenuTimeSlotCommand",contextMenuCommandName:j.get_value(),contextMenuID:j.get_menu().get_id(),menuItemIndex:j._getHierarchicalIndex(),appointmentID:-1,targetSlotIndex:q,lastSlotIndex:k,slotWidth:p,slotHeight:o};
this.postback(l);
};
c._timeSlotContextMenuItemClickedHandler=function(l,j){var k=j.get_item();
a.raiseControlEvent(this,"timeSlotContextMenuItemClicked",{slot:this._contextMenuTimeSlot,startSlot:this._contextMenuStartTimeSlot,endSlot:this._contextMenuEndTimeSlot,item:k});
};
c._addAppointmentContextMenuHandlers=function(){this._contextMenuHandlersAdded=true;
this._appointmentContextMenuItemClickingDelegate=Function.createDelegate(this,this._appointmentContextMenuItemClickingHandler);
this._appointmentContextMenuItemClickedDelegate=Function.createDelegate(this,this._appointmentContextMenuItemClickedHandler);
var k=this.get_appointmentContextMenus();
for(var l=0;
l<k.length;
l++){var j=k[l];
if(j){j.add_itemClicking(this._appointmentContextMenuItemClickingDelegate);
j.add_itemClicked(this._appointmentContextMenuItemClickedDelegate);
}}};
c._appointmentContextMenuItemClickingHandler=function(p,k){this._preventCtxMenuClosing=false;
var m=k.get_item(),o=m.get_value(),n=this._contextMenuAppointment,j=this.getAppointmentDomElement(k._targetElement);
var l=a.raiseCancellableControlEvent(this,"appointmentContextMenuItemClicking",{appointment:n,item:m});
k.set_cancel(l);
if(l){return;
}if(this.get_shouldPostbackOnAppointmentContextMenuItemClick()&&!this._renderingManager){if(o==e.ContextMenuCommands.Edit){this._handleServerSideContextMenuEdit(n,m);
}else{if(o==e.ContextMenuCommands.Delete){this._handleServerSideContextMenuDelete(n,m);
}else{this._handleServerSideContextMenuItemClick(n,m);
}}return;
}if(o==e.ContextMenuCommands.Edit){this.editAppointmentWithConfirmation(n,j);
}else{if(o==e.ContextMenuCommands.Delete){this.deleteAppointmentWithConfirmation(n);
}}};
c._handleServerSideContextMenuItemClick=function(j,k){var l={command:"ContextMenuAppointmentCommand",contextMenuCommandName:k.get_value(),contextMenuID:k.get_menu().get_id(),menuItemIndex:k._getHierarchicalIndex(),appointmentID:j._internalID};
this.postback(l);
};
c._handleServerSideContextMenuEdit=function(j,l){if(!j){return;
}var k={OnConfirm:this._onContextMenuEditDialogCallback,Scheduler:this,Appointment:j,CallbackIsCalledFromDialog:true,ContextMenuID:l.get_menu().get_id(),MenuItemIndex:l._getHierarchicalIndex()};
this._showEditConfirmationDialog(k);
};
c._onContextMenuEditDialogCallback=function(l,j){if(j.CallbackIsCalledFromDialog){var k=new d.SchedulerRecurrenceActionDialogClosedEventArgs(j.Appointment,d.RecurrenceAction.Edit,l);
j.Scheduler._raiseRecurrenceActionDialogClosed(k);
}var m={command:"ContextMenuEdit",contextMenuID:j.ContextMenuID,menuItemIndex:j.MenuItemIndex,appointmentID:j.Appointment._internalID,editSeries:l};
j.Scheduler.postback(m);
};
c._handleServerSideContextMenuDelete=function(j,l){if(!j){return;
}var k={OnConfirm:this._onContextMenuDeleteDialogCallback,Scheduler:this,Appointment:j,CallbackIsCalledFromDialog:true,ContextMenuID:l.get_menu().get_id(),MenuItemIndex:l._getHierarchicalIndex()};
this._showDeleteConfirmationDialog(k);
};
c._onContextMenuDeleteDialogCallback=function(l,j){if(j.CallbackIsCalledFromDialog){var k=new d.SchedulerRecurrenceActionDialogClosedEventArgs(j.Appointment,d.RecurrenceAction.Delete,l);
j.Scheduler._raiseRecurrenceActionDialogClosed(k);
}var m={command:"ContextMenuDelete",contextMenuID:j.ContextMenuID,menuItemIndex:j.MenuItemIndex,appointmentID:j.Appointment._internalID,editSeries:l};
j.Scheduler.postback(m);
};
c._appointmentContextMenuItemClickedHandler=function(l,j){var k=j.get_item();
a.raiseControlEvent(this,"appointmentContextMenuItemClicked",{appointment:this._contextMenuAppointment,item:k});
};
c._removeAppointmentContextMenuHandlers=function(){if(!this._contextMenuHandlersAdded){return;
}var k=this.get_appointmentContextMenus();
for(var l=0;
l<k.length;
l++){var j=k[l];
if(j){j.remove_itemClicking(this._appointmentContextMenuItemClickingDelegate);
j.remove_itemClicked(this._appointmentContextMenuItemClickedDelegate);
}}};
c._removeTimeSlotContextMenuHandlers=function(){if(!this._timeSlotContextMenuHandlersAdded){return;
}var k=this.get_timeSlotContextMenus();
for(var l=0;
l<k.length;
l++){var j=k[l];
if(j){j.remove_itemClicking(this._timeSlotContextMenuItemClickingDelegate);
j.remove_itemClicked(this._timeSlotContextMenuItemClickedDelegate);
}}};
c._showTimeSlotContextMenu=function(k,m,n,l){this._contextMenuTimeSlot=m;
this._contextMenuStartTimeSlot=n;
this._contextMenuEndTimeSlot=l;
var j=this._getTimeSlotContextMenu();
if(j){this._filterTimeSlotContextMenu(j);
j.show(k);
}};
c._filterTimeSlotContextMenu=function(j){if(!this._renderingManager){return;
}var n=this.get_selectedView()==d.SchedulerViewType.TimelineView;
var l=this.get_selectedView()==d.SchedulerViewType.MonthView;
var m=j.findItemByValue(e.ContextMenuCommands.ShowFullTime);
if(m){if(n||l){m.hide();
}else{m.show();
var k=this.get_localization();
m.set_text(this.get_showFullTime()?k.ShowBusinessHours:k.Show24Hours);
}}};
c._getTimeSlotContextMenu=function(){var j=this.get_timeSlotContextMenuIDs();
if(j.length==0){return null;
}return $find(this._resolveContextMenuID(j[0]));
};
c._resolveContextMenuID=function(j){return String.format("{0}_{1}",this.get_id(),j);
};
c.get_appointmentContextMenus=function(){if(!this._appointmentContextMenus){this._appointmentContextMenus=[];
var j=this.get_appointmentContextMenuIDs();
for(var k=0;
k<j.length;
k++){Array.add(this._appointmentContextMenus,$find(this._resolveContextMenuID(j[k])));
}}return this._appointmentContextMenus;
};
c.get_timeSlotContextMenus=function(){if(!this._timeSlotContextMenus){this._timeSlotContextMenus=[];
var j=this.get_timeSlotContextMenuIDs();
for(var k=0;
k<j.length;
k++){Array.add(this._timeSlotContextMenus,$find(this._resolveContextMenuID(j[k])));
}}return this._timeSlotContextMenus;
};
b.showContextMenu=function(k){var j=this.get_contextMenu();
if(j){j.show(k);
}};
b.get_contextMenu=function(){if(!this._contextMenu){var k=this.get_owner();
var l=k.get_appointmentContextMenuIDs();
if(l.length==0){return null;
}var j=this.get_contextMenuID()||l[0];
this._contextMenu=$find(k._resolveContextMenuID(j));
}return this._contextMenu;
};
})();
