Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.PasswordStrengthChecker=function(a){Telerik.Web.UI.PasswordStrengthChecker.initializeBase(this,[a]);
};
Telerik.Web.UI.PasswordStrengthChecker.prototype={initialize:function(){Telerik.Web.UI.PasswordStrengthChecker.callBaseMethod(this,"initialize");
},dispose:function(){},_getPasswordStrength:function(e,p){var m=e;
var n="";
var l=0;
var s=p.CalculationWeightings.split(";");
var b=parseInt(s[0],10);
var c=parseInt(s[1],10);
var a=parseInt(s[2],10);
var d=parseInt(s[3],10);
var o=m.length/p.PreferredPasswordLength;
if(o>1){o=1;
}var f=(o*b);
l+=f;
if(o<1){n=String.format("Remaining characters",p.PreferredPasswordLength-m.length);
}var i;
if(p.MinimumNumericCharacters>0){var h=new RegExp("[0-9]","g");
i=this._getRegexCount(h,m);
if(i>=p.MinimumNumericCharacters){l+=c;
}if(i<p.MinimumNumericCharacters){if(n!=""){n+=", ";
}n+=String.format("Remaining numbers",p.MinimumNumericCharacters-i);
}}else{l+=(o*c);
}if(p.RequiresUpperAndLowerCaseCharacters==true||(typeof(p.RequiresUpperAndLowerCaseCharacters)=="string"&&Boolean.parse(p.RequiresUpperAndLowerCaseCharacters)==true)){var g=new RegExp("[a-z]","g");
var r=new RegExp("[A-Z]","g");
var j=this._getRegexCount(g,m);
var k=this._getRegexCount(r,m);
if(j>0||k>0){if(j>=p.MinLowerCaseChars&&k>=p.MinUpperCaseChars){l+=a;
}else{if(p.MinLowerCaseChars>0&&(p.MinLowerCaseChars-j)>0){if(n!=""){n+=", ";
}n+=String.format("Remaining lower case",p.MinLowerCaseChars-j);
}if(p.MinUpperCaseChars>0&&(p.MinUpperCaseChars-k)>0){if(n!=""){n+=", ";
}n+=String.format("Remaining upper case",p.MinUpperCaseChars-k);
}}}else{if(n!=""){n+=", ";
}n+="Mixed case characters";
}}else{l+=(o*a);
}if(p.MinimumSymbolCharacters>0){var q=new RegExp("[^a-zA-Z0-9\x20]","g");
i=this._getRegexCount(q,m);
if(i>=p.MinimumSymbolCharacters){l+=d;
}if(i<p.MinimumSymbolCharacters){if(n!=""){n+=", ";
}n+=String.format("Remaining symbols",p.MinimumSymbolCharacters-i);
}}else{l+=(o*d);
}return l;
},showStrength:function(e,a,h){var g=this._getPasswordStrength(a.value,h);
var b=new Telerik.Web.UI.PasswordStrengthCalculatingEventArgs(a.value,g,"");
e.raise_passwordStrengthCalculating(b);
var c=null;
if(b._strengthScore>0&&b._strengthScore<=100){c=Math.floor(b._strengthScore/25);
}var d="";
if(b._indicatorText){d=b._indicatorText;
}else{if(h._IndicatorWords==undefined){h._IndicatorWords=h.TextStrengthDescriptions.split(";");
while(h._IndicatorWords.length<5){h._IndicatorWords[h._IndicatorWords.length]="";
}}if(c!=null){d=h._IndicatorWords[c];
}}if(h._IndicatorStyles==undefined){h._IndicatorStyles=h.TextStrengthDescriptionStyles.split(";");
}var f=null;
if(h.IndicatorElementID==""){if(e.get_element){f=$get(e.get_element().id+"_passwordStrengthIndicator");
}else{f=$get(a.id+"_passwordStrengthIndicator");
}}else{f=$get(h.IndicatorElementID);
}if(f){f.innerHTML=d;
if(c!=null){f.className=h.IndicatorElementBaseStyle+" "+h._IndicatorStyles[c+1];
}else{f.className=h.IndicatorElementBaseStyle+" "+h._IndicatorStyles[0];
}}},_getRegexCount:function(b,d){var a=0;
if(d!=null&&d!=""){var c=d.match(b);
if(c!=null){a=c.length;
}}return a;
}};
Telerik.Web.UI.PasswordStrengthChecker.registerClass("Telerik.Web.UI.PasswordStrengthChecker",Telerik.Web.UI.RadWebControl);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadInputControl=function(a){Telerik.Web.UI.RadInputControl.initializeBase(this,[a]);
this._autoPostBack=false;
this._enabled=true;
this._showButton=false;
this._invalidStyleDuration=100;
this._selectionOnFocus=Telerik.Web.UI.SelectionOnFocus.None;
this._postBackEventReferenceScript="";
this._styles=null;
this._skin=null;
this._enableAriaSupport=false;
this._causesValidation=false;
this._validationGroup="";
this._isEnterPressed=false;
this._isDropped=false;
this._enableOldBoxModel=false;
this._shouldResetWidthInPixels=true;
this._reducedPixelWidthFlag=false;
this._originalTextBoxWidth=null;
this._originalCellPadding=null;
this._originalDisplay=null;
this._onTextBoxKeyUpDelegate=null;
this._onTextBoxKeyPressDelegate=null;
this._onTextBoxBlurDelegate=null;
this._onTextBoxFocusDelegate=null;
this._onTextBoxDragEnterDelegate=null;
this._onTextBoxDragLeaveDelegate=null;
this._onTextBoxDragDropDelegate=null;
this._onTextBoxMouseOutDelegate=null;
this._onTextBoxMouseOverDelegate=null;
this._onTextBoxKeyDownDelegate=null;
this._onTextBoxMouseWheelDelegate=null;
this._onFormResetDelegate=null;
this._emptyMessage="";
this._initialValueAsText=null;
this._originalInitialValueAsText="";
this._validationText="";
this._displayText="";
this._value="";
this._text="";
this._holdsValidValue=true;
this._lastSetTextBoxValue="";
this._onTextBoxMouseUpDelegate=null;
this._focused=false;
this._isRtl=false;
this._nonTableLayout=true;
};
Telerik.Web.UI.RadInputControl.prototype={initialize:function(){Telerik.Web.UI.RadInputControl.OverrideValidatorFunctions();
Telerik.Web.UI.RadInputControl.callBaseMethod(this,"initialize");
this._clientID=this.get_id();
this._wrapperElementID=this.get_id()+"_wrapper";
var a=(!$telerik.quirksMode&&($telerik.isIE6||($telerik.isIE7&&!document.documentMode)||(document.documentMode&&document.documentMode<8)));
this._nonTableLayout=this.get_wrapperElement().className.indexOf("riSingle")>-1;
this._textBoxElement=$get(this._clientID);
this._textBoxElement.RadInputValidationValue=this._validationText;
if(this._initialValueAsText!==null){this._value=this._constructValueFromInitialText(this._initialValueAsText);
this._text=this._constructEditText(this._value);
this._originalInitialValueAsText=this._initialValueAsText;
}this._lastSetTextBoxValue=this._displayText;
this._textBoxElement.RadInputLastSetTextBoxValue=this._displayText;
this._initialValueAsText=this._text;
if(this._nonTableLayout&&a){this._textBoxElement.style.width="100%";
this._enableOldBoxModel=true;
}this._originalTextBoxCssText=this._textBoxElement.style.cssText;
if(this._originalTextBoxCssText.lastIndexOf(";")!=this._originalTextBoxCssText.length-1){this._originalTextBoxCssText+=";";
}var d=this.get_wrapperElement();
if(d.style.display=="none"){this._originalDisplay="";
}else{this._originalDisplay=d.style.display;
}if($telerik.isIE7||$telerik.quirksMode){if(this._originalDisplay=="inline-block"){this._originalDisplay="inline";
d.style.zoom=1;
}else{if(document.documentMode&&document.documentMode>7&&this._originalDisplay=="inline"){this._originalDisplay="inline-block";
}}}if(d.style.display!="none"){d.style.display=this._originalDisplay;
}if($telerik.getCurrentStyle(d,"direction")=="rtl"){var b=this._skin!=""?String.format(" RadInputRTL_{0}",this._skin):"";
d.className+=String.format(" RadInputRTL{0}",b);
this._isRtl=true;
}this.repaint();
this._originalMaxLength=this._textBoxElement.maxLength;
if(this._originalMaxLength==-1){this._originalMaxLength=2147483647;
}this._selectionEnd=0;
this._selectionStart=0;
this._hovered=false;
this._invalid=false;
this._attachEventHandlers();
if(this._focused){this.updateDisplayValue();
var c=this;
setTimeout(function(){c._updateSelectionOnFocus();
},0);
}else{if(($telerik.isFirefox2||$telerik.isSafari)&&this.isEmpty()&&this.get_emptyMessage().length>this._originalMaxLength){this.updateDisplayValue();
}}this.updateCssClass();
this._initializeButtons();
if(this.get_enableAriaSupport()){this._initializeAriaSupport();
}this.updateClientState();
this.raise_load(Sys.EventArgs.Empty);
},dispose:function(){Telerik.Web.UI.RadInputControl.callBaseMethod(this,"dispose");
if(this.Button){if(this._onButtonClickDelegate){window.$removeHandler(this.Button,"click",this._onButtonClickDelegate);
this._onButtonClickDelegate=null;
}}if(this._onTextBoxPasteDelegate){window.$removeHandler(this._textBoxElement,"paste",this._onTextBoxPasteDelegate);
this._onTextBoxPasteDelegate=null;
}if(this._onTextBoxInputDelegate){window.$removeHandler(this._textBoxElement,"input",this._onTextBoxInputDelegate);
this._onTextBoxInputDelegate=null;
}if(this._onTextBoxKeyDownDelegate){window.$removeHandler(this._textBoxElement,"keydown",this._onTextBoxKeyDownDelegate);
this._onTextBoxKeyDownDelegate=null;
}if(this._onTextBoxKeyPressDelegate){window.$removeHandler(this._textBoxElement,"keypress",this._onTextBoxKeyPressDelegate);
this._onTextBoxKeyPressDelegate=null;
}if(this._onTextBoxKeyUpDelegate){window.$removeHandler(this._textBoxElement,"keyup",this._onTextBoxKeyUpDelegate);
this._onTextBoxKeyUpDelegate=null;
}if(this._onTextBoxBlurDelegate){window.$removeHandler(this._textBoxElement,"blur",this._onTextBoxBlurDelegate);
this._onTextBoxBlurDelegate=null;
}if(this._onTextBoxFocusDelegate){window.$removeHandler(this._textBoxElement,"focus",this._onTextBoxFocusDelegate);
this._onTextBoxFocusDelegate=null;
}if(this._onTextBoxDragEnterDelegate){window.$removeHandler(this._textBoxElement,"dragenter",this._onTextBoxDragEnterDelegate);
this._onTextBoxDragEnterDelegate=null;
}if(this._onTextBoxDragLeaveDelegate){if($telerik.isFirefox){window.$removeHandler(this._textBoxElement,"dragexit",this._onTextBoxDragLeaveDelegate);
}else{window.$removeHandler(this._textBoxElement,"dragleave",this._onTextBoxDragLeaveDelegate);
}this._onTextBoxDragLeaveDelegate=null;
}if(this._onTextBoxMouseOutDelegate){window.$removeHandler(this._textBoxElement,"mouseout",this._onTextBoxMouseOutDelegate);
this._onTextBoxMouseOutDelegate=null;
}if(this._onTextBoxMouseOverDelegate){window.$removeHandler(this._textBoxElement,"mouseover",this._onTextBoxMouseOverDelegate);
this._onTextBoxMouseOverDelegate=null;
}if(this._onTextBoxMouseUpDelegate){window.$removeHandler(this._textBoxElement,"mouseup",this._onTextBoxMouseUpDelegate);
this._onTextBoxMouseUpDelegate=null;
}if(this._onFormResetDelegate){if(this._textBoxElement.form){window.$removeHandler(this._textBoxElement.form,"reset",this._onFormResetDelegate);
}this._onFormResetDelegate=null;
}if(!$telerik.isIE){if(this._onTextBoxMouseWheelDelegate){if($telerik.isSafari||$telerik.isOpera){window.$removeHandler(this._textBoxElement,"mousewheel",this._onTextBoxMouseWheelDelegate);
}else{window.$removeHandler(this._textBoxElement,"DOMMouseScroll",this._onTextBoxMouseWheelDelegate);
}this._onTextBoxMouseWheelDelegate=null;
}}else{if(this._onTextBoxMouseWheelDelegate){window.$removeHandler(this._textBoxElement,"mousewheel",this._onTextBoxMouseWheelDelegate);
this._onTextBoxMouseWheelDelegate=null;
}}if(this._onTextBoxDragDropDelegate){if($telerik.isFirefox&&Sys.Browser.version<3.5){window.$removeHandler(this._textBoxElement,"dragdrop",this._onTextBoxDragDropDelegate);
}else{window.$removeHandler(this._textBoxElement,"drop",this._onTextBoxDragDropDelegate);
}this._onTextBoxDragDropDelegate=null;
}if(this._textBoxElement){this._textBoxElement._events=null;
}},clear:function(){this.set_value("");
},disable:function(){this.set_enabled(false);
this._textBoxElement.disabled="disabled";
this.updateCssClass();
this.updateClientState();
this.raise_disable(Sys.EventArgs.Empty);
},enable:function(){this.set_enabled(true);
this._textBoxElement.disabled="";
this.updateCssClass();
this.updateClientState();
this.raise_enable(Sys.EventArgs.Empty);
},focus:function(){if(!this._textBoxElement.disabled){this._textBoxElement.focus();
}},blur:function(){this._textBoxElement.blur();
},isEmpty:function(){return this._validationText=="";
},isNegative:function(){return false;
},isReadOnly:function(){return this._textBoxElement.readOnly||!this._enabled;
},isMultiLine:function(){return this._textBoxElement&&this._textBoxElement.tagName.toUpperCase()=="TEXTAREA";
},updateDisplayValue:function(){if(this._focused){if(!this._holdsValidValue){this._holdsValidValue=true;
}else{this.set_textBoxValue(this.get_editValue());
}}else{if(this._isEmptyMessage()){this.set_textBoxValue(this.get_emptyMessage());
}else{this.set_textBoxValue(this.get_displayValue());
}}},_isEmptyMessage:function(){return this.isEmpty()&&this.get_emptyMessage();
},repaint:function(){if(!this.canRepaint()){this.add_parentShown(this.get_element());
return;
}else{this._clearParentShowHandlers();
}this._updatePercentageHeight();
if(this._shouldResetWidthInPixels){this._resetWidthInPixels();
}if(!this._reducedPixelWidthFlag&&this._enableOldBoxModel){var a=this;
setTimeout(function(){a._reducePixelWidthByPaddings();
},0);
}},updateCssClass:function(b){if(!this._holdsValidValue&&!b){this._textBoxElement.style.cssText=this._originalTextBoxCssText+this.updateCssText(this.get_styles()["InvalidStyle"][0]);
this._textBoxElement.className=this.get_styles()["InvalidStyle"][1];
return;
}var c="";
var a="";
if(this._enabled&&(!this._isEmptyMessage())&&(!this.isNegative())){a=this._originalTextBoxCssText+this.updateCssText(this.get_styles()["EnabledStyle"][0]);
if(!this._compareStyles(this._textBoxElement.style.cssText,a)){this._textBoxElement.style.cssText=a;
}c=this.get_styles()["EnabledStyle"][1];
}if(this._enabled&&(!this._isEmptyMessage())&&this.isNegative()){a=this._originalTextBoxCssText+this.updateCssText(this.get_styles()["NegativeStyle"][0]);
if(!this._compareStyles(this._textBoxElement.style.cssText,a)){this._textBoxElement.style.cssText=a;
}c=this.get_styles()["NegativeStyle"][1];
}if(this._enabled&&this._isEmptyMessage()){a=this._originalTextBoxCssText+this.updateCssText(this.get_styles()["EmptyMessageStyle"][0]);
if(!this._compareStyles(this._textBoxElement.style.cssText,a)){this._textBoxElement.style.cssText=a;
}c=this.get_styles()["EmptyMessageStyle"][1];
}if(this._focused){a=this._originalTextBoxCssText+this.updateCssText(this.get_styles()["FocusedStyle"][0]);
if(!this._compareStyles(this._textBoxElement.style.cssText,a)){this._textBoxElement.style.cssText=a;
}c=this.get_styles()["FocusedStyle"][1];
}if(this._invalid){a=this._originalTextBoxCssText+this.updateCssText(this.get_styles()["InvalidStyle"][0]);
if(!this._compareStyles(this._textBoxElement.style.cssText,a)){this._textBoxElement.style.cssText=a;
}c=this.get_styles()["InvalidStyle"][1];
}if(this._textBoxElement.readOnly&&this._isEmptyMessage()){a=this._originalTextBoxCssText+this.updateCssText(this.get_styles()["EmptyMessageStyle"][0]);
if(!this._compareStyles(this._textBoxElement.style.cssText,a)){this._textBoxElement.style.cssText=a;
}c=this.get_styles()["EmptyMessageStyle"][1];
}else{if(this._textBoxElement.readOnly){a=this._originalTextBoxCssText+this.updateCssText(this.get_styles()["ReadOnlyStyle"][0]);
if(!this._compareStyles(this._textBoxElement.style.cssText,a)){this._textBoxElement.style.cssText=a;
}c=this.get_styles()["ReadOnlyStyle"][1];
}}if(!this._enabled){a=this._originalTextBoxCssText+this.updateCssText(this.get_styles()["DisabledStyle"][0]);
if(!this._compareStyles(this._textBoxElement.style.cssText,a)){this._textBoxElement.style.cssText=a;
}c=this.get_styles()["DisabledStyle"][1];
}if(this._hovered){a=this._originalTextBoxCssText+this.updateCssText(this.get_styles()["HoveredStyle"][0]);
if(!this._compareStyles(this._textBoxElement.style.cssText,a)){this._textBoxElement.style.cssText=a;
}c=c.trim()+" "+this.get_styles()["HoveredStyle"][1].replace("riTextBox","").trim();
}if(c!=""&&!this._compareStyles(this._textBoxElement.className,c)){this._textBoxElement.className=c;
}if(c==""&&this._textBoxElement.className&&this._textBoxElement.className==""){this._textBoxElement.removeAttribute("class");
}},_compareStyles:function(){if(arguments.length>=2){var a=arguments[0].replace(/ /g,"").replace(/;/g,"");
var b=arguments[1].replace(/ /g,"").replace(/;/g,"");
return a===b;
}return false;
},updateCssText:function(f){var e=f.split(";");
var a;
var c="";
for(a=0;
a<e.length;
a++){var d=e[a].split(":");
if(d.length==2){var b=""+d[0].toLowerCase();
if(b!="width"&&b!="height"){c+=e[a]+";";
}}}return c;
},selectText:function(b,a){this._selectionStart=b;
this._selectionEnd=a;
this._applySelection();
},selectAllText:function(){if(this._textBoxElement.value.length>0){this.selectText(0,this._textBoxElement.value.length);
return true;
}return false;
},get_value:function(){return this._value;
},get_valueAsString:function(){if(this._value){return this._value.toString();
}else{return"";
}},_setNewValue:function(a){this._holdsValidValue=this._setHiddenValue(a)||this._holdsValidValue;
this._textBoxElement.RadInputLastSetTextBoxValue=this._textBoxElement.value;
this._triggerDomEvent("change",this._textBoxElement);
if(this._holdsValidValue){this.set_displayValue(this._constructDisplayText(this._value));
this.updateClientState();
var b=this._initialValueAsText;
this._initialValueAsText=this._textBoxElement.value;
this.raise_valueChanged(this.get_editValue(),b);
this.updateCssClass();
}else{this.updateClientState();
}this._initialValueAsText=this.get_editValue();
},set_value:function(b){var a=new Telerik.Web.UI.InputValueChangingEventArgs(b,this._initialValueAsText);
this.raise_valueChanging(a);
if(a.get_cancel()){this.set_textBoxValue(this.get_element().RadInputLastSetTextBoxValue);
}else{b=a.get_newValue();
this._setNewValue(b);
}},get_displayValue:function(){return this._displayText;
},set_displayValue:function(a){this._displayText=a;
this.updateDisplayValue();
},get_editValue:function(){return this._text;
},set_caretPosition:function(a){if(this._textBoxElement.tagName.toLowerCase()=="textarea"&&this._textBoxElement.value.length<a){return;
}this._selectionStart=a;
this._selectionEnd=a;
this._applySelection();
},get_caretPosition:function(){this._calculateSelection();
if(this._selectionStart!=this._selectionEnd){return new Array(this._selectionStart,this._selectionEnd);
}else{if(this._textBoxElement.selectionStart){return this._textBoxElement.selectionStart;
}else{return this._selectionStart;
}}},raisePostBackEvent:function(){eval(this._postBackEventReferenceScript);
},get_wrapperElement:function(){return $get(this._wrapperElementID);
},get_textBoxValue:function(){return this._textBoxElement.value;
},set_textBoxValue:function(a){if(this._textBoxElement.value!=a){this._textBoxElement.value=a;
}this._lastSetTextBoxValue=a;
this._textBoxElement.RadInputLastSetTextBoxValue=a;
},get_autoPostBack:function(){return this._autoPostBack;
},set_autoPostBack:function(a){if(this._autoPostBack!==a){this._autoPostBack=a;
this.raisePropertyChanged("autoPostBack");
}},get_emptyMessage:function(){return this._emptyMessage;
},set_emptyMessage:function(a){if(this._emptyMessage!==a){this._emptyMessage=a;
if(this._textBoxElement){this.updateDisplayValue();
this.updateCssClass();
this.updateClientState();
this.raisePropertyChanged("emptyMessage");
}}},get_selectionOnFocus:function(){return this._selectionOnFocus;
},set_selectionOnFocus:function(a){if(this._selectionOnFocus!==a){this._selectionOnFocus=a;
this.raisePropertyChanged("selectionOnFocus");
}},get_showButton:function(){return this._showButton;
},set_showButton:function(a){if(this._showButton!==a){this._showButton=a;
this.raisePropertyChanged("showButton");
}},get_invalidStyleDuration:function(){return this._invalidStyleDuration;
},set_invalidStyleDuration:function(a){if(this._invalidStyleDuration!==a){this._invalidStyleDuration=a;
this.raisePropertyChanged("invalidStyleDuration");
}},get_enabled:function(){return this._enabled;
},set_enabled:function(a){if(this._enabled!==a){this._enabled=a;
this.updateClientState();
if(this.get_enableAriaSupport()){this._applyAriaStateChange("disabled",!a);
}this.raisePropertyChanged("enabled");
}},get_styles:function(){return this._styles;
},set_styles:function(a){if(this._styles!==a){this._styles=a;
this.raisePropertyChanged("styles");
}},saveClientState:function(a){var d=["enabled","emptyMessage","validationText","valueAsString"];
var b;
var c;
if(a){for(b=0,c=a.length;
b<c;
b++){d[d.length]=a[b];
}}var e={};
for(b=0;
b<d.length;
b++){e[d[b]]=this["get_"+d[b]]();
}this.saveCustomClientStateValues(e);
return Sys.Serialization.JavaScriptSerializer.serialize(e);
},saveCustomClientStateValues:function(a){a.lastSetTextBoxValue=this._lastSetTextBoxValue;
},get_visible:function(){if(this.get_wrapperElement().style.display=="none"){return false;
}else{return true;
}},set_visible:function(a){if(a==true&&this._originalDisplay!=null){this.get_wrapperElement().style.display=this._originalDisplay;
this.repaint();
}else{if(a==false&&this.get_visible()){this._originalDisplay=this.get_wrapperElement().style.display;
this.get_wrapperElement().style.display="none";
}}},get_shouldResetWidthInPixels:function(){return this._shouldResetWidthInPixels;
},set_shouldResetWidthInPixels:function(a){this._shouldResetWidthInPixels=a;
},get_enableOldBoxModel:function(){return this._enableOldBoxModel;
},set_enableOldBoxModel:function(a){this._enableOldBoxModel=a;
},get_enableAriaSupport:function(){return this._enableAriaSupport;
},set_enableAriaSupport:function(a){if(this._enableAriaSupport!=a){this._enableAriaSupport=a;
}},get_causesValidation:function(){return this._causesValidation;
},get_validationGroup:function(){return this._validationGroup;
},_reducePixelWidthByPaddings:function(){if(this._textBoxElement.offsetWidth>0&&this._textBoxElement.parentNode.tagName.toLowerCase()=="span"&&this._textBoxElement.style.width&&(this._nonTableLayout||(this._textBoxElement.parentNode.parentNode.className!="rcInputCell"&&this._textBoxElement.style.width.indexOf("%")==-1&&(!this._originalTextBoxWidth||this._originalTextBoxWidth.indexOf("%")==-1)))){var f=0;
var a=0;
if(document.defaultView&&document.defaultView.getComputedStyle){f=parseInt(document.defaultView.getComputedStyle(this._textBoxElement,null).getPropertyValue("border-left-width"),10)+parseInt(document.defaultView.getComputedStyle(this._textBoxElement,null).getPropertyValue("padding-left"),10)+parseInt(document.defaultView.getComputedStyle(this._textBoxElement,null).getPropertyValue("padding-right"),10)+parseInt(document.defaultView.getComputedStyle(this._textBoxElement,null).getPropertyValue("border-right-width"),10);
a=parseInt(document.defaultView.getComputedStyle(this._textBoxElement,null).getPropertyValue("border-top-width"),10)+parseInt(document.defaultView.getComputedStyle(this._textBoxElement,null).getPropertyValue("padding-top"),10)+parseInt(document.defaultView.getComputedStyle(this._textBoxElement,null).getPropertyValue("padding-bottom"),10)+parseInt(document.defaultView.getComputedStyle(this._textBoxElement,null).getPropertyValue("border-bottom-width"),10);
}else{if(this._textBoxElement.currentStyle){if(document.compatMode&&document.compatMode!="BackCompat"){f=parseInt(this._textBoxElement.currentStyle.borderLeftWidth,10)+parseInt(this._textBoxElement.currentStyle.paddingLeft,10)+parseInt(this._textBoxElement.currentStyle.paddingRight,10)+parseInt(this._textBoxElement.currentStyle.borderRightWidth,10);
a=parseInt(this._textBoxElement.currentStyle.borderTopWidth,10)+parseInt(this._textBoxElement.currentStyle.paddingTop,10)+parseInt(this._textBoxElement.currentStyle.paddingBottom,10)+parseInt(this._textBoxElement.currentStyle.borderBottomWidth,10);
}}}var j=parseInt(this._textBoxElement.style.width,10);
if(this._nonTableLayout&&this._textBoxElement.parentNode.style.width&&this._textBoxElement.parentNode.style.width.indexOf("%")==-1){j=parseInt(this._textBoxElement.parentNode.currentStyle.width,10);
}var k=j-f;
var b=parseInt(this._textBoxElement.offsetHeight,10)-a;
if(f==0||k<=0){return;
}this._textBoxElement.style.width=k+"px";
var e="";
var h=this._originalTextBoxCssText.split(";");
if(h==[]){for(var c=0;
c<h.length;
c++){var g=h[c].split(":");
if(g.length==2){var d=""+g[0].toLowerCase();
if(d!="width"||d!="height"){e+=h[c]+";";
}else{if(d=="width"){e+="width:"+k+"px;";
if(!this._originalTextBoxWidth){this._originalTextBoxWidth=h[c].split(":")[1].trim();
}}else{e+="height:"+k+"px;";
}}}}}else{e+="width:"+k+"px;";
e+="height:"+b+"px;";
}this._originalTextBoxCssText=e;
this._reducedPixelWidthFlag=true;
}},_updatePercentageHeight:function(){var b=$get(this._wrapperElementID);
if(b.style.height.indexOf("%")!=-1&&b.offsetHeight>0){var a=0;
if(this._textBoxElement.currentStyle){a=parseInt(this._textBoxElement.currentStyle.borderTopWidth,10)+parseInt(this._textBoxElement.currentStyle.borderBottomWidth,10)+parseInt(this._textBoxElement.currentStyle.paddingTop,10)+parseInt(this._textBoxElement.currentStyle.paddingBottom,10);
}else{if(window.getComputedStyle){a=parseInt(window.getComputedStyle(this._textBoxElement,null).getPropertyValue("border-top-width"),10)+parseInt(window.getComputedStyle(this._textBoxElement,null).getPropertyValue("border-bottom-width"),10)+parseInt(window.getComputedStyle(this._textBoxElement,null).getPropertyValue("padding-top"),10)+parseInt(window.getComputedStyle(this._textBoxElement,null).getPropertyValue("padding-bottom"),10);
}}this._textBoxElement.style.height="1px";
this._textBoxElement.style.cssText=this._textBoxElement.style.cssText;
this._textBoxElement.style.height=b.offsetHeight-a+"px";
if(this._originalTextBoxCssText.search(/(^|[^-])height/)!=-1){this._originalTextBoxCssText=this._originalTextBoxCssText.replace(/(^|[^-])height(\s*):(\s*)([^;]+);/i,"$1height:"+(b.offsetHeight-a)+"px;");
}else{this._originalTextBoxCssText+="height:"+(b.offsetHeight-a)+"px;";
}}},_resetWidthInPixels:function(){if(($telerik.isIE6||($telerik.isIE7&&!document.documentMode)||(document.documentMode&&document.documentMode<8))&&this._textBoxElement.offsetWidth>0&&(this._textBoxElement.parentNode.tagName.toLowerCase()=="td"||(this._textBoxElement.parentNode.parentNode.tagName.toLowerCase()=="td"&&this._textBoxElement.parentNode.parentNode.className=="rcInputCell")||(this._textBoxElement.parentNode.tagName.toLowerCase()=="span"&&this._textBoxElement.parentNode.parentNode.className!="rcInputCell"&&(this._textBoxElement.currentStyle.width.indexOf("%")!=-1||(this._originalTextBoxWidth&&this._originalTextBoxWidth.indexOf("%")!=-1))))){var g=this._textBoxElement.value;
var d;
var h;
var c="";
if(g!=""){this._textBoxElement.value="";
}if(this._originalCellPadding&&this._textBoxElement.parentNode.tagName.toLowerCase()=="td"){this._textBoxElement.parentNode.style.paddingRight=this._originalCellPadding;
}else{if(this._originalCellPadding&&this._textBoxElement.parentNode.parentNode.tagName.toLowerCase()=="td"&&this._textBoxElement.parentNode.parentNode.className=="rcInputCell"){this._textBoxElement.parentNode.parentNode.style.paddingRight=this._originalCellPadding;
}}if(this._originalTextBoxWidth){this._textBoxElement.style.width=this._originalTextBoxWidth;
}else{if(g!=""){this._textBoxElement.style.cssText=this._textBoxElement.style.cssText;
}}d=parseInt(this._textBoxElement.currentStyle.paddingLeft,10)+parseInt(this._textBoxElement.currentStyle.paddingRight,10);
h=this._textBoxElement.clientWidth-d;
if(h>0){this._textBoxElement.style.width=h+"px";
if(this._textBoxElement.parentNode.tagName.toLowerCase()=="td"){if(!this._originalCellPadding){this._originalCellPadding=this._textBoxElement.parentNode.currentStyle.paddingRight;
}this._textBoxElement.parentNode.style.paddingRight="0px";
}else{if(this._textBoxElement.parentNode.parentNode.tagName.toLowerCase()=="td"&&this._textBoxElement.parentNode.parentNode.className=="rcInputCell"){if(!this._originalCellPadding){this._originalCellPadding=this._textBoxElement.parentNode.parentNode.currentStyle.paddingRight;
}this._textBoxElement.parentNode.parentNode.style.paddingRight="0px";
}}var f=this._originalTextBoxCssText.split(";");
for(var a=0;
a<f.length;
a++){var e=f[a].split(":");
if(e.length==2){var b=""+e[0].toLowerCase();
if(b!="width"){c+=f[a]+";";
}else{c+="width:"+h+"px;";
if(!this._originalTextBoxWidth){this._originalTextBoxWidth=f[a].split(":")[1].trim();
}}}}this._originalTextBoxCssText=c;
}if(g!=""){this._textBoxElement.value=g;
}}},_initializeButtons:function(){this._onButtonClickDelegate=Function.createDelegate(this,this._onButtonClickHandler);
this.Button=null;
var b=$get(this._wrapperElementID);
var a=b.getElementsByTagName("a");
for(var c=0;
c<a.length;
c++){if(a[c].className.indexOf("riButton")!=(-1)){this.Button=a[c];
window.$addHandler(this.Button,"click",this._onButtonClickDelegate);
}}},_initializeAriaSupport:function(){var a=this.get_wrapperElement();
a.setAttribute("role","textbox");
a.setAttribute("aria-atomic","true");
a.setAttribute("aria-disabled",(!this.get_enabled())+"");
if(this.isMultiLine()){a.setAttribute("aria-multiline","true");
}if(this.isReadOnly()){a.setAttribute("aria-readonly","true");
}if(this.Button){this.Button.setAttribute("role","button");
this.Button.setAttribute("aria-label","Go");
}},_applyAriaStateChange:function(a,b){var c=$get(this.get_id()+"_wrapper");
if(c){c.setAttribute("aria-"+a,b+"");
}},_attachEventHandlers:function(){this._onTextBoxKeyUpDelegate=Function.createDelegate(this,this._onTextBoxKeyUpHandler);
this._onTextBoxKeyPressDelegate=Function.createDelegate(this,this._onTextBoxKeyPressHandler);
this._onTextBoxBlurDelegate=Function.createDelegate(this,this._onTextBoxBlurHandler);
this._onTextBoxFocusDelegate=Function.createDelegate(this,this._onTextBoxFocusHandler);
this._onTextBoxKeyDownDelegate=Function.createDelegate(this,this._onTextBoxKeyDownHandler);
window.$addHandler(this._textBoxElement,"keydown",this._onTextBoxKeyDownDelegate);
window.$addHandler(this._textBoxElement,"keypress",this._onTextBoxKeyPressDelegate);
window.$addHandler(this._textBoxElement,"keyup",this._onTextBoxKeyUpDelegate);
window.$addHandler(this._textBoxElement,"blur",this._onTextBoxBlurDelegate);
window.$addHandler(this._textBoxElement,"focus",this._onTextBoxFocusDelegate);
if($telerik.isIE||$telerik.isSafari){this._onTextBoxPasteDelegate=Function.createDelegate(this,this._onTextBoxPasteHandler);
window.$addHandler(this._textBoxElement,"paste",this._onTextBoxPasteDelegate);
}else{this._onTextBoxInputDelegate=Function.createDelegate(this,this._onTextBoxInputHandler);
window.$addHandler(this._textBoxElement,"input",this._onTextBoxInputDelegate);
}if(this._textBoxElement&&this._textBoxElement.form){this._onFormResetDelegate=Function.createDelegate(this,this._onFormResetHandler);
window.$addHandler(this._textBoxElement.form,"reset",this._onFormResetDelegate);
}this._attachMouseEventHandlers();
},_onTextBoxPasteHandler:function(c){if(this.isMultiLine()&&this._maxLength>0){var i=this;
if($telerik.isSafari){window.setTimeout(function(){i._textBoxElement.value=i._textBoxElement.value.substr(0,i._maxLength);
},1);
}else{if(document.selection){if(!c){c=window.event;
}var a=true;
var b="";
try{b=window.clipboardData.getData("Text");
}catch(d){a=false;
}if(a&&b!=""){if(c.preventDefault){c.preventDefault();
}var g=document.selection.createRange();
var f=this._maxLength-this._escapeNewLineChars(this._textBoxElement.value,"\r\n").length+this._escapeNewLineChars(g.text,"\r\n").length;
var h=this._escapeNewLineChars(window.clipboardData.getData("Text"),"\r\n").substr(0,f);
if(h.length>0&&h.charAt(h.length-1)=="\r"){h=h.substr(0,h.length-1);
}g.text=h;
}else{window.setTimeout(function(){i._textBoxElement.value=i._textBoxElement.value.substr(0,i._maxLength);
},1);
}}}}},_onTextBoxInputHandler:function(a){if(this.isMultiLine()&&this._maxLength>0&&this._textBoxElement.value.length>this._maxLength){this._textBoxElement.value=this._textBoxElement.value.substr(0,this._maxLength);
}},_attachMouseEventHandlers:function(){if(!$telerik.isIE){this._onTextBoxMouseUpDelegate=Function.createDelegate(this,this._onTextBoxMouseUpHandler);
window.$addHandler(this._textBoxElement,"mouseup",this._onTextBoxMouseUpDelegate);
}this._onTextBoxMouseOutDelegate=Function.createDelegate(this,this._onTextBoxMouseOutHandler);
this._onTextBoxMouseOverDelegate=Function.createDelegate(this,this._onTextBoxMouseOverHandler);
this._onTextBoxMouseWheelDelegate=Function.createDelegate(this,this._onTextBoxMouseWheelHandler);
this._onTextBoxDragEnterDelegate=Function.createDelegate(this,this._onTextBoxDragEnterHandler);
this._onTextBoxDragLeaveDelegate=Function.createDelegate(this,this._onTextBoxDragLeaveHandler);
this._onTextBoxDragDropDelegate=Function.createDelegate(this,this._onTextBoxDragDropHandler);
window.$addHandler(this._textBoxElement,"mouseout",this._onTextBoxMouseOutDelegate);
window.$addHandler(this._textBoxElement,"mouseover",this._onTextBoxMouseOverDelegate);
window.$addHandler(this._textBoxElement,"dragenter",this._onTextBoxDragEnterDelegate);
if($telerik.isFirefox){window.$addHandler(this._textBoxElement,"dragexit",this._onTextBoxDragLeaveDelegate);
}else{window.$addHandler(this._textBoxElement,"dragleave",this._onTextBoxDragLeaveDelegate);
}if($telerik.isFirefox&&Sys.Browser.version<3.5){window.$addHandler(this._textBoxElement,"dragdrop",this._onTextBoxDragDropDelegate);
}else{window.$addHandler(this._textBoxElement,"drop",this._onTextBoxDragDropDelegate);
}if(!$telerik.isIE){if(($telerik.isSafari)||$telerik.isOpera){window.$addHandler(this._textBoxElement,"mousewheel",this._onTextBoxMouseWheelDelegate);
}else{window.$addHandler(this._textBoxElement,"DOMMouseScroll",this._onTextBoxMouseWheelDelegate);
}}else{window.$addHandler(this._textBoxElement,"mousewheel",this._onTextBoxMouseWheelDelegate);
}},_onTextBoxMouseUpHandler:function(a){},_cancelKeyPressEventIfMaxLengthReached:function(b){var f=this._escapeNewLineChars(this._textBoxElement.value,"\r\n");
var d=this._maxLength;
if(d>0&&f.length+(b.charCode==13)>=d&&((b.charCode==13)||this._isNormalChar(b))){var c=false;
if(document.selection){if(document.selection.createRange().text){c=true;
}}else{var a=this.get_caretPosition();
if(a[0]||a[1]){c=true;
}}if(!c){b.stopPropagation();
b.preventDefault();
return false;
}}},_onTextBoxKeyPressHandler:function(a){this._isEnterPressed=false;
var b=new Telerik.Web.UI.InputKeyPressEventArgs(a,a.charCode,String.fromCharCode(a.charCode));
this.raise_keyPress(b);
if(b.get_cancel()){a.stopPropagation();
a.preventDefault();
return false;
}if((a.charCode==13)&&!this.isMultiLine()){var c=this._textBoxElement.value;
this._isEnterPressed=true;
this.set_value(c);
this._isEnterPressed=false;
if(this.get_autoPostBack()){a.stopPropagation();
a.preventDefault();
return false;
}return true;
}if(this.isMultiLine()){return(this._cancelKeyPressEventIfMaxLengthReached(a));
}},_onTextBoxKeyUpHandler:function(a){if(a&&a.keyCode===9){this._updateSelectionOnFocus();
}},_onTextBoxBlurHandler:function(a){this._focused=false;
if(this.isReadOnly()){return;
}var b=this._textBoxElement.value;
if(this._initialValueAsText+""!==b){this.set_value(b);
}else{this.updateDisplayValue();
this.updateClientState();
this.updateCssClass();
}this.raise_blur(Sys.EventArgs.Empty);
},_onTextBoxFocusHandler:function(a){if(!this.isReadOnly()){this._updateStateOnFocus();
}if(($telerik.isSafari||$telerik.isFirefox)&&this.get_selectionOnFocus()!=Telerik.Web.UI.SelectionOnFocus.None&&this.get_selectionOnFocus()!=Telerik.Web.UI.SelectionOnFocus.SelectAll){var b=this;
window.setTimeout(function(){b._updateSelectionOnFocus();
},0);
}},_onTextBoxDragEnterHandler:function(a){if(this.isEmpty()&&this.get_emptyMessage()!=""){this.set_textBoxValue("");
}},_onTextBoxDragLeaveHandler:function(a){if(this.isEmpty()&&this.get_emptyMessage()!=""&&!$telerik.isMouseOverElement(this._textBoxElement,a)){this.set_textBoxValue(this.get_emptyMessage());
}},_updateStateOnFocus:function(){if(this._isDropped||this._lastSetTextBoxValue!==this._textBoxElement.value){this._updateHiddenValue();
this._isDropped=false;
}this._focused=true;
this.updateDisplayValue();
this.updateCssClass();
this._updateSelectionOnFocus();
this.raise_focus(Sys.EventArgs.Empty);
},_onTextBoxMouseOutHandler:function(a){this._hovered=false;
this.updateCssClass();
this.raise_mouseOut(Sys.EventArgs.Empty);
},_onTextBoxMouseOverHandler:function(a){this._hovered=true;
this.updateCssClass();
this.raise_mouseOver(Sys.EventArgs.Empty);
},_onTextBoxKeyDownHandler:function(a){if(a.keyCode==27&&!$telerik.isIE){var b=this;
window.setTimeout(function(){b.set_textBoxValue(b.get_editValue());
},0);
}},_onTextBoxMouseWheelHandler:function(b){var a;
if(this._focused){if(b.rawEvent.wheelDelta){a=b.rawEvent.wheelDelta/120;
if(window.opera){a=-a;
}}else{if(b.detail){a=-b.rawEvent.detail/3;
}else{if(b.rawEvent&&b.rawEvent.detail){a=-b.rawEvent.detail/3;
}}}if(a>0){this._handleWheel(false);
}else{this._handleWheel(true);
}b.stopPropagation();
b.preventDefault();
}},_onButtonClickHandler:function(a){var b=new Telerik.Web.UI.InputButtonClickEventArgs(Telerik.Web.UI.InputButtonType.Button);
this.raise_buttonClick(b);
},_onTextBoxDragDropHandler:function(a){this._isDropped=true;
if($telerik.isFirefox){var b=this;
window.setTimeout(function(){b._textBoxElement.focus();
},1);
}},_onFormResetHandler:function(a){if(this.get_element().form===a.target){var b=this._constructValueFromInitialText(this._originalInitialValueAsText);
this._setHiddenValue(b);
this._initialValueAsText=this._text;
this.set_displayValue(this._constructDisplayText(this._value));
this.updateClientState();
this.updateCssClass();
}},_calculateSelection:function(){if((Sys.Browser.agent==Sys.Browser.Opera)||!document.selection){var d=this._supportSelection();
if(d){this._selectionEnd=this._textBoxElement.selectionEnd;
this._selectionStart=this._textBoxElement.selectionStart;
}return;
}var c=0;
var b=0;
try{c=Math.abs(document.selection.createRange().moveStart("character",-10000000));
if(c>0){c=this._calculateSelectionInternal(c);
}b=Math.abs(document.selection.createRange().moveEnd("character",-10000000));
if(b>0){b=this._calculateSelectionInternal(b);
}}catch(a){}this._selectionEnd=b;
this._selectionStart=c;
},_calculateSelectionInternal:function(e){if(!this.isMultiLine()){return e;
}var b=Math.abs(this._textBoxElement.createTextRange().moveEnd("character",-10000000));
var c=document.body.createTextRange();
c.moveToElementText(this._textBoxElement);
var d=Math.abs(c.moveStart("character",-10000000));
var a=Math.abs(c.moveEnd("character",-10000000));
if(a-b==d){e-=d;
}return e;
},_SetValue:function(a){var b=this._setHiddenValue(a);
if(typeof(b)=="undefined"||b==true){this.set_textBoxValue(this.get_editValue());
this.updateClientState();
}},_triggerDomEvent:function(a,c){if(!a||a==""||!c){return;
}if(a=="change"){this._textBoxElement.RadInputChangeFired=true;
}var b;
if(c.fireEvent&&document.createEventObject){b=document.createEventObject();
c.fireEvent(String.format("on{0}",a),b);
}else{if(c.dispatchEvent){b=document.createEvent("HTMLEvents");
b.initEvent(a,true,true);
c.dispatchEvent(b);
}}if(a=="change"){this._textBoxElement.RadInputChangeFired=false;
}},_updateSelectionOnFocus:function(){if(!this._textBoxElement.value){this.set_caretPosition(0);
}switch(this.get_selectionOnFocus()){case Telerik.Web.UI.SelectionOnFocus.None:break;
case Telerik.Web.UI.SelectionOnFocus.CaretToBeginning:this.set_caretPosition(0);
break;
case Telerik.Web.UI.SelectionOnFocus.CaretToEnd:if(this._textBoxElement.value.length>0){if($telerik.isIE){var a=this._textBoxElement.value.replace(/\r/g,"").length;
if(a!=this.get_caretPosition()){this.set_caretPosition(a);
}}else{this.set_caretPosition(this._textBoxElement.value.length);
}}break;
case Telerik.Web.UI.SelectionOnFocus.SelectAll:this.selectAllText();
break;
default:this.set_caretPosition(0);
break;
}},_isInVisibleContainer:function(b){var a=b;
while((typeof(a)!="undefined")&&(a!=null)){if((a.disabled==true)||(typeof(a.style)!="undefined"&&((typeof(a.style.display)!="undefined"&&a.style.display=="none")||(typeof(a.style.visibility)!="undefined"&&a.style.visibility=="hidden")))){return false;
}if(typeof(a.parentNode)!="undefined"&&a.parentNode!=null&&a.parentNode!=a&&a.parentNode.tagName.toLowerCase()!="body"){a=a.parentNode;
}else{return true;
}}return true;
},_supportSelection:function(){if(!!this.get_inputType){var a=this.get_inputType();
if(a==Telerik.Web.UI.InputType.Date||a==Telerik.Web.UI.InputType.DateTime||a==Telerik.Web.UI.InputType.DateTimeLocal||a==Telerik.Web.UI.InputType.Month||a==Telerik.Web.UI.InputType.Week||a==Telerik.Web.UI.InputType.Time){return false;
}}return true;
},_applySelection:function(){if(!this._isInVisibleContainer(this._textBoxElement)){return;
}var b=this;
var d;
if((Sys.Browser.agent==Sys.Browser.Opera)||!document.selection){var f=this._supportSelection();
if(f){this._textBoxElement.selectionStart=b._selectionStart;
this._textBoxElement.selectionEnd=b._selectionEnd;
}return;
}try{this._textBoxElement.select();
d=document.selection.createRange();
d.collapse();
d.moveStart("character",this._selectionStart);
d.collapse();
d.moveEnd("character",this._selectionEnd-this._selectionStart);
d.select();
}catch(c){var a=this;
window.setTimeout(function(){document.body.focus();
a._textBoxElement.select();
d=document.selection.createRange();
d.collapse();
d.moveStart("character",a._selectionStart);
d.collapse();
d.moveEnd("character",a._selectionEnd-a._selectionStart);
d.select();
},1);
}},set_invalid:function(a){if(this._holdsValidValue==a){this._holdsValidValue=!a;
this.updateCssClass();
}},get_invalid:function(){return !this._holdsValidValue;
},_invalidate:function(){if(this._holdsValidValue){this._holdsValidValue=false;
this._initialValueAsText="";
this._displayText="";
this._clearHiddenValue();
return false;
}},_clearHiddenValue:function(){var a=this._errorHandlingCanceled;
this._errorHandlingCanceled=true;
this._setHiddenValue("");
this.updateClientState();
this._errorHandlingCanceled=a;
},_handleWheel:function(a){},_setHiddenValue:function(a){if(a){a=a.toString();
}else{a="";
}if(a==this._value){return false;
}else{this._value=a;
this._text=this._constructEditText(a);
this.set_validationText(this._constructValidationText(a));
return true;
}},get_validationText:function(a){return this._validationText;
},set_validationText:function(a){this._validationText=a;
this._textBoxElement.RadInputValidationValue=a;
},_updateHiddenValue:function(){if(!this._textBoxElement.readOnly){if(this._setHiddenValue(this._textBoxElement.value)){this.updateClientState();
return true;
}else{return false;
}}else{return false;
}},_escapeNewLineChars:function(b,a){return b.replace(/\r\n/g,"\n").replace(/\n/g,a);
},_isNormalChar:function(a){if(($telerik.isFirefox&&(a.rawEvent.keyCode!=0&&a.rawEvent.keyCode!=13)||a.ctrlKey)||($telerik.isOpera&&a.rawEvent.which==0)||($telerik.isSafari&&(a.charCode<Sys.UI.Key.space||a.charCode>60000))){return false;
}return true;
},_constructEditText:function(a){return a;
},_constructDisplayText:function(a){return a;
},_constructValidationText:function(a){return a;
},_constructValueFromInitialText:function(a){return a;
},_canAutoPostBackAfterValidation:function(){if(!this.get_causesValidation()||!window.Page_ValidationActive){return true;
}return window.Page_ClientValidate(this.get_validationGroup());
},add_blur:function(a){this.get_events().addHandler("blur",a);
},remove_blur:function(a){this.get_events().removeHandler("blur",a);
},raise_blur:function(a){this.raiseEvent("blur",a);
},add_mouseOut:function(a){this.get_events().addHandler("mouseOut",a);
},remove_mouseOut:function(a){this.get_events().removeHandler("mouseOut",a);
},raise_mouseOut:function(a){this.raiseEvent("mouseOut",a);
},add_valueChanged:function(a){this.get_events().addHandler("valueChanged",a);
},remove_valueChanged:function(a){this.get_events().removeHandler("valueChanged",a);
},raise_valueChanged:function(b,c){if(typeof(b)!="undefined"&&b!=null&&typeof(c)!="undefined"&&c!=null&&b.toString()==c.toString()){if(!this._isEnterPressed){return false;
}}var d=false;
if(typeof(b)!="undefined"&&b!=null&&typeof(c)!="undefined"&&c!=null){if(b.toString()!=c.toString()){var a=new Telerik.Web.UI.InputValueChangedEventArgs(b,c);
this.raiseEvent("valueChanged",a);
d=!a.get_cancel();
}else{d=this._isEnterPressed;
}}if(this.get_autoPostBack()&&d&&this._canAutoPostBackAfterValidation()){this.raisePostBackEvent();
}},add_error:function(a){this.get_events().addHandler("error",a);
},remove_error:function(a){this.get_events().removeHandler("error",a);
},raise_error:function(a){if(this.InEventRaise){return;
}this.InEventRaise=true;
this.raiseEvent("error",a);
if(!a.get_cancel()){this._invalid=true;
this._errorHandlingCanceled=false;
this.updateCssClass();
if(this.get_enableAriaSupport()){this._applyAriaStateChange("invalid",true);
}var c=this._isIncrementing?true:false;
var b=this;
var d=function(){b._invalid=false;
b.updateCssClass(c);
if(b.get_enableAriaSupport()){b._applyAriaStateChange("invalid",false);
}};
setTimeout(function(){d();
},this.get_invalidStyleDuration());
}else{this._errorHandlingCanceled=true;
this._invalid=false;
this.updateCssClass();
}this.InEventRaise=false;
},add_load:function(a){this.get_events().addHandler("load",a);
},remove_load:function(a){this.get_events().removeHandler("load",a);
},raise_load:function(a){this.raiseEvent("load",a);
},add_mouseOver:function(a){this.get_events().addHandler("mouseOver",a);
},remove_mouseOver:function(a){this.get_events().removeHandler("mouseOver",a);
},raise_mouseOver:function(a){this.raiseEvent("mouseOver",a);
},add_focus:function(a){this.get_events().addHandler("focus",a);
},remove_focus:function(a){this.get_events().removeHandler("focus",a);
},raise_focus:function(a){this.raiseEvent("focus",a);
},add_disable:function(a){this.get_events().addHandler("disable",a);
},remove_disable:function(a){this.get_events().removeHandler("disable",a);
},raise_disable:function(a){this.raiseEvent("disable",a);
},add_enable:function(a){this.get_events().addHandler("enable",a);
},remove_enable:function(a){this.get_events().removeHandler("enable",a);
},raise_enable:function(a){this.raiseEvent("enable",a);
},add_keyPress:function(a){this.get_events().addHandler("keyPress",a);
},remove_keyPress:function(a){this.get_events().removeHandler("keyPress",a);
},raise_keyPress:function(a){this.raiseEvent("keyPress",a);
},add_enumerationChanged:function(a){this.get_events().addHandler("enumerationChanged",a);
},remove_enumerationChanged:function(a){this.get_events().removeHandler("enumerationChanged",a);
},raise_enumerationChanged:function(a){this.raiseEvent("enumerationChanged",a);
},add_moveUp:function(a){this.get_events().addHandler("moveUp",a);
},remove_moveUp:function(a){this.get_events().removeHandler("moveUp",a);
},raise_moveUp:function(a){this.raiseEvent("moveUp",a);
},add_moveDown:function(a){this.get_events().addHandler("moveDown",a);
},remove_moveDown:function(a){this.get_events().removeHandler("moveDown",a);
},raise_moveDown:function(a){this.raiseEvent("moveDown",a);
},add_buttonClick:function(a){this.get_events().addHandler("buttonClick",a);
},remove_buttonClick:function(a){this.get_events().removeHandler("buttonClick",a);
},raise_buttonClick:function(a){this.raiseEvent("buttonClick",a);
},add_valueChanging:function(a){this.get_events().addHandler("valueChanging",a);
},remove_valueChanging:function(a){this.get_events().removeHandler("valueChanging",a);
},raise_valueChanging:function(a){this.raiseEvent("valueChanging",a);
}};
Telerik.Web.UI.RadInputControl.OverrideValidatorFunctions=function(){if(typeof(window.ValidatorGetValue)=="function"&&typeof(window.ValidatorGetValue_Original)=="undefined"){window.ValidatorGetValue_Original=window.ValidatorGetValue;
window.ValidatorGetValue=function(b){var a=document.getElementById(b);
if(typeof(a.RadInputValidationValue)=="string"){if(a.RadInputLastSetTextBoxValue==a.value){return a.RadInputValidationValue;
}else{return a.value;
}}else{return window.ValidatorGetValue_Original(b);
}};
}if(typeof(ValidatorOnChange)=="function"&&typeof(window.ValidatorOnChange_Original)=="undefined"){window.ValidatorOnChange_Original=window.ValidatorOnChange;
window.ValidatorOnChange=function(b){b=b||window.event;
var a;
if((typeof(b.srcElement)!="undefined")&&(b.srcElement!=null)){a=b.srcElement;
}else{a=b.target;
}if(typeof(a.RadInputValidationValue)!="string"||(typeof(a.RadInputChangeFired)=="boolean"&&a.RadInputChangeFired)){return window.ValidatorOnChange_Original(b);
}};
}if(typeof(window.ValidatedTextBoxOnKeyPress)=="function"&&typeof(window.ValidatedTextBoxOnKeyPress_Original)=="undefined"){window.ValidatedTextBoxOnKeyPress_Original=window.ValidatedTextBoxOnKeyPress;
window.ValidatedTextBoxOnKeyPress=function(b){b=b||window.event;
if(b.keyCode==13){window.ValidatorOnChange(b);
var a;
if((typeof(b.srcElement)!="undefined")&&(b.srcElement!=null)){a=b.srcElement;
}else{a=b.target;
}if(typeof(a.RadInputValidationValue)!="string"){return window.AllValidatorsValid(a.Validators);
}}return true;
};
}};
Telerik.Web.UI.RadInputControl.registerClass("Telerik.Web.UI.RadInputControl",Telerik.Web.UI.RadWebControl);
Telerik.Web.UI.RadInputControl.CancelRawEventOnEnterKey=function(b,a){if(a.get_keyCode()==13){return $telerik.cancelRawEvent(a.get_domEvent());
}};
Telerik.Web.UI.RadInputControl.OverrideValidatorFunctions();
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.InputErrorReason=function(){};
Telerik.Web.UI.InputErrorReason.prototype={ParseError:1,OutOfRange:2};
Telerik.Web.UI.InputErrorReason.registerEnum("Telerik.Web.UI.InputErrorReason",false);
Telerik.Web.UI.SelectionOnFocus=function(){};
Telerik.Web.UI.SelectionOnFocus.prototype={None:0,CaretToBeginning:1,CaretToEnd:2,SelectAll:3};
Telerik.Web.UI.SelectionOnFocus.registerEnum("Telerik.Web.UI.SelectionOnFocus",false);
Telerik.Web.UI.InputButtonType=function(){};
Telerik.Web.UI.InputButtonType.prototype={Button:1,MoveUpButton:2,MoveDownButton:3};
Telerik.Web.UI.InputButtonType.registerEnum("Telerik.Web.UI.InputButtonType",false);
Telerik.Web.UI.DisplayFormatPosition=function(){};
Telerik.Web.UI.DisplayFormatPosition.prototype={Left:1,Right:2};
Telerik.Web.UI.DisplayFormatPosition.registerEnum("Telerik.Web.UI.DisplayFormatPosition",false);
Telerik.Web.UI.InputSettingValidateOnEvent=function(){};
Telerik.Web.UI.InputSettingValidateOnEvent.prototype={Blur:0,Submit:1,All:2};
Telerik.Web.UI.InputSettingValidateOnEvent.registerEnum("Telerik.Web.UI.InputSettingValidateOnEvent",false);
Telerik.Web.UI.InputType=function(){};
Telerik.Web.UI.InputType.prototype={Text:0,Date:1,DateTime:2,Number:3,Time:4,DateTimeLocal:5,Month:6,Week:7,Range:8,Email:9,Url:10,Search:11,Tel:12,Color:13};
Telerik.Web.UI.InputType.registerEnum("Telerik.Web.UI.InputType",false);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.InputValueChangedEventArgs=function(a,b){Telerik.Web.UI.InputValueChangedEventArgs.initializeBase(this);
this._newValue=a;
this._oldValue=b;
};
Telerik.Web.UI.InputValueChangedEventArgs.prototype={get_oldValue:function(){return this._oldValue;
},get_newValue:function(){return this._newValue;
}};
Telerik.Web.UI.InputValueChangedEventArgs.registerClass("Telerik.Web.UI.InputValueChangedEventArgs",Sys.CancelEventArgs);
Telerik.Web.UI.InputValueChangingEventArgs=function(a,b){Telerik.Web.UI.InputValueChangingEventArgs.initializeBase(this,[a,b]);
};
Telerik.Web.UI.InputValueChangingEventArgs.prototype={set_newValue:function(a){if(this._newValue!==a){this._newValue=a;
}}};
Telerik.Web.UI.InputValueChangingEventArgs.registerClass("Telerik.Web.UI.InputValueChangingEventArgs",Telerik.Web.UI.InputValueChangedEventArgs);
Telerik.Web.UI.MaskedTextBoxEventArgs=function(b,c,a){Telerik.Web.UI.MaskedTextBoxEventArgs.initializeBase(this);
this._newValue=b;
this._oldValue=c;
this._chunk=a;
};
Telerik.Web.UI.MaskedTextBoxEventArgs.prototype={get_oldValue:function(){return this._oldValue;
},get_newValue:function(){return this._newValue;
},get_currentPart:function(){return this._chunk;
}};
Telerik.Web.UI.MaskedTextBoxEventArgs.registerClass("Telerik.Web.UI.MaskedTextBoxEventArgs",Sys.CancelEventArgs);
Telerik.Web.UI.InputKeyPressEventArgs=function(a,c,b){Telerik.Web.UI.InputKeyPressEventArgs.initializeBase(this);
this._domEvent=a;
this._keyCode=c;
this._keyCharacter=b;
};
Telerik.Web.UI.InputKeyPressEventArgs.prototype={get_domEvent:function(){return this._domEvent;
},get_keyCode:function(){return this._keyCode;
},get_keyCharacter:function(){return this._keyCharacter;
}};
Telerik.Web.UI.InputKeyPressEventArgs.registerClass("Telerik.Web.UI.InputKeyPressEventArgs",Sys.CancelEventArgs);
Telerik.Web.UI.InputButtonClickEventArgs=function(a){Telerik.Web.UI.InputButtonClickEventArgs.initializeBase(this);
this._buttonType=a;
};
Telerik.Web.UI.InputButtonClickEventArgs.prototype={get_buttonType:function(){return this._buttonType;
}};
Telerik.Web.UI.InputButtonClickEventArgs.registerClass("Telerik.Web.UI.InputButtonClickEventArgs",Sys.CancelEventArgs);
Telerik.Web.UI.InputErrorEventArgs=function(b,a){Telerik.Web.UI.InputErrorEventArgs.initializeBase(this);
this._reason=b;
this._inputText=a;
};
Telerik.Web.UI.InputErrorEventArgs.prototype={get_reason:function(){return this._reason;
},get_inputText:function(){return this._inputText;
}};
Telerik.Web.UI.InputErrorEventArgs.registerClass("Telerik.Web.UI.InputErrorEventArgs",Sys.CancelEventArgs);
Telerik.Web.UI.NumericInputErrorEventArgs=function(d,a,c,b){Telerik.Web.UI.NumericInputErrorEventArgs.initializeBase(this,[d,a]);
this._keyCode=c;
this._keyCharacter=b;
};
Telerik.Web.UI.NumericInputErrorEventArgs.prototype={get_reason:function(){return this._reason;
},get_inputText:function(){return this._inputText;
},get_keyCode:function(){return this._keyCode;
},get_keyCharacter:function(){return this._keyCharacter;
}};
Telerik.Web.UI.NumericInputErrorEventArgs.registerClass("Telerik.Web.UI.NumericInputErrorEventArgs",Telerik.Web.UI.InputErrorEventArgs);
Telerik.Web.UI.InputManagerKeyPressEventArgs=function(a,c,b,d){Telerik.Web.UI.InputManagerKeyPressEventArgs.initializeBase(this,[a,c,b]);
this._targetInput=d;
};
Telerik.Web.UI.InputManagerKeyPressEventArgs.prototype={get_targetInput:function(){return this._targetInput;
}};
Telerik.Web.UI.InputManagerKeyPressEventArgs.registerClass("Telerik.Web.UI.InputManagerKeyPressEventArgs",Telerik.Web.UI.InputKeyPressEventArgs);
Telerik.Web.UI.InputManagerEventArgs=function(b,a){Telerik.Web.UI.InputManagerEventArgs.initializeBase(this);
this._targetInput=b;
this._domEvent=a;
};
Telerik.Web.UI.InputManagerEventArgs.prototype={get_targetInput:function(){return this._targetInput;
},get_domEvent:function(){return this._domEvent;
}};
Telerik.Web.UI.InputManagerEventArgs.registerClass("Telerik.Web.UI.InputManagerEventArgs",Sys.EventArgs);
Telerik.Web.UI.InputManagerErrorEventArgs=function(b,a,c){Telerik.Web.UI.InputManagerErrorEventArgs.initializeBase(this,[b,a]);
this._targetInput=c;
};
Telerik.Web.UI.InputManagerErrorEventArgs.prototype={get_targetInput:function(){return this._targetInput;
},set_inputText:function(a){this._inputText=a;
}};
Telerik.Web.UI.InputManagerErrorEventArgs.registerClass("Telerik.Web.UI.InputManagerErrorEventArgs",Telerik.Web.UI.InputErrorEventArgs);
Telerik.Web.UI.NumericInputManagerErrorEventArgs=function(d,a,c,b,e){Telerik.Web.UI.NumericInputManagerErrorEventArgs.initializeBase(this,[d,a,c,b]);
this._targetInput=e;
};
Telerik.Web.UI.NumericInputManagerErrorEventArgs.prototype={get_targetInput:function(){return this._targetInput;
}};
Telerik.Web.UI.NumericInputManagerErrorEventArgs.registerClass("Telerik.Web.UI.NumericInputManagerErrorEventArgs",Telerik.Web.UI.NumericInputErrorEventArgs);
Telerik.Web.UI.InputManagerValidatingEventArgs=function(a){Telerik.Web.UI.InputManagerValidatingEventArgs.initializeBase(this);
this._input=a;
this._isValid=true;
this._context=null;
};
Telerik.Web.UI.InputManagerValidatingEventArgs.prototype={get_input:function(){return this._input;
},get_isValid:function(){return this._isValid;
},set_isValid:function(a){this._isValid=a;
},get_context:function(){return this._context;
},set_context:function(a){this._context=a;
}};
Telerik.Web.UI.InputManagerValidatingEventArgs.registerClass("Telerik.Web.UI.InputManagerValidatingEventArgs",Sys.CancelEventArgs);
Telerik.Web.UI.PasswordStrengthCalculatingEventArgs=function(b,c,a){Telerik.Web.UI.PasswordStrengthCalculatingEventArgs.initializeBase(this);
this._passwordText=b;
this._strengthScore=c;
this._indicatorText=a;
};
Telerik.Web.UI.PasswordStrengthCalculatingEventArgs.prototype={get_passwordText:function(){return this._passwordText;
},get_strengthScore:function(){return this._strengthScore;
},set_strengthScore:function(a){if(typeof a=="number"){a=Math.ceil(a);
if(a>100){a=100;
}if(a<0){a=0;
}this._strengthScore=a;
}},set_indicatorText:function(a){this._indicatorText=a;
}};
Telerik.Web.UI.PasswordStrengthCalculatingEventArgs.registerClass("Telerik.Web.UI.PasswordStrengthCalculatingEventArgs",Sys.EventArgs);
Telerik.Web.UI.InputManagerValueChangedEventArgs=function(b,a,d,c){this._domEvent=a;
this._oldValue=d;
this._newValue=c;
this._inputExtender=b;
};
Telerik.Web.UI.InputManagerValueChangedEventArgs.prototype={get_domEvent:function(){return this._domEvent;
},get_oldValue:function(){return this._oldValue;
},get_newValue:function(){return this._newValue;
},get_inputExtender:function(){return this._inputExtender;
}};
Telerik.Web.UI.InputManagerValueChangedEventArgs.registerClass("Telerik.Web.UI.InputManagerValueChangedEventArgs",Sys.EventArgs);
$telerik.findTextBox=$find;
$telerik.toTextBox=function(a){return a;
};
Telerik.Web.UI.RadTextBox=function(a){Telerik.Web.UI.RadTextBox.initializeBase(this,[a]);
this._maxLength=0;
this._inputType=Telerik.Web.UI.InputType.Text;
this._passwordSettings=null;
this._resizeMode="none";
this._resizeVertical=false;
this._resizeHorizontal=false;
this._onTextBoxMouseMoveDelegate=null;
this._onResizeIconMouseDownDelegate=null;
this._resizeIconSpan=null;
this._onMouseMoveDelegate=null;
this._onMouseUpDelegate=null;
this._wrapperElementExtraWidth=0;
this._parentElementExtraWidth=0;
this._wrapperElementExtraHeight=0;
this._parentElementExtraHeight=0;
this._minWidth=75;
this._minHeight=35;
};
Telerik.Web.UI.RadTextBox.prototype={initialize:function(){Telerik.Web.UI.RadTextBox.callBaseMethod(this,"initialize");
if(this._passwordSettings!=null){if(this._passwordSettings.ShowIndicator){Telerik.Web.UI.PasswordStrengthChecker.prototype.showStrength(this,this._textBoxElement,this._passwordSettings);
}}if(this._resizeMode!="none"){if(this._resizeMode=="vertical"){this._resizeVertical=true;
}else{if(this._resizeMode=="horizontal"){this._resizeHorizontal=true;
}else{if(this._resizeMode=="both"){this._resizeVertical=true;
this._resizeHorizontal=true;
}}}this._wrapperElementExtraWidth=this._textBoxElement.parentNode.offsetWidth-this._textBoxElement.offsetWidth;
this._parentElementExtraWidth=this.get_wrapperElement().offsetWidth-this._textBoxElement.offsetWidth;
this._wrapperElementExtraHeight=this._textBoxElement.parentNode.offsetHeight-this._textBoxElement.offsetHeight;
this._parentElementExtraHeight=this.get_wrapperElement().offsetHeight-this._textBoxElement.offsetHeight;
this._onTextBoxMouseMoveDelegate=Function.createDelegate(this,this._onTextBoxMouseMoveHandler);
window.$addHandler(this._textBoxElement,"mousemove",this._onTextBoxMouseMoveDelegate);
if($telerik.isIE){var a=document.createElement("span");
a.className="riResizeIcon";
this._textBoxElement.parentNode.appendChild(a);
this._onResizeIconMouseDownDelegate=Function.createDelegate(this,this._onResizeIconMouseDownHandler);
this._resizeIconSpan=a;
window.$addHandler(this._resizeIconSpan,"mousedown",this._onResizeIconMouseDownDelegate);
if(this._resizeVertical){if(this._resizeHorizontal){if(this._isRtl){this._resizeIconSpan.style.cursor="sw-resize";
}else{this._resizeIconSpan.style.cursor="se-resize";
}}else{this._resizeIconSpan.style.cursor="s-resize";
}}else{this._resizeIconSpan.style.cursor="w-resize";
}}else{this.get_wrapperElement().style.backgroundImage="none";
}}},dispose:function(){if(this._onTextBoxMouseMoveDelegate){window.$removeHandler(this._textBoxElement,"mousemove",this._onTextBoxMouseMoveDelegate);
this._onTextBoxMouseMoveDelegate=null;
}if(this._onResizeIconMouseDownDelegate){window.$removeHandler(this._resizeIconSpan,"mousedown",this._onResizeIconMouseDownDelegate);
this._onResizeIconMouseDownDelegate=null;
}this._onMouseUpHandler(null);
Telerik.Web.UI.RadTextBox.callBaseMethod(this,"dispose");
},_onTextBoxMouseWheelHandler:function(a){return true;
},_onTextBoxKeyUpHandler:function(a){Telerik.Web.UI.RadTextBox.callBaseMethod(this,"_onTextBoxKeyUpHandler",[a]);
if(this._passwordSettings!=null){if(this._passwordSettings.ShowIndicator){Telerik.Web.UI.PasswordStrengthChecker.prototype.showStrength(this,this._textBoxElement,this._passwordSettings);
}}},_adjustWrappersDimensions:function(){var a=false;
var c=this._parentElementExtraWidth+this._textBoxElement.offsetWidth;
var b=this._parentElementExtraHeight+this._textBoxElement.offsetHeight;
if(c!=this.get_wrapperElement().offsetWidth){this.get_wrapperElement().style.width=c+"px";
this._textBoxElement.parentNode.style.width=this._wrapperElementExtraWidth+this._textBoxElement.offsetWidth+"px";
a=true;
}if(b!=this.get_wrapperElement().offsetHeight){this.get_wrapperElement().style.height=b+"px";
this._textBoxElement.parentNode.style.height=this._wrapperElementExtraHeight+this._textBoxElement.offsetHeight+"px";
a=true;
}return a;
},_onTextBoxMouseMoveHandler:function(b){if(!$telerik.isIE){var a=this._adjustWrappersDimensions();
if(a&&!$telerik.isFirefox&&!this._onMouseMoveDelegate){this._onMouseMoveDelegate=Function.createDelegate(this,this._onMouseMoveHandler);
window.$addHandler(document,"mousemove",this._onMouseMoveDelegate);
this._onMouseUpDelegate=Function.createDelegate(this,this._onMouseUpHandler);
window.$addHandler(document,"mouseup",this._onMouseUpDelegate);
}}},_onResizeIconMouseDownHandler:function(a){$telerik.cancelRawEvent(a);
if(!this._onMouseUpDelegate&&!this._onMouseMoveDelegate){this._onMouseMoveDelegate=Function.createDelegate(this,this._onMouseMoveHandler);
window.$addHandler(document,"mousemove",this._onMouseMoveDelegate);
this._onMouseUpDelegate=Function.createDelegate(this,this._onMouseUpHandler);
window.$addHandler(document,"mouseup",this._onMouseUpDelegate);
}},_onTextBoxMouseUpHandler:function(a){this._onMouseUpHandler(a);
Telerik.Web.UI.RadTextBox.callBaseMethod(this,"_onTextBoxMouseUpHandler",[a]);
},_onMouseUpHandler:function(a){if(this._onMouseMoveDelegate){window.$removeHandler(document,"mousemove",this._onMouseMoveDelegate);
this._onMouseMoveDelegate=null;
}if(this._onMouseUpDelegate){window.$removeHandler(document,"mouseup",this._onMouseUpDelegate);
this._onMouseUpDelegate=null;
}},_onMouseMoveHandler:function(c){if($telerik.isIE){var f=$telerik.getLocation(this._textBoxElement);
var g;
var h;
if(c.rawEvent.pageX==null){var d=c.target.ownerDocument||document;
var b=d.documentElement;
var a=d.body;
g=c.clientX+(b&&b.scrollLeft||a&&a.scrollLeft||0)-(b&&b.clientLeft||a&&a.clientLeft||0);
h=c.clientY+(b&&b.scrollTop||a&&a.scrollTop||0)-(b&&b.clientTop||a&&a.clientTop||0);
}else{g=c.rawEvent.pageX;
h=c.rawEvent.pageY;
}if(this._resizeHorizontal){var j;
if(this._isRtl){j=(f.x-g)+this._textBoxElement.clientWidth+5;
}else{j=g-f.x+5;
}if(j>=this._minWidth){this._textBoxElement.style.width=j+"px";
}}if(this._resizeVertical){var i=5+h-f.y;
if(i>=this._minHeight){this._textBoxElement.style.height=i+"px";
}}}this._adjustWrappersDimensions();
},updateCssClass:function(a){if(this._resizeMode!="none"){this._originalTextBoxCssText="height: "+this._textBoxElement.style.height+"; width: "+this._textBoxElement.style.width+";";
}Telerik.Web.UI.RadTextBox.callBaseMethod(this,"updateCssClass",[a]);
},get_inputType:function(){return this._inputType;
},set_inputType:function(a){if(this._inputType!==a){this._inputType=a;
this.raisePropertyChanged("inputType");
}},get_maxLength:function(){return this._maxLength;
},set_maxLength:function(a){if(this._maxLength!==a){this._maxLength=a;
this.get_element().maxLength=a;
this.raisePropertyChanged("maxLength");
}},get_passwordSettings:function(){return this._passwordSettings;
},set_passwordSettings:function(a){if(this._passwordSettings!==a){this._passwordSettings=a;
}},raise_passwordStrengthCalculating:function(a){this.raiseEvent("passwordStrengthCalculating",a);
},add_passwordStrengthCalculating:function(a){this.get_events().addHandler("passwordStrengthCalculating",a);
},remove_passwordStrengthCalculating:function(a){this.get_events().removeHandler("passwordStrengthCalculating",a);
}};
Telerik.Web.UI.RadTextBox.registerClass("Telerik.Web.UI.RadTextBox",Telerik.Web.UI.RadInputControl);
