Type.registerNamespace("Telerik.Web.UI");
(function(){$telerik.toSlidingZone=function(b){return b;
};
$telerik.findSlidingZone=$find;
var a=Telerik.Web.UI;
a.SplitterSlideDirection=function(){};
a.SplitterSlideDirection.prototype={Right:1,Left:2,Top:3,Bottom:4};
a.SplitterSlideDirection.registerEnum("Telerik.Web.UI.SplitterSlideDirection",false);
a.RadSlidingZone=function(b){a.RadSlidingZone.initializeBase(this,[b]);
this._width=null;
this._height=null;
this._clickToOpen=false;
this._resizeStep=0;
this._slideDuration=300;
this._splitter=null;
this._slideDirection=a.SplitterSlideDirection.Right;
this._slidingPanes=null;
this._slidingPanesById=null;
this._initiallyDockedPaneId=null;
this._dockedPaneId=null;
this._initiallyExpandedPaneId=null;
this._expandedPaneId=null;
this.GetPaneById=this.getPaneById;
this.GetTabsContainer=this.getTabsContainer;
this.DockPane=this.dockPane;
this.UndockPane=this.undockPane;
this.GetPanes=this.getPanes;
this.ExpandPane=this.expandPane;
this.CollapsePane=this.collapsePane;
this.IsLeftDirection=this.isLeftDirection;
this.IsRightDirection=this.isRightDirection;
this.IsTopDirection=this.isTopDirection;
this.IsBottomDirection=this.isBottomDirection;
};
a.RadSlidingZone.prototype={endUpdate:function(){if(this._width.toString().indexOf("px")>-1){this._width=parseInt(this._width,10);
}if(this._height.toString().indexOf("px")>-1){this._height=parseInt(this._height,10);
}a.RadSlidingZone.callBaseMethod(this,"endUpdate");
},dispose:function(){var d=this.getPanes();
for(var b=0,c=d.length;
b<c;
b++){var e=d[b];
if(e){e._moveRootToParent(true);
}}if(this._paneTabMoutTimeout){window.clearTimeout(this._paneTabMoutTimeout);
this._paneTabMoutTimeout=null;
}a.RadSplitterController.getInstance()._removeSlidingZone(this.get_id());
a.RadSlidingZone.callBaseMethod(this,"dispose");
},initialize:function(){a.RadSlidingZone.callBaseMethod(this,"initialize");
var b=this._getPanesContainer();
var c=this.get_element();
if(this._isVerticalSlide()){b=b.parentNode;
if(this.isTopDirection()&&($telerik.isIE6||$telerik.isIE7)){c.style.marginTop="-1px";
}}else{if(this.isLeftDirection()&&$telerik.isSafari){c.style.marginLeft="-1px";
}}if($telerik.isIE6||$telerik.isIE7){c.setAttribute("cellSpacing","0");
c.setAttribute("cellPadding","0");
}b.style.display="";
},set_clickToOpen:function(b){this._clickToOpen=b;
this.updateClientState();
},get_clickToOpen:function(){return this._clickToOpen;
},set_resizeStep:function(b){this._resizeStep=b;
this.updateClientState();
},get_resizeStep:function(){return this._resizeStep;
},set_slideDuration:function(e){this._slideDuration=e;
this.updateClientState();
var d=this.getPanes();
for(var b=0;
b<d.length;
b++){var c=d[b];
c._slideDuration=e;
if(c._animation){c._animation._expandAnimation.set_duration(e);
}}},get_slideDuration:function(){return this._slideDuration;
},get_width:function(){return this._width;
},get_height:function(){return this._height;
},get_expandedPaneId:function(){return this._expandedPaneId;
},get_dockedPaneId:function(){return this._dockedPaneId;
},get_parent:function(){return this._getParentPane();
},_getParentPane:function(){var b=this._parent;
if(!b){b=this._parent=a.RadSplitterController.getInstance()._getParentPane(this.get_id());
}return b;
},get_splitter:function(){var b=this._splitter;
if(!b){b=this._splitter=a.RadSplitterController.getInstance()._getSplitter(this.get_id());
}return b;
},set_splitter:function(b){this._splitter=b;
},add_loaded:function(b){this.add_load(b);
},remove_loaded:function(b){this.remove_load(b);
},add_load:function(b){this.get_events().addHandler("load",b);
},remove_load:function(b){this.get_events().removeHandler("load",b);
},getPaneById:function(b){return this._getSlidingPanesById()[b];
},getTabsContainer:function(){return $get("RAD_SLIDING_ZONE_TABS_CONTAINER_"+this.get_id());
},_getPanesContainer:function(){return $get("RAD_SLIDING_ZONE_PANES_CONTAINER_"+this.get_id());
},dockPane:function(h){var j=this.getPaneById(h);
if(!j||!j.get_enableDock()){return false;
}var d=new Sys.CancelEventArgs();
j.raiseEvent("docking",d);
if(d.get_cancel()){return false;
}var c=this._dockedPaneId;
if(c&&!this.undockPane(c)){return false;
}j._moveRootToParent(true);
var i=this._getPanesContainer();
var e=this.isLeftDirection();
var f=this.isTopDirection();
this._dockingMode=true;
var o=this._getTabsContainerSize();
var l=o+j[this._isHorizontalSlide()?"get_width":"get_height"]();
var k=this.get_parent();
var m=k.getVarSize();
var n=(e||f)?a.SplitterDirection.Backward:a.SplitterDirection.Forward;
var g=m+this.get_splitter()._getAvailIncreaseDelta(k.get_indexInPanes(),n);
l=Math.min(l,g);
var b=l-m;
if(b!=0){k.resize(b,n);
}j._dock();
j._setSlidingContainerSize();
j._setTabDockedState();
var p=this.get_element();
if(f&&($telerik.isIE6||$telerik.isIE7)){p.style.marginTop="0";
}else{if(e&&$telerik.isSafari){i.style.width="1px";
setTimeout(function(){i.style.width="";
},0);
p.style.marginLeft="0";
}}this._dockedPaneId=h;
this._dockingMode=false;
this.updateClientState();
j.raiseEvent("docked",new Sys.EventArgs());
return true;
},undockPane:function(g){var i=this.getPaneById(g);
if(!i){return false;
}var d=new Sys.CancelEventArgs();
i.raiseEvent("undocking",d);
if(d.get_cancel()){return false;
}if(!g){g=this._dockedPaneId;
}var j=this.get_parent();
if(j.get_collapsed()){return false;
}i._moveRootToParent(false);
this._dockingMode=true;
i._undock();
i._setTabDefaultState();
this._dockedPaneId=null;
var f=this.isTopDirection();
var e=this.isLeftDirection();
var h=this._getPanesContainer();
var l=this.get_element();
if(f&&($telerik.isIE6||$telerik.isIE7)){l.style.marginTop="-1px";
}else{if(e&&$telerik.isSafari){h.style.width="1px";
setTimeout(function(){h.style.width="";
},0);
l.style.marginLeft="-1px";
}}var b=j.getVarSize();
var c=b-this._getTabsContainerSize();
var k=(e||f)?a.SplitterDirection.Backward:a.SplitterDirection.Forward;
j.resize(c*(-1),k);
this.updateClientState();
this._dockingMode=false;
i.raiseEvent("undocked",new Sys.EventArgs());
this._paneTabInMover=null;
return true;
},getPanes:function(){var b=this._slidingPanes;
if(!b){var c=this.get_id();
b=this._slidingPanes=a.RadSplitterController.getInstance()._getSlidingPanes(c);
}return b;
},_getSlidingPanesById:function(){var f=this._slidingPanesById;
if(!f){f=[];
var e=this.getPanes();
for(var b=0,c=e.length;
b<c;
b++){var d=e[b];
f[d.get_id()]=d;
}this._slidingPanesById=f;
}return f;
},expandPane:function(e){if(!e){return false;
}var d=this.getPaneById(e);
if(!d){return false;
}if(d._dockOnOpen){this.dockPane(e);
this._dockedPaneId=e;
this.updateClientState();
return false;
}var c=this._expandedPaneId;
if((e==this._paneTabInMover)||(c&&e==c)){return false;
}if(c&&!this.collapsePane(c)){this._paneTabInMover=null;
return;
}if(e==this._dockedPaneId){return false;
}var b=new Sys.CancelEventArgs();
d.raiseEvent("expanding",b);
if(b.get_cancel()){return false;
}this._paneTabInMover=e;
d._setTabExpandedState();
d._expand();
this._expandedPaneId=e;
this.updateClientState();
return true;
},collapsePane:function(e,d){if(this._expandedPaneId!=e){return true;
}if(this._dockedPaneId==e){return false;
}var f=this.getPaneById(e);
if(!f){return false;
}var c=new Sys.CancelEventArgs();
f.raiseEvent("collapsing",c);
if(c.get_cancel()){return false;
}f._setTabDefaultState();
var b=f._animation;
if(b){b._stopAnimation();
}if(!d){f._tableElement.style.position="";
}f._collapse();
this._expandedPaneId=null;
this.updateClientState();
this._paneTabInMover=null;
return true;
},isLeftDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Left);
},isRightDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Right);
},isTopDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Top);
},isBottomDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Bottom);
},_paneTab_OnMouseOver:function(b){if(this._clickToOpen){return;
}window.clearTimeout(this._paneTabMoutTimeout);
var c=this._getPaneIdFromTabElement(b.target);
this.expandPane(c);
},_paneTab_OnMouseOut:function(b){if(this._clickToOpen){return;
}var c=this._getPaneIdFromTabElement(b.target);
if(!c){return;
}if($telerik.isMouseOverElementEx(this.getPaneById(c).getTabContainer(),b)){return $telerik.cancelRawEvent(b);
}this._paneTabMoutTimeout=setTimeout(Function.createDelegate(this,function(){this._paneTabInMover=null;
this.collapsePane(c);
}),100);
},_paneTab_OnMouseDown:function(b){if(!this._clickToOpen){return;
}var f=b.target;
var d=this._getPaneIdFromTabElement(f);
var c=this._expandedPaneId;
if(c==d){this.collapsePane(d);
}else{this.expandPane(d);
}},_isHorizontalSlide:function(){return(this._slideDirection==a.SplitterSlideDirection.Left||this._slideDirection==a.SplitterSlideDirection.Right);
},_isVerticalSlide:function(){return !this._isHorizontalSlide();
},_getPaneIdFromTabElement:function(b){while(b&&b.tagName!="DIV"){b=b.parentNode;
}if(!b||b.id.indexOf("RAD_SLIDING_PANE_TAB_")==-1){return"";
}return b.id.substr("RAD_SLIDING_PANE_TAB_".length);
},_handleParentPaneResizing:function(k,b){if(this._dockingMode){return;
}var d=b.get_delta();
if(this._dockedPaneId){var e=this.getPaneById(this._dockedPaneId);
if(!e.get_enableResize()){b.set_cancel(true);
return;
}var l=this._getTabsContainerSize();
var h=l+(this._isHorizontalSlide())?e.get_minWidth():e.get_minHeight();
var g=l+(this._isHorizontalSlide())?e.get_maxWidth():e.get_maxHeight();
var f=e.get_slidingPaneBounds();
var c=(this._isHorizontalSlide())?f.width:f.height;
var i=c+d;
if(i>g||i<h){b.set_cancel(true);
return;
}var j=new a.PaneResizingEventArgs(d);
e.raiseEvent("resizing",j);
b.set_cancel(j.get_cancel());
}},_getTabsContainerSize:function(){var b=this.getTabsContainer();
return(this._isHorizontalSlide())?b.offsetWidth:b.offsetHeight;
},_handleParentPaneResized:function(q,b){var h=this._dockedPaneId;
if(this._dockingMode||!h){return;
}var g=this.getPaneById(h);
var j=g.get_enableResize();
var k=g._isVerticalSlide();
var i=g.get_slidingPaneBounds();
var d=i.width;
var f=(!j&&!k)?0:(q.get_width()-b.get_oldWidth());
var n=d+f;
var c=i.height;
var e=(!j&&k)?0:q.get_height()-b.get_oldHeight();
var m=c+e;
g._setSlidingContainerSize(n,m);
var p=g.get_width();
var o=b.get_oldHeight();
var l=q.get_height();
g.set_width(n);
g.set_height(l);
g.raiseEvent("resized",new a.PaneResizedEventArgs(p,o));
},_handleSplitterResized:function(d,b){if(this._expandedPaneId){if(d.get_width()!=b.get_oldWidth()||d.get_height()!=b.get_oldHeight()){var c=this._expandedPaneId;
this.collapsePane(c);
this.expandPane(c);
}}},_splitterLoadHandler:function(){var f=this.get_parent();
f.add_resizing(Function.createDelegate(this,this._handleParentPaneResizing));
f.add_resized(Function.createDelegate(this,this._handleParentPaneResized));
var k=this.get_splitter();
k.add_resized(Function.createDelegate(this,this._handleSplitterResized));
if($telerik.quirksMode||$telerik.isFirefox2){var j=this.getPanes();
for(var d=0,e=j.length;
d<e;
d++){var h=j[d];
var g=h.get_element();
g.className=k.getContainerElement().className+" RadSlidingPaneQuirksMode "+g.className;
h._originalParent=h.get_element().parentNode;
h._moveRootToParent(false);
}}var b=this._initiallyDockedPaneId;
if(b!=null){this.dockPane(b);
}var c=this._initiallyExpandedPaneId;
if(c!=null){this.expandPane(c);
}this.updateClientState();
this.raiseEvent("load");
},saveClientState:function(){if(this.get_isUpdating()){return null;
}var f={dockedPaneId:this._dockedPaneId||"",expandedPaneId:this._expandedPaneId||""};
var d=["clickToOpen","resizeStep","slideDuration"];
for(var b=0,c=d.length;
b<c;
b++){var e=d[b];
f[e]=this["get_"+e]();
}return Sys.Serialization.JavaScriptSerializer.serialize(f);
}};
a.RadSlidingZone._preInitialize=function(c,d,b){a.RadSplitterController.getInstance()._addSlidingZone(c,d,b);
};
a.RadSlidingZone.registerClass("Telerik.Web.UI.RadSlidingZone",a.RadWebControl);
})();
Type.registerNamespace("Telerik.Web.UI");
(function(){$telerik.toSlidingPane=function(f){return f;
};
$telerik.findSlidingPane=$find;
var b=Telerik.Web.UI;
var a=$telerik.$;
var c=Telerik.Web.Browser;
var d=Telerik.Web.BrowserFeatures;
var e={width:1,height:1};
b.RadSlidingPane=function(f){b.RadSlidingPane.initializeBase(this,[f]);
this._title="";
this._isTabRotated=false;
this._enableResize=true;
this._enableDock=true;
this._dockOnOpen=false;
this._parentPane=null;
this._clickToOpen=false;
this._slideDirection=b.SplitterSlideDirection.Right;
this._slideDuration=300;
this._resizeBarSize=null;
this._isExpanded=false;
this._isDocked=false;
this._width=150;
this._height=150;
this._minWidth=60;
this._minHeight=60;
this._overlay=false;
this._isInitialSizeApplied=false;
this._popupBehavior=null;
this._popupElement=null;
this._contentElement=null;
this._tableElement=null;
this._tabContainer=null;
this._resizeElement=null;
this._originalParent=null;
this.GetContentContainer=this.getContentContainer;
this.GetContent=this.getContent;
this.SetContent=this.setContent;
this.GetDockIconElement=this.getDockIconElement;
this.GetUndockIconElement=this.getUndockIconElement;
this.GetCollapseIconElement=this.getCollapseIconElement;
this.GetSlidingContainerTitle=this.getSlidingContainerTitle;
this.GetSlidingPaneResizeContainer=this.getSlidingPaneResizeContainer;
this.GetTabContainer=this.getTabContainer;
this.HideTab=this.hideTab;
this.ShowTab=this.showTab;
this.IsTabDisplayed=this.isTabDisplayed;
};
b.RadSlidingPane.prototype={initialize:function(){b.RadSlidingPane.callBaseMethod(this,"initialize");
this._popupElement=this.get_element();
this._contentElement=this.getContentContainer();
this._tableElement=this._popupElement.getElementsByTagName("TABLE")[0];
this._tabContainer=this.getTabContainer();
this._resizeElement=this.getSlidingPaneResizeContainer();
var m=this._tabContainer;
$addHandlers(m,{mousedown:this._paneTab_OnMouseDown,mouseover:this._paneTab_OnMouseOver,mouseout:this._paneTab_OnMouseOut},this);
var l=this._popupElement;
$addHandlers(l,{mouseover:this._slidingContainer_OnMouseOver,mouseout:this._slidingContainer_OnMouseOut},this);
var k=this._resizeElement;
if(k){k.setAttribute("unselectable","on");
$addHandlers(k,{mouseover:this._resizeSlidePane_OnMouseOver,mouseout:this._resizeSlidePane_OnMouseOut},this);
this._createResizeHelper();
var j=this._getCursorStyle();
var h={};
h[j]=k;
this._resizeExtender=new b.ResizeExtender(this,this._helperBar,h,null,null,j,false);
}var g=this.getDockIconElement();
$addHandlers(g,{mouseover:this._dockElement_OnMouseOver,mouseout:this._dockElement_OnMouseOut,mousedown:this._dockElement_OnMouseDown},this);
var n=this.getUndockIconElement();
$addHandlers(n,{mouseover:this._undockElement_OnMouseOver,mouseout:this._undockElement_OnMouseOut,mousedown:this._undockElement_OnMouseDown},this);
var f=this.getCollapseIconElement();
$addHandlers(f,{mouseover:this._collapseElement_OnMouseOver,mouseout:this._collapseElement_OnMouseOut,mousedown:this._collapseElement_OnMouseDown},this);
if(this._scrollingEnabled){if(b.TouchScrollExtender._getNeedsScrollExtender()&&!this._dropDownTouchScroll){this._createTouchScrollExtender(true);
}else{if(this._persistScrollPosition){this._attachScrollHandler(true);
}}}var i=this._tableElement.getElementsByTagName("table")[0];
if($telerik.isIE6||$telerik.isIE7){this._tableElement.setAttribute("cellSpacing","0");
this._tableElement.setAttribute("cellPadding","0");
i.setAttribute("cellSpacing","0");
i.setAttribute("cellPadding","0");
}if(this._resizeElement){this._setResizeElSpan();
}if(this._isHorizontalSlide()&&!$telerik.getInvisibleParent(this.get_element())){if(!$telerik.isIE){this._applyTabRotation();
}}this.updateClientState();
},dispose:function(){this._moveRootToParent(true);
this._originalParent=null;
var i=this._popupBehavior;
if(i){i.dispose();
this._popupBehavior=null;
}var f=this._animation;
if(this._expandAnimationEndedDelegate){if(f){f.remove_expandAnimationEnded(this._expandAnimationEndedDelegate);
}this._expandAnimationEndedDelegate=null;
}if(f){f.dispose();
this._animation=null;
}var l=this._tabContainer;
if(l){$clearHandlers(l);
}var k=this._popupElement;
if(k){$clearHandlers(k);
}this._popupElement=null;
var j=this._resizeElement;
if(j){$clearHandlers(j);
}this._resizeElement=null;
var h=this.getDockIconElement();
if(h){$clearHandlers(h);
}var m=this.getUndockIconElement();
if(m){$clearHandlers(m);
}var g=this.getCollapseIconElement();
if(g){$clearHandlers(g);
}this._attachScrollHandler(false);
this._createTouchScrollExtender(false);
this._contentElement=null;
b.RadSplitterController.getInstance()._removeSlidingPane(this.get_id());
b.RadSlidingPane.callBaseMethod(this,"dispose");
},repaint:function(){b.RadSlidingPane.callBaseMethod(this,"repaint");
if(!this._isTabRotated&&!$telerik.isIE){this._applyTabRotation();
}},get_parent:function(){return this._getSlidingZone();
},_getSlidingZone:function(){var f=this._parent;
if(!f){f=this._parent=b.RadSplitterController.getInstance()._getSlidingZone(this.get_id());
}return f;
},get_enableResize:function(){return this._enableResize;
},set_enableResize:function(f){this._enableResize=f;
this.updateClientState();
},get_enableDock:function(){return this._enableDock;
},set_enableDock:function(f){this._enableDock=f;
this.updateClientState();
},get_dockOnOpen:function(){return this._dockOnOpen;
},set_dockOnOpen:function(f){this._dockOnOpen=f;
this.updateClientState();
},set_title:function(h){this._title=h;
var f=this._getTitleContainerElement();
if(f!=null){f.innerHTML=h;
}var g=this.getSlidingContainerTitle();
if(g){g.innerHTML=h;
}this.updateClientState();
},get_title:function(){return this._title;
},get_expanded:function(){return this._isExpanded;
},get_docked:function(){return this._isDocked;
},get_overlay:function(){return this._overlay;
},set_overlay:function(g){this._overlay=g;
var f=this._popupBehavior;
if(f){f.set_overlay(this._overlay);
}},get_parentPane:function(){var f=this._parentPane;
if(!f){f=this._parentPane=b.RadSplitterController.getInstance()._getParentPane(this.get_id());
}return f;
},set_parentPane:function(f){this._parentPane=f;
},add_docked:function(f){this.get_events().addHandler("docked",f);
},remove_docked:function(f){this.get_events().removeHandler("docked",f);
},add_undocked:function(f){this.get_events().addHandler("undocked",f);
},remove_undocked:function(f){this.get_events().removeHandler("undocked",f);
},add_beforeDock:function(f){this.add_docking(f);
},remove_beforeDock:function(f){this.remove_docking(f);
},add_docking:function(f){this.get_events().addHandler("docking",f);
},remove_docking:function(f){this.get_events().removeHandler("docking",f);
},add_beforeUndock:function(f){this.add_undocking(f);
},remove_beforeUndock:function(f){this.remove_undocking(f);
},add_undocking:function(f){this.get_events().addHandler("undocking",f);
},remove_undocking:function(f){this.get_events().removeHandler("undocking",f);
},getContentContainer:function(){if(!this._contentElement){this._contentElement=$get("RAD_SLIDING_PANE_CONTENT_"+this.get_id());
}return this._contentElement;
},get_pane:function(){return this.get_parentPane().get_element();
},get_paneBounds:function(){var f=this.get_pane();
return $telerik.getBounds(f);
},_show:function(g,h){var f=this._popupBehavior;
f._setCoordinates(g,h);
f.show();
},get_slidingPaneBounds:function(){var f=this._popupElement;
var h=(f.style.top==""&&!this._isDocked);
if(h){this._setSlidingContainerSize();
}var g=$telerik.getBounds(f);
return g;
},_fixIeHeight:function(i,g){if($telerik.standardsMode){var f=(i.offsetHeight-parseInt(g,10));
if(f>0){var h=(parseInt(i.style.height,10)-f);
if(h>0){i.style.height=h+"px";
}}}},getContent:function(){return this._contentElement.innerHTML;
},setContent:function(f){this._contentElement.innerHTML=f;
},getDockIconElement:function(){return $get("RAD_SPLITTER_SLIDING_PANE_DOCK_"+this.get_id());
},getDockIconWrapperElement:function(){return this.getDockIconElement().parentNode;
},getUndockIconElement:function(){return $get("RAD_SPLITTER_SLIDING_PANE_UNDOCK_"+this.get_id());
},getUnDockIconWrapperElement:function(){return this.getUndockIconElement().parentNode;
},getCollapseIconElement:function(){return $get("RAD_SPLITTER_SLIDING_PANE_COLLAPSE_"+this.get_id());
},getCollapseIconWrapperElement:function(){return this.getCollapseIconElement().parentNode;
},getSlidingContainerTitle:function(){return $get("RAD_SPLITTER_SLIDING_TITLE_"+this.get_id());
},getSlidingPaneResizeContainer:function(){if(!this._resizeElement){this._resizeElement=$get("RAD_SPLITTER_SLIDING_ZONE_RESIZE_"+this.get_id());
}return this._resizeElement;
},getTabContainer:function(){if(!this._tabContainer){this._tabContainer=$get("RAD_SLIDING_PANE_TAB_"+this.get_id());
}return this._tabContainer;
},hideTab:function(){var f=this._tabContainer;
if(f==null){return;
}f.style.display="none";
},showTab:function(){var f=this._tabContainer;
if(f==null){return;
}f.style.display="";
},isTabDisplayed:function(){var f=this._tabContainer;
if(f==null){return false;
}return(f.style.display!="none");
},_setResizeElSpan:function(){if(this._isHorizontalSlide()){this._resizeElement.setAttribute("rowSpan","2");
}else{this._resizeElement.setAttribute("colSpan","2");
}},_getIsLeftDirection:function(){var f=$telerik.isRightToLeft(this.get_element());
return(this._isLeftDirection()&&!f)||(f&&this._isRightDirection());
},_getIsRightDirection:function(){var f=$telerik.isRightToLeft(this.get_element());
return(this._isRightDirection()&&!f)||(f&&this._isLeftDirection());
},_setTabDefaultState:function(){var f=this._tabContainer;
if(f==null){return false;
}Sys.UI.DomElement.removeCssClass(f,"rspPaneTabContainerDocked");
Sys.UI.DomElement.removeCssClass(f,"rspPaneTabContainerExpanded");
},_setTabDockedState:function(){var f=this._tabContainer;
if(f==null){return false;
}Sys.UI.DomElement.addCssClass(f,"rspPaneTabContainerDocked");
},_setTabExpandedState:function(){var f=this._tabContainer;
if(f==null){return false;
}Sys.UI.DomElement.addCssClass(f,"rspPaneTabContainerExpanded");
},_applyTabRotation:function(){if(this._isTabRotated){return;
}var j=a("span",this._tabContainer).get(0),f=this._getTabIconElement(),g=f?a(f).outerHeight(true):0;
if(this._isHorizontalSlide()){a(this._tabContainer).height(a(j).width()+g);
}var m=0;
var i=a(j);
if($telerik.isRightToLeft(this.get_element())){m=i.width()+parseInt(i.css("margin-left"),10)-i.height();
}if(d.writingMode){var o=i.hasClass("rspRotatedTabText")?"vertical-rl":"horizontal-tb";
i.css({transform:"rotate(0)",writingMode:o});
}else{var l=String.format("{0}transform",this._getBrowserCssPrefix());
i.css(l,"matrix(0, 1, -1, 0, "+m+", 0)");
var k=this._calculateTabTextLineHeight();
var h=Math.ceil(k/2);
var n=String.format("{0}transform-origin",this._getBrowserCssPrefix());
i.css(n,String.format("{0}px {0}px",h)).css("line-height",k+"px");
}this._isTabRotated=true;
},_calculateTabTextLineHeight:function(){var f=(this._isHorizontalSlide())?"width":"height";
return parseInt($telerik.getComputedStyle(this._tabContainer,f),10);
},_getTabIconElement:function(){return $get("RAD_SLIDING_PANE_ICON_"+this.get_id());
},_resizeSlidePane_OnMouseOver:function(f){var g=(this._isHorizontalSlide())?"rspSlideContainerResizeOver":"rspSlideContainerResizeOverHorizontal";
Sys.UI.DomElement.addCssClass(this._resizeElement,g);
},_resizeSlidePane_OnMouseOut:function(f){var g=(this._isHorizontalSlide())?"rspSlideContainerResizeOver":"rspSlideContainerResizeOverHorizontal";
Sys.UI.DomElement.removeCssClass(this._resizeElement,g);
},_resizeByDelta:function(f){var g=new b.PaneResizingEventArgs(f);
this.raiseEvent("resizing",g);
if(g.get_cancel()){return;
}var j=this._isTopDirection();
var i=this._getIsLeftDirection();
if(j||i){f*=-1;
}var h=this._isHorizontalSlide();
var p=this.get_slidingPaneBounds();
var l=h?(p.width+f):null;
var k=!h?(p.height+f):null;
this._setSlidingContainerSize(l,k);
var o=this._popupBehavior;
var q=o.get_x()-(i?f:0);
var r=o.get_y()-(j?f:0);
this._show(q,r);
var n=this.get_width();
var m=this.get_height();
if(h){this.set_width(l);
this._resizeTitleElemWidth(l);
}else{this.set_height(k);
}$telerik.repaintChildren(this);
this.raiseEvent("resized",new b.PaneResizedEventArgs(n,m));
},_resizeTitleElemWidth:function(i){var h=this.getSlidingContainerTitle(),f=$telerik.getMarginBox(h),g=$telerik.getComputedStyle(h,"overflow");
h.style.overflow="hidden";
h.style.width="1px";
i=i-f.horizontal-this._resizeElement.offsetWidth-this._getCommandsWidth();
h.style.width=i>18?i+"px":18+"px";
h.style.overflow=g;
},_getIconWrapperElements:function(){return $telerik.getElementsByClassName(this.get_element(),"rspSlideHeaderIconWrapper");
},_getCommandsWidth:function(){var j=0;
var h=this._getIconWrapperElements();
for(var f=0;
f<h.length;
f++){var g=h[f];
if($telerik.getVisible(g)){j+=g.offsetWidth;
}}return j;
},_getCursorStyle:function(){return(this._isHorizontalSlide()?"w-resize":"n-resize");
},_createResizeHelper:function(){var j=this._popupElement.style.zIndex+2;
var h=this._isHorizontalSlide();
var f=this._getCursorStyle();
var i=document.createElement("div");
i.unselectable="on";
a(i).css({display:"none",position:"absolute",cursor:f,zIndex:j});
document.body.insertBefore(i,document.body.firstChild);
Sys.UI.DomElement.addCssClass(i,"RadSplitter");
var g=document.createElement("div");
g.unselectable="on";
a(g).css({cursor:f,fontSize:"1px",margin:(h?"0 150px":"150px 0")});
g.innerHTML="<!-- / -->";
i.appendChild(g);
Sys.UI.DomElement.addCssClass(g,"rspHelperBarSlideDrag");
this._helperBar=i;
this._helperBarDecoration=g;
},_getHelperSize:function(){var g={width:4,height:4};
var f=this.get_parentPane();
if(this._isHorizontalSlide()){g.height=f.get_height();
}else{g.width=f.get_width();
}return g;
},onDragStart:function(f){var A=this._getSlidingZone();
var i=A.get_dockedPaneId();
if(i==this.get_id()){return false;
}var m=this._isHorizontalSlide();
var z=this.get_width();
var k=this.get_height();
var o=m?(z-this.get_minWidth()):(k-this.get_minHeight());
var p=m?(this.get_maxWidth()-z):(this.get_maxHeight()-k);
var r=this.get_parentPane();
var u=this.get_splitter()._getAvailDecreaseDelta(r.get_indexInPanes(),b.SplitterDirection.Forward);
var s=Math.min(r._getAvailIncreaseDelta(),u);
if(i!=null){var h=A.getPaneById(i);
s+=(m)?h.get_width():h.get_height();
}s-=(m)?z:k;
p=Math.min(p,s);
if(this._getIsLeftDirection()||this._isTopDirection()){var y=p;
p=o;
o=y;
}var x=this.get_splitter();
var q=x._getDragOverlay();
a(q).css({zIndex:(this._popupElement.style.zIndex+1),cursor:this._getCursorStyle(),display:"block"});
$telerik.setBounds(q,$telerik.getBounds(x.get_element()));
var w=this._getHelperSize();
$telerik.setSize(this._helperBarDecoration,w);
var v=this._resizeElement;
var n=$telerik.getLocation(v);
if($telerik.isSafari&&m){n.y=$telerik.getLocation(v.parentNode).y;
}var g=this._cachedResizeHelperBounds=a.extend({},w,n);
this._liveResizePosition=a.extend({},g);
this._cachedSplitterBounds={x:g.x-(m?o:0),y:g.y-(!m?o:0),width:g.width+(m?(o+p):0),height:g.height+(!m?(o+p):0)};
n[m?"x":"y"]-=150;
var l=this._helperBar;
l.style.display="";
$telerik.setLocation(l,n);
var j=this._resizeExtender;
j._originalBounds=a.extend({},g,n);
this._resizeMode=true;
return true;
},onDragEnd:function(f){if(!this.get_expanded()){return;
}var h=this._isHorizontalSlide()?"x":"y";
var g=this._liveResizePosition[h]-this._cachedResizeHelperBounds[h];
if(g!=0){this._resizeByDelta(g);
}this.get_splitter()._getDragOverlay().style.display="none";
this._helperBar.style.display="none";
Sys.UI.DomElement.removeCssClass(this._helperBarDecoration,"rspHelperBarSlideError");
this._liveResizePosition=null;
this._cachedSplitterBounds=null;
this._cachedResizeHelperBounds=null;
this._resizeMode=false;
},onDrag:function(f){var n=this._cachedSplitterBounds;
if(n.width<1||n.height<1){return false;
}var g=this._helperBarDecoration;
Sys.UI.DomElement.removeCssClass(g,"rspHelperBarSlideError");
var h=this._isHorizontalSlide();
var j=h?"x":"y";
f[j]+=150;
var m=this._cachedResizeHelperBounds;
var l=b.ResizeExtender.containsBounds(n,new Telerik.Web.UI.Bounds(f.x,f.y,m.width,m.height));
if(!l){var i=false;
if(f.x<=n.x){f.x=n.x;
if(h){i=true;
}}else{if(n.x+n.width<=f.x+m.width){f.x=n.x+n.width-m.width;
if(h){i=true;
}}}if(f.y<=n.y){f.y=n.y;
if(!h){i=true;
}}else{if(n.y+n.height<=f.y+m.height){f.y=n.y+n.height-m.height;
if(!h){i=true;
}}}l=true;
if(i){Sys.UI.DomElement.addCssClass(g,"rspHelperBarSlideError");
}}var k=this._resizeStep;
if(k>0){f[j]-=(f[j]-m[j])%k;
}this._liveResizePosition=a.extend({},f);
f[j]-=150;
return l;
},_paneTab_OnMouseDown:function(f){var g=this._getSlidingZone();
g._paneTab_OnMouseDown(f);
},_paneTab_OnMouseOver:function(f){var g=this._getSlidingZone();
g._paneTab_OnMouseOver(f);
},_paneTab_OnMouseOut:function(f){var g=this._getSlidingZone();
g._paneTab_OnMouseOut(f);
},_slidingContainer_OnMouseOut:function(g){if(this.get_docked()||this._resizeMode||this._clickToOpen||!this.get_expanded()){return;
}if($telerik.isMouseOverElementEx(this._popupElement,g)){return;
}var i=this;
var h=function(){var f=i._getSlidingZone();
f._paneTabInMover=null;
f.collapsePane(i.get_id());
};
var j=this._getSlidingZone();
window.clearTimeout(j._paneTabMoutTimeout);
j._paneTabMoutTimeout=window.setTimeout(h,1000);
},_slidingContainer_OnMouseOver:function(f){if(this.get_docked()||this._resizeMode){return;
}var g=this._getSlidingZone();
window.setTimeout(function(){window.clearTimeout(g._paneTabMoutTimeout);
},0);
},_dockElement_OnMouseDown:function(f){if(f.button&&f.button!=1){return true;
}if(!this.get_expanded()){return;
}var g=this._getSlidingZone();
if(!g.collapsePane(this.get_id(),true)){return;
}g.dockPane(this.get_id());
this.getDockIconElement().className="rspSlideHeaderDockIcon";
},_dockElement_OnMouseOver:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.addCssClass(this.getDockIconElement(),"rspSlideHeaderDockIconOver");
},_dockElement_OnMouseOut:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.removeCssClass(this.getDockIconElement(),"rspSlideHeaderDockIconOver");
},_undockElement_OnMouseDown:function(f){if(f.button&&f.button!=1){return true;
}if(!this.get_docked()){return;
}this._getSlidingZone().undockPane(this.get_id());
},_undockElement_OnMouseOver:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.addCssClass(this.getUndockIconElement(),"rspSlideHeaderUndockIconOver");
},_undockElement_OnMouseOut:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.removeCssClass(this.getUndockIconElement(),"rspSlideHeaderUndockIconOver");
},_collapseElement_OnMouseDown:function(f){if(f.button&&f.button!=1){return true;
}if(!this.get_expanded()){return;
}var g=this._getSlidingZone();
g._paneTabInMover=null;
g.collapsePane(this.get_id());
},_collapseElement_OnMouseOver:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.addCssClass(this.getCollapseIconElement(),"rspSlideHeaderCollapseIconOver");
},_collapseElement_OnMouseOut:function(f){if(f.button&&f.button!=1){return true;
}Sys.UI.DomElement.removeCssClass(this.getCollapseIconElement(),"rspSlideHeaderCollapseIconOver");
},_onExpandAnimationEnded:function(){this._tableElement.style.position="static";
if($telerik.isFirefox){this._configureScrolling();
Sys.UI.DomElement.removeCssClass(this._contentElement,"rspHideContentOverflow");
}if($telerik.getVisible(this.get_element())){this._showOverlayElement(true);
}this.setScrollPos(this._scrollLeft,this._scrollTop);
this._element.style.overflow="hidden";
$telerik.repaintChildren(this);
this.raiseEvent("expanded",new Sys.EventArgs());
},_expandSlidingContainer:function(){this._showOverlayElement(false);
if($telerik.isFirefox){var f=this._contentElement;
f.style.overflow="hidden";
Sys.UI.DomElement.addCssClass(f,"rspHideContentOverflow");
}var j=this._tableElement;
var k=$telerik.getOuterSize(j);
var g=b.jSlideDirection.Right;
if(this._getIsLeftDirection()){g=b.jSlideDirection.Left;
j.style.left=k.width+"px";
}else{if(this._isBottomDirection()){g=b.jSlideDirection.Down;
j.style.top=-k.height+"px";
}else{if(this._isTopDirection()){g=b.jSlideDirection.Up;
j.style.top=k.height+"px";
}else{j.style.left=-k.width+"px";
}}}if(!this._animation){var h=new b.AnimationSettings({duration:this._slideDuration});
var i=new b.jSlide(j,h,null,false);
i.initialize();
i.set_direction(g);
this._expandAnimationEndedDelegate=Function.createDelegate(this,this._onExpandAnimationEnded);
i.add_expandAnimationEnded(this._expandAnimationEndedDelegate);
this._animation=i;
}this._animation.expand();
},_collapseSlidingContainer:function(){try{this._animation.stop();
}catch(f){}this._hideSlidingContainer();
this.raiseEvent("collapsed",new Sys.EventArgs());
},_setSlidingContainerSize:function(m,h){var l=$telerik.getSize(this.get_parentPane()._contentElement);
var i=this._isVerticalSlide();
if(m==null){m=(!i)?this.get_width():l.width;
}if(h==null){h=i?this.get_height():l.height;
}var f=this._contentElement;
if($telerik.isSafari){f.style.width=m+"px";
f.style.height=h+"px";
}var j=this._popupElement;
if(parseInt(j.style.width,10)!=m){j.style.width=m+"px";
}if(parseInt(j.style.height,10)!=h){j.style.height=h+"px";
}if(c.ie&&c.version===8){this._setContentOuterSize(e);
}var k=this._getResizeElementSize();
var g={height:(h-this._getHeaderHeight()-(i?k.height:0)),width:(m-(!i?k.width:0))};
this._setContentOuterSize(g);
this._isInitialSizeApplied=true;
},_getHeaderHeight:function(){var f=0;
var g=$telerik.getElementByClassName(this._tableElement,"rspSlideHeader","tr");
if(g){f=$telerik.getOuterSize(g).height;
}return f;
},_getResizeElementSize:function(){var g={width:0,height:0};
if(this._enableResize){var f=this._resizeElement;
if("none"!=$telerik.getCurrentStyle(f,"display","")){g=$telerik.getOuterSize(f);
}}return g;
},_setContentOuterSize:function(j){var g=this._contentElement;
var f=$telerik.getBorderBox(g);
var i=$telerik.getPaddingBox(g);
var h=$telerik.getMarginBox(g);
j.height-=(f.vertical+i.vertical+h.vertical);
if(parseInt(g.style.height,10)!=j.height&&j.height>=0){g.style.height=j.height+"px";
}j.width-=(f.horizontal+i.horizontal+h.horizontal);
if(parseInt(g.style.width,10)!=j.width&&j.width>=0){g.style.width=j.width+"px";
}},_hideSlidingContainer:function(){var f=this._popupElement;
f.style.top="";
f.style.left="";
this._showOverlayElement(false);
},_dockSlidingContainer:function(){this._popupElement.style.position="static";
this._tableElement.style.position="static";
this._showOverlayElement(false);
},_unDockSlidingContainer:function(){this._popupElement.style.position="";
this._tableElement.style.position="";
this._showOverlayElement(true);
},_setSlidingContainerResizable:function(h){var j=this._resizeElement;
var g=this._isVerticalSlide();
if(g){j=j.parentNode;
}if(h&&j.style.display==""){return;
}if(this._enableResize){var i=this._resizeBarSize;
if(null==i){i=this._getResizeElementSize()[g?"height":"width"];
if(i>0){this._resizeBarSize=i;
}}if(h){i*=-1;
}var f=this._contentElement;
if(g){f.style.height=parseInt(f.style.height,10)+i+"px";
}else{f.style.width=parseInt(f.style.width,10)+i+"px";
}}j.style.display=(h)?"":"none";
},_setIconsExpandedState:function(){this._hideAllIcons();
this.getDockIconWrapperElement().style.display=(this.get_enableDock())?"":"none";
this.getCollapseIconWrapperElement().style.display="";
},_setIconsDockedState:function(){this._hideAllIcons();
this.getUnDockIconWrapperElement().style.display="";
},_hideAllIcons:function(){this.getDockIconWrapperElement().style.display="none";
this.getUnDockIconWrapperElement().style.display="none";
this.getCollapseIconWrapperElement().style.display="none";
},_getTitleContainerElement:function(){return $get("RAD_SLIDING_PANE_TEXT_"+this.get_id());
},_dock:function(){if(!this._isInitialSizeApplied){this._setSlidingContainerSize();
}this._setIconsDockedState();
this._setSlidingContainerResizable(false);
this._dockSlidingContainer();
this.setScrollPos(this._scrollLeft,this._scrollTop);
$telerik.repaintChildren(this);
this._isExpanded=false;
this._isDocked=true;
},_undock:function(){this._isExpanded=false;
this._isDocked=false;
this._setSlidingContainerResizable(this._enableResize);
this._unDockSlidingContainer();
this._hideSlidingContainer();
},_expand:function(){var j=this._getSlidingZone().getTabsContainer();
var i=this._popupElement;
if(!this._popupBehavior){var f=(new Date()-100)+"PopupBehavior";
this._popupBehavior=$create(Telerik.Web.PopupBehavior,{id:f,parentElement:j,overlay:this._overlay,keepInScreenBounds:false,manageVisibility:false},null,null,i);
}this._setSlidingContainerResizable(this._enableResize);
this._setIconsExpandedState();
var k=0;
var l=0;
var g=this.get_slidingPaneBounds();
var h=$telerik.getSize(j);
if(this._getIsRightDirection()){k=h.width;
}else{if(this._getIsLeftDirection()){k=-g.width;
}else{if(this._isBottomDirection()){l=h.height;
}else{if(this._isTopDirection()){l=-g.height;
}}}}this._show(k,l);
this._expandSlidingContainer();
if(this._isHorizontalSlide()){this._resizeTitleElemWidth(g.width);
}this._isExpanded=true;
this._isDocked=false;
},_collapse:function(){this._isExpanded=false;
this._isDocked=false;
this._collapseSlidingContainer();
},_isLeftDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Left);
},_isRightDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Right);
},_isTopDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Top);
},_isBottomDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Bottom);
},_isHorizontalSlide:function(){return(this._slideDirection==b.SplitterSlideDirection.Left||this._slideDirection==b.SplitterSlideDirection.Right);
},_isVerticalSlide:function(){return !this._isHorizontalSlide();
},saveClientState:function(){var k=this.getScrollPos();
var l={_scrollLeft:k.left,_scrollTop:k.top};
var h=["width","height","title","enableResize","minWidth","maxWidth","minHeight","maxHeight","enableDock"];
for(var f=0,g=h.length;
f<g;
f++){var j=h[f];
l[j]=this["get_"+j]();
}return Sys.Serialization.JavaScriptSerializer.serialize(l);
},_getOverlayElement:function(){return this._popupElement._hideWindowedElementsIFrame;
},_showOverlayElement:function(g){var f=this._getOverlayElement();
if(!f){return;
}f.style.display=g?"":"none";
},_getRadioButtons:function(){var f=this._contentElement.getElementsByTagName("input");
var k=[];
for(var g=0,j=f.length;
g<j;
g++){var h=f[g];
if(h.type=="radio"){k.push(h);
}}return k;
},_getRadioButtonsStatus:function(h){var j=[];
for(var f=0,g=h.length;
f<g;
f++){j.push(h[f].getAttribute("checked"));
}return j;
},_restoreRadioButtonsStatus:function(h,g){for(var f=g.length-1;
f>=0;
f--){if(h.length==0){break;
}g[f].setAttribute("checked",h.pop());
}},_moveRootToParent:function(k){if(!$telerik.quirksMode&&!$telerik.isFirefox2){return;
}var f=(k)?this._originalParent:this.get_splitter().get_element();
var j=this._popupElement;
if(!j){return;
}var g=j.parentNode;
var h;
var i;
if(!f||!g||f.id==g.id){return;
}if($telerik.isIE){h=this._getRadioButtons();
i=this._getRadioButtonsStatus(h);
}g.removeChild(j);
f.appendChild(j);
if($telerik.isIE){this._restoreRadioButtonsStatus(i,h);
}},_getBrowserCssPrefix:function(){if($telerik.isFirefox){return"-moz-";
}else{if($telerik.isChrome||$telerik.isSafari){return"-webkit-";
}else{if($telerik.isOpera){return"-o-";
}else{return"";
}}}}};
b.RadSlidingPane._preInitialize=function(h,i,j,g,f){b.RadSplitterController.getInstance()._addSlidingPane(h,i,j,g,f);
};
b.RadSlidingPane.registerClass("Telerik.Web.UI.RadSlidingPane",b.SplitterPaneBase);
d.addTest("writingMode",function(){var f=document.body;
var g=document.createElement("span");
g.appendChild(document.createTextNode("some long content"));
g.style.position="absolute";
g.style.left="-10000000";
g.style.top="-10000000";
g.style.writingMode="vertical-rl";
try{f.appendChild(g);
return g.offsetWidth<g.offsetHeight;
}finally{f.removeChild(g);
}});
})();
