Type.registerNamespace("Telerik.Web.UI");
(function(){var a=Telerik.Web.UI;
a.SplitterItem=function(b){a.SplitterItem.initializeBase(this,[b]);
this._index=-1;
this._splitter=null;
this._splitterOrientation=a.Orientation.Vertical;
};
a.SplitterItem.prototype={initialize:function(){a.SplitterItem.callBaseMethod(this,"initialize");
},dispose:function(){a.SplitterItem.callBaseMethod(this,"dispose");
},get_index:function(){var b=this._index;
if(b==(-1)){b=this._index=a.RadSplitterController.getInstance()._getIndex(this.get_id());
}return b;
},get_splitter:function(){var b=this._splitter;
if(!b){b=this._splitter=a.RadSplitterController.getInstance()._getSplitter(this.get_id());
}return b;
},get_parent:function(){return this.get_splitter();
},_isSplitterVertical:function(){return(this._splitterOrientation==a.Orientation.Vertical);
}};
a.SplitterItem.registerClass("Telerik.Web.UI.SplitterItem",a.RadWebControl);
})();
(function(){Type.registerNamespace("Telerik.Web.UI");
var a=Telerik.Web.UI;
a.PaneResizingEventArgs=function(b,c){a.PaneResizingEventArgs.initializeBase(this);
this._delta=b;
this._resizeDirection=c;
};
a.PaneResizingEventArgs.prototype={get_delta:function(){return this._delta;
},get_resizeDirection:function(){return this._resizeDirection;
}};
a.PaneResizingEventArgs.registerClass("Telerik.Web.UI.PaneResizingEventArgs",Sys.CancelEventArgs);
a.PaneBeforeResizeEventArgs=a.PaneResizingEventArgs;
a.PaneResizedEventArgs=function(c,b){a.PaneResizedEventArgs.initializeBase(this);
this._oldWidth=c;
this._oldHeight=b;
};
a.PaneResizedEventArgs.prototype={get_oldWidth:function(){return this._oldWidth;
},get_oldHeight:function(){return this._oldHeight;
}};
a.PaneResizedEventArgs.registerClass("Telerik.Web.UI.PaneResizedEventArgs",Sys.EventArgs);
a.SplitterPaneBase=function(b){a.SplitterPaneBase.initializeBase(this,[b]);
this._minWidth=20;
this._minHeight=20;
this._maxWidth=10000;
this._maxHeight=10000;
this._collapsed=false;
this._scrollingEnabled=true;
this._persistScrollPosition=true;
this._scrollHandler=null;
this._scrollLeft=0;
this._scrollTop=0;
this._dropDownTouchScroll=null;
this._width=0;
this._height=0;
this.GetScrollPos=this.getScrollPos;
this.SetScrollPos=this.setScrollPos;
};
a.SplitterPaneBase.prototype={endUpdate:function(){if(this._width.toString().indexOf("px")>-1){this._width=parseInt(this._width,10);
}if(this._height.toString().indexOf("px")>-1){this._height=parseInt(this._height,10);
}a.SplitterPaneBase.callBaseMethod(this,"endUpdate");
},initialize:function(){a.SplitterPaneBase.callBaseMethod(this,"initialize");
var b=this._isSplitterVertical();
this.getVarSize=b?this.get_width:this.get_height;
this.setVarSize=b?this.set_width:this.set_height;
this.getVarMinSize=b?this.get_minWidth:this.get_minHeight;
this.getVarMaxSize=b?this.get_maxWidth:this.get_maxHeight;
},dispose:function(){a.SplitterPaneBase.callBaseMethod(this,"dispose");
},_setOuterWidth:function(d,f){if(!d){throw Error.argumentNull("element");
}if(f==null){throw Error.argumentNull("width");
}var b=$telerik.getBorderBox(d);
var e=$telerik.getPaddingBox(d);
var c=f-b.horizontal-e.horizontal;
d.style.width=c.toString()+"px";
},_setOuterHeight:function(d,e){if(!d){throw Error.argumentNull("element");
}if(e==null){throw Error.argumentNull("height");
}var b=$telerik.getBorderBox(d);
var f=$telerik.getPaddingBox(d);
var c=e-b.vertical-f.vertical;
d.style.height=c.toString()+"px";
},set_minWidth:function(b){this._minWidth=b;
this.updateClientState();
},get_minWidth:function(){return this._minWidth;
},set_minHeight:function(b){this._minHeight=b;
this.updateClientState();
},get_minHeight:function(){return this._minHeight;
},set_maxWidth:function(b){this._maxWidth=b;
this.updateClientState();
},get_maxWidth:function(){return this._maxWidth;
},set_maxHeight:function(b){this._maxHeight=b;
this.updateClientState();
},get_maxHeight:function(){return this._maxHeight;
},set_width:function(b){this._width=b;
this.updateClientState();
},get_width:function(){return this._width;
},set_height:function(b){this._height=b;
this.updateClientState();
},get_height:function(){return this._height;
},set_collapsed:function(b){this._collapsed=b;
this.updateClientState();
},get_collapsed:function(){return this._collapsed;
},get_scrolling:function(){return this._scrolling;
},set_scrolling:function(b){if($telerik.isOpera&&(b==a.SplitterPaneScrolling.X||b==a.SplitterPaneScrolling.Y)){this._scrolling=a.SplitterPaneScrolling.Both;
}else{this._scrolling=b;
}this._configureScrolling();
this._scrollingEnabled=(this._scrolling!=a.SplitterPaneScrolling.None);
},getScrollPos:function(){return{left:this._scrollLeft,top:this._scrollTop};
},setScrollPos:function(c,d){var b=this._getContentElement();
if(b){b.scrollLeft=this._scrollLeft=c;
b.scrollTop=this._scrollTop=d;
}},get_persistScrollPosition:function(){return this._persistScrollPosition;
},set_persistScrollPosition:function(b){this._persistScrollPosition=b;
},add_beforeCollapse:function(b){this.add_collapsing(b);
},remove_beforeCollapse:function(b){this.remove_collapsing(b);
},add_collapsing:function(b){this.get_events().addHandler("collapsing",b);
},remove_collapsing:function(b){this.get_events().removeHandler("collapsing",b);
},add_beforeExpand:function(b){this.add_expanding(b);
},remove_beforeExpand:function(b){this.remove_expanding(b);
},add_expanding:function(b){this.get_events().addHandler("expanding",b);
},remove_expanding:function(b){this.get_events().removeHandler("expanding",b);
},add_beforeResize:function(b){this.add_resizing(b);
},remove_beforeResize:function(b){this.remove_resizing(b);
},add_resizing:function(b){this.get_events().addHandler("resizing",b);
},remove_resizing:function(b){this.get_events().removeHandler("resizing",b);
},add_collapsed:function(b){this.get_events().addHandler("collapsed",b);
},remove_collapsed:function(b){this.get_events().removeHandler("collapsed",b);
},add_expanded:function(b){this.get_events().addHandler("expanded",b);
},remove_expanded:function(b){this.get_events().removeHandler("expanded",b);
},add_resized:function(b){this.get_events().addHandler("resized",b);
},remove_resized:function(b){this.get_events().removeHandler("resized",b);
},_getContentElement:function(){var b=null;
if(this.getContentContainer){b=this.getContentContainer();
}else{if(this.getContentElement){b=this.getContentElement();
}}return b;
},_configureScrolling:function(){var b=this._getContentElement();
if(b){var c=this.get_scrolling();
switch(c){case a.SplitterPaneScrolling.None:b.style.overflow="hidden";
break;
case a.SplitterPaneScrolling.X:b.style.overflowX="auto";
b.style.overflowY="hidden";
break;
case a.SplitterPaneScrolling.Y:b.style.overflowX="hidden";
b.style.overflowY="auto";
break;
case a.SplitterPaneScrolling.Both:default:b.style.overflow="auto";
break;
}}},_attachScrollHandler:function(d){var b=this._getContentElement();
if(b){var c=this._scrollHandler;
if(c){if(!d){$telerik.removeExternalHandler(b,"scroll",c);
this._scrollHandler=null;
}}else{if(d){this._scrollHandler=Function.createDelegate(this,this._onScroll);
$telerik.addExternalHandler(b,"scroll",this._scrollHandler);
}}}},_createTouchScrollExtender:function(d){var b=this._getContentElement();
if(b){var c=this._dropDownTouchScroll;
if(c){if(!d){c.dispose();
this._dropDownTouchScroll=null;
}}else{if(d){this._dropDownTouchScroll=new a.TouchScrollExtender(b);
this._dropDownTouchScroll.initialize();
}}}},_onScroll:function(){var b=this._getContentElement();
if(b){this._scrollLeft=b.scrollLeft;
this._scrollTop=b.scrollTop;
this.updateClientState();
}}};
a.SplitterPaneBase.registerClass("Telerik.Web.UI.SplitterPaneBase",a.SplitterItem);
})();
Type.registerNamespace("Telerik.Web.UI");
(function(){$telerik.toSplitter=function(c){return c;
};
$telerik.findSplitter=$find;
var a=Telerik.Web.UI;
a.SplitterPaneScrolling=function(){};
a.SplitterPaneScrolling.prototype={Both:1,X:2,Y:3,None:4};
a.SplitterPaneScrolling.registerEnum("Telerik.Web.UI.SplitterPaneScrolling",false);
a.SplitterResizeMode=function(){};
a.SplitterResizeMode.prototype={AdjacentPane:1,Proportional:2,EndPane:3};
a.SplitterResizeMode.registerEnum("Telerik.Web.UI.SplitterResizeMode",false);
a.SplitterDirection=function(){};
a.SplitterDirection.prototype={Forward:1,Backward:2};
a.SplitterDirection.registerEnum("Telerik.Web.UI.SplitterDirection",false);
a.SplitterResizingEventArgs=function(d,c){a.SplitterResizingEventArgs.initializeBase(this);
this._newWidth=d;
this._newHeight=c;
};
a.SplitterResizingEventArgs.prototype={get_newWidth:function(){return this._newWidth;
},get_newHeight:function(){return this._newHeight;
}};
a.SplitterResizingEventArgs.registerClass("Telerik.Web.UI.SplitterResizingEventArgs",Sys.CancelEventArgs);
a.SplitterBeforeResizeEventArgs=a.SplitterResizingEventArgs;
a.SplitterResizedEventArgs=function(d,c){a.SplitterResizedEventArgs.initializeBase(this);
this._oldWidth=d;
this._oldHeight=c;
};
a.SplitterResizedEventArgs.prototype={get_oldWidth:function(){return this._oldWidth;
},get_oldHeight:function(){return this._oldHeight;
}};
a.SplitterResizedEventArgs.registerClass("Telerik.Web.UI.SplitterResizedEventArgs",Sys.EventArgs);
a.RadSplitter=function(c){a.RadSplitter.initializeBase(this,[c]);
this._fullScreenMode=false;
this._visibleDuringInit=true;
this._liveResize=false;
this._orientation=a.Orientation.Vertical;
this._resizeMode=a.SplitterResizeMode.AdjacentPane;
this._borderSize=1;
this._panesBorderSize=1;
this._splitBarSize=null;
this._width="400px";
this._height="400px";
this._heightOffset=0;
this._isNested=false;
this._load=null;
this._resizeWithBrowserWindow=true;
this._attachResizeHandler=false;
this._onWindowResizeDelegate=null;
this._parentPaneId="";
this._panes=null;
this._panesByIndex=null;
this._panesById=null;
this._splitBars=null;
this._splitBarsByAbsIndex=null;
this._splitBarsById=null;
this._splitBarsByIndex=null;
this._initializedInternal=false;
this._splitBarsSizeCalculated=false;
this._containerElement=$get("RAD_SPLITTER_"+this.get_id());
var d=$telerik.getViewPortSize();
this._initialWindowWidth=d.width;
this._initialWindowHeight=d.height;
this._cancelInterval=0;
this._lastResizedValue=0;
this._resizedValue=0;
this._registerWithScriptManager=true;
this._renderMode=a.RenderMode.Classic;
this.IsNested=this.isNested;
this.GetMinWidth=this.getMinWidth;
this.GetMaxWidth=this.getMaxWidth;
this.GetMinHeight=this.getMinHeight;
this.GetMaxHeight=this.getMaxHeight;
this.GetInnerWidth=this.getInnerWidth;
this.GetInnerHeight=this.getInnerHeight;
this.GetPanes=this.getPanes;
this.Resize=this.resize;
this.GetEndPane=this.getEndPane;
this.GetStartPane=this.getStartPane;
this.IsVertical=this.isVertical;
this.GetPaneByIndex=this.getPaneByIndex;
this.GetPaneById=this.getPaneById;
this.GetSplitBarByIndex=this.getSplitBarByIndex;
this.GetSplitBarById=this.getSplitBarById;
this.GetSplitBars=this.getSplitBars;
this.GetContainerElement=this.getContainerElement;
};
a.RadSplitter.prototype={endUpdate:function(){var c=this._width;
if(c.toString().indexOf("px")>-1){this._width=parseInt(c,10);
}c=this._height;
if(c.toString().indexOf("px")>-1){this._height=parseInt(c,10);
}a.RadSplitter.callBaseMethod(this,"endUpdate");
},initialize:function(){a.RadSplitter.callBaseMethod(this,"initialize");
this._originalWidth=this._width;
this._originalHeight=this._height;
if(this._attachResizeHandler){this._onWindowResizeDelegate=Function.createDelegate(this,this._windowResizeHandler);
$addHandler(window,"resize",this._onWindowResizeDelegate);
}if($telerik.isIE6||$telerik.isIE7){this._containerElement.setAttribute("cellSpacing","0");
this._containerElement.setAttribute("cellPadding","0");
}if(this._registerWithScriptManager){this._appLoadDelegate=Function.createDelegate(this,this._appLoadHandler);
Sys.Application.add_load(this._appLoadDelegate);
}else{this._appLoadHandler();
}},dispose:function(){if(this._onWindowResizeDelegate){$removeHandler(window,"resize",this._onWindowResizeDelegate);
this._onWindowResizeDelegate=null;
}var c=this._dragOverlay;
if(c){c.parentNode.removeChild(c);
}this._dragOverlay=null;
a.RadSplitterController.getInstance()._removeSplitter(this.get_id());
a.RadSplitter.callBaseMethod(this,"dispose");
},get_borderSize:function(){return this._borderSize;
},get_splitBarSize:function(){return this._splitBarSize;
},set_resizeMode:function(c){this._resizeMode=c;
},get_resizeMode:function(){return this._resizeMode;
},set_liveResize:function(c){this._liveResize=c;
},get_liveResize:function(){return this._liveResize;
},set_heightOffset:function(c){this._heightOffset=c;
},get_heightOffset:function(){return this._heightOffset;
},set_width:function(c){if(c.toString().indexOf("px")>-1){c=parseInt(c,10);
}else{if(c.toString().indexOf("%")>-1){c=this._calculatePercentSize(c).width;
}}if(c==this._width||isNaN(c)){return;
}this.resize(c);
},get_width:function(){return this._width;
},set_height:function(c){if(c.toString().indexOf("px")>-1){c=parseInt(c,10);
}else{if(c.toString().indexOf("%")>-1){c=this._calculatePercentSize(null,c).height;
}}if(c==this._height||isNaN(c)){return;
}this.resize(null,c);
},get_height:function(){return this._height;
},get_parent:function(){var c=this._parentPaneId;
if(c!=""){return $find(c);
}return null;
},get_renderMode:function(){return this._renderMode;
},set_renderMode:function(c){this._renderMode=c;
},add_loaded:function(c){this.add_load(c);
},remove_loaded:function(c){this.remove_load(c);
},add_load:function(c){this.get_events().addHandler("load",c);
},remove_load:function(c){this.get_events().removeHandler("load",c);
},add_beforeResize:function(c){this.add_resizing(c);
},remove_beforeResize:function(c){this.remove_resizing(c);
},add_resizing:function(c){this.get_events().addHandler("resizing",c);
},remove_resizing:function(c){this.get_events().removeHandler("resizing",c);
},add_resized:function(c){this.get_events().addHandler("resized",c);
},remove_resized:function(c){this.get_events().removeHandler("resized",c);
},getMinWidth:function(d,c){return this._getMinMaxSize(d,c,true,true);
},getMaxWidth:function(d,c){return this._getMinMaxSize(d,c,false,true);
},getMinHeight:function(d,c){return this._getMinMaxSize(d,c,true,false);
},getMaxHeight:function(d,c){return this._getMinMaxSize(d,c,false,false);
},isNested:function(){return this._isNested;
},getInnerWidth:function(){return this._width-this._getSplitterBordersSize();
},getInnerHeight:function(){return this._height-this._getSplitterBordersSize();
},getPanes:function(){var e=this._panes;
if(!e){var f=this.get_id();
var c=a.RadSplitterController.getInstance();
var d=(this.isVertical()&&$telerik.isRightToLeft(this.get_element()));
if(!this._splitBars){c._ensureItemsOrder(f,d);
}e=this._panes=c._getPanes(f);
}return e;
},resize:function(i,d){if(!this._initializedInternal){var g=null;
var f=null;
if(this.isNested()){g=i;
f=d;
}this._calculateInitialSize(g,f);
return;
}var c=new a.SplitterResizingEventArgs((i?i:this._width),(d?d:this._height));
this.raiseEvent("resizing",c);
if(c.get_cancel()){return false;
}var h=this._resizeSplitter(i,d);
if(h.fixedSizeChanged||h.varSizeChanged){var e=this._handleFixedSizeChange(h);
if(h.varSizeChanged){this._handleVarSizeChange(h,e);
}this._raisePanesResizeEvent();
}this.raiseEvent("resized",new a.SplitterResizedEventArgs(h.oldWidth,h.oldHeight));
return true;
},getEndPane:function(){var c=this._getPanesByIndex();
return c[c.length-1];
},getStartPane:function(){return this._getPanesByIndex()[0];
},isVertical:function(){return(this._orientation==a.Orientation.Vertical);
},getPaneByIndex:function(c){return this._getPanesByIndex()[c];
},getPaneById:function(c){return this._getPanesById()[c];
},getSplitBarByIndex:function(c){return this._getSplitBarsByIndex()[c];
},getSplitBarById:function(c){return this._getSplitBarsById()[c];
},getSplitBars:function(){var e=this._splitBars;
if(!e){var f=this.get_id();
var c=a.RadSplitterController.getInstance();
var d=(this.isVertical()&&$telerik.isRightToLeft(this.get_element()));
if(!this._panes){c._ensureItemsOrder(f,d);
}e=this._splitBars=c._getSplitBars(f);
}return e;
},getContainerElement:function(){return this._containerElement;
},_getSplitBarsByIndex:function(){var g=this._splitBarsByIndex;
if(!g){g=[];
var f=this.getSplitBars();
for(var c=0,d=f.length;
c<d;
c++){var e=f[c];
g[c]=e;
}this._splitBarsByIndex=g;
}return g;
},_getSplitBarsById:function(){var g=this._splitBarsById;
if(!g){g=[];
var f=this.getSplitBars();
for(var c=0,d=f.length;
c<d;
c++){var e=f[c];
g[e.get_id()]=e;
}this._splitBarsById=g;
}return g;
},_getPanesByIndex:function(){var g=this._panesByIndex;
if(!g){g=[];
var f=this.getPanes();
for(var c=0,d=f.length;
c<d;
c++){var e=f[c];
g[c]=e;
}this._panesByIndex=g;
}return g;
},_getPanesById:function(){var g=this._panesById;
if(!g){g=[];
var f=this.getPanes();
for(var c=0,d=f.length;
c<d;
c++){var e=f[c];
g[e.get_id()]=e;
}this._panesById=g;
}return g;
},_raisePanesResizeEvent:function(){var g=this._initializedInternal;
var f=this.getPanes();
for(var c=0,d=f.length;
c<d;
c++){var e=f[c];
if(e._isCollapsed()){continue;
}e._endResize(g);
}},_resizeSplitter:function(k,d){var e=this.isVertical();
var c;
var j={oldWidth:this._width,oldHeight:this._height,fixedSizeChanged:false,varSizeDelta:0};
if(k!=null){if(e){var i=this.getMinWidth();
var g=this.getMaxWidth();
k=Math.min(g,Math.max(i,k));
}if(k!=j.oldWidth){this._setOuterWidth(k);
if(e){c=this._getPanesVarSize()+this._getSplitBarsSize()+this._getSplitterBordersSize()+this._getItemsBorderSize();
j.varSizeDelta=k-c;
}else{j.fixedSizeChanged=true;
}}}if(d!=null){if(!e){var h=this.getMinHeight();
var f=this.getMaxHeight();
d=Math.min(f,Math.max(h,d));
}if(d!=j.oldHeight){this._setOuterHeight(d);
if(!e){c=this._getPanesVarSize()+this._getSplitBarsSize()+this._getSplitterBordersSize()+this._getItemsBorderSize();
j.varSizeDelta=d-c;
}else{j.fixedSizeChanged=true;
}}}j.varSizeChanged=(j.varSizeDelta!=0);
return j;
},_handleFixedSizeChange:function(o){var f=[];
var g={};
var k=[];
var l=0;
var n=this.getPanes();
var h=this.isVertical();
var c=h?this.getInnerHeight():this.getInnerWidth();
var d=h?"set_height":"set_width";
for(var e=0,j=n.length;
e<j;
e++){var m=n[e];
if(m._isCollapsed()){continue;
}m._initResize();
if(o.fixedSizeChanged){m[d](c,true);
}if(o.varSizeChanged){var p=m.getVarSize();
if(m._isInitialFreeSize()){g[m.get_id()]=p;
f[f.length]=m;
}else{l+=p;
k[k.length]=m;
}}}return{freePanes:f,freeSizes:g,notFreePanes:k,notFreeSize:l};
},_handleVarSizeChange:function(m,l){var c=m.varSizeDelta;
var f=l.freePanes;
var g=f.length;
if(g>0){var h=l.freeSizes;
var d=parseInt(c/g,10);
if(d!=0){for(var j=0;
j<g;
j++){var k=f[j];
var e=(d>0)?Math.min(d,k._getAvailIncreaseDelta()):Math.max(d,(-1)*k._getAvailDecreaseDelta());
c-=e;
h[k.get_id()]+=e;
}}c=this._fixRoundOffError(c,h,f);
}if(c!=0){this._resizeSetOfPanesProportional(c,l.notFreePanes,l.notFreeSize);
}},_resizeTwoPanesWithDelta:function(c,m,n){if(c==0||!m||m.length!=2||!m[0]||!m[1]){return false;
}var o=(!this._isCollapseMode&&!this._isExpandMode);
if(o){var d=new a.PaneResizingEventArgs(c,n);
m[0].raiseEvent("resizing",d);
if(d.get_cancel()){return false;
}d=new a.PaneResizingEventArgs(((-1)*c),n);
m[1].raiseEvent("resizing",d);
if(d.get_cancel()){return false;
}}for(var e=0,g=m.length;
e<g;
e++){var k=m[e];
var f=(e==0);
var l=(f?1:(-1))*c;
var j=k._width;
var h=k._height;
k.setVarSize(k.getVarSize()+l);
if(f&&!o){continue;
}k.raiseEvent("resized",new a.PaneResizedEventArgs(j,h));
}return true;
},_resizeAdjacentPane:function(d,e,f){var c=this._getAvailAdjacentPane(e.get_indexInPanes(),f);
return this._resizeTwoPanesWithDelta(d,[e,c],f);
},_resizeEndPane:function(c,e,f){var d=(f==a.SplitterDirection.Forward)?this.getEndPane():this.getStartPane();
return this._resizeTwoPanesWithDelta(c,[e,d],f);
},_resizeProportional:function(c,n,d){if(c==0||!n){return false;
}var l=[];
var m=0;
var k=this._getPanesByIndex();
var g=((d==a.SplitterDirection.Forward)?1:(-1));
for(var f=(n.get_indexInPanes()+g),h=k.length;
f<h&&f>=0;
f+=g){var j=k[f];
if(j._isCollapsed()||j._locked||(j.getVarMinSize()==j.getVarMaxSize())){continue;
}l[l.length]=j;
m+=j.getVarSize();
}if(l.length<2){return this._resizeAdjacentPane(c,n,d);
}var q=(!this._isCollapseMode&&!this._isExpandMode);
if(q){var e=new a.PaneResizingEventArgs(c,d);
n.raiseEvent("resizing",e);
if(e.get_cancel()){return false;
}}var p=n._width;
var o=n._height;
n.setVarSize(n.getVarSize()+c);
if(q){n.raiseEvent("resized",new a.PaneResizedEventArgs(p,o));
}this._resizeSetOfPanesProportional((-1)*c,l,m,d);
},_resizeSetOfPanesProportional:function(e,s,t,j){var o=[];
var d={};
var r=[];
do{var q=t;
var g=e;
for(var k=0,l=s.length;
k<l;
k++){if(r[k]){continue;
}var m=s[k];
var n=m.get_id();
var c=d[n];
var p=c?c:m.getVarSize();
var f=(l-r.length>1&&Math.abs(g)>1)?Math.floor(g*(p/q)):g;
var h=(f>0)?Math.min(f,m._getAvailIncreaseDelta(p)):Math.max(f,(-1)*m._getAvailDecreaseDelta(p));
if(h==0||f!=h){r[k]=true;
if(h==0){continue;
}}o[o.length]=m;
d[n]=(p+h);
e-=h;
t+=h;
if(e==0){break;
}}}while((e!=0)&&(r.length<s.length));
return this._fixRoundOffError(e,d,o,j);
},_setOuterWidth:function(d){if(this.isVertical()&&this._arePanesFixedSize()){d=this._getPanesVarSize()+this._getSplitBarsSize()+this._getBordersSize();
}if(this._width!=d){var c=this.get_element();
if(d<0||d==""){c.style.width="";
}else{c.style.width=d+"px";
}this._width=d;
}},_setOuterHeight:function(d){if(!this.isVertical()&&this._arePanesFixedSize()){d=this._getPanesVarSize()+this._getSplitBarsSize()+this._getBordersSize();
}if(this._height!=d){var c=this.get_element();
if(d<0||d==""){c.style.height="";
}else{c.style.height=d+"px";
}this._height=d;
}},_arePanesFixedSize:function(){var e=this.getPanes();
for(var c=0,d=e.length;
c<d;
c++){if(!e[c]._isInitialFixedSize()){return false;
}}return true;
},_containsFreeSizedPanes:function(){var e=this.getPanes();
for(var c=0,d=e.length;
c<d;
c++){if(e[c]._isFreeSize()){return true;
}}return false;
},_containsInitialFreeSizedPanes:function(){var e=this.getPanes();
for(var c=0,d=e.length;
c<d;
c++){if(e[c]._isInitialFreeSize()){return true;
}}return false;
},_containsInitialPercentSizedPanes:function(){var e=this.getPanes();
for(var c=0,d=e.length;
c<d;
c++){if(e[c]._isInitialPercentSize()){return true;
}}return false;
},_windowResizeHandler:function(){this._resizedValue++;
if(!this._cancelInterval){var c=this;
this._cancelInterval=window.setInterval(function(){try{if(c._resizedValue>c._lastResizedValue){c._lastResizedValue=c._resizedValue+1;
return;
}window.clearInterval(c._cancelInterval);
c._cancelInterval=0;
c._handlePageResize();
}catch(d){}},200);
}},_handlePageResize:function(f){if(!this._isVisible()){return;
}this._calculateInitialSize();
var i=$telerik.getViewPortSize();
var k=i.width;
var j=i.height;
if(!f&&this._initialWindowHeight==j&&this._initialWindowWidth==k){return;
}this._initialWindowHeight=j;
this._initialWindowWidth=k;
var h=null;
var d=null;
if(this._originalWidth.toString().indexOf("%")>-1){d=this._calculatePercentSize();
var e=d.width;
if(e!=this._width){h=e;
}}var g=null;
if(this._originalHeight.toString().indexOf("%")>-1){if(!d){d=this._calculatePercentSize();
}var c=d.height;
if(c!=this._height){g=c;
}}this.resize(h,g);
},_setSize:function(m,l){var g=this.isVertical();
if(this._arePanesFixedSize()){var j=this._getPanesVarSize()+this._getSplitBarsSize()+this._getBordersSize();
this[g?"_setOuterWidth":"_setOuterHeight"](j);
this[g?"_changeOriginalWidth":"_changeOriginalHeight"](j);
}var k=this.getPanes();
var d=null,f,h;
if(this._originalWidth.toString().indexOf("%")>-1||m){var e;
if(m){e=m;
}else{d=this._calculatePercentSize();
e=d.width;
}this._setOuterWidth(e);
if(!g){var o=this.getInnerWidth();
for(f=0,h=k.length;
f<h;
f++){k[f].set_width(o,true);
}}}if(this._originalHeight.toString().indexOf("%")>-1||l){var c;
if(l){c=l;
}else{if(!d){d=this._calculatePercentSize();
}c=d.height;
}this._setOuterHeight(c);
if(g){var n=this.getInnerHeight();
for(f=0,h=k.length;
f<h;
f++){k[f].set_height(n,true);
}}}},_fixSplitterActualSize:function(){if(this._originalHeight.toString().indexOf("%")==-1){return;
}var c=this.getContainerElement();
if(parseInt(c.style.height,10)==this._height){return;
}this._setOuterHeight(this._height);
},_calculatePercentSize:function(q,p){var o=this._originalWidth;
if(!q&&(o.toString().indexOf("%")>-1)){q=o;
}var n=this._originalHeight;
if(!p&&(n.toString().indexOf("%")>-1)){p=n;
}var f=this.get_element();
if(q&&f.style.width!=q){f.style.width=q;
}if(p&&f.style.height!=p){f.style.height=p;
}var r=this._containerElement;
var h=$telerik.isIE?!Sys.UI.DomElement.containsCssClass(r,"rspHideRadSplitter"):false;
var g=$telerik.getFirstChildByTagName(f,"div",0);
if(g){g.style.width="1px";
g.style.height="1px";
}else{if(h){Sys.UI.DomElement.addCssClass(r,"rspHideRadSplitter");
r.style.position="";
}}var m=this._heightOffset;
var c=f.offsetHeight-m;
var e=$telerik.isOpera;
if(e||(m>0)){f.style.height="";
}var d=f.offsetWidth;
if(g){g.style.width="";
g.style.height="";
}else{if(h){Sys.UI.DomElement.removeCssClass(r,"rspHideRadSplitter");
r.style.position="static";
}}if(e){f.style.width="";
}if($telerik.isIE&&document.forms&&document.forms.length>0){document.forms[0].style.cssText=document.forms[0].style.cssText;
}if(d<=0){d=400;
}if(c<=0){c=400;
}if(this.isVertical()){var l=this.getMinWidth();
var j=this.getMaxWidth();
d=Math.min(j,Math.max(l,d));
}else{var k=this.getMinHeight();
var i=this.getMaxHeight();
c=Math.min(i,Math.max(k,c));
}return{width:d,height:c};
},_fixRoundOffError:function(s,c,p,h,j){if(!p){return s;
}var u=(h!=null);
var r={},k,l,t;
var q=p.length;
for(k=0;
k<q;
k++){var f=s;
l=p[k];
var m=l.get_id();
t=c[l.get_id()];
if(s!=0){var e=(s>0)?Math.min(s,l._getAvailIncreaseDelta(t)):Math.max(s,(-1)*l._getAvailDecreaseDelta(t));
if(e!=0){t+=e;
s-=e;
}}r[m]=t;
if(u){var g=new a.PaneResizingEventArgs((t-l.getVarSize()),h);
l.raiseEvent("resizing",g);
if(g.get_cancel()){r[m]=-1;
s=f;
continue;
}}}for(k=0;
k<q;
k++){l=p[k];
t=r[l.get_id()];
if(t==-1){continue;
}var o=l._width;
var n=l._height;
l.setVarSize(t,true);
if(u||j){var d=l._getChildSplitter();
if(null!=d){d.resize(l.getInnerWidth(),l.getInnerHeight());
}else{$telerik.repaintChildren(l);
}if(u){l.raiseEvent("resized",new a.PaneResizedEventArgs(o,n));
}}}return s;
},_setPanesSize:function(){var o=this.getPanes();
var l=this.isVertical();
var p=l?this._getPanesAvailWidth():this._getPanesAvailHeight();
if(p<0){p=0;
}var e=0;
var j=0;
var t=0;
var h=[];
var s=[];
var r={},k;
for(k=o.length-1;
k>=0;
k--){var n=o[k];
if(n._isCollapsed()){continue;
}if(!n._collapsed&&n._expandedSize>0){continue;
}if(n._isPercentSize()){s[s.length]=n;
var m=l?n._originalWidth:n._originalHeight;
var q=parseInt(parseInt(m,10)*p/100,10);
r[n.get_id()]=q;
t+=q;
}else{if(n._isFixedSize()){var d=n._getChildSplitter();
if(null!=d){d.resize(n.getInnerWidth(),n.getInnerHeight());
}$telerik.repaintChildren(n);
e+=n.getVarSize();
}else{h[h.length]=n;
}}}var f=h.length;
if(f>0){var c=p-t-e;
var v=parseInt(c/f,10);
if(v<0){v=0;
}j=v*f;
for(k=0;
k<f;
k++){var g=h[k];
r[g.get_id()]=v;
}}var u=p-t-e-j;
if(u<0){u=0;
}this._fixRoundOffError(u,r,h.concat(s),null,true);
this._doInitialExpand();
this._doInitialCollapse();
},_doInitialExpand:function(){var f=this.getPanes();
for(var c=0,d=f.length;
c<d;
c++){var e=f[c];
if(!e._collapsed&&e._expandedSize>0){e._doInitialExpand();
}}},_doInitialCollapse:function(){var f=this.getPanes();
for(var c=0,d=f.length;
c<d;
c++){var e=f[c];
if(e._collapsed){e._doInitialCollapse();
}}},_endLoadSlidingZones:function(){var f=this.getPanes();
for(var c=0,d=f.length;
c<d;
c++){var e=f[c];
var g=e._getChildSlidingZone();
if(g){g._splitterLoadHandler();
}}},_getPanesVarSize:function(){var e=this.getPanes();
var f=0;
for(var c=0,d=e.length;
c<d;
c++){var g=e[c].getVarSize();
if(g==""){g=0;
}f+=g;
}return f;
},_getPanesAvailWidth:function(){var c=this.getInnerWidth();
if(this.isVertical()){c-=(this._getItemsBorderSize()+this._getSplitBarsSize());
}return c;
},_getPanesAvailHeight:function(){var c=this.getInnerHeight();
if(!this.isVertical()){c-=(this._getItemsBorderSize()+this._getSplitBarsSize());
}return c;
},_getSplitterBordersSize:function(){var c=2*this._borderSize;
if(this.isNested()){c=0;
}return c;
},_getItemsBorderSize:function(){var g=this.getPanes();
var c=0;
for(var d=0,f=g.length;
d<f;
d++){if(!g[d]._isCollapsed()){c++;
}}var e=Math.max(c+this.getSplitBars().length-1,0);
return(e*this._borderSize);
},_getBordersSize:function(){return(this._getItemsBorderSize()+this._getSplitterBordersSize());
},_getSplitBarsSize:function(){if(!this._isVisible()){return 0;
}if(this._splitBarsSizeCalculated){return this._splitBarsSize;
}var i=this.getSplitBars().length;
var k=0;
if(i>0){var f=0;
var j=this._splitBarSize;
var d=(this._borderSize==0);
if(j!=null){f=parseInt(j,10);
if(d){f+=2;
}}else{var g=this.getSplitBarByIndex(0);
var h=g.get_element();
var c=null;
if(d){c=h;
}else{c=$telerik.getFirstChildByTagName(h,"input");
}if(c){var e=$telerik.getOuterSize(c);
f=(this.isVertical())?e.width:e.height;
}f=Math.max(f,0);
}k=i*f;
}this._splitBarsSizeCalculated=true;
this._splitBarsSize=k;
return k;
},_getAvailAdjacentPane:function(g,f){if((this.getPanes().length-1)==g){f=a.SplitterDirection.Backward;
}else{if(g==0){f=a.SplitterDirection.Forward;
}}var e=(f==a.SplitterDirection.Forward)?1:-1;
var d=g+e;
var c=null;
var h=this._getPanesByIndex();
do{c=h[d];
if(c==null){return null;
}d+=e;
}while(c._isCollapsed()||c._locked||(c.getVarMinSize()==c.getVarMaxSize()));
return c;
},_getAvailIncreaseDelta:function(k,e){var j=0,g,h;
switch(this._resizeMode){case a.SplitterResizeMode.EndPane:var f=(e==a.SplitterDirection.Forward)?this.getEndPane():this.getStartPane();
j=f._getAvailIncreaseDelta();
break;
case a.SplitterResizeMode.Proportional:var l=this._getPanesByIndex();
var d=[];
if(e==a.SplitterDirection.Forward){for(g=k+1,h=this._panes.length;
g<h;
g++){d[d.length]=l[g];
}}else{for(g=k-1;
g>=0;
g--){d[d.length]=l[g];
}}for(g=0,h=d.length;
g<h;
g++){j+=d[g]._getAvailIncreaseDelta();
}break;
case a.SplitterResizeMode.AdjacentPane:default:var c=this._getAvailAdjacentPane(k,e);
if(c==null){return 0;
}j+=c._getAvailIncreaseDelta();
}j=Math.max(j,0);
return j;
},_getAvailDecreaseDelta:function(k,e){var j=0,g,h;
switch(this._resizeMode){case a.SplitterResizeMode.EndPane:var f=(e==a.SplitterDirection.Forward)?this.getEndPane():this.getStartPane();
j=f._getAvailDecreaseDelta();
break;
case a.SplitterResizeMode.Proportional:var d=[];
var l=this._getPanesByIndex();
if(e==a.SplitterDirection.Forward){for(g=k+1,h=this._panes.length;
g<h;
g++){d[d.length]=l[g];
}}else{for(g=k-1;
g>=0;
g--){d[d.length]=l[g];
}}for(g=0,h=d.length;
g<h;
g++){j+=d[g]._getAvailDecreaseDelta();
}break;
case a.SplitterResizeMode.AdjacentPane:default:var c=this._getAvailAdjacentPane(k,e);
if(c==null){return 0;
}j=c._getAvailDecreaseDelta();
}j=Math.max(j,0);
return j;
},_collapsePane:function(g,d){var f=g._initialCollapseMode;
if(!f){var e=new Sys.CancelEventArgs();
g.raiseEvent("collapsing",e);
if(e.get_cancel()){return false;
}}this._isCollapseMode=true;
if(typeof(d)=="undefined"){d=a.SplitterDirection.Forward;
}var c=this._getAvailIncreaseDelta(g.get_indexInPanes(),d);
if(c<g.getVarSize()){this._isCollapseMode=false;
return false;
}g._collapse(d);
if(!f){g.raiseEvent("collapsed",new Sys.EventArgs());
}this._isCollapseMode=false;
return true;
},_expandPane:function(i,e){var g=i._initialExpandMode;
if(!g){var f=new Sys.CancelEventArgs();
i.raiseEvent("expanding",f);
if(f.get_cancel()){return false;
}}this._isExpandMode=true;
if(typeof(e)=="undefined"){e=a.SplitterDirection.Forward;
}var c=this._getAvailDecreaseDelta(i.get_indexInPanes(),e);
if(c<=0){this._isExpandMode=false;
return false;
}var h=i.getVarMinSize();
if(h>c){this._isExpandMode=false;
return false;
}var d=Math.min(c,i._expandedSize);
i._expand(d,e);
if(!g){i.raiseEvent("expanded",new Sys.EventArgs());
}this._isExpandMode=false;
return true;
},_resizePanes:function(c,e,d){if(typeof(d)=="undefined"){d=a.SplitterDirection.Forward;
}switch(this._resizeMode){case a.SplitterResizeMode.EndPane:this._resizeEndPane(c,e,d);
break;
case a.SplitterResizeMode.Proportional:this._resizeProportional(c,e,d);
break;
case a.SplitterResizeMode.AdjacentPane:default:this._resizeAdjacentPane(c,e,d);
}},_changeOriginalWidth:function(c){this._originalWidth=c;
},_changeOriginalHeight:function(c){this._originalHeight=c;
},_getMinMaxSize:function(n,d,h,j){var m=this.getPanes().length;
if(!n){n=0;
}if(!d){d=m;
}n=Math.max(0,n);
d=Math.min(d,m);
var f=(j)?"get_width":"get_height";
var e=(h)?"get_min":"get_max";
e+=(j)?"Width":"Height";
var l=this._getPanesByIndex();
var c=this._getSplitBarsSize()+this._getBordersSize();
for(var g=n;
g<d;
g++){var k=l[g];
c+=(k._locked)?k[f]():k[e]();
}return c;
},_getDragOverlay:function(){var c=this._dragOverlay;
if(!c){c=this._dragOverlay=document.createElement("div");
c.style.display="none";
c.style.position="absolute";
c.style.backgroundColor="#fff";
c.style.filter="alpha(opacity=0)";
c.style.opacity=0;
document.body.insertBefore(c,document.body.firstChild);
}return c;
},_isVisible:function(){return(this.getContainerElement().offsetWidth!=0);
},_appLoadHandler:function(){if(this._appLoadDelegate){Sys.Application.remove_load(this._appLoadDelegate);
this._appLoadDelegate=null;
}var c=this.isNested();
var f=!c;
if(c){var d=this.get_parent();
if(d&&d._initializedInternal){var e=d.get_splitter();
f=(e&&e._initializedInternal);
}}if(f){this._calculateInitialSize();
}},repaint:function(){var c=this;
var d=function(){if(!c._isVisible()||c.isNested()){return;
}c._handlePageResize(true);
};
window.setTimeout(d,10);
},_calculateInitialSize:function(e,d){if(this._initializedInternal){return;
}if(!this._isVisible()){return;
}this._setSize(e,d);
this._setPanesSize();
this._fixSplitterActualSize();
if(!this._visibleDuringInit){var c=this.getContainerElement();
Sys.UI.DomElement.removeCssClass(c,"rspHideRadSplitter");
if($telerik.isIE){c.style.position="static";
}}this._endLoadSlidingZones();
this._initializedInternal=true;
if(this._load){this.add_load(eval(this._load));
}this.raiseEvent("load");
}};
a.RadSplitter._preInitialize=function(c){a.RadSplitterController.getInstance()._addSplitter(c);
};
a.RadSplitter.registerClass("Telerik.Web.UI.RadSplitter",a.RadWebControl);
a.RadSplitterControllerClass=function(){this._splitters={};
this._panes={};
this._splitBars={};
this._slidingZones={};
this._slidingPanes={};
};
a.RadSplitterControllerClass.prototype={_addSplitter:function(c){if(this._splitters[c]){return;
}this._splitters[c]={};
},_removeSplitter:function(d){var c=this._splitters[d];
if(c){delete c.panes;
delete c.splitbars;
c=null;
delete this._splitters[d];
}},_addPane:function(g,i,h,f,c,d,e){if(this._panes[g]){return;
}this._panes[g]={splitterId:i,prevSplitBarId:h,nextSplitBarId:f,index:c,indexInPanes:d,isLastPane:b(e)};
var j=this._splitters[i].panes;
if(!j){j=[];
}j[j.length]=g;
this._splitters[i].panes=j;
},_removePane:function(c){delete this._panes[c];
},_addSplitBar:function(g,h,f,e,c,d){if(this._splitBars[g]){return;
}this._splitBars[g]={splitterId:h,prevPaneId:f,nextPaneId:e,index:c,indexInSplitBars:d};
var i=this._splitters[h].splitbars;
if(!i){i=[];
}i[i.length]=g;
this._splitters[h].splitbars=i;
},_removeSplitBar:function(c){delete this._splitBars[c];
},_addSlidingZone:function(d,e,c){if(this._slidingZones[d]){return;
}this._slidingZones[d]={splitterId:e,parentPaneId:c};
},_removeSlidingZone:function(d){var c=this._slidingZones[d];
if(c){delete c.slidingPanes;
c=null;
}delete this._slidingZones[d];
},_addSlidingPane:function(e,g,h,d,c){if(this._slidingPanes[e]){return;
}this._slidingPanes[e]={splitterId:g,zoneId:h,parentPaneId:d,index:c};
var f=this._slidingZones[h].slidingPanes;
if(!f){f=[];
}f[f.length]=e;
this._slidingZones[h].slidingPanes=f;
},_removeSlidingPane:function(c){delete this._slidingPanes[c];
},_getSplitter:function(d){if(d){var c=this._panes[d];
if(!c){c=this._splitBars[d];
}if(!c){c=this._slidingPanes[d];
}if(!c){c=this._slidingZones[d];
}if(c){return $find(c.splitterId);
}}return null;
},_getSlidingZone:function(d){if(d){var c=this._slidingPanes[d];
if(c){return $find(c.zoneId);
}}return null;
},_getParentPane:function(d){if(d){var c=this._slidingZones[d];
if(!c){c=this._slidingPanes[d];
}if(c){return $find(c.parentPaneId);
}}return null;
},_getIndex:function(d){if(d){var c=this._panes[d];
if(!c){c=this._splitBars[d];
}if(!c){c=this._slidingPanes[d];
}if(c){return c.index;
}}return null;
},_getPanePrevSplitBar:function(c){var d=this._panes[c].prevSplitBarId;
return((d&&d!="")?$find(d):null);
},_getPaneNextSplitBar:function(d){var c=this._panes[d].nextSplitBarId;
return((c&&c!="")?$find(c):null);
},_getSplitBarPrevPane:function(d){var c=this._splitBars[d].prevPaneId;
return((c&&c!="")?$find(c):null);
},_getSplitBarNextPane:function(d){var c=this._splitBars[d].nextPaneId;
return((c&&c!="")?$find(c):null);
},_getPanes:function(g){var f=[];
var e=this._splitters[g].panes;
if(e){for(var c=0,d=e.length;
c<d;
c++){f[f.length]=$find(e[c]);
}}return f;
},_getSplitBars:function(g){var f=[];
var e=this._splitters[g].splitbars;
if(e){for(var c=0,d=e.length;
c<d;
c++){f[f.length]=$find(e[c]);
}}return f;
},_getSlidingPanes:function(g){var f=[];
var e=this._slidingZones[g].slidingPanes;
if(e){for(var c=0,d=e.length;
c<d;
c++){f[f.length]=$find(e[c]);
}}return f;
},_getIndexInPanes:function(c){return this._panes[c].indexInPanes;
},_isLastPane:function(c){return this._panes[c].isLastPane;
},_getIndexInSplitBars:function(c){return this._splitBars[c].indexInSplitBars;
},_resetLastItemClass:function(s,l){var d=s?s:(l?this._panes[l].splitterId:null);
if(!d){return;
}var r=this._splitters[d];
var q=this._splitBars;
var g,c;
var p=r.splitbars;
if(p){for(c=p.length-1;
c>=0;
c--){var o=p[c];
var n=$get(o);
if(n){Sys.UI.DomElement.removeCssClass(n,"rspLastItem");
}if(!g||(o&&(q[g].index<q[o].index))){g=o;
}}}var m=this._panes;
var f;
var k=r.panes;
if(k){for(c=k.length-1;
c>=0;
c--){var j=k[c];
var h=$get(j);
if(h){Sys.UI.DomElement.removeCssClass(h,"rspLastItem");
}if(!f||(j&&(m[f].index<m[j].index))){f=j;
}}}var e=$get(f);
if(!e||(g&&m[f].index<q[g].index)){e=$get(g);
}if(e){Sys.UI.DomElement.addCssClass(e,"rspLastItem");
}},_ensureItemsOrder:function(u,c){this._fixItemsIndeces(u);
if(c){var t=this._splitters[u];
var l=this._panes;
var k=t.panes;
var m=k?k.length:0;
var q=t.splitbars;
var s=q?q.length:0;
var e=m+s;
var f=[],d,n;
for(d=m-1;
d>=0;
d--){var j=k[d];
f[f.length]=j;
var h=l[j];
h.indexInPanes=m-1-h.indexInPanes;
h.index=(e-1-h.index);
h.isLastPane=false;
n=h.prevSplitBarId;
h.prevSplitBarId=h.nextSplitBarId;
h.nextSplitBarId=n;
}t.panes=f;
var r=this._splitBars;
var g=[];
for(d=s-1;
d>=0;
d--){var p=q[d];
g[g.length]=p;
var o=r[p];
o.indexInSplitBars=s-1-o.indexInSplitBars;
o.index=(e-1-o.index);
n=o.prevPaneId;
o.prevPaneId=o.nextPaneId;
o.nextPaneId=n;
}t.splitbars=g;
this._resetLastItemClass(u);
}},_fixItemsIndeces:function(t){var s=this._splitters[t];
var j=s.panes;
var m=j?j.length:0;
var o=s.splitbars;
var r=o?o.length:0;
var l=this._panes;
var f=[];
var g=0,c,d;
if(l&&j){for(c=0;
c<m;
c++){var h=l[j[c]];
d=h.index;
f[d]=h;
if(g<d){g=d;
}}}var q=this._splitBars;
if(q&&o){for(c=0;
c<r;
c++){var n=q[o[c]];
d=n.index;
f[d]=n;
if(g<d){g=d;
}}}if((m+r-1)<g){d=0;
var k=0;
var p=0;
for(c=0;
c<=g;
c++){var e=f[c];
if(e){e.index=d;
d++;
if(typeof(e.indexInPanes)!="undefined"){e.indexInPanes=k;
k++;
}else{e.indexInSplitBars=p;
p++;
}}}}},getInstance:function(){return this;
}};
a.RadSplitterControllerClass.registerClass("Telerik.Web.UI.RadSplitterControllerClass",null);
function b(c){if(c.toLowerCase){c=c.toLowerCase();
}return(c!=="false")&&!!c;
}if(!a.RadSplitterController){a.RadSplitterController=new a.RadSplitterControllerClass();
}})();
Type.registerNamespace("Telerik.Web.UI");
(function(){$telerik.toPane=function(b){return b;
};
$telerik.findPane=$find;
var a=Telerik.Web.UI;
a.RadPane=function(b){a.RadPane.initializeBase(this,[b]);
this._originalWidth=null;
this._originalHeight=null;
this._expandedSize=0;
this._indexInPanes=null;
this._isLast=null;
this._prevSplitBar=null;
this._nextSplitBar=null;
this._childSplitterId="";
this._childSlidingZoneId="";
this._locked=false;
this._contentUrl="";
this._showContentDuringLoad=true;
this._onIframeLoadDelegate=null;
this._collapsedDirection=a.SplitterDirection.Forward;
this._contentElement=$get("RAD_SPLITTER_PANE_CONTENT_"+this.get_id());
this.Resize=this.resize;
this.Print=this.print;
this.Collapse=this.collapse;
this.Expand=this.expand;
this.IsExternalContent=this.isExternalContent;
this.GetInnerWidth=this.getInnerWidth;
this.GetInnerHeight=this.getInnerHeight;
this.IsSplitterContainer=this.isSplitterContainer;
this.GetContentElement=this.getContentElement;
this.GetExtContentElement=this.getExtContentElement;
this.IsLocked=this.isLocked;
this.Lock=this.lock;
this.UnLock=this.unlock;
};
a.RadPane.prototype={initialize:function(){a.RadPane.callBaseMethod(this,"initialize");
if(this._isSplitterVertical()){this._getOrigVarSize=this._getOrigWidth;
this._setOrigVarSize=this._setOrigWidth;
this._getAvailIncreaseDelta=this._getWidthAvailIncreaseDelta;
this._getAvailDecreaseDelta=this._getWidthAvailDecreaseDelta;
}else{this._getOrigVarSize=this._getOrigHeight;
this._setOrigVarSize=this._setOrigHeight;
this._getAvailIncreaseDelta=this._getHeightAvailIncreaseDelta;
this._getAvailDecreaseDelta=this._getHeightAvailDecreaseDelta;
}if(this.isExternalContent()){this._setExternalContent(this._contentUrl);
}else{if(this._scrollingEnabled){if(a.TouchScrollExtender._getNeedsScrollExtender()&&!this._dropDownTouchScroll){this._createTouchScrollExtender(true);
}this._initializeScrollPosition();
}}this.updateClientState();
this._initializedInternal=true;
},_initializeScrollPosition:function(){if(this._persistScrollPosition){if(this._dropDownTouchScroll){this._onScrollDelegate=Function.createDelegate(this,this._onScroll);
this._dropDownTouchScroll.add_scrollEnded(this._onScrollDelegate);
}else{this._attachScrollHandler(true);
}this.setScrollPos(this._scrollLeft,this._scrollTop);
}},dispose:function(){this._attachScrollHandler(false);
if(this._onScrollDelegate){this._dropDownTouchScroll.remove_scrollEnded(this._onScrollDelegate);
}this._createTouchScrollExtender(false);
this._registerIframeLoadHandler(false);
this._prevSplitBar=null;
this._nextSplitBar=null;
this._contentElement=null;
a.RadSplitterController.getInstance()._removePane(this.get_id());
a.RadPane.callBaseMethod(this,"dispose");
},_registerIframeLoadHandler:function(b){var c=this._extContentElement;
if(!c){return;
}if(b){this._onIframeLoadDelegate=Function.createDelegate(this,this._onIframeLoad);
$addHandler(c,"load",this._onIframeLoadDelegate);
}else{if(this._onIframeLoadDelegate){$removeHandler(c,"load",this._onIframeLoadDelegate);
this._onIframeLoadDelegate=null;
$clearHandlers(c);
}}},_onIframeLoad:function(){this._showLoadingSign(false);
},_showLoadingSign:function(e){var b=this._extContentElement;
if(!b){return;
}var d=b.style;
var c=b.parentNode;
if(!c){return;
}if(e){d.position="absolute";
d.top="-10000px";
Sys.UI.DomElement.addCssClass(c,"rspLoading");
}else{b.style.position="";
Sys.UI.DomElement.removeCssClass(c,"rspLoading");
}},set_content:function(b){if(this.isExternalContent()){Sys.UI.DomElement.removeCssClass(this._contentElement,"rspIOSScrollFixer");
this._contentElement.style.overflow=this._contentOverflow.overflow;
this._contentElement.style.overflowX=this._contentOverflow.overflowX;
this._contentElement.style.overflowY=this._contentOverflow.overflowY;
this._contentUrl=null;
this.updateClientState();
}this._contentElement.innerHTML=b;
},get_content:function(){if(this.isExternalContent()){return"";
}return this._contentElement.innerHTML;
},set_contentUrl:function(b){this._contentUrl=b;
if(this._initializedInternal){this._setExternalContent(b);
}this.updateClientState();
},get_contentUrl:function(){if(!this.isExternalContent()){return"";
}return this._contentUrl;
},get_showContentDuringLoad:function(){return this._showContentDuringLoad;
},set_showContentDuringLoad:function(b){this._showContentDuringLoad=b;
if(!this._extContentElement){return;
}if(!b){this._registerIframeLoadHandler(false);
}else{if(!this._onIframeLoadDelegate){this._registerIframeLoadHandler(true);
}}},get_minWidth:function(){var d=this._minWidth;
var b=0;
var c=this._getChildSplitter();
if((null!=c)&&c.isVertical()){b=c.getMinWidth();
}return Math.max(d,b);
},get_minHeight:function(){var d=this._minHeight;
var b=0;
var c=this._getChildSplitter();
if((null!=c)&&!c.isVertical()){b=c.getMinHeight();
}return Math.max(d,b);
},get_maxWidth:function(){var b=this._getMaxSize(true);
return b;
},get_maxHeight:function(){var b=this._getMaxSize(false);
return b;
},set_width:function(g,e,d){var c=this._contentElement;
if(!c){return;
}var f=(g>=0&&g!==this._width);
if(f){this._setWidth(g);
}if(d||(f&&!e&&(c.style.display!="none"))){var b=this._getChildSplitter();
if(null!=b){b.set_width(this.getInnerWidth());
}else{$telerik.repaintChildren(this);
}}},set_height:function(g,e,d){var c=this._contentElement;
if(!c){return;
}var f=(g>=0&&g!==this._height);
if(f){this._setHeight(g);
}if(d||(f&&!e&&(c.style.display!="none"))){var b=this._getChildSplitter();
if(null!=b){b.set_height(this.getInnerHeight());
}else{$telerik.repaintChildren(this);
}}},get_locked:function(){return this._locked;
},set_locked:function(b){this._locked=b;
},resize:function(b,c){this.get_splitter()._resizePanes(b,this,c);
},print:function(b){var k="width="+this.get_width()+"px, height="+this.get_height()+"px, scrollbars=1";
var j=(this.isExternalContent())?this.get_contentUrl():"about:blank";
var h=window.open(j,"",k,false);
if(this.isExternalContent()){try{var m=function(){h.print();
};
setTimeout(m,1000);
}catch(c){}return;
}var l="";
if(b){l="<head>";
for(var d=0,f=b.length;
d<f;
d++){l+="<link href = '"+b[d]+"' rel='stylesheet' type='text/css'></link>";
}l+="</head>";
}var g=l+"<body>"+this.get_content()+"</body>";
h.document.open();
h.document.write(g);
h.document.close();
h.print();
},collapse:function(c){if(this.get_collapsed()){return true;
}if(!c){c=a.SplitterDirection.Forward;
}var e=this._getTargetSplitBar(c);
var d=false;
if(e!=null){var b=a.SplitterDirection.Forward;
if(e.get_index()<this.get_index()){b=a.SplitterDirection.Backward;
}d=e._collapseTargetPane(b);
}else{d=this.get_splitter()._collapsePane(this,c);
}return d;
},expand:function(b){if(!this.get_collapsed()){return true;
}if(!b){b=a.SplitterDirection.Forward;
}var e=this._getTargetSplitBar(b);
var d=false;
if(e!=null){var c=a.SplitterDirection.Forward;
if(e.get_index()<this.get_index()){c=a.SplitterDirection.Backward;
}d=e._collapseTargetPane(c);
}else{d=this.get_splitter()._expandPane(this,b);
}return d;
},isExternalContent:function(){return(this._contentUrl!=null&&this._contentUrl!="");
},getInnerWidth:function(){return parseInt(this._width,10);
},getInnerHeight:function(){return parseInt(this._height,10);
},_getChildSlidingZone:function(){var b=this._childSlidingZoneId;
if(b!=""){return $find(b);
}return null;
},_getChildSplitter:function(){var b=this._childSplitterId;
if(b!=""){return $find(b);
}return null;
},isSplitterContainer:function(){return(null!=this._getChildSplitter());
},getContentElement:function(){return this._contentElement;
},getExtContentElement:function(){return this._extContentElement;
},isLocked:function(){return this._locked;
},lock:function(){this.set_locked(true);
this.updateClientState();
},unlock:function(){this.set_locked(false);
},_isLastPane:function(){var b=this._isLast;
if(b==null){b=this._isLast=a.RadSplitterController.getInstance()._isLastPane(this.get_id());
}return b;
},_isFixedSize:function(){return(!this._isFreeSize()&&!this._isPercentSize());
},_isInitialFixedSize:function(){return(!this._isInitialFreeSize()&&!this._isInitialPercentSize());
},_isFreeSize:function(){return(this.getVarSize()=="");
},_isInitialFreeSize:function(){return(this._getOrigVarSize()=="");
},_isPercentSize:function(){return(this.getVarSize().toString().indexOf("%")>-1);
},_isInitialPercentSize:function(){return(this._getOrigVarSize().toString().indexOf("%")>-1);
},_getWidthAvailDecreaseDelta:function(b){if(this._isCollapsed()||this.isLocked()){return 0;
}return((b?b:this.get_width())-this.get_minWidth());
},_getWidthAvailIncreaseDelta:function(b){if(this._isCollapsed()||this.isLocked()){return 0;
}return(this.get_maxWidth()-(b?b:this.get_width()));
},_getHeightAvailDecreaseDelta:function(b){if(this._isCollapsed()||this.isLocked()){return 0;
}return((b?b:this.get_height())-this.get_minHeight());
},_getHeightAvailIncreaseDelta:function(b){if(this._isCollapsed()||this.isLocked()){return 0;
}return(this.get_maxHeight()-(b?b:this.get_height()));
},_setHeight:function(b){this._setSize(null,b);
},_setWidth:function(b){this._setSize(b);
},get_indexInPanes:function(){var b=this._indexInPanes;
if(null==b){b=this._indexInPanes=a.RadSplitterController.getInstance()._getIndexInPanes(this.get_id());
}return b;
},_getPrevSplitBar:function(){var b=this._prevSplitBar;
if(!b){b=this._prevSplitBar=a.RadSplitterController.getInstance()._getPanePrevSplitBar(this.get_id());
}return b;
},_getNextSplitBar:function(){var b=this._nextSplitBar;
if(!b){b=this._nextSplitBar=a.RadSplitterController.getInstance()._getPaneNextSplitBar(this.get_id());
}return b;
},_setSize:function(i,d){var e="";
var h=null;
var f="";
var c="";
if(i!=null){if(d!=null){this._setSize(null,d);
}h=i;
e="_width";
f="_setOuterWidth";
c="getInnerWidth";
}else{if(d!=null){h=d;
e="_height";
f="_setOuterHeight";
c="getInnerHeight";
}}if(h==null){return;
}h=parseInt(h,10);
if(isNaN(h)||h===this[e]){return;
}h=Math.max(h,0);
this[e]=h;
if($telerik.isOpera){var g=this.get_splitter().getContainerElement();
g.style.width="1px";
g.style.height="1px";
}if(this._contentElement!=null){this[f](this._contentElement,this[c]());
if(this.isExternalContent()){var b=this._extContentElement;
if(b){this[f](b,this[c]());
}}}this.updateClientState();
},_getOrigWidth:function(){return this._originalWidth;
},_getOrigHeight:function(){return this._originalHeight;
},_setOrigWidth:function(b){this._originalWidth=b;
},_setOrigHeight:function(b){this._originalHeight=b;
},_isCollapsed:function(){return(this.get_collapsed()&&this._expandedSize>0);
},_doInitialCollapse:function(){this._initialCollapseMode=true;
this._collapsed=false;
var b=this._isLastPane()?a.SplitterDirection.Backward:this._collapsedDirection;
this.collapse(b);
this._initialCollapseMode=false;
},_doInitialExpand:function(){this._initialExpandMode=true;
this._collapsed=true;
var b=this._isLastPane()?a.SplitterDirection.Backward:a.SplitterDirection.Forward;
this.expand(b);
this._initialExpandMode=false;
},_getWrapperElement:function(){return(this._isSplitterVertical()?this.get_element():$get("RAD_SPLITTER_PANE_TR_"+this.get_id()));
},_show:function(){this._contentElement.style.display="";
this._getWrapperElement().style.display="";
},_hide:function(){this._contentElement.style.display="none";
this._getWrapperElement().style.display="none";
},_collapse:function(b){var c=(this._expandedSize>0);
var e=this.getVarSize();
if(e>0){this._expandedSize=e;
}this._hide();
var d=this.get_splitter();
if(!c){this.resize((-1)*(e+d._borderSize),b);
}this[this._isSplitterVertical()?"_width":"_height"]=0;
a.RadSplitterController.getInstance()._resetLastItemClass(null,this.get_id());
this._collapsedDirection=b;
this._collapsed=true;
this.updateClientState();
},_expand:function(c,b){var d=this.get_splitter();
this.resize(c+d._borderSize,b);
this._show();
if(this._isSplitterVertical()){this.set_height(d.getInnerHeight());
}else{this.set_width(d.getInnerWidth());
}this.setVarSize(c,null,true);
a.RadSplitterController.getInstance()._resetLastItemClass(null,this.get_id());
this._collapsed=false;
this._expandedSize=0;
this.updateClientState();
},_getTargetSplitBar:function(b){if(!b){b=a.SplitterDirection.Forward;
}var c=this._getNextSplitBar();
var d=this._getPrevSplitBar();
var e=(b==a.SplitterDirection.Forward)?c:d;
if(e&&e.isCollapseDirectionEnabled(b)){return e;
}b=(b==a.SplitterDirection.Forward)?a.SplitterDirection.Backward:a.SplitterDirection.Forward;
e=(b==a.SplitterDirection.Forward)?c:d;
if(e&&e.isCollapseDirectionEnabled(b)){return e;
}return null;
},_setExternalContent:function(g){if(!this._extContentElement){var f=(this._scrollingEnabled)?"auto":"no";
var c=(!document.all)?"-3px;":null;
var b=($telerik.isIE&&!$telerik.isIE9Mode)?document.createElement("<iframe name='"+this.get_id()+"'>"):document.createElement("iframe");
b.name=this.get_id();
b.id="RAD_SPLITTER_PANE_EXT_CONTENT_"+this.get_id();
b.src=g;
b.style.border="0px";
b.frameBorder="0";
b.setAttribute("scrolling",f);
if(c){b.marginBottom=c;
}this._contentElement.innerHTML="";
this._contentElement.appendChild(b);
var e=this.getInnerWidth();
if(e&&!isNaN(e)){this._setOuterWidth(b,e);
}var d=this.getInnerHeight();
if(d&&!isNaN(d)){this._setOuterHeight(b,d);
}this._extContentElement=b;
this._contentOverflow={overflow:this._contentElement.style.overflow,overflowX:this._contentElement.style.overflowX,overflowY:this._contentElement.style.overflowY};
if($telerik.isMobileSafari){Sys.UI.DomElement.addCssClass(this._contentElement,"rspIOSScrollFixer");
}else{this._contentElement.style.overflow="hidden";
this._contentElement.style.overflowX="hidden";
this._contentElement.style.overflowY="hidden";
}if(!this.get_showContentDuringLoad()){this._registerIframeLoadHandler(true);
}}else{this._extContentElement.src=g;
}if(!this.get_showContentDuringLoad()){this._showLoadingSign(true);
}},_getMaxSize:function(d){var e=(d)?this._maxWidth:this._maxHeight;
var b=0;
var c=this._getChildSplitter();
if(null!=c){var f=false;
if(d&&!c.isVertical()||!d&&c.isVertical()){f=true;
}if(!f){b=(d)?c.getMaxWidth():c.getMaxHeight();
if(b!=null){if(e!=null){e=Math.min(e,b);
}else{e=b;
}}}}return e;
},_initResize:function(){this._oldWidth=this._width;
this._oldHeight=this._height;
},_endResize:function(e){var d=this._oldWidth;
var c=this._oldHeight;
if((d!=null&&d!=this._width)||(c!=null&&c!=this._height)){d=(d!=null)?d:this._width;
c=(c!=null)?c:this._height;
var b=this._getChildSplitter();
if(null!=b){b.resize(this.getInnerWidth(),this.getInnerHeight());
}else{$telerik.repaintChildren(this);
}if(e){this.raiseEvent("resized",new a.PaneResizedEventArgs(d,c));
}this._oldWidth=null;
this._oldHeight=null;
}},saveClientState:function(){if(this.get_isUpdating()){return null;
}var f=this.getScrollPos();
var g={_originalWidth:this._originalWidth,_originalHeight:this._originalHeight,_collapsedDirection:this._collapsedDirection,_scrollLeft:f.left,_scrollTop:f.top,_expandedSize:this._expandedSize};
var d=["width","height","collapsed","contentUrl","minWidth","maxWidth","minHeight","maxHeight","locked"];
for(var b=0,c=d.length;
b<c;
b++){var e=d[b];
g[e]=this["get_"+e]();
}return Sys.Serialization.JavaScriptSerializer.serialize(g);
}};
a.RadPane._preInitialize=function(f,h,g,e,b,c,d){a.RadSplitterController.getInstance()._addPane(f,h,g,e,b,c,d);
};
a.RadPane.registerClass("Telerik.Web.UI.RadPane",a.SplitterPaneBase);
})();
Type.registerNamespace("Telerik.Web.UI");
(function(){$telerik.toSplitBar=function(g){return g;
};
$telerik.findSplitBar=$find;
var b=Telerik.Web.UI;
var c=b.EventNamesMap;
var a=$telerik.$;
var f=a.proxy;
var e="mouseover";
var d="mouseout";
a.registerEnum(b,"SplitBarCollapseMode",{None:1,Forward:2,Backward:3,Both:4});
b.RadSplitBar=function(g){b.RadSplitBar.initializeBase(this,[g]);
this._collapseMode=b.SplitBarCollapseMode.None;
this._enableResize=true;
this._resizeStep=0;
this._indexInSplitBars=null;
this._prevPane=null;
this._nextPane=null;
this._collapsed={};
this._collapsed[b.SplitterDirection.Forward]=false;
this._collapsed[b.SplitterDirection.Backward]=false;
this._splitterOrientation=b.Orientation.Vertical;
this._liveResize=false;
this._resizeExtender=null;
this._splitter=null;
this.IsCollapseDirectionEnabled=this.isCollapseDirectionEnabled;
this.GetCollapseBarElement=this.getCollapseBarElement;
this.IsCollapsed=this.isCollapsed;
this.GetWidth=this.getWidth;
this.GetHeight=this.getHeight;
};
b.RadSplitBar.prototype={initialize:function(){var n=this;
b.RadSplitBar.callBaseMethod(this,"initialize");
var i=b.SplitterDirection.Forward;
if(this.isCollapseDirectionEnabled(i)){var g=this.getCollapseBarElement(i);
a(g).onEvent(c.down,f(n._collapseBarFwdOnMouseDown,n)).on(e,f(n._collapseBarFwdOnMouseOver,n)).on(d,f(n._collapseBarFwdOnMouseOut,n));
g.setAttribute("unselectable","on");
}i=b.SplitterDirection.Backward;
if(this.isCollapseDirectionEnabled(i)){var h=this.getCollapseBarElement(i);
a(h).onEvent(c.down,f(n._collapseBarBackOnMouseDown,n)).on(e,f(n._collapseBarBackOnMouseOver,n)).on(d,f(n._collapseBarBackOnMouseOut,n));
h.setAttribute("unselectable","on");
}if(this.get_enableResize()){var j=this.get_element();
j.setAttribute("unselectable","on");
$addHandlers(j,{mouseover:this._onMouseOver,mouseout:this._onMouseOut},this);
this._createResizeHelper();
var m=this._getCursorStyle();
var l={};
l[m]=j;
var k=this._resizeExtender=new b.ResizeExtender(this,this._helperBar,l,null,null,m,false);
k.set_hideIframes(false);
}},dispose:function(){var i=this;
var g=b.SplitterDirection.Forward;
if(i.isCollapseDirectionEnabled(g)){a(i.getCollapseBarElement(g)).offEvent();
}g=b.SplitterDirection.Backward;
if(i.isCollapseDirectionEnabled(g)){a(i.getCollapseBarElement(g)).offEvent();
}if(this._resizeExtender){this._resizeExtender.dispose();
}var h=this._helperBar;
if(h){h.parentNode.removeChild(h);
}this._resizeExtender=null;
this._helperBar=null;
this._helperBarDecoration=null;
this._splitter=null;
b.RadSplitterController.getInstance()._removeSplitBar(this.get_id());
b.RadSplitBar.callBaseMethod(this,"dispose");
},set_collapseMode:function(g){this._collapseMode=g;
},get_collapseMode:function(){return this._collapseMode;
},set_resizeStep:function(g){this._resizeStep=g;
},get_resizeStep:function(){return this._resizeStep;
},set_enableResize:function(g){this._enableResize=g;
},get_enableResize:function(){return this._enableResize;
},set_nextPane:function(g){this._nextPane=g;
},get_nextPane:function(){var g=this._nextPane;
if(!g){g=this._nextPane=b.RadSplitterController.getInstance()._getSplitBarNextPane(this.get_id());
}return g;
},set_prevPane:function(g){this._prevPane=g;
},get_prevPane:function(){var g=this._prevPane;
if(!g){g=this._prevPane=b.RadSplitterController.getInstance()._getSplitBarPrevPane(this.get_id());
}return g;
},isCollapseDirectionEnabled:function(h){var i=false;
var g=this._collapseMode;
if((g==b.SplitBarCollapseMode.Both)||(g==b.SplitBarCollapseMode.Forward&&h==b.SplitterDirection.Forward)||(g==b.SplitBarCollapseMode.Backward&&h==b.SplitterDirection.Backward)){i=true;
}return i;
},getCollapseBarElement:function(g){var h="Forward";
if(g==b.SplitterDirection.Backward){h="Backward";
}return $get("RAD_SPLITTER_BAR_COLLAPSE_"+h+"_"+this.get_id());
},isCollapsed:function(g){return this._collapsed[g];
},getWidth:function(){return this.get_element().offsetWidth;
},getHeight:function(){return this.get_element().offsetHeight;
},_setButtonOverCss:function(h){var g=this.getCollapseBarElement(h);
var i=g.className+"Over";
Sys.UI.DomElement.addCssClass(g,i);
},_resetButtonCss:function(i){var g=this.getCollapseBarElement(i);
if(!g){return;
}var k=this._isSplitterVertical();
var h=k?"rspCollapseBarCollapseOver":"rspCollapseBarHorizontalCollapseOver";
var j=k?"rspCollapseBarExpandOver":"rspCollapseBarHorizontalExpandOver";
Sys.UI.DomElement.removeCssClass(g,h);
Sys.UI.DomElement.removeCssClass(g,j);
},_collapseBarFwdOnMouseOut:function(g){g.stopPropagation();
this._resetButtonCss(b.SplitterDirection.Forward);
return false;
},_collapseBarBackOnMouseOut:function(g){g.stopPropagation();
this._resetButtonCss(b.SplitterDirection.Backward);
return false;
},_collapseBarFwdOnMouseOver:function(g){g.stopPropagation();
this._setButtonOverCss(b.SplitterDirection.Forward);
return false;
},_collapseBarBackOnMouseOver:function(g){g.stopPropagation();
this._setButtonOverCss(b.SplitterDirection.Backward);
return false;
},_buttonMouseDown:function(h,g){if(h.button&&h.button!=1){return true;
}this._collapseTargetPane(g);
setTimeout(Function.createDelegate(this,function(){this._resetButtonCss(g);
}),10);
return $telerik.cancelRawEvent(h);
},_collapseBarFwdOnMouseDown:function(g){return this._buttonMouseDown(g,b.SplitterDirection.Forward);
},_collapseBarBackOnMouseDown:function(g){return this._buttonMouseDown(g,b.SplitterDirection.Backward);
},_createResizeHelper:function(){var g=this._getCursorStyle();
var j=document.createElement("div");
j.unselectable="on";
a(j).css({display:"none",position:"absolute",cursor:g,zIndex:"2"});
document.body.insertBefore(j,document.body.firstChild);
Sys.UI.DomElement.addCssClass(j,"RadSplitter");
var h=document.createElement("div");
h.unselectable="on";
var i=a(h).css({cursor:g,fontSize:"1px",margin:(this._isSplitterVertical()?"0 150px":"150px 0")});
h.innerHTML="<!-- / -->";
j.appendChild(h);
if(!this._liveResize){Sys.UI.DomElement.addCssClass(h,"rspHelperBarDrag");
}else{i.css("opacity","0.6");
}this._helperBar=j;
this._helperBarDecoration=h;
},onDragStart:function(g){if(this.isCollapsed(b.SplitterDirection.Forward)||this.isCollapsed(b.SplitterDirection.Backward)){return false;
}var r=this.get_splitter();
var s=this._targetResizePane=r._getAvailAdjacentPane(this.get_prevPane().get_indexInPanes()+1,b.SplitterDirection.Backward);
if(!s){return false;
}var n=this._getAvailDecreaseDelta();
var o=this._getAvailIncreaseDelta();
var p=r._getDragOverlay();
a(p).css({zIndex:"1",cursor:this._getCursorStyle(),display:"block"});
$telerik.setBounds(p,$telerik.getBounds(r.get_element()));
var i=this.get_element();
var q=$telerik.getContentSize(i);
$telerik.setSize(this._helperBarDecoration,q);
var m=$telerik.getLocation(i);
var h=this._cachedSplitbarBounds=a.extend({},q,m);
this._lastAppliedPosition=a.extend({},h);
this._liveResizePosition=a.extend({},h);
var l=this._isSplitterVertical();
this._cachedSplitterBounds={x:h.x-(l?n:0),y:h.y-(!l?n:0),width:h.width+(l?(n+o):0),height:h.height+(!l?(n+o):0)};
var k=this._helperBar;
k.style.display="";
m[l?"x":"y"]-=150;
$telerik.setLocation(k,m);
var j=this._resizeExtender;
j._originalBounds=a.extend({},h,m);
return true;
},onDragEnd:function(g){var j=this._isSplitterVertical()?"x":"y";
var h=this[this._liveResize?"_lastAppliedPosition":"_cachedSplitbarBounds"];
var i=this._liveResizePosition[j]-h[j];
if(i!=0){this._targetResizePane.resize(i,b.SplitterDirection.Forward);
}this.get_splitter()._getDragOverlay().style.display="none";
this._helperBar.style.display="none";
Sys.UI.DomElement.removeCssClass(this._helperBarDecoration,"rspHelperBarError");
this._lastAppliedPosition=null;
this._liveResizePosition=null;
this._cachedSplitterBounds=null;
this._cachedSplitbarBounds=null;
},onDrag:function(g){var q=this._cachedSplitterBounds;
if(q.width<1||q.height<1){return false;
}var h=this._helperBarDecoration;
Sys.UI.DomElement.removeCssClass(h,"rspHelperBarError");
var j=this._isSplitterVertical();
var m=j?"x":"y";
g[m]+=150;
var p=this._cachedSplitbarBounds;
var o=b.ResizeExtender.containsBounds(q,new Telerik.Web.UI.Bounds(g.x,g.y,p.width,p.height));
if(!o){var l=false;
if(g.x<=q.x){g.x=q.x;
if(j){l=true;
}}else{if(q.x+q.width<=g.x+p.width){g.x=q.x+q.width-p.width;
if(j){l=true;
}}}if(g.y<=q.y){g.y=q.y;
if(!j){l=true;
}}else{if(q.y+q.height<=g.y+p.height){g.y=q.y+q.height-p.height;
if(!j){l=true;
}}}o=true;
if(l){Sys.UI.DomElement.addCssClass(h,"rspHelperBarError");
}}if(this._liveResize){var k=this._lastUpdate;
if(!k||((new Date()-k)>=32)){this._lastUpdate=new Date();
var i=g[m]-this._lastAppliedPosition[m];
this._targetResizePane.resize(i,b.SplitterDirection.Forward);
this._lastAppliedPosition=a.extend({},g);
}}else{var n=this._resizeStep;
if(n>0){g[m]-=(g[m]-p[m])%n;
}}this._liveResizePosition=a.extend({},g);
g[m]-=150;
return o;
},_setSplitBarClass:function(g){if(!this._isInactive){var h=(this._isSplitterVertical())?"rspResizeBarOver":"rspResizeBarOverHorizontal";
var i=this.get_element();
Sys.UI.DomElement.removeCssClass(i,h);
if(g){Sys.UI.DomElement.addCssClass(i,h);
}}},_onMouseOver:function(g){this._setSplitBarClass(true);
},_onMouseOut:function(g){this._setSplitBarClass();
},_getIndexInSplitBars:function(){var g=this._indexInSplitBars;
if(null==g){g=this._indexInSplitBars=b.RadSplitterController.getInstance()._getIndexInSplitBars(this.get_id());
}return g;
},_setCursorStyle:function(){this.get_element().style.cursor=this._getCursorStyle();
},_getCursorStyle:function(){var g="";
if(this.get_enableResize()&&!this._isInactive){g=(this._isSplitterVertical())?"w-resize":"n-resize";
}return g;
},_getCollapseTarget:function(g){return(g==b.SplitterDirection.Forward)?this.get_prevPane():this.get_nextPane();
},_getAvailableDelta:function(i,k){var j=this.get_splitter();
var g=j._getAvailAdjacentPane(this.get_prevPane().get_indexInPanes()+1,b.SplitterDirection.Backward);
if(g==null){return 0;
}var h=0;
h=g[i]();
if(h<=0){return 0;
}var l=j[k](g.get_indexInPanes(),b.SplitterDirection.Forward);
return Math.min(l,h);
},_getAvailDecreaseDelta:function(){return this._getAvailableDelta("_getAvailDecreaseDelta","_getAvailIncreaseDelta");
},_getAvailIncreaseDelta:function(){return this._getAvailableDelta("_getAvailIncreaseDelta","_getAvailDecreaseDelta");
},_getCollapseBarHeight:function(g){if(this.getCollapseBarElement(g)==null){return 0;
}return this.getCollapseBarElement(g).offsetHeight;
},_getCollapseDivClass:function(g){var i=this._isSplitterVertical();
var h=i?"rspCollapseBarCollapse":"rspCollapseBarHorizontalCollapse";
if(g==b.SplitterDirection.Backward){h=i?"rspCollapseBarExpand":"rspCollapseBarHorizontalExpand";
}return h;
},_getExpandDivClass:function(g){var i=this._isSplitterVertical();
var h=i?"rspCollapseBarExpand":"rspCollapseBarHorizontalExpand";
if(g==b.SplitterDirection.Backward){h=i?"rspCollapseBarCollapse":"rspCollapseBarHorizontalCollapse";
}return h;
},_collapseTargetPane:function(i){var n=this._getCollapseTarget(i);
if(!n){return false;
}var k=false;
var m=this.get_splitter();
var j=n._isCollapsed();
if(!n.isLocked()){if(this.isCollapsed(i)||n._initialExpandMode){if(!j){return true;
}k=m._expandPane(n,i);
if(k){j=false;
}}else{if(j){return true;
}k=m._collapsePane(n,i);
if(k){j=true;
}}}if(k){this._collapsed[i]=j;
var g=this.getCollapseBarElement(i);
if(g){g.className=this[j?"_getExpandDivClass":"_getCollapseDivClass"](i);
}var l=(i==b.SplitterDirection.Forward)?b.SplitterDirection.Backward:b.SplitterDirection.Forward;
var h=this.getCollapseBarElement(l);
if(h!=null){h.style.display=j?"none":"";
}}else{this._showExpandCollapseError(i);
}return k;
},_showExpandCollapseError:function(i){var h=this.getCollapseBarElement(i);
if(h==null){return;
}var k=(i==b.SplitterDirection.Forward);
var j=this._isSplitterVertical()?(k?"rspCollapseBarCollapseError":"rspCollapseBarExpandError"):(k?"rspCollapseBarHorizontalCollapseError":"rspCollapseBarHorizontalExpandError");
var g=function(){Sys.UI.DomElement.addCssClass(h,j);
};
var l=function(){Sys.UI.DomElement.removeCssClass(h,j);
};
setTimeout(g,0);
setTimeout(l,200);
setTimeout(g,400);
setTimeout(l,600);
setTimeout(g,800);
setTimeout(l,1000);
}};
b.RadSplitBar._preInitialize=function(k,l,j,i,g,h){b.RadSplitterController.getInstance()._addSplitBar(k,l,j,i,g,h);
};
b.RadSplitBar.registerClass("Telerik.Web.UI.RadSplitBar",b.SplitterItem);
})();
