(function(a,d,c){var b=250000;
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.GridVirtualization=function(){var e=this;
Telerik.Web.UI.GridVirtualization.initializeBase(e);
e._tableView=null;
e._startIndex=-1;
e._virtualItemCount=5000;
e._cachedData=[];
e._cachedDataLength=0;
e._timeout=null;
e._queue=[];
e._bindingType="Server";
e._haveCustomScrollbar=true;
e._scrollbar=null;
e._loadingPanel=null;
e._isLoadingPanelCurrentlyVisible=false;
e._currentRequestData=null;
e._globalItemsState=[];
e._startScrollTop=0;
e._shouldLoadState=true;
e._enableCurrentPageScrollOnly=false;
e._retrievedItemsPerRequest=0;
e._itemsPerView=0;
e._maxCacheSize=0;
};
Telerik.Web.UI.GridVirtualization.prototype={initialize:function(){Telerik.Web.UI.GridVirtualization.callBaseMethod(this,"initialize");
var j=this;
var i=j._tableView;
var e=i.get_owner();
var k=e.ClientSettings.Virtualization;
var f=i._data.LoadingPanelID;
j._virtualItemCount=i._data.TotalItemsCount===c?5000:i._data.TotalItemsCount;
j._enableCurrentPageScrollOnly=k.EnableCurrentPageScrollOnly&&i.get_allowPaging();
j._retrievedItemsPerRequest=k.RetrievedItemsPerRequest||1000;
j._itemsPerView=k.ItemsPerView||100;
j._maxCacheSize=k.MaxCacheSize===c?Number.MAX_VALUE:k.MaxCacheSize;
if(f){j._loadingPanel=$find(f)||$telerik.findControl(a.body,f);
}if(j._loadingPanel){j._loadingPanelShowingDelegate=Function.createDelegate(j,j._loadingPanelShowing);
}j._haveCustomScrollbar=!(j._enableCurrentPageScrollOnly&&j._itemsPerView>=i.get_pageSize());
if(j._haveCustomScrollbar){i.get_owner().get_element().style.position="relative";
j._scrollbar=$get(i.get_id()+"_VirtualScroll");
if(e.GridDataDiv){j._scrollbar.style.height=e.GridDataDiv.style.height;
}j._scrollbar.style.width=Telerik.Web.UI.Grid.getScrollBarHeight()+1+"px";
j.setupScrollbar();
var g=Function.createDelegate(j,j._onScroll);
d.$addHandler(j._scrollbar,"scroll",g);
if(j._startScrollTop>0){setTimeout(function(){j._scrollbar.scrollTop=j._startScrollTop;
});
}if(!$telerik.isTouchDevice){var h=Function.createDelegate(j,j._onWheelScroll);
d.$addHandler(i.get_element(),"DOMMouseScroll",h);
d.$addHandler(i.get_element(),"mousewheel",h);
}}if((k.CurrentPageIndex!==c)&&k.EnableCurrentPageScrollOnly){i.set_currentPageIndex(k.CurrentPageIndex);
}if(typeof(e.ClientSettings.DataBinding.Location)!="undefined"&&e.ClientSettings.DataBinding.Location!=""){j._bindingType="WebService";
j._virtualItemCount=j._retrievedItemsPerRequest;
e.add_dataSourceResolved(Function.createDelegate(j,j._onDataSourceResolved));
j.select();
}else{if(e._clientDataSourceID){j._bindingType="ClientDataSource";
}else{j.set_cachedData(j._parseJSON(i._data.VirtualizationDataAsJSON));
j._virtualItemCount=j._tableView._data.TotalItemsCount;
}}j._handleGlobalItemsState();
i.get_dataItems();
i.get_owner().add_command(function(n,l){var m=parseInt(l.get_commandArgument(),10);
if(!isNaN(m)&&j._haveCustomScrollbar){j._itemAtTop=j._getScrollInfo().itemAtTop;
e.updateClientState();
j._itemAtTop=null;
}});
this._hideOverflowingItemsFromNextPage();
},dispose:function(){Telerik.Web.UI.GridVirtualization.callBaseMethod(this,"dispose");
},set__tableView:function(e){this._tableView=e;
},set_cachedData:function(f){var e=this;
e._cachedData=f;
e._cachedDataLength=f.length;
},get_cachedData:function(){return this._cachedData;
},get_startIndex:function(){var e=this._startIndex;
if(e<0){return 0;
}return e;
},get_virtualItemCount:function(){return this._virtualItemCount;
},set_virtualItemCount:function(e){this._virtualItemCount=e;
this.setupScrollbar();
},set_bindingType:function(e){this._bindingType=e;
},get_bindingType:function(){return this._bindingType;
},setupScrollbar:function(){var l=this;
var k=l._tableView;
var h=l._scrollbar;
var n=l._enableCurrentPageScrollOnly?k.get_pageSize():l._virtualItemCount;
var m=k.get_element().offsetHeight*(n/l._itemsPerView);
var g=Math.ceil(m/b);
var j=m%b;
var e;
if(l._haveCustomScrollbar||h){if(l._virtualItemCount>l._itemsPerView){l._haveCustomScrollbar=true;
h.style.display="";
if(h.children.length!==g){h.innerHTML="";
for(var f=0;
f<g;
f++){e=a.createElement("div");
e.style.width="1px";
e.style.height=b+"px";
h.appendChild(e);
}}if(j>0){h.children[h.children.length-1].style.height=j+"px";
}}else{l._haveCustomScrollbar=false;
h.style.display="none";
}}},scrollToIndex:function(e,g){if(!this._haveCustomScrollbar){return;
}var i=this;
var h=i._tableView;
var j=i._enableCurrentPageScrollOnly?h.get_pageSize():i._virtualItemCount;
var f=i._getScrollInfo();
if(g){e-=f.itemAtBottom-f.itemAtTop-1;
}if(i._enableCurrentPageScrollOnly){e=e%h.get_pageSize();
}i._scrollbar.scrollTop=e*(f.currentScrollbarHeight/j);
},repaint:function(){var g=this._tableView;
var e=g.get_owner().GridDataDiv;
var f=this._scrollbar;
if(f){f.style.height=e?e.style.height:g.get_element().style.height;
}},_getScrollInfo:function(){if(!this._haveCustomScrollbar){return null;
}var f=$telerik.getElementsByClassName(this._tableView.get_element(),"rgEditForm");
var g;
for(g=0;
g<f.length;
g++){f[g].style.display="none";
}var o=this;
var n=o._tableView;
var p=o._enableCurrentPageScrollOnly?n.get_pageSize():o._virtualItemCount;
var e=n.get_element().offsetHeight*(p/o._itemsPerView);
var l=n.get_element().offsetHeight*(o._virtualItemCount/o._itemsPerView);
var m=o._scrollbar.scrollTop%l;
var j=o._virtualItemCount*m/l;
var h=o._virtualItemCount*(m+n.get_element().parentNode.offsetHeight)/l;
var k=n._dataItemsByGlobalIndex?n._dataItemsByGlobalIndex:n.get_dataItems();
for(g=0;
g<f.length;
g++){f[g].style.display="";
}if(o._enableCurrentPageScrollOnly){j+=n.get_currentPageIndex()*n.get_pageSize();
h+=n.get_currentPageIndex()*n.get_pageSize();
}return{currentScrollbarHeight:e,scrollBarHeight:l,scrollTop:m,itemAtTop:j,itemAtBottom:h,itemsByGlobalIndex:k};
},_onWheelScroll:function(h){var j=this;
var i=h.rawEvent||h;
var g=i.wheelDeltaY;
var f;
if(i.wheelDelta&&g===c||g){f=i.wheelDelta;
}else{if(i.detail&&i.axis===i.VERTICAL_AXIS){f=(-i.detail)*10;
}}if(f&&j._haveCustomScrollbar){h.preventDefault();
j._scrollbar.scrollTop+=-f;
}},_onScroll:function(f){var j=this;
var i=j._tableView;
var g=j._getScrollInfo();
var h=null;
if(!g.itemsByGlobalIndex[Math.floor(g.itemAtBottom)]&&Math.floor(g.itemAtBottom)!==j._virtualItemCount){h=Math.ceil(g.itemAtTop);
}else{if(!g.itemsByGlobalIndex[Math.floor(g.itemAtTop)]){h=Math.ceil(g.itemAtBottom)-j._itemsPerView;
h=Math.max(h,0);
}}if(h==null||(j._enableCurrentPageScrollOnly&&h<i.get_pageSize()*i.get_currentPageIndex())){j._setScrollPosition();
}else{j.select(h);
}},_setScrollPosition:function(){if(!this._haveCustomScrollbar){return;
}var m=this;
var l=m._tableView;
var k=l.get_element();
var e=l.get_element().parentNode;
var j=m._getScrollInfo();
var g=j.itemAtTop;
var f=j.itemsByGlobalIndex[Math.ceil(g)];
var i=0;
var h=m._enableCurrentPageScrollOnly?Math.floor(g/l.get_pageSize()):Math.round(g/l.get_pageSize());
if(f){e.scrollTop=$telerik.getLocation(f.get_element()).y-$telerik.getLocation(e).y+e.scrollTop;
e.scrollTop+=f.get_element().offsetHeight*(g%1);
e.scrollTop=e.scrollTop;
}if(!l.get_owner().ClientSettings.Scrolling.UseStaticHeaders){if(m.get_startIndex()===0||m.get_startIndex()===l.get_currentPageIndex()*l.get_pageSize()){while(k.rows[i].className.indexOf("rgRow")==-1){k.parentNode.scrollTop-=k.rows[i].offsetHeight;
i++;
}}else{if(m._startIndex>=m._virtualItemCount-m._itemsPerView||(m._enableCurrentPageScrollOnly&&m._startIndex%l.get_pageSize()>=l.get_pageSize()-m._itemsPerView)){k.parentNode.scrollTop+=k.rows[k.rows.length-1].offsetHeight;
}}}else{if(m._startIndex>=m._virtualItemCount-m._itemsPerView||(m._enableCurrentPageScrollOnly&&m._startIndex%l.get_pageSize()>=l.get_pageSize()-m._itemsPerView)&&k.parentNode.clientHeight!==k.parentNode.offsetHeight){k.parentNode.scrollTop+=Telerik.Web.UI.Grid.getScrollBarHeight();
}}l.set_currentPageIndex(Math.min(h,l.get_pageCount()-1),true);
clearTimeout(m._updateClientStateTimeout);
m._updateClientStateTimeout=setTimeout(function(){l._owner.updateClientState();
},100);
},select:function(h,f){var j=this;
var i=j._tableView;
var g=j._haveCustomScrollbar?j._itemsPerView:i.get_pageSize();
h=typeof h==="undefined"?i.get_currentPageIndex()*i.get_pageSize():h;
var e=h+g;
if(h===j._startIndex&&!f){return;
}if(e>=j._virtualItemCount){e=j._virtualItemCount;
h=Math.max(e-g,0);
}j._startIndex=h;
clearTimeout(j._timeout);
if(!j._tryBindFromCache(h,e)){j._setLoadingPanelVisibility(true);
j._timeout=setTimeout(function(){j._requestData(h,e);
},100);
}},_tryBindFromCache:function(k,f){var m=this;
var h=this._tableView.get_owner();
var e=this._cachedData;
var l;
var g;
f=Math.min(f,m._virtualItemCount-1);
if(m._bindingType=="ClientDataSource"&&h._clientSideBinding.get_clientDataSource().get_dataSourceObject().inRange(k,f-k)){m._bindData(k,f);
return true;
}else{if(e[k]&&e[f]){for(var j=k;
j<f;
j++){if(!e[j]){if(!l){l=j;
}g=j;
}}if(g){m._setLoadingPanelVisibility(true);
m._timeout=setTimeout(function(){m._executeRequest(k,f,l,g);
},100);
return true;
}m._bindData(k,f);
return true;
}}return false;
},_setLoadingPanelVisibility:function(h){var g=this;
var f=g._loadingPanel;
var e=g._tableView.get_element().parentNode.id;
if(f){if(h&&!g._isLoadingPanelCurrentlyVisible){f.add_showing(g._loadingPanelShowingDelegate);
f.show(e);
g._isLoadingPanelCurrentlyVisible=true;
}else{if(!h&&g._isLoadingPanelCurrentlyVisible){f.hide(e);
g._isLoadingPanelCurrentlyVisible=false;
}}}},_loadingPanelShowing:function(f,e){var g=this;
e.get_loadingElement().style.width=(parseInt(/[0-9]+/.exec(e.get_loadingElement().style.width)[0],10)-Telerik.Web.UI.Grid.getScrollBarHeight())+"px";
g._loadingPanel.remove_showing(g._loadingPanelShowingDelegate);
},_requestData:function(h,e){var j=this;
var g=j._retrievedItemsPerRequest;
e=Math.min(e,j._virtualItemCount-1);
var i=e-(e%g);
var f=Math.min(i+g,j._virtualItemCount);
if(i>h){i=h;
}if(f<e){f=e;
}j._executeRequest(h,e,i,f);
},_executeRequest:function(k,f,l,g){var n=this;
var m=n._tableView;
var h=m.get_owner();
var j=g-l;
var e=n._bindingType;
if(n._currentRequestData){n._queue.push([k,f,l]);
return;
}n._currentRequestData=[k,f,l,g];
if(e==="Server"){m.get_owner()._initializeCallback(n._getCallbackArgument(l,j),function(p){n._handleRequestResult(n._parseJSON(p));
});
}else{if(e=="ClientDataSource"){h._clientSideBinding.get_clientDataSource().get_dataSourceObject().prefetch(l,j,function(){n._tryBindFromCache(k,f);
});
n._currentRequestData=null;
}else{if(e==="WebService"){if(!h._onSuccessDelegate&&!h._onFailDelegate){h._onSuccessDelegate=Function.createDelegate(h,h._onSuccess);
h._onFailDelegate=Function.createDelegate(h,h._onFail);
}if(typeof(h.ClientSettings.DataBinding.SelectMethod)!="undefined"&&h.ClientSettings.DataBinding.SelectMethod!=""){h._getData(h.ClientSettings.DataBinding.Location,h.ClientSettings.DataBinding.SelectMethod,h._getRequestData(l,j),h._onSuccessDelegate,h._onFailDelegate);
}else{if(typeof(h.ClientSettings.DataBinding.DataService)!="undefined"&&typeof(h.ClientSettings.DataBinding.DataService.TableName)!="undefined"&&h.ClientSettings.DataBinding.DataService.TableName!=""){var i=m.getDataServiceQuery(h.ClientSettings.DataBinding.DataService.TableName,h.ClientSettings.DataBinding.DataService.FilterQueryOption,h.ClientSettings.DataBinding.DataService.SortQueryOption,l/j,j);
var o=String.format("{0}/{1}",h.ClientSettings.DataBinding.Location,i);
h._getDataServiceData(h._onSuccessDelegate,h._onFailDelegate,o);
}}}}}},_getCallbackArgument:function(f,e){return String.format("getData$${0}$${1}$${2}",this._tableView._data.UniqueID,f,e);
},_parseJSON:function(e){var g=/^[\],:{}\s]*$/;
var f=/(?:^|:|,)(?:\s*\[)+/g;
var h=/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g;
var i=/"[^"\\\r\n]*"|true|false|null|-?(?:\d+\.|)\d+(?:[eE][+-]?\d+|)/g;
if(d.JSON&&d.JSON.parse){return d.JSON.parse(e);
}if(e===null){return e;
}if(typeof e==="string"&&e){if(g.test(e.replace(h,"@").replace(i,"]").replace(f,""))){return(new Function("return "+e))();
}}},_handleRequestResult:function(l){var o=this;
var e=o._cachedData;
var k=o._currentRequestData;
var m=k[0];
var f=k[1];
var n=k[2];
var j=o._haveCustomScrollbar||!o._enableCurrentPageScrollOnly?o._itemsPerView:o._tableView.get_pageSize();
var g=Math.max(k[3],m+j)+1;
for(var h=n;
h<g;
h++){if(!e[h]){o._cachedDataLength++;
if(!l[h-n]){break;
}e[h]=l[h-n];
}}o._handleCachedDataOverflow(m,f);
if(o._startIndex===m){o._bindData(m,m+j);
}o._currentRequestData=null;
setTimeout(function(){var i=o._queue.pop();
if(i){o._requestData.apply(o,i);
}});
},_handleCachedDataOverflow:function(k,f){var l=this;
var e=l._cachedData;
var h=l._retrievedItemsPerRequest;
var j;
var g;
if(l._cachedDataLength>l._maxCacheSize){if((l._virtualItemCount/2)>k+((f-k)/2)){j=e.length-1;
while(!e[j]){j-=h;
}for(g=j-h;
g<j;
g++){l._cachedDataLength--;
e[g]=null;
}}else{j=0;
while(!e[j]){j+=h;
}for(g=0;
g<j+h;
g++){l._cachedDataLength--;
e[g]=null;
}}}},_onDataSourceResolved:function(f,e){this._handleRequestResult(e.get_data());
},_bindData:function(g,f){var i=this;
var h=i._tableView;
var e;
if(f==i._virtualItemCount-1){f=i._virtualItemCount;
}i._isDataBinding=true;
if(i._bindingType=="ClientDataSource"){h.get_owner()._clientSideBinding.get_clientDataSource().get_dataSourceObject().range(g,f-g);
}else{e=h._dataSource;
h._dataSource=i._cachedData.slice(g,Math.min(f,i._cachedData.length));
i._isDataBinding=true;
h.dataBind();
i._shouldLoadState=true;
h._dataSource=e;
}i._isDataBinding=false;
i.setupScrollbar();
i._setScrollPosition();
i._setLoadingPanelVisibility(false);
i._hideOverflowingItemsFromNextPage();
},_hideOverflowingItemsFromNextPage:function(){var j=this;
var h=j._tableView;
var e=h.get_dataItems();
var f=e.length-(j.get_startIndex()+j._itemsPerView)+(h.get_pageSize()*h.get_currentPageIndex()+h.get_pageSize());
if(j._enableCurrentPageScrollOnly&&f>0){for(var g=e.length-1;
g>=0&&g>=f;
g--){e[g].get_element().style.visibility="hidden";
}}},_handleGlobalItemsState:function(){var k=this;
var j=k._tableView;
var f=j.get_owner();
var e=["rowSelected","rowDeselected","hierarchyExpanded","hierarchyCollapsed","rowShown","rowHidden","rowResized"];
var h;
for(var g=0;
g<e.length;
g++){f["add_"+e[g]](function(l,i){if(i.get_tableView()===j){k.updateItemState(i.get_gridDataItem(),true);
}});
}f.add_cellSelected(function(l,i){h=k.updateItemState(i.get_gridDataItem(),true);
h.selectedCells[i.get_column().get_uniqueName()]=true;
});
f.add_cellDeselected(function(l,i){h=k.updateItemState(i.get_gridDataItem(),true);
h.selectedCells[i.get_column().get_uniqueName()]=null;
});
},_createState:function(e){if(e){var g=e.get_element();
var f=false;
if((!!(e.get_editFormItem()&&e.get_editFormItem().style.display==""))||this._tableView._data.EditMode=="InPlace"&&g.className.indexOf("rgEditRow")!=-1){f=true;
}return{isSelected:e.get_selected(),isExpanded:e.get_expanded(),isInEditMode:f,isVisible:g.offsetHeight!==0&&g.offsetWidth!==0,height:g.style.height?g.offsetHeight:null,selectedCells:{}};
}return{isSelected:false,isExpanded:false,isInEditMode:false,isVisible:true,height:null,selectedCells:{}};
},_cancelEvent:function(f,e){e.set_cancel(true);
},_moveEditForm:function(e){var k=this;
var j=e.get_element();
var f=k._tableView.get_dataItems();
var g;
for(var h=0;
h<f.length;
h++){g=f[h].get_editFormItem();
if(g){j.parentNode.insertBefore(g,j.nextSibling);
return g;
}}},updateItemState:function(e,f){var i=this;
var g=Math.max(i._startIndex,0)+e._itemIndex;
var h;
h=i._createState(e);
if(h.isSelected||h.isExpanded||h.isInEditMode||!h.isVisible||h.height!=null||f){i._globalItemsState[g]=h;
}return h;
},updateItemsCellSelectionState:function(){var l=this;
var k=l._tableView;
var h=k.get_owner()._selectedCellsIndexes;
var f;
var j;
var e;
for(var g=0;
g<h.length;
g++){e=h[g].split("&");
f=k.get_dataItems()[parseInt(e[0],10)];
if(f){j=l.updateItemState(f,true);
j.selectedCells[e[1]]=true;
}}},loadState:function(e){var j=this;
var i=j._tableView;
var g=e._element;
var f=e.get_editFormItem();
var h=j._globalItemsState[j._startIndex+e._itemIndex]||{isSelected:false,isExpanded:false,isInEditMode:false,isVisible:true,height:null,selectedCells:{}};
if(h.isSelected&&!e._selected){e.set_selected(true);
}else{if(!h.isSelected&&e._selected){i.get_owner().add_activeRowChanging(j._cancelEvent);
e.set_selected(false);
i.get_owner().remove_activeRowChanging(j._cancelEvent);
}}if(h.isExpanded&&!e._expanded){e.set_expanded(true);
}else{if(!h.isExpanded&&e._expanded){e.set_expanded(false);
}}if(h.isInEditMode){if(!f){f=j._moveEditForm(e);
}g.className="rgEditRow";
g.style.display="";
if(f){setTimeout(function(){f.style.display="";
});
}}else{if(!h.isInEditMode){j.hideEditFormItem(f,g);
}}if(e.get_itemIndex()>=0){if(h.isVisible&&g.style.display==="none"){i.showItem(e.get_itemIndex());
}else{if(!h.isVisible&&g.style.display===""){i.hideItem(e.get_itemIndex());
}}}if(h.height==null&&g.style.height){g.cells[0].style.height="auto";
g.style.height="auto";
}else{if(h.height!=null){i.resizeItem(e.get_itemIndex(),h.height,true);
}}},hideEditFormItem:function(f,g){if(g.className.indexOf("rgEditRow")!==-1){if(this._tableView._data.EditMode=="InPlace"){setTimeout(function(){g.style.display="none";
});
}else{var e=g.previousRow;
while(e&&e.className.indexOf("rgRow")===-1&&e.className.indexOf("rgRow")===-1){e=e.previousRow;
}g.className=e?e.indexOf("rgRow")===-1?"rgRow":"rgAltRow":"rgAltRow";
}}if(this._tableView._data.EditMode=="PopUp"){return;
}if(f){f.style.display="none";
}},loadCellSelection:function(g,e,k){var j=this;
var i=j._globalItemsState[j._startIndex+g._itemIndex];
var f=e.className;
var h="rgSelectedCell";
if(i&&i.selectedCells[k]&&f.indexOf(h)===-1){Sys.UI.DomElement.addCssClass(e,h);
}else{if(f.indexOf(h)!==-1){Sys.UI.DomElement.removeCssClass(e,h);
}}}};
Telerik.Web.UI.GridVirtualization.registerClass("Telerik.Web.UI.GridVirtualization",Sys.Component);
Telerik.Web.UI.GridVirtualization._handleRowHeightChangingEvents=function(f){var h=f.get_masterTableView();
var e=["rowResized","hierarchyExpanded","hierarchyCollapsed"];
var j;
f.add_columnResized(function(k,i){j=i.get_gridColumn().get_owner();
if(j._virtualization){j.setupScrollbar();
}else{if(f.get_masterTableViewHeader()&&f.get_masterTableViewHeader().get_id()===j.get_id()&&h._virtualization){h._virtualization.setupScrollbar();
}}});
for(var g=0;
g<e.length;
g++){f["add_"+e[g]](function(k,i){j=i.get_tableView();
if(j._virtualization){j._virtualization.setupScrollbar();
}});
}};
})(document,window);
