(function(c,a,l){Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.ImageAnimations");
var b=c.ImageAnimations,j="None",k="Random",e="__$telerik.animation__",i="imageLoaded",g="animationStart",f="animationEnd",h={horizontalSlices:1,verticalSlices:1};
Telerik.Web.UI.RadImageAnimations=function(){var n=this;
c.RadImageAnimations.initializeBase(n);
var o=n._types=[];
for(var m in b){if(m!=k&&m!=j&&b[m]._prototypeIndentification==e){o.push(m);
}}};
c.RadImageAnimations.registerAnimation=function(m){m._prototypeIndentification=e;
m.init=m.init||a.noop;
m.iteration=m.iteration||j;
m.iterationOptions=a.extend({},m.iterationOptions);
if(m.currentImage){m.currentImage.options=a.extend({},h,m.currentImage.options);
}if(m.newImage){m.newImage.options=a.extend({},h,m.newImage.options);
}b[m.name]=m;
};
b.Iterations={};
c.RadImageAnimations.registerIteration=function(m){m.options=a.extend({},m.options);
b.Iterations[m.name]=m;
};
c.RadImageAnimations.prototype={initialize:function(){c.RadImageAnimations.callBaseMethod(this,"initialize");
},dispose:function(){c.RadImageAnimations.callBaseMethod(this,"dispose");
},animate:function(n,o,p){var m=new d(this,n,o,p);
m.animate();
return m;
},show:function(n,o){var m=new d(this,n,null,o);
m.show();
return m;
},hide:function(n,o){var m=new d(this,n,null,o);
m.hide();
return m;
}};
c.RadImageAnimations.registerClass("Telerik.Web.UI.RadImageAnimations",Sys.Component);
var d=function(p,m,n,o){this._owner=p;
this._currentImage=m;
this._nextImageOrImageSrc=n;
this._options=o;
this._isPlaying=false;
this._animationStarted=false;
this._$currentImage=l;
this._$nextImage=l;
};
d.prototype={stop:function(){var o=this,m=o._$currentImage,n=o._$nextImage;
if(o._isPlaying){o._isPlaying=false;
if(o._animationStarted){o._disposeImage(m,n);
m.stopTransition(true,true);
n.stopTransition(true,true);
clearTimeout(o._timeout);
}a.raiseControlEvent(o._owner,f,{$image:n});
}if(m){m.remove();
}if(n){m.remove();
}},animate:function(){var r=this,o=r._currentImage,p=r._nextImageOrImageSrc,q=r._options,m=a(o),n;
r._isPlaying=true;
if(typeof p=="string"){a("<img>").css("display","none").appendTo(m.parent()).on("load",function(s){n=a(this);
n.off("load");
if(!r._isPlaying){n.remove();
}a.raiseControlEvent(r._owner,i,{$image:n});
if(!r._isPlaying){n.remove();
}r._animate(m,n,q);
}).prop("src",p);
}else{r._animate(m,a(p),q);
}},show:function(){var p=this,m=a(p._currentImage),n=p._options,o=n.type==j?0:n.speed;
p._isPlaying=true;
if(!p._isPlaying||a.raiseCancellableControlEvent(p._owner,g,{$newImage:m})){return;
}if(b[n.type].type=="Hide"){n.reverseAnimation=true;
}p._hideShowImage(m,n,!!n.reverseAnimation);
p._timeout=setTimeout(a.proxy(p._disposeImage,p,null,m),o);
},hide:function(){var p=this,m=a(p._currentImage),n=p._options,o=n.type==j?0:n.speed;
p._isPlaying=true;
if(!p._isPlaying||a.raiseCancellableControlEvent(p._owner,g,{$newImage:m})){return;
}if(b[n.type].type=="Show"){n.reverseAnimation=true;
}p._hideShowImage(m,n,!n.reverseAnimation);
if(n.dispose===false){p._timeout=setTimeout(a.proxy(p._disposeImage,p,null,m),o);
}else{p._timeout=setTimeout(a.proxy(p._disposeImage,p,m,m),o);
}},_animate:function(m,n,o){var q=this,p=o.type==j?0:o.speed;
if(!q._isPlaying||a.raiseCancellableControlEvent(q._owner,g,{$newImage:n})){return;
}q._animationStarted=true;
q._$currentImage=m;
q._$nextImage=n;
if(!m.is(n)){q._hideShowImage(m,o,true);
q._timeout=setTimeout(a.proxy(q._disposeImage,q,m,n),p);
}else{q._timeout=setTimeout(a.proxy(q._disposeImage,q,null,n),p);
}q._hideShowImage(n,o,false);
},_hideShowImage:function(m,o,n){var p=this,q=o.type;
switch(q){case j:m.show();
break;
case k:o.type=p._getRandomType();
p._hideShowImage(m,o,n);
o.type=k;
break;
default:p._callAnimation(m,o,b[q],n?b[q].currentImage:b[q].newImage);
break;
}},_callAnimation:function(m,r,o,p){if(!p||!m.length){m.prependTo(m.parent()).show();
return;
}var s=this,q=p.options,n;
if(q.verticalSlices>1||q.horizontalSlices>1){s._slice(m,q.horizontalSlices,q.verticalSlices,function(u,t){m.parent().append(u);
m.hide();
s._sliceCallback=function(){m.show();
if(u.parentNode){u.parentNode.removeChild(u);
}};
b.Iterations[o.iteration].iterate(t,r,function(v,x,w){n=a(v);
if(p.setup){p.setup(n,r);
}s._timeoutAndAnimate(n,x,w,p,r);
});
});
}else{if(p.setup){p.setup(m,r);
}p.animate(m,r.speed,r);
}},_timeoutAndAnimate:function(m,r,p,n,o){var q=new Date();
setTimeout(function(){if(new Date()-q<o.speed){n.animate(m,p,o);
}},r);
},_slice:function(m,r,E,n){var C="px",D="url('"+m.get(0).src+"')",G=document.createElement("div"),F=m.width(),q=m.height(),A=Math.floor(F/r),y=Math.floor(q/E),z=[],v,x,s,t,u,w,B=new Image(),o=(F/r-A)*r,p=(q/E-y)*E;
B.onload=function(){w=(B.width!=F||B.height!=q)&&!m.get(0).style.backgroundSize;
a(G).css({position:"absolute",width:F+C,height:q+C,left:m.css("paddingLeft"),top:m.css("paddingTop")});
for(var H=0;
H<r;
H++){z[H]=v=[];
for(var I=0;
I<E;
I++){v[I]=x=document.createElement("div");
G.appendChild(x);
x.style.position="absolute";
if(I==E-1){x.style.height=(y+p)+C;
}else{x.style.height=y+C;
}if(H==r-1){x.style.width=(A+o)+C;
}else{x.style.width=A+C;
}t=H*A+C;
u=I*y+C;
x.style.left=t;
x.style.top=u;
if(w){x.style.overflow="hidden";
s=document.createElement("img");
x.appendChild(s);
s.src=m.get(0).src;
s.style.position="absolute";
s.style.width=F+C;
s.style.height=q+C;
s.style.left="-"+t;
s.style.top="-"+u;
}else{x.style.backgroundImage=D;
x.style.backgroundSize=(F+C)+" "+(q+C);
x.style.backgroundPosition="-"+t+" -"+u;
}}}n(G,z);
};
B.src=m.get(0).src;
},_getRandomType:function(){var m=this._owner._types;
return m[Math.floor(Math.random()*m.length)];
},_disposeImage:function(m,n){var o=this;
if(m){m.remove();
}if(o._sliceCallback){o._sliceCallback();
}o._isPlaying=false;
a.raiseControlEvent(o._owner,f,{$image:n});
}};
a.registerControlEvents(c.RadImageAnimations,[g,f,i]);
})(Telerik.Web.UI,$telerik.$);
(function(b,a,c){Type.registerNamespace("Telerik.Web.UI");
b.RadImageAnimations.registerAnimation({name:"Blocks",type:"Hide",iteration:"Grow",currentImage:{options:{horizontalSlices:7,verticalSlices:6},setup:function(d,f){if(f.reverseAnimation){var g=d.width(),e=d.height();
d.data("$telerik.data",{width:d.width(),height:d.height()});
d.css({opacity:0,width:g*0.8,height:e*0.8,marginLeft:g*0.1,marginTop:e*0.1});
}},animate:function(d,h,g){var i=d.width(),f=d.height(),e;
if(g.reverseAnimation){e=d.data("$telerik.data");
i=e.width;
f=e.height;
d.transition({opacity:1,width:i,height:f,marginLeft:0,marginTop:0},h,g.easing);
}else{d.transition({opacity:0,width:i*0.8,height:f*0.8,marginLeft:i*0.1,marginTop:f*0.1},h,g.easing);
}}}});
b.RadImageAnimations.registerAnimation({name:"BigBlocks",type:"Hide",iteration:"Grow",currentImage:{options:{horizontalSlices:2,verticalSlices:2},setup:function(d,f){if(f.reverseAnimation){var g=d.width(),e=d.height();
d.data("$telerik.data",{width:d.width(),height:d.height()});
d.css({opacity:0,width:g*0.8,height:e*0.8,marginLeft:g*0.1,marginTop:e*0.1});
}},animate:function(d,h,g){var i=d.width(),f=d.height(),e;
if(g.reverseAnimation){e=d.data("$telerik.data");
i=e.width;
f=e.height;
d.transition({opacity:1,width:i,height:f,marginLeft:0,marginTop:0},h,g.easing);
}else{d.transition({opacity:0,width:i*0.8,height:f*0.8,marginLeft:i*0.1,marginTop:f*0.1},h,g.easing);
}}}});
b.RadImageAnimations.registerAnimation({name:"SmallBlocks",type:"Hide",iteration:"Grow",currentImage:{options:{horizontalSlices:17,verticalSlices:10},setup:function(d,f){if(f.reverseAnimation){var g=d.width(),e=d.height();
d.data("$telerik.data",{width:d.width(),height:d.height()});
d.css({opacity:0,width:g*0.8,height:e*0.8,marginLeft:g*0.1,marginTop:e*0.1});
}},animate:function(d,h,g){var i=d.width(),f=d.height(),e;
if(g.reverseAnimation){e=d.data("$telerik.data");
i=e.width;
f=e.height;
d.transition({opacity:1,width:i,height:f,marginLeft:0,marginTop:0},h,g.easing);
}else{d.transition({opacity:0,width:i*0.8,height:f*0.8,marginLeft:i*0.1,marginTop:f*0.1},h,g.easing);
}}}});
})(Telerik.Web.UI,$telerik.$);
(function(b,a,c){Type.registerNamespace("Telerik.Web.UI");
b.RadImageAnimations.registerAnimation({name:"Fade",currentImage:{animate:function(d,e){d.transition({opacity:0},e);
}},newImage:{setup:function(d){d.fadeTo(0,0.01);
},animate:function(d,e){d.transition({opacity:1},e);
}}});
})(Telerik.Web.UI,$telerik.$);
(function(b,a,c){Type.registerNamespace("Telerik.Web.UI");
b.RadImageAnimations.registerAnimation({name:"Resize",type:"Show",currentImage:{animate:function(d,e){d.transition({opacity:0},e);
}},newImage:{setup:function(d){var e={width:d.width(),height:d.height()};
d.css("marginTop",d.height()/2).css("marginLeft",d.width()/2);
d.width(0).height(0).data("$telerik.data",e).show();
},animate:function(d,g,f){var e=d.data("$telerik.data");
d.transition({marginTop:0,marginLeft:0,width:e.width,height:e.height},g,f.easing);
}}});
b.RadImageAnimations.registerAnimation({name:"HorizontalResize",type:"Show",iteration:"Grow",currentImage:{animate:function(d,f,e){if(!e.reverseAnimation){d.transition({opacity:0},f);
}}},newImage:{options:{horizontalSlices:8,verticalSlices:1},setup:function(d,f){if(!f.reverseAnimation){var e={width:d.width(),height:d.height()};
d.width(0).data("$telerik.data",e).show();
}},animate:function(d,g,f){if(f.reverseAnimation){d.transition({width:0},g);
}else{var e=d.data("$telerik.data");
d.transition({width:e.width,height:e.height},g,f.easing);
}}}});
b.RadImageAnimations.registerAnimation({name:"VerticalResize",type:"Show",iteration:"Grow",currentImage:{animate:function(d,f,e){if(!e.reverseAnimation){d.transition({opacity:0},f);
}}},newImage:{options:{horizontalSlices:1,verticalSlices:8},setup:function(d,f){if(!f.reverseAnimation){var e={width:d.width(),height:d.height()};
d.height(0).data("$telerik.data",e).show();
}},animate:function(d,g,f){if(f.reverseAnimation){d.transition({height:0},g);
}else{var e=d.data("$telerik.data");
d.transition({width:e.width,height:e.height},g,f.easing);
}}}});
b.RadImageAnimations.registerAnimation({name:"DiagonalResize",type:"Show",iteration:"Grow",currentImage:{animate:function(d,f,e){if(!e.reverseAnimation){d.transition({opacity:0},f,e.easing);
}}},newImage:{options:{horizontalSlices:7,verticalSlices:6},setup:function(d,f){if(!f.reverseAnimation){var e={width:d.width(),height:d.height()};
d.width(0).height(0).data("$telerik.data",e);
}},animate:function(d,g,f){if(f.reverseAnimation){d.transition({width:0,height:0},g);
}else{var e=d.data("$telerik.data");
d.transition({opacity:100,width:e.width,height:e.height},g,f.easing);
}}}});
})(Telerik.Web.UI,$telerik.$);
(function(b,a,c){Type.registerNamespace("Telerik.Web.UI");
b.RadImageAnimations.registerAnimation({name:"HorizontalSlide",type:"Show",newImage:{setup:function(d,f){var e={width:d.width(),height:d.height()};
if(f.reverseAnimation){d.data("$telerik.data",e).show();
}else{d.css({marginLeft:-e.width,opacity:0}).data("$telerik.data",e).show();
}},animate:function(d,g,f){var e=d.data("$telerik.data");
if(f.reverseAnimation){d.transition({marginLeft:-e.width,opacity:0},g,f.easing);
}else{d.transition({marginLeft:0,opacity:100,width:e.width,height:e.height},g,f.easing);
}}},currentImage:{setup:function(d,f){var e={width:d.width(),height:d.height()};
if(f.reverseAnimation){d.css({marginLeft:-e.width,opacity:0}).data("$telerik.data",e).show();
}else{d.data("$telerik.data",e).show();
}},animate:function(d,g,f){var e=d.data("$telerik.data");
if(f.reverseAnimation){d.transition({marginLeft:0,opacity:100,width:e.width,height:e.height},g,f.easing);
}else{d.transition({marginLeft:-e.width,opacity:0},g,f.easing);
}}}});
b.RadImageAnimations.registerAnimation({name:"VerticalSlide",type:"Show",newImage:{setup:function(d,f){var e={width:d.width(),height:d.height()};
if(f.reverseAnimation){d.data("$telerik.data",e).show();
}else{d.css({marginTop:-e.height,opacity:0}).data("$telerik.data",e).show();
}},animate:function(d,g,f){var e=d.data("$telerik.data");
if(f.reverseAnimation){d.transition({marginTop:-e.height,opacity:0},g,f.easing);
}else{d.transition({marginTop:0,opacity:100,width:e.width,height:e.height},g,f.easing);
}}},currentImage:{setup:function(d,f){var e={width:d.width(),height:d.height()};
if(f.reverseAnimation){d.css({marginTop:-e.height,opacity:0}).data("$telerik.data",e).show();
}else{d.data("$telerik.data",e).show();
}},animate:function(d,g,f){var e=d.data("$telerik.data");
if(f.reverseAnimation){d.transition({marginTop:0,opacity:100,width:e.width,height:e.height},g,f.easing);
}else{d.transition({marginTop:-e.height,opacity:0},g,f.easing);
}}}});
})(Telerik.Web.UI,$telerik.$);
(function(b,a,c){Type.registerNamespace("Telerik.Web.UI");
b.RadImageAnimations.registerAnimation({name:"VerticalStripes",type:"Hide",iteration:"Grow",currentImage:{options:{horizontalSlices:10,verticalSlices:1},setup:function(d,e){if(e.reverseAnimation){var f=d.width();
d.data("$telerik.data",d.width());
d.css({opacity:0,width:f*0.7,marginLeft:f*0.12});
}},animate:function(d,f,e){var g=d.width();
if(e.reverseAnimation){g=d.data("$telerik.data");
d.transition({opacity:1,width:g,marginLeft:0},f,e.easing);
}else{d.transition({opacity:0,width:g*0.7,marginLeft:g*0.12},f,e.easing);
}}}});
b.RadImageAnimations.registerAnimation({name:"HorizontalStripes",type:"Hide",iteration:"Grow",currentImage:{options:{horizontalSlices:1,verticalSlices:10},setup:function(d,f){if(f.reverseAnimation){var e=d.height();
d.data("$telerik.data",d.height());
d.css({opacity:0,height:e*0.8,marginTop:e*0.12});
}},animate:function(d,g,f){var e=d.height();
if(f.reverseAnimation){e=d.data("$telerik.data");
d.transition({opacity:1,height:e,marginTop:0},g,f.easing);
}else{d.transition({opacity:0,height:e*0.8,marginTop:e*0.12},g,f.easing);
}}}});
b.RadImageAnimations.registerAnimation({name:"CollapsingVerticalStripes",type:"Hide",iteration:"Grow",currentImage:{options:{horizontalSlices:10,verticalSlices:1},setup:function(d,e){if(e.reverseAnimation){var f=d.width();
d.data("$telerik.data",{width:d.width(),height:d.height()});
d.css({opacity:0,width:f*0.7,height:0,marginLeft:f*0.12});
}},animate:function(d,g,f){var h=d.width();
if(f.reverseAnimation){var e=d.data("$telerik.data");
d.transition({opacity:1,width:e.width,height:e.height,marginLeft:0},g,f.easing);
}else{d.transition({opacity:0,width:h*0.7,height:0,marginLeft:h*0.12},g,f.easing);
}}}});
b.RadImageAnimations.registerAnimation({name:"CollapsingHorizontalStripes",type:"Hide",iteration:"Grow",currentImage:{options:{horizontalSlices:1,verticalSlices:10},setup:function(d,e){if(e.reverseAnimation){d.data("$telerik.data",{width:d.width(),height:d.height()});
d.css({opacity:0,width:0,height:0,marginLeft:0});
}},animate:function(d,h,g){var f=d.height();
if(g.reverseAnimation){var e=d.data("$telerik.data");
d.transition({opacity:1,width:e.width,height:e.height,marginTop:0},h,g.easing);
}else{d.transition({opacity:0,height:f*0.8,width:0,marginTop:f*0.12},h,g.easing);
}}}});
})(Telerik.Web.UI,$telerik.$);
(function(){})();
(function(b,a,e){Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.ImageAnimations");
var c=[[-1,0],[0,-1],[-1,-1],[-1,1],[1,-1],[1,0],[0,1],[1,1]];
b.RadImageAnimations.registerIteration({name:"Grow",options:{startX:0,startY:0},iterate:function(m,j,f){var q=j.speed,l=2,p=(Math.max(m.length,m[0].length)/2)+2,o=q/(p*l),n=q/p;
var k=[[Math.floor(0),Math.floor(0)]],r={},i,h=1,g=0;
r[0+","+0]=true;
while(k.length!=0){i=k.shift();
f(m[i[0]][i[1]],o*g,n*l);
d(k,r,i[0],i[1],m.length,m[0].length);
h--;
if(h==0){h=k.length;
g++;
}}}});
function d(l,n,m,f,k,j){var o,p,h;
for(var g=0;
g<c.length;
g++){o=m+c[g][0];
p=f+c[g][1];
h=o+","+p;
if(o>=0&&p>=0&&o<k&&p<j&&!n[h]){l.push([Math.floor(o),Math.floor(p)]);
n[h]=true;
}}}})(Telerik.Web.UI,$telerik.$);
(function(){})();
(function(){})();
