Type.registerNamespace("Telerik.Web.UI.Editor.Modules.DomInspector");
(function(a,g,b,e){var d="&nbsp;";
var c="reModule reHTMLStructure reRow reCaptionRow";
var f=Telerik.Web.UI.Editor.Utils;
b.BaseView=function(h){var i=this;
i.owner=h;
i._element=h?h.get_element():null;
i._removeNodeClass="RemoveElement";
i._selectedNodeClass="";
i._nodeClass="";
i._separatorContent="";
};
b.BaseView.prototype={initialize:function(){},dispose:function(){delete this.owner;
},createRemoveNode:function(h){var j=this;
var i=document.createElement("a");
i.innerHTML=h||j.owner._removeElementString;
i.href="javascript:void(0)";
i.className=this._removeNodeClass;
a(i).appendTo(j.get_element());
return i;
},createElementsNode:function(h,j){var k=this;
var i=document.createElement("a");
i.oncontextmenu=$telerik.cancelRawEvent;
i.href="javascript:void(0);";
i.innerHTML=h;
i.className=this._getElemNodeClass(j);
a(i).appendTo(k.get_element());
this.createSeparator();
return i;
},createSeparator:function(){var i=this;
var h=document.createElement("span");
h.innerHTML=this._separatorContent;
a(h).appendTo(i.get_element());
return h;
},isClickableNode:function(h){return f.isTag(h,"a")||this.isDeleteBtn(h);
},isDeleteBtn:function(h){return h.innerHTML===this.owner._getLocalizedString("DomInspectorRemoveElement","Remove Element");
},getRootClassName:function(){return"";
},_getElemNodeClass:function(h){},render:function(){a(this.get_element()).addClass(c);
},clear:function(){a(this._element).html(d);
},get_element:function(){return this._element;
},onShow:function(){}};
b.BaseView.registerClass("Telerik.Web.UI.Editor.Modules.DomInspector.BaseView");
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.Editor.Modules.DomInspector);
Type.registerNamespace("Telerik.Web.UI.Editor.Modules.DomInspector");
(function(a,d,b,c){b.ClassicView=function(e){var f=this;
b.ClassicView.initializeBase(f,[e]);
f._removeNodeClass="reModule_domlink";
f._selectedNodeClass="reModule_domlink_selected";
f._nodeClass="reModule_domlink";
f._separatorContent="&nbsp;> ";
};
b.ClassicView.prototype={getRootClassName:function(){return"reModule";
},_getElemNodeClass:function(e){return e?this._selectedNodeClass:this._nodeClass;
}};
b.ClassicView.registerClass("Telerik.Web.UI.Editor.Modules.DomInspector.ClassicView",Telerik.Web.UI.Editor.Modules.DomInspector.BaseView);
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.Editor.Modules.DomInspector);
Type.registerNamespace("Telerik.Web.UI.Editor.Modules.DomInspector");
(function(a,d,b,c){b.LightweightView=function(e){var f=this;
b.LightweightView.initializeBase(f,[e]);
f._removeNodeClass="reRemoveDOMElement";
f._selectedNodeClass="reDOMElementSelected";
f._nodeClass="reDOMElement";
f._separatorContent="&gt;";
};
b.LightweightView.prototype={getRootClassName:function(){return"reModule reHTMLStructure reRow reCaptionRow";
},_getElemNodeClass:function(f){var e=this._nodeClass;
if(f){e+=" "+this._selectedNodeClass;
}return e;
}};
b.LightweightView.registerClass("Telerik.Web.UI.Editor.Modules.DomInspector.LightweightView",Telerik.Web.UI.Editor.Modules.DomInspector.BaseView);
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.Editor.Modules.DomInspector);
(function(a,o){Type.registerNamespace("Telerik.Web.UI.Editor.Modules.DomInspector");
var c=Telerik.Web.UI;
var g=c.Editor;
var b=g.Modules.DomInspector;
var l=50;
var h=Sys.UI.DomElement.containsCssClass;
var e=".reDomElement";
var i=".reIcon";
var f=".reDom";
var p="reModule t-hbox";
var m="reDomElementSelected";
var d="reIconDelete";
var j="reScrollLeft";
var k="reScrollRight";
b.Templates={DomElementsContainerTemplate:'<div class="reDomWrapper reScrollLeft reScrollRight t-flex"><div class="reDom"/></div>',DomElementTemplate:'<a  href="#" class="reDomElement"/>',RemoveDomElementTemplate:'<span class="reDelete" title="DeleteElement" role="button"><span class="reIcon reIconDelete"></span></span>',SeparatorTemplate:"<span>&gt;</span>"};
var n=b.Templates;
b.MobileView=function(q){var r=this;
b.MobileView.initializeBase(r,[q]);
r._domElementLinksContainer=null;
r._removeDomElementLinkTool=null;
};
b.MobileView.prototype={initialize:function(){b.MobileView.callBaseMethod(this,"initialize");
},dispose:function(){if(this.list){this.list.off("scroll");
this.list=o;
}this.container=o;
this._domElementLinksContainer=o;
b.MobileView.callBaseMethod(this,"dispose");
},createElementsNode:function(q,s){var t=this;
var r=a(n.DomElementTemplate).html(q).appendTo(t._domElementLinksContainer);
if(s){r.addClass(m);
}else{this.createSeparator();
}return r;
},createRemoveNode:function(){var q=this;
q._removeDomElementLinkTool=a(n.RemoveDomElementTemplate).appendTo(q.get_element()).get(0);
return q._removeDomElementLinkTool;
},createSeparator:function(){var r=this;
var q=a(n.SeparatorTemplate).appendTo(r._domElementLinksContainer).get(0);
return q;
},render:function(){var t=this;
var r=t.get_element();
a(r).addClass(p);
var q=t.container=a(n.DomElementsContainerTemplate).appendTo(r);
var s=t.list=q.children(f).first();
s.stopScroll(Function.createDelegate(this,this._onScroll),l);
t._domElementLinksContainer=s.get(0);
},onShow:function(){this._onScroll();
},isDeleteBtn:function(q){return h(q,d);
},clear:function(){var q=this;
a(q._domElementLinksContainer).empty();
a(q._removeDomElementLinkTool).remove();
},_getDomElementLinksContainer:function(){return this._domElementLinksContainer;
},_getRemoveNodeTool:function(){return this._removeDomElementLinkTool;
},_getRemoveNodeToolIcon:function(){return a(this._getRemoveNodeTool()).children(i).get(0);
},_getDomElementLinks:function(){return a(this._getDomElementLinksContainer()).children(e);
},_onScroll:function(){var q=this.container;
var r=this._domElementLinksContainer;
var s=function(t,u){if(u){q.addClass(t);
}else{q.removeClass(t);
}};
s(j,r.scrollLeft>0);
s(k,(r.scrollWidth-r.scrollLeft)>r.clientWidth);
}};
a.fn.stopScroll=function(q,r){return this.scroll(a.debounce(r||250,q||Function.emptyFunction));
};
b.MobileView.registerClass("Telerik.Web.UI.Editor.Modules.DomInspector.MobileView",b.BaseView);
})($telerik.$);
(function(a,e){Type.registerNamespace("Telerik.Web.UI.Editor.Modules.DomInspector");
var c=Telerik.Web.UI;
var d=c.RenderMode;
var b=c.Editor.Modules.DomInspector;
b.ViewFactory={getView:function(f){var g=f.get_editor().get_renderMode();
switch(g){case d.Classic:return new b.ClassicView(f);
case d.Lite:return new b.LightweightView(f);
case d.Mobile:return new b.MobileView(f);
default:return null;
}}};
})($telerik.$);
Type.registerNamespace("Telerik.Web.UI.Editor.Modules.NodeInspector");
(function(a){Telerik.Web.UI.Editor.Modules.NodeInspector.ToolsController=function(b){this._tools=b;
};
Telerik.Web.UI.Editor.Modules.NodeInspector.ToolsController.prototype={initialize:function(){},dispose:function(){delete this._tools;
},update:function(e,d){var c=this._tools[e],b=d.getAttribute?d.getAttribute(e):null;
if(c){if(typeof(this["_"+e])==="function"){this["_"+e](c,d);
}else{if(c.set_value){c.set_value(b||"");
}}}},_noWrap:function(b,c){var d=(c.style.whiteSpace=="nowrap")?"nowrap":"";
if(!d){d=c.noWrap;
}b.set_value(d);
},_border:function(b,c){var d=parseInt(c.style.borderWidth,10);
if(isNaN(d)){d="";
}b.set_value(d);
},_bgColor:function(b,c){this._setColor("backgroundColor",b,c);
},_borderColor:function(b,c){this._setColor("borderColor",b,c);
},_setColor:function(b,c,d){var f=d.style[b];
if(!f){f=d.getAttribute(b);
}if(f){var e=f.indexOf(")");
if(e!=-1){f=f.substring(0,e+1);
}}c.set_color(f);
},_align:function(c,d){var g=d.tagName.toLowerCase();
switch(g){case"img":c.updateValue("",null);
var e=($telerik.isIE)?"styleFloat":"cssFloat";
var f=(typeof(d.style[e])=="undefined")?"":d.style[e];
var j=(typeof(d.style.verticalAlign)=="undefined")?"":d.style.verticalAlign;
if(j==""&&f!=""){switch(f){case"left":c.updateValue("left",null);
break;
case"right":c.updateValue("right",null);
break;
}}if(f==""){switch(j){case"top":c.updateValue("top",null);
break;
case"middle":c.updateValue("absmiddle",null);
break;
case"text-bottom":c.updateValue("bottom",null);
break;
}}break;
case"td":case"th":var h=d.style.textAlign;
var k=d.style.verticalAlign;
var b=d.getAttribute("align");
var i=d.getAttribute("vAlign");
if((h=="left"||h=="center"||h=="right")&&(k=="top"||k=="middle"||k=="bottom")){c.updateValue(h,k);
}else{if(b||i){c.updateValue(b,i);
}else{c.updateValue(null,null);
}}break;
default:c.updateValue(d.getAttribute("align"),d.getAttribute("vAlign"));
break;
}},_target:function(b,c){var d=c.getAttribute("target");
b.updateValue(d||"");
},_width:function(b,c){this._setDimention("width",b,c);
},_height:function(b,c){this._setDimention("height",b,c);
},_setDimention:function(b,c,d){var e=d.style[b];
if(!e){e=d.getAttribute(b);
}if(!e&&d.nodeName=="IMG"){e=(b=="width")?d.offsetWidth:d.offsetHeight;
}c.set_value(e);
},_name:function(b,c){b.set_value(c.name);
},_className:function(c,d){var b=d.getAttribute("class");
if(!b){b="";
}c.updateValue(b);
}};
})();
Type.registerNamespace("Telerik.Web.UI.Editor.Modules.NodeInspector");
(function(a,d,b,c){b.ClassicView=function(e){this.owner=e;
};
b.ClassicView.prototype={initialize:function(){},dispose:function(){delete this.owner;
},createUI:function(){var o=this.owner;
var f=o._tools;
var k=o._nodeInspectorAttributesArray;
var l=document.createElement("table");
l.border=0;
l.cellSpacing=0;
l.cellPadding=0;
for(var p=0;
p<k.length;
p++){var g=k[p];
var n=l.insertRow(-1);
for(var h=0;
h<g.length;
h++){var j=g[h];
var m=n.insertCell(-1);
m.style.display="none";
m.setAttribute("controlName",j);
m.innerHTML=o._getLocalizedString(j,j);
m.className="reModuleLabel";
m=n.insertCell(-1);
m.style.display="none";
m.setAttribute("controlHolder",j);
var e=o._getControlByName(j);
if(e){f[j]=e;
m.appendChild(e.get_element());
}}}return l;
},updateControls:function(w){var u=this.owner;
var k=u._nodeAttributesArray[w.tagName];
var p=u._mainPanel;
var l=u._tools;
for(var v=0;
v<p.rows.length;
v++){var s=p.rows[v];
for(var n=0;
n<s.cells.length;
n++){var r=s.cells[n];
var h=r.getAttribute("controlName");
if(h){r.style.display=u._arrayValueExists(h,k)?"":"none";
}var g=r.getAttribute("controlHolder");
if(g){r.style.display=u._arrayValueExists(g,k)?"":"none";
if("none"==r.style.display){continue;
}var j=l[g];
var f=w.getAttribute?w.getAttribute(g,2):"";
var t;
if(g=="noWrap"){var q=(w.style.whiteSpace=="nowrap")?"nowrap":"";
if(!q){q=w.noWrap;
}j.set_value(q);
}else{if(g=="border"){t=parseInt(w.style.borderWidth,10);
if(isNaN(t)){t="";
}j.set_value(t);
}else{if(g=="borderColor"||g=="bgColor"){if(g=="bgColor"){g="backgroundColor";
}t=w.style[g];
if(!t){t=w.getAttribute(g);
}if(t){var o=t.indexOf(")");
if(o!=-1){t=t.substring(0,o+1);
}}j.set_color(t);
}else{if(g=="align"){var z=w.tagName.toLowerCase();
switch(z){case"img":j.updateValue("",null);
var m=($telerik.isIE)?"styleFloat":"cssFloat";
var y=(typeof(w.style[m])=="undefined")?"":w.style[m];
var D=(typeof(w.style.verticalAlign)=="undefined")?"":w.style.verticalAlign;
if(D==""&&y!=""){switch(y){case"left":j.updateValue("left",null);
break;
case"right":j.updateValue("right",null);
break;
}}if(y==""){switch(D){case"top":j.updateValue("top",null);
break;
case"middle":j.updateValue("absmiddle",null);
break;
case"text-bottom":j.updateValue("bottom",null);
break;
}}break;
case"td":case"th":var B=w.style.textAlign;
var E=w.style.verticalAlign;
var e=w.getAttribute("align");
var C=w.getAttribute("vAlign");
if((B=="left"||B=="center"||B=="right")&&(E=="top"||E=="middle"||E=="bottom")){j.updateValue(B,E);
}else{if(e||C){j.updateValue(e,C);
}else{j.updateValue(null,null);
}}break;
default:j.updateValue(w.getAttribute("align"),w.getAttribute("vAlign"));
break;
}}else{if(g=="target"){var A=w.getAttribute(g);
j.updateValue(A||"");
}else{if(g=="width"||g=="height"){var x=w.style[g];
if(!x){x=w.getAttribute(g);
}if(!x&&w.nodeName=="IMG"){x=(g=="width")?w.offsetWidth:w.offsetHeight;
}j.set_value(x);
}else{if("name"==g.toLowerCase()){j.set_value(w.name);
}else{if("className"==g){if(!u.isIE){f=w.getAttribute("class");
}if(!f){f="";
}j.updateValue(f);
}else{if(f&&j.set_value){j.set_value(f);
}else{if(j.set_value){j.set_value("");
}}}}}}}}}}}}}}};
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.Editor.Modules.NodeInspector);
Type.registerNamespace("Telerik.Web.UI.Editor.Modules.NodeInspector");
(function(a,d,b,c){b.LightweightView=function(e){this.owner=e;
};
b.LightweightView.prototype={initialize:function(){},dispose:function(){delete this.owner;
},createUI:function(){var m=this.owner;
var f=m._tools;
var l=m._nodeInspectorAttributesArray;
var p=document.createElement("div");
for(var n=0;
n<l.length;
n++){var g=l[n];
var o=document.createElement("div");
o.className="reRow reAltRow";
p.appendChild(o);
for(var h=0;
h<g.length;
h++){var j=g[h];
var k=document.createElement("span");
k.setAttribute("controlName",j);
k.className="reLabel";
k.innerHTML=m._getLocalizedString(j,j);
o.appendChild(k);
var e=m._getControlByName(j);
if(e){f[j]=e;
o.appendChild(e.get_element());
}}}return p;
},updateControls:function(f){var e=this.owner;
var g=e._tools;
var h=new Telerik.Web.UI.Editor.Modules.NodeInspector.ToolsController(g);
a(e._mainPanel).find("span").each(function(k,m){var l=a(m);
var i=null;
var j=l.attr("controlName");
if(j){l.css("display","none");
i=g[j];
if(i){a(i.get_element()).css("display","none");
if(a.inArray(j,e._nodeAttributesArray[f.tagName])>-1){l.css("display","");
a(i.get_element()).css("display","");
h.update(j,f);
}}}});
}};
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.Editor.Modules.NodeInspector);
Type.registerNamespace("Telerik.Web.UI.Editor.Modules.NodeInspector");
(function(a,d,b,c){b.ViewFactory=function(){};
b.ViewFactory.getView=function(f){var e=d.RenderMode,g=f.get_editor().get_renderMode();
var h=null;
if(g==e.Lite){h=new b.LightweightView(f);
}else{if(g==e.Classic){h=new b.ClassicView(f);
}}return h;
};
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.Editor.Modules.NodeInspector);
(function(a,b){Type.registerNamespace("Telerik.Web.UI.Editor");
Type.registerNamespace("Telerik.Web.UI.Editor.Modules");
Telerik.Web.UI.Editor.ModulesManager=function(c){this._editor=c;
this._modules=[];
this._onEditorModeChangeDelegate=Function.createDelegate(this,this._onEditorModeChange);
};
Telerik.Web.UI.Editor.ModulesManager.prototype={initialize:function(){this.createModules();
this._editor.add_modeChange(this._onEditorModeChangeDelegate);
},getModuleByName:function(d){for(var c=0;
c<this._modules.length;
c++){if(this._modules[c].get_name()==d){return this._modules[c];
}}return null;
},createModules:function(){if(!this._editor){return;
}var d=this._editor.get_modulesJSON();
for(var c=0;
c<d.length;
c++){if(d[c].name!="RadEditorTrackChangesInfo"||this._editor.get_enableComments()||this._editor.get_enableTrackChanges()){this.createModule(d[c]);
}}},createModule:function(c){if(c.attributes){for(var h in c.attributes){c[h.toLowerCase()]=c.attributes[h];
}}var g=c.enabled;
if(false==g){return;
}c.editor=this._editor;
var j=c.name;
if(j){c.title=this._editor.getLocalizedString(j);
}var d=null;
try{d=eval("Telerik.Web.UI.Editor.Modules."+j);
}catch(f){}if(!d){try{d=eval(j);
}catch(f){}}if(d){var i=document.createElement("div");
var k=this._getModuleZone(c.dockingzone);
delete c.dockingzone;
delete c.dockable;
if(k){if(k.innerHTML=="&nbsp;"||k.innerHTML.length==1){k.innerHTML="";
}k.appendChild(i);
}this._modules[this._modules.length]=$create(d,c,null,null,i);
}},_getModuleZone:function(e){var c=this._editor;
if(c.get_renderMode()===Telerik.Web.UI.RenderMode.Mobile){return a(c.get_element()).find(".reModules").get(0);
}else{var d=this._editor.get_id();
var f=$get(d+e);
if(!f){f=$get(d+"Module");
}return f;
}},_onEditorModeChange:function(f,c){var d=Telerik.Web.UI.EditModes;
var e=f.get_mode();
this.setModulesVisible((e==d.Design));
},setModulesVisible:function(c){var f=this._modules;
var d=false;
var e;
if(!c&&this._enabledModules==null){d=true;
this._enabledModules={};
for(e=0;
e<f.length;
e++){var g=f[e];
if(g.get_visible()){this._enabledModules[g.get_name()]=true;
}g.set_visible(false);
}}else{if(c&&this._enabledModules){d=true;
for(e=0;
e<f.length;
e++){var h=f[e];
var j=this._enabledModules[h.get_name()];
if(j){h.set_visible(true);
}}this._enabledModules=null;
}}if(d){this._fixIEBottomZoneDisplacement(c);
}},_fixIEBottomZoneDisplacement:function(d){if($telerik.isIE&&this._editor.get_renderMode()==Telerik.Web.UI.RenderMode.Classic){if(!this._emptySpan){this._emptySpan=document.createElement("span");
var c=this._getModuleZone("Bottom");
if(c){var e=this._emptySpan;
e.innerHTML="&nbsp;";
e.style.display="none";
c.appendChild(e);
}}this._emptySpan.style.display=d?"none":"";
}},get_modules:function(){return this._modules;
}};
Telerik.Web.UI.Editor.ModulesManager.registerClass("Telerik.Web.UI.Editor.ModulesManager",null);
Telerik.Web.UI.Editor.Modules.ModuleBase=function(c){var d=this;
Telerik.Web.UI.Editor.Modules.ModuleBase.initializeBase(this,[c]);
this._editor=null;
this._name="";
this._visible=true;
this._enabled=true;
this._rendered=false;
this._enableMaxWidth=true;
this._title="";
this._className="reModule";
this._scriptFile="";
this._attributes={};
this.isSafari=$telerik.isSafari;
this.isIE=$telerik.isIE;
this.isOpera=$telerik.isOpera;
this.isFirefox=$telerik.isFirefox;
d._view=null;
};
Telerik.Web.UI.Editor.Modules.ModuleBase.prototype={initialize:function(){Telerik.Web.UI.Editor.Modules.ModuleBase.callBaseMethod(this,"initialize");
if(this.get_visible()){this.render();
this.attachEventHandlers();
}},render:function(){if(this._view){this._view.render();
}else{var c=this.get_element();
if(c){c.className=this._className;
}}this._rendered=true;
},attachEventHandlers:function(){},detachEventHandlers:function(){},toggleVisibility:function(){this.set_visible(!this.get_visible());
},attachEventHandler:function(e,d){var c=this.get_editor();
if(c){c.attachInternalHandler(e,d);
}},_getLocalizedString:function(d,c){return this._editor.getLocalizedString(d,c);
},get_editor:function(){return this._editor;
},set_editor:function(c){this._editor=c;
},get_attributes:function(){return this._attributes;
},set_attributes:function(c){this._attributes=c;
},get_scriptFile:function(){return this._scriptFile;
},set_scriptFile:function(c){this._scriptFile=c;
},get_visible:function(){var c=this.get_element();
if(!c){return false;
}return(c.style.display!="none");
},set_visible:function(c){if(c&&!this._rendered){this.render();
}var d=this.get_element();
d.style.display=c?"":"none";
if(c){this.onShow();
}},get_enabled:function(){return this._enabled;
},set_enabled:function(c){this._enabled=c;
},get_title:function(){return this._title;
},set_title:function(c){this._title=c;
},get_name:function(){return this._name;
},set_name:function(c){this._name=c;
},onShow:function(){},dispose:function(){this.detachEventHandlers();
Telerik.Web.UI.Editor.Modules.ModuleBase.callBaseMethod(this,"dispose");
}};
Telerik.Web.UI.Editor.Modules.ModuleBase.registerClass("Telerik.Web.UI.Editor.Modules.ModuleBase",Sys.UI.Control);
})($telerik.$);
(function(a,k){Type.registerNamespace("Telerik.Web.UI");
var c=Telerik.Web.UI;
var l=c.Editor.Utils;
var h=l.isTag;
var e=Sys.UI.DomElement;
var d=e.addCssClass;
var i=e.removeCssClass;
var f=e.containsCssClass;
var b=c.Editor.Modules;
var j=3;
var g="RadEDomMouseOver";
b.RadEditorDomInspector=function(m){b.RadEditorDomInspector.initializeBase(this,[m]);
};
b.RadEditorDomInspector.prototype={initialize:function(){this._onSelectionChangeHandler=Function.createDelegate(this,this._onSelectionChange);
this._editorPathArray=[];
this._removeElementString=this._getLocalizedString("DomInspectorRemoveElement","Remove Element");
this._view=b.DomInspector.ViewFactory.getView(this);
b.RadEditorDomInspector.callBaseMethod(this,"initialize");
},dispose:function(){var m=this;
m.clear();
if(m._view){m._view.dispose();
delete m._view;
}b.RadEditorDomInspector.callBaseMethod(m,"dispose");
},render:function(){var m=this;
b.RadEditorDomInspector.callBaseMethod(m,"render");
m.clear();
m.get_editor().add_selectionChange(m._onSelectionChangeHandler);
m.showDomPath();
},get_visible:function(){var m=this.get_editor();
if(m.get_renderMode()!=c.RenderMode.Mobile){return b.RadEditorDomInspector.callBaseMethod(this,"get_visible");
}var n=this.get_element();
return !$telerik.getInvisibleParent(n)&&!$telerik.getHiddenParent(n);
},attachEventHandlers:function(){this._registerMouseHandlers(true);
},detachEventHandlers:function(){this._registerMouseHandlers(false);
},_onSelectionChange:function(){var m=this;
setTimeout(function(){m.showDomPath();
},50);
},_registerMouseHandlers:function(m){var o=this.get_element();
if(true==m){var n={click:this._onMouseClick,mouseover:this._onMouseOver,mouseout:this._onMouseOut};
$addHandlers(o,n,this);
}else{if(o){$clearHandlers(o);
}}},_highlightNode:function(m){d(m,g);
},_removeNodeHighlight:function(m){if(!f(m,g)){return;
}i(m,g);
if(""==m.className){m.removeAttribute("className",0);
m.removeAttribute("class",0);
}},_onMouseOver:function(n){try{var m=this._getReferredEditorElement(n);
if(!m||this._isSelectedElement(m)){return;
}Sys.UI.DomElement.addCssClass(m,"RadEDomMouseOver");
}catch(o){}},_onMouseOut:function(n){var m=this._getReferredEditorElement(n);
if(!m){return;
}try{Sys.UI.DomElement.removeCssClass(m,"RadEDomMouseOver");
if(""==m.className){m.removeAttribute("className",0);
m.removeAttribute("class",0);
}}catch(o){}},_onMouseClick:function(m){var p=m.target;
var q=this._view;
if(!p||!q||!q.isClickableNode(p)){return null;
}if(q.isDeleteBtn(p)){var n=this._editorPathArray[0];
this.removeSelectedElement(n);
}else{var o=this._getReferredEditorElement(m);
this.selectElement(o);
}this._updateTabChooser();
return $telerik.cancelRawEvent(m);
},_updateTabChooser:function(){var m=this.get_editor();
var o=m.get_toolAdapter();
if(o.get_tabChooser){var n=o.get_tabChooser();
n.selectContextualTab(l.getSelectedElement(m));
}},clear:function(){this.detachEventHandlers();
if(this._view){this._view.clear();
}this._editorPathArray=[];
},_createRemoveNodeLink:function(){var m=this;
var n=m._view;
if(n){n.createRemoveNode();
}},addDomCouple:function(m,n){if(!m||!m.tagName){return;
}if(this._view){this._view.createElementsNode(m.tagName,n);
}},_getPathArray:function(o,n){var m=[];
var p=this._isMarker;
if(o&&o.nodeType==j){o=o.parentNode;
}while(o&&o!=n){if(!p(o)){m.push(o);
}o=o.parentNode;
}return m;
},_isMarker:function(m){return a(m).is(".__reTextHighlight,.__reHighlightMarker");
},_isSelectedElement:function(n){var m=this._editorPathArray;
if(m&&m[0]==n){return true;
}},_getReferredEditorElement:function(m){var r=m.target;
if(!r||r.tagName!="A"){return null;
}var p=this.get_element().getElementsByTagName("A");
var o=-1;
for(var n=0;
n<p.length;
n++){if(p[n]==r){o=n;
break;
}}if(o>-1){var q=this._editorPathArray.concat([]).reverse();
return q[o];
}},showDomPath:function(){if(!this.get_visible()){return;
}try{var n=this.get_editor();
var o=n.getSelectedElement();
if(!o){return;
}var m=n.get_contentArea();
if(!$telerik.$.contains(m,o)){this.renderPath(m);
}this.renderPath(o);
}catch(p){}},renderPath:function(m){this.clear();
this._renderPath(m);
},onShow:function(){if(this._view){this._view.onShow();
}},selectElement:function(o){try{var n=this.get_editor();
this._removeNodeHighlight(o);
this._selectedElement=o;
if(n.get_renderMode()===c.RenderMode.Mobile){this.selectElementMobile(o);
}else{var m=o.childNodes;
if(m.length===1&&h(m[0],"img")){n.selectElement(o);
}else{n.selectElementContents(o);
}this.showDomPath();
}this._selectedElement=null;
}catch(p){}},selectElementMobile:function(n){var m=this.get_editor();
var p=m.get_toolAdapter();
p._removeSelectionHighlight();
var s=m.getDomRange();
var t=function(v){return h(n,v);
};
if(t("table")||t("ul")||t("ol")){s.selectNode(n);
}else{if(t("tr")||t("tbody")||t("thead")){var u=n.getElementsByTagName("td");
var o=u[0];
var q=u[u.length-1];
var r=q.childNodes[q.childNodes.length-1];
if(l.isTextNode(r)){r=q;
}s.setStart(o,0);
s.setEnd(r,r.childNodes.length);
}else{s.selectNodeContents(n);
}}s.select();
m.raiseEvent("selectionChange",Sys.EventArgs.Empty);
p._highlightSelection();
this.renderPath(n);
},removeSelectedElement:function(p){var o=this.get_editor();
var r=function(s){return h(p,s);
};
var n;
try{if(r("TD")||r("TH")){o.fire("DeleteCell");
}else{if(r("TR")){var m=p.getElementsByTagName("td");
if(m.length){this.selectElement(m[0]);
o.fire("DeleteRow");
}}else{if(r("TABLE")||r("TBODY")||r("THEAD")||r("TFOOT")||r("EMBED")||r("OBJECT")||r("INPUT")||r("IMG")||r("HR")){n=new Telerik.Web.UI.Editor.GenericCommand(this._removeElementString,o.get_contentWindow(),o);
window.setTimeout(function(){p.parentNode.removeChild(p);
o.setFocus();
o.executeCommand(n);
o.raiseEvent("selectionChange");
},0);
}else{if(p!==o.get_contentArea()){n=new Telerik.Web.UI.Editor.GenericCommand(this._removeElementString,o.get_contentWindow(),o);
Telerik.Web.UI.Editor.Utils.removeNode(p);
o.setFocus();
o.executeCommand(n);
}}}}}catch(q){}o.raiseEvent("selectionChange");
},_renderPath:function(p){var o=this.get_editor();
var n=o.get_contentArea();
if(o.get_enableImmutableElements()&&l.isImmutableNode(p)){return;
}this._editorPathArray=this._getPathArray(p,n);
var m=this._editorPathArray;
for(var q=m.length-1;
q>=0;
q--){this.addDomCouple(m[q],(q==0));
}this.attachEventHandlers();
if(m.length>0){this._createRemoveNodeLink();
}},_getDomElementLinks:function(){var m=this;
return m._view?m._view._getDomElementLinks():[];
},_getRemoveNodeTool:function(){var m=this;
return m._view?m._view._getRemoveNodeTool():null;
},_getRemoveNodeToolIcon:function(){var m=this;
return m._view?m._view._getRemoveNodeToolIcon():null;
}};
Telerik.Web.UI.Editor.Modules.RadEditorDomInspector.registerClass("Telerik.Web.UI.Editor.Modules.RadEditorDomInspector",Telerik.Web.UI.Editor.Modules.ModuleBase);
})($telerik.$);
(function(a,h){var f=a.proxy;
var b=Telerik.Web.UI.Editor;
var c=b.Modules;
var e=".htmlInspector";
var d="keyup";
var g="textarea";
c.RadEditorHtmlInspector=function(i){var j=this;
j._textarea=null;
c.RadEditorHtmlInspector.initializeBase(j,[i]);
};
c.RadEditorHtmlInspector.prototype={initialize:function(){var i=this;
i._selectionChangeHandler=Function.createDelegate(i,i._selectionChange);
c.RadEditorHtmlInspector.callBaseMethod(this,"initialize");
},dispose:function(){var k=this;
var j=k.get_editor();
var i=j.get_contentArea();
a(k._textarea).off(e);
a(k._textarea).remove();
k._textarea=null;
a(i).off(d+e);
c.RadEditorHtmlInspector.callBaseMethod(this,"dispose");
},set_visible:function(i){c.RadEditorHtmlInspector.callBaseMethod(this,"set_visible",[i]);
if(i){this._selectionChange();
}},render:function(){var l=this;
var k=l.get_element();
var j=l.get_editor();
var i=j.get_contentArea();
var m;
c.RadEditorHtmlInspector.callBaseMethod(l,"render");
m=document.createElement(g);
m.style.width="99%";
m.className="reTextarea";
m.setAttribute("rows","10");
m.setAttribute("cols","80");
a(m).on(d+e,f(l.updateEditorContent,l));
l._textarea=m;
l._updateContent();
a(k).append(m);
j.add_selectionChange(l._selectionChangeHandler);
a(i).off(d+e);
a(i).on(d+e,f(l._updateContent,l));
},updateEditorContent:function(){var j=this;
var i=j.get_editor();
if(!j.get_visible()){return;
}i.set_html(a(j._textarea).val(),j._getLocalizedString("Typing"),false,false);
if(i.get_enableImmutableElements()){b.Utils.revertOriginalImmutables(i);
}},_selectionChange:function(){this._updateContent();
},_updateContent:function(){var k=this;
var i=k.get_editor();
var j=a(i.get_contentArea()).html();
a(k._textarea).val(j);
}};
c.RadEditorHtmlInspector.registerClass("Telerik.Web.UI.Editor.Modules.RadEditorHtmlInspector",c.ModuleBase);
})($telerik.$);
Telerik.Web.UI.Editor.Modules.RadEditorNodeInspector=function(a){Telerik.Web.UI.Editor.Modules.RadEditorNodeInspector.initializeBase(this,[a]);
this._updateMainPanelDelegate=Function.createDelegate(this,this._updateMainPanel);
this._onToolValueSelectedDelegate=Function.createDelegate(this,this._onToolValueSelected);
this._onDropDownBeforeShowDelegate=Function.createDelegate(this,this._onDropDownBeforeShow);
this._tools={};
this._toolNames={};
this._selectedElement=null;
this._view=null;
};
Telerik.Web.UI.Editor.Modules.RadEditorNodeInspector.prototype={_nodeAttributesArray:{TABLE:["width","borderColor","cellSpacing","bgColor","className","SetTableProperties","height","cellPadding","align","border"],TH:["width","borderColor","bgColor","className","SetCellProperties","height","align","noWrap","border"],TD:["width","borderColor","bgColor","className","SetCellProperties","height","align","noWrap","border"],TR:["width","className","height"],A:["href","className","LinkManager","title","target","id"],IMG:["width","borderColor","className","SetImageProperties","height","align","border","alt","title"],INPUT:["NAME","width","height","id","title","className","value"],BUTTON:$telerik.isIE&&!$telerik.isIE9Mode?null:["NAME","width","height","id","title","className","value"],FORM:["className","width","height","NAME","action","id"],TEXTAREA:["className","width","height","NAME","id","rows","cols"]},_nodeInspectorAttributesArray:[["rows","NAME","width","cellSpacing","borderColor","href","alt","align","value","target","SetTableProperties","SetCellProperties","LinkManager"],["cols","id","height","action","cellPadding","border","bgColor","title","noWrap","className","SetImageProperties"]],initialize:function(){Telerik.Web.UI.Editor.Modules.RadEditorNodeInspector.callBaseMethod(this,"initialize");
this.get_editor().add_selectionChange(this._updateMainPanelDelegate);
this._invalidValueString=this._getLocalizedString("NodeInspectorInvalidValue","Invalid value. Please enter a number.");
this._view=Telerik.Web.UI.Editor.Modules.NodeInspector.ViewFactory.getView(this);
},render:function(){Telerik.Web.UI.Editor.Modules.RadEditorNodeInspector.callBaseMethod(this,"render");
var a=this.get_element();
a.style.height=this._getModuleHeight();
},_getModuleHeight:function(){var b=this.get_skin(),a;
switch(b){case"Glow":case"Silk":a=60;
break;
case"BlackMetroTouch":case"MetroTouch":a=75;
break;
case"Bootstrap":a=85;
break;
default:a=50;
break;
}return a+"px";
},get_skin:function(){return this._editor.get_skin();
},getNamedCssForSelectedElement:function(a){return this.get_editor().getCssArray(a);
},dispose:function(){this._tools=[];
this._mainPanel=null;
if(this._view){this._view.dispose();
this._view=null;
}Telerik.Web.UI.Editor.Modules.RadEditorNodeInspector.callBaseMethod(this,"dispose");
},_createMainPanel:function(){if(this._view){return this._view.createUI();
}},_updateMainPanel:function(){if(!this.get_visible()||!this._view){return;
}if(!this._isMainCreated){this._mainPanel=this._createMainPanel();
this._mainPanel.style.display="none";
this.get_element().appendChild(this._mainPanel);
this._isMainCreated=true;
}var c=this.get_editor();
var f=c.getSelectedElement();
var h=Telerik.Web.UI.Editor.Utils;
if(!f||h.isEditorContentArea(f)||f.ownerDocument!=c.get_document()||(c.get_enableImmutableElements()&&h.isImmutableNode(f))){this._mainPanel.style.display="none";
return;
}if(f.tagName=="TBODY"){f=f.parentNode;
}var a=this._nodeAttributesArray[f.tagName];
if(!a){var d=h.getElementParentByTag(f,"A");
if(!d){d=h.getElementParentByTag(f,"TD");
}if(!d){d=h.getElementParentByTag(f,"TH");
}if(d){f=d;
}else{this._mainPanel.style.display="none";
return;
}}var g=null;
if(this._selectedElement){try{g=this._selectedElement.tagName;
}catch(b){}}if(!this._selectedElement||(g!=f.tagName)){this._tools.align.setTagName(f.tagName);
}this._selectedElement=f;
this._updateControlValues(this._selectedElement);
this._mainPanel.style.display="";
},_arrayValueExists:function(b,a){return Array.contains(a,b);
},_issValidAttribValue:function(b){if(null==b){return false;
}b=b.trim();
if(""==b){return true;
}var a=parseInt(b,10);
if(isNaN(a)){return false;
}return true;
},_onDropDownBeforeShow:function(f,a){var c=this.get_editor();
var h=f.get_name();
var b=f.get_items();
if(b&&b.length>0){return;
}var d=null;
switch(h){case"className":var e=this._selectedElement;
var g=e&&e.tagName?e.tagName:"";
d=c.getCssArray(g);
break;
case"target":d=[["_blank",this._getLocalizedString("blank","New Window")],["_self",this._getLocalizedString("self","Same Window")],["_parent",this._getLocalizedString("parent","Parent window")],["_top",this._getLocalizedString("top","Top browser window")],["_search",this._getLocalizedString("search","Search pane")],["_media",this._getLocalizedString("media","Media pane")]];
break;
case"bgColor":case"borderColor":d=c.get_colors();
break;
}if(d){f.set_items(d);
}},_onToolValueSelected:function(b,a){if(b){if(Telerik.Web.UI.EditorDropDown.isInstanceOfType(b)||Telerik.Web.UI.EditorSpinBox.isInstanceOfType(b)||Telerik.Web.UI.EditorCheckBox.isInstanceOfType(b)||Telerik.Web.UI.EditorTextBox.isInstanceOfType(b)){this.fire(b);
}else{this.get_editor().fire(b.get_name());
}}},executeStyleRuleCommand:function(c,e,d,f){var b=this.get_editor();
var a=new Telerik.Web.UI.Editor.StyleRuleCommand(f,b.get_contentWindow(),c,e,d,b);
b.executeCommand(a);
},executeAttributeCommand:function(d,a,e,f){var c=this.get_editor();
var b=new Telerik.Web.UI.Editor.AttributeCommand(f,c.get_contentWindow(),d,a,e,c);
c.executeCommand(b);
},_updateControlValues:function(a){if(this._view){this._view.updateControls(a);
}},fire:function(i){if(!i){return;
}var e=i.get_name();
var l=this._getLocalizedString(e,e);
if(!l){l=e;
}var c,j;
var h=this._selectedElement;
if("AlignmentSelector"==e){var a=i.getAlign();
var m=i.getVAlign();
l=this._getLocalizedString("Align","Align");
var n=this._getLocalizedString("vAlign","vAlign");
var g=($telerik.isIE)?"styleFloat":"cssFloat";
var k=h.tagName.toLowerCase();
var d=false;
switch(k){case"img":switch(a){case"left":this.executeStyleRuleCommand(h,g,"left",l);
this.executeStyleRuleCommand(h,"verticalAlign","",l);
break;
case"right":this.executeStyleRuleCommand(h,g,"right",l);
this.executeStyleRuleCommand(h,"verticalAlign","",l);
break;
case"top":this.executeStyleRuleCommand(h,g,"",l);
this.executeStyleRuleCommand(h,"verticalAlign","top",l);
break;
case"bottom":this.executeStyleRuleCommand(h,g,"",l);
this.executeStyleRuleCommand(h,"verticalAlign","text-bottom",l);
break;
case"absmiddle":this.executeStyleRuleCommand(h,g,"",l);
this.executeStyleRuleCommand(h,"verticalAlign","middle",l);
break;
default:this.executeStyleRuleCommand(h,g,"",l);
this.executeStyleRuleCommand(h,"verticalAlign","",l);
break;
}d=true;
break;
case"td":case"th":this.executeStyleRuleCommand(h,"textAlign",a,l);
this.executeStyleRuleCommand(h,"verticalAlign",m,n);
d=true;
break;
default:this.executeAttributeCommand(h,"align",a,l);
this.executeAttributeCommand(h,"vAlign",m,n);
break;
}if(d){h.removeAttribute("align");
h.removeAttribute("vAlign");
}}else{if("borderColor"==e){j=i.get_selectedItem();
this.executeStyleRuleCommand(this._selectedElement,"borderColor",j,l);
h.removeAttribute("borderColor");
}else{if("bgColor"==e){j=i.get_selectedItem();
this.executeStyleRuleCommand(this._selectedElement,"backgroundColor",j,l);
h.removeAttribute("bgColor");
}else{if("border"==e){j=i.get_selectedItem();
if(!this._issValidAttribValue(j)){alert(this._invalidValueString);
return;
}if(j){j+="px";
this.executeStyleRuleCommand(this._selectedElement,"borderWidth",j,l);
this.executeStyleRuleCommand(this._selectedElement,"borderStyle","solid",l);
}else{this.executeStyleRuleCommand(this._selectedElement,"borderWidth","",l);
this.executeStyleRuleCommand(this._selectedElement,"borderStyle","",l);
}h.removeAttribute("border");
}else{if("width"==e||"height"==e){j=i.get_selectedItem();
if(!this._issValidAttribValue(j)){alert(this._invalidValueString);
return;
}var f=function(q){var p=""+q;
if(p.indexOf("%")!=-1){return p;
}else{var o=p.match(/(em|ex|px|in|cm|mm|pt|pc)$/);
p=parseInt(p,10);
if(!isNaN(p)){p=(o)?p+o[0]:p+"px";
return p;
}}return q;
};
j=f(j);
if(this._selectedElement.removeAttribute){this._selectedElement.removeAttribute(e);
}this.executeStyleRuleCommand(this._selectedElement,e,j,l);
}else{if("noWrap"==e){c=i.get_selectedItem();
if(c){this.executeStyleRuleCommand(this._selectedElement,"whiteSpace","nowrap",l);
}else{this.executeStyleRuleCommand(this._selectedElement,"whiteSpace","",l);
}}else{var b=e;
c=i.get_selectedItem();
switch(e){case"background":case"className":case"target":case"value":break;
case"cellSpacing":case"cellPadding":if(!this._issValidAttribValue(c)){alert(this._invalidValueString);
return;
}break;
case"NAME":if(!this.isIE){b="name";
}}this.executeAttributeCommand(h,b,c,l);
}}}}}}if(this._selectedElement){this._updateControlValues(this._selectedElement);
}if(this._selectedElement.style.cssText==""){this._selectedElement.removeAttribute("style");
}},_getControlByName:function(c){var a=null,d=Telerik.Web.UI.RenderMode.toString(this.get_editor()._renderMode)=="Lite"?"Lightweight":Telerik.Web.UI.RenderMode.toString(this.get_editor()._renderMode),e={text:this._getLocalizedString(c),name:c,addClickHandler:true,skin:this.get_skin()},b={valueSelected:this._onToolValueSelectedDelegate,show:this._onDropDownBeforeShowDelegate};
switch(c){case"className":e.text=this._getLocalizedString("className");
e.width="90px";
a=Telerik.Web.UI.Editor.UI.StaticToolsUI.createTool(d,e,b,Telerik.Web.UI.Editor.ApplyClassDropDown);
break;
case"borderColor":case"bgColor":e.addCustomColorText=this._getLocalizedString("AddCustomColor");
a=Telerik.Web.UI.Editor.UI.StaticToolsUI.createTool(d,e,b,Telerik.Web.UI.Editor.ColorPicker);
break;
case"align":e.name="AlignmentSelector";
e.text=this._getLocalizedString("align");
a=Telerik.Web.UI.Editor.UI.StaticToolsUI.createTool(d,e,b,Telerik.Web.UI.Editor.AlignmentSelector);
break;
case"SetCellProperties":case"SetTableProperties":case"SetImageProperties":case"LinkManager":delete b.show;
a=Telerik.Web.UI.Editor.UI.StaticToolsUI.createTool(d,e,b);
break;
case"target":e.sizetofit=true;
e.width="90px";
a=Telerik.Web.UI.Editor.UI.StaticToolsUI.createTool(d,e,b,Telerik.Web.UI.EditorUpdateableDropDown);
break;
case"noWrap":delete b.show;
a=Telerik.Web.UI.Editor.UI.StaticToolsUI.createTool(d,e,b,Telerik.Web.UI.EditorCheckBox,document.createElement("span"));
break;
case"width":case"height":case"cellPadding":case"cellSpacing":case"rows":case"cols":case"border":delete b.show;
a=Telerik.Web.UI.Editor.UI.StaticToolsUI.createTool(d,e,b,Telerik.Web.UI.EditorSpinBox,document.createElement("span"));
break;
default:delete b.show;
a=Telerik.Web.UI.Editor.UI.StaticToolsUI.createTool(d,e,b,Telerik.Web.UI.EditorTextBox,document.createElement("span"));
}return a;
}};
Telerik.Web.UI.Editor.Modules.RadEditorNodeInspector.registerClass("Telerik.Web.UI.Editor.Modules.RadEditorNodeInspector",Telerik.Web.UI.Editor.Modules.ModuleBase);
(function(a,b,d){var c=b.Modules;
var e=b.Utils;
c.RadEditorStatistics=function(f){c.RadEditorStatistics.initializeBase(this,[f]);
};
c.RadEditorStatistics.prototype={initialize:function(){this._enableMaxWidth=false;
this._wordsString=this._getLocalizedString("StatisticsWords","Words:");
this._charactersString=this._getLocalizedString("StatisticsCharacters","Characters:");
this._onDoCountDelegate=Function.createDelegate(this,this.doCount);
this._className+=" reStatistic";
c.RadEditorStatistics.callBaseMethod(this,"initialize");
},render:function(){c.RadEditorStatistics.callBaseMethod(this,"render");
this.get_editor().add_selectionChange(this._onDoCountDelegate);
this.doCount();
},_trimNewLineCharsRegExp:/(^[\n\r]+)|([\n\r]+$)/g,_punctRegExp:/[!\.?;,:&_\-\u2013\{\}\[\]\(\)~#'"]/g,_trimSpacesRegExp:/(^[\s\u00a0]+)|([\s\u00a0]+$)/g,_space:/[\s\u00a0]+/g,doCount:function(){var h=this;
if(!h.get_visible()){return;
}var g=h.get_editor().get_text({removeMultipleSpaces:true});
g=g.replace(h._trimNewLineCharsRegExp,"");
var i=h._getWordsCount(g);
var f=h._getCharactersCount(g);
h._renderCounts(i,f);
},_getCharactersCount:function(f){return e._getCharactersCount(f);
},_getWordsCount:function(f){var g=this;
var i=f.replace(g._punctRegExp,"").replace(g._trimSpacesRegExp,"");
var h=i?i.split(g._space):[];
return h.length;
},_renderCounts:function(h,f){var g=this.get_element();
g.innerHTML="<span style='line-height:22px'>"+this._wordsString+" "+h+" &nbsp;&nbsp;"+this._charactersString+" "+f+"&nbsp;</span>";
}};
c.RadEditorStatistics.registerClass("Telerik.Web.UI.Editor.Modules.RadEditorStatistics",c.ModuleBase);
})($telerik.$,Telerik.Web.UI.Editor);
Type.registerNamespace("Telerik.Web.UI.Editor.Modules");
(function(d,a){var b=d.Editor;
var c=b.Modules;
c.RadEditorTrackChangesInfo=function(e){c.RadEditorTrackChangesInfo.initializeBase(this,[e]);
};
c.RadEditorTrackChangesInfo.prototype={initialize:function(){this._onRadEditorTrackChangesInfoDelegate=Function.createDelegate(this,this.getRadEditorTrackChangesInfo);
this._isTrackChangeOnFocus=false;
this._author="";
this._trackChangeType="";
this._currTrackChangeElement=null;
c.RadEditorTrackChangesInfo.callBaseMethod(this,"initialize");
},render:function(){var m=this;
var k=m.get_editor();
var l=k._clientStateFieldID;
c.RadEditorTrackChangesInfo.callBaseMethod(m,"render");
k.add_selectionChange(m._onRadEditorTrackChangesInfoDelegate);
var q=m.get_element();
q.id="rade_tccomment_view_id_"+l;
q.style.width=q.parentNode.style.width;
q.className="reCommentViewContainer";
var h=document.createElement("DIV");
h.id="rade_tccomment_divV_id_"+l;
q.appendChild(h);
var f=document.createElement("DIV");
f.id="rade_tccomment_divEditTitle_id_"+l;
f.className="reCommentTitle";
f.innerHTML="Comment";
this._divEditTitle=f;
var j=document.createElement("DIV");
j.id="rade_tccomment_divViewTitle_id_"+l;
j.className="reCommentTitle";
j.innerHTML="Comment";
this._divViewTitle=j;
var e=document.createElement("DIV");
e.id="rade_tccomment_divEdit_id_"+l;
e.style.width=q.style.width;
e.className="reCommentEdit";
e.style.display="none";
this._divEdit=e;
h.appendChild(e);
e.appendChild(f);
var i=document.createElement("DIV");
i.id="rade_tccomment_divView_id_"+l;
i.style.width=q.style.width;
i.className="reCommentView";
i.style.display="none";
this._divView=i;
h.appendChild(i);
i.appendChild(j);
var g=document.createElement("DIV");
g.id="rade_tccomment_divInfo_id_"+l;
g.className="reCommentInfoPanel";
g.style.width=q.style.width;
g.style.display="none";
this._divInfo=g;
h.appendChild(g);
var s=document.createElement("TEXTAREA");
s.id="rade_textarea_id_"+l;
s.className="reCommentTextArea";
s.setAttribute("rows","2");
s.setAttribute("cols","25");
this._textarea=s;
e.appendChild(s);
var p=document.createElement("input");
p.id="rade_tccomment_save_id_"+l;
p.type="button";
p.value="Save";
p.className="reCommentButton";
p.onclick=function(){var t=m._textarea.value.replace(/^\s+|\s+$/g,"");
if(t==""||t.toLowerCase()=="<enter here>"){alert("Cannot enter empty comment.");
if(s.setActive){s.setActive();
}s.focus();
return;
}m._commentText.innerHTML=t;
m._commentAttr.value=t;
m._timeStampAttr.value=new Date().getTime();
m._titleAttr.value=m._author+": "+t+": "+new Date(parseInt(m._timeStampAttr.value,10)).toLocaleString();
a("#"+m._divEdit.id).hide();
m._show(a("#"+m._divView.id));
};
e.appendChild(p);
var n=document.createElement("input");
n.id="rade_tccomment_cancel_id_"+l;
n.type="button";
n.value="Cancel";
n.className="reCommentButton";
n.onclick=function(){m._textarea.value=m._commentText.innerHTML;
a("#"+m._divView.id).hide();
a("#"+m._divEdit.id).hide();
};
e.appendChild(n);
var o=document.createElement("input");
o.id="rade_tccomment_edit_id_"+l;
o.type="button";
o.value="Edit";
o.className="reCommentButton";
o.onclick=function(){m._textarea.value=m._commentText.innerHTML;
a("#"+m._divView.id).hide();
m._show(a("#"+m._divEdit.id));
m._textarea.focus();
if(m._textarea.value=="<Enter here>"){m._textarea.select();
}};
var r=document.createElement("span");
r.id="rade_tccomment_spanView_id_"+l;
this._commentText=r;
r.className="reCommentViewText";
i.appendChild(r);
i.appendChild(o);
if(l){a("#rade_textarea_id_"+l).focus(function(){a(this).filter(function(){return a(this).val()==""||a(this).val()=="<Enter here>";
}).removeClass("reCommentTextAreaWatermark").val("");
});
a("#rade_textarea_id_"+l).blur(function(){a(this).filter(function(){return a(this).val()=="";
}).addClass("reCommentTextAreaWatermark").val("<Enter here>");
});
}},_show:function(e){this._hideOtherVisibleContainers(e);
e.fadeIn(300);
},_hideOtherVisibleContainers:function(f){var e=(f)?f.attr("id"):"";
a(".reCommentEdit:visible[id!="+e+"],.reCommentView:visible[id!="+e+"],.reCommentInfoPanel:visible[id!="+e+"]").fadeOut(300);
},getRadEditorTrackChangesInfo:function(){if(!this.get_visible()){return;
}var g=a("#"+this._divInfo.id);
var f=a("#"+this._divEdit.id);
var h=a("#"+this._divView.id);
var i=this.get_editor();
var k=i.getSelectedElement();
var o=b.TrackChangesUtils.findTrackChangesParentElement(k);
this._author="";
if(null!=o){var e=b.TrackChangesConstants.Attribute;
this._timeStampAttr=o.HtmlElement.getAttributeNode(e.Timestamp);
var n=null==this._timeStampAttr?"":" on "+new Date(parseInt(this._timeStampAttr.value,10)).toLocaleString();
this._currTrackChangeElement=o;
this._author=(o.User=="")?"You":o.User;
var m=Telerik.Web.UI.Editor.TrackChangesElementType;
if(m.Comment==o.Type){this._commentAttr=o.HtmlElement.getAttributeNode(e.Comment);
this._titleAttr=o.HtmlElement.getAttributeNode(e.Title);
this._commentText.innerHTML=(null==this._commentAttr)?"":this._commentAttr.value;
if(this._author==i.get_author()){this._textarea.value=this._commentText.innerHTML||"<Enter here>";
g.hide();
if(this._commentAttr.value==" "||this._titleAttr.value=="#empty comment#"){h.hide();
this._show(f);
var l=this._textarea;
window.setTimeout(function(){try{if(l.setActive){l.setActive();
}l.focus();
}catch(p){return;
}},300);
}else{f.hide();
this._show(h);
}}else{h.hide();
f.hide();
this._show(g);
this._divInfo.innerHTML=this._author+": "+this._commentText.innerHTML+n;
}}else{var j=" ";
if(m.Delete==o.Type){j="Deleted by "+this._author+n;
}else{if(m.Insert==o.Type){j="Inserted by "+this._author+n;
}else{if(m.FormatChange==o.Type||m.JustifyFormatChange==o.Type){j="Format change("+o.BrowserCommand+") by "+this._author+n;
}}}this._divInfo.innerHTML=j;
h.hide();
f.hide();
j!=" "?this._show(g):g.fadeOut(300);
}}else{if(f.is(":visible")){f.fadeOut(300);
}if(h.is(":visible")){h.fadeOut(300);
}if(g.is(":visible")){g.fadeOut(300);
}}}};
c.RadEditorTrackChangesInfo.registerClass("Telerik.Web.UI.Editor.Modules.RadEditorTrackChangesInfo",c.ModuleBase);
})(Telerik.Web.UI,$telerik.$);
