(function(a,c){$telerik.findProgressArea=$find;
$telerik.toProgressArea=function(d){return d;
};
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.ProgressAreaContainerName="Panel";
function b(d){return $find(d);
}Telerik.Web.UI.RadProgressArea=function(d){Telerik.Web.UI.RadProgressArea.initializeBase(this,[d]);
this._progressManagerFound=false;
this._popupVisible=false;
this._width="";
this._height="";
this._skin="";
this._headerText="";
this._rtlCalculated=false;
this._isRightToLeft=false;
this._disposed=false;
$telerik.RadUpload_isIFrameProgress=($telerik.isSafari||$telerik.isOpera)&&!$telerik.isChrome;
this._bodyElement=($telerik.standardsMode)?document.documentElement:document.body;
};
Telerik.Web.UI.RadProgressArea.prototype={initialize:function(){Telerik.Web.UI.RadProgressArea.callBaseMethod(this,"initialize");
if(!this.get_progressManagerFound()){alert("Could not find an instance of RadProgressManager or RadAsyncUpload on the page. Are you missing the control declaration?");
}if(this._getIsRightToLeft()){this._applyRightToLeft();
}this._setupControls();
this.cancelClicked=false;
if(this._cancelButtonElement){$telerik.addHandlers(this._cancelButtonElement,{click:this.cancelRequest},this);
a(this._cancelButtonElement).on("mouseover",function(f){var d=a(f.target);
if(!d.hasClass("ruHovered")){d.addClass("ruHovered");
}}).on("mouseout",function(d){a(d.target).removeClass("ruHovered");
});
}if(typeof(Telerik.Web.UI.ProgressAreas)=="undefined"){Telerik.Web.UI.ProgressAreas=[];
}Telerik.Web.UI.ProgressAreas[Telerik.Web.UI.ProgressAreas.length]=this;
},dispose:function(){this._disposed=true;
if(this._cancelButtonElement){$telerik.clearHandlers(this._cancelButtonElement);
}Array.remove(Telerik.Web.UI.ProgressAreas,this);
Telerik.Web.UI.RadProgressArea.callBaseMethod(this,"dispose");
},_addSafariDefinition:function(d){d[d.length]=String.format("{0} = new RadUploadSafariProgressArea('{0}');",this.get_id());
},_setupControls:function(){this._clientId=this.get_id();
this._element=$get(this._clientId);
this._primaryProgressBarElement=this._findElement("PrimaryProgressElement");
this._primaryTotalElement=this._findElement("PrimaryTotal");
this._primaryValueElement=this._findElement("PrimaryValue");
this._primaryPercentElement=this._findElement("PrimaryPercent");
this._secondaryProgressBarElement=this._findElement("SecondaryProgressElement");
this._secondaryTotalElement=this._findElement("SecondaryTotal");
this._secondaryValueElement=this._findElement("SecondaryValue");
this._secondaryPercentElement=this._findElement("SecondaryPercent");
this._currentOperationElement=this._findElement("CurrentOperation");
this._timeElapsedElement=this._findElement("TimeElapsed");
this._timeEstimatedElement=this._findElement("TimeEstimated");
this._speedElement=this._findElement("Speed");
this._cancelButtonElement=a(this._element).find(".ruCancel")[0];
this._progressAreaHeader=this._findElement("ProgressAreaHeader");
this.updateTextIndicator(this._progressAreaHeader,this._headerText);
},_setupSafariProgressAreaControls:function(){if($telerik.RadUpload_isIFrameProgress){this._getSafariProgressArea()._primaryProgressBarElement=this._primaryProgressBarElement;
this._getSafariProgressArea()._primaryTotalElement=this._primaryTotalElement;
this._getSafariProgressArea()._primaryValueElement=this._primaryValueElement;
this._getSafariProgressArea()._primaryPercentElement=this._primaryPercentElement;
this._getSafariProgressArea()._secondaryProgressBarElement=this._secondaryProgressBarElement;
this._getSafariProgressArea()._secondaryTotalElement=this._secondaryTotalElement;
this._getSafariProgressArea()._secondaryValueElement=this._secondaryValueElement;
this._getSafariProgressArea()._secondaryPercentElement=this._secondaryPercentElement;
this._getSafariProgressArea()._currentOperationElement=this._currentOperationElement;
this._getSafariProgressArea()._timeElapsedElement=this._timeElapsedElement;
this._getSafariProgressArea()._timeEstimatedElement=this._timeEstimatedElement;
this._getSafariProgressArea()._speedElement=this._speedElement;
this._getSafariProgressArea()._cancelButtonElement=this._cancelButtonElement;
this._getSafariProgressArea()._width=this._width;
this._getSafariProgressArea()._height=this._height;
if(!this._element){this._element=$get(this._clientId);
}this._getSafariProgressArea()._element=this._element;
}},_getSafariProgressArea:function(){if(!this._safariProgressArea){this._safariProgressArea=getRadProgressManager()._safariPoller.contentWindow[this.get_id()];
}return this._safariProgressArea;
},_getIsRightToLeft:function(){if(!this._rtlCalculated){var d=this.get_element();
this._isRightToLeft=$telerik.getCurrentStyle(d,"direction","ltr")=="rtl";
return this._isRightToLeft;
this._rtlCalculated=true;
}return this._isRightToLeft;
},_applyRightToLeft:function(){var d=this.get_element();
if(/RadUploadProgressArea_rtl/.test(d.className)){return;
}$telerik.addCssClasses(d,["RadUploadProgressArea_rtl",String.format("RadUploadProgressArea_{0}_rtl",this._skin)]);
},_findElement:function(e){var d=this._haveContainer()?this._clientId+"_"+Telerik.Web.UI.ProgressAreaContainerName+"_"+e:this._clientId+"_"+e;
return $get(d);
},_haveContainer:function(){var d=a(this._element);
return d.find(".ruShadow").length>0;
},cancelRequest:function(){this.cancelClicked=true;
},update:function(e){if(this._disposed){return;
}if(!$telerik.RadUpload_isIFrameProgress){var d=new Sys.CancelEventArgs();
d._progressData=e;
d.get_progressData=function(){return this._progressData;
};
this.raiseEvent("progressUpdating",d);
if(d.get_cancel()){return;
}this.show();
d._progressValue=e.PrimaryPercent;
d._progressBarElementName="PrimaryProgressBar";
d._progressBarElement=this._primaryProgressBarElement;
d.get_progressValue=function(){return this._progressValue;
};
d.get_progressBarElementName=function(){return this._progressBarElementName;
};
d.get_progressBarElement=function(){return this._progressBarElement;
};
this.raiseEvent("progressBarUpdating",d);
if(!d.get_cancel()&&!isNaN(e.PrimaryPercent)){this.updateHorizontalProgressBar(this._primaryProgressBarElement,e.PrimaryPercent);
}d._progressValue=e.SecondaryPercent;
d._progressBarElementName="SecondaryProgressBar";
d._progressBarElement=this._secondaryProgressBarElement;
this.raiseEvent("progressBarUpdating",d);
if(!d.get_cancel()&&!isNaN(e.SecondaryPercent)){this.updateHorizontalProgressBar(this._secondaryProgressBarElement,e.SecondaryPercent);
}}else{this.show();
this.updateHorizontalProgressBar(this._primaryProgressBarElement,e.PrimaryPercent);
this.updateHorizontalProgressBar(this._secondaryProgressBarElement,e.SecondaryPercent);
}this.updateTextIndicator(this._primaryTotalElement,e.PrimaryTotal);
this.updateTextIndicator(this._primaryValueElement,e.PrimaryValue);
this.updateTextIndicator(this._primaryPercentElement,e.PrimaryPercent);
this.updateTextIndicator(this._secondaryTotalElement,e.SecondaryTotal);
this.updateTextIndicator(this._secondaryValueElement,e.SecondaryValue);
this.updateTextIndicator(this._secondaryPercentElement,e.SecondaryPercent);
this.updateTextIndicator(this._currentOperationElement,e.CurrentOperationText);
this.updateTextIndicator(this._timeElapsedElement,e.TimeElapsed);
this.updateTextIndicator(this._timeEstimatedElement,e.TimeEstimated);
this.updateTextIndicator(this._speedElement,e.Speed);
},show:function(){if(!this._element){this._element=document.getElementById(this._clientId);
}if(this._element){this._element.className=this._element.className.replace(/\s*RadUploadProgressAreaHidden/ig,"");
if(!$telerik.RadUpload_isIFrameProgress&&this._element.style.position=="absolute"){if(!this._popupBehavior){this._popupBehavior=$create(Telerik.Web.PopupBehavior,{id:(new Date()-100)+"PopupBehavior",parentElement:this._bodyElement},null,null,this._element);
}if(this._popupVisible==false){this._popupVisible=true;
var d=$telerik.getBounds(this._element);
var e=this._element.style;
var f=e.left?parseInt(e.left):d.x;
var g=e.top?parseInt(e.top):d.y;
this._popupBehavior.set_x(f);
this._popupBehavior.set_y(g);
this._popupBehavior.show();
}}}},hide:function(){this._element.className+=" RadUploadProgressAreaHidden";
if(this._popupBehavior){this._popupBehavior.hide(true);
}},updateTextIndicator:function(d,e){if(!d||typeof(e)=="undefined"){return;
}if(typeof(d.value)=="string"){d.value=e;
}else{if(typeof(d.innerHTML)=="string"){d.innerHTML=e;
}}},updateHorizontalProgressBar:function(d,e){if(d&&typeof(e)!="undefined"){d.style.width=e+"%";
}},updateVerticalProgressBar:function(d,e){if(d&&typeof(e)!="undefined"){d.style.height=e+"%";
}},get_progressManagerFound:function(){return this._progressManagerFound||!!Telerik.Web.UI.RadAsyncUpload;
},set_progressManagerFound:function(d){this._progressManagerFound=d;
},add_progressUpdating:function(d){this.get_events().addHandler("progressUpdating",d);
},remove_progressUpdating:function(d){this.get_events().removeHandler("progressUpdating",d);
},add_progressBarUpdating:function(d){this.get_events().addHandler("progressBarUpdating",d);
},remove_progressBarUpdating:function(d){this.get_events().removeHandler("progressBarUpdating",d);
}};
Telerik.Web.UI.RadProgressArea.registerClass("Telerik.Web.UI.RadProgressArea",Telerik.Web.UI.RadWebControl);
})($telerik.$);
