(function(d,a){Type.registerNamespace("Telerik.Web.UI");
var c=a.extend,b=a.ajax,e={0:"GET",1:"POST",2:"PUT",3:"DELETE"};
d.WebApiLoader=function(h){var g=h.get_path(),f=h.get_type?h.get_type():"json";
this._baseUrl=g.endsWith("/")?g:g+"/";
this._dataType=f;
this._contentType="application/"+f+";charset=utf-8";
this._successCallBack;
this._failCallBack;
};
d.WebApiLoader.prototype={add_loadingSuccess:function(f){this._successCallBack=f;
},add_loadingError:function(f){this._failCallBack=f;
},invokeMethod:function(f){var g=this,j=e[f.httpVerb],h={url:g._baseUrl+f.methodName,dataType:g._dataType,type:j,data:f.data,contentType:g._contentType,context:{userContext:f.context}};
var i=g._resolveStatusCodes(j);
c(true,h,{statusCode:i});
g._query(h);
},_resolveStatusCodes:function(j){var g=this,h;
var i=function(k,m,l){var o=this,n=new d.WebServiceLoaderSuccessEventArgs(k,o.userContext);
g._successCallBack(l,n);
};
var f=function(m,n,l){var o=this,k=new d.WebServiceLoaderErrorEventArgs(l,o.context);
g._failCallBack(m,k);
};
switch(j){case"GET":h={404:f,405:f};
break;
case"POST":h={201:i};
break;
case"DELETE":h={204:i,404:f};
break;
}return c({},h,{200:i,500:f});
},_query:function(f){b(f);
}};
})(Telerik.Web.UI,$telerik.$);
