Type.registerNamespace("Telerik.Web.UI.Scheduler.Views.Timeline.GroupedByDate");
(function(c){var a=$telerik.$;
var b=Telerik.Web.UI.Scheduler;
c.GroupedByDate.Model=function(f,d,e){c.GroupedByDate.Model.initializeBase(this,[f,d,e]);
};
c.GroupedByDate.Model.prototype={_getRawIndexFromDomElement:function(d){while(d&&(d.tagName.toUpperCase()!="TD")){d=d.parentNode;
}if(!d){return null;
}var f=d.cellIndex%this._resources.get_count();
var g={};
g.modelIndex=f;
var e;
if(this._isVertical){e=d.parentNode.rowIndex;
}else{e=Math.floor(d.cellIndex/this._resources.get_count());
}g.intervalIndex=e;
return g;
},_getDomElementFromRawIndex:function(f){if(f.modelIndex===undefined){return this._timelineModels[0]._getDomElementFromRawIndex(f.intervalIndex);
}var e=this._owner.get_element();
var g=f.modelIndex;
var d=f.intervalIndex;
if(this._isVertical){return a("div.rsTimelineView table.rsAllDayTable",e)[0].tBodies[0].rows[d].cells[g];
}d+=this._getNumberOfSlots()*f.modelIndex;
return a("div.rsTimelineView table.rsAllDayTable",e)[0].tBodies[0].rows[0].cells[d];
},_getSourceCellOffsetOfMovedAppointment:function(d,e){return 0;
},_getTimeFromDomElement:function(d){var e=this._getRawIndexFromDomElement(d);
return this._timelineModels[0]._getTimeFromIndex(e);
},_getRenderer:function(){if(!this._renderer){this._renderer=new b.Rendering.DateGroupedTimelineViewRenderer(this);
}return this._renderer;
},updateDraggingAppointmentSize:function(d,f,e){return;
}};
c.GroupedByDate.Model.registerClass("Telerik.Web.UI.Scheduler.Views.Timeline.GroupedByDate.Model",c.GroupedByResource.Model);
})(Telerik.Web.UI.Scheduler.Views.Timeline);
