Type.registerNamespace("Telerik.Web");
Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.Widgets");
(function(b,a){b.Widgets.MouseScroll=function(c,d,e){this.element=c;
this._accumulatedScroll=0;
this.setOptions(e);
this.set_externalHandler(d);
this.attachMouseWheel();
};
b.Widgets.MouseScroll.prototype={handleMouseScroll:function(c){this._checkSpecialKey(c);
this._checkCancelRawEvent(c);
this.callExternalMethod(c,this.wheel(c.rawEvent));
},callExternalMethod:function(d,c){this.externalHandler(d,c);
},handleMouseScrollWithAccumulation:function(d){this._checkSpecialKey(d);
this._checkCancelRawEvent(d);
var c=this.wheel(d.rawEvent);
this._accumulateScroll(c);
this._currentEvent=d;
this.startAccumulateTimer();
},startAccumulateTimer:function(){if(!this.accumulateTimer){this.accumulateTimer=setTimeout(Function.createDelegate(this,this.finishAccumulating),this.options.timeToAccumulate);
}},finishAccumulating:function(c){this.callExternalMethod(this._currentEvent,this._accumulatedScroll);
this.clearAccumulating();
},wheel:function(d){var c=0;
if(d.wheelDelta){c=d.wheelDelta/40;
}else{if(d.detail){c=-d.detail;
}}return c>0?Math.ceil(c):Math.floor(c);
},setOptions:function(c){this.options=a.extend({timeToAccumulate:200,throttleTime:null,specialKey:"",cancelRawEvent:false},c||{});
},attachMouseWheel:function(){this.internalHandler=this.options.timeToAccumulate?Function.createDelegate(this,this.handleMouseScrollWithAccumulation):Function.createDelegate(this,this.handleMouseScroll);
$telerik.addHandler(this.element,"mousewheel",this.internalHandler);
$telerik.addHandler(this.element,"DOMMouseScroll",this.internalHandler);
},detachMouseWheel:function(){$telerik.removeHandler(this.element,"mousewheel",this.internalHandler);
$telerik.removeHandler(this.element,"DOMMouseScroll",this.internalHandler);
delete this.internalHandler;
},clearAccumulating:function(){clearTimeout(this.accumulateTimer);
delete this._currentEvent;
delete this.accumulateTimer;
this._accumulatedScroll=0;
},set_externalHandler:function(c){this.externalHandler=c||Function.emptyFunction;
if(this.options.throttleTime){this.externalHandler=a.throttle(this.options.throttleTime,this.externalHandler);
}},dispose:function(){this.detachMouseWheel();
delete this.element;
},_checkSpecialKey:function(d){var c=this.options.specialKey&&d[this.options.specialKey];
if(c){$telerik.cancelRawEvent(d.rawEvent);
}return !c;
},_checkCancelRawEvent:function(c){if(this.options.cancelRawEvent){$telerik.cancelRawEvent(c);
}},_accumulateScroll:function(c){this._accumulatedScroll+=this._normalizeDelta(c);
},_normalizeDelta:function(c){return c==0?0:(c<0?-1:1);
}};
})(Telerik.Web.UI,$telerik.$);
