(function(a,i){Type.registerNamespace("Telerik.Web.UI.Widgets");
var j=Telerik.Web.UI.Widgets;
var h=3000;
var e=15;
var b=window.clearInterval;
var g=function(k){return window.setInterval(k,e);
};
var c=window.clearTimeout;
var f=window.setTimeout;
var d=$telerik.getComputedStyle;
j.Polling={waitFor:function(k,p){var l=a.Deferred();
var n,m;
var o=function(){b(n);
c(m);
};
n=g(function(){if(k()){o();
l.resolve();
}});
m=f(function(){o();
l.reject();
},p||h);
return l.promise();
},css:function(m,n,l){if(!m||!m.style){var k=a.Deferred();
k.reject();
return k.promise();
}return this.waitFor(function(){return m.style[n]===l||d(m,n)===l;
});
}};
})($telerik.$);
