Type.registerNamespace("Telerik.Web.UI.Widgets");
(function(b,a){var d=function(e){(function(){var g={};
a.extend(e,{trigger:function(k){var l=g[k];
if(!l){return;
}for(var m=0;
m<l.length;
m++){var j=Array.prototype.slice.call(arguments);
j.shift();
j.unshift(this);
l[m].handler.apply(l[m].context,j);
}},_bind:function(j,i){a.each(j,function(k,l){f(k,l,i);
});
},_unbind:function(j,i){a.each(j,function(k,l){h(k,l,i);
});
},_disposeEvents:function(){g=null;
}});
function f(j,k,i){var l=g[j]||[];
l.push({handler:k,context:i});
g[j]=l;
}function h(k,l,j){var m=g[k];
if(!m){return;
}var o=-1;
for(var n=0;
n<m.length;
n++){if(m[n].func==l&&m[n].context==j){o=n;
break;
}}if(o>-1){m=m.splice(o,1);
}g[k]=m;
}})();
};
b.Widgets.Resizable=function(e,f){this._element=e;
this._handlesCollection={};
this.options=a.extend({handleSize:7,liveResize:false,enableFrameOverlay:false,appendHandleToElement:false,useTinyHandles:false,constraints:{minWidth:null,minHeight:null,maxWidth:null,maxHeight:null},ownerDocument:document,handles:[{direction:"W",element:null},{direction:"NW",element:null},{direction:"N",element:null},{direction:"NE",element:null},{direction:"E",element:null},{direction:"SE",element:null},{direction:"S",element:null},{direction:"SW",element:null}]},f||{});
d(this);
this.initialize();
};
b.Widgets.Resizable.prototype={initialize:function(){this._initHandles();
},add_resizeStart:function(e){this._bind({resizeStart:e});
},remove_resizeStart:function(e){this._unbind({resizeStart:e});
},add_resizing:function(e){this._bind({resizing:e});
},remove_resizing:function(e){this._unbind({resizing:e});
},add_resizeEnd:function(e){this._bind({resizeEnd:e});
},remove_resizeEnd:function(e){this._unbind({resizeEnd:e});
},get_element:function(){return this._element;
},get_constraints:function(){return this.options.constraints;
},set_constraints:function(e){if(e){if((e.minWidth&&e.maxWidth&&e.minWidth>e.maxWidth)||(e.minHeight&&e.maxHeight&&e.minHeight>e.maxHeight)){throw Error("Invalid Parameters");
}}a.extend(this.options.constraints,e||{maxWidth:null,minWidth:null,maxHeight:null,minHeight:null});
for(var f in this._handlesCollection){this._setHandleConstraints(this._handlesCollection[f]);
}},get_minWidth:function(){return this.options.constraints.minWidth;
},set_minWidth:function(g){var e=this.options.constraints;
if((isNaN(g)&&g!==null&&g!=="")||(e.maxWidth&&e.maxWidth<g)){throw Error("Invalid Parameters");
}e.minWidth=g;
for(var f in this._handlesCollection){this._setHandleConstraints(this._handlesCollection[f]);
}},get_maxWidth:function(){return this.options.constraints.maxWidth;
},set_maxWidth:function(g){var e=this.options.constraints;
if((isNaN(g)&&g!==null&&g!=="")||(e.minWidth&&e.minWidth>g)){throw Error("Invalid Parameters");
}e.maxWidth=g;
for(var f in this._handlesCollection){this._setHandleConstraints(this._handlesCollection[f]);
}},get_minHeight:function(){return this.options.constraints.minHeight;
},set_minHeight:function(g){var e=this.options.constraints;
if((isNaN(g)&&g!==null&&g!=="")||(e.maxHeight&&e.maxHeight<g)){throw Error("Invalid Parameters");
}e.minHeight=g;
for(var f in this._handlesCollection){this._setHandleConstraints(this._handlesCollection[f]);
}},get_maxHeight:function(){return this.options.constraints.maxHeight;
},set_maxHeight:function(g){var e=this.options.constraints;
if((isNaN(g)&&g!==null&&g!=="")||(e.minHeight&&e.minHeight>g)){throw Error("Invalid Parameters");
}e.maxHeight=g;
for(var f in this._handlesCollection){this._setHandleConstraints(this._handlesCollection[f]);
}},hideHandles:function(){for(var e in this._handlesCollection){var f=this._handlesCollection[e];
f._element.style.display="none";
}},showHandles:function(){for(var e in this._handlesCollection){var f=this._handlesCollection[e];
f._element.style.display="";
}},repaint:function(){this._configureHandles();
},_initHandles:function(){var f=this.options.handles;
for(var g=0;
g<f.length;
g++){var e=null;
if(f[g].element){e=this._initExternalHandle(f[g]);
}else{e=this._initHandle(f[g]);
}e.add_dragStart(a.proxy(this._handleDragStart,this));
e.add_dragging(a.proxy(this._handleDragging,this));
e.add_dragEnd(a.proxy(this._handleDragEnd,this));
this._handlesCollection[e._direction]=e;
}this._configureHandles();
},_initExternalHandle:function(f){var e=new b.Widgets.Handle(f.element,f.direction,{handle:f.element,cursorType:this._getCursorFromDirection(f.direction),enableFrameOverlay:this.options.enableFrameOverlay});
return e;
},_initHandle:function(g){var f=this._createHandleElement(g);
var e=new b.Widgets.Handle(f,g.direction,{ownerDocument:this.options.ownerDocument,cursorType:this._getCursorFromDirection(g.direction),enableFrameOverlay:this.options.enableFrameOverlay});
return e;
},_createHandleElement:function(f){var e=this.options.ownerDocument.createElement("div");
e.style.position="absolute";
e.setAttribute("unselectable","on");
e.className="rrHandle rr"+f.direction;
return e;
},_configureHandles:function(){for(var e in this._handlesCollection){var f=this._handlesCollection[e];
if(f.get_useExternalHandle()){this._setHandleConstraints(f);
continue;
}this._appendHandleToDOM(f);
this._applyElementsZIndex(f);
this._sizeHandle(f);
this._positionHandle(f);
f._element.style.cssText=f._element.style.cssText;
this._setHandleConstraints(f);
}},_appendHandleToDOM:function(e){if(!this._element.parentNode){throw Error("Resizable element should be part of the DOM tree");
}if(this.options.appendHandleToElement){this._element.appendChild(e._element);
}else{this.options.ownerDocument.body.appendChild(e._element);
}},_applyElementsZIndex:function(e){var f=this._element.style.zIndex||$telerik.getComputedStyle(this._element,"z-index");
e._element.style.zIndex=f||"";
},_setHandleConstraints:function(f){var j=!!f.get_useExternalHandle();
var g=j?0:this.options.handleSize;
var h=a(f._element);
var i=h.offset();
var e;
if(j){e={minWidth:this.options.constraints.minWidth?this.options.constraints.minWidth-Math.ceil(a(this._element).innerWidth()):null,maxWidth:this.options.constraints.maxWidth?this.options.constraints.maxWidth-Math.floor(a(this._element).innerWidth()):null,minHeight:this.options.constraints.minHeight?this.options.constraints.minHeight-Math.ceil(a(this._element).innerHeight()):null,maxHeight:this.options.constraints.maxHeight?this.options.constraints.maxHeight-Math.floor(a(this._element).innerHeight()):null};
}else{e={minWidth:this.options.constraints.minWidth?this.options.constraints.minWidth-this._element.offsetWidth:null,maxWidth:this.options.constraints.maxWidth?this.options.constraints.maxWidth-this._element.offsetWidth:null,minHeight:this.options.constraints.minHeight?this.options.constraints.minHeight-this._element.offsetHeight:null,maxHeight:this.options.constraints.maxHeight?this.options.constraints.maxHeight-this._element.offsetHeight:null};
}f.set_constraints(null);
if(f._direction=="E"||f._direction=="W"){f.set_minY(i.top);
f.set_maxY(i.top+h.height());
}else{if(f._direction=="N"||f._direction=="S"){f.set_minX(i.left);
f.set_maxX(i.left+h.width());
}}if(f._direction.indexOf("W")>-1){if(e.maxWidth!==null){f.set_minX(null);
f.set_minX(f.get_position().x-e.maxWidth);
}f.set_maxX(null);
if(e.minWidth!==null){f.set_maxX(f.get_position().x-e.minWidth+g);
}else{f.set_maxX(this._getHandleOpositeConstraints(f._direction,j).x);
}}else{if(f._direction.indexOf("E")>-1){if(e.maxWidth!==null){f.set_maxX(null);
f.set_maxX(f.get_position().x+e.maxWidth+g);
}f.set_minX(null);
if(e.minWidth!==null){f.set_minX(f.get_position().x+e.minWidth);
}else{f.set_minX(this._getHandleOpositeConstraints(f._direction,j).x);
}}}if(f._direction.indexOf("N")>-1){if(e.maxHeight!==null){f.set_minY(null);
f.set_minY(f.get_position().y-e.maxHeight);
}f.set_maxY(null);
if(e.minHeight!==null){f.set_maxY(f.get_position().y-e.minHeight+g);
}else{f.set_maxY(this._getHandleOpositeConstraints(f._direction,j).y);
}}else{if(f._direction.indexOf("S")>-1){if(e.maxHeight!==null){f.set_maxY(null);
f.set_maxY(f.get_position().y+e.maxHeight+g);
}f.set_minY(null);
if(e.minHeight!==null){f.set_minY(f.get_position().y+e.minHeight);
}else{f.set_minY(this._getHandleOpositeConstraints(f._direction,j).y);
}}}},_getHandleOpositeConstraints:function(e,g){var h={x:null,y:null};
var f=g?0:c(this.options.handleSize);
if(e.toLowerCase().indexOf("w")>-1){h.x=a(this._element).offset().left+a(this._element).width()+f;
}else{if(e.toLowerCase().indexOf("e")>-1){h.x=a(this._element).offset().left-f;
}}if(e.toLowerCase().indexOf("n")>-1){h.y=a(this._element).offset().top+a(this._element).height()+f;
}else{if(e.toLowerCase().indexOf("s")>-1){h.y=a(this._element).offset().top-f;
}}return h;
},_sizeHandle:function(f){var e=f.get_direction();
if(this.options.useTinyHandles){f._element.style.width=f._element.style.height=this.options.handleSize+"px";
}else{if(e.indexOf("W")>-1||e.indexOf("E")>-1){f._element.style.width=this.options.handleSize+"px";
}else{f._element.style.width=Math.max(this.options.handleSize,parseFloat(this._element.clientWidth)-this.options.handleSize)+"px";
}if(e.indexOf("N")>-1||e.indexOf("S")>-1){f._element.style.height=this.options.handleSize+"px";
}else{f._element.style.height=Math.max(this.options.handleSize,parseFloat(this._element.clientHeight)-this.options.handleSize)+"px";
}}},_positionHandle:function(n){var r=this;
var q=r.options;
var e=q.appendHandleToElement&&r._isRootPositioned();
if(e&&q.useTinyHandles){return r._positionHandleStatic(n);
}var j=n.get_direction();
var k=r._element;
var f=k.clientHeight;
var g=k.clientWidth;
var p=j.indexOf("S")>-1?parseFloat(f):0;
var s=j.indexOf("E")>-1?parseFloat(g):0;
var o=n._element.style;
var i=parseFloat(f)>q.handleSize/2&&(j=="E"||j=="W")?1:-1;
var h=parseFloat(g)>q.handleSize/2&&(j=="N"||j=="S")?1:-1;
var m=c(q.handleSize);
var l=e?{top:0,left:0}:r._getPosition(k);
o.top=(l.top+p+i*m)+"px";
o.left=(l.left+s+h*m)+"px";
if(q.useTinyHandles){if(j=="S"||j=="N"){o.left=(l.left+c(g)-m)+"px";
}if(j=="E"||j=="W"){o.top=(l.top+c(f)-m)+"px";
}}},_positionHandleStatic:function(f){if(f._positioned){return;
}var e=f.get_direction();
var g="-"+c(this.options.handleSize)+"px";
var h={};
if(e.indexOf("N")>-1){h.top=0;
}if(e.indexOf("W")>-1){h.left=0;
}if(e.indexOf("E")>-1){h.right=0;
}if(e.indexOf("S")>-1){h.bottom=0;
}if(e=="N"||e=="S"){h.left="50%";
h.marginLeft=g;
}if(e=="W"||e=="E"){h.top="50%";
h.marginTop=g;
}a(f._element).css(h);
f._positioned=true;
},_isRootPositioned:function(){var e=this._isRootIndirectlyPositioned()||$telerik.getComputedStyle(this._element,"position")!="static";
return e;
},_isRootIndirectlyPositioned:function(){var e=this._element;
return($telerik.getComputedStyle(e,"transform")!="none"&&$telerik.getComputedStyle(e,"MozTransform")!="none"&&$telerik.getComputedStyle(e,"webkitTransform")!="none"&&$telerik.getComputedStyle(e,"OTransform")!="none"&&$telerik.getComputedStyle(e,"msTransform")!="none");
},_getPosition:function(e){var i={top:e.offsetTop,left:e.offsetLeft},f=e.offsetParent;
while(f){i.top+=f.offsetTop;
i.left+=f.offsetLeft;
var g=$telerik.getComputedStyle(f,"overflowX");
var h=$telerik.getComputedStyle(f,"overflowY");
if(h==="auto"||h==="scroll"){i.top-=f.scrollTop;
}if(g==="auto"||g==="scroll"){i.left-=f.scrollLeft;
}f=f.offsetParent;
}return i;
},_toggleDocumentCursor:function(e){if(typeof(e)=="string"){this.options.ownerDocument.body.style.cursor=this._getCursorFromDirection(e);
}else{this.options.ownerDocument.body.style.cursor="";
}},_getCursorFromDirection:function(e){if(e){return e.toLowerCase()+"-resize";
}else{return null;
}},_handleDragStart:function(g,e){this._setHandleConstraints(g);
var i=new b.Widgets.Resizable.ResizeableEventArgs(g.get_direction(),null,e.get_domEvent());
this.trigger("resizeStart",i);
if(!i._cancel){this._toggleDocumentCursor(g.get_direction());
}e.set_cancel(i._cancel);
var h=this.options;
if(h.liveResize&&!i._cancel){var f=this._element;
this.resizeHelper={width:f.clientWidth,height:f.clientHeight,offset:h.appendHandleToElement?{left:f.offsetLeft,top:f.offsetTop}:a(f).offset()};
}},_handleDragging:function(h,e){var f={x:e._delta.x,y:e._delta.y},g=h.get_direction(),i=this.options;
if(h.get_useExternalHandle()){if(g=="N"||g=="S"){f.x=0;
f.y=Math.min(f.y,this._element.clientHeight);
}if(g=="E"||g=="W"){f.x=Math.min(f.x,this._element.clientWidth);
f.y=0;
}}var j=new b.Widgets.Resizable.ResizeableEventArgs(g,f,e.get_domEvent());
this.trigger("resizing",j);
e.set_cancel(j._cancel||i.appendHandleToElement);
if(i.liveResize&&!j._cancel){this._applyElementSizing(g,f);
}},_handleDragEnd:function(h,e){var f=e._delta,g=h.get_direction();
if(h.get_useExternalHandle()){if(g=="N"||g=="S"){f.x=0;
f.y=Math.min(f.y,this._element.clientHeight);
}if(g=="E"||g=="W"){f.x=Math.min(f.x,this._element.clientWidth);
f.y=0;
}}this._toggleDocumentCursor();
this._configureHandles();
var i=new b.Widgets.Resizable.ResizeableEventArgs(h.get_direction(),f,e.get_domEvent());
this.trigger("resizeEnd",i);
},_applyElementSizing:function(f,e){var g=1,h=1;
if(f.indexOf("W")>-1){h=-1;
$telerik.$(this._element).css("left",parseFloat(this.resizeHelper.offset.left)+e.x);
}if(f.indexOf("N")>-1){g=-1;
$telerik.$(this._element).css("top",parseFloat(this.resizeHelper.offset.top)+e.y);
}a(this._element).innerWidth(parseFloat(this.resizeHelper.width)+h*e.x).innerHeight(parseFloat(this.resizeHelper.height)+g*e.y);
},dispose:function(){for(var e in this._handlesCollection){var f=this._handlesCollection[e];
if(!f.get_useExternalHandle()){if(f._element.parentNode){f._element.parentNode.removeChild(f._element);
}}f.dispose();
}this._element=null;
this._handlesCollection=null;
this.options=null;
}};
function c(e){return(e/2);
}b.Widgets.Resizable.ResizeableEventArgs=function(f,e,g){this._cancel=false;
this._delta=e;
this._direction=f;
this._domEvent=g;
};
b.Widgets.Resizable.ResizeableEventArgs.prototype={get_delta:function(){return this._delta;
},get_direction:function(){return this._direction;
},get_domEvent:function(){return this._domEvent;
},get_cancel:function(){return this._cancel;
},set_cancel:function(e){this._cancel=(e===true||e==="true");
}};
b.Widgets.Handle=function(f,e,g){this._direction=e;
this.options=a.extend(this.options,g||{});
Telerik.Web.UI.Widgets.Handle.initializeBase(this,[f,g]);
};
b.Widgets.Handle.prototype={get_direction:function(){return this._direction;
}};
Telerik.Web.UI.Widgets.Draggable.registerClass("Telerik.Web.UI.Widgets.Draggable");
Telerik.Web.UI.Widgets.Handle.registerClass("Telerik.Web.UI.Widgets.Handle",Telerik.Web.UI.Widgets.Draggable);
})(Telerik.Web.UI,$telerik.$);
