Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadDockZonesGlobalArray=[];
Telerik.Web.UI.registerRadDockZone=function(a){if(!Array.contains(this.RadDockZonesGlobalArray,a)){Array.add(this.RadDockZonesGlobalArray,a);
}};
Telerik.Web.UI.unregisterRadDockZone=function(a){Array.remove(this.RadDockZonesGlobalArray,a);
};
$telerik.toDockZone=function(a){return a;
};
$telerik.findDockZone=$find;
Telerik.Web.UI.RadDockZone=function(a){Telerik.Web.UI.RadDockZone.initializeBase(this,[a]);
this._dropDownTouchScroll=null;
};
Telerik.Web.UI.RadDockZone.prototype={initialize:function(){Telerik.Web.UI.RadDockZone.callBaseMethod(this,"initialize");
this._resetDockIndices();
this._placeholder=$get(this.get_clientID()+"_D");
if($telerik.isRightToLeft(this.get_element())){Sys.UI.DomElement.addCssClass(this._placeholder,"rdRtl");
}this._clearElement=$get(this.get_clientID()+"_C");
if(Telerik.Web.UI.TouchScrollExtender._getNeedsScrollExtender()&&!this._dropDownTouchScroll){this._createTouchScrollExtender(true);
}Telerik.Web.UI.registerRadDockZone(this);
},dispose:function(){this._createTouchScrollExtender(false);
Telerik.Web.UI.unregisterRadDockZone(this);
Telerik.Web.UI.RadDockZone.callBaseMethod(this,"dispose");
},_createTouchScrollExtender:function(d){var a=this.get_element();
if(a){var b=this._dropDownTouchScroll;
if(b){if(!d){b.dispose();
this._dropDownTouchScroll=null;
}}else{if(d){var c=$telerik.$(a).css("overflowY");
if(c=="auto"){this._dropDownTouchScroll=new Telerik.Web.UI.TouchScrollExtender(a);
this._dropDownTouchScroll.initialize();
}}}}},dock:function(d,c){var b=this.get_docks();
var a=null;
if(b.length>c){a=b[c].get_element();
}this._dockBefore(d,a,false);
d._hitZone=null;
},get_docks:function(){var c=[];
var b=this.get_element().firstChild;
while(b!=null){if(b!=this._placeholder&&b.id){var a=$find(b.id);
if(a&&Telerik.Web.UI.RadDock&&Telerik.Web.UI.RadDock.isInstanceOfType(a)){Array.add(c,a);
}}b=b.nextSibling;
}return c;
},_dockBefore:function(l,g,m,k){k=k?k:false;
var f=l.get_element();
var n=this.get_element();
var b=l.get_enableAnimation()?l.get_animationDuration():0;
var a={};
var i;
if(g){if(g!=this._placeholder){n.insertBefore(this._placeholder,g);
g=this._placeholder;
}i=g;
i.style.display="";
var j=$telerik.getLocation(i);
var c=$telerik.getBounds(i);
a.left=j.x;
a.top=j.y;
var d=c.width>5?c.width:parseInt(l.get_width(),10);
a.width=d;
}else{i=this._clearElement;
b=0;
}var h=l.get_titleElement();
if(h!=null){h.style.display="none";
}if(!k||b==0){this._onDockBeforeAnimationEnd(l,i,m);
return;
}var e=this;
$telerik.stopTransition(f,false,true);
$telerik.transition(f,a,b,"easeIn",function(){e._onDockBeforeAnimationEnd(l,i,m);
});
},_onDockBeforeAnimationEnd:function(g,e,h){var a=g.get_element();
var j=this.get_element();
if(e){if(e.className.indexOf("rdPlaceHolder")!=-1){e.style.display="none";
}}var c=g.get_titleElement();
if(c!=null){c.style.display="block";
}if(g._closed){a.style.display="none";
}j.insertBefore(a,e);
var f=$find(g.get_dockZoneID());
if(f){f._resetDockIndices();
f._resetDocksResizeHandles();
}g.set_dockZone(this);
g.set_dockZoneID(j.id);
if(this.get_fitDocks()){if(!this.get_isHorizontal()){g._fitWidth();
}}else{if(!this.get_isHorizontal()){g._unfitWidth();
}}g._resetPosition();
g._setPinUnpinVisibility();
if(g._resizableWidget){g._initResizableWidget();
}var b=this.get_docks();
for(var d=0;
d<b.length;
d++){if(b[d]._resizable){b[d]._setResizeLimit();
b[d]._resizableWidget.repaint();
}}this._resetDockIndices();
g.set_isDragged(false);
if(h){g.raise_dockPositionChanged(new Sys.EventArgs());
}},_resetDockIndices:function(){var a=this.get_docks();
for(var b=0;
b<a.length;
b++){a[b].set_index(b);
a[b].updateClientState();
}},_resetDocksResizeHandles:function(){var b=this.get_docks();
for(var c=0;
c<b.length;
c++){var a=b[c];
if(a._resizable&&!a._collapsed){a._setResizeLimit();
a._resizableWidget.repaint();
}}},get_isHorizontal:function(){return Sys.UI.DomElement.containsCssClass(this.get_element(),"rdHorizontal");
},_lastFoundItem:null,_lastFoundItemBounds:null,_findItemAt:function(j,f){var g=this.get_element();
if(!(this._lastFoundItem&&this._isInside(j,this._lastFoundItemBounds))){this._lastFoundItem=null;
this._lastFoundItemBounds=null;
var e=g.firstChild;
while(e!=null){if(e!=f&&e.nodeType!=3&&e.nodeType!=8){var h=this.get_isHorizontal();
var k=this._getMarginBox(f);
var a=this._getBorderBox(f);
var b=$telerik.getBounds(e);
var i=$telerik.getLocation(e);
b.x=i.x;
b.y=i.y;
b.x-=(($telerik.isSafari?0:k.left)+a.left+2);
b.y-=(k.top+a.top+2);
b.width+=(($telerik.isSafari?0:k.right)+a.right+2);
b.height+=(k.bottom+a.bottom+2);
var d={x:b.x,y:b.y,width:(h?b.width/2:b.width),height:(h?b.height:b.height/2)};
if(this._isInside(j,d)){this._lastFoundItem=e;
this._lastFoundItemBounds=d;
break;
}var c={x:b.x+(h?b.width/2:0),y:b.y+(h?0:b.height/2),width:(h?b.width/2:b.width),height:(h?b.height:b.height/2)};
if(this._isInside(j,c)){if(e.nextSibling){this._lastFoundItem=e.nextSibling;
this._lastFoundItemBounds=c;
break;
}}}e=e.nextSibling;
}}return this._lastFoundItem;
},_isInside:function(a,b){return(a.x>b.x&&a.x<(b.x+b.width)&&a.y>b.y&&a.y<(b.y+b.height));
},_showPlaceholder:function(a,f){this._repositionPlaceholder(a.get_element(),f);
var e=this.get_docks();
if(e.length>0){for(var d=0;
d<e.length;
d++){if(e[d].get_closed()==false){var b=a._getBounds();
var h=a._getMarginBox(this._placeholder);
var g=a._getBorderBox(this._placeholder);
var c=this.get_isHorizontal();
var j=this._placeholder.style;
j.height=b.height-(h.vertical+g.vertical)+"px";
j.width=this.get_fitDocks()&&!c?"100%":b.width-(h.horizontal+g.horizontal)+"px";
j.display="block";
return;
}}}if(this.get_highlightedCssClass()==null){Sys.UI.DomElement.addCssClass(this.get_element(),"rdPlaceHolder");
}},_repositionPlaceholder:function(a,b){var c=this._findItemAt(b,a)||this._findNextClosestDockElement(b);
var d=this.get_element();
if(null==c){d.insertBefore(this._placeholder,this._clearElement);
}else{if(c.previousSibling!=this._placeholder){d.insertBefore(this._placeholder,c);
}}},_isDockOnRow:function(a,c){var b=$telerik.$(a._element);
return c.y>=b.offset().top&&c.y<=(b.offset().top+b.height());
},_findLastDockOnRow:function(c){var d=null;
var a=this.get_docks();
for(var b=0;
b<a.length;
b++){if(this._isDockOnRow(a[b],c)){d=a[b];
}}return d;
},_findNextClosestDock:function(c){var a=this.get_docks();
var b=this._findLastDockOnRow(c);
return b&&a.length>b.get_index()?a[b.get_index()+1]:null;
},_findNextClosestDockElement:function(a){var b=this._findNextClosestDock(a);
return b?b._element:null;
},_getMarginBox:function(a){return $telerik.getMarginBox(a);
},_getBorderBox:function(a){return $telerik.getBorderBox(a);
},_hidePlaceholder:function(){Sys.UI.DomElement.removeCssClass(this.get_element(),"rdPlaceHolder");
this._placeholder.style.display="none";
this._lastFoundItem=null;
this._lastFoundItemBounds=null;
},hidePlaceholder:function(){this._hidePlaceholder();
},canDrop:function(c){var b=c.get_allowedZones();
var e=c.get_forbiddenZones();
var a=this.get_allowedDocks();
var f=this.get_uniqueName();
var d=c.get_uniqueName();
return((c.get_dockMode()!=Telerik.Web.UI.DockMode.Floating)&&(e.length==0||Array.indexOf(e,f)<0)&&(b.length==0||Array.indexOf(b,f)>=0)&&(a.length==0||Array.indexOf(a,d)>=0));
},drop:function(b){var a=new Sys.CancelEventArgs();
b.raise_dockPositionChanging(a);
this._hidePlaceholder();
if(this.get_highlightedCssClass()!=null){this.removeCssClass(this.get_highlightedCssClass());
}if(a.get_cancel()){b._restorePosition();
}else{this._dockBefore(b,this._placeholder,true,true);
}},dragEnterTarget:function(b,c){var a=new Sys.EventArgs();
a.dockZone=this;
a.DockZone=this;
b.raise_enterZone(a);
this._showPlaceholder(b,c);
if(this.get_highlightedCssClass()!=null){this.addCssClass(this.get_highlightedCssClass());
}},onDragInTarget:function(a,b){this._repositionPlaceholder(a.get_element(),b);
},dragLeaveTarget:function(b){var a=new Sys.EventArgs();
a.dockZone=this;
a.DockZone=this;
b.raise_leaveZone(a);
this._hidePlaceholder();
if(this.get_highlightedCssClass()!=null){this.removeCssClass(this.get_highlightedCssClass());
}},hitTest:function(a,b,f){if(!this.canDrop(a)){return false;
}if(f==null){f=true;
}var d=$telerik.getDocumentRelativeCursorPosition(b);
var c=$telerik.isTouchDevice?$telerik.getTouchEventLocation(b):{x:d.left,y:d.top};
if($telerik.containsPoint($telerik.getBounds(this.get_element()),c.x,c.y)){if(f){this.dragEnterTarget(a,c);
}return true;
}else{this.dragLeaveTarget(a);
return false;
}},getScrollOffset:function(a,d){var b=a.scrollLeft;
var e=a.scrollTop;
if(d){var c=a.parentNode;
while(c!=null&&c.scrollLeft!=null){b+=c.scrollLeft;
e+=c.scrollTop;
if(c==document.body&&(b!=0&&e!=0)){break;
}c=c.parentNode;
}}return{x:b,y:e};
},clone:function(e){if(!e){e="RadDockZoneClone_"+(new Date()-100);
}var d=this.get_element();
var f=d.cloneNode(true);
f.setAttribute("id",e);
f.removeAttribute("control");
f.innerHTML="";
var g=this._placeholder.cloneNode(true);
g.setAttribute("id",e+"_D");
f.appendChild(g);
var b=$get(this._clientStateFieldID).cloneNode(true);
b.setAttribute("id",e+"_ClientState");
f.appendChild(b);
var a;
if(this._clearElement){a=this._clearElement.cloneNode(true);
a.setAttribute("id",e+"_C");
f.appendChild(a);
}d.parentNode.insertBefore(f,d.nextSibling);
var c=$telerik.cloneControl(this,Telerik.Web.UI.RadDockZone,f);
c.set_uniqueName(e);
c._placeholder=g;
if(a){c._clearElement=a;
}return c;
},addPoints:function(a,b){return{x:a.x+b.x,y:a.y+b.y};
}};
$telerik.$.registerControlProperties(Telerik.Web.UI.RadDockZone,{allowedDocks:[],uniqueName:null,layoutID:null,highlightedCssClass:null,fitDocks:true,clientID:null});
Telerik.Web.UI.RadDockZone.registerClass("Telerik.Web.UI.RadDockZone",Telerik.Web.UI.RadWebControl);
