Type.registerNamespace("Telerik.Web.UI.Dock");
(function(a,b,f){var e=["Transform","webkitTransform","OTransform","MozTransform","msTransform"];
var c=["BackfaceVisibility","webkitBackfaceVisibility","OBackfaceVisibility","MozBackfaceVisibility","msBackfaceVisibility"];
var d=Telerik.Web.Browser;
a.registerEnum(b,"DockMode",{Floating:1,Docked:2,Default:3});
$telerik.toDock=function(g){return g;
};
$telerik.findDock=$find;
Telerik.Web.UI.RadDock=function(g){Telerik.Web.UI.RadDock.initializeBase(this,[g]);
this._initialized=false;
this._enableDrag=true;
this._top=0;
this._left=0;
this._dockZoneID=null;
this._title=null;
this._commands=null;
this._closed=false;
this._collapsed=false;
this._pinned=false;
this._handle=null;
this._resizable=false;
this._width="300px";
this._height=null;
this._expandedHeight=0;
this._handle=null;
this._form=null;
this._isDragged=false;
this._accessKey="";
this._tabIndex=0;
this._draggedCssClass="rdDragHelper";
this._dropDownTouchScroll=null;
this.set_handle=this.set_handle;
this._isCustomHandle=false;
this._draggableWidget=null;
this._resizableWidget=null;
};
Telerik.Web.UI.RadDock.DragDataType="RadDock";
Telerik.Web.UI.RadDock.prototype={_isDockRightToLeft:function(){var g=this._isRightToLeft;
if(g==null){var h=this.get_element();
if(h){g=this._isRightToLeft=$telerik.isRightToLeft(h);
}}return g;
},_setResizeLimit:function(){var n=this.get_dockZoneID(),i=null,h=null,k=this._renderingView.get_minWidth(),j=this._renderingView.get_minHeight();
if(n){var l=$find(n);
var m=l.get_element();
var g=this._getBounds();
if(l.get_isHorizontal()){i=g.width+this._caluclateZoneFreeSpace(l).width;
h=m.offsetHeight;
}else{h=g.height+this._caluclateZoneFreeSpace(l).height;
i=m.offsetWidth;
}}this._resizableWidget.set_constraints({minWidth:this._renderingView.get_minWidth(),minHeight:this._renderingView.get_minHeight(),maxWidth:i?Math.max(k,i):null,maxHeight:h?Math.max(this.get_height()?this._element.offsetHeight:j,h):null});
},_updateSizeValues:function(){var g=this._getBounds();
this._width=g.width;
this._height=g.height;
},_moveElements:function(h,i){while(h.childNodes&&h.childNodes.length>0){var g=h.childNodes[0];
h.removeChild(g);
i.appendChild(g);
}},_initResizableWidget:function(){if(this._resizableWidget&&this._resizableWidget.dispose){this._resizableWidget.dispose();
}if(!this._resizable){return;
}if(d.webkit){this._kickStartCssTransform();
}this._resizableWidget=new Telerik.Web.UI.Widgets.Resizable(this._element,{handles:this._getAvailableHandles()});
if(this._renderingView){this._setResizeLimit();
}if(this._collapsed){this._resizableWidget.hideHandles();
}this._resizableWidget.add_resizeStart(a.proxy(this._resizeStartHandler,this));
this._resizableWidget.add_resizing(a.proxy(this._resizingHandler,this));
this._resizableWidget.add_resizeEnd(a.proxy(this._resizeEndHandler,this));
},_getAvailableHandles:function(){var g;
var i=this.get_dockZoneID();
if(i){var h=$find(i);
g=h.get_isHorizontal()?[{direction:this._isDockRightToLeft()?"W":"E",element:null}]:[{direction:"S",element:null}];
}return g;
},_resizeStartHandler:function(h,g){if(this._collapsed){g.set_cancel(true);
}this.resizeHelper={width:this.get_width(),height:this.get_height()||this._element.clientHeight,offset:{top:this.get_top(),left:this.get_left()}};
this.raise_resizeStart(new Sys.EventArgs());
},_resizingHandler:function(j,g){var h=g.get_direction(),i=1,k=1;
if(h.indexOf("W")>-1){k=-1;
this.set_left(parseInt(this.resizeHelper.offset.left,10)+g.get_delta().x);
}if(h.indexOf("N")>-1){i=-1;
this.set_top(parseInt(this.resizeHelper.offset.top,10)+g.get_delta().y);
}if(h.indexOf("W")>-1||h.indexOf("E")>-1){this.set_width(parseInt(this.resizeHelper.width,10)+k*g.get_delta().x);
}if(h.indexOf("N")>-1||h.indexOf("S")>-1){this.set_height(parseInt(this.resizeHelper.height,10)+i*g.get_delta().y);
}},_resizeEndHandler:function(h,g){this.raise_resizeEnd(new Sys.EventArgs());
var j=this.get_dockZoneID();
if(j){var i=$find(j);
i._resetDocksResizeHandles();
}},_makeResizable:function(){this._enableMoveResize();
},_caluclateZoneFreeSpace:function(j){var l=$telerik.getContentSize(j.get_element());
var h=j.get_isHorizontal()?this._getDocksFromCurrentRow(j):j.get_docks();
for(var k=0;
k<h.length;
k++){var g=h[k]._getBounds();
l.height-=g.height;
l.width-=g.width;
}return l;
},_getDocksFromCurrentRow:function(j){var l=[],h=j.get_docks(),g=this._getLocation().y;
for(var k=0;
k<h.length;
k++){if(h[k]._getLocation().y==g){l.push(h[k]);
}}return l;
},_initializeDrag:function(){if(this._handle){this._disposeDrag();
if(this.get_enableDrag()&&!this.get_pinned()){if(this._draggableWidget&&this._draggableWidget.dispose){this._draggableWidget.dispose();
}this._draggableWidget=new Telerik.Web.UI.Widgets.Draggable(this._element,{handle:this._handle,shouldPreventDefault:false,validateNestedElementsAsTriggers:true});
this._draggableWidget.add_dragStarting(a.proxy(this._dragStartHandler,this));
this._draggableWidget.add_dragging(a.proxy(this._draggingHandler,this));
this._draggableWidget.add_dragEnd(a.proxy(this._dragEndHandler,this));
}}},_draggingHandler:function(h,g){this._hitZone=this.dockingZoneHitTest(g._domEvent);
this.raise_drag(new Sys.EventArgs());
$telerik.cancelRawEvent(g.get_domEvent());
},_dragStartHandler:function(i,g){if(!this.get_enableDrag()||this.get_pinned()){return false;
}this.set_isDragged(true);
var h=new Sys.CancelEventArgs();
h.ownerEvent=g.get_domEvent();
this.raiseEvent("dragStart",h);
g.set_cancel(h.get_cancel());
if(h.get_cancel()){return false;
}this._renderingView.get_contentContainer().style.overflow="hidden";
this.addCssClass(this._draggedCssClass);
this._startDragDrop();
},_dragEndHandler:function(h,g){var i=this._hitZone;
if(!i){i=this._hitZone=this.dockingZoneHitTest(g._domEvent);
}if(i){if(i.canDrop(this)){i.drop(this);
}else{this._restorePosition();
}}else{if(this.canDrop()){this.drop();
}else{this._restorePosition();
}}this._renderingView.get_contentContainer().style.overflow="auto";
this.removeCssClass(this._draggedCssClass);
if(this._resizableWidget){this._resizableWidget.repaint();
}this.raise_dragEnd(new Sys.EventArgs());
},_disposeDrag:function(){if(this._handle&&this._draggableWidget){this._draggableWidget.dispose();
this._draggableWidget=null;
}},_startDragDrop:function(){var i=this.get_element();
this.originalZIndex=i.style.zIndex;
var g=this._getBounds(i);
var h=this._getBorderBox(i);
g.width-=h.horizontal;
g.height-=h.vertical;
i.style.width=g.width+"px";
i.style.zIndex="9999999";
var j=this._getLocation(i);
if(i.parentNode!=this._form){this._form.appendChild(i);
}var k=$find(this.get_dockZoneID());
if(k){k._showPlaceholder(this,j);
}this._setLocation(j);
},get_isDragged:function(){return this._isDragged;
},set_isDragged:function(g){this._isDragged=g;
},get_dockZones:function(){if(typeof(Telerik.Web.UI.RadDockZonesGlobalArray)=="undefined"){return[];
}return Telerik.Web.UI.RadDockZonesGlobalArray;
},dockingZoneHitTest:function(k){var n=null,p;
var j=this.get_dockZones();
var h=this.get_element();
var m=[];
var l=[];
for(p=0;
p<j.length;
p++){if(j[p].hitTest(this,k,false)){m[m.length]=j[p].get_element();
l[l.length]=j[p];
}}if(m.length>0){if(m.length==1){n=$find(m[0].id);
}else{if(m.length>1){h.style.display="none";
var o=document.elementFromPoint(k.clientX,k.clientY);
h.style.display="";
if(o){var g=document.body;
while(o!=g){for(p=0;
p<m.length;
p++){if(o==m[p]){if(o.id){n=$find(o.id);
}break;
}}if(n!=null){break;
}o=o.parentNode;
}}}}for(p=0;
p<l.length;
p++){if(l[p]!=n){l[p].dragLeaveTarget(this);
}else{n.hitTest(this,k,true);
}}}return n;
},canDrop:function(){return this.get_dockMode()!=Telerik.Web.UI.DockMode.Docked;
},drop:function(){var g=new Sys.CancelEventArgs();
this.raise_dockPositionChanging(g);
this.get_element().style.zIndex=this.originalZIndex;
if(g.get_cancel()){this._restorePosition();
}else{if(this.get_dockZoneID()){this.get_dockZone()._resetDocksResizeHandles();
}this.undock();
if(this._resizable){this._initResizableWidget();
this._setResizeLimit();
}this.raise_dockPositionChanged(new Sys.EventArgs());
}},clone:function(o){if(!o){o="RadDockClone_"+(new Date()-100);
}var m=this.get_handle();
this._setHandle(null);
var t=this._grip==m?"_G":"_H";
var u=false;
if(m&&!m.id){m.id=this.get_id()+t;
u=true;
}var k=this.get_commands();
for(var p in k){k[p].detachCommandHandlers();
}var q=this._renderingView.clone(o);
this._removeClonedHandles(q);
var s=$telerik.cloneControl(this,Telerik.Web.UI.RadDock,q);
this._setHandle(m);
if(m&&(m.className.indexOf("rdTitleBar")==-1)){var r=$get(m.id,q);
r.id=o+t;
s.set_handle(r);
if(u){m.removeAttribute("id");
}}var l=s.get_commandsContainer();
if(l){var j=s.get_commandsContainer().getElementsByTagName("a");
for(var n=0;
n<j.length;
n++){var h=j[n];
h.removeAttribute("control");
}}if(this._originalCommandsObject){s.set_commands(Array.clone(this._originalCommandsObject));
}s._initializeCommands();
for(var g in k){k[g].attachCommandHandlers();
}s.set_uniqueID(o);
if(s.get_dockZone()){s.get_dockZone()._resetDockIndices();
}return s;
},_removeClonedHandles:function(g){a(g).find(".rrHandle").remove();
},getCommand:function(g){return this._commands?this._commands[g]:null;
},get_handle:function(){return this._handle;
},set_handle:function(g){this._isCustomHandle=true;
this._setHandle(g);
},_setHandle:function(g){this._disposeDrag();
this._handle=g;
this._initializeDrag();
},subtractPoints:function(g,h){return{x:g.x-h.x,y:g.y-h.y};
},addPoints:function(g,h){return{x:g.x+h.x,y:g.y+h.y};
},_getRenderingView:function(){if(this._renderMode==Telerik.Web.UI.RenderMode.Classic){return new Telerik.Web.UI.Dock.ClassicView(this);
}else{if(this._renderMode==Telerik.Web.UI.RenderMode.Lite){return new Telerik.Web.UI.Dock.LightweightView(this);
}else{throw Error("RadDock with ID: "+this.get_id()+" has not defined RenderMode");
}}},initialize:function(){Telerik.Web.UI.RadDock.callBaseMethod(this,"initialize");
this._renderingView=this._getRenderingView();
if(this._isDockRightToLeft()){var g=this.get_element();
Sys.UI.DomElement.addCssClass(g,"rdRtl");
Sys.UI.DomElement.addCssClass(g,"RadDock_"+this.get_skin()+"_rtl");
}if(!$telerik.isTouchDevice){this._resetCSS3Rules();
}this._renderingView.initialize();
this._initializeCommands();
this._updateToggleCommandsState();
this._setPinUnpinVisibility();
var k=this.get_element();
var i=k.parentNode;
var j=$telerik.getInvisibleParent(this.get_element().parentNode);
var h=(j!=null);
if(h){var l={position:k.style.position,top:k.style.top,left:k.style.left};
k.parentNode.removeChild(k);
k.style.position="absolute";
k.style.top="-5000px";
k.style.left="-5000px";
document.body.appendChild(k);
k.style.position=l.position;
k.style.top=l.top;
k.style.left=l.left;
k.parentNode.removeChild(k);
var n=this.get_dockZone();
if(n&&Telerik.Web.UI.RadDockZone.isInstanceOfType(n)){i.insertBefore(k,n._placeholder);
}else{i.appendChild(k);
}}if(Telerik.Web.UI.TouchScrollExtender._getNeedsScrollExtender()&&!this._dropDownTouchScroll){this._createTouchScrollExtender(true);
}if(!h&&this.get_dockZoneID()==""){var m=window.theForm;
i.removeChild(k);
m.appendChild(k);
}k.style.visibility="";
this._registerShortcuts();
this._initResizableWidget();
this.updateClientState();
this.raise_initialize();
this.raise_load();
this.add_dockPositionChanged(Function.createDelegate(this,function(){this.conditionalPostback("dockPositionChanged");
}));
},dispose:function(){this._createTouchScrollExtender(false);
this._renderingView.dispose();
Telerik.Web.UI.RadDock.callBaseMethod(this,"dispose");
},_resetCSS3Rules:function(){this._setCss3Rules("none","visible");
},_kickStartCssTransform:function(){this._setCss3Rules("","visible");
},_setCss3Rules:function(i,g){var h=this._element.style;
Array.forEach(e,function(j){h[j]=i;
});
Array.forEach(c,function(j){h[j]=g;
});
},_createTouchScrollExtender:function(i){var g=$get(this.get_id()+"_C");
if(g){var h=this._dropDownTouchScroll;
if(h){if(!i){h.dispose();
this._dropDownTouchScroll=null;
}}else{if(i){this._dropDownTouchScroll=new Telerik.Web.UI.TouchScrollExtender(g);
this._dropDownTouchScroll.initialize();
}}}},undock:function(){var g=this.get_element();
if(g.parentNode!=this._form){this._form.appendChild(g);
g.style.position="absolute";
}var h=this._getLocation(g);
this.set_left(h.x);
this.set_top(h.y);
var i=$find(this.get_dockZoneID());
if(i){this.set_dockZoneID("");
i._resetDockIndices();
this._unfitWidth();
}this._setPinUnpinVisibility();
this.updateClientState();
},_fitWidth:function(){this._renderingView.fitWidth();
},_unfitWidth:function(){this._renderingView.unfitWidth();
},_initializeCommands:function(){if(!this.get_commandsContainer()){this._commands={};
return;
}var k=this._renderingView.getCommandsElements();
var m=this._commands;
if(m){this._commands={};
for(var n=0;
n<m.length;
n++){var j=m[n];
var g=eval(j.clientTypeName);
if(g==Telerik.Web.UI.DockCommand||g.inheritsFrom(Telerik.Web.UI.DockCommand)){j.radDock=this;
var l=null;
if(j.command){l={command:eval(j.command)};
delete j.command;
}var h=$create(g,j,l,null,k[n]);
this._commands[h.get_name()]=h;
}else{throw Error.invalidOperation(j.clientTypeName+" does not inherit from Telerik.Web.UI.DockCommand.");
}}}},_updateToggleCommandsState:function(){var g=this.getCommand("ExpandCollapse");
if(g){g.set_state(this.get_collapsed()?2:1);
}var h=this.getCommand("PinUnpin");
if(h){h.set_state(this.get_pinned()?2:1);
}},_setPinUnpinVisibility:function(){var g=this.getCommand("PinUnpin");
if(g){g.get_element().style.display=this.get_dockZoneID()?"none":"";
}},_getBounds:function(g){if(!g){g=this.get_element();
}return $telerik.getBounds(g);
},_getMarginBox:function(g){if(!g){g=this.get_element();
}return $telerik.getMarginBox(g);
},_getBorderBox:function(g){if(!g){g=this.get_element();
}return $telerik.getBorderBox(g);
},_resetPosition:function(){var g=this.get_element();
g.style.top="";
g.style.left="";
g.style.position="";
if(typeof(this.originalZIndex)=="undefined"){this.originalZIndex="";
}g.style.zIndex=this.originalZIndex;
},_restorePosition:function(){var g=$find(this.get_dockZoneID());
if(g){g.dock(this,this.get_index());
}else{this.undock();
}},_getLocation:function(g){if(!g){g=this.get_element();
}return $telerik.getLocation(g);
},_setLocation:function(g){$telerik.setLocation(this.get_element(),g);
},_setSize:function(i,h){var g=this._getBounds();
this._setHeight(h);
if(!i){i=g.width;
}this._setWidthHtmlEl(i);
},get_contentContainer:function(){this._ensureRenderingView();
return this._renderingView.get_contentContainer();
},get_titleBar:function(){this._ensureRenderingView();
return this._renderingView.get_titleBar();
},get_commandsContainer:function(){this._ensureRenderingView();
return this._renderingView.get_commandsContainer();
},get_titleElement:function(){this._ensureRenderingView();
return this._renderingView.get_titleElement();
},_ensureRenderingView:function(){if(!this._renderingView){this._renderingView=this._getRenderingView();
this._renderingView.initialize();
}},executeCommand:function(h){var g=this.getCommand(h);
if(!g){return;
}if(b.DockToggleCommand.isInstanceOfType(g)){g.set_state(g.get_state()==1?2:1);
}g.onCommand();
},addShortCut:function(g,h){if(this._shortCutManager){this._shortCutManager.addShortCut(g,h);
}},removeShortCut:function(g){if(this._shortCutManager){this._shortCutManager.removeShortCut(g);
}},setShortCut:function(g,h){if(this._shortCutManager){this._shortCutManager.setShortCut(g,h);
}},_getDefaultShortCuts:function(){var g=[["Close","ESC"],["PinUnpin","Ctrl+F12"],["ExpandCollapse","Ctrl+F11"]];
return g;
},_registerShortcuts:function(h){this._attachShortcutHandlers(h!==false);
if(!this._shortCutManager){this._shortCutManager=new b.ShortCutManager(this._getDefaultShortCuts());
this._shortCutManager.addShortCuts(this.get_shortcuts());
}var g=this.get_element();
g.setAttribute("tabIndex",this._tabIndex.toString());
if(this._accessKey){g.setAttribute("accessKey",this._accessKey);
}},_attachShortcutHandlers:function(g){if(g){this._keyDownDelegate=Function.createDelegate(this,this._keyDown);
$addHandler(this.get_element(),"keydown",this._keyDownDelegate);
}else{$removeHandler(this.get_element(),"keydown",this._keyDownDelegate);
this._keyDownDelegate=null;
}},_keyDown:function(g){var i=this._shortCutManager.isShortCutHit(g.rawEvent);
if(!i){return;
}var h=new b.Dock.ShortCutCancelEventArgs(g.rawEvent,i);
this.raiseEvent("shortCutHit",h);
if(!h.get_cancel()){this.executeCommand(i.get_name());
}$telerik.cancelRawEvent(g.rawEvent);
return false;
},saveClientState:function(){var g={Top:this.get_top(),Left:this.get_left(),DockZoneID:this.get_dockZoneID(),Collapsed:this.get_collapsed(),Pinned:this.get_pinned(),Resizable:this.get_resizable(),Closed:this.get_closed(),Width:this.get_width(),Height:this.get_height(),ExpandedHeight:this._expandedHeight,Index:this.get_index(),IsDragged:this.get_isDragged()};
return Sys.Serialization.JavaScriptSerializer.serialize(g);
},conditionalPostback:function(g){if(this.get_autoPostBack()){this.doPostBack(g);
}},doPostBack:function(g){__doPostBack(this.get_uniqueID(),g);
},get_top:function(){return this._top;
},set_top:function(g){if(g!=""){g=parseInt(g,10);
if(this._initialized){this.get_element().style.top=g+"px";
}}this._top=g;
this.updateClientState();
},get_left:function(){return this._left;
},set_left:function(g){if(g!=""){g=parseInt(g,10);
if(this._initialized){this.get_element().style.left=g+"px";
}}this._left=g;
this.updateClientState();
},_onCloseAnimationEnd:function(){var h=this.get_element();
var g=this.getCommand("Close");
var i=this.get_titleElement();
if(i!=null){i.style.display="block";
}if(this._resizable){if(this.get_dockZoneID()){this.get_dockZone()._resetDocksResizeHandles();
}if(this._closed){this._resizableWidget.hideHandles();
}else{this._resizableWidget.showHandles();
}}if(this._closed){h.style.display="none";
if(this._resizable){if(this.get_dockZoneID()){this.get_dockZone()._resetDocksResizeHandles();
}this._resizableWidget.hideHandles();
}this.updateClientState();
if(g){Telerik.Web.UI.DockCloseCommand.callBaseMethod(g,"onCommand");
}}else{h.style.display="block";
this._renderingView.repaint();
if(!this._collapsed){this.set_height(this.get_height());
}$telerik.repaintChildren(this);
if(this._resizable){if(this.get_dockZoneID()){this.get_dockZone()._resetDocksResizeHandles();
}this._resizableWidget.hideHandles();
}this.updateClientState();
if(g){Telerik.Web.UI.DockCloseCommand.callBaseMethod(g,"onCommand");
}}},get_visible:function(){return !this.get_closed();
},set_visible:function(g){this.set_closed(!g);
},get_closed:function(){return this._closed;
},set_closed:function(l,k){if(!this._initialized){return;
}this._closed=l;
k=k?k:false;
var h=this.get_enableAnimation()?this.get_animationDuration():0;
if(!k||h==0){this._onCloseAnimationEnd();
return;
}var i=this.get_element();
var g=Function.createDelegate(this,this._onCloseAnimationEnd);
var j=this.get_titleElement();
if(j!=null){j.style.display="none";
}if(l){$telerik.stopTransition(i,false,true);
$telerik.transition(i,{opacity:0},h,"easeIn",g);
}else{$telerik.stopTransition(i,false,true);
$telerik.transition(i,{opacity:1},h,"easeIn",g);
}},get_collapsed:function(){return this._collapsed;
},set_collapsed:function(h,g){g=g?g:false;
if(this._resizable&&this._resizableWidget){if(h){this._resizableWidget.hideHandles();
}else{this._resizableWidget.showHandles();
}}this._collapsed=h;
this.updateClientState();
if(this._initialized&&this._renderingView){this._renderingView.collapse(h,g);
}},get_commands:function(){return this._commands;
},set_commands:function(g){this._commands=g;
this._originalCommandsObject=g;
},get_dockZoneID:function(){return this._dockZoneID;
},set_dockZoneID:function(g){this._dockZoneID=g;
},get_height:function(){return this._height;
},set_height:function(g){this._height=g;
this.updateClientState();
if(this._initialized){this._renderingView.set_height(g);
}},get_enableDrag:function(){return this._enableDrag;
},set_enableDrag:function(g){this._enableDrag=g;
this._initializeDrag();
},get_pinned:function(){return this._pinned;
},set_pinned:function(h){if(this.get_dockZoneID()){return;
}this._pinned=h;
var g=this.getCommand("PinUnpin");
if(g){g.set_state(h?2:1);
}if(this._renderingView&&this._initialized){this._renderingView.pin(h);
}},get_title:function(){return this._title;
},set_title:function(g){this._title=g;
if(this._renderingView){this._renderingView.set_title(g);
}},set_visibleTitlebar:function(h){if(h==null){h=true;
}var g=this._topBar;
if(h){this.get_titleBar().style.display="";
Sys.UI.DomElement.removeCssClass(g,"rdNone");
}else{Sys.UI.DomElement.addCssClass(g,"rdNone");
this.get_titleBar().style.display="none";
}},get_width:function(){return this._width;
},set_width:function(g){this._width=g;
this.updateClientState();
if(this._initialized&&this._renderingView){this._renderingView.set_width(g);
}},get_resizable:function(){return this._resizable;
},set_resizable:function(g){this._resizable=g;
this._initResizableWidget();
},get_renderMode:function(){return this._renderMode;
},set_renderMode:function(g){this._renderMode=g;
}};
$telerik.$.registerControlProperties(Telerik.Web.UI.RadDock,{allowedZones:[],animationDuration:300,autoPostBack:false,dockMode:Telerik.Web.UI.DockMode.Default,dockZone:null,enableAnimation:false,forbiddenZones:[],index:0,layoutID:null,skin:"Default",tag:"",uniqueID:null,uniqueName:null,shortcuts:[]});
$telerik.$.extend({registerControlEventsDock:function(g,h){$telerik.$.registerControlEvents(g,h);
$telerik.$.each(h,function(k,j){g.prototype["raise_"+j]=function(i){this.raiseEvent(j,i);
};
});
}});
$telerik.$.registerControlEventsDock(Telerik.Web.UI.RadDock,["command","dockPositionChanged","dockPositionChanging","drag","dragEnd","dragStart","enterZone","initialize","leaveZone","resizeEnd","resizeStart","load"]);
Telerik.Web.UI.RadDock.registerClass("Telerik.Web.UI.RadDock",Telerik.Web.UI.RadWebControl);
Telerik.Web.UI.RadDock.prototype.repaint=function(){this._renderingView.repaint();
if(this._resizableWidget){this._resizableWidget.repaint();
}};
Telerik.Web.UI.Dock.ShortCutCancelEventArgs=function(g,h){b.Dock.ShortCutCancelEventArgs.initializeBase(this);
this._domEvent=g;
this._shortCut=h;
};
Telerik.Web.UI.Dock.ShortCutCancelEventArgs.prototype={get_shortCut:function(){return this._shortCut;
},get_domEvent:function(){return this._domEvent;
}};
Telerik.Web.UI.Dock.ShortCutCancelEventArgs.registerClass("Telerik.Web.UI.Dock.ShortCutCancelEventArgs",Sys.CancelEventArgs);
Telerik.Web.UI.DockCommand=function(g){Telerik.Web.UI.DockCommand.initializeBase(this,[g]);
};
Telerik.Web.UI.DockCommand.prototype={add_command:function(g){this.get_events().addHandler("command",g);
},remove_command:function(g){this.get_events().removeHandler("command",g);
},raise_command:function(g){var h=this.get_events().getHandler("command");
if(h){h(this.get_radDock(),g);
}},onCommand:function(h){var g=new Sys.CancelEventArgs();
g.command=this;
g.event=h;
g.Command=this;
this.raise_command(g);
if(g.get_cancel()){return;
}this.get_radDock().raise_command(g);
if(g.get_cancel()){return;
}this.get_radDock().updateClientState();
this.conditionalPostback();
},onMouseDown:function(g){return $telerik.cancelRawEvent(g.rawEvent);
},_stopPropagation:function(g){g.stopPropagation();
},conditionalPostback:function(){if(this.get_autoPostBack()){this.get_radDock().doPostBack(this.get_name());
}},initialize:function(){Telerik.Web.UI.DockCommand.callBaseMethod(this,"initialize");
this.attachCommandHandlers();
},dispose:function(){this.detachCommandHandlers();
Telerik.Web.UI.DockCommand.callBaseMethod(this,"dispose");
},attachCommandHandlers:function(){var g=this.get_element();
var h=this._touchStartEvent=this._getSupportedTouchEvent();
$addHandlers(g,{click:this.onCommand,mousedown:this.onMouseDown},this);
if(h){a(g).on(h,this._stopPropagation);
}},detachCommandHandlers:function(){var g=this.get_element();
$clearHandlers(g);
if(this._touchStartEvent){a(g).off(this._touchStartEvent,this._stopPropagation);
}},_getSupportedTouchEvent:function(){var g=window;
return"ontouchstart" in g?"touchstart":"PointerEvent" in g?"pointerdown":"MSPointerEvent" in g?"MSPointerDown":f;
}};
$telerik.$.registerControlProperties(Telerik.Web.UI.DockCommand,{autoPostBack:false,clientTypeName:null,cssClass:"rdCustom",name:"Custom",radDock:null,shortCut:"",text:"Custom"});
Telerik.Web.UI.DockCommand.registerClass("Telerik.Web.UI.DockCommand",Sys.UI.Control);
Telerik.Web.UI.DockToggleCommand=function(g){Telerik.Web.UI.DockToggleCommand.initializeBase(this,[g]);
this._state=1;
this._alternateCssClass="rdCustom";
this._alternateText="Custom";
this._initialSetState=false;
};
Telerik.Web.UI.DockToggleCommand.prototype={updateState:function(){var g=this.get_element();
var h=this.get_radDock()._renderMode==Telerik.Web.UI.RenderMode.Classic?g.getElementsByTagName("span")[0]:g;
if(this.get_state()==1){g.title=this.get_text();
Sys.UI.DomElement.addCssClass(h,this.get_cssClass());
Sys.UI.DomElement.removeCssClass(h,this.get_alternateCssClass());
}else{g.title=this.get_alternateText();
Sys.UI.DomElement.addCssClass(h,this.get_alternateCssClass());
Sys.UI.DomElement.removeCssClass(h,this.get_cssClass());
}},get_state:function(){return this._state;
},set_state:function(g){this._state=g;
if(this._initialSetState){this.updateState();
}},get_alternateCssClass:function(){return this._alternateCssClass;
},set_alternateCssClass:function(g){this._alternateCssClass=g;
},get_alternateText:function(){return this._alternateText;
},set_alternateText:function(g){this._alternateText=g;
},initialize:function(){Telerik.Web.UI.DockToggleCommand.callBaseMethod(this,"initialize");
this._initialSetState=true;
this.updateState();
},dispose:function(){b.DockToggleCommand.callBaseMethod(this,"dispose");
}};
b.DockToggleCommand.registerClass("Telerik.Web.UI.DockToggleCommand",Telerik.Web.UI.DockCommand);
b.DockCloseCommand=function(g){Telerik.Web.UI.DockCloseCommand.initializeBase(this,[g]);
this._cssClass="rdClose";
this._name="Close";
this._text="Close";
};
b.DockCloseCommand.prototype={onCommand:function(g){this.get_radDock().set_closed(true,true);
}};
b.DockCloseCommand.registerClass("Telerik.Web.UI.DockCloseCommand",Telerik.Web.UI.DockCommand);
b.DockExpandCollapseCommand=function(g){b.DockExpandCollapseCommand.initializeBase(this,[g]);
this._cssClass="rdCollapse";
this._alternateCssClass="rdExpand";
this._name="ExpandCollapse";
this._text="Collapse";
this._alternateText="Expand";
};
b.DockExpandCollapseCommand.prototype={onCommand:function(g){this.get_radDock().set_collapsed(!this.get_radDock().get_collapsed(),true);
}};
b.DockExpandCollapseCommand.registerClass("Telerik.Web.UI.DockExpandCollapseCommand",Telerik.Web.UI.DockToggleCommand);
b.DockPinUnpinCommand=function(g){Telerik.Web.UI.DockPinUnpinCommand.initializeBase(this,[g]);
this._cssClass="rdUnpin";
this._alternateCssClass="rdPin";
this._name="PinUnpin";
this._text="Pin";
this._alternateText="Unpin";
};
b.DockPinUnpinCommand.prototype={onCommand:function(g){if(this.get_radDock().get_dockZoneID()){return;
}this.get_radDock().set_pinned(!this.get_radDock().get_pinned());
Telerik.Web.UI.DockPinUnpinCommand.callBaseMethod(this,"onCommand");
}};
b.DockPinUnpinCommand.registerClass("Telerik.Web.UI.DockPinUnpinCommand",Telerik.Web.UI.DockToggleCommand);
})($telerik.$,Telerik.Web.UI);
Type.registerNamespace("Telerik.Web.UI.Dock");
(function(b,a){b.Dock.IView=function(c){};
b.Dock.IView.prototype={initialize:function(){},dispose:function(){},repaint:function(){},clone:function(){},get_width:function(){},set_width:function(c){},get_height:function(){},set_height:function(c){},get_title:function(){},set_title:function(c){},isPinned:function(){},pin:function(c){},isCollapsed:function(){},collapse:function(d,c){},isClosed:function(){},get_minWidth:function(){},get_minHeight:function(){},get_titleElement:function(){},get_titleBar:function(){},get_commandsContainer:function(){},get_contentContainer:function(){},getCommandsElements:function(){},fitWidth:function(){},unfitWidth:function(){}};
b.Dock.IView.registerInterface("Telerik.Web.UI.Dock.IView");
})(Telerik.Web.UI,$telerik.$);
Type.registerNamespace("Telerik.Web.UI.Dock");
(function(b,a){b.Dock.BaseView=function(c){this.control=c;
this.initialize();
};
b.Dock.BaseView.prototype={initialize:function(){this.initializeFormElement();
},isPinned:function(){return this.control._pinned;
},isCollapsed:function(){return this.control._collapsed;
},isClosed:function(){return this.control._closed;
},get_width:function(){return this.control.get_width();
},get_height:function(){return this.control.get_height();
},get_title:function(){return this.control._title;
},set_title:function(d){var c=this.get_titleElement();
if(c){c.innerHTML=d;
}},get_contentContainer:function(){if(!this._contentContainer){this._contentContainer=$get(this.control.get_id()+"_C");
}return this._contentContainer;
},get_titleBar:function(){if(!this._titleBar){this._titleBar=$get(this.control.get_id()+"_T");
}return this._titleBar;
},get_commandsContainer:function(){if(!this._commandsContainer){var c=this.get_titleBar();
if(c){this._commandsContainer=$telerik.getElementByClassName(c,"rdCommands","UL");
}else{this._commandsContainer=null;
}}return this._commandsContainer;
},initializeFormElement:function(){var c=this.control.get_element().parentNode;
while(c){if(c.tagName.toLowerCase()==="form"){this._form=this.control._form=c;
break;
}c=c.parentNode;
}}};
b.Dock.BaseView.registerClass("Telerik.Web.UI.Dock.BaseView");
})(Telerik.Web.UI,$telerik.$);
Type.registerNamespace("Telerik.Web.UI.Dock");
(function(b,a){b.Dock.ClassicView=function(c){b.Dock.ClassicView.initializeBase(this,[c]);
this.control=c;
};
b.Dock.ClassicView.prototype={initialize:function(){Telerik.Web.UI.Dock.ClassicView.callBaseMethod(this,"initialize");
this._initializeHtmlElementVariables();
this._setUnselectableOn();
this.control._setHandle(this._titleBar||this._grip);
if(this.get_height()){this._setContentContainerHeight(this._height);
}this._middleMiddleCell.style.height="auto";
if(this.get_height()!=null){this._setHeightHtmlEl(this.get_height());
}this._fixEmWidth();
},repaint:function(){if(this.isClosed()||$telerik.getInvisibleParent(this.control.get_element())!=null){return;
}this._fixEmWidth();
this._setContentContainerHeight();
},clone:function(f){var e=this.control.get_element();
var g=e.cloneNode(true);
g.removeAttribute("control");
var h=$telerik.getElementByClassName(g,"rdTable","TABLE").rows;
var i=$telerik.getElementByClassName(h[0].cells[1],"rdTitleBar","DIV");
var d=$telerik.getElementByClassName(h[1].cells[1],"rdContent","DIV");
var c=g.getElementsByTagName("input")[0];
if(i){i.setAttribute("id",f+"_T");
}d.setAttribute("id",f+"_C");
g.setAttribute("id",f);
c.setAttribute("id",f+"_ClientState");
c.setAttribute("name",f+"_ClientState");
e.parentNode.insertBefore(g,e.nextSibling);
return g;
},get_minWidth:function(){var d=0;
for(var c=0;
c<this.getCommandsElements().length;
c++){d+=this.getCommandsElements()[c].clientWidth;
}if(this._topLeftBar){d+=this._topLeftBar.clientWidth;
}if(this._topRightBar){d+=this._topLeftBar.clientWidth;
}return d;
},get_minHeight:function(){var c=0;
if(this._topBar){c+=this._topBar.clientHeight||this._topBar.offsetHeight;
}if(this._bottomBar){c+=this._bottomBar.clientHeight||this._bottomBar.offsetHeight;
}return c;
},getCommandsElements:function(){return this.get_commandsContainer()?this.get_commandsContainer().getElementsByTagName("a"):[];
},get_titleElement:function(){var c=this.get_titleBar();
return c?c.getElementsByTagName("em")[0]:null;
},set_width:function(c){this._setWidthHtmlEl(c);
this._fixEmWidth();
},set_height:function(c){if(this._tableElement){this._tableElement.style.height="auto";
}this._setHeight(c);
},pin:function(f){if($telerik.isIE6){if(f){this.control.set_enableDrag(false);
}else{this.control.set_enableDrag(true);
}return;
}var c=this.control.get_element();
c.style.position="absolute";
var e=$telerik.getScrollOffset(c,true);
var d=this.control._getLocation(c);
if(f){d=this.control.subtractPoints(d,e);
this.control._setLocation(d);
c.style.position="fixed";
this.control.set_enableDrag(false);
}else{d=this.control.addPoints(d,e);
this.control._setLocation(d);
this.control.set_enableDrag(true);
}},collapse:function(p,m){var n=this,g=this.control,i=g.get_element(),j=this._tableElement,h=this.get_contentContainer(),f=h.style.overflow;
$telerik.stopTransition(h,false,true);
var d=g.get_enableAnimation()?g.get_animationDuration():0;
if(!m){d=0;
}var c={};
var k=g.getCommand("ExpandCollapse");
i.style.height="auto";
if(g._resizable){j.style.height="auto";
}h.style.overflow="hidden";
if(p){g._expandedHeight=g._height?parseInt(g._height,10):parseInt(g._getBounds().height,10);
if(!h.style.height){n._forceContentContainerHeight(g._expandedHeight);
}c.height="0px";
$telerik.transition(h,c,d,"easeIn",function(){n._setContentContainerHeight();
g.addCssClass("rdCollapsed");
if(k){k.set_state(2);
Telerik.Web.UI.DockExpandCollapseCommand.callBaseMethod(k,"onCommand");
}if(g._resizable){if(g.get_dockZoneID()){$find(g.get_dockZoneID())._resetDocksResizeHandles();
}else{g._resizableWidget.repaint();
}}h.style.overflow=f;
});
}else{if(g._collapsed&&!p&&!g._expandedHeight){if(g._height){g._expandedHeight=parseInt(g._height,10);
}else{h.style.height="auto";
g.removeCssClass("rdCollapsed");
g._expandedHeight=parseInt(g._getBounds().height,10);
g.addCssClass("rdCollapsed");
}}g.removeCssClass("rdCollapsed");
var o=this._getBounds(this._topBar).height,e=this._getBounds(this._bottomMiddleBar).height,l=parseInt(g._expandedHeight,10)-o-e;
c.height=l+"px";
h.style.height="0px";
$telerik.transition(h,c,d,"easeIn",function(){h.style.display="";
j.style.height="";
if(g.get_height()!=null){n._setHeightHtmlEl(g._expandedHeight);
}if(g._resizable){if(g.get_dockZoneID()){$find(g.get_dockZoneID())._resetDocksResizeHandles();
}else{g._resizableWidget.repaint();
}}if(g.get_height()==null){i.style.height="";
}g._renderingView._setContentContainerHeight();
if(k){k.set_state(1);
}$telerik.repaintChildren(g);
if(g._resizable){g.set_height($telerik.getBounds(i).height+"px");
}if(k){Telerik.Web.UI.DockExpandCollapseCommand.callBaseMethod(k,"onCommand");
}h.style.overflow=f;
});
}if(!m&&g._resizable){g._resizableWidget.repaint();
}},fitWidth:function(){this.control.get_element().style.width="100%";
this.get_contentContainer().style.width="100%";
this._fixEmWidth();
},unfitWidth:function(){this.set_width(this.get_width());
},dispose:function(){this._disposeHtmlVariables();
},_initializeHtmlElementVariables:function(){this._grip=$get(this.control.get_id()+"_G");
this._titleBar=$get(this.control.get_id()+"_T");
this.get_commandsContainer();
var c=this.control.get_element();
this._tableElement=c.getElementsByTagName("table")[0];
var d=this._tableElement.rows;
this._topBar=d[0];
this._topLeftBar=d[0].cells[0];
this._topRightBar=d[0].cells[2];
this._middleLeftBar=d[1].cells[0];
this._middleMiddleCell=d[1].cells[1];
this._middleRightBar=d[1].cells[2];
this._bottomBar=d[2];
this._bottomLeftBar=d[2].cells[0];
this._bottomMiddleBar=d[2].cells[1];
this._bottomRightBar=d[2].cells[2];
},_disposeHtmlVariables:function(){this._grip=this._titleBar=this._commandsContainer=this._tableElement=this._topBar=this._topLeftBar=this._topRightBar=this._middleLeftBar=this._middleMiddleCell=this._middleRightBar=this._bottomBar=this._bottomLeftBar=this._bottomMiddleBar=this._bottomRightBar=this._form=null;
},_setUnselectableOn:function(){this._topLeftBar.setAttribute("unselectable","on");
this._topRightBar.setAttribute("unselectable","on");
this._middleLeftBar.setAttribute("unselectable","on");
this._middleRightBar.setAttribute("unselectable","on");
this._bottomLeftBar.setAttribute("unselectable","on");
this._bottomMiddleBar.setAttribute("unselectable","on");
this._bottomRightBar.setAttribute("unselectable","on");
},_setHeight:function(c){this._setContentContainerHeight(c);
this._setHeightHtmlEl(c);
},_setContentContainerHeight:function(d){var e=this,c=this.get_contentContainer();
if(!c){return;
}if(e.get_height()!=null||e._resizable){e._forceContentContainerHeight(d);
}else{c.style.height="";
}},_forceContentContainerHeight:function(g){var j=this,f=j.get_contentContainer(),c=j._getBounds();
var h=g!=null?parseInt(g,10):c.height,e=j._getBounds(j._topBar),d=j._getBounds(j._bottomBar),i=h-e.height-d.height;
f.style.height=(i<0?0:i)+"px";
},_setHeightHtmlEl:function(d,c){if(!c){c=this.control.get_element();
}if(!d){c.style.height="";
return;
}if(d.toString().indexOf("%")>-1){c.style.height=parseInt(d,10)+"%";
}else{c.style.height=parseInt(d,10)+"px";
}},_setWidthHtmlEl:function(d,c){if(!d){return;
}if(!c){c=this.control.get_element();
}if(d.toString().indexOf("%")>-1){c.style.width=parseInt(d,10)+"%";
}else{c.style.width=parseInt(d,10)+"px";
}},_fixEmWidth:function(){var f=this.get_titleBar();
if(f==null){return;
}var e=this.control.get_element();
var h=this.get_titleElement();
if(!h){return;
}var c=this.get_commandsContainer();
var d=c?$telerik.getOuterBounds(c).width:0;
h.style.display="block";
h.style.width="";
if(h.offsetWidth+30+d<e.offsetWidth){return;
}var g=$telerik.getBounds(f).width;
if(g>0){if($telerik.isIE6){h.style.display="none";
g=$telerik.getBounds(f).width;
h.style.display="block";
}var j=g-d-30;
var i=j>0?j:0;
h.style.width=i+"px";
}},_getBounds:function(c){if(!c){c=this.control.get_element();
}return $telerik.getBounds(c);
}};
b.Dock.ClassicView.registerClass("Telerik.Web.UI.Dock.ClassicView",Telerik.Web.UI.Dock.BaseView,Telerik.Web.UI.Dock.IView);
})(Telerik.Web.UI,$telerik.$);
Type.registerNamespace("Telerik.Web.UI.Dock");
(function(b,a){b.Dock.LightweightView=function(c){b.Dock.LightweightView.initializeBase(this,[c]);
this.control=c;
};
b.Dock.LightweightView.prototype={initialize:function(){var d=this;
var c=d.control;
b.Dock.LightweightView.callBaseMethod(d,"initialize");
c._setHandle(d._getHandle());
if(c.get_collapsed()){d._setCollapsedDockHeight();
}else{if(c.get_height()){d.set_height(c.get_height());
}}},dispose:function(){},repaint:function(){},clone:function(d){var e=this.control._element;
var c=e.cloneNode(true);
this._fixCloneIds(c,d);
e.parentNode.insertBefore(c,e.nextSibling);
return c;
},get_minWidth:function(){var c=0;
if(this.get_commandsContainer()){c+=this.get_commandsContainer().clientWidth;
}if(this._getTitleWrapper()){c+=parseInt($telerik.getComputedStyle(this._getTitleWrapper(),"padding-left",0),10);
c+=parseInt($telerik.getComputedStyle(this._getTitleWrapper(),"padding-right",0),10);
}return c;
},get_minHeight:function(){return this._getTitleWrapperHeight();
},set_width:function(d){var c=d.indexOf&&d.indexOf("%")>-1?"%":"px";
this.control.get_element().style.width=parseInt(d,10)+c;
if(this.get_titleElement()){this._sizeTitleElement();
}},set_height:function(c){if(c){this.control.get_element().style.height=parseInt(c,10)+"px";
this._setContentWrapperHeight(c);
}},pin:function(d){var c=d?"fixed":"absolute";
this.control.set_enableDrag(!d);
this.control.get_element().style.position=c;
},collapse:function(i,g){var c=this.control.getCommand("ExpandCollapse");
var h=this,f={},d=this.control,e=this.control.get_enableAnimation()?this.control.get_animationDuration():0;
if(i){this.control._element.style.overflow="hidden";
f.height=this._getTitleWrapperHeight();
d._expandedHeight=this._calcExpandedHeight();
if(!h.get_height()){h.set_height(d._expandedHeight);
}}else{this.control._element.style.overflow="";
d.removeCssClass("rdCollapsed");
this.set_height(this._getTitleWrapperHeight());
if(!d._expandedHeight){d._expandedHeight=this._calcExpandedHeight();
}f.height=parseInt(d._expandedHeight,10);
}$telerik.stopTransition(this.control._element,false,true);
$telerik.transition(this.control._element,f,e,"easeIn",function(){if(i){h.set_height(h._getTitleWrapperHeight());
d.addCssClass("rdCollapsed");
}else{h.set_height(d._expandedHeight);
}if(d._resizable&&d._resizableWidget){if(d.get_dockZoneID()){$find(d.get_dockZoneID())._resetDocksResizeHandles();
}else{d._resizableWidget.repaint();
}}if(c){c.set_state(i?2:1);
Telerik.Web.UI.DockExpandCollapseCommand.callBaseMethod(c,"onCommand");
}});
},close:function(d,c){},get_titleElement:function(){return this.get_titleBar()?this.get_titleBar().getElementsByTagName("h6")[0]:null;
},getCommandsElements:function(){return a(".rdCommandButton",this.get_commandsContainer()).toArray();
},fitWidth:function(){this.originalWidth=this.get_width();
this.control.get_element().style.width="100%";
if(this.get_titleElement()){this._sizeTitleElement();
}},unfitWidth:function(){var c=this.originalWidth||this.get_width();
this.set_width(c);
this.originalWidth=null;
},_getHandle:function(){return $get(this.control.get_id()+"_T")||$get(this.control.get_id()+"_G");
},_sizeTitleElement:function(){var f=this.get_titleElement(),e=this.get_titleBar(),c=this.get_commandsContainer(),d=c?parseInt(c.clientWidth,10):0;
f.style.width=Math.max(0,parseInt(e.clientWidth,10)-d)+"px";
f.style.display="";
},_setContentWrapperHeight:function(d){var e=this;
var c=this.get_contentContainer().parentNode;
if(e.control.get_height()){c.style.overflow="auto";
}c.style.height=parseInt(d,10)-this._getTitleWrapperHeight()+"px";
},_getBounds:function(c){if(!c){c=this.control.get_element();
}return $telerik.getBounds(c);
},_getTitleWrapperHeight:function(){var c=a(this.control._element).find(".rdTitleWrapper");
var d=$telerik.isIE6||$telerik.isIE7?c.get(0).clientHeight:c.get(0).offsetHeight;
return parseInt(d,10);
},_fixCloneIds:function(c,d){a(c).attr("id",d);
a(".rdTitleBar",c).attr("id",d+"_T");
a(".rdContent",c).attr("id",d+"_C");
a("input[id$='ClientState']").attr("id",d+"_ClientState");
},_getTitleWrapper:function(){return a(".rdTitleWrapper",this.control._element).get(0);
},_calcExpandedHeight:function(){var c=this.control;
return c._expandedHeight&&!isNaN(parseInt(c._expandedHeight,10))?parseInt(c._expandedHeight,10):c._height?parseInt(c._height,10):parseInt(c._element.clientHeight,10);
},_setCollapsedDockHeight:function(){var d=this;
var c=d.control;
c._expandedHeight=d._calcExpandedHeight();
d.set_height(d._getTitleWrapperHeight());
a(c.get_element()).css("overflow","");
}};
b.Dock.LightweightView.registerClass("Telerik.Web.UI.Dock.LightweightView",Telerik.Web.UI.Dock.BaseView,Telerik.Web.UI.Dock.IView);
})(Telerik.Web.UI,$telerik.$);
