Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.WindowManager");
$telerik.toWindowManager=function(a){return a;
};
$telerik.findWindowManager=$find;
function GetRadWindowManager(){return Telerik.Web.UI.WindowManager.Manager;
}window.radalert=function(g,f,c,e,a,b){var d=GetRadWindowManager();
return d.radalert(g,f,c,e,a,b);
};
window.radconfirm=function(h,a,g,d,b,f,c){var e=GetRadWindowManager();
return e.radconfirm(h,a,g,d,b,f,c);
};
window.radprompt=function(h,a,g,d,b,f,c){var e=GetRadWindowManager();
return e.radprompt(h,a,g,d,b,f,c);
};
window.radopen=function(f,c,g,a,b,e){var d=GetRadWindowManager();
return d.open(f,c,null,g,a,b,e);
};
window.radopenWithContainer=function(b,d){var c=GetRadWindowManager();
var a=$get(b);
if(!a){c.radalert("Content element with such ClientID not found!<br/> Make sure you have provided a correct ClientID!");
return;
}return c.open(null,d,a);
};
Telerik.Web.UI.RadWindowManager=function(a){Telerik.Web.UI.RadWindowManager.initializeBase(this,[a]);
this._windowIDs=[];
this._windows=[];
this._preserveClientState=false;
this.Open=this.open;
this.GetWindowByName=this.getWindowByName;
this.GetWindowById=this.getWindowById;
this.GetActiveWindow=this.getActiveWindow;
this.GetWindowObjects=this.get_windows;
this.GetWindows=this.get_windows;
this.Cascade=this.cascade;
this.Tile=this.tile;
this.RestoreAll=this.restoreAll;
this.MaximizeAll=this.maximizeAll;
this.MinimizeAll=this.minimizeAll;
this.ShowAll=this.showAll;
this.CloseAll=this.closeAll;
this.CloseActiveWindow=this.closeActiveWindow;
this.MinimizeActiveWindow=this.minimizeActiveWindow;
this.RestoreActiveWindow=this.restoreActiveWindow;
};
Telerik.Web.UI.RadWindowManager.prototype={get_zIndex:function(){return Telerik.Web.UI.RadWindowUtils._zIndex;
},set_zIndex:function(a){if(isNaN(a)){return;
}Telerik.Web.UI.RadWindowUtils._zIndex=a;
},initialize:function(b){try{var c=this.get_element().style.zIndex;
if(c){this.set_zIndex(c);
}}catch(a){}this._initialize();
this._registerAsPageManager();
if(this.get_preserveClientState()){this.restoreState();
}},dispose:function(){var a=this.get_preserveClientState();
if(a){this.saveState();
}this._disposeWindows();
this._windows=null;
Telerik.Web.UI.RadWindowManager.callBaseMethod(this,"dispose");
},open:function(k,m,b,l,d,e,i){var a,g=this.getWindowByName(m);
if(!g){if(!m){m=this.get_id()+this._getUniqueId();
}g=this._createWindow(m,b);
var c=this.get_element().className;
if(c){g.set_cssClass(c.replace(/^ /,""));
}}else{if(b&&this.get_navigateUrl()){g._dockMode=false;
}}if(k&&!g.get_reloadOnShow()&&g._iframe&&g._iframe.src!=k){g.setUrl(k);
}else{if(k){g._navigateUrl=k;
}}if(l||d){g.setSize(l,d);
}var h=g.get_popupElement();
var f=parseInt(e,10);
if(!isNaN(f)){g.set_left(f);
if(h){a=g.getWindowBounds();
g.moveTo(f,a.y);
}}var j=parseInt(i,10);
if(!isNaN(j)){g.set_top(j);
if(h){a=g.getWindowBounds();
g.moveTo(a.x,j);
}}g.show();
return g;
},radalert:function(g,e,c,d,a,b){var f=this._getStandardPopup("alert",g,null,b);
if(typeof(d)!="undefined"){f.set_title(d);
}f.setSize(e?e:280,c?c:200);
f.set_clientCallBackFunction(function(i,h){if(a){a(h);
}});
f.center();
f.show();
return f;
},radconfirm:function(h,a,f,d,b,e,c){var g=this._getStandardPopup("confirm",h,null,c);
if(typeof(e)!="undefined"){g.set_title(e);
}g.setSize(f?f:280,d?d:200);
g.set_clientCallBackFunction(function(j,i){if(a){a(i);
}});
g.center();
g.show();
return g;
},radprompt:function(i,a,g,e,b,f,c){var h=this._getStandardPopup("prompt",i,c);
if(typeof(f)!="undefined"){h.set_title(f);
}h.setSize(g?g:280,e?e:200);
h.set_clientCallBackFunction(function(k,j){if(a){a(j);
}});
h.center();
h.show();
if(c&&$telerik.isIE){var d=h.get_popupElement().getElementsByTagName("INPUT")[0];
if(d){d.value=c;
}}return h;
},getActiveWindow:function(){return Telerik.Web.UI.RadWindowController.get_activeWindow();
},getWindowById:function(b){var c=this.get_windows();
for(var a=0;
a<c.length;
a++){var d=c[a];
if(b==d.get_id()){return d;
}}return null;
},getWindowByName:function(b){var c=this.get_windows();
if(!c){return null;
}for(var a=0;
a<c.length;
a++){var d=c[a];
if(b==d.get_name()){return d;
}}return null;
},removeWindow:function(a){if(!a){return;
}var b=this.getWindowByName(a.get_name());
var c=this.get_windows();
if(b){Array.remove(c,b);
}},_getUniqueId:function(){return""+(new Date()-100);
},_initialize:function(){var a=this._windowIDs;
for(var b=0;
b<a.length;
b++){var d=a[b];
var c=$find(d);
if(!c){continue;
}c.set_windowManager(this);
this._windows[this._windows.length]=c;
}},_disposeWindows:function(){for(var a=0;
a<this._windows.length;
a++){var b=this._windows[a];
if(b.isCloned()){b.dispose();
}}this._windows=[];
},clearCloneCache:function(){this.__clonedProperties__=null;
},_createWindow:function(c,a){var b=this.clone(c);
b.set_modal(b.isModal());
b.set_centerIfModal(this.get_centerIfModal());
b.set_name(c);
this._windows[this._windows.length]=b;
b.set_windowManager(this);
if(a){b.set_contentElement(a);
b._dockMode=true;
b.set_behaviors(b.get_behaviors()&~Telerik.Web.UI.WindowBehaviors.Reload);
}return b;
},_replaceLocalization:function(e,a){var d=/##LOC\[(.*?)\]##/;
while(e.match(d)){var b=this._getLocalizationString(RegExp.$1);
var c=b?b:"";
e=e.replace(d,c);
}return e;
},_getStandardPopup:function(k,j,f,e){var i=this._createWindow(k+this._getUniqueId(),false);
i.set_destroyOnClose(true);
i.set_restrictionZoneID(null);
i.set_modal(true);
j=j.replace(/\$/g,"$$$");
var a=document.getElementById(this.get_id()+"_"+k.toLowerCase()+"template");
var b=$telerik.isIE&&!$telerik.isIE9Mode?"''":"";
var c=this._stringFormat(a.innerHTML,i.get_id(),j,f?f:b);
c=this._replaceLocalization(c,Telerik.Web.UI.RadWindowUtils.Localization);
var h=document.createElement("div");
h.innerHTML=c;
h.id=i.get_id()+"_content";
i.set_behaviors(Telerik.Web.UI.WindowBehaviors.Close+Telerik.Web.UI.WindowBehaviors.Move);
i.set_visibleStatusbar(false);
i._isPredefined=true;
i.set_contentElement(h);
if(k!="prompt"&&e!=null&&e!="null"){var d=$telerik.$(h).find("div[class*='rwDialog']")[0];
if(d){if(e!=""){d.style.backgroundImage="url('"+e+"')";
}else{$telerik.$(d).removeClass("rad"+k);
$telerik.$(d).removeClass("rw"+k.substr(0,1).toUpperCase()+k.substr(1)+"Dialog");
}}}var g=i.get_contentElement().getElementsByTagName("INPUT")[0];
if(!g){g=i.get_contentElement().getElementsByTagName("A")[0];
}if(g&&g.focus){window.setTimeout(function(){var m=true;
if(g.setActive){try{g.setActive();
m=false;
}catch(l){}}if(m){g.focus();
}},0);
}return i;
},_stringFormat:function(b){for(var a=1;
a<arguments.length;
a++){b=b.replace(new RegExp("\\{"+(a-1)+"\\}","ig"),arguments[a]);
}return b;
},_registerAsPageManager:function(){var a=Telerik.Web.UI.WindowManager.Manager;
var b=this.get_id();
if(a&&a.get_id()==b){a.dispose();
Telerik.Web.UI.WindowManager.Manager=null;
}if(a&&!a.get_id()){Telerik.Web.UI.WindowManager.Manager=null;
}if(!Telerik.Web.UI.WindowManager.Manager){Telerik.Web.UI.WindowManager.Manager=this;
}if(a){this._ensureFirstManagerIsRegistered();
}},_ensureFirstManagerIsRegistered:function(){var a=this.get_id(),b=this;
document.body.innerHTML.replace(/\$create\(Telerik.Web.UI.RadWindowManager.*\$get\("([^"]*)"\)/,function(d,c){if(a==c){Telerik.Web.UI.WindowManager.Manager=b;
}});
},saveWindowState:function(c){if(!c||!c.isCreated()){return;
}var a=c.getWindowBounds();
var b=(c.isVisible()||c.isMinimized())+"@"+a.width+"@"+a.height+"@"+a.x+"@"+a.y+"@"+c.isMinimized();
this._setRadWindowCookie(c.get_id(),b);
},saveState:function(){var c=this.get_windows();
var a;
for(a=0;
a<c.length;
a++){var b=c[a];
if(b.isCloned()){this.saveWindowState(b);
}}},restoreState:function(){var a;
function e(h,g){var f=g.split("@");
if(f.length>1){if("true"==f[0]&&!h.isVisible()){h.show();
}window.setTimeout(function(){if(parseInt(f[1],10)>0){h.set_width(f[1]);
}if(parseInt(f[2],10)>0){h.set_height(f[2]);
}if("true"==f[0]){h.moveTo(parseInt(f[3],10),parseInt(f[4],10));
}if("true"==f[5]){h.minimize();
}},1);
}}var d=this.get_windows();
for(a=0;
a<d.length;
a++){var c=d[a];
var b=this._getRadWindowCookie(c.get_id());
if(b){e(c,b);
}}},_getOnlyCookie:function(){var d="RadWindowCookie";
var a=document.cookie.split("; ");
for(var c=0;
c<a.length;
c++){var b=a[c].split("=");
if(d==b[0]){return b[1];
}}return null;
},_setRadWindowCookie:function(d,f){d="["+d+"]";
var e=this._getOnlyCookie();
var b="";
var c="";
if(e){var a=e.split(d);
if(a&&a.length>1){b=a[0];
c=a[1].substr(a[1].indexOf("#")+1);
}else{c=e;
}}var g=new Date();
g.setFullYear(g.getFullYear()+10);
document.cookie="RadWindowCookie="+(b+d+"-"+f+"#"+c)+";path=/;expires="+g.toUTCString()+";";
},_getRadWindowCookie:function(d){var a=this._getOnlyCookie();
if(!a){return;
}var e=null;
d="["+d+"]";
var c=a.indexOf(d);
if(c>=0){var b=c+d.length+1;
e=a.substring(b,a.indexOf("#",b));
}return e;
},cascade:function(){var d=0;
var c=0;
var b=this._getWindowsSortedByZindex();
for(var a=0;
a<b.length;
a++){var e=b[a];
if(!e.isClosed()&&e.isVisible()){e.restore();
e.moveTo(c,d);
e.setActive(true);
d+=25;
c+=25;
}}},tile:function(){var c=this._getWindowsSortedByZindex();
var e=0,a;
for(a=0;
a<c.length;
a++){var k=c[a];
if(!k.isClosed()&&k.isVisible()){e++;
}}var f=5;
var d=0;
var g=1;
if(e<=f){d=e;
}else{a=2;
while((e*a)<(f*(a+1))){a++;
if(a>6){break;
}}g=a;
d=Math.ceil(e/g);
}var h=$telerik.getClientBounds();
var m=Math.floor(h.width/d);
var l=Math.floor(h.height/g);
var b=document.documentElement.scrollLeft||document.body.scrollLeft;
var o=document.documentElement.scrollTop||document.body.scrollTop;
var n=0;
for(a=0;
a<c.length;
a++){var j=c[a];
if(!j.isClosed()&&j.isVisible()){n++;
if((n-1)%(d)==0&&n>d){o+=l;
b=document.documentElement.scrollLeft||document.body.scrollLeft;
}j.restore();
j.moveTo(b,o);
j.setSize(m,l);
b+=m;
}}},closeActiveWindow:function(){this._executeActiveWindow("close");
},minimizeActiveWindow:function(){this._executeActiveWindow("minimize");
},restoreActiveWindow:function(){this._executeActiveWindow("restore");
},closeAll:function(){this._executeAll("close");
},showAll:function(){this._executeAll("show");
},minimizeAll:function(){this._executeAll("minimize");
},maximizeAll:function(){this._executeAll("maximize");
},restoreAll:function(){this._executeAll("restore");
},_getWindowsSortedByZindex:function(){var a=this._windows.concat([]);
var b=function(c,d){var e=c.get_zindex();
var f=d.get_zindex();
if(e==f){return 0;
}return(e<f?-1:1);
};
return a.sort(b);
},_executeAll:function(a){if(!this._windows){return;
}var c=this._windows.concat([]);
for(var b=0;
b<c.length;
b++){c[b][a]();
}},_executeActiveWindow:function(b){var a=this.getActiveWindow();
if(a&&"function"==typeof(a[b])){a[b]();
}},get_preserveClientState:function(){return this._preserveClientState;
},set_preserveClientState:function(a){if(this._preserveClientState!=a){this._preserveClientState=a;
}},set_windowControls:function(a){this._windowIDs=eval(a);
this._disposeWindows();
},set_child:function(a){},get_windowControls:function(){},get_windows:function(){return this._windows;
}};
Telerik.Web.UI.RadWindowManager.registerClass("Telerik.Web.UI.RadWindowManager",Telerik.Web.UI.RadWindow);
