(function(a,b){Type.registerNamespace("Telerik.Web.UI");
$telerik.toXmlHttpPanel=function(d){return d;
};
$telerik.findXmlHttpPanel=$find;
a.registerEnum(b,"XmlHttpPanelWcfRequestMethod",{GET:1,POST:2,PUT:4,DELETE:8});
b.RadXmlHttpPanel=function(d){b.RadXmlHttpPanel.initializeBase(this,[d]);
this._uniqueId="";
this._isCallbackPanel=false;
this._loadingPanelID="";
this._async=true;
this._dropDownTouchScroll=null;
this._wcfRequestMethod=b.XmlHttpPanelWcfRequestMethod.GET;
};
b.RadXmlHttpPanel.prototype={initialize:function(){b.RadXmlHttpPanel.callBaseMethod(this,"initialize");
this._loaded=true;
if(!this._isCallbackPanel&&this.get_value()){this.set_value(this.get_value());
}if(b.TouchScrollExtender._getNeedsScrollExtender()&&!this._dropDownTouchScroll){this._createTouchScrollExtender(true);
}},dispose:function(){this._createTouchScrollExtender(false);
b.RadXmlHttpPanel.callBaseMethod(this,"dispose");
},get_value:function(){return this._value;
},set_value:function(d){this._value=d;
if(!this._loaded){return;
}window.setTimeout(Function.createDelegate(this,function(){this._showLoadingPanel();
if(this.get_wcfServicePath()){this._execWsfServiceCall();
}else{if(this._isCallbackPanel){this._execCallback();
}else{var e=this._getWebServiceLoader();
e.loadData({context:this._getWebServiceArgument()});
}}}),10);
},reload:function(){this.set_value(this.get_value());
},_raiseResponseEnded:function(){this.raiseEvent("responseEnded",new Sys.EventArgs());
},set_html:function(e){this._hideLoadingPanel();
var d=new b.XmlHttpPanelEventArgs(e);
this.raiseEvent("responseEnding",d);
if(d.get_cancel()){return;
}e=d.get_content();
var i=this.get_wcfServiceMethod();
if(i){var h=i+"Result";
if(e[h]){e=e[h];
}}if(!e||typeof e!=="string"){e="";
}var f=this.get_element();
this._disposeElement(f,true);
f.innerHTML=e;
if(this.get_enableClientScriptEvaluation()){var g=Function.createDelegate(this,this._raiseResponseEnded);
$telerik.evalScripts(f,g);
}else{this._raiseResponseEnded();
}},_disposeElement:function(f,d){if(!f){return;
}if(f.nodeType===1){var e=f.getElementsByTagName("*");
for(var g=e.length-1;
g>=0;
g--){this._disposeElementInternal(e[g]);
}if(!d){this._disposeElementInternal(f);
}}},_disposeElementInternal:function(g){var f=g.dispose;
if(f&&typeof(f)==="function"){g.dispose();
}else{var e=g.control;
if(e&&typeof(e.dispose)==="function"){e.dispose();
}}},_hideLoadingPanel:function(){var d=this._getLoadingPanel();
if(d&&d.hide){d.hide(this.get_element().id);
}},_showLoadingPanel:function(){var d=this._getLoadingPanel();
if(d&&d.show){d.show(this.get_element().id);
}},_getLoadingPanel:function(){return $find(this.get_loadingPanelID());
},_getWebServiceArgument:function(){var d={Value:this._value};
return d;
},_getCallbackArgument:function(){var e=this.get_value();
if(typeof(e)!="string"){e=e+"";
}e=e.replace(/"/g,'\\"');
var d=String.format('{{ Value : "{0}"}}',e);
return d;
},_onError:function(e){if(!e){e="No error data available";
}this._hideLoadingPanel();
var d=new b.XmlHttpPanelErrorEventArgs(e);
this.raiseEvent("responseError",d);
if(!d.get_cancelErrorAlert()){alert("XmlHttpPanel loading error:\n Exception="+e);
}},_createTouchScrollExtender:function(g){var d=this.get_element();
if(d){var e=this._dropDownTouchScroll;
if(e){if(!g){e.dispose();
this._dropDownTouchScroll=null;
}}else{if(g){var f=$telerik.$(d).css("overflow");
if(f=="scroll"||f=="auto"){this._dropDownTouchScroll=new b.TouchScrollExtender(d);
this._dropDownTouchScroll.initialize();
}}}}},_execWsfServiceCall:function(){var e=Function.createDelegate(this,this._onWsfServiceResponse);
var d=Function.createDelegate(this,this._onWsfServiceError);
a.ajax({type:this.get_wcfRequestMethod(),url:this.get_wcfServicePath()+"/"+this.get_wcfServiceMethod(),data:this.get_value(),contentType:"application/json; charset=utf-8",dataType:"json",processdata:true,success:e,error:d});
},_onWsfServiceResponse:function(d){this.set_html(d);
},_onWsfServiceError:function(d){this._onError(d.statusText);
},_onCallbackResponse:function(e,d){this.set_html(e);
},_onCallbackError:function(e,d){this._onError(e);
},_execCallback:function(){var f=Function.createDelegate(this,this._onCallbackResponse);
var e=Function.createDelegate(this,this._onCallbackError);
var d=this._getCallbackArgument();
return WebForm_DoCallback(this._uniqueId,d,f,"SOME_CONTEXT",e,this.get_async());
},_getWebServiceLoader:function(){if(!this._webServiceLoader){var d=new b.WebServiceSettings({path:this.get_webMethodPath(),method:this.get_webMethodName()});
this._webServiceLoader=new b.WebServiceLoader(d);
this._webServiceLoader.add_loadingError(Function.createDelegate(this,this._onWebServiceError));
this._webServiceLoader.add_loadingSuccess(Function.createDelegate(this,this._onWebServiceResponse));
}return this._webServiceLoader;
},_onWebServiceError:function(e,d){this._onError(d.get_message());
},_onWebServiceResponse:function(f,d){var e=d.get_data();
this.set_html(e);
},add_responseEnd:function(d){this.get_events().addHandler("responseEnding",d);
},remove_responseEnd:function(d){this.get_events().removeHandler("responseEnding",d);
},get_loadingPanelID:function(){return this._loadingPanelID;
},set_loadingPanelID:function(d){if(this._loadingPanelID!=d){this._loadingPanelID=d;
}},get_async:function(){return this._async;
},set_async:function(d){this._async=!!d;
},get_wcfRequestMethod:function(){try{return b.XmlHttpPanelWcfRequestMethod.toString(this._wcfRequestMethod);
}catch(d){return b.XmlHttpPanelWcfRequestMethod.toString(b.XmlHttpPanelWcfRequestMethod.GET);
}},set_wcfRequestMethod:function(d){if(d&&d.toUpperCase){d=b.XmlHttpPanelWcfRequestMethod[d.toUpperCase()]||d;
}this._wcfRequestMethod=d;
}};
a.registerControlProperties(b.RadXmlHttpPanel,{enableClientScriptEvaluation:false,wcfServicePath:null,wcfServiceMethod:null,webMethodName:null,webMethodPath:null});
a.registerControlEvents(b.RadXmlHttpPanel,["responseEnding","responseEnded","responseError"]);
b.RadXmlHttpPanel.registerClass("Telerik.Web.UI.RadXmlHttpPanel",b.RadWebControl);
var c=function(e,d){b[e]=function(){var f=Array.prototype.slice.call(arguments);
b[e].initializeBase(this,f);
};
b[e].registerClass("Telerik.Web.UI."+e,d);
};
b.XmlHttpPanelEventArgs=function(d){b.XmlHttpPanelEventArgs.initializeBase(this);
this._content=d;
};
b.XmlHttpPanelEventArgs.prototype={get_content:function(){return this._content;
},set_content:function(d){this._content=d;
}};
b.XmlHttpPanelEventArgs.registerClass("Telerik.Web.UI.XmlHttpPanelEventArgs",Sys.CancelEventArgs);
c("RadXmlHttpPanelEventArgs",Telerik.Web.UI.XmlHttpPanelEventArgs);
b.XmlHttpPanelErrorEventArgs=function(d){b.XmlHttpPanelErrorEventArgs.initializeBase(this);
this._cancelErrorAlert=false;
this._errorMessage=d;
};
b.XmlHttpPanelErrorEventArgs.prototype={get_errorMessage:function(){return this._errorMessage;
},get_cancelErrorAlert:function(){return this._cancelErrorAlert;
},set_cancelErrorAlert:function(d){this._cancelErrorAlert=d;
}};
b.XmlHttpPanelErrorEventArgs.registerClass("Telerik.Web.UI.XmlHttpPanelErrorEventArgs",Sys.EventArgs);
c("RadXmlHttpPanelErrorEventArgs",Telerik.Web.UI.XmlHttpPanelErrorEventArgs);
})($telerik.$,Telerik.Web.UI);
