Type.registerNamespace("Telerik.Web.UI.Scheduler.Views.Agenda.GroupedByResource");
(function(a,c,d,b,e){e.GroupedByResource.Model=function(h,f,g){e.GroupedByResource.Model.initializeBase(this,[h,g]);
this._groupingResource=f;
this._agendaModels=[];
this._resources=null;
};
e.GroupedByResource.Model.prototype={initialize:function(){var h=this._owner;
this._agendaModels=[];
this._resources=h.get_resources().getResourcesByType(this._groupingResource);
for(var f=0,g=this._resources.get_count();
f<g;
f++){this._agendaModels[f]=new e.Model(h);
this._agendaModels[f]._contentTable=a(h.get_element()).find("div.rsTopWrap table.rsAgendaTable")[f];
this._agendaModels[f].initializeTimeSlots();
}this.updateColGroups();
},_getShowResourceHeaders:function(){return(this._settings.showResourceHeaders!==false);
},_getShowResourceHeadersResolved:function(){return(this._getShowResourceHeaders()&&this._settings.isVertical!==true);
},_addColGroups:function(f){this._addResourceCol(f);
e.GroupedByResource.Model.callBaseMethod(this,"_addColGroups",[f]);
},_addResourceCol:function(f){if(!this._getShowResourceHeadersResolved()){return;
}var i=this._settings,h=i.resourceColumnWidth,g=document.createElement("col");
if(h!==undefined){g.width=h;
}f.appendChild(g);
},_getPrevRowForAppointmentPart:function(g){var f=this._agendaModels,i=g.modelIndex,k=g.slot.get_index(),j;
do{var h=f[i];
do{j=h._timeSlots[k]._domElements;
if(j.length>0){return j[j.length-1];
}}while(k--);
i--;
if(i>=0){k=f[i]._timeSlots.length-1;
}}while(i>=0&&!this._isVertical);
return null;
},_addToSlots:function(f,g){var h=this._getModelForAppointmentPart(f);
h._addToSlots(f,g);
},_getModelForAppointmentPart:function(f){return this._agendaModels[f.modelIndex];
},_getResourceForAppointmentPart:function(f){return this._resources.getResource(f.modelIndex);
},_getRenderer:function(){if(!this._renderer){this._renderer=new d.Rendering.ResourceGroupedAgendaViewRenderer(this);
}return this._renderer;
}};
e.GroupedByResource.Model.registerClass("Telerik.Web.UI.Scheduler.Views.Agenda.GroupedByResource.Model",e.ModelBase);
})($telerik.$,Telerik.Web.UI,Telerik.Web.UI.Scheduler,Telerik.Web.UI.Scheduler.DateTime,Telerik.Web.UI.Scheduler.Views.Agenda);
