Type.registerNamespace("Telerik.Web.UI");
(function(a){a.PivotGridFieldSettings=function(b){a.PivotGridFieldSettings.initializeBase(this,[b]);
this.owner=null;
this._fieldSettingsWindow=null;
this._clientData={};
this._okButton=null;
this._cancelButton=null;
this._okButtonClickDelegate=null;
this._cancelButtonClickDelegate=null;
this._currentField=null;
this._functionsBox=null;
};
a.PivotGridFieldSettings.prototype={initialize:function(){a.PivotGridFieldSettings.callBaseMethod(this,"initialize");
this._okButtonClickDelegate=$telerik.addMobileHandler(this,this.get_okButton(),"click",this._onOKButtonClick);
this._cancelButtonClickDelegate=$telerik.addMobileHandler(this,this.get_cancelButton(),"click",this._onCacnelButtonClick);
},dispose:function(){a.PivotGridFieldSettings.callBaseMethod(this,"dispose");
if(this._okButtonClickDelegate!=null){$telerik.removeMobileHandler(this.get_okButton(),"click",this._okButtonClickDelegate,null,true);
this._okButtonClickDelegate=null;
}if(this._cancelButtonClickDelegate!=null){$telerik.removeMobileHandler(this.get_cancelButton(),"click",this._cancelButtonClickDelegate,null,true);
this._cancelButtonClickDelegate=null;
}},displayFieldSettingsWindow:function(b){if(b._isConfigurationPanelField){this._currentField=this.owner._getField(b.get_uniqueName());
}else{this._currentField=b;
}var c=this.get_functionsBox().findItemByValue(this._currentField.get_aggregate());
if(c!=undefined){c.select();
}this.get_fieldSettingsWindow().set_title(this._clientData.Title+" ("+this._currentField.get_uniqueName()+")");
this.get_fieldSettingsWindow().show();
},_onOKButtonClick:function(b){this.get_owner().fireCommand("AggregateFunctionChanged",this._currentField.get_uniqueName()+";"+this.get_functionsBox().get_selectedItem().get_value());
},_onCacnelButtonClick:function(b){this.get_fieldSettingsWindow().close();
},get_functionsBox:function(){if(this._functionsBox==null){this._functionsBox=$find(String.format("{0}_C_{1}",this.get_fieldSettingsWindow().get_id(),"FunctionsBox"));
}return this._functionsBox;
},get_fieldSettingsWindow:function(){if(this._fieldSettingsWindow==undefined){this._fieldSettingsWindow=$find(String.format("{0}_{1}",this.get_owner().get_id(),"FieldSettingsWindow"));
}return this._fieldSettingsWindow;
},get_okButton:function(){if(this._okButton==undefined){this._okButton=$get(String.format("{0}_C_{1}",this.get_fieldSettingsWindow().get_id(),"UpdateFieldButton"));
}return this._okButton;
},get_cancelButton:function(){if(this._cancelButton==null){this._cancelButton=$get(String.format("{0}_C_{1}",this.get_fieldSettingsWindow().get_id(),"CancelButton"));
}return this._cancelButton;
},get_owner:function(){return this.owner;
},set_owner:function(b){this.owner=b;
}};
a.PivotGridFieldSettings.registerClass("Telerik.Web.UI.PivotGridFieldSettings",Sys.UI.Control);
})(Telerik.Web.UI);
