Type.registerNamespace("Telerik.Web.UI");
$telerik.toToolTip=function(a){return a;
};
$telerik.findToolTip=$find;
Telerik.Web.UI.RadToolTipControllerClass=function(){this._tooltipToShow=null;
this._activeToolTip=null;
this._registerGlobalBodyEventHandlers();
};
Telerik.Web.UI.RadToolTipControllerClass.prototype={_registerGlobalBodyEventHandlers:function(){var a=Function.createDelegate(this,function(c){if(c.keyCode==27){if(this._activeToolTip&&!this._activeToolTip.isModal()){this._hideCurrentToolTipNoAnimation();
}}});
var b=Function.createDelegate(this,function(c){this._hideOnBodyClick(c);
});
Sys.Application.add_init(function(){$addHandler(document.body,"keydown",a);
$addHandler(document.body,"click",b);
});
Sys.Application.add_unload(function(){$removeHandler(document.body,"keydown",a);
$removeHandler(document.body,"click",b);
});
},_hideOnBodyClick:function(c){var a=false;
if(this._activeToolTip!=null&&!this._activeToolTip.isModal()){var b=this._activeToolTip;
if($telerik.isMouseOverElementEx(b._tableElement,c)){return;
}a=this._activeToolTip._hideIfNotManualCloseOrFromCode();
}if(a){this._activeToolTip=null;
}},_cancelLastShowRequest:function(){if(this._tooltipToShow){var a=this._tooltipToShow;
this._tooltipToShow=null;
a.cancelShowDelay();
}},_hideCurrentToolTipNoAnimation:function(){this._cancelLastShowRequest();
if(this._activeToolTip!=null){this._activeToolTip._hideNoAnimation();
}this._activeToolTip=null;
},requestShow:function(b){this._cancelLastShowRequest();
var a=this._activeToolTip;
if(a==b){return;
}else{if(a){a._hideIfNotManualCloseOrFromCode();
}}this._tooltipToShow=b;
},cancelSpecificShowRequest:function(a){if(this._tooltipToShow==a){this._cancelLastShowRequest();
}},showTooltip:function(a){if(!a||a.isVisible()){return;
}this._cancelLastShowRequest();
this.set_activeToolTip(a);
a.show();
},notifyToolTipClosed:function(a){if(this._activeToolTip==a){this._activeToolTip=null;
}},set_activeToolTip:function(b){var a=this._activeToolTip;
if(a&&b!=a){this._hideCurrentToolTipNoAnimation();
}this._activeToolTip=b;
},get_activeToolTip:function(){return this._activeToolTip;
},getInstance:function(){return this;
}};
Telerik.Web.UI.RadToolTipControllerClass.registerClass("Telerik.Web.UI.RadToolTipControllerClass",null);
if(!Telerik.Web.UI.RadToolTipController){Telerik.Web.UI.RadToolTipController=new Telerik.Web.UI.RadToolTipControllerClass();
}Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadToolTip=function(a){Telerik.Web.UI.RadToolTip.initializeBase(this,[a]);
this._offsetX=0;
this._offsetY=6;
this._position=Telerik.Web.UI.ToolTipPosition.BottomCenter;
this._horizontalPosition=null;
this._verticalPosition=null;
this._targetControlID=null;
this._serverTargetControlID=null;
this._serverValue="";
this._formID=null;
this._targetControl=null;
this._popupElement=null;
this._tableElement=null;
this._contentCell=null;
this._titleElement=null;
this._contentElement=null;
this._calloutElement=null;
this._closeLink=null;
this._manualCloseButton=null;
this._popupBehavior=null;
this._modal=false;
this._overlay=false;
this._onModalShowHandler=null;
this._onModalCloseHandler=null;
this._skin="Default";
this._title="";
this._text="";
this._manualCloseButtonText="";
this._width="";
this._height="";
this._relativeTo=Telerik.Web.UI.ToolTipRelativeDisplay.Mouse;
this._contentScrolling=Telerik.Web.UI.ToolTipScrolling.Default;
this._showEvent=Telerik.Web.UI.ToolTipShowEvent.OnMouseOver;
this._hideEvent=Telerik.Web.UI.ToolTipHideEvent.Default;
this._visibleOnPageLoad=false;
this._mouseTrailing=false;
this._showCallout=true;
this._renderInPageRoot=false;
this._showDelayRef=null;
this._autoCloseRef=null;
this._showDelay=400;
this._autoCloseDelay=3000;
this._hideDelay=300;
this._animation=Telerik.Web.UI.ToolTipAnimation.None;
this._animationDuration=500;
this._zIndex=8000;
this._cssClass=null;
};
Telerik.Web.UI.RadToolTip.getCurrent=function(){var a=Telerik.Web.UI.RadToolTipController.getInstance();
if(!a){return null;
}return a.get_activeToolTip();
};
Telerik.Web.UI.RadToolTip.prototype={get_zIndex:function(){return this._zIndex;
},set_zIndex:function(b){var a=parseInt(b);
if(isNaN(b)){return;
}if(this._zIndex!=b){this._zIndex=b;
}},initialize:function(){Telerik.Web.UI.RadToolTip.callBaseMethod(this,"initialize");
this.set_position(this._position);
this._getToolTipAltText(this._targetControl);
var a=$telerik.getCurrentStyle(this.get_element(),"zIndex");
if(null!=a){this.set_zIndex(a);
}if(this._visibleOnPageLoad){setTimeout(Function.createDelegate(this,function(){this.show();
}),0);
}},dispose:function(){this._getToolTipController().set_activeToolTip(null);
if(this._showRef){window.clearTimeout(this._showRef);
this._showRef=null;
}if(this._popupBehavior){this._popupBehavior.dispose();
this._popupBehavior=null;
}this._registerPopupHandlers(false);
this._registerMouseHandlers(this._targetControl,false);
this._makeModal(false);
if(this._closeLinkHandler&&this._closeLink){$clearHandlers(this._closeLink);
this._closeLinkHandler=null;
}if(this._popupElement){var a=this.get_id();
if(a){var b=$get(a);
if(b){b.appendChild(this._popupElement);
}}}Telerik.Web.UI.RadToolTip.callBaseMethod(this,"dispose");
},isCreated:function(){return this._popupElement!=null;
},get_leaveTargetAndToolTip:function(){return this.isHideEventEnabled(Telerik.Web.UI.ToolTipHideEvent.LeaveTargetAndToolTip);
},isHideEventEnabled:function(a){return a&this._hideEvent;
},hide:function(){this._hideUnconditionally();
},_hideIfNotManualCloseOrFromCode:function(){var b=this.isHideEventEnabled(Telerik.Web.UI.ToolTipHideEvent.FromCode);
var a=this.get_manualClose();
if(a||b){return false;
}this._hideUnconditionally();
return true;
},_hideUnconditionally:function(){if(!this.isVisible()){return;
}this._hide();
},_hideNoAnimation:function(){this._hide(false);
},_hide:function(c){if(this._animation!=Telerik.Web.UI.ToolTipAnimation.None){$telerik.$(this._popupElement).stop();
}this.cancelHideDelay();
this.cancelShowDelay();
this.cancelAutoCloseDelay();
var a=this._popupElement;
if(!a){return;
}var e=new Sys.CancelEventArgs();
this.raiseEvent("beforeHide",e);
if(e.get_cancel()){return;
}if(this._animation!=Telerik.Web.UI.ToolTipAnimation.None&&c!=false){var b=this._calloutElement;
if(b){b.style.visibility="hidden";
}var d=Function.createDelegate(this,this._afterHide);
$telerik.$(a).fadeOut(this._animationDuration,d);
}else{this._afterHide();
}},_afterHide:function(){try{if(this._popupBehavior){this._popupBehavior.hide();
this._popupBehavior.pin(false);
}}catch(a){}this._getToolTipController().notifyToolTipClosed(this);
this.raiseEvent("hide");
this._registerPopupHandlers(false);
},clone:function(a){var b=document.createElement("span");
if(a){b.setAttribute("id",a);
}return $telerik.cloneControl(this,Telerik.Web.UI.RadToolTip,b);
},show:function(){if(!this.get_element()){return;
}this._createUI();
var a=new Sys.CancelEventArgs();
this.raiseEvent("beforeShow",a);
if(a.get_cancel()){return;
}this._popupBehavior.pin(false);
this._showRef=window.setTimeout(Function.createDelegate(this,function(){this._getToolTipController().set_activeToolTip(this);
if(this._animation==Telerik.Web.UI.ToolTipAnimation.None){this._show();
this._afterShow();
}else{window.setTimeout(Function.createDelegate(this,function(){this._playAnimation();
}),100);
}}),0);
},updateLocation:function(){this._show();
},showLoadingMessage:function(a){var b=this._getFullSkinName();
var c="rtLoading";
if(a){Sys.UI.DomElement.addCssClass(this._contentCell,b);
Sys.UI.DomElement.addCssClass(this._contentCell,c);
}else{Sys.UI.DomElement.removeCssClass(this._contentCell,b);
Sys.UI.DomElement.removeCssClass(this._contentCell,c);
}},_getToolTipAltText:function(a){var d=a?a:this.get_targetControl();
if(d){var e=d.getAttribute("title");
var b=d.getAttribute("alt");
if(e||b){d.removeAttribute("alt");
d.removeAttribute("title");
if(!this.get_text()){var c=e?e:b;
this.set_text(c);
}}}},isModal:function(){return this._modal;
},set_contentElement:function(a){this._contentCell.innerHTML="";
if(a.parentNode&&a.parentNode.removeChild){a.parentNode.removeChild(a);
}this._contentCell.appendChild(a);
a.style.display="";
this._contentElement=a;
this._setOverflow();
this.showLoadingMessage(false);
},get_contentElement:function(){return this._contentElement;
},set_content:function(b){this._text=b;
if(this.isCreated()){var a=document.createElement("div");
a.innerHTML=b;
this.set_contentElement(a);
}},get_content:function(){return this._contentElement?this._contentElement.innerHTML:"";
},cancelHideDelay:function(){if(this._hideDelayRef){window.clearTimeout(this._hideDelayRef);
this._hideDelayRef=0;
}},cancelAutoCloseDelay:function(){if(this._autoCloseRef){window.clearTimeout(this._autoCloseRef);
this._autoCloseRef=0;
}},cancelShowDelay:function(){if(this._showDelayRef){window.clearTimeout(this._showDelayRef);
this._showDelayRef=null;
}this._getToolTipController().cancelSpecificShowRequest(this);
},_getToolTipController:function(){return Telerik.Web.UI.RadToolTipController.getInstance();
},_resetAutoCloseDelay:function(){this.cancelAutoCloseDelay();
if(this.get_manualClose()||this.get_sticky()){return;
}if(this._autoCloseDelay){this._autoCloseRef=window.setTimeout(Function.createDelegate(this,function(){this._hideIfNotManualCloseOrFromCode();
}),this._autoCloseDelay);
}},_resetShowDelay:function(){this.cancelShowDelay();
var a=Function.createDelegate(this,function(){this._getToolTipController().showTooltip(this);
this.cancelShowDelay();
});
this._showDelayRef=window.setTimeout(a,this._showDelay);
},_resetHideDelay:function(){this.cancelHideDelay();
if(this._hideDelay>0){this._hideDelayRef=window.setTimeout(Function.createDelegate(this,function(){this._hideIfNotManualCloseOrFromCode();
}),this._hideDelay);
}else{this._hideIfNotManualCloseOrFromCode();
}},_show:function(){var d=null;
try{d=this.getToolTipBounds();
}catch(c){var a=this;
window.setTimeout(function(){a._addToolTipToDocument();
},10);
return;
}this._setPopupVisible(d.x,d.y);
var b=this.get_contentElement();
if(b){$telerik.repaintChildren(b);
}},_afterShow:function(){this._registerPopupHandlers(true);
this._popupBehavior.pin(this._isRelativeToBrowserWindow());
this._resetAutoCloseDelay();
if(this._animation==Telerik.Web.UI.ToolTipAnimation.None){this._adjustCallout();
}this.raiseEvent("show");
},_isRelativeToBrowserWindow:function(){if(!this._targetControl||this._relativeTo==Telerik.Web.UI.ToolTipRelativeDisplay.BrowserWindow){return true;
}return false;
},_playAnimation:function(){if(this!=Telerik.Web.UI.RadToolTip.getCurrent()){return;
}var f=Function.createDelegate(this,function(){var l=this.getToolTipBounds();
this._setPopupVisible(l.x,l.y);
this._adjustCallout();
var m=$telerik.getBounds(this._tableElement);
$telerik.$(this._popupElement).hide();
return m;
});
var a=f();
var j=Function.createDelegate(this,function(){if(this._isRelativeToBrowserWindow()){this._documentOverflowX=document.documentElement.style.overflowX;
document.documentElement.style.overflowX="hidden";
}if(this.get_showCallout()&&this._calloutElement){this._calloutElement.style.visibility="hidden";
}});
var h=Function.createDelegate(this,function(){this._popupElement.style.filter="";
this.get_popupElement().style.opacity="";
if(this.get_showCallout()&&this._calloutElement){this._calloutElement.style.visibility="";
}this._show();
if(null!=this._documentOverflowX){document.documentElement.style.overflowX=this._documentOverflowX;
this._documentOverflowX=null;
}this._afterShow();
});
var b=this._popupElement;
var g=this._animation;
var c=""+this._position;
var i=this._isRelativeToBrowserWindow();
if(i&&this._verticalPosition!=2){vp=(this._verticalPosition==1?3:1);
c=parseInt(vp+""+this._horizontalPosition);
}var k=i?document.documentElement:this._targetControl;
var d=k?$telerik.getBounds(k):new Sys.UI.Bounds(1,1,1,1);
var e=this._animationDuration;
window.setTimeout(function(){Telerik.Web.UI.Animations.playJQueryAnimation(b,g,d,a,c,j,h,e);
},0);
},_makeModal:function(a){if(this._onModalShowHandler){this.remove_show(this._onModalShowHandler);
this._onModalShowHandler=null;
}if(this._onModalCloseHandler){this.remove_hide(this._onModalCloseHandler);
this._onModalCloseHandler=null;
}if(this._modalExtender){this._modalExtender.dispose();
this._modalExtender=null;
}if(!a){return;
}this._onModalShowHandler=function(b){if(!b._modalExtender){b._modalExtender=new Telerik.Web.UI.ModalExtender(b._popupElement);
}b._modalExtender.show();
};
this.add_show(this._onModalShowHandler);
this._onModalCloseHandler=function(b){if(b._modalExtender){b._modalExtender.hide();
}};
this.add_hide(this._onModalCloseHandler);
},_onMouseOver:function(a){this._logMousePosition(a);
this._resetShowDelay();
this.cancelHideDelay();
this.cancelAutoCloseDelay();
this._getToolTipController().requestShow(this);
},_onMouseMove:function(a){this._logMousePosition(a);
this._resetAutoCloseDelay();
if(this._mouseTrailing&&this.isVisible()){this._show();
}},_onMouseOut:function(b){if(!this.isVisible()){this.cancelShowDelay();
return;
}var a=$telerik.isMouseOverElementEx(this._targetControl,b);
if(!a){this.cancelShowDelay();
if(!this.get_sticky()){this._resetHideDelay();
}}},_onClick:function(a){this._onMouseOver(a);
return $telerik.cancelRawEvent(a);
},_onRightClick:function(a){this._onMouseOver(a);
return $telerik.cancelRawEvent(a);
},_registerMouseHandlers:function(f,d){if(true==d){var b={};
var c=Telerik.Web.UI.ToolTipShowEvent;
if(this._showEvent==c.OnMouseOver){this._onMouseOverDelegate=Function.createDelegate(this,this._onMouseOver);
this._onMouseMoveDelegate=Function.createDelegate(this,this._onMouseMove);
this._onMouseOutDelegate=Function.createDelegate(this,this._onMouseOut);
$telerik.addExternalHandler(f,"mouseover",this._onMouseOverDelegate);
$telerik.addExternalHandler(f,"mousemove",this._onMouseMoveDelegate);
$telerik.addExternalHandler(f,"mouseout",this._onMouseOutDelegate);
}if(this._showEvent==c.OnClick){this._onClickDelegate=Function.createDelegate(this,this._onClick);
$telerik.addExternalHandler(f,"click",this._onClickDelegate);
}if(this._showEvent==c.OnRightClick){this._onRightClickDelegate=Function.createDelegate(this,this._onRightClick);
$telerik.addExternalHandler(f,"contextmenu",this._onRightClickDelegate);
}if(this._showEvent==c.OnFocus){this._onFocusDelegate=Function.createDelegate(this,this._onMouseOver);
this._onBlurDelegate=Function.createDelegate(this,this._onMouseOut);
$telerik.addExternalHandler(f,"focus",this._onFocusDelegate);
$telerik.addExternalHandler(f,"blur",this._onBlurDelegate);
}}else{if(f){var g=[["mouseover",this._onMouseOverDelegate],["mousemove",this._onMouseMoveDelegate],["mouseout",this._onMouseOutDelegate],["click",this._onClickDelegate],["contextmenu",this._onRightClickDelegate],["focus",this._onFocusDelegate],["blur",this._onBlurDelegate]];
for(var a=0;
a<g.length;
a++){var j=g[a];
try{if(null!=j[1]){$telerik.removeExternalHandler(f,j[0],j[1]);
}}catch(h){}}this._onMouseOverDelegate=null;
this._onMouseMoveDelegate=null;
this._onMouseOutDelegate=null;
this._onClickDelegate=null;
this._onRightClickDelegate=null;
this._onFocusDelegate=null;
this._onBlurDelegate=null;
}}},_registerPopupHandlers:function(a){if(true==a){if(this.get_sticky()){this._popupStickyHandler=Function.createDelegate(this,this._onPopupStickyMouseOut);
$addHandler(this._tableElement,"mouseout",this._popupStickyHandler);
}else{if(this.get_leaveTargetAndToolTip()){this._popupEnterHandler=Function.createDelegate(this,this._onPopupEnterToolTip);
$addHandler(this._tableElement,"mouseover",this._popupEnterHandler);
this._popupLeaveHandler=Function.createDelegate(this,this._onPopupLeaveToolTip);
$addHandler(this._tableElement,"mouseout",this._popupLeaveHandler);
}}}else{if(this._popupStickyHandler||this._popupEnterHandler||this._popupLeaveHandler){$clearHandlers(this._tableElement);
this._popupStickyHandler=null;
this._popupEnterHandler=null;
this._popupLeaveHandler=null;
}}},_onPopupStickyMouseOut:function(b){var a=$telerik.isMouseOverElementEx(this._tableElement,b);
if(!a){this._hideIfNotManualCloseOrFromCode();
}},_onPopupEnterToolTip:function(b){var a=$telerik.isMouseOverElementEx(this._tableElement,b);
if(a){this.cancelHideDelay();
this.cancelAutoCloseDelay();
}},_onPopupLeaveToolTip:function(b){var a=$telerik.isMouseOverElementEx(this._tableElement,b);
if(!a){this._resetHideDelay();
this._resetAutoCloseDelay();
}},_getPosRelativeToMouse:function(i){var f=i.x;
var e=i.y;
var c=this._getMousePosition();
var b=c.clientX;
var d=c.clientY;
var a=$telerik.standardsMode;
if(!$telerik.isIE&&document.compatMode!="CSS1Compat"){a=false;
}else{if($telerik.isSafari){a=false;
}}if(a){f-=$telerik.getCorrectScrollLeft(document.documentElement);
e-=document.documentElement.scrollTop;
}else{f-=$telerik.getCorrectScrollLeft(document.body);
e-=document.body.scrollTop;
}var g=b-f;
var h=d-e;
return{x:g,y:h};
},_logMousePosition:function(a){if(!a){return;
}this._mouseX=a.clientX;
this._mouseY=a.clientY;
},_getMousePosition:function(){var a={};
a.clientX=this._mouseX;
a.clientY=this._mouseY;
return a;
},_getCalloutBounds:function(){var b={width:0,height:0,marginLeft:0,marginTop:0};
if(this._showCallout&&this._calloutElement){b.marginLeft=parseInt($telerik.getCurrentStyle(this._calloutElement,"marginLeft"));
b.marginTop=parseInt($telerik.getCurrentStyle(this._calloutElement,"marginTop"));
if(isNaN(b.marginLeft)){b.marginLeft=0;
}if(isNaN(b.marginTop)){b.marginTop=0;
}var a=$telerik.getBounds(this._calloutElement);
if(a){if(a.width){b.width=a.width;
}if(a.height){b.height=a.height;
}}}return b;
},_getBoundsRelativeToBrowser:function(c,g,h){var a=this._horizontalPosition;
var e=this._verticalPosition;
var b=0;
var d=0;
if(!h){h=$telerik.getClientBounds();
}var f=$telerik.getScrollOffset(document.compatMode&&document.compatMode!="BackCompat"?document.documentElement:document.body);
if("fixed"!=this._popupElement.style.position){b+=f.x;
d+=f.y;
}switch(a){case 2:b+=-parseInt(c.width/2-h.width/2);
b+=this._offsetX;
break;
case 3:b+=h.width;
b-=c.width;
b-=this._offsetX;
break;
case 1:default:b+=-c.width;
b+=(-g.width-g.marginLeft);
b+=this._offsetX;
break;
}switch(e){case 2:d+=-parseInt((c.height-h.height)/2);
break;
case 1:d+=this._offsetY;
break;
case 3:default:d+=h.height;
d-=this._offsetY;
d-=c.height;
break;
}return new Sys.UI.Bounds(b,d,c.width,c.height);
},_getBoundsRelativeToElement:function(c,f,g){var a=this._horizontalPosition;
var e=this._verticalPosition;
var b=0;
var d=0;
if(!g){g=$telerik.getBounds(this._targetControl);
}switch(a){case 2:b+=-parseInt(c.width/2-g.width/2);
b+=this._offsetX;
break;
case 3:b+=g.width;
b-=f.marginLeft;
b+=this._offsetX;
break;
case 1:default:b+=-c.width;
b+=(-f.width-f.marginLeft);
b-=this._offsetX;
break;
}switch(e){case 2:d+=-parseInt(c.height/2-g.height/2);
d+=this._offsetY;
break;
case 1:d-=c.height;
d-=f.height+f.marginTop;
d-=this._offsetY;
break;
case 3:default:d+=g.height;
d-=f.marginTop;
d+=this._offsetY;
break;
}return new Sys.UI.Bounds(b,d,c.width,c.height);
},_getBoundsRelativeToMouse:function(b,d,f){var f=this._targetControl?$telerik.getBounds(this._targetControl):$telerik.getClientBounds();
var c=this._getPosRelativeToMouse(f);
if(isNaN(c.x)){c.x=0;
c.y=0;
}else{f.width=0;
f.height=0;
}var e=this._getBoundsRelativeToElement(b,d,f);
var a=new Sys.UI.Bounds(c.x+e.x,c.y+e.y,b.width,b.height);
return a;
},getToolTipBounds:function(){var d=this._popupElement;
var h=(d.style.display=="none")?true:false;
if(h){d.style.visibility="hidden";
}d.style.display="";
this._setOverflow();
if(this._firstShow!=true){this._fixIeHeight(this._tableElement,this._height);
this._firstShow=true;
}var e=this._isRelativeToBrowserWindow()?document.documentElement:this._targetControl;
this._popupBehavior.set_parentElement(e);
var a=$telerik.getBounds(this._tableElement);
var f=this._getCalloutBounds();
if(h){this._popupElement.style.display="none";
d.style.visibility="";
}var g=Telerik.Web.UI.ToolTipRelativeDisplay;
var c=Telerik.Web.UI.ToolTipShowEvent;
var b=null;
if(this._relativeTo==g.BrowserWindow){b=this._getBoundsRelativeToBrowser(a,f);
}else{if(!this._targetControl&&this._showEvent==c.FromCode){b=this._getBoundsRelativeToBrowser(a,f);
}else{if(this._targetControl&&this._showEvent==c.FromCode){b=this._getBoundsRelativeToElement(a,f);
}else{if((this._mouseTrailing||this._relativeTo==g.Mouse)){b=this._getBoundsRelativeToMouse(a,f);
}else{if(this._relativeTo==g.Element){b=this._getBoundsRelativeToElement(a,f);
}}}}}return b;
},_fixIeHeight:function(b,a){if("CSS1Compat"==document.compatMode){var c=(b.offsetHeight-parseInt(a));
if(c>0){var d=(parseInt(b.style.height)-c);
if(d>0){b.style.height=d+"px";
}}}},_refreshTitle:function(){if(null==this._titleElement){return;
}this._titleElement.innerHTML=this._title;
this._titleElement.style.display=(this._title)?"":"none";
},getManualCloseButton:function(){return this._manualCloseButton;
},_createManualCloseButton:function(a){if(this.get_manualClose()){var c=document.createElement("a");
c.href="javascript: void(0);";
c.className="rtCloseButton";
this._closeLinkHandler=Function.createDelegate(this,function(d){this._hideUnconditionally();
return $telerik.cancelRawEvent(d);
});
$addHandler(c,"click",this._closeLinkHandler);
this._closeLink=c;
var b=document.createElement("span");
b.innerHTML=this._manualCloseButtonText;
c.title=this._manualCloseButtonText;
this._manualCloseButton=c;
c.appendChild(b);
a.appendChild(c);
}},_createUI:function(){if(!this._popupElement){var o=this.get_id();
var s="RadToolTipWrapper_"+o;
var k=document.createElement("div");
k.id=s;
var f=this.get_element();
var e=f.parentNode?f:this._getDefaultParent();
var u=$telerik.isRightToLeft(e);
k.className=this._getFullSkinName()+(this.get_showCallout()?" rtVisibleCallout":"")+(u?" RadToolTip_rtl":"")+(this._cssClass?" "+this._cssClass:" ");
k.setAttribute("unselectable","on");
this._popupElement=k;
var v=document.createElement("div");
v.className="rtCallout "+this._getCalloutPosition(this._position);
v.innerHTML="&nbsp;";
this._calloutElement=v;
var t=document.createElement("table");
t.className="rtWrapper";
t.style.width=this._width;
t.style.height=this._height;
this._tableElement=t;
var b=[];
if(u){b=["rtWrapperTopRight","rtWrapperTopCenter","rtWrapperTopLeft","rtWrapperRightMiddle","rtWrapperContent","rtWrapperLeftMiddle","rtWrapperBottomRight","rtWrapperBottomCenter","rtWrapperBottomLeft"];
}else{b=["rtWrapperTopLeft","rtWrapperTopCenter","rtWrapperTopRight","rtWrapperLeftMiddle","rtWrapperContent","rtWrapperRightMiddle","rtWrapperBottomLeft","rtWrapperBottomCenter","rtWrapperBottomRight"];
}var p=0;
for(var m=1;
m<=3;
m++){var a=t.insertRow(-1);
for(var n=1;
n<=3;
n++){var h=a.insertCell(-1);
h.innerHTML="&nbsp;";
h.className=b[p];
p++;
}}var l=t.rows[0].cells[1];
l.innerHTML="";
if(u){this._createManualCloseButton(l);
}var q=document.createElement("div");
q.className="rtTitlebar";
q.style.display="none";
this._titleElement=q;
this._refreshTitle();
l.appendChild(q);
if(!u){this._createManualCloseButton(l);
}var d=t.rows[1].cells[1];
d.vAlign="top";
d.innerHTML="";
this._contentCell=d;
var g=null;
var g=null;
if(this._text){this.set_content(this._text);
}else{var r=this.get_id();
if(r){g=$get(r);
}if(g&&g.innerHTML){var c=this._transferNodeChildren(g);
this.set_contentElement(c);
}}k.appendChild(v);
k.appendChild(t);
this._popupElement.style.display="none";
this._popupElement.style.position="absolute";
this._addToolTipToDocument(g);
}if(!this._popupBehavior){this._popupBehavior=$create(Telerik.Web.PopupBehavior,{id:(new Date()-100)+"PopupBehavior",parentElement:this._targetControl,overlay:this._overlay},null,null,this._popupElement);
}},_transferNodeChildren:function(d){if(!d){return null;
}var a=d.ownerDocument.createElement(d.tagName);
var c=0;
while(d.childNodes&&d.childNodes.length>c){var b=d.childNodes[c];
if(this._clientStateFieldID&&b.id==this._clientStateFieldID){c=1;
continue;
}d.removeChild(b);
a.appendChild(b);
}return a;
},_getDefaultParent:function(){var a=this._formID?document.getElementById(this._formID):null;
if(!a){if(document.forms&&document.forms.length>0){a=document.forms[0];
}else{a=document.body;
}}return a;
},_addToolTipToDocument:function(a){if(null!=a&&!this.get_renderInPageRoot()){a.parentNode.insertBefore(this._popupElement,a);
return;
}var b=this._getDefaultParent();
b.appendChild(this._popupElement);
},_getParentByTagName:function(c,b){var a=c;
b=b.toUpperCase();
while(a.tagName.toUpperCase()!=b){a=a.parentNode;
if(!a){break;
}}return a;
},_getFullSkinName:function(){return"RadToolTip RadToolTip_"+this._skin;
},_getUniqueString:function(){return""+(new Date()-100);
},_getCalloutPosition:function(oPos){with(Telerik.Web.UI.ToolTipPosition){switch(oPos){case TopLeft:return"rtCalloutBottomRight";
case TopCenter:return"rtCalloutBottomCenter";
case TopRight:return"rtCalloutBottomLeft";
case MiddleLeft:return"rtCalloutMiddleRight";
case Center:return"rtCalloutCenter";
case MiddleRight:return"rtCalloutMiddleLeft";
case BottomLeft:return"rtCalloutTopRight";
case BottomCenter:return"rtCalloutTopCenter";
case BottomRight:return"rtCalloutTopLeft";
}}return"";
},_getHorizontalSide:function(a){return parseInt((a+"").charAt(1));
},_getVerticalSide:function(a){return parseInt((a+"").charAt(0));
},_setPopupVisible:function(b,a){this._popupElement.style.zIndex=this._zIndex;
this._popupBehavior.set_x(b);
this._popupBehavior.set_y(a);
this._popupBehavior.show();
if(!this.get_width()){this._popupElement.style.width="";
}},_reSetToolTipPosition:function(){var a=this.getToolTipBounds();
this._setPopupVisible(a.x,a.y);
},_setOverflow:function(){var flow=this._contentScrolling;
if(flow==Telerik.Web.UI.ToolTipScrolling.Default){return;
}var el=this._contentElement;
if(!el||el.parentNode!=this._contentCell||((!el.document||!el.document.documentElement)&&$telerik.isIE)){return;
}var overflow="";
with(Telerik.Web.UI.ToolTipScrolling){switch(flow){case Auto:overflow="auto";
break;
case None:overflow="hidden";
break;
case X:overflow="";
el.style.overflowX="scroll";
el.style.overflowY="hidden";
break;
case Y:overflow="";
el.style.overflowY="scroll";
el.style.overflowX="hidden";
break;
case Both:overflow="scroll";
}}var parent=el.parentNode;
el.style.display="none";
var bounds=$telerik.getBounds(parent);
el.style.width=bounds.width+"px";
el.style.height=bounds.height+"px";
if(!el.style.overflowX&&!el.style.overflowY){el.style.overflow=overflow;
}el.style.display="";
},_getLeftOffset:function(){var a=Telerik.Web.UI.ToolTipPosition;
if(a.Left==this._position){return(-1*this._targetControl.offsetWidth)+this._offsetX;
}else{if(a.Right==this._position){return this._targetControl.offsetWidth+this._offsetX;
}else{return this._offsetX;
}}},_getTopOffset:function(){var a;
var b=Telerik.Web.UI.ToolTipPosition;
if(b.Top==this._position){a=(-1*this._targetControl.offsetHeight)+this._offsetY;
}else{if(b.Bottom==this._position){a=this._targetControl.offsetHeight+this._offsetY;
}else{a=this._offsetY;
}}return a;
},_adjustCallout:function(){if(this._originalPosition){this.set_position(this._originalPosition);
this.updateLocation();
this._originalPosition=null;
}if(this.get_showCallout()&&this.get_position()!=22&&this._relativeTo==Telerik.Web.UI.ToolTipRelativeDisplay.Element){var b=this.get_targetControl();
if(!b){return;
}var h=$telerik.getBounds(b);
var c=this.get_popupElement();
var g=c.getElementsByTagName("DIV")[0];
g.style.left="";
g.style.top="";
var f=$telerik.getBounds(g);
var d=$telerik.getViewPortSize();
var e=Math.min(d.height-h.y,h.height);
var a=Math.min(d.width-h.x,h.width);
g.style.visibility="hidden";
this._fixToolTipPosition(h,f,a,e,true);
f=$telerik.getBounds(g);
this._fixToolTipPosition(h,f,a,e,false);
g.style.visibility="visible";
this._fixCalloutPosition(h,a,e);
}},_fixCalloutPosition:function(j,a,h){var b=this.get_popupElement();
var i=b.getElementsByTagName("DIV")[0];
i.style.left="";
i.style.top="";
var f=$telerik.getBounds(i);
var g=$telerik.getBounds(b);
var e=null;
var d=null;
if(this._verticalPosition==Telerik.Web.UI.ToolTipVerticalPosition.Middle){d=Math.floor(j.y+h/2-g.y+f.width/2);
}else{var c=this._horizontalPosition;
if(c!=Telerik.Web.UI.ToolTipHorizontalPosition.Center){return;
}e=Math.floor(j.x+a/2-g.x+f.width/2);
}if(d){i.style.top=d+"px";
}if(e){i.style.left=e+"px";
}},_fixToolTipPosition:function(i,f,a,g,b){var e=false;
var d=this.get_position();
var h;
var j;
var c;
if(b){h=2;
j=(i.x+a>f.x&&this._horizontalPosition==Telerik.Web.UI.ToolTipHorizontalPosition.Right);
c=(i.x<f.x&&this._horizontalPosition==Telerik.Web.UI.ToolTipHorizontalPosition.Left);
}else{h=20;
j=(i.y+g>f.y&&this._verticalPosition==Telerik.Web.UI.ToolTipVerticalPosition.Bottom);
c=(i.y<f.y&&this._verticalPosition==Telerik.Web.UI.ToolTipVerticalPosition.Top);
}if(j){e=true;
h=(-1)*(h);
}if(c){e=true;
}if(e){d+=h;
this._originalPosition=this.get_position();
this.set_position(d);
this.updateLocation();
}},isVisible:function(){var a=this._popupElement;
return(a&&a.style.display!="none");
},get_targetControlID:function(){return this._targetControlID;
},set_targetControlID:function(b){if(this._targetControlID!=b){this._targetControlID=b;
var a=(this._targetControlID?$get(this._targetControlID):null);
this.set_targetControl(a);
}},get_serverTargetControlID:function(){return this._serverTargetControlID;
},set_serverTargetControlID:function(a){this._serverTargetControlID=a;
},get_serverValue:function(){return this._serverValue;
},set_serverValue:function(a){this._serverValue=a;
},get_value:function(){return this.get_serverValue();
},set_value:function(a){this.set_serverValue(a);
},get_formID:function(){return this._formID;
},set_formID:function(a){if(this._formID!=a){this._formID=a;
}},get_position:function(){return this._position;
},set_position:function(a){if(this._position!=a){this._position=a;
if(this._calloutElement){this._calloutElement.className="rtCallout "+this._getCalloutPosition(this._position);
}}this._horizontalPosition=this._getHorizontalSide(this._position);
this._verticalPosition=this._getVerticalSide(this._position);
},get_offsetX:function(){return this._offsetX;
},set_offsetX:function(a){if(this._offsetX!=a){this._offsetX=a;
}},get_offsetY:function(){return this._offsetY;
},set_offsetY:function(a){if(this._offsetY!=a){this._offsetY=a;
}},get_title:function(){return this._title;
},set_title:function(a){if(this._title!=a){this._title=a;
}this._refreshTitle();
},get_text:function(){return this._text;
},set_text:function(a){if(this._text!=a){this._text=a;
}if(this.isCreated()){this.set_content(this._text);
}},get_width:function(){return this._width;
},set_width:function(a){if(this._width!=a){this._width=a;
}},get_height:function(){return this._height;
},set_height:function(a){if(this._height!=a){this._height=a;
}},get_relativeTo:function(){return this._relativeTo;
},set_relativeTo:function(a){if(this._relativeTo!=a){this._relativeTo=a;
}},get_contentScrolling:function(){return this._contentScrolling;
},set_contentScrolling:function(a){if(this._contentScrolling!=a){this._contentScrolling=a;
}},get_sticky:function(){return this.isHideEventEnabled(Telerik.Web.UI.ToolTipHideEvent.LeaveToolTip);
},set_sticky:function(a){if(a){this.set_hideEvent(Telerik.Web.UI.ToolTipHideEvent.LeaveToolTip);
}},get_manualClose:function(){return this.isHideEventEnabled(Telerik.Web.UI.ToolTipHideEvent.ManualClose);
},set_manualClose:function(a){if(a){this.set_hideEvent(Telerik.Web.UI.ToolTipHideEvent.ManualClose);
}},get_showCallout:function(){return this._showCallout;
},set_showCallout:function(a){if(this._showCallout!=a){this._showCallout=a;
}},get_renderInPageRoot:function(){return this._renderInPageRoot;
},set_renderInPageRoot:function(a){if(this._renderInPageRoot!=a){this._renderInPageRoot=a;
}},get_showDelay:function(){return this._showDelay;
},set_showDelay:function(a){if(this._showDelay!=a){this._showDelay=a;
}},get_autoCloseDelay:function(){return this._autoCloseDelay;
},set_autoCloseDelay:function(a){if(this._autoCloseDelay!=a){this._autoCloseDelay=a;
}},get_hideDelay:function(){return this._hideDelay;
},set_hideDelay:function(a){if(this._hideDelay!=a){this._hideDelay=a;
}},get_mouseTrailing:function(){return this._mouseTrailing;
},set_mouseTrailing:function(a){if(this._mouseTrailing!=a){this._mouseTrailing=a;
if(true==a){this.set_relativeTo(Telerik.Web.UI.ToolTipRelativeDisplay.Mouse);
}}},get_visibleOnPageLoad:function(){return this._visibleOnPageLoad;
},set_visibleOnPageLoad:function(a){if(this._visibleOnPageLoad!=a){this._visibleOnPageLoad=a;
}},get_animation:function(){return this._animation;
},set_animation:function(a){if(this._animation!=a){this._animation=a;
}},get_animationDuration:function(){return this._animationDuration;
},set_animationDuration:function(a){if(this._animationDuration!=a){this._animationDuration=a;
}},get_showEvent:function(){return this._showEvent;
},set_showEvent:function(a){if(this._showEvent!=a){this._showEvent=a;
}},get_hideEvent:function(){return this._hideEvent;
},set_hideEvent:function(a){this._hideEvent=a;
},get_modal:function(){return this._modal;
},set_modal:function(a){if(this._modal!=a){this._modal=a;
}this._makeModal(this._modal);
},get_overlay:function(){return this._overlay;
},set_overlay:function(a){this._overlay=a;
if(this._popupBehavior){this._popupBehavior.set_overlay(this._overlay);
}if(this.isVisible()){this._reSetToolTipPosition();
}},get_skin:function(){return this._skin;
},set_skin:function(a){if(a&&this._skin!=a){this._skin=a;
}},get_targetControl:function(){return this._targetControl;
},set_targetControl:function(b){if(this._targetControl!=b){if(this._targetControl&&(this._targetControl!=b)){this._registerMouseHandlers(this._targetControl,false);
}var a=this._ensureRadControlsCompatTarget(b);
this._targetControl=a;
if(a){this._getToolTipAltText(a);
this._registerMouseHandlers(a,true);
if(this._popupBehavior){this._popupBehavior.set_parentElement(a);
}}}},_ensureRadControlsCompatTarget:function(a){var d=null;
if(a!=null){this._getToolTipAltText(a);
d=a.getAttribute("_rfddecoratedID");
if(d){a=$get(d);
}}var e=d?d:this.get_targetControlID();
var b=$get(e+"_text");
if(b&&e){var c=$find(e);
if(c&&Object.getType(c).inheritsFrom(Telerik.Web.UI.RadInputControl)){a=$get(e+"_text");
}}return a;
},get_popupElement:function(){return this._popupElement;
},add_beforeShow:function(a){this.get_events().addHandler("beforeShow",a);
},remove_beforeShow:function(a){this.get_events().removeHandler("beforeShow",a);
},add_show:function(a){this.get_events().addHandler("show",a);
},remove_show:function(a){this.get_events().removeHandler("show",a);
},add_beforeHide:function(a){this.get_events().addHandler("beforeHide",a);
},remove_beforeHide:function(a){this.get_events().removeHandler("beforeHide",a);
},add_hide:function(a){this.get_events().addHandler("hide",a);
},remove_hide:function(a){this.get_events().removeHandler("hide",a);
}};
Telerik.Web.UI.RadToolTip.registerClass("Telerik.Web.UI.RadToolTip",Telerik.Web.UI.RadWebControl);
Telerik.Web.UI.ToolTipPosition=function(){throw Error.invalidOperation();
};
Telerik.Web.UI.ToolTipPosition.prototype={TopLeft:11,TopCenter:12,TopRight:13,MiddleLeft:21,Center:22,MiddleRight:23,BottomLeft:31,BottomCenter:32,BottomRight:33};
Telerik.Web.UI.ToolTipPosition.registerEnum("Telerik.Web.UI.ToolTipPosition",false);
Telerik.Web.UI.ToolTipHorizontalPosition=function(){throw Error.invalidOperation();
};
Telerik.Web.UI.ToolTipHorizontalPosition.prototype={Left:1,Center:2,Right:3};
Telerik.Web.UI.ToolTipHorizontalPosition.registerEnum("Telerik.Web.UI.ToolTipHorizontalPosition",false);
Telerik.Web.UI.ToolTipVerticalPosition=function(){throw Error.invalidOperation();
};
Telerik.Web.UI.ToolTipVerticalPosition.prototype={Top:1,Middle:2,Bottom:3};
Telerik.Web.UI.ToolTipVerticalPosition.registerEnum("Telerik.Web.UI.ToolTipVerticalPosition",false);
Telerik.Web.UI.ToolTipRelativeDisplay=function(){throw Error.invalidOperation();
};
Telerik.Web.UI.ToolTipRelativeDisplay.prototype={Mouse:0,Element:1,BrowserWindow:2};
Telerik.Web.UI.ToolTipRelativeDisplay.registerEnum("Telerik.Web.UI.ToolTipRelativeDisplay",false);
Telerik.Web.UI.ToolTipScrolling=function(){throw Error.invalidOperation();
};
Telerik.Web.UI.ToolTipScrolling.prototype={Auto:0,None:1,X:2,Y:3,Both:4,Default:5};
Telerik.Web.UI.ToolTipScrolling.registerEnum("Telerik.Web.UI.ToolTipScrolling",false);
Telerik.Web.UI.ToolTipAnimation=function(){throw Error.invalidOperation();
};
Telerik.Web.UI.ToolTipAnimation.prototype={None:0,Resize:1,Fade:2,Slide:4,FlyIn:8};
Telerik.Web.UI.ToolTipAnimation.registerEnum("Telerik.Web.UI.ToolTipAnimation",false);
Telerik.Web.UI.ToolTipShowEvent=function(){throw Error.invalidOperation();
};
Telerik.Web.UI.ToolTipShowEvent.prototype={OnMouseOver:1,OnClick:2,OnRightClick:4,OnFocus:8,FromCode:16};
Telerik.Web.UI.ToolTipShowEvent.registerEnum("Telerik.Web.UI.ToolTipShowEvent",false);
Telerik.Web.UI.ToolTipHideEvent=function(){throw Error.invalidOperation();
};
Telerik.Web.UI.ToolTipHideEvent.prototype={Default:1,LeaveToolTip:2,ManualClose:4,LeaveTargetAndToolTip:8,FromCode:16};
Telerik.Web.UI.ToolTipHideEvent.registerEnum("Telerik.Web.UI.ToolTipHideEvent",false);
