(function(){Type.registerNamespace("Telerik.Web.UI.ToolTip");
Telerik.Web.UI.ToolTip.RendererBase=function(a){this.tooltip=a;
this.isRightToLeft=a.isRightToLeft();
};
Telerik.Web.UI.ToolTip.RendererBase.prototype={createPopupBehavior:function(){this.tooltip._popupBehavior=$create(Telerik.Web.PopupBehavior,{id:(new Date()-100)+"PopupBehavior",parentElement:this.tooltip._targetControl,overlay:this.tooltip._overlay},null,null,this.tooltip._popupElement);
}};
Telerik.Web.UI.ToolTip.RendererBase.registerClass("Telerik.Web.UI.ToolTip.RendererBase");
})();
Type.registerNamespace("Telerik.Web.UI.ToolTip");
(function(){Telerik.Web.UI.ToolTip.IRenderer=function(a){};
Telerik.Web.UI.ToolTip.IRenderer.prototype={createUI:function(){},createRootElement:function(){},createCalloutElement:function(){},createTitleElement:function(){},createContentWrapper:function(){},setContent:function(){}};
Telerik.Web.UI.ToolTip.IRenderer.registerInterface("Telerik.Web.UI.ToolTip.IRenderer");
})();
Type.registerNamespace("Telerik.Web.UI.ToolTip");
(function(){Telerik.Web.UI.ToolTip.BaseView=function(a){this.tooltip=a;
};
Telerik.Web.UI.ToolTip.BaseView.prototype={get_width:function(){this.tooltip._width;
},get_height:function(){this.tooltip._height;
},_addElementShadow:function(a){if(this.tooltip.get_enableShadow()){Sys.UI.DomElement.addCssClass(a,"rtShadow");
}},_removeElementShadow:function(a){if(this.tooltip.get_enableShadow()){Sys.UI.DomElement.removeCssClass(a,"rtShadow");
}},_fixCalloutPosition:function(e,i,h){var d=this.tooltip.get_popupElement();
this.tooltip._calloutElement.style.left="";
this.tooltip._calloutElement.style.top="";
var a=$telerik.getBounds(this.tooltip._calloutElement);
var f=$telerik.getBounds(d);
var c=null;
var g=null;
if(f.width==0&&f.height==0){return;
}if(this.tooltip._verticalPosition==Telerik.Web.UI.ToolTipVerticalPosition.Middle){g=Math.floor(e.y+h/2-f.y+a.width/2);
}else{var b=this.tooltip._horizontalPosition;
if(b!=Telerik.Web.UI.ToolTipHorizontalPosition.Center){return;
}c=Math.floor(e.x+i/2-f.x+a.width/2);
}if(g){this.tooltip._calloutElement.style.top=g+"px";
}if(c){this.tooltip._calloutElement.style.left=c+"px";
}},fixToolTipPositionBase:function(h,c,k,j,e,f){if(c.width==0&&c.height==0){return;
}var i=false;
var g=this.tooltip.get_position();
var d;
var a;
var b;
if(e){d=2;
a=(h.x+k>c.x+f&&this.tooltip._horizontalPosition==Telerik.Web.UI.ToolTipHorizontalPosition.Right);
b=(h.x<c.x-f&&this.tooltip._horizontalPosition==Telerik.Web.UI.ToolTipHorizontalPosition.Left);
}else{d=20;
a=(h.y+j>c.y+f&&this.tooltip._verticalPosition==Telerik.Web.UI.ToolTipVerticalPosition.Bottom);
b=(h.y<c.y-f&&this.tooltip._verticalPosition==Telerik.Web.UI.ToolTipVerticalPosition.Top);
}if(a){i=true;
d=(-1)*(d);
}if(b){i=true;
}if(i){g+=d;
this.tooltip._originalPosition=this.tooltip.get_position();
this.tooltip.set_position(g);
this.tooltip.updateLocation();
}},_setOverflowToElement:function(a,b){var c=Telerik.Web.UI.ToolTipScrolling;
switch(b){case c.X:a.style.overflowX="scroll";
a.style.overflowY="hidden";
break;
case c.Y:a.style.overflowY="scroll";
a.style.overflowX="hidden";
break;
}},_fixMozSetOverflowToElement:function(a,b){if(!a.style.overflowX&&!a.style.overflowY){a.style.overflow=this._getOverflowString(b);
}},_getOverflowString:function(a){var b="",c=Telerik.Web.UI.ToolTipScrolling;
switch(a){case c.Auto:b="auto";
break;
case c.None:b="hidden";
break;
case c.Both:b="scroll";
break;
}return b;
},_createTouchScrollExtender:function(b){var a=b==Telerik.Web.UI.ToolTipScrolling.None?false:true;
if(a&&Telerik.Web.UI.TouchScrollExtender._getNeedsScrollExtender()&&!this.tooltip._dropDownTouchScroll){this.tooltip._createTouchScrollExtender(true);
}},registerPopupHandlers:function(a){if(true==a){if(this.tooltip.get_sticky()){this.tooltip._popupStickyHandler=Function.createDelegate(this,this._onPopupStickyMouseOut);
$addHandler(this.tooltip._popupElement,"mouseout",this.tooltip._popupStickyHandler);
}else{if(this.tooltip.get_leaveTargetAndToolTip()){this.tooltip._popupEnterHandler=Function.createDelegate(this,this._onPopupEnterToolTip);
$addHandler(this.tooltip._popupElement,"mouseover",this.tooltip._popupEnterHandler);
this.tooltip._popupLeaveHandler=Function.createDelegate(this,this._onPopupLeaveToolTip);
$addHandler(this.tooltip._popupElement,"mouseout",this.tooltip._popupLeaveHandler);
}}}else{if(this.tooltip._popupStickyHandler||this.tooltip._popupEnterHandler||this.tooltip._popupLeaveHandler){$clearHandlers(this.tooltip._popupElement);
this.tooltip._popupStickyHandler=null;
this.tooltip._popupEnterHandler=null;
this.tooltip._popupLeaveHandler=null;
}}},_onPopupStickyMouseOut:function(a){var b=this.isMouseOverElement(a);
if(!b){this.tooltip._hideIfNotManualCloseOrFromCode();
}},_onPopupEnterToolTip:function(a){var b=this.isMouseOverElement(a);
if(b){this.tooltip.cancelHideDelay();
this.tooltip.cancelAutoCloseDelay();
}},_onPopupLeaveToolTip:function(a){var b=this.isMouseOverElement(a);
if(!b){this.tooltip._resetHideDelay();
this.tooltip._resetAutoCloseDelay();
}},isMouseOverElement:function(a){return $telerik.isMouseOverElementEx(this.tooltip._popupElement,a);
}};
Telerik.Web.UI.ToolTip.BaseView.registerClass("Telerik.Web.UI.ToolTip.BaseView");
})();
Type.registerNamespace("Telerik.Web.UI.ToolTip");
(function(){Telerik.Web.UI.ToolTip.IView=function(a){};
Telerik.Web.UI.ToolTip.IView.prototype={set_width:function(a){},set_height:function(a){},addShadow:function(){},removeShadow:function(){},get_bounds:function(){},refreshTitle:function(){},showLoadingMessage:function(){},isLoading:function(){}};
Telerik.Web.UI.ToolTip.IView.registerInterface("Telerik.Web.UI.ToolTip.IView");
})();
Type.registerNamespace("Telerik.Web.UI.ToolTip");
(function(){Telerik.Web.UI.ToolTip.ClassicRenderer=function(a){Telerik.Web.UI.ToolTip.ClassicRenderer.initializeBase(this,[a]);
};
Telerik.Web.UI.ToolTip.ClassicRenderer.prototype={createUI:function(){if(!this.tooltip._popupElement){this.createRootElement();
this.createCalloutElement();
this.createTableElement();
this.createTableElementCells();
this.createTitleWrapper();
this.createTitleElement();
this.tooltip._refreshTitle();
this.createManualCloseButton();
this.appendTitleElements();
this.createContentWrapper();
this.setContent();
}if(!this.tooltip._popupBehavior){this.createPopupBehavior();
}},createRootElement:function(){var b=this.tooltip.get_id();
var c="RadToolTipWrapper_"+b;
var a=document.createElement("div");
a.id=c;
a.className=this.tooltip._getFullSkinName()+(this.tooltip.get_showCallout()?" rtVisibleCallout":"")+(this.isRightToLeft?" RadToolTip_rtl":"")+(this.tooltip._cssClass?" "+this.tooltip._cssClass:" ");
if(!$telerik.isIE6){this.tooltip._getUiView()._addElementShadow(a);
}a.setAttribute("unselectable","on");
this.tooltip._popupElement=a;
},createCalloutElement:function(){var a=document.createElement("div");
a.className="rtCallout "+this.tooltip._getCalloutPosition(this.tooltip._position);
a.innerHTML="&nbsp;";
this.tooltip._calloutElement=a;
},createTableElement:function(){var b=document.createElement("table");
b.className="rtWrapper";
var c=parseInt(this.tooltip.get_width(),10);
b.style.width=(!isNaN(c)&&c>0)?c+"px":"";
var a=parseInt(this.tooltip.get_height(),10);
b.style.height=(!isNaN(a)&&a>0)?a+"px":"";
this.tooltip._tableElement=b;
},createTableElementCells:function(){var c=[];
if(this.isRightToLeft){c=["rtWrapperTopRight","rtWrapperTopCenter","rtWrapperTopLeft","rtWrapperRightMiddle","rtWrapperContent","rtWrapperLeftMiddle","rtWrapperBottomRight","rtWrapperBottomCenter","rtWrapperBottomLeft"];
}else{c=["rtWrapperTopLeft","rtWrapperTopCenter","rtWrapperTopRight","rtWrapperLeftMiddle","rtWrapperContent","rtWrapperRightMiddle","rtWrapperBottomLeft","rtWrapperBottomCenter","rtWrapperBottomRight"];
}if(!$telerik.isIE6){this.tooltip._uiView._addElementShadow(this.tooltip._tableElement);
}var e=0;
for(var d=1;
d<=3;
d++){var a=this.tooltip._tableElement.insertRow(-1);
for(var f=1;
f<=3;
f++){var b=a.insertCell(-1);
b.innerHTML="&nbsp;";
b.className=c[e];
e++;
}}},createTitleElement:function(){var a=document.createElement("div");
a.className="rtTitlebar";
a.style.display="none";
this.tooltip._titleBar=a;
},createManualCloseButton:function(){if(!this.tooltip.get_manualClose()){return;
}var a=document.createElement("a");
a.href="javascript: void(0);";
a.className="rtCloseButton";
this.tooltip._closeElementHandler=Function.createDelegate(this,function(c){this.tooltip._hideUnconditionally();
return $telerik.cancelRawEvent(c);
});
$addHandler(a,"click",this.tooltip._closeElementHandler);
this.tooltip._closeElement=a;
var b=document.createElement("span");
b.innerHTML=this.tooltip._manualCloseButtonText;
a.title=this.tooltip._manualCloseButtonText;
this.tooltip._manualCloseButton=a;
a.appendChild(b);
},appendTitleElements:function(){if(!this.tooltip._manualCloseButton){this.tooltip._titleWrapper.appendChild(this.tooltip._titleBar);
return;
}if(this.isRightToLeft){this.tooltip._titleWrapper.appendChild(this.tooltip._manualCloseButton);
this.tooltip._titleWrapper.appendChild(this.tooltip._titleBar);
}else{this.tooltip._titleWrapper.appendChild(this.tooltip._titleBar);
this.tooltip._titleWrapper.appendChild(this.tooltip._manualCloseButton);
}},createTitleWrapper:function(){this.tooltip._titleWrapper=this.tooltip._tableElement.rows[0].cells[1];
this.tooltip._titleWrapper.innerHTML="";
},createContentWrapper:function(){var a=this.tooltip._tableElement.rows[1].cells[1];
a.vAlign="top";
a.innerHTML="";
this.tooltip._contentWrapper=a;
},setContent:function(){var d;
var e=this.tooltip;
if(e._text){e.set_content(e._text);
}else{var f=e.get_id();
if(f){d=$get(f);
}if(d&&d.innerHTML){var a=e._transferNodeChildren(d);
e.set_contentElement(a);
}}var b=e._popupElement;
b.appendChild(e._calloutElement);
b.appendChild(e._tableElement);
var c=b.style;
c.display="none";
c.position="absolute";
d=d||e.get_element();
e._addToolTipToDocument(d);
},_appendManualCloseButton:function(a){this.tooltip._titleWrapper.appendChild(a);
},_removeManualCloseButton:function(a){this.tooltip._titleWrapper.removeChild(a);
}};
Telerik.Web.UI.ToolTip.ClassicRenderer.registerClass("Telerik.Web.UI.ToolTip.ClassicRenderer",Telerik.Web.UI.ToolTip.RendererBase,Telerik.Web.UI.ToolTip.IRenderer);
})();
Type.registerNamespace("Telerik.Web.UI.ToolTip");
(function(){Telerik.Web.UI.ToolTip.ClassicRendererAria=function(a){Telerik.Web.UI.ToolTip.ClassicRendererAria.initializeBase(this,[a]);
};
Telerik.Web.UI.ToolTip.ClassicRendererAria.prototype={createUI:function(){Telerik.Web.UI.ToolTip.ClassicRendererAria.callBaseMethod(this,"createUI");
this._applyAriaSupport();
},_applyAriaSupport:function(){if(!this.tooltip.get_enableAriaSupport()){return;
}this.tooltip.get_element().setAttribute("aria-hidden","true");
this._applyAriaForLayoutTables();
var b=this.tooltip.get_popupElement();
b.setAttribute("aria-hidden","true");
b.setAttribute("aria-labelledby",this.tooltip._titleBar.id);
b.setAttribute("role","tooltip");
var a=this.tooltip.getManualCloseButton();
if(a){a.setAttribute("role","button");
}},_applyAriaForLayoutTables:function(){var c=this.tooltip._tableElement;
if(c){c.setAttribute("role","presentation");
}var g=c.getElementsByTagName("tr");
for(var a=0;
a<g.length;
a++){var f=g[a];
f.setAttribute("role","presentation");
var d=f.getElementsByTagName("td");
for(var b=0;
b<d.length;
b++){d[b].setAttribute("role","presentation");
}}var e=this.tooltip._titleBar;
if(e){e.id=this.tooltip.get_id()+"_title";
e.setAttribute("role","label");
}}};
Telerik.Web.UI.ToolTip.ClassicRendererAria.registerClass("Telerik.Web.UI.ToolTip.ClassicRendererAria",Telerik.Web.UI.ToolTip.ClassicRenderer);
})();
Type.registerNamespace("Telerik.Web.UI.ToolTip");
(function(){Telerik.Web.UI.ToolTip.LightweightRenderer=function(a){Telerik.Web.UI.ToolTip.LightweightRenderer.initializeBase(this,[a]);
};
Telerik.Web.UI.ToolTip.LightweightRenderer.prototype={createUI:function(){if(!this.tooltip._popupElement){this.createRootElement();
this.addRoundedCorners();
this.createTooltipWrapper();
this.setRootElementSize();
this.createManualCloseButton();
this.createCalloutElement();
this.createTitleElement();
this.createContentWrapper();
this.setContent();
}if(!this.tooltip._popupBehavior){this.createPopupBehavior();
}},createRootElement:function(){var b=this.tooltip.get_id();
var c="RadToolTipWrapper_"+b;
var a=document.createElement("div");
a.id=c;
a.className=this.tooltip._getFullSkinName()+(this.tooltip.get_showCallout()?" rtVisibleCallout":"")+(this.isRightToLeft?" rtRtl":"")+(this.tooltip._cssClass?" "+this.tooltip._cssClass:"");
if(!$telerik.isIE6){this.tooltip._getUiView()._addElementShadow(a);
}a.setAttribute("unselectable","on");
this.set_popupElement(a);
},setRootElementSize:function(){var b=parseInt(this.tooltip.get_width(),10);
this.get_popupElement().style.width=(!isNaN(b)&&b>0)?b+"px":"";
var a=parseInt(this.tooltip.get_height(),10);
this.get_popupElement().style.height=(!isNaN(a)&&a>0)?a+"px":"";
},addRoundedCorners:function(){if(this.tooltip.get_enableRoundedCorners()){Sys.UI.DomElement.addCssClass(this.get_popupElement(),"rtRoundedCorner");
}},createCalloutElement:function(){if(this.tooltip.get_position()==Telerik.Web.UI.ToolTipPosition.Center){return;
}if(this.tooltip.get_relativeTo()==Telerik.Web.UI.ToolTipRelativeDisplay.BrowserWindow){return;
}var a=document.createElement("span");
a.className="rtCallout "+this.tooltip._getCalloutPosition(this.tooltip._position);
a.innerHTML="&nbsp;";
this.set_calloutElement(a);
this.get_tooltipWrapper().appendChild(a);
},createTitleElement:function(){if(!this.tooltip._title){return;
}this.createTitleBar();
this.createTitleWrapper();
var a=document.createElement("h6");
a.className="rtTitle";
a.style.display="none";
this.set_titleElement(a);
this.get_titleWrapper().appendChild(a);
this.tooltip.set_title(this.tooltip._title);
},createTitleBar:function(){var a=document.createElement("div");
a.className="rtTitleBar";
this.set_titleBar(a);
this.get_tooltipWrapper().appendChild(a);
},createTitleWrapper:function(){var a=document.createElement("div");
a.className="rtTitleWrapper";
a.id=this.tooltip.get_id()+"_title";
this.set_titleWrapper(a);
this.get_titleBar().appendChild(a);
},createManualCloseButton:function(){if(!this.tooltip.get_manualClose()){return;
}var a=document.createElement("button");
a.className="rtClose";
var b=document.createElement("span");
b.className="rtCloseIcon";
a.appendChild(b);
if(this.tooltip._manualCloseButtonText){a.value=this.tooltip._manualCloseButtonText;
a.title=this.tooltip._manualCloseButtonText;
}this.set_manualCloseButton(a);
this.tooltip._closeElement=a;
this.tooltip._closeElementHandler=Function.createDelegate(this,function(c){this.tooltip._hideUnconditionally();
return $telerik.cancelRawEvent(c);
});
$addHandler(a,"click",this.tooltip._closeElementHandler);
this.get_tooltipWrapper().appendChild(a);
},createTooltipWrapper:function(){var a=document.createElement("div");
a.className="rtRelativeWrapper";
this.set_tooltipWrapper(a);
this.get_popupElement().appendChild(a);
},createContentWrapper:function(){var a=document.createElement("div");
a.className="rtContent";
a.innerHTML="";
this.set_contentWrapper(a);
this.get_tooltipWrapper().appendChild(a);
},setContent:function(){var d;
var e=this.tooltip;
if(e._text){e.set_content(e._text);
}else{var f=e.get_id();
if(f){d=$get(f);
}if(d&&d.innerHTML){var a=e._transferNodeChildren(d);
e.set_contentElement(a);
}}var b=this.get_popupElement();
var c=b.style;
c.display="none";
c.position="absolute";
d=d||e.get_element();
e._addToolTipToDocument(d);
},_appendManualCloseButton:function(a){this.tooltip._tooltipWrapper.appendChild(a);
},_removeManualCloseButton:function(a){this.tooltip._tooltipWrapper.removeChild(a);
},get_popupElement:function(){return this.tooltip._popupElement;
},set_popupElement:function(a){this.tooltip._popupElement=a;
},get_contentWrapper:function(){return this.tooltip._contentWrapper;
},set_contentWrapper:function(a){this.tooltip._contentWrapper=a;
},get_tooltipWrapper:function(){return this.tooltip._tooltipWrapper;
},set_tooltipWrapper:function(a){this.tooltip._tooltipWrapper=a;
},get_calloutElement:function(){return this.tooltip._calloutElement;
},set_calloutElement:function(a){this.tooltip._calloutElement=a;
},get_titleElement:function(){return this.tooltip._titleElement;
},set_titleElement:function(a){this.tooltip._titleElement=a;
},get_titleWrapper:function(){return this.tooltip._titleWrapper;
},set_titleWrapper:function(a){this.tooltip._titleWrapper=a;
},get_titleBar:function(){return this.tooltip._titleBar;
},set_titleBar:function(a){this.tooltip._titleBar=a;
},get_manualCloseButton:function(){return this.tooltip._manualCloseButton;
},set_manualCloseButton:function(a){this.tooltip._manualCloseButton=a;
}};
Telerik.Web.UI.ToolTip.LightweightRenderer.registerClass("Telerik.Web.UI.ToolTip.LightweightRenderer",Telerik.Web.UI.ToolTip.RendererBase,Telerik.Web.UI.ToolTip.IRenderer);
})();
Type.registerNamespace("Telerik.Web.UI.ToolTip");
(function(){Telerik.Web.UI.ToolTip.LightweightRendererAria=function(a){Telerik.Web.UI.ToolTip.LightweightRendererAria.initializeBase(this,[a]);
};
Telerik.Web.UI.ToolTip.LightweightRendererAria.prototype={createUI:function(){Telerik.Web.UI.ToolTip.LightweightRendererAria.callBaseMethod(this,"createUI");
this._applyAriaSupport();
},_applyAriaSupport:function(){if(!this.tooltip.get_enableAriaSupport()){return;
}this.tooltip.get_element().setAttribute("aria-hidden","true");
this.tooltip._tooltipWrapper.setAttribute("role","presentation");
this.tooltip._contentWrapper.setAttribute("role","presentation");
var b=this.tooltip.get_popupElement();
if(this.tooltip._title){b.setAttribute("aria-labelledby",this.tooltip._titleWrapper.id);
this.tooltip._titleWrapper.setAttribute("role","label");
}b.setAttribute("aria-hidden","true");
b.setAttribute("role","tooltip");
var a=this.tooltip.getManualCloseButton();
if(a){a.setAttribute("role","button");
}}};
Telerik.Web.UI.ToolTip.LightweightRendererAria.registerClass("Telerik.Web.UI.ToolTip.LightweightRendererAria",Telerik.Web.UI.ToolTip.LightweightRenderer);
})();
Type.registerNamespace("Telerik.Web.UI.ToolTip");
(function(){var a="rtLoading";
Telerik.Web.UI.ToolTip.ClassicView=function(b){Telerik.Web.UI.ToolTip.ClassicView.initializeBase(this,[b]);
};
Telerik.Web.UI.ToolTip.ClassicView.prototype={set_width:function(b){this.tooltip._popupElement.style.width="";
this.tooltip._tableElement.style.width=b+"px";
},set_height:function(b){this.tooltip._popupElement.style.height="";
this.tooltip._tableElement.style.height=b+"px";
},addShadow:function(){this._addElementShadow(this.tooltip._tableElement);
this._addElementShadow(this.tooltip._popupElement);
},removeShadow:function(){this._removeElementShadow(this.tooltip._tableElement);
this._removeElementShadow(this.tooltip._popupElement);
},get_bounds:function(){return $telerik.getBounds(this.tooltip._tableElement);
},fixIeHeight:function(){if("CSS1Compat"==document.compatMode){var b=(this.tooltip._tableElement.offsetHeight-parseInt(this.tooltip.get_height(),10));
if(b>0){var c=(parseInt(this.tooltip._tableElement.style.height,10)-b);
if(c>0){this.tooltip._tableElement.style.height=c+"px";
}}}},fixToolTipPosition:function(d,b,f,e,c){this.fixToolTipPositionBase(d,b,f,e,c,0);
},fixTooltipBounds:function(b){return b;
},refreshTitle:function(){if(null==this.tooltip._titleBar){return;
}this.tooltip._titleBar.innerHTML=this.tooltip._title;
this.tooltip._titleBar.style.display=(this.tooltip._title)?"":"none";
var b=this.tooltip._tableElement.rows[0];
Sys.UI.DomElement.removeCssClass(b,"rtVisibleTitleBar");
if(this.tooltip._title){Sys.UI.DomElement.addCssClass(b,"rtVisibleTitleBar");
}Telerik.Web.UI.ToolTip.AriaSupportHelper.setTitleElementAriaHiddenAttr(b,this.tooltip._title,this.tooltip.get_enableAriaSupport());
},showLoadingMessage:function(c){var b=this.tooltip._getFullSkinName();
if(c){Sys.UI.DomElement.addCssClass(this.tooltip._contentWrapper,b);
Sys.UI.DomElement.addCssClass(this.tooltip._contentWrapper,a);
}else{Sys.UI.DomElement.removeCssClass(this.tooltip._contentWrapper,b);
Sys.UI.DomElement.removeCssClass(this.tooltip._contentWrapper,a);
}},isLoading:function(){return Sys.UI.DomElement.containsCssClass(this.tooltip._contentWrapper,a);
},setOverflow:function(){var d=this.tooltip.get_contentScrolling();
if(d==Telerik.Web.UI.ToolTipScrolling.Default){return;
}var c=this.tooltip._contentElement;
if(!c||c.parentNode!=this.tooltip._contentWrapper||((!c.document||!c.document.documentElement)&&$telerik.isIE)){return;
}this._setOverflowToElement(c,d);
var f=c.parentNode;
c.style.display="none";
var e=$telerik.getPaddingBox(c);
var b=$telerik.getBounds(f);
c.style.width=Math.abs(b.width-e.vertical)+"px";
c.style.height=Math.abs(b.height-e.horizontal)+"px";
this._fixMozSetOverflowToElement(c,d);
this._createTouchScrollExtender(d);
c.style.display="";
}};
Telerik.Web.UI.ToolTip.ClassicView.registerClass("Telerik.Web.UI.ToolTip.ClassicView",Telerik.Web.UI.ToolTip.BaseView,Telerik.Web.UI.ToolTip.IView);
})();
Type.registerNamespace("Telerik.Web.UI.ToolTip");
(function(){var a="rtLoading";
Telerik.Web.UI.ToolTip.LightweightView=function(b){Telerik.Web.UI.ToolTip.LightweightView.initializeBase(this,[b]);
};
Telerik.Web.UI.ToolTip.LightweightView.prototype={set_width:function(b){this.tooltip._popupElement.style.width=b+"px";
},set_height:function(b){this.tooltip._popupElement.style.height=b+"px";
},addShadow:function(){this._addElementShadow(this.tooltip._popupElement);
},removeShadow:function(){this._removeElementShadow(this.tooltip._popupElement);
},get_bounds:function(){return $telerik.getBounds(this.tooltip._popupElement);
},fixTooltipBounds:function(c){if(this.tooltip.get_relativeTo()==Telerik.Web.UI.ToolTipRelativeDisplay.BrowserWindow){return c;
}var b=this.get_calloutPosition(),d=Telerik.Web.UI.CalloutPosition;
switch(b){case d.TopLeft:c.x-=31;
c.y+=9;
break;
case d.TopCenter:c.y+=9;
break;
case d.TopRight:c.x+=40;
c.y+=9;
break;
case d.MiddleLeft:c.x+=10;
break;
case d.Center:break;
case d.MiddleRight:c.x-=2;
break;
case d.BottomLeft:c.x-=31;
break;
case d.BottomCenter:break;
case d.BottomRight:c.x+=40;
break;
}return c;
},get_calloutPosition:function(){var c=this.tooltip.get_position(),b=Telerik.Web.UI.ToolTipPosition;
switch(c){case b.TopLeft:return Telerik.Web.UI.CalloutPosition.BottomRight;
case b.TopCenter:return Telerik.Web.UI.CalloutPosition.BottomCenter;
case b.TopRight:return Telerik.Web.UI.CalloutPosition.BottomLeft;
case b.MiddleLeft:return Telerik.Web.UI.CalloutPosition.MiddleRight;
case b.Center:return Telerik.Web.UI.CalloutPosition.Center;
case b.MiddleRight:return Telerik.Web.UI.CalloutPosition.MiddleLeft;
case b.BottomLeft:return Telerik.Web.UI.CalloutPosition.TopRight;
case b.BottomCenter:return Telerik.Web.UI.CalloutPosition.TopCenter;
case b.BottomRight:return Telerik.Web.UI.CalloutPosition.TopLeft;
}return null;
},fixIeHeight:function(){if("CSS1Compat"==document.compatMode){var b=(this.tooltip._popupElement.offsetHeight-parseInt(this.tooltip.get_height(),10));
if(b>0){var c=(parseInt(this.tooltip._popupElement.style.height,10)-b);
if(c>0){this.tooltip._popupElement.style.height=c+"px";
}}}},fixToolTipPosition:function(d,b,f,e,c){this.fixToolTipPositionBase(d,b,f,e,c,10);
},refreshTitle:function(){if(!this.tooltip._titleElement){return;
}this.tooltip._titleElement.innerHTML=this.tooltip._title;
this.tooltip._titleElement.style.display=(this.tooltip._title)?"":"none";
Telerik.Web.UI.ToolTip.AriaSupportHelper.setTitleElementAriaHiddenAttr(this.tooltip._titleBar,this.tooltip._title,this.tooltip.get_enableAriaSupport());
},showLoadingMessage:function(b){if(b){Sys.UI.DomElement.addCssClass(this.tooltip._popupElement,a);
}else{Sys.UI.DomElement.removeCssClass(this.tooltip._popupElement,a);
}},isLoading:function(){return Sys.UI.DomElement.containsCssClass(this.tooltip._popupElement,a);
},setOverflow:function(){var c=this.tooltip.get_contentScrolling();
if(c==Telerik.Web.UI.ToolTipScrolling.Default){return;
}var b=this.tooltip._contentWrapper;
if(!b||($telerik.isIE&&((!b.document||!b.document.documentElement)&&(!b.ownerDocument||!b.ownerDocument.documentElement)))){return;
}this._setOverflowToElement(b,c);
if(this.tooltip.get_height()){var e=this.tooltip._titleBar?this.tooltip._titleBar.clientHeight:0;
var d=parseInt(this.tooltip.get_height(),10)-e;
b.style.height=d+"px";
}this._fixMozSetOverflowToElement(b,c);
this._createTouchScrollExtender(c);
b.style.display="";
}};
Telerik.Web.UI.ToolTip.LightweightView.registerClass("Telerik.Web.UI.ToolTip.LightweightView",Telerik.Web.UI.ToolTip.BaseView,Telerik.Web.UI.ToolTip.IView);
})();
(function(){Type.registerNamespace("Telerik.Web.UI.ToolTip");
var a=Telerik.Web.UI.ToolTip,b=Telerik.Web.UI.RenderMode;
a.RendererFactory={getRenderer:function(f){var e=f._renderMode,c=f.get_enableAriaSupport(),d;
switch(e){case b.Lite:d=c?new a.LightweightRendererAria(f):new a.LightweightRenderer(f);
break;
default:d=c?new a.ClassicRendererAria(f):new a.ClassicRenderer(f);
break;
}return d;
}};
})();
(function(){Type.registerNamespace("Telerik.Web.UI.ToolTip");
var a=Telerik.Web.UI.ToolTip,b=Telerik.Web.UI.RenderMode;
a.ViewFactory={getView:function(d){var c=d._renderMode;
switch(c){case b.Lite:return new a.LightweightView(d);
default:return new a.ClassicView(d);
}}};
})();
Type.registerNamespace("Telerik.Web.UI.ToolTip");
(function(){Telerik.Web.UI.ToolTip.AriaSupportHelper={setPopupElementAriaHiddenAttr:function(d,b,c,a){if(!b||!d||a==c){return;
}d.setAttribute("aria-hidden",a.toString());
},removeAriaDescribedbyAttr:function(b,a){if(!a){return;
}b.removeAttribute("aria-describedby");
},setAriaDescribedbyAttr:function(b,a,c){if(!a){return;
}b.setAttribute("aria-describedby","RadToolTipWrapper_"+c);
},setTitleElementAriaHiddenAttr:function(d,c,b){if(!b){return;
}var a=c?false:true;
d.setAttribute("aria-hidden",a.toString());
}};
})();
Type.registerNamespace("Telerik.Web.UI");
(function(){$telerik.toToolTip=function(d){return d;
};
$telerik.findToolTip=$find;
var a=$telerik.$;
var b=Telerik.Web.UI;
var c=Telerik.Web.Browser;
b.RadToolTipControllerClass=function(){this._tooltipToShow=null;
this._activeToolTip=null;
this._registerGlobalBodyEventHandlers();
};
b.RadToolTipControllerClass.prototype={_registerGlobalBodyEventHandlers:function(){var e=Function.createDelegate(this,function(f){if(f.keyCode==27){if(this._activeToolTip&&(!this._activeToolTip.isModal()||this._activeToolTip.get_enableAriaSupport())){this._hideCurrentToolTipNoAnimation();
}}});
var d=Function.createDelegate(this,function(f){this._hideOnBodyClick(f);
});
Sys.Application.add_init(function(){$addHandler(document.body,"keydown",e);
$addHandler(document.body,"click",d);
});
Sys.Application.add_unload(function(){$removeHandler(document.body,"keydown",e);
$removeHandler(document.body,"click",d);
});
},_hideOnBodyClick:function(d){var g=false;
if(this._activeToolTip!=null&&!this._activeToolTip.isModal()){var f=this._activeToolTip;
if(f._getUiView().isMouseOverElement(d)){return;
}g=this._activeToolTip._hideIfNotManualCloseOrFromCode();
}if(g){this._activeToolTip=null;
}},_cancelLastShowRequest:function(){if(this._tooltipToShow){var d=this._tooltipToShow;
this._tooltipToShow=null;
d.cancelShowDelay();
}},_hideCurrentToolTipNoAnimation:function(){this._cancelLastShowRequest();
if(this._activeToolTip!=null){this._activeToolTip._hideNoAnimation();
}this._activeToolTip=null;
},requestShow:function(e){this._cancelLastShowRequest();
var d=this._activeToolTip;
if(d==e){return;
}else{if(d){d._hideIfNotManualCloseOrFromCode();
}}this._tooltipToShow=e;
},cancelSpecificShowRequest:function(d){if(this._tooltipToShow==d){this._cancelLastShowRequest();
}},showTooltip:function(d){if(!d||d.isVisible()){return;
}this._cancelLastShowRequest();
this.set_activeToolTip(d);
d.show();
},notifyToolTipClosed:function(d){if(this._activeToolTip==d){this._activeToolTip=null;
}},set_activeToolTip:function(e){var d=this._activeToolTip;
if(d&&e!=d){this._hideCurrentToolTipNoAnimation();
}this._activeToolTip=e;
},get_activeToolTip:function(){return this._activeToolTip;
},getInstance:function(){return this;
}};
b.RadToolTipControllerClass.registerClass("Telerik.Web.UI.RadToolTipControllerClass",null);
if(!b.RadToolTipController){b.RadToolTipController=new b.RadToolTipControllerClass();
}a.registerEnum(b,"ToolTipPosition",{TopLeft:11,TopCenter:12,TopRight:13,MiddleLeft:21,Center:22,MiddleRight:23,BottomLeft:31,BottomCenter:32,BottomRight:33});
a.registerEnum(b,"CalloutPosition",{TopLeft:1,TopCenter:2,TopRight:3,MiddleLeft:4,Center:5,MiddleRight:6,BottomLeft:7,BottomCenter:8,BottomRight:9});
a.registerEnum(b,"ToolTipHorizontalPosition",{Left:1,Center:2,Right:3});
a.registerEnum(b,"ToolTipVerticalPosition",{Top:1,Middle:2,Bottom:3});
a.registerEnum(b,"ToolTipRelativeDisplay",{Mouse:0,Element:1,BrowserWindow:2});
a.registerEnum(b,"ToolTipScrolling",{Auto:0,None:1,X:2,Y:3,Both:4,Default:5});
a.registerEnum(b,"ToolTipAnimation",{None:0,Resize:1,Fade:2,Slide:4,FlyIn:8});
a.registerEnum(b,"ToolTipShowEvent",{OnMouseOver:1,OnClick:2,OnRightClick:4,OnFocus:8,FromCode:16});
a.registerEnum(b,"ToolTipHideEvent",{Default:1,LeaveToolTip:2,ManualClose:4,LeaveTargetAndToolTip:8,FromCode:16});
Type.registerNamespace("Telerik.Web.UI");
b.RadToolTip=function(d){b.RadToolTip.initializeBase(this,[d]);
this._position=b.ToolTipPosition.BottomCenter;
this._horizontalPosition=null;
this._verticalPosition=null;
this._targetControlID=null;
this._targetControl=null;
this._popupElement=null;
this._tableElement=null;
this._contentWrapper=null;
this._titleBar=null;
this._titleElement=null;
this._contentElement=null;
this._calloutElement=null;
this._closeElement=null;
this._manualCloseButton=null;
this._titleWrapper=null;
this._manualCloseOffset=null;
this._popupBehavior=null;
this._modal=false;
this._overlay=false;
this._onModalShowHandler=null;
this._onModalCloseHandler=null;
this._title="";
this._text="";
this._width="";
this._height="";
this._manualCloseButtonText="";
this._mouseTrailing=false;
this._showDelayRef=null;
this._autoCloseRef=null;
this._zIndex=8000;
this._cssClass=null;
this._dropDownTouchScroll=null;
this._hideEvent=b.ToolTipHideEvent.Default;
this._renderer=null;
this._uiView=null;
this._tooltipWrapper=null;
};
b.RadToolTip.getCurrent=function(){var d=b.RadToolTipController.getInstance();
if(!d){return null;
}return d.get_activeToolTip();
};
b.RadToolTip.prototype={get_zIndex:function(){return this._zIndex;
},set_zIndex:function(d){if(!isNaN(d)){this._zIndex=+d;
}},initialize:function(){b.RadToolTip.callBaseMethod(this,"initialize");
this.initRenderer();
this.initUiView();
this.set_position(this._position);
this._getToolTipAltText(this._targetControl);
this.applyElementZIndex();
if(this.get_enableAriaSupport()){this._createUI();
}if(this.get_visibleOnPageLoad()){setTimeout(Function.createDelegate(this,function(){this.show();
}),0);
}},dispose:function(){var f=this._getToolTipController();
if(this==f.get_activeToolTip()){f.set_activeToolTip(null);
}if(this._showRef){window.clearTimeout(this._showRef);
this._showRef=null;
}if(this._popupBehavior){this._popupBehavior.dispose();
this._popupBehavior=null;
}this._registerPopupHandlers(false);
this._registerMouseHandlers(this._targetControl,false);
this._makeModal(false);
this._createTouchScrollExtender(false);
if(this._closeElementHandler&&this._closeElement){$clearHandlers(this._closeElement);
this._closeElementHandler=null;
}if(this._popupElement){var e=this.get_id();
if(e){var d=$get(e);
if(d){d.appendChild(this._popupElement);
}}}b.RadToolTip.callBaseMethod(this,"dispose");
},applyElementZIndex:function(){var d=$telerik.getCurrentStyle(this.get_element(),"zIndex");
var e=c.ie&&c.version===7&&d===0;
if(null!=d&&!e){this.set_zIndex(d);
}},isCreated:function(){return this._popupElement!=null;
},get_leaveTargetAndToolTip:function(){return this.isHideEventEnabled(b.ToolTipHideEvent.LeaveTargetAndToolTip);
},isHideEventEnabled:function(d){return d&this.get_hideEvent();
},hide:function(){this._hideUnconditionally();
},_hideIfNotManualCloseOrFromCode:function(){var d=this.isHideEventEnabled(b.ToolTipHideEvent.FromCode);
var e=this.get_manualClose();
if(e||d){return false;
}this._hideUnconditionally();
return true;
},_hideUnconditionally:function(){if(!this.isVisible()){return;
}this._hide();
},_hideNoAnimation:function(){this._hide(false);
},_hide:function(h){if(this.get_animation()!=b.ToolTipAnimation.None){$telerik.$(this._popupElement).stop();
}this.cancelHideDelay();
this.cancelShowDelay();
this.cancelAutoCloseDelay();
var i=this._popupElement;
if(!i){return;
}var e=new Sys.CancelEventArgs();
this.raiseEvent("beforeHide",e);
if(e.get_cancel()){return;
}var f=this.get_contentElement();
if(f){f.scrollTop=f.scrollLeft=0;
}if(this.get_animation()!=b.ToolTipAnimation.None&&h!=false){if($telerik.isIE){this._getUiView().removeShadow();
}var d=this._calloutElement;
if(d){d.style.visibility="hidden";
}var g=Function.createDelegate(this,this._afterHide);
$telerik.$(i).fadeOut(this.get_animationDuration(),g);
}else{this._afterHide();
}},_afterHide:function(){try{if(this._popupBehavior){this._popupBehavior.hide();
this._popupBehavior.pin(false);
}}catch(d){}this._getToolTipController().notifyToolTipClosed(this);
this.raiseEvent("hide");
Telerik.Web.UI.ToolTip.AriaSupportHelper.setPopupElementAriaHiddenAttr(this._popupElement,this.get_enableAriaSupport(),this.isVisible(),true);
this._registerPopupHandlers(false);
},clone:function(d){var e=document.createElement("span");
if(d){e.setAttribute("id",d);
}return $telerik.cloneControl(this,b.RadToolTip,e);
},show:function(){if(!this.get_element()){return;
}this._createUI();
var d=new Sys.CancelEventArgs();
this.raiseEvent("beforeShow",d);
if(d.get_cancel()||!(this._shouldShow()||this.isLoading())){return;
}this._popupBehavior.pin(false);
this._showRef=window.setTimeout(Function.createDelegate(this,function(){this._getToolTipController().set_activeToolTip(this);
if(this.get_animation()==b.ToolTipAnimation.None){this._show();
this._afterShow();
}else{window.setTimeout(Function.createDelegate(this,function(){this._playAnimation();
}),100);
}}),0);
},updateLocation:function(){this._show();
},showLoadingMessage:function(d){this._getUiView().showLoadingMessage(d);
},isLoading:function(){return this._getUiView().isLoading();
},_getToolTipAltText:function(g){var h=g?g:this.get_targetControl();
if(h){var i=h.getAttribute("title");
var f=this.get_ignoreAltAttribute();
var d=f?null:h.getAttribute("alt");
if(i||d){if(!f){h.removeAttribute("alt");
}h.removeAttribute("title");
if(!this.get_text()){var e=i?i:d;
this.set_text(e);
}}}},isModal:function(){return this._modal;
},set_contentElement:function(d){this._contentWrapper.innerHTML="";
if(d.parentNode&&d.parentNode.removeChild){d.parentNode.removeChild(d);
}this._contentWrapper.appendChild(d);
d.style.display="";
this._contentElement=d;
this._setOverflow();
this.showLoadingMessage(false);
},get_contentElement:function(){return this._contentElement;
},set_content:function(d){this._text=d;
if(this.isCreated()){var e=document.createElement("div");
e.innerHTML=d;
this.set_contentElement(e);
}},get_content:function(){return this._contentElement?this._contentElement.innerHTML:"";
},cancelHideDelay:function(){if(this._hideDelayRef){window.clearTimeout(this._hideDelayRef);
this._hideDelayRef=0;
}},cancelAutoCloseDelay:function(){if(this._autoCloseRef){window.clearTimeout(this._autoCloseRef);
this._autoCloseRef=0;
}},cancelShowDelay:function(){if(this._showDelayRef){window.clearTimeout(this._showDelayRef);
this._showDelayRef=null;
}this._getToolTipController().cancelSpecificShowRequest(this);
},_getToolTipController:function(){return b.RadToolTipController.getInstance();
},_resetAutoCloseDelay:function(){this.cancelAutoCloseDelay();
if(this.get_manualClose()||this.get_sticky()){return;
}if(this.get_autoCloseDelay()){this._autoCloseRef=window.setTimeout(Function.createDelegate(this,function(){this._hideIfNotManualCloseOrFromCode();
}),this.get_autoCloseDelay());
}},_shouldShow:function(){var d=Sys.WebForms.PageRequestManager.getInstance();
if(d&&d.get_isInAsyncPostBack()){return true;
}return !this.isEmpty();
},_resetShowDelay:function(){this.cancelShowDelay();
var d=Function.createDelegate(this,function(){this._getToolTipController().showTooltip(this);
this.cancelShowDelay();
});
this._showDelayRef=window.setTimeout(d,this.get_showDelay());
},_resetHideDelay:function(){this.cancelHideDelay();
if(this.get_hideDelay()>0){this._hideDelayRef=window.setTimeout(Function.createDelegate(this,function(){this._hideIfNotManualCloseOrFromCode();
}),this.get_hideDelay());
}else{this._hideIfNotManualCloseOrFromCode();
}},_show:function(){var f=null;
try{f=this.getToolTipBounds();
}catch(h){var d=this;
window.setTimeout(function(){d._addToolTipToDocument();
},10);
return;
}this._setPopupVisible(f.x,f.y);
var g=this.get_contentElement();
if(g){$telerik.repaintChildren(g);
}},_afterShow:function(){this._registerPopupHandlers(true);
this._popupBehavior.pin(this._isRelativeToBrowserWindow());
this._resetAutoCloseDelay();
if(this.get_animation()==b.ToolTipAnimation.None){this._adjustCallout();
}this.raiseEvent("show");
Telerik.Web.UI.ToolTip.AriaSupportHelper.setPopupElementAriaHiddenAttr(this._popupElement,this.get_enableAriaSupport(),this.isVisible(),false);
},_isRelativeToBrowserWindow:function(){if(!this._targetControl||this.get_relativeTo()==b.ToolTipRelativeDisplay.BrowserWindow){return true;
}return false;
},_playAnimation:function(){if(this!=b.RadToolTip.getCurrent()){return;
}var g=Function.createDelegate(this,function(){var q=this.getToolTipBounds();
this._setPopupVisible(q.x,q.y);
this._adjustCallout();
var p=this._getUiView().get_bounds();
$telerik.$(this._popupElement).hide();
return p;
});
var h=g();
var j=Function.createDelegate(this,function(){if(this._isRelativeToBrowserWindow()){this._documentOverflowX=document.documentElement.style.overflowX;
document.documentElement.style.overflowX="hidden";
}if(this.get_showCallout()&&this._calloutElement){this._calloutElement.style.visibility="hidden";
}if($telerik.isIE){this._getUiView().removeShadow();
}});
var i=Function.createDelegate(this,function(){var p=this.get_popupElement();
p.style.filter="";
p.style.opacity="";
if(this.get_showCallout()&&this._calloutElement){this._calloutElement.style.visibility="";
}if($telerik.isIE&&!$telerik.isIE6){this._getUiView().addShadow();
}if(this._renderMode==Telerik.Web.UI.RenderMode.Classic){this._show();
}if(null!=this._documentOverflowX){document.documentElement.style.overflowX=this._documentOverflowX;
this._documentOverflowX=null;
}this._afterShow();
});
var d=this.get_popupElement();
var f=this.get_animation();
var k=""+this._position;
var l=this._isRelativeToBrowserWindow();
if(l&&this._verticalPosition!=2){var o=(this._verticalPosition==1?3:1);
k=parseInt(o+""+this._horizontalPosition,10);
}var m=l?document.documentElement:this._targetControl;
var n=m?$telerik.getBounds(m):new Telerik.Web.UI.Bounds(1,1,1,1);
var e=this.get_animationDuration();
window.setTimeout(function(){b.Animations.playJQueryAnimation(d,f,n,h,k,j,i,e);
},0);
},_makeModal:function(d){if(this._onModalShowHandler){this.remove_show(this._onModalShowHandler);
this._onModalShowHandler=null;
}if(this._onModalCloseHandler){this.remove_hide(this._onModalCloseHandler);
this._onModalCloseHandler=null;
}if(this._modalExtender){this._modalExtender.dispose();
this._modalExtender=null;
}if(!d){return;
}this._onModalShowHandler=function(e){if(!e._modalExtender){e._modalExtender=new b.ModalExtender(e._popupElement);
}e._modalExtender.show();
};
this.add_show(this._onModalShowHandler);
this._onModalCloseHandler=function(e){if(e._modalExtender){e._modalExtender.hide();
}};
this.add_hide(this._onModalCloseHandler);
},_onMouseOver:function(d){this._logMousePosition(d);
this.cancelHideDelay();
this.cancelAutoCloseDelay();
var f=this.get_showEvent();
if(f==b.ToolTipShowEvent.OnMouseOver){this._resetShowDelay();
this._getToolTipController().requestShow(this);
}},_onMouseMove:function(d){this._logMousePosition(d);
this._resetAutoCloseDelay();
if(this._mouseTrailing&&this.isVisible()){this._show();
}},_onMouseOut:function(d){if(!this.isVisible()){this.cancelShowDelay();
return;
}var f=$telerik.isMouseOverElementEx(this._targetControl,d);
if(!f){this.cancelShowDelay();
if(!this.get_sticky()){this._resetHideDelay();
}}},_onClick:function(d){this._onMouseOver(d);
this._resetShowDelay();
this._getToolTipController().requestShow(this);
return $telerik.cancelRawEvent(d);
},_onRightClick:function(d){this._onMouseOver(d);
this._resetShowDelay();
this._getToolTipController().requestShow(this);
return $telerik.cancelRawEvent(d);
},_registerMouseHandlers:function(m,d){if(true==d){var k=b.ToolTipShowEvent;
var l=this.get_showEvent();
if((l==k.OnMouseOver)||this.isHideEventEnabled(b.ToolTipHideEvent.LeaveTargetAndToolTip)){this._onMouseOverDelegate=Function.createDelegate(this,this._onMouseOver);
$telerik.addExternalHandler(m,"mouseover",this._onMouseOverDelegate);
this._onMouseOutDelegate=Function.createDelegate(this,this._onMouseOut);
$telerik.addExternalHandler(m,"mouseout",this._onMouseOutDelegate);
}if(l==k.OnMouseOver){this._onMouseMoveDelegate=Function.createDelegate(this,this._onMouseMove);
$telerik.addExternalHandler(m,"mousemove",this._onMouseMoveDelegate);
}if(l==k.OnClick){this._onClickDelegate=Function.createDelegate(this,this._onClick);
$telerik.addExternalHandler(m,"click",this._onClickDelegate);
}if(l==k.OnRightClick){this._onRightClickDelegate=Function.createDelegate(this,this._onRightClick);
$telerik.addExternalHandler(m,"contextmenu",this._onRightClickDelegate);
}if(l==k.OnFocus){this._onFocusDelegate=Function.createDelegate(this,this._onClick);
this._onBlurDelegate=Function.createDelegate(this,this._onMouseOut);
$telerik.addExternalHandler(m,"focus",this._onFocusDelegate);
$telerik.addExternalHandler(m,"blur",this._onBlurDelegate);
}}else{if(m){var g=[["mouseover",this._onMouseOverDelegate],["mousemove",this._onMouseMoveDelegate],["mouseout",this._onMouseOutDelegate],["click",this._onClickDelegate],["contextmenu",this._onRightClickDelegate],["focus",this._onFocusDelegate],["blur",this._onBlurDelegate]];
for(var h=0;
h<g.length;
h++){var j=g[h];
try{if(null!=j[1]){$telerik.removeExternalHandler(m,j[0],j[1]);
}}catch(f){}}this._onMouseOverDelegate=null;
this._onMouseMoveDelegate=null;
this._onMouseOutDelegate=null;
this._onClickDelegate=null;
this._onRightClickDelegate=null;
this._onFocusDelegate=null;
this._onBlurDelegate=null;
}}},_registerPopupHandlers:function(d){if(!d&&!this._popupStickyHandler&&!this._popupEnterHandler&&!this._popupLeaveHandler){return;
}this._getUiView().registerPopupHandlers(d);
},_getPosRelativeToMouse:function(l){var f=l.x;
var g=l.y;
var j=this._getMousePosition();
var h=j.clientX;
var i=j.clientY;
var k=$telerik.standardsMode;
if(!$telerik.isIE&&document.compatMode!="CSS1Compat"){k=false;
}else{if($telerik.isSafari){k=false;
}}if(k){f-=$telerik.getCorrectScrollLeft(document.documentElement);
g-=document.documentElement.scrollTop;
}else{f-=$telerik.getCorrectScrollLeft(document.body);
g-=document.body.scrollTop;
}var d=h-f;
var e=i-g;
return{x:d,y:e};
},_logMousePosition:function(d){if(!d){return;
}this._mouseX=d.clientX;
this._mouseY=d.clientY;
},_getMousePosition:function(){var d={};
d.clientX=this._mouseX;
d.clientY=this._mouseY;
return d;
},_getCalloutBounds:function(){var d={width:0,height:0,marginLeft:0,marginTop:0};
if(this.get_showCallout()&&this._calloutElement){d.marginLeft=parseInt($telerik.getCurrentStyle(this._calloutElement,"marginLeft"),10);
d.marginTop=parseInt($telerik.getCurrentStyle(this._calloutElement,"marginTop"),10);
if(isNaN(d.marginLeft)){d.marginLeft=0;
}if(isNaN(d.marginTop)){d.marginTop=0;
}var e=$telerik.getBounds(this._calloutElement);
if(e){if(e.width){d.width=e.width;
}if(e.height){d.height=e.height;
}}}return d;
},_getBoundsRelativeToBrowser:function(h,d,j){var e=this._horizontalPosition;
var k=this._verticalPosition;
var l=0;
var m=0;
var f=this.get_offsetX();
var g=this.get_offsetY();
if(!j){j=$telerik.getClientBounds();
}var i=$telerik.getScrollOffset(document.compatMode&&document.compatMode!="BackCompat"?document.documentElement:document.body);
if("fixed"!=this._popupElement.style.position){l+=i.x;
m+=i.y;
}switch(e){case 2:l+=-parseInt(h.width/2-j.width/2,10);
l+=f;
break;
case 3:l+=j.width;
l-=h.width;
l-=f;
break;
default:l+=-h.width;
l+=(-d.width-d.marginLeft);
l+=f;
break;
}switch(k){case 2:m+=-parseInt((h.height-j.height)/2,10);
m+=g;
break;
case 1:m+=g;
break;
default:m+=j.height;
m-=g;
m-=h.height;
break;
}return new Telerik.Web.UI.Bounds(l,m,h.width,h.height);
},_getBoundsRelativeToElement:function(h,d,i){var e=this._horizontalPosition;
var j=this._verticalPosition;
var k=0;
var l=0;
var f=this.get_offsetX();
var g=this.get_offsetY();
if(!i){i=$telerik.getBounds(this._targetControl);
}switch(e){case 2:k+=-parseInt(h.width/2-i.width/2,10);
k+=f;
break;
case 3:k+=i.width;
k-=d.marginLeft;
k+=f;
break;
default:k+=-h.width;
k+=(-d.width-d.marginLeft);
k-=f;
break;
}switch(j){case 2:l+=-parseInt(h.height/2-i.height/2,10);
l+=g;
break;
case 1:l-=h.height;
l-=d.height+d.marginTop;
l-=g;
break;
default:l+=i.height;
l-=d.marginTop;
l+=g;
break;
}return new Telerik.Web.UI.Bounds(k,l,h.width,h.height);
},_getBoundsRelativeToMouse:function(f,e){var i=this._targetControl?$telerik.getBounds(this._targetControl):$telerik.getClientBounds();
var g=this._getPosRelativeToMouse(i);
if(isNaN(g.x)){g.x=0;
g.y=0;
}else{i.width=0;
i.height=0;
}var h=this._getBoundsRelativeToElement(f,e,i);
var j=Math.round(g.x+h.x);
var k=Math.round(g.y+h.y);
var d=new Telerik.Web.UI.Bounds(j,k,f.width,f.height);
return d;
},getToolTipBounds:function(){var i=this._popupElement;
var k=(i.style.display=="none")?true:false;
if(k){i.style.visibility="hidden";
}i.style.display="";
this._setOverflow();
if(this._firstShow!=true){this._getUiView().fixIeHeight();
this._firstShow=true;
}var g=this._isRelativeToBrowserWindow()?document.documentElement:this._targetControl;
this._popupBehavior.set_parentElement(g);
var h=this._getUiView().get_bounds();
var e=this._getCalloutBounds();
if(k){this._popupElement.style.display="none";
i.style.visibility="";
}var f=b.ToolTipRelativeDisplay;
var j=b.ToolTipShowEvent;
var d=null;
if(this.get_relativeTo()==f.BrowserWindow){d=this._getBoundsRelativeToBrowser(h,e);
}else{if(!this._targetControl&&this.get_showEvent()==j.FromCode){d=this._getBoundsRelativeToBrowser(h,e);
}else{if(this._targetControl&&this.get_showEvent()==j.FromCode){d=this._getBoundsRelativeToElement(h,e);
}else{if((this._mouseTrailing||this.get_relativeTo()==f.Mouse)){d=this._getBoundsRelativeToMouse(h,e);
}else{if(this.get_relativeTo()==f.Element){d=this._getBoundsRelativeToElement(h,e);
}}}}}d=this._getUiView().fixTooltipBounds(d);
return d;
},_refreshTitle:function(){this._getUiView().refreshTitle();
},getManualCloseButton:function(){return this._manualCloseButton;
},_getManualCloseOffset:function(){if(!this._manualCloseOffset){var d=this.getManualCloseButton();
var i=d.offsetTop;
var h=i<0?(d.offsetHeight+i):0;
var f=d.offsetLeft;
var e=$telerik.getBounds(this.get_popupElement()).width-f;
var g=e>0?d.offsetWidth-e:0;
if(this.isRightToLeft()){g=(f<=d.offsetWidth/2)?Math.abs(f):0;
}this._manualCloseOffset={offsetX:g,offsetY:h};
}return this._manualCloseOffset;
},_createManualCloseButton:function(){this._getRenderer().createManualCloseButton();
},_createUI:function(){this._getRenderer().createUI();
},_transferNodeChildren:function(f){if(!f){return null;
}var g=f.ownerDocument.createElement(f.tagName);
var d=0;
while(f.childNodes&&f.childNodes.length>d){var e=f.childNodes[d];
if(this._clientStateFieldID&&e.id==this._clientStateFieldID){d=1;
continue;
}f.removeChild(e);
g.appendChild(e);
}return g;
},_getDefaultParent:function(){var d=this.get_formID();
var e=d?document.getElementById(d):null;
if(!e){if(document.forms&&document.forms.length>0){e=document.forms[0];
}else{e=document.body;
}}return e;
},_addToolTipToDocument:function(d){if(d&&d.parentNode&&!this.get_renderInPageRoot()){d.parentNode.insertBefore(this._popupElement,d);
return;
}var e=this._getDefaultParent();
e.appendChild(this._popupElement);
},_getParentByTagName:function(d,f){var e=d;
f=f.toUpperCase();
while(e.tagName.toUpperCase()!=f){e=e.parentNode;
if(!e){break;
}}return e;
},_getFullSkinName:function(){return"RadToolTip RadToolTip_"+this.get_skin();
},_getUniqueString:function(){return""+(new Date()-100);
},_getCalloutPosition:function(d){var e=b.ToolTipPosition;
switch(d){case e.TopLeft:return"rtCalloutBottomRight";
case e.TopCenter:return"rtCalloutBottomCenter";
case e.TopRight:return"rtCalloutBottomLeft";
case e.MiddleLeft:return"rtCalloutMiddleRight";
case e.Center:return"rtCalloutCenter";
case e.MiddleRight:return"rtCalloutMiddleLeft";
case e.BottomLeft:return"rtCalloutTopRight";
case e.BottomCenter:return"rtCalloutTopCenter";
case e.BottomRight:return"rtCalloutTopLeft";
}return"";
},_getHorizontalSide:function(d){return parseInt((d+"").charAt(1),10);
},_getVerticalSide:function(d){return parseInt((d+"").charAt(0),10);
},_setPopupVisible:function(j,k){var g=this._isRelativeToBrowserWindow();
var d=this.get_contentElement();
if(d){d.scrollTop=d.scrollLeft=0;
}this._popupElement.style.zIndex=this._zIndex;
if(($telerik.isMobileSafari||$telerik.isSafari||$telerik.isChrome)&&g){var f=window.pageYOffset,e=window.pageXOffset,i=document.body.scrollTop,h=document.body.scrollLeft;
if(i&&i!=document.documentElement.scrollTop){k+=g?f:-f;
}if(h&&h!=document.documentElement.scrollLeft){j+=g?e:-e;
}}this._popupBehavior.set_x(j);
this._popupBehavior.set_y(k);
this._popupBehavior.show();
if(this.get_manualClose()){this._fixManualCloseOffset();
}if(!this.get_width()){this._popupElement.style.width="";
}},_fixManualCloseOffset:function(){var e=this._getManualCloseOffset();
var j=this.get_popupElement();
var f=$telerik.getBounds(j);
var k=false;
var h=e.offsetY;
var g=e.offsetX;
var d=this.isRightToLeft();
if(h>0&&parseInt(j.style.top,10)<h){k=true;
f.y=h;
}if((g>0&&(parseInt(j.style.left,10)+f.width+g>$telerik.getViewPortSize().width))||d){k=true;
if(d&&f.x<0){f.x=0;
}f.x=d?f.x+g:f.x-g;
}if(k){$telerik.setLocation(j,{x:f.x,y:f.y});
var i=j._hideWindowedElementsIFrame;
if(i){$telerik.setLocation(i,{x:f.x,y:f.y});
}}},_reSetToolTipPosition:function(){var d=this.getToolTipBounds();
this._setPopupVisible(d.x,d.y);
},_reSetPositionWithoutFlicker:function(){var d=this._popupBehavior;
if(!d){return;
}d.set_manageVisibility(false);
this._reSetToolTipPosition();
this._adjustCallout();
d.set_manageVisibility(true);
var e=this.get_width();
if(e){this._popupElement.style.width=e+"px";
}},_setOverflow:function(){this._getUiView().setOverflow();
},_createTouchScrollExtender:function(f){var d=this._contentElement;
if(d){var e=this._dropDownTouchScroll;
if(e){if(!f){e.dispose();
this._dropDownTouchScroll=null;
}}else{if(f){this._dropDownTouchScroll=new b.TouchScrollExtender(d);
this._dropDownTouchScroll.initialize();
}}}},_getLeftOffset:function(){var e=b.ToolTipPosition;
var d=this.get_offsetX();
if(e.Left==this._position){return(-1*this._targetControl.offsetWidth)+d;
}else{if(e.Right==this._position){return this._targetControl.offsetWidth+d;
}else{return d;
}}},_getTopOffset:function(){var f;
var e=b.ToolTipPosition;
var d=this.get_offsetY();
if(e.Top==this._position){f=(-1*this._targetControl.offsetHeight)+d;
}else{if(e.Bottom==this._position){f=this._targetControl.offsetHeight+d;
}else{f=d;
}}return f;
},_adjustCallout:function(){if(this._originalPosition){this.set_position(this._originalPosition);
this.updateLocation();
this._originalPosition=null;
}if(this.get_showCallout()&&this.get_position()!=22&&this.get_relativeTo()==b.ToolTipRelativeDisplay.Element){var f=this.get_targetControl();
if(!f){return;
}var e=$telerik.getBounds(f);
this._calloutElement.style.left="";
this._calloutElement.style.top="";
var d=$telerik.getBounds(this._calloutElement);
var g=$telerik.getViewPortSize();
var h=Math.min(g.height-e.y,e.height);
var i=Math.min(g.width-e.x,e.width);
this._calloutElement.style.visibility="hidden";
this._fixToolTipPosition(e,d,i,h,true);
d=$telerik.getBounds(this._calloutElement);
this._fixToolTipPosition(e,d,i,h,false);
this._calloutElement.style.visibility="visible";
this._fixCalloutPosition(e,i,h);
}},_fixCalloutPosition:function(d,f,e){this._getUiView()._fixCalloutPosition(d,f,e);
},_fixToolTipPosition:function(f,d,h,g,e){this._getUiView().fixToolTipPosition(f,d,h,g,e);
},isEmpty:function(){var d=a(this.get_contentElement());
return d.text().match(/[^\s]/)===null&&d.children().length===0;
},isVisible:function(){var d=this._popupElement;
return(d&&d.style.display!="none");
},isRightToLeft:function(){var d=this.get_element();
var e=d.parentNode?d:this._getDefaultParent();
return $telerik.isRightToLeft(e);
},get_targetControlID:function(){return this._targetControlID;
},set_targetControlID:function(e){if(this._targetControlID!=e){this._targetControlID=e;
var d=(this._targetControlID?$get(this._targetControlID):null);
this.set_targetControl(d);
}},get_value:function(){return this.get_serverValue();
},set_value:function(d){this.set_serverValue(d);
},get_position:function(){return this._position;
},set_position:function(d){if(this._position!=d){this._position=d;
if(this._calloutElement){this._calloutElement.className="rtCallout "+this._getCalloutPosition(this._position);
}}this._horizontalPosition=this._getHorizontalSide(this._position);
this._verticalPosition=this._getVerticalSide(this._position);
},get_title:function(){return this._title;
},set_title:function(d){if(this._title!=d){this._title=d;
}if(this._popupElement){this._refreshTitle();
}},get_text:function(){return this._text;
},set_text:function(d){if(this._text!=d){this._text=d;
}if(this.isCreated()){this.set_content(this._text);
}},get_width:function(){return this._width;
},set_width:function(e){var d=parseInt(e,10);
if(!isNaN(d)&&d>0&&this._width!=d){this._width=d;
if(this._popupElement){this._getUiView().set_width(d);
}}},get_height:function(){return this._height;
},set_height:function(e){var d=parseInt(e,10);
if(!isNaN(d)&&d>0&&this._height!=d){this._height=d;
if(this._popupElement){this._getUiView().set_height(d);
}}},get_sticky:function(){return this.isHideEventEnabled(b.ToolTipHideEvent.LeaveToolTip);
},set_sticky:function(d){if(d){this.set_hideEvent(b.ToolTipHideEvent.LeaveToolTip);
}},get_manualClose:function(){return this.isHideEventEnabled(b.ToolTipHideEvent.ManualClose);
},set_manualClose:function(d){if(d){this.set_hideEvent(b.ToolTipHideEvent.ManualClose);
}},get_mouseTrailing:function(){return this._mouseTrailing;
},set_mouseTrailing:function(d){if(this._mouseTrailing!=d){this._mouseTrailing=d;
if(true==d){this.set_relativeTo(b.ToolTipRelativeDisplay.Mouse);
}}},get_modal:function(){return this._modal;
},set_modal:function(d){if(this._modal!=d){this._modal=d;
}this._makeModal(this._modal);
},get_overlay:function(){return this._overlay;
},set_overlay:function(d){this._overlay=d;
if(this._popupBehavior){this._popupBehavior.set_overlay(this._overlay);
}if(this.isVisible()){this._reSetToolTipPosition();
}},get_targetControl:function(){return this._targetControl;
},set_targetControl:function(e){if(this._targetControl!=e){if(this._targetControl&&(this._targetControl!=e)){this._registerMouseHandlers(this._targetControl,false);
Telerik.Web.UI.ToolTip.AriaSupportHelper.removeAriaDescribedbyAttr(this._targetControl,this.get_enableAriaSupport());
}var d=this._ensureRadControlsCompatTarget(e);
this._targetControl=d;
if(d){this._getToolTipAltText(d);
this._registerMouseHandlers(d,true);
if(this._popupBehavior){this._popupBehavior.set_parentElement(d);
}Telerik.Web.UI.ToolTip.AriaSupportHelper.removeAriaDescribedbyAttr(d,this.get_enableAriaSupport(),this.get_id());
}}},get_hideEvent:function(){return this._hideEvent;
},set_hideEvent:function(e){if(this.get_hideEvent()==e){return;
}this._hideEvent=e;
if(!this.isCreated()){return;
}if(this.get_manualClose()){this._createManualCloseButton();
this._getRenderer()._appendManualCloseButton(this._manualCloseButton);
}else{var d=this.getManualCloseButton();
if(!d){return;
}this._getRenderer()._removeManualCloseButton(d);
if(this._closeElementHandler&&this._closeElement){$clearHandlers(this._closeElement);
this._closeElementHandler=null;
this._manualCloseButton=this._closeElement=null;
}}},_ensureRadControlsCompatTarget:function(f){var d=null;
if(f!=null){this._getToolTipAltText(f);
d=f.getAttribute("_rfddecoratedID");
if(d){f=$get(d);
}}var g=d?d:this.get_targetControlID();
var e=$get(g+"_text");
if(e&&g){var h=$find(g);
if(h&&Object.getType(h).inheritsFrom(b.RadInputControl)){f=$get(g+"_text");
}}return f;
},get_popupElement:function(){return this._popupElement;
},initRenderer:function(){this._renderer=Telerik.Web.UI.ToolTip.RendererFactory.getRenderer(this);
},initUiView:function(){this._uiView=Telerik.Web.UI.ToolTip.ViewFactory.getView(this);
},_getRenderer:function(){return this._renderer;
},_getUiView:function(){return this._uiView;
}};
a.registerControlProperties(b.RadToolTip,{serverTargetControlID:null,serverValue:"",formID:null,offsetX:0,offsetY:6,relativeTo:b.ToolTipRelativeDisplay.Mouse,contentScrolling:b.ToolTipScrolling.Default,showCallout:true,renderInPageRoot:true,showDelay:400,autoCloseDelay:3000,hideDelay:300,visibleOnPageLoad:false,animation:b.ToolTipAnimation.None,animationDuration:500,showEvent:b.ToolTipShowEvent.OnMouseOver,skin:"Default",enableShadow:true,enableRoundedCorners:true,ignoreAltAttribute:false,enableAriaSupport:false,renderMode:b.RenderMode.Classic});
a.registerControlEvents(b.RadToolTip,["beforeShow","show","beforeHide","hide"]);
b.RadToolTip.registerClass("Telerik.Web.UI.RadToolTip",b.RadWebControl);
})();
