(function(a,c,b,d){if(!c.RadListBoxItem.Views){c.RadListBoxItem.Views={};
}c.RadListBoxItem.Views.Classic=function(e){this._owner=e;
};
c.RadListBoxItem.Views.Classic.prototype={get_text:function(){return c.RadListBoxItem.callBaseMethod(this._owner,"get_text");
},set_text:function(e){c.RadListBoxItem.callBaseMethod(this._owner,"set_text",[e]);
},set_element:function(e){this._owner._textElement=e.getElementsByTagName("span")[0];
},get_textElement:function(){if(!this._owner._textElement){this._owner._textElement=this._getTextNode();
}return this._owner._textElement;
},_getTextNode:function(){var e=this._owner.get_element(),f;
if(e){f=$telerik.getChildByClassName(e,"rlbText",0);
return f||$telerik.getChildByClassName(e,"rlbTemplate",0)||null;
}return null;
},_renderTextElement:function(e){e[e.length]="<span class='rlbText'";
if(this._owner._getStyles(this._owner.get_textElement(),"_textElementStyles")){var f=this._owner._parseStyles(this._owner._getStyles(this._owner.get_textElement(),"_textElementStyles"));
this._owner._renderStyles(f,e);
}e[e.length]=" />";
e[e.length]=this._owner.get_text();
e[e.length]="</span>";
}};
})($telerik.$,Telerik.Web.UI,Telerik.Web.StringBuilder);
