(function(a,c,b,d){if(!c.RadListBoxItem.Views){c.RadListBoxItem.Views={};
}c.RadListBoxItem.Views.Lite=function(e){this._owner=e;
};
c.RadListBoxItem.Views.Lite.prototype={get_text:function(){var f=this._owner;
if(f._text!==null){return f._text;
}f._text=f._properties.getValue("text","");
if(f._text){return f._text;
}if(!f.get_element()){return"";
}var e=f.get_textElement();
if(!e){return"";
}f._text=e.nodeValue;
return f._text;
},set_text:function(e){var g=this._owner;
var f=this.get_textElement();
if(f){f.nodeValue=e;
}g._text=e;
g._properties.setValue("text",e,true);
},set_element:function(e){this._owner._textElement=this._getTextNode();
},get_textElement:function(){if(!this._owner._textElement){this._owner._textElement=this._getTextNode();
}return this._owner._textElement;
},_renderTextElement:function(e){e[e.length]=this.get_text();
},_getTextNode:function(){var f=null,g=this._owner,e=a(g.get_element());
if(e.children("label").length>0){e=a(e.children("label")[0]);
}if(e.length>0){e.contents().each(function(){if(this.nodeType==3){f=this;
return false;
}});
if(!f){f=this._createTextNode(e.get(0));
}}return f;
},_createTextNode:function(e){var f=document.createTextNode("");
e.appendChild(f);
return f;
}};
})($telerik.$,Telerik.Web.UI,Telerik.Web.StringBuilder);
