(function(a,t){var n=window.kendo;
var s=n.ui;
var k=s.Gantt;
var l=s.GanttList;
var j=a.extend;
var g="radCalendar";
var h="radDatePicker";
var i="radDateTimePicker";
var p="radNumericTextBox";
var q="radTextBox";
var m={wrapper:"RadGantt",rowHeight:"rgtRowheight",listWrapper:"rgtTreelistWrapper",list:"rgtTreelistWrapper",timelineWrapper:"rgtTimelineWrapper",timeline:"rgtTimelineWrapper",splitBarWrapper:"rgtSplitbar",splitBar:"rgtSplitbar",splitBarHover:"rgtSplitbarHover",popupWrapper:"radPopup",popupList:"radList",resizeHandle:"radResizeHandle",icon:"radIcon",item:"radItem",line:"radLine",buttonDelete:"k-gantt-delete",buttonCancel:"k-gantt-cancel",buttonSave:"k-gantt-update",buttonToggle:"k-gantt-toggle",primary:"radPrimary",hovered:"radStateHovered",selected:"radStateSelected",focused:"radStateFocused",gridHeader:"radGridHeader",gridHeaderWrap:"radGridHeaderWrap",gridContent:"radGridContent",popup:{form:"radPopupEditForm",editForm:"rgtEditForm",formContainer:"radEditFormContainer",resourcesFormContainer:"radResourceFormContainer",message:"radPopupMessage",buttonsContainer:"rgtButtonsContainer",button:"radButton",editField:"radFormField",editLabel:"radFormLabel",resourcesField:"k-gantt-resources"},toolbar:{headerWrapper:"rgtToolbar rgtHeader",footerWrapper:"rgtToolbar rgtFooter",toolbar:"radToolbar",expanded:"rgtExpanded",views:"rgtViews",viewsWrapper:"radToolbar rgtViews",actions:"rgtActions",button:"radButton",buttonToggle:"radButton radButtonIcon k-gantt-toggle",iconPlus:"radIcon radIconPlus",iconPdf:"radIcon radIconPdf",iconToggle:"radIcon k-i-gantt-toggle",viewButtonDefault:"radStateDefault",viewButton:"rgtViewButton",currentView:"rgtCurrentView",link:"radButton",pdfButton:"rgtPdfButton",appendButton:"rgtCreateButton"}};
j(true,s.Gantt,{styles:m});
var o={wrapper:"radGrid rgtTreelist",header:"radHeader",alt:"radAlt",editCell:"k-edit-cell",group:"rgtTreelistGroup",gridHeader:"radGridHeader",gridHeaderWrap:"radGridHeaderWrap",gridContent:"rgtTreelistContent",gridContentWrap:"rgtTreelistContent radGridContent",selected:"radStateSelected",icon:"radIcon",iconCollapse:"radIconCollapse",iconExpand:"radIconExpand",iconHidden:"radIconNone",iconPlaceHolder:"radIcon radIconNone",input:"k-input",link:"k-link",resizeHandle:"k-resize-handle",resizeHandleInner:"k-resize-handle-inner",dropPositions:"radIconInsertTop radIconInsertBottom radIconAdd radIconInsertMiddle",dropTop:"radIconInsertTop",dropBottom:"radIconInsertBottom",dropAdd:"radIconAdd",dropMiddle:"radIconInsertMiddle",dropDenied:"radIconDenied",dragStatus:"radDragStatus",dragClue:"radDragClue",dragClueText:"radDragClueText"};
j(true,s.GanttList,{styles:o});
var u={alt:"radAlt",reset:"k-reset",nonWorking:"radNonwork",header:"radHeader",gridHeader:"radGridHeader",gridHeaderWrap:"radGridHeaderWrap",gridContent:"rgtTimelineContent",tasksWrapper:"rgtTables",rowsTable:"radFauxRows",columnsTable:"radFauxColumns",tasksTable:"rgtTasks",dependenciesWrapper:"rgtDependencies",resource:"rgtResource",resourceAlt:"rgtResource radAlt",task:"rgtTask",taskSingle:"rgtTaskSingle",taskMilestone:"rgtTaskMilestone",taskSummary:"rgtTaskSummary",taskWrap:"rgtTaskWrap",taskMilestoneWrap:"rgtMilestoneWrap",resourcesWrap:"rgtResourceWrap",taskDot:"rgtTaskDot",taskDotStart:"rgtTaskStart",taskDotEnd:"rgtTaskEnd",taskDragHandle:"rgtDragHanle",taskContent:"rgtTaskContent",taskTemplate:"rgtTaskTemplate",taskActions:"rgtTaskActions",taskDelete:"rgtTaskDelete",taskComplete:"rgtTaskComplete",taskDetails:"rgtTaskDetails",taskDetailsPercent:"rgtTaskPct",link:"radButton",icon:"radIcon",iconDelete:"radIconDelete",taskResizeHandle:"radResizeHandle",taskResizeHandleWest:"radResizeW",taskResizeHandleEast:"radResizeE",taskSummaryProgress:"rgtProgress",taskSummaryComplete:"rgtComplete",line:"radLine",lineHorizontal:"radLineH",lineVertical:"radLineV",arrowWest:"radArrowW",arrowEast:"radArrowE",dragHint:"radDragHint",dependencyHint:"rgtDependencyHint",tooltipWrapper:"radTooltip",tooltipContent:"radTooltipContent",tooltipCallout:"radCallout radCalloutS",callout:"radCallout",marquee:"radMarquee",marqueeColor:"radMarqueeColor"};
j(true,s.GanttView,{styles:u});
var r={wrapper:"radGrid rgtTimeline",gridHeader:"radGridHeader",gridHeaderWrap:"radGridHeaderWrap",gridContent:"rgtTimelineContent",gridContentWrap:"rgtTimelineContent radGridContent",tasksWrapper:"rgtTables",dependenciesWrapper:"rgtDependencies",task:"rgtTask",line:"radLine",taskResizeHandle:"radResizeHandle",taskResizeHandleWest:"radResizeW",taskDragHandle:"rgtDragHanle",taskDelete:"rgtTaskDelete",taskComplete:"rgtTaskComplete",taskWrapActive:"rgtTaskWrapActive",taskWrap:"rgtTaskWrap",taskDot:"rgtTaskDot",taskDotStart:"rgtTaskStart",taskDotEnd:"rgtTaskEnd",hovered:"radStateHovered",selected:"radStateSelected",origin:"radOrigin"};
j(true,s.GanttTimeline,{styles:r});
function f(z){var y=k.styles;
var v=function(){var A=z.dateView;
A.div.addClass(y.popupWrapper);
A.calendar.wrapper.addClass(g);
};
var x=function(){z.timeView.list.addClass(y.popupWrapper);
};
var w=function(A){z.wrapper.addClass(A);
};
if(z){if(z instanceof s.DatePicker){w(h);
z.bind("open",function(){v();
},true);
}else{if(z instanceof s.DateTimePicker){w(i);
z.bind("open",function(A){if(A.view==="time"){x();
}else{v();
}});
}else{if(z instanceof s.NumericTextBox){w(p);
}}}}}var d=k.fn.editTask;
k.fn.editTask=function(w){d.call(this,w);
var v=this._editor.container;
v.parent().addClass("radSkin_"+this.options.skin);
var x=v.find("input[data-role]");
x.each(function(z,y){var A=n.widgetInstance($telerik.$(y));
if(A){f(A);
}});
v.find("input[name='title']").addClass(q);
};
var e=k.fn.showDialog;
k.fn.showDialog=function(w){e.call(this,w);
var v=this._editor.popup.element;
v.parent().addClass("radSkin_"+this.options.skin);
};
var c=l.fn._editCell;
l.fn._editCell=function(v){c.call(this,v);
if(!this.editable){return;
}var w=n.widgetInstance(v.cell.find("input[data-role]"));
if(w){f(w);
}else{v.cell.children("input").addClass(q);
}};
var b=k.fn._createResourceEditor;
k.fn._createResourceEditor=function(v,w){var x=this;
b.call(this,v,w);
var y=this._resourceEditor.window.wrapper;
y.addClass("radSkin_"+this.options.skin);
this._resourceEditor.grid.bind("filterMenuInit",function(A){var z=A.container;
z.addClass("radSkin_"+x.options.skin);
});
};
})(window.kendo.jQuery);
(function(a,j){$telerik.findGantt=$find;
$telerik.toGantt=function(m){return m;
};
Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.Gantt");
var c=Telerik.Web.UI;
var b=Sys.Serialization.JavaScriptSerializer;
var e="__EVENTVALIDATION";
var k="__VIEWSTATE";
var i=function(m){return m.d||m;
};
var h=window.kendo;
var f=h.ui.Gantt;
var g=h.ui.GanttList;
a.registerEnum(c,"GanttViewType",{Day:0,Week:1,Month:2,Year:3});
var d=c.Gantt={commands:{create:{task:"InsertTask",dependency:"InsertDependency",assignment:"InsertAssignment"},destroy:{task:"DeleteTask",dependency:"DeleteDependency",assignment:"DeleteAssignment"},update:{task:"UpdateTask",dependency:"UpdateDependency",assignment:"UpdateAssignment"}},transportProxy:function(o){this._data=o.data;
this._id=o.id;
this._type=o.type;
this._commandsCache=o.commandsCache;
var p=this;
var m=c.Gantt.commands;
var n=function(x){var s=x.cmd;
var w=s.indexOf("Task")>-1;
if(x.args.length){var q=x.args[0];
var t=q.data.models||q.data;
if(w){var u=function(z){var y=new Date(z);
y.setMinutes(y.getMinutes()-y.getTimezoneOffset());
return y;
};
for(var v=0;
v<t.length;
v++){t[v].Start=u(t[v].Start);
t[v].End=u(t[v].End);
}}if(!(t instanceof Array)){t=[a.extend({},t)];
}if(p._postBack){p._commandsCache[s]=t;
}else{var r=c.Gantt.callbackCommand({cmd:s,data:t,type:p._type});
c.Gantt.request({id:p._id,cmd:r},function(){if(w){var y=arguments[0];
for(var z=0;
z<y.length;
z++){y[z].Start=new Date(y[z].Start);
y[z].End=new Date(y[z].End);
}}q.success.apply(this,arguments);
},q.fail);
}}};
this.set_postback=function(q){p._postBack=q;
};
this.read=function(){var q=p._data;
if(q&&p._type==="task"){for(var r=0;
r<q.length;
r++){q[r].Start=new Date(q[r].Start);
q[r].End=new Date(q[r].End);
}}arguments[0].success(p._data);
};
this.create=function(){n({args:arguments,cmd:m.create[p._type]});
};
this.update=function(){n({args:arguments,cmd:m.update[p._type]});
};
this.destroy=function(){n({args:arguments,cmd:m.destroy[p._type]});
};
},transport:function(o){var p=o.path.lastIndexOf("/")===o.path.length-1?o.path:o.path+"/";
var r=o.type;
var n=o.methods;
var q={parameterMap:function(t,s){if(s!=="read"){return b.serialize({models:(t.models||[t])});
}}};
for(var m in n){q[m]={url:p+n[m],type:r,dataType:"json",contentType:"application/json"};
}return q;
},request:function(n,o,m){a.ajax(c.Gantt.transportCallbackParams(n)).done(o).fail(m);
},callbackCommand:function(n){var o={commandName:n.cmd};
var m={task:"tasks",dependency:"dependencies",assignment:"assignments"};
o[m[n.type]]=n.data;
return o;
},transportCallbackParams:function(o){var m=$get(e);
var n=m?m.value:"";
var p=$get(k);
var q=p?p.value:"";
return{url:window.location,data:{__EVENTTARGET:"",__EVENTARGUMENT:"",__VIEWSTATE:q,__CALLBACKID:o.id,__CALLBACKPARAM:b.serialize(o.cmd),__EVENTVALIDATION:n},type:"POST",dataType:"JSON",converters:{"text json":c.Gantt.callbackConverter}};
},callbackConverter:function(n){var m=n.split("|")[1];
return a.parseJSON(m);
},createDependency:function(n,o,p){var m=new c.GanttDependency();
m._loadFromDictionary({predecessorId:n,successorId:o,type:p});
return m;
},createAssignment:function(o,n,p){var m=new c.GanttAssignment();
m._loadFromDictionary({TaskID:o,ResourceID:n,Units:p});
return m;
}};
var l=function(m){for(var n in m){this["set_"+n](m[n]);
}};
a.registerControlProperties(l,{path:"",useHttpGet:false,method:"GetTasks",deleteTasksMethod:"DeleteTasks",insertTasksMethod:"InsertTasks",updateTasksMethod:"UpdateTasks",getDependenciesMethod:"GetDependencies",deleteDependenciesMethod:"DeleteDependencies",insertDependenciesMethod:"InsertDependencies",getResourcesMethod:"GetResources",getAssignmentsMethod:"GetAssignments",insertAssignmentsMethod:"InsertAssignments",updateAssignmentsMethod:"UpdateAssignments",deleteAssignmentsMethod:"DeleteAssignments"});
c.RadGantt=function(m){c.RadGantt.initializeBase(this,[m]);
this._widget=null;
this._webServiceSettings=null;
this._postBackReference=null;
this._skin="Default";
this._height=700;
this._width="100%";
this._uniqueId=null;
this._postBackOnNavigate=false;
this._postBackOnTaskInsert=false;
this._postBackOnTaskUpdate=false;
this._postBackOnTaskDelete=false;
this._postBackOnDependencyInsert=false;
this._postBackOnDependencyDelete=false;
this._postBackOnAssignmentInsert=false;
this._postBackOnAssignmentUpdate=false;
this._postBackOnAssignmentDelete=false;
this._commandsCache={};
this._navigationSettings={};
};
c.RadGantt.prototype={initialize:function(){c.RadGantt.callBaseMethod(this,"initialize");
this._extendStyles();
this.initializePdfSettings();
this.initializeWidget();
this.initializeCustomFields();
this._initializePostback();
this._initializeKeyboardNavigation();
this._initializeScroll();
},initializePdfSettings:function(){var n=this.get_pdfSettings();
if(n){if(n.date){var m=parseInt(n.date.match(/\d+/)[0],10);
n.date=new Date(m);
}if(n.margin){n.margin=a.parseJSON(n.margin);
}if(n.fonts){n.fonts=a.parseJSON(n.fonts);
h.pdf.defineFont(n.fonts);
}}},initializeWidget:function(){var m=this;
this._widget=a(this.get_element()).kendoGantt(this.widget()).data("kendoGantt");
this._widget.timeline.bind("navigate",function(n){m.updateClientState();
});
},initializeCustomFields:function(){var m=this.get_customTaskFields();
var n;
var q=c.GanttTask;
for(var o=0,p=m.length;
o<p;
o++){n=m[o].clientPropertyName;
q.prototype["get_"+n]=function(){return this._data[n];
};
q.prototype["set_"+n]=function(s){var r={};
r[n]=s;
this._data[n]=s;
this._update(r);
};
}},_initializeScroll:function(){var m=this;
a(".rgtTimelineContent").on("scroll",function(n){m.set_scrollTop(a(this).scrollTop());
m.set_scrollLeft(h.scrollLeft(this));
m.updateClientState();
}).scrollTop(this.get_scrollTop());
h.scrollLeft(a(".rgtTimelineContent"),m.get_scrollLeft());
},dispose:function(){this.disposeWidget();
this._disposeScroll();
this._disposeKeyboardNavigation();
c.RadGantt.callBaseMethod(this,"dispose");
},disposeWidget:function(){this._widget.destroy();
},_disposeScroll:function(){a(".rgtTimelineContent").off("scroll");
},proxy:function(n,m){var p=this.get_webServiceSettings();
var o;
if(p){o={task:{read:p.get_method(),update:p.get_updateTasksMethod(),destroy:p.get_deleteTasksMethod(),create:p.get_insertTasksMethod()},dependency:{read:p.get_getDependenciesMethod(),destroy:p.get_deleteDependenciesMethod(),create:p.get_insertDependenciesMethod()},assignment:{read:p.get_getAssignmentsMethod(),update:p.get_updateAssignmentsMethod(),destroy:p.get_deleteAssignmentsMethod(),create:p.get_insertAssignmentsMethod()}};
return d.transport({path:p.get_path(),type:p.get_useHttpGet()?"GET":"POST",methods:o[n]});
}else{return new c.Gantt.transportProxy({data:this[m](),id:this._uniqueId,type:n,commandsCache:this._commandsCache});
}},widget:function(){var o=this;
var m=!this.get_readOnly();
if(m&&!this.get_displayDeleteConfirmation()){m={confirmation:false};
}var n={dataSource:this.tasksDataSource(),dependencies:this.dependenciesDataSource(),autoBind:true,selectable:!this.get_readOnly(),editable:m,toolbar:this.toolbar(),currentTimeMarker:this.currentTimeMarker(),messages:this.get_localization(),showWorkHours:!this.get_showFullTime(),showWorkDays:!this.get_showFullWeek(),workWeekStart:this.get_workWeekStart(),workWeekEnd:this.get_workWeekEnd(),tooltip:{visible:this.get_showTooltip()},hourSpan:this.get_hourSpan(),snap:this.get_snapToGrid(),height:this.get_height(),width:this.get_width(),listWidth:this.get_listWidth(),rowHeight:this.get_rowHeight(),views:this.views(),columns:this.columns(),resizable:this.get_allowColumnResize(),navigatable:this._getNavigatable(),skin:this._skin,pdf:this.get_pdfSettings(),taskTemplate:this.get_clientTemplate(),moveStart:function(p){if(a.raiseCancellableControlEvent(o,"taskMoveStart",{task:p.task})){p.preventDefault();
}},move:function(q){var p={task:q.task,start:q.start};
if(a.raiseCancellableControlEvent(o,"taskMoving",p)){q.preventDefault();
}},moveEnd:function(q){var p={task:q.task,start:q.start};
if(a.raiseCancellableControlEvent(o,"taskMoveEnd",p)){q.preventDefault();
}},resizeStart:function(p){if(a.raiseCancellableControlEvent(o,"taskResizeStart",{task:p.task})){p.preventDefault();
}},resize:function(q){var p={task:q.task,start:q.start,end:q.end};
if(a.raiseCancellableControlEvent(o,"taskResizing",p)){q.preventDefault();
}},resizeEnd:function(q){var p={task:q.task,start:q.start,end:q.end};
if(a.raiseCancellableControlEvent(o,"taskResizeEnd",p)){q.preventDefault();
}},columnResize:function(q){var p={column:q.column,newWidth:q.newWidth,oldWidth:q.oldWidth};
a.raiseControlEvent(o,"columnResized",p);
},navigate:function(p){o._raiseNavigationCommand(p);
},pdfExport:function(p){if(a.raiseCancellableControlEvent(o,"pdfExporting",{})){p.preventDefault();
}},dataBound:function(p){if(!o._widget){o._widget=p.sender;
}a.raiseControlEvent(o,"dataBound",{});
}};
if(this.get_enableResources()){a.extend(true,n,{resources:this.resources(),assignments:this.assignments()});
}return n;
},currentTimeMarker:function(){var m=this.get_showCurrentTimeMarker();
if(m){m={updateInterval:this.get_currentTimeMarkerInterval()};
}return m;
},toolbar:function(){var m=[];
if(!this.get_readOnly()){m.push("append");
}if(this.get_enablePdfExport()){m.push("pdf");
}return m;
},views:function(){var m={day:{selected:true,slotSize:100,timeHeaderTemplate:"#=kendo.toString(start, 't')#",dayHeaderTemplate:"#=kendo.toString(start, 'ddd M/dd')#"},week:{selected:false,slotSize:100,dayHeaderTemplate:"#=kendo.toString(start, 'ddd M/dd')#",weekHeaderTemplate:"#=kendo.toString(start, 'ddd M/dd')# - #=kendo.toString(kendo.date.addDays(end, -1), 'ddd M/dd')#"},month:{selected:false,slotSize:150,weekHeaderTemplate:"#=kendo.toString(start, 'ddd M/dd')# - #=kendo.toString(kendo.date.addDays(end, -1), 'ddd M/dd')#",monthHeaderTemplate:"#=kendo.toString(start, 'MMMM, yyyy')#"},year:{selected:false,slotSize:100,monthHeaderTemplate:"#=kendo.toString(start, 'MMM')#",yearHeaderTemplate:"#=kendo.toString(start, 'yyyy')#"}};
var n=a.map(this.get_viewsData(),function(o){return a.extend(true,{},m[o.type],o);
});
return n;
},columns:function(){var m=[{field:"id",title:"ID",sortable:false,editable:false},{field:"title",title:"Title",sortable:true,editable:true},{field:"start",title:"Start Time",sortable:true,editable:true,format:"{0:MM/dd/yyyy HH:mm}"},{field:"end",title:"End Time",sortable:true,editable:true,format:"{0:MM/dd/yyyy HH:mm}"},{field:"percentComplete",title:"Percent Complete",sortable:true,editable:true,format:"{0:p}"}];
var o={title:"",sortable:true,editable:true,format:""};
var n=this.get_columnsData();
var p=function(s){for(var t=0;
t<m.length;
t++){var r=m[t];
if(r.field===s.field){return a.extend({},r,s);
}}return a.extend({},o,s);
};
for(var q=0;
q<n.length;
q++){n[q]=p(n[q]);
}return n.length?n:m;
},tasksDataSource:function(){var m=this.get_customTaskFields();
var s=["default","string","number","date","boolean"];
var n;
var o;
var r={transport:this.proxy("task","get_tasksData"),schema:{model:{id:"id",fields:{id:{from:"ID"},orderId:{from:"OrderID",type:"number"},parentId:{from:"ParentID",defaultValue:null},title:{from:"Title",defaultValue:"",type:"string"},start:{from:"Start",type:"date"},end:{from:"End",type:"date"},percentComplete:{from:"PercentComplete",type:"number"},summary:{from:"Summary",type:"bool"},expanded:{from:"Expanded",type:"bool"}}},parse:i},batch:true};
for(var p=0,q=m.length;
p<q;
p++){n=m[p];
o={from:n.propertyName,type:s[n.type]};
if(n.defaultValue!==j){o.defaultValue=n.defaultValue;
}r.schema.model.fields[n.clientPropertyName]=o;
}if(this.get_webServiceSettings()){r.requestStart=this._getRequestEventHandler("Tasks");
}return r;
},dependenciesDataSource:function(){var m={transport:this.proxy("dependency","get_dependenciesData"),schema:{model:{id:"id",fields:{id:{from:"ID"},predecessorId:{from:"PredecessorID"},successorId:{from:"SuccessorID"},type:{from:"Type",type:"number"}}},parse:i},batch:true};
if(this.get_webServiceSettings()){m.requestStart=this._getRequestEventHandler("Dependencies");
}return m;
},resources:function(){var m={dataColorField:"Color",dataTextField:"Text",dataFormatField:"Format",dataSource:this.resourcesDataSource()};
return m;
},resourcesDataSource:function(){var n=this.get_resourcesData();
var o=this.get_webServiceSettings();
var m={schema:{model:{id:"id",fields:{id:{from:"ID"}}},parse:i}};
if(n.length>0){m.data=n;
}else{if(o){m.transport=d.transport({path:o.get_path(),type:o.get_useHttpGet()?"GET":"POST",methods:{read:o.get_getResourcesMethod()}});
m.requestStart=this._getRequestEventHandler("Resources");
}}return m;
},assignments:function(){var m={dataTaskIdField:"TaskID",dataResourceIdField:"ResourceID",dataValueField:"Units",dataSource:this.assignmentsDataSource()};
return m;
},assignmentsDataSource:function(){var m={transport:this.proxy("assignment","get_assignmentsData"),schema:{model:{id:"id",fields:{id:{from:"ID"},TaskID:{from:"TaskID"},ResourceID:{from:"ResourceID"},Units:{from:"Units"}}},parse:i},batch:true};
if(this.get_webServiceSettings()){m.requestStart=this._getRequestEventHandler("Assignments");
}return m;
},get_tasks:function(){var m=this._widget.dataSource.taskChildren();
var q=new c.GanttTaskCollection(this);
var p;
for(var n=0,o=m.length;
n<o;
n++){p=new c.GanttTask();
p._loadFromDictionary(m[n]);
q._add(p);
}return q;
},get_allTasks:function(){var m=this._widget.dataSource.taskAllChildren();
var q=[];
var p;
for(var n=0,o=m.length;
n<o;
n++){p=new c.GanttTask();
p._loadFromDictionary(m[n]);
p._owner=this;
q.push(p);
}return q;
},get_webServiceSettings:function(){return this._webServiceSettings;
},set_webServiceSettings:function(n){var m=b.deserialize(n);
this._webServiceSettings=new l(m);
},get_dependencies:function(){var m=this._widget.dependencies.view();
var n=new c.GanttDependencyCollection(this);
var o;
for(var p=0,q=m.length;
p<q;
p++){o=new c.GanttDependency();
o._loadFromDictionary(m[p]);
n._add(o);
}return n;
},get_resources:function(){var m=this._widget.resources.dataSource.view();
var q=new c.GanttResourceCollection(this);
var p;
for(var n=0,o=m.length;
n<o;
n++){p=new c.GanttResource();
p._loadFromDictionary(m[n]);
q._add(p);
}return q;
},get_assignments:function(){var o=this._widget.assignments.dataSource.view();
var n=new c.GanttAssignmentCollection(this);
var m;
for(var p=0,q=o.length;
p<q;
p++){m=new c.GanttAssignment();
m._loadFromDictionary(o[p]);
n._add(m);
}return n;
},get_postBackReference:function(){return this._postBackReference;
},get_height:function(){return this._height;
},set_height:function(m){this._height=m;
if(this._widget){this._widget.options.height=m;
a(this.get_element()).height(m);
this._widget.resize();
}},get_width:function(){return this._width;
},set_width:function(m){this._width=m;
if(this._widget){this._widget.options.width=m;
a(this.get_element()).width(m);
this._widget.resize();
}},get_selectedView:function(){var m=this._widget.timeline._selectedViewName;
switch(m){case"day":return c.GanttViewType.Day;
case"week":return c.GanttViewType.Week;
case"month":return c.GanttViewType.Month;
case"year":return c.GanttViewType.Year;
}},set_selectedView:function(m){var n=["day","week","month","year"];
this._widget.view(n[m]);
},exportToPdf:function(){if(this.get_enablePdfExport()){this._widget.saveAsPDF();
}},saveClientState:function(){return'{"scrollTop":'+Math.round(this.get_scrollTop())+', "scrollLeft":'+Math.round(this.get_scrollLeft())+', "selectedView":'+this.get_selectedView()+"}";
},postback:function(m){var n=this.get_postBackReference().replace("arguments",Sys.Serialization.JavaScriptSerializer.serialize(m).replace(/\\/g,"\\\\"));
eval(n);
},_extractTaskFromDomElement:function(o){var q;
var n;
var m;
var p=null;
q=a(o).closest(".rgtTask");
if(q.length>0){n=this._widget.dataSource;
m=n.getByUid(q.attr("data-uid"));
if(m){p=new c.GanttTask();
p._loadFromDictionary(m);
}}return p;
},_getRequestEventHandler:function(n){var m=this;
return function(p){var o={type:p.type+n,context:{}};
if(a.raiseCancellableControlEvent(m,"requestStart",o)){p.preventDefault();
return;
}p.sender.transport.parameterMap=function(r,q){var s={context:o.context};
if(q!=="read"){s.models=(r.models||[r]);
}return b.serialize(s);
};
};
},_raiseNavigationCommand:function(o){var m={view:o.view};
var n={day:"SwitchToDayView",week:"SwitchToWeekView",month:"SwitchToMonthView",year:"SwitchToYearView"};
if(a.raiseCancellableControlEvent(this,"navigationCommand",m)){o.preventDefault();
}else{if(this._postBackOnNavigate){o.preventDefault();
this.postback({commandName:n[m.view]});
}}},_insertTask:function(m,o){var q=this._widget;
var p=o._data;
var n=q.dataSource._createNewModel(p);
q._createTask(n,m);
},_updateTask:function(n,o){var m=this._getKendoTask(n);
this._widget._updateTask(m,o);
},_removeTask:function(n){var m=this._getKendoTask(n);
this._widget.removeTask(m);
},_addDependency:function(m){var p=this._widget;
var n=m._getInfo();
var o=p.dependencies._createNewModel(n);
p._createDependency(o);
},_removeDependency:function(m){var n=this._getKendoDependency(m);
this._widget.removeDependency(n);
},_updateAssignment:function(m){var n=this._getKendoAssignment(m);
this._widget._updateAssignment(n,m.get_units());
},_addAssignment:function(m){var q=this._widget;
var o=m._getInfo();
var n=q.assignments.dataSource;
var p=n._createNewModel(o);
n.add(p);
},_removeAssignment:function(m){var n=this._getKendoAssignment(m);
this._widget._removeAssignment(n);
},_getKendoTask:function(m){return this._widget.dataSource.getByUid(m._uid);
},_getKendoDependency:function(m){return this._widget.dependencies.getByUid(m._uid);
},_getKendoAssignment:function(m){return this._widget.assignments.dataSource.getByUid(m._uid);
},_extendStyles:function(){var m=" radSkin_"+this._skin;
if($telerik.isRightToLeft(this.get_element())){f.styles.wrapper+=" RadGantt_rtl RadGantt_"+this._skin+"_rtl k-rtl";
}f.styles.popupWrapper+=m;
g.styles.dragClue+=m;
},_initializePostback:function(){var p=this;
var o=[this._postBackOnTaskInsert,this._postBackOnTaskUpdate,this._postBackOnTaskDelete,this._postBackOnDependencyInsert,this._postBackOnDependencyDelete,this._postBackOnAssignmentInsert,this._postBackOnAssignmentUpdate,this._postBackOnAssignmentDelete];
var n=["_createTask","_updateTask","_removeTask","_createDependency","removeDependency","_createAssignment","_updateAssignment","_removeAssignment"];
var m=a(n).filter(function(q){return o[q];
});
a(m).each(function(r,q){var t=p._widget;
var s=t[q];
p._widget[q]=function(){t.dataSource.transport.set_postback(true);
if(t.dependencies.transport.set_postback){t.dependencies.transport.set_postback(true);
}if(t.assignments.dataSource.transport.set_postback){t.assignments.dataSource.transport.set_postback(true);
}s.apply(this,arguments);
p._commandsCache.commandName="Postback";
p.postback(p._commandsCache);
};
});
},_getNavigatable:function(){return this._navigationSettings.focusKey!==j;
},_initializeKeyboardNavigation:function(){var p=this._widget;
var o=this._navigationSettings;
var m=o.commandKey;
if(this._getNavigatable()){var n=this._keyboardNavigationHandler=function(s){var q=s.altKey===((1&m)>0);
var r=s.ctrlKey===((2&m)>0);
var t=s.shiftKey===((4&m)>0);
if(q&&r&&t&&s.keyCode===o.focusKey){p.list.content.find("table").focus();
}};
a(document.body).on("keydown",n);
}},_disposeKeyboardNavigation:function(){if(this._getNavigatable()){a(document.body).off("keydown",this._keyboardNavigationHandler);
}}};
a.registerControlProperties(c.RadGantt,{tasksData:[],dependenciesData:[],resourcesData:[],assignmentsData:[],enableResources:false,allowColumnResize:false,enablePdfExport:false,readOnly:false,workWeekStart:c.DayOfWeek.Monday,workWeekEnd:c.DayOfWeek.Friday,showFullTime:false,showFullWeek:true,showTooltip:true,showCurrentTimeMarker:true,currentTimeMarkerInterval:10000,displayDeleteConfirmation:true,hourSpan:1,snapToGrid:true,listWidth:"30%",rowHeight:null,clientTemplate:null,localization:{},viewsData:[],columnsData:[],customTaskFields:[],pdfSettings:{},scrollTop:0,scrollLeft:0});
a.registerControlEvents(c.RadGantt,["navigationCommand","taskMoveStart","taskMoving","taskMoveEnd","taskResizeStart","taskResizing","taskResizeEnd","columnResized","pdfExporting","requestStart","dataBound"]);
c.RadGantt.registerClass("Telerik.Web.UI.RadGantt",c.RadWebControl);
})($telerik.$);
(function(a,b,c){b.GanttTask=function(){this._data={parentId:null,title:"",percentComplete:0,summary:false,expanded:true};
this._owner=null;
};
b.GanttTask.prototype={_loadFromDictionary:function(d){this._data=a.extend({},d);
if(d.uid!==c){this._uid=d.uid;
}},get_id:function(){return this._data.id;
},get_parentId:function(){return this._data.parentId;
},get_orderId:function(){return this._data.orderId;
},get_start:function(){return this._data.start;
},get_end:function(){return this._data.end;
},get_title:function(){return this._data.title;
},get_percentComplete:function(){return this._data.percentComplete;
},get_summary:function(){return this._data.summary;
},get_expanded:function(){return this._data.expanded;
},get_tasks:function(){var k=new b.GanttTaskCollection(this);
var f;
var e;
var d;
var j;
if(this._owner){f=this._owner._widget.dataSource;
e=f.getByUid(this._uid);
if(e){d=f.taskChildren(e);
for(var g=0,h=d.length;
g<h;
g++){j=new b.GanttTask();
j._loadFromDictionary(d[g]);
k._add(j);
}}}return k;
},get_dependencies:function(){var e=new b.GanttDependencyCollection(this);
var d;
if(this._owner){d=this._owner._widget.dependencies.dependencies(this.get_id());
e=this._createDependencyCollection(d);
}return e;
},get_predecessors:function(){var e=new b.GanttDependencyCollection(this);
var d;
if(this._owner){d=this._owner._widget.dependencies.predecessors(this.get_id());
e=this._createDependencyCollection(d);
}return e;
},get_successors:function(){var e=new b.GanttDependencyCollection(this);
var d;
if(this._owner){d=this._owner._widget.dependencies.successors(this.get_id());
e=this._createDependencyCollection(d);
}return e;
},get_element:function(){var e=this._owner;
var d=null;
if(e){d=a(e.get_element()).find(".rgtTimelineContent").find(".rgtTask[data-uid='"+this._uid+"']")[0];
}return d;
},set_start:function(d){this._data.start=d;
this._update({start:d});
},set_end:function(d){this._data.end=d;
this._update({end:d});
},set_title:function(d){this._data.title=d;
this._update({title:d});
},set_percentComplete:function(d){this._data.percentComplete=d;
this._update({percentComplete:d});
},set_expanded:function(d){this._data.expanded=d;
this._update({expanded:d});
},_update:function(d){if(this._owner){this._owner._updateTask(this,d);
}},_createDependencyCollection:function(d){var f;
var e=new b.GanttDependencyCollection(this);
for(var g=0,h=d.length;
g<h;
g++){f=new b.GanttDependency();
f._loadFromDictionary(d[g]);
e._add(f);
}return e;
}};
b.GanttTask.registerClass("Telerik.Web.UI.GanttTask");
})($telerik.$,Telerik.Web.UI);
(function(a,b){b.GanttTaskCollection=function(c){if(c instanceof b.GanttTask){this._owner=c._owner;
}else{this._owner=c;
}this._parent=c;
this._array=[];
};
b.GanttTaskCollection.prototype={_add:function(c){this._array.push(c);
c._owner=this._owner;
},_insert:function(c,d){Array.insert(this._array,c,d);
d._owner=this._owner;
},_remove:function(c){this._array.pop(c);
c._owner=null;
},add:function(d){var c=this._array.length;
this.insert(c,d);
},insert:function(c,d){this._insert(c,d);
if(this._owner===this._parent){d._parentId=null;
}else{d._parentId=this._parent.get_id();
}this._owner._insertTask(c,d);
},remove:function(c){if(this.indexOf(c)>-1){this._remove(c);
this._owner._removeTask(c);
}},get_count:function(){return this._array.length;
},getTask:function(c){return this._array[c];
},indexOf:function(f){var c=this._array;
for(var d=0,e=c.length;
d<e;
d++){if(c[d]._uid===f._uid){return d;
}}return -1;
},toArray:function(){return this._array.slice(0);
}};
b.GanttTaskCollection.registerClass("Telerik.Web.UI.GanttTaskCollection");
})($telerik.$,Telerik.Web.UI);
(function(a,b,c){a.registerEnum(b,"GanttDependencyType",{FinishFinish:0,FinishStart:1,StartFinish:2,StartStart:3});
b.GanttDependency=function(){this._type=b.GanttDependencyType.FinishFinish;
this._owner=null;
};
b.GanttDependency.prototype={_loadFromDictionary:function(d){if(d.id!==c){this._id=d.id;
}if(d.predecessorId!==c){this._predecessorId=d.predecessorId;
}if(d.successorId!==c){this._successorId=d.successorId;
}if(d.type!==c){this._type=d.type;
}if(d.uid!==c){this._uid=d.uid;
}},get_id:function(){return this._id;
},get_predecessorId:function(){return this._predecessorId;
},get_successorId:function(){return this._successorId;
},get_type:function(){return this._type;
},_getInfo:function(){var d={predecessorId:this._predecessorId,successorId:this._successorId,type:this._type};
return d;
}};
b.GanttDependency.registerClass("Telerik.Web.UI.GanttDependency");
})($telerik.$,Telerik.Web.UI);
(function(a,b){b.GanttDependencyCollection=function(c){this._parent=c;
this._array=[];
};
b.GanttDependencyCollection.prototype={_add:function(c){this._array.push(c);
c._owner=this._parent;
},_remove:function(c){this._array.pop(c);
c._owner=null;
},add:function(c){this._add(c);
this._parent._addDependency(c);
},remove:function(c){if(this.indexOf(c)>-1){this._remove(c);
this._parent._removeDependency(c);
}},get_count:function(){return this._array.length;
},getDependency:function(c){return this._array[c];
},indexOf:function(d){var c=this._array;
for(var e=0,f=c.length;
e<f;
e++){if(c[e]._uid===d._uid){return e;
}}return -1;
},toArray:function(){return this._array.slice(0);
}};
b.GanttDependencyCollection.registerClass("Telerik.Web.UI.GanttDependencyCollection");
})($telerik.$,Telerik.Web.UI);
(function(a,b,c){b.GanttResource=function(){this._owner=null;
};
b.GanttResource.prototype={_loadFromDictionary:function(d){if(d.id!==c){this._id=d.id;
}if(d.Text!==c){this._text=d.Text;
}if(d.Color!==c){this._color=d.Color;
}if(d.Format!==c){this._format=d.Format;
}if(d.uid!==c){this._uid=d.uid;
}},get_id:function(){return this._id;
},get_text:function(){return this._text;
},get_color:function(){return this._color;
},get_format:function(){return this._format;
}};
b.GanttResource.registerClass("Telerik.Web.UI.GanttResource");
})($telerik.$,Telerik.Web.UI);
(function(a,b){b.GanttResourceCollection=function(c){this._parent=c;
this._array=[];
};
b.GanttResourceCollection.prototype={_add:function(c){this._array.push(c);
c._owner=this._parent;
},get_count:function(){return this._array.length;
},getResource:function(c){return this._array[c];
},indexOf:function(f){var c=this._array;
for(var d=0,e=c.length;
d<e;
d++){if(c[d]._uid===f._uid){return d;
}}return -1;
},toArray:function(){return this._array.slice(0);
}};
})($telerik.$,Telerik.Web.UI);
(function(a,b,c){b.GanttAssignment=function(){this._owner=null;
};
b.GanttAssignment.prototype={_loadFromDictionary:function(d){if(d.id!==c){this._id=d.id;
}if(d.TaskID!==c){this._taskId=d.TaskID;
}if(d.ResourceID!==c){this._resourceId=d.ResourceID;
}if(d.Units!==c){this._units=d.Units;
}if(d.uid!==c){this._uid=d.uid;
}},get_id:function(){return this._id;
},get_taskId:function(){return this._taskId;
},get_resourceId:function(){return this._resourceId;
},get_units:function(){return this._units;
},set_units:function(d){this._units=d;
this._update();
},_getInfo:function(){var d={TaskID:this._taskId,ResourceID:this._resourceId,Units:this._units};
return d;
},_update:function(){if(this._owner){this._owner._updateAssignment(this);
}}};
b.GanttAssignment.registerClass("Telerik.Web.UI.GanttAssignment");
})($telerik.$,Telerik.Web.UI);
(function(a,b){b.GanttAssignmentCollection=function(c){this._parent=c;
this._array=[];
};
b.GanttAssignmentCollection.prototype={_add:function(c){this._array.push(c);
c._owner=this._parent;
},_remove:function(c){this._array.pop(c);
c._owner=null;
},add:function(c){this._add(c);
this._parent._addAssignment(c);
},remove:function(c){if(this.indexOf(c)>-1){this._remove(c);
this._parent._removeAssignment(c);
}},get_count:function(){return this._array.length;
},getAssignment:function(c){return this._array[c];
},indexOf:function(d){var c=this._array;
for(var e=0,f=c.length;
e<f;
e++){if(c[e]._uid===d._uid){return e;
}}return -1;
},toArray:function(){return this._array.slice(0);
}};
b.GanttAssignmentCollection.registerClass("Telerik.Web.UI.GanttAssignmentCollection");
})($telerik.$,Telerik.Web.UI);
