(function(a){Type.registerNamespace("Telerik.Web.UI.Scheduler.Views.Year.GroupedByResource");
var b=Telerik.Web.UI;
var c=b.Scheduler.Views.Year;
c.GroupedByResource.Model=function(f,d,e){c.GroupedByResource.Model.initializeBase(this,[f]);
this._groupingResource=d;
this._isVertical=e;
this._yearModels=[];
this._resources=null;
};
c.GroupedByResource.Model.prototype={initialize:function(){this._resources=this._owner.get_resources().getResourcesByType(this._groupingResource);
for(var d=0;
d<this._resources.get_count();
d++){this._yearModels[d]=new c.Model(this._owner);
}this._initializeContentElements();
},_initializeContentElements:function(){for(var d=0;
d<this._resources.get_count();
d++){this._yearModels[d]._contentElement=a(this._owner.get_element()).find("div.rsTopWrap .rsYearMonthsWrap")[d];
}},getTimeSlotFromDomElement:function(d){var e=this._getRawIndexFromDomElement(d);
var g=this._getStartTimeFromRawIndex(e);
var f=this._resources.getResource(e.modelIndex);
return new c.GroupedByResource.TimeSlot(e,g,f,d);
},getTimeSlotForAppointment:function(d){},_getRawIndexFromDomElement:function(d){var g=null;
while(d&&(d.tagName.toUpperCase()!="TD")){d=d.parentNode;
}if(d){var f=a(d).parents(".rsYearMonthsWrap").parent().index();
var e=this._yearModels[f];
if(e){g=e._getRawIndexFromDomElement(d);
g.modelIndex=f;
}}return g;
},_getRenderer:function(){if(!this._renderer){this._renderer=new b.Scheduler.Rendering.ResourceGroupedYearViewRenderer(this);
}return this._renderer;
}};
c.GroupedByResource.Model.registerClass("Telerik.Web.UI.Scheduler.Views.Year.GroupedByResource.Model",c.ModelBase);
c.GroupedByResource.TimeSlot=function(e,g,f,d){c.GroupedByResource.TimeSlot.initializeBase(this,[e,g,d]);
this._resource=f;
};
c.GroupedByResource.TimeSlot.prototype={get_index:function(){var d=this.get_rawIndex();
var e=c.GroupedByResource.TimeSlot.callBaseMethod(this,"get_index");
return String.format("{0}:{1}",d.modelIndex,e);
},get_resource:function(){return this._resource;
}};
c.GroupedByResource.TimeSlot.registerClass("Telerik.Web.UI.Scheduler.Views.Year.GroupedByResource.TimeSlot",c.TimeSlot);
})($telerik.$);
