(function(a,b){var c=a.proxy;
if(!b.RadComboBox.Views){b.RadComboBox.Views={};
}b.RadComboBox.Views.Lite=function(d){b.RadComboBox.makeEventHandler(this);
this._owner=d;
this._enabled=d.get_enabled(),this._wrapper=$telerik.getFirstChildByTagName(d.get_element(),"span",0);
};
b.RadComboBox.Views.Lite.prototype={initialize:function(){this.initDomEvents();
},initDomEvents:function(){var d=a(this.get_wrapper()),e=this;
d.on("click",function(g){var f=a(g.target),h=f.is(".rcbInput")?"inputClick":"buttonClick";
e.trigger(h,g);
});
d.on({mouseover:c(this._onWrapperHover,this),mouseout:c(this._onWrapperOut,this)});
},dispose:function(){this.disposeEvents();
this.disposeDomEvents();
},disposeDomEvents:function(){a(this.get_wrapper()).off();
},disable:function(){this.withWrapper(function(d){d.addClass("rcbDisabled");
});
},enable:function(){this.withWrapper(function(d){d.removeClass("rcbDisabled");
});
},repaint:function(){a(this.get_wrapper()).toggleClass("rcbReadOnly",this._owner.get_readOnly());
},focus:function(d){this.withWrapper(function(e){e.removeClass("rcbHovered");
e.addClass("rcbFocused");
});
},blur:function(d){this.withWrapper(function(e){e.removeClass("rcbFocused");
});
},withWrapper:function(d){var e=this.get_wrapper();
if(e!==null){d.apply(this,[a(e)]);
}},_onWrapperHover:function(d){if(!this._owner.get_enabled()){return;
}this.withWrapper(function(e){if(!e.is(".rcbFocused")){e.addClass("rcbHovered");
}});
},_onWrapperOut:function(d){if(!this._owner.get_enabled()){return;
}var g=this._wrapper;
var f=d.relatedTarget;
if(!f){return;
}while(f&&f.nodeType!==9){if(f.parentNode&&f.parentNode==g){return;
}f=f.parentNode;
}this.withWrapper(function(e){if(e.is(".rcbHovered")){e.removeClass("rcbHovered");
}});
},get_wrapper:function(){return this._wrapper;
}};
})($telerik.$,Telerik.Web.UI);
