(function(a,d){$telerik.findClientExportManager=$find;
$telerik.toClientExportManager=function(e){return e;
};
Type.registerNamespace("Telerik.Web.UI");
var b=Telerik.Web.UI;
var c=window.kendo;
b.RadClientExportManager=function(e){b.RadClientExportManager.initializeBase(this,[e]);
};
b.RadClientExportManager.prototype={initialize:function(){b.RadClientExportManager.callBaseMethod(this,"initialize");
this._initializeSettings();
this._raiseClientEvent("load",{});
},_initializeSettings:function(){if(this._pdfSettings){if(this._pdfSettings.date){var e=parseInt(this._pdfSettings.date.match(/\d+/)[0],10);
this._pdfSettings.date=new Date(e);
}if(this._pdfSettings.margin){this._pdfSettings.margin=a.parseJSON(this._pdfSettings.margin);
}if(this._pdfSettings.fonts){this._pdfSettings.fonts=a.parseJSON(this._pdfSettings.fonts);
c.pdf.defineFont(this._pdfSettings.fonts);
}}},_raiseClientEvent:function(g,e){var f=a.extendEventArgs(new Sys.EventArgs(),e);
a.raiseControlEvent(this,g,f);
},_raiseCancellableControlEvent:function(f,g,e){return a.raiseCancellableControlEvent(f,g,e);
},exportPDF:function(f,h){var e;
var i=this;
var g={};
if(!h){e=this.get_pdfSettings();
}else{e=h;
}if(e.pageBreakSelector){g.forcePageBreak=e.pageBreakSelector;
}c.drawing.drawDOM(f,g).then(function(j){return c.drawing.exportPDF(j,e);
}).done(function(j){var k=i._raiseCancellableControlEvent(i,"pdfExporting",{dataURI:j});
if(!k){c.saveAs({dataURI:j,fileName:e.fileName,proxyURL:e.proxyURL});
i._raiseClientEvent("pdfExported",{});
}});
},exportImage:function(f,g){var e;
var h=this;
if(!g){e=this.get_imageSettings();
}else{e=g;
}c.drawing.drawDOM(f).then(function(i){return c.drawing.exportImage(i,e);
}).done(function(i){var j=h._raiseCancellableControlEvent(h,"imageExporting",{dataURI:i});
if(!j){c.saveAs({dataURI:i,fileName:e.fileName,proxyURL:e.proxyURL});
h._raiseClientEvent("imageExported",{});
}});
},exportSVG:function(f,g){var e;
var h=this;
if(!g){e=this.get_svgSettings();
}else{e=g;
}c.drawing.drawDOM(f).then(function(i){return c.drawing.exportSVG(i,e);
}).done(function(i){var j=h._raiseCancellableControlEvent(h,"svgExporting",{dataURI:i});
if(!j){c.saveAs({dataURI:i,fileName:e.fileName,proxyURL:e.proxyURL});
h._raiseClientEvent("svgExported",{});
}});
},dispose:function(){b.RadClientExportManager.callBaseMethod(this,"dispose");
}};
a.registerControlProperties(b.RadClientExportManager,{pdfSettings:null,svgSettings:null,imageSettings:null});
a.registerControlEvents(b.RadClientExportManager,["load","pdfExporting","pdfExported","imageExporting","imageExported","svgExporting","svgExported"]);
b.RadClientExportManager.registerClass("Telerik.Web.UI.RadClientExportManager",b.RadWebControl);
})($telerik.$);
