Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadBarcode=function(a){Telerik.Web.UI.RadBarcode.initializeBase(this,[a]);
};
Telerik.Web.UI.RadBarcode.prototype={initialize:function(){Telerik.Web.UI.RadBarcode.callBaseMethod(this,"initialize");
if(document.namespaces&&document.namespaces.add){var a=document.documentMode;
if(!a||a<8){document.createStyleSheet().addRule("v\\:*","behavior: url(#default#VML);");
}if(a<=8){this._convertToVML(this.get_element());
}}},_convertToVML:function(a){var d=this._createVmlWrapper(a);
a.appendChild(d);
var b=a.getElementsByTagName("svg")[0];
var c=null;
if(b.getElementsByTagName("path").length>0){c=this._getQRCodeVML(a,d);
}else{c=this._getBarcodeVML(a,d);
}d.innerHTML=c;
b.style.display="none";
},_getQRCodeVML:function(a,j){var f=a.getElementsByTagName("svg")[0];
var d=f.getElementsByTagName("path")[0];
var e=0;
if(f.getAttribute("width")=="100%"){e=Math.min(a.offsetHeight,a.offsetWidth);
}else{e=parseInt(f.getAttribute("width"),10);
}var k="<v:shape strokecolor='black' filled='True' strokeweight='0' coordorigin='0 0' fillcolor='black' style='position: absolute;left:0px;top:0px;width:"+e+"px;height:"+e+"px;'";
var g=d.getAttribute("d").split(" ");
var h=parseInt(f.getAttribute("viewBox").split(" ")[3],10);
var c=h;
k+="coordsize='";
k+=h*e;
k+=",";
k+=h*e;
k+="'path='";
for(var b=0;
b<g.length-5;
b+=5){var l=parseInt(g[b+1],10);
var n=parseInt(g[b+2],10);
var m=parseInt(g[b+3],10);
var o=parseInt(g[b+4],10);
if(l==m){l--;
m++;
}else{n--;
o++;
}l=l*e;
m=m*e-c;
n=n*e;
o=o*e-c;
k+="m "+l+","+n+"l"+m+","+n+","+m+","+o+","+l+","+o+"x e";
}k+="' > </v:shape>";
return k;
},_getBarcodeVML:function(b,c){var d="";
d+=this._getRectanglesVmlHtml(b);
var a=[];
d+=this._getTextVmlHtml(b,a);
c.innerHTML=d;
this._refreshTextBoxPositions(c,a);
return d;
},_getRectanglesVmlHtml:function(a){var e=a.getElementsByTagName("svg")[0];
var d=e.getElementsByTagName("rect");
var b="";
for(var c=0;
c<d.length;
c++){b+=this._getVmlShapeHtmlFromSvgRectangle(d[c],a.offsetWidth,a.offsetHeight);
}return b;
},_getVmlShapeHtmlFromSvgRectangle:function(a,h,g){var f="<v:shape fillcolor='black' path='m 0,0 l 0,100, 100,100, 100,0 x e' coordsize='100,100' style='position: absolute;left:";
var c=this._convertPercentageStringToFloat(a.x);
var e=this._convertPercentageStringToFloat(a.width);
var b=this._convertPercentageStringToFloat(a.height);
var d=this._convertPercentageStringToFloat(a.y);
f+=c*h*0.01;
f+="px;top:";
f+=d*g*0.01;
f+="px;width:";
f+=e*h*0.01;
f+="px;height:";
f+=b*g*0.01;
f+="px;'></v:shape>";
return f;
},_getTextVmlHtml:function(b,a){var e=b.getElementsByTagName("svg")[0];
var g=e.getElementsByTagName("text");
var f=null;
var c="";
for(var d=0;
d<g.length;
d++){f=g[d];
a.push(f.getAttribute("text-anchor"));
c+=this._getVmlTextboxHtmlFromSvgText(f,b.offsetWidth,b.offsetHeight);
}return c;
},_getVmlTextboxHtmlFromSvgText:function(a,d,c){var e=this._convertPercentageStringToFloat(a.x);
var f=this._convertPercentageStringToFloat(a.y);
var b="<v:textbox";
b+=" style='position: absolute;left: ";
b+=e*d*0.01;
b+="px;top: ";
b+=f*c*0.01;
b+="px;'";
b+=">";
b+=a.innerHTML;
b+="</v:textbox>";
return b;
},_refreshTextBoxPositions:function(g,b){var e=g.getElementsByTagName("textbox");
for(var c=0;
c<e.length;
c++){var d=e[c];
var f=d.style;
var h=this._convertPixelsStringToFloat(f.left);
var j=this._convertPixelsStringToFloat(f.top);
var a=b[c];
if(a=="middle"){f.left=h-d.offsetWidth/2;
}else{if(a=="end"){f.left=h-d.offsetWidth;
}}f.top=j-d.offsetHeight/2-5;
}},_createVmlWrapper:function(a){var b=document.createElement("span");
var c=b.style;
c.position="absolute";
c.width=a.offsetWidth;
c.height=a.offsetHeight;
return b;
},_convertPercentageStringToFloat:function(a){return this._convertStringToFloat(a,"%");
},_convertPixelsStringToFloat:function(a){return this._convertStringToFloat(a,"px");
},_convertStringToFloat:function(c,a){if(typeof(c)!="string"){c=c.toString();
}var b;
if(typeof(a)=="undefined"||a==null){b=c.substring(0,c.lastIndexOf("%"));
}else{b=c;
}b=parseFloat(b);
return b;
}};
Telerik.Web.UI.RadBarcode.registerClass("Telerik.Web.UI.RadBarcode",Sys.UI.Control);
if(document.documentMode==8&&((typeof window.RadBarcodeDoNotOverrideDocument=="undefined")||window.RadBarcodeDoNotOverrideDocument)){document.writeln('<?import namespace="v" implementation="#default#VML" ?>');
}if(typeof(Sys)!=="undefined"){Sys.Application.notifyScriptLoaded();
}