Type.registerNamespace("Telerik.Web.UI");
(function(a,b){a.PivotGridContextMenu=function(){a.PivotGridContextMenu.initializeBase(this);
this._owner=null;
this._contextMenu=null;
this._isFirstWindowShow=true;
this._onContextMenuDelegate=null;
this._onClickDelegate=null;
this._onFieldsWindowContextMenuDelegate=null;
this._onFieldsWindowClickDelegate=null;
};
a.PivotGridContextMenu.prototype={initialize:function(){a.PivotGridContextMenu.callBaseMethod(this,"initialize");
var e=this._owner;
this._onContextMenuDelegate=$telerik.addMobileHandler(this,e.get_element(),"contextmenu",this._onContextMenuHandler);
this._onClickDelegate=$telerik.addMobileHandler(this,e.get_element(),"click",this._onClickHandler);
var c=this._contextMenu=$find(String.format("{0}_{1}",e.get_id(),"ContextMenu"));
var g=this;
c.add_showing(function(i,h){e.raise_menuShowing(a.PivotGrid.BuildEventArgs(new Sys.EventArgs(),{menu:i,menuArguments:h}));
});
c.add_shown(function(i,h){e.raise_menuShown(a.PivotGrid.BuildEventArgs(new Sys.EventArgs(),{menu:i,menuArguments:h}));
});
c.add_itemClicked(function(i,h){g._handleItemClick.call(g,i,h);
});
var d=e.get_fieldsWindow();
if(d){d.add_resizeEnd(function(){e.updateClientState();
});
d.add_dragEnd(function(){e.updateClientState();
});
var f=c.findItemByValue("ShowHideFieldsWindow");
d.add_show(function(i){e.updateClientState();
var h=e.get_configurationPanel();
if(!h||h.get_element().parentNode.className.indexOf("rpgFieldsWindow")==-1){if(e._dragging){e._dragging._attachFieldsWindowEvent();
}}else{if(h._enableFieldsContextMenu){g._onFieldsWindowContextMenuDelegates=$telerik.addMobileHandler(g,i.get_contentElement(),"contextmenu",g._onContextMenuHandler);
}g._onFieldsWindowClickDelegate=$telerik.addMobileHandler(g,i.get_contentElement(),"click",g._onClickHandler);
}g._isFirstWindowShow=false;
f.set_text(e._hideFieldsWindowText);
});
d.add_close(function(){e.updateClientState();
g._isFirstWindowShow=false;
f.set_text(e._showFieldsWindowText);
});
}},dispose:function(){if(this._onContextMenuDelegate){$telerik.removeMobileHandler(document,"contextmenu",this._onContextMenuDelegate,null,true);
}if(this._onClickDelegate){$telerik.removeMobileHandler(document,"click",this._onClickDelegate,null,true);
}if(this._onFieldsWindowContextMenuDelegate){$telerik.removeMobileHandler(document,"contextmenu",this._onFieldsWindowContextMenuDelegate,null,true);
}if(this._onFieldsWindowClickDelegate){$telerik.removeMobileHandler(document,"click",this._onFieldsWindowClickDelegate,null,true);
}a.PivotGridContextMenu.callBaseMethod(this,"dispose");
},get_owner:function(){return this._owner;
},set__owner:function(c){this._owner=c;
},_onContextMenuHandler:function(g){var f=a.PivotGrid.GetTouchCurrentElement(g),j=this._owner,i=j._searchForFieldFromElement(f),d=j.get_configurationPanel();
i=a.PivotGridField.isInstanceOfType(i)?i:null;
if(i==null){var c=f.className;
if(c.indexOf("rpgFilterZone")!=-1||c.indexOf("rpgDataZone")!=-1||c.indexOf("rpgColumnsZone")!=-1||c.indexOf("rpgRowsZone")!=-1||f.id.endsWith("_DropFieldHereCell")){this._showZoneContextMenu(g);
}else{if(j._olapExtension&&d._enableFieldsContextMenu){var h=j._olapExtension;
var k=h.treeView._extractNodeFromDomElement(a.PivotGrid.GetTouchCurrentElement(g));
i=h.getFieldFromNode(k);
if(i){i._isTreeViewFieldTarget=true;
g.target=i.get_element();
this._showConfigurationPanelFieldsMenu(g,i,true);
}}}}else{if(!i._isConfigurationPanelField){this._showFieldContextMenu(g,i);
}else{if(d&&d._enableFieldsContextMenu){this._showConfigurationPanelFieldsMenu(g,i);
}}}},_onClickHandler:function(f){var d=a.PivotGrid.GetTouchCurrentElement(f);
var c=d.className;
if(c&&c.indexOf("rpgChangeLayout")!=-1){this._showConfigurationPanelMenu(f);
}else{var g=this._owner._searchForFieldFromElement(d);
if(c&&c.indexOf("rpgItemContextMenu")!=-1){this._showConfigurationPanelFieldsMenu(f,g);
}}},_showZoneContextMenu:function(c){var d={Refresh:true,ZoneSeparator:true,ShowHideFieldsWindow:true};
if(this._setContextMenuItemsVisibility(d)>0){this._contextMenu.show(c);
}},_showFieldContextMenu:function(c,d){var f={Refresh:true,ZoneSeparator:true,ShowHideFieldsWindow:true,HideField:true,ZoneSummarizeBySettings:d.get_zoneType()==a.PivotGridFieldZoneType.Aggregate};
this._setContextMenuItemsVisibility(f);
this._contextMenu.show(c);
},_showConfigurationPanelMenu:function(d){var j={Stacked:true,SideBySide:true,TwoByTwo:true,OneByFour:true};
var i=this;
var c=i._contextMenu;
i._setContextMenuItemsVisibility(j);
var h=i._owner.get_configurationPanel().get_layoutType();
c.show(d);
for(var g in a.PivotGridConfigurationPanelLayoutType){var f=c.findItemByValue(g);
if(f){if(a.PivotGridConfigurationPanelLayoutType[g]==h){f.set_focused(true);
}else{f.set_focused(false);
}}}},_showConfigurationPanelFieldsMenu:function(c,d,f){var l=true,g=true;
if(d.get_previousField()==null){l="disable";
}if(d.get_nextField()==null){g="disable";
}var j=true,k=true,i=true,h=true,m=false;
switch(d.get_zoneType()){case a.PivotGridFieldZoneType.Filter:j="disable";
break;
case a.PivotGridFieldZoneType.Aggregate:h="disable";
m=true;
break;
case a.PivotGridFieldZoneType.Column:i="disable";
break;
case a.PivotGridFieldZoneType.Row:k="disable";
break;
}f=f||d.get_id().endsWith(String.format("_{0}_Hidden",d.get_uniqueName()));
var o={MoveUp:f?false:l,MoveDown:f?false:g,MoveToBeginning:f?false:l,MoveToEnd:f?false:g,ConfigurationPanelSeparator1:!f,MoveToFilterFields:d._isHidden?true:j,MoveToRowFields:d._isHidden?true:k,MoveToColumnFields:d._isHidden?true:i,MoveToAggregateFields:d._isHidden?true:h,ConfigurationPanelSeparator2:!f,HideField:f?false:true,ConfigurationPanelSeparator3:m,SummarizeBySettings:m};
var n=this;
n._setContextMenuItemsVisibility(o);
n._contextMenu.show(c);
},_setContextMenuItemsVisibility:function(h){var c=this._contextMenu;
var g=c.get_items();
var d=g.get_count();
var j=0;
for(var e=0;
e<d;
e++){var f=g.getItem(e);
if(h[f.get_value()]){f.set_visible(true);
j++;
if(h[f.get_value()]=="disable"){f.set_enabled(false);
}else{f.set_enabled(true);
}}else{f.set_visible(false);
}}return j;
},_handleItemClick:function(j,c){var g=c.get_item().get_value();
var h=this._owner;
var k;
var d;
switch(g){case"Refresh":h.rebind();
break;
case"Hide":k=c.get_targetElement();
d=h._getField(k);
if(d==null){d=h._getField(k.parentNode);
}if(d!=null){d.hide();
}break;
case"ZoneSummarizeBySettings":k=c.get_targetElement();
d=h._getField(k);
if(d==null){d=h._getField(k.parentNode);
}this.get_owner().get_fieldSettings().displayFieldSettingsWindow(d);
break;
case"SummarizeBySettings":k=c.get_targetElement();
d=h._getField(k);
if(d==null){d=h._getField(k.parentNode);
}this.get_owner().get_fieldSettings().displayFieldSettingsWindow(d);
break;
case"ShowHideFieldsWindow":var e=h.get_fieldsWindow();
if(e.isVisible()){e.close();
}else{if(this._isFirstWindowShow&&(e.get_top()==null||e.get_left()==null)){var i=$telerik.getDocumentRelativeCursorPosition(c.get_domEvent());
e.moveTo(i.left,i.top);
}e.show(c.get_domEvent());
}break;
}if(g=="Stacked"||g=="SideBySide"||g=="TwoByTwo"||g=="OneByFour"){c.get_item().set_focused(true);
h.get_configurationPanel().set_layoutType(a.PivotGridConfigurationPanelLayoutType[g]);
}else{if(g=="MoveUp"||g=="MoveDown"||g=="MoveToBeginning"||g=="MoveToEnd"||g=="MoveToFilterFields"||g=="MoveToRowFields"||g=="MoveToColumnFields"||g=="MoveToAggregateFields"||g=="HideField"){var f="_"+g.charAt(0).toLowerCase()+g.substring(1);
h.get_configurationPanel()[f](h._searchForFieldFromElement(c.get_targetElement()));
}}}};
a.PivotGridContextMenu.registerClass("Telerik.Web.UI.PivotGridContextMenu",Sys.Component);
})(Telerik.Web.UI);
